### ISSUE TITLE
Defining webroot for services

### ISSUE THREAD

**Issue by skippednote** [lando/lando#1012]
`.lando.yml`
```yml
name: proj
recipe: drupal8
config:
  webroot: docroot
  xdebug: true
  conf:
    php: .lando/php.ini
services:
  node:
    type: node:8
    globals:
      gulp-cli: "latest"
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
  npm:
    service: node
  gulp:
    service: node
```

This is a Drupal 8 project. Now if I want to run a gulp inside my theme directory which is located at `/app/docroot/themes/custom/mytheme` I'd normally do `lando gulp` but it throws the following error:
`Local gulp not found in /app`. I tried setting `webroot` for the node service but it doesn't seem to work.

- Is there a way to define webroot for a service?
- Is there a better way that I'm missing regarding how to run commands for projects that aren't at the root of the project.
