### ISSUE TITLE
Lando start always installs wp-cli, node, npm, gulp, bower etc

### ISSUE THREAD

**Issue by edwinsiebel** [lando/lando#1021]
**Tell us about your setup**
* version: v3.0.0-beta.47 on Ubuntu 16.04

**Tell us about your `.lando.yml`**
```yml
name: name
recipe: wordpress

config:
    # PHP version 7.0
    type: php:7.0

    # Served by the latest nginx
    via: nginx:1.13

    # Optionally serve php over https
    ssl: true

    # Optionally specify a webroot if it is a subdirectory of the appRoot
    webroot: htdocs

    # Optionally activate xdebug
    #
    # If you are having trouble getting xdebug to work please see:
    # https://docs.devwithlando.io/services/php.html#using-xdebug
    xdebug: true

    conf:
      # Use a custom nginx config file
      server: provision/nginx/default.conf

# Proxy to allow for nice urls
proxy:
  web:
  mailhog:
    - mail.name.lndo.site
  pma:
    - pma.name.lndo.site

services:
  # Add a phpmyadmin db frontend
  pma:
    # Use the latest version of phpmyadmin
    type: phpmyadmin:4.6
    # Optionally serve php over https
    ssl: true
    hosts:
      - database

  # Spin up a mailhog container called "mailhog"
  mailhog:
    # Use the latest mailhog version
    type: mailhog

    # List of services that we want to capture mail from
    # You can run `lando info` to get a list of services that are available
    # Mailhog expects that these services will be php services
    hogfrom:
      - appserver

  database:
    type: mariadb
    config:
      # Data settings
      confd: provision/mysql

  appserver:
    run:
      - cd $LANDO_MOUNT && composer install

    overrides:
      services:
        environment:
          environment: 'development'
          DB_HOST: 'database'

    config:
      # Use a custom php.ini
      # This **should** load last which means you should be able to override
      # any previously set php settings.
      conf: provision/php/php.ini

    environment:
      - environment=development
      - DB_HOST=database

  node:
    # Node version 6.10
    type: node:6.10

    # Note that most deps should be installed by the normal npm install, this is
    # for things like gulp/grunt cli that are global dependencies
    globals:
      gulp-cli: "latest"
      bower: "latest"
      webpack: "latest"
      npm: "latest"

tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"

  gulp:
    service: node
  bower:
    service: node
  npm:
    service: node
  node:
    service: node
```

**Tell us about the error you got**

Everything I do a lando start, it unnecessary installs wp-cli, npm, node, gulp, bower. See [lando.log](https://github.com/lando/lando/files/2085236/lando.log).

Can this be disabled and only be done when doing a lando rebuild, which makes more sense?

Or can I change something to the lando config file, to disable this repeated installations?

thanks
