### ISSUE TITLE
Cannot override nginx port

### ISSUE THREAD

**Issue by erichomanchuk** [lando/lando#1037]
Version: v3.0.0-beta.47 on macOS High Sierra Version 10.13.5

This is a similar issue to one that has already been reported and closed [here](https://github.com/lando/lando/issues/359). I am trying to override the port for the appserver to allow browserSync to work on a drupal8/nginx  build.

I can get browserSync to work if I use the apache server. But when I switch to nginx it breaks and throws the error below multiple times for both the 3000 and 3001 ports. 

```bash
ERROR: for 58b4efc33ce7_fpm_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint fpm_nginx_1 (4afb21b2a4804c09b32309bfba8577607fb09e854a610a2440d4edb7ec6968a8): Bind for 0.0.0.0:3001 failed: port is already allocated
```

I think the issue comes because of the php version used for nginx. Looking at the docker containers I can see that the ports 3000, 3001 got assigned to the  appserver/php container.

```bash
ab5b408781f7        fosterinteractive/docker-mainspring-php-pl:1.0-fpm   "/lando-entrypoint.s…"   59 seconds ago      Up About a minute             0.0.0.0:3000-3001->3000-3001/tcp, 9000/tcp                          fpm_appserver_1
62089e445c10        mariadb:10.1                                         "/lando-entrypoint.s…"   59 seconds ago      Up About a minute (healthy)   0.0.0.0:32787->3306/tcp                                             fpm_database_1
cd9fda2fb8ab        traefik:1.5.4-alpine                                 "/lando-entrypoint.s…"   About an hour ago   Up About a minute             0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:58086->8080/tcp   landoproxyhyperion5000gandalfedition_proxy_1
```

```yml
name: fpm
recipe: drupal8
config:
  # Optionally specify a webroot if it is a subdirectory of the appRoot
  webroot: web

  via: nginx

  database: mariadb:10.1

services:
  appserver:
    type: php:custom
    overrides:
      services:
        # Use custom php imag eto include node in our appserver to run patternlab
        image: fosterinteractive/docker-mainspring-php-pl:1.0-fpm
        # Make the default browsersync ports available.
        ports:
          - 3000:3000
          - 3001:3001
    run_as_root:
      - "cd $LANDO_WEBROOT/themes/mainspring && npm run init"

tooling:
  npm:
    service: appserver
  node:
    service: appserver
  gulp:
    service: appserver
  composer:
    service: appserver

```
If I just use the default drupal8 recipe and switch to nginx server I can get the same errors.

```yaml
name: fpm
recipe: drupal8
config:
  # Optionally specify a webroot if it is a subdirectory of the appRoot
  webroot: web

  via: nginx

services:
  appserver:
    type: php:7.1
    overrides:
      services:
        # Make the default browsersync ports available.
        ports:
          - 3000:3000
          - 3001:3001
```
I can see that the ports have been assigned to the container devwithlando/php:7.1-fpm so they cant be assigned to the nginx container which doesn't start.

```bash
CONTAINER ID        IMAGE                      COMMAND                  CREATED              STATUS                        PORTS                                                               NAMES
0cfff90d5e7e        mysql:5.7                  "/lando-entrypoint.s…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:32788->3306/tcp                                             fpm_database_1
e41acc1089de        devwithlando/php:7.1-fpm   "/lando-entrypoint.s…"   About a minute ago   Up About a minute             0.0.0.0:3000-3001->3000-3001/tcp, 9000/tcp                          fpm_appserver_1
cd9fda2fb8ab        traefik:1.5.4-alpine       "/lando-entrypoint.s…"   About an hour ago    Up About a minute             0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:58086->8080/tcp   landoproxyhyperion5000gandalfedition_proxy_1
```
I guess the question that Im asking is if its possible to add the port overrides to the nginx service from this type of build.  I guess everything works nicely with the apache build because its included in the container with php.

Thanks.

**Comment by jbertoen** [comment]
Your issue is a little different I think, but I can gladly announce that it is probably fixed in master. At least I hope, if your issue is some what similar to mine.
https://github.com/lando/lando/issues/1024

The thing is that currently in beta47 one container can only have one set of urls mapped to a container (for onlye one port, with the exception of 443). So in your case, 80, 3000 or 3001. Not all three.

To assign a url to a port different to the :80 default, you have to add that port to the url in the proxy.

With the fix in issue #1024 you can do the following:
```
name: fpm
recipe: drupal8
proxy:
  nginx:
    - fpm.localhost
    - browsersync3000.localhost:3000
    - browsersync3001.localhost:3001
config:
  # Optionally specify a webroot if it is a subdirectory of the appRoot
  webroot: web

  via: nginx

  database: mariadb:10.1

services:
  appserver:
    type: php:custom
    overrides:
      services:
        # Use custom php imag eto include node in our appserver to run patternlab
        image: fosterinteractive/docker-mainspring-php-pl:1.0-fpm
        # Make the default browsersync ports available.
        ports:
          - 3000:3000
          - 3001:3001
        expose:
          - 3000:3000
          - 3001:3001
    run_as_root:
      - "cd $LANDO_WEBROOT/themes/mainspring && npm run init"
```
Although I do not know for sure if the expose option is needed. But this worked for my node container to expose multiple apps on different ports.
