### ISSUE TITLE
Extra "app" symlink showing up in project after a rebuild

### ISSUE THREAD

**Issue by bmcclure** [lando/lando#1043]
Bug Report
==========

**Tell us about your setup**

v3.0.0-beta.47 on elementaryOS Loki

**Tell us about your `.lando.yml`**

```yml
name: mysite
recipe: pantheon
config:
  framework: drupal
  env: dev
  site: mysite
  id: c4d05745-2c4a-4127-9b54-2a09905a5292
  xdebug: true
```
pantheon.yml:
```yml
api_version: 1
php_version: 7.0
drush_version: 8
```

**Tell us about the command you were running**

```bash
lando rebuild -y
```

**Tell us about the error you got**

In this case, there is no error, but just an extra symlink showing up in the code.

**Tell us generally about your bug**

It seems like rebuilding the app as of one of the most recent Lando releases also adds a new "app" symlink to the code directory which points to `/app`. It shows up as a new file in the git repository and is easy to accidentally commit if you don't watch out for it. Deleting the file doesn't seem to break anything.
