### ISSUE TITLE
Lando hangs on lando build, seems it can't verify that web containers are running?

### ISSUE THREAD

**Issue by wesruv** [lando/lando#1044]
Bug Report
==========

**Tell us about your setup**
What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**
* lando version v3.0.0-beta.47
* Ubuntu 16.04.4 LTS (GNU/Linux 4.13.0-45-generic x86_64)

**Tell us about your `.lando.yml`**
```yml
name: backdrop-core
recipe: backdrop
config:
  webroot: docroot
  via: apache
  php: '7.2'
  database: mysql:5.7
  xdebug: true
proxy:
  appserver:
    - local.core.backdrop.com
```

No special config

**Tell us about the command you were running**
This happens on build, it seems that everything builds properly, when I run with vvv I can see https isn't reporting back, but it is working when I hit it in my browser.

Here's the log of what's happening, with the line number of where it starts to get goofy:
https://gist.github.com/wesruv/12e09b15b15ac3befcd91abbd808de79#file-shelloutput-L540

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
Without verbose, the last message I see is:
```
'drush' cache was cleared.                                                                                                                                                                                                                           [success]
```

Which was really confusing, be nice if it told me it was waiting for containers to respond, but I guess I figured it out.


Does this bug prevent you from using lando?
No, but it's weird.
