### ISSUE TITLE
Add Acquia Cloud recipe

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#105]
Create a recipe that simulates the Acquia Cloud environment.

Stack foundation:
- Ubuntu Xenial (16.04 LTS)
- Apache/2.2.22
- mysql  Ver 14.14 Distrib 5.6.32-78.1
- PHP 5.6.30

Configuration:
- Generate ssh keypair
- Install drush aliases

Other projects that may help assist with the recipe:
- https://github.com/ciandt-dev/Docker4Acquia
- https://github.com/geerlingguy/acquia-cloud-api-scripts

**Comment by nalipaz** [comment]
Here is a go at the acquia docker images that I created when they were still on 12.04 I believe:

https://github.com/heremedia/acquia

**Comment by uberhacker** [comment]
@nalipaz: Nice!  I imagine upgrading to 16.04 is not difficult.  From what I understand, they did not change the versions of php, mysql and apache.  The ultimate goal here is to provide the tools necessary to interact with their api.

**Comment by pirog** [comment]
yeah i think dropping the right containers shouldnt be too tricky and is easy enough to replicate by using the pantehon recipe as a start state. the bigger thing is going to be what @uberhacker which is getting that nice integration with their API

**Comment by nalipaz** [comment]
Here is a link to what they document their servers as using:
https://docs.acquia.com/acquia-cloud/arch/tech-platform

**Comment by pirog** [comment]
Yeah nice and i think you can probably get at least a non-integrative pseudo recipe for this using currently existing lando mechanisms eg something like this, havent tested this, just giving you an idea of where to start if you wanted to get this rolling

```yml
name: acquia

# reroute the main url through varnish
proxy:
  appserver:
  varnish:
    - acquia.lndo.site

# start with basic lamp recipe
recipe: lamp
config:
  php: 7.1 # or other as appropriate
  # modify webroot sub dir as needed
  # webroot: docroot 
  database: mysql:5.6
edge:
    type: varnish:4.1
    backends:
      - appserver
    ssl: true
cache:
  type: memcached:1.4
```

**Comment by kevwalsh** [comment]
I just came across this approach to using Lando with BLT for acquia cloud: https://thinktandem.io/blog/2017/12/09/lando-blt-acquia/

**Comment by dsdobrzynski** [comment]
I am setting this up and implementing BLT. This is my `.lando.yml` that is working:

```yaml
name: acquia

# Start with the default Drupal 8 recipe
recipe: drupal8

# add in the varnish edge
proxy:

  # Empty the proxy settings provided by drupal8 recipe
  nginx:

  edge:
    - edge.acquia.lndo.site

# Configure the Drupal8 recipe
config:

  # See: https://www.drupal.org/docs/8/system-requirements

  # Optionally specify the php version to use.
  #
  # If ommitted this will default to the latest php version supported by Drupal 8.
  # Consult the `php` service to see what versions are available. Note that all
  # such versions may not be supported in Drupal 8s so YMMV.
  #
  # See: https://www.drupal.org/docs/8/system-requirements/php
  #
  # NOTE: that this needs to be wrapped in quotes so that it is a string
  #
  php: '7.1'

  # Optionally specify whether you want to serve drupal via nginx or apache
  #
  # If ommitted this will default to the latest apache
  #
  # See: https://www.drupal.org/docs/8/system-requirements/web-server
  #
  via: apache:2.4

  # Optionally specify the location of the webroot relative to your approot.
  #
  # If ommitted this will be your approot itself.
  #
  webroot: docroot

  # Optionally specify how you want Lando to handle Drush. There are a few options
  #
  # If omitted this will install the Drush Launcher and assume you've installed a
  # site-local version of Drush with Composer
  #
  # You can also configure it in the following ways:
  #
  # 1. Install via Composer
  #
  # This will install the Drush Launcher (https://github.com/drush-ops/drush-launcher)
  # and will delegate to the site-local version of Drush you've installed with Composer
  # http://docs.drush.org/en/master/install/
  # drush: composer
  #
  # 2. Install Globally
  #
  # This will globally install the corresponding Drush 8 PHAR posted over at
  # https://github.com/drush-ops/drush/releases
  # drush: global:8.1.12
  #
  # This will ATTEMPT to globally install any pre Drush 8 versions via Composer
  # drush: global:~7
  #
  # 3. Specify a path
  #
  # This assumes the user has already installed Drush but wishes to tell Lando where
  # it exists.
  # drush: path:/app/vendor/bin/drush
  #
  # 4. Do nothing
  #
  # This will tell Lando to not do anything, e.g. it's up to the user
  # drush: false
  #
  drush: composer

  # Optionally specify whether you want to disable the global install of drupal console.
  #
  # You should also consider a site-local install of drupal console via composer
  #
  # See: https://hechoendrupal.gitbooks.io/drupal-console/content/en/getting/composer.html
  #
  drupal: false

  # Optionally specify the database type, this can be one of:
  #
  #   - `mysql`
  #   - `mariadb`
  #   - `postgres`
  #
  # If ommitted this will default to the latest mysql. You can additionally provide
  # a version with `type:version` but you will need to consult the documentation
  # for the correct DB service to see what versions are available
  #
  # see: https://www.drupal.org/docs/8/system-requirements/database-server
  #
  database: mysql:5.6

  # Optionally activate xdebug
  #
  # If you are having trouble getting xdebug to work please see:
  # https://docs.devwithlando.io/services/php.html#using-xdebug
  xdebug: true

  # Optionally mix in your own config files
  #
  # If ommitted this will use "sane defaults" for your recipe type
  # conf:

  # For more information on setting these files check out the documentation
  # and examples
  #
  # Docs: https://docs.devwithlando.io/services/php.html
  # Examples: https://github.com/lando/lando/tree/master/examples
  #
  # server: config/drupal8.conf
  # php: config/php.ini

  # For more information on setting these files check out the documentation
  # and examples for the relevant services:
  #
  # MySQL: https://docs.devwithlando.io/services/mysql.html
  # MariaDB: https://docs.devwithlando.io/services/mariadb.html
  # PostGres: https://docs.devwithlando.io/services/postgres.html
  #
  # Examples: https://github.com/lando/lando/tree/master/examples
  #
  # database: config/mysql

# add additional auxiliary services
services:

  # set up a Varnish edge
  edge:
    type: varnish:4.1
    backends:
      - appserver

    # Optionally spin up another nginx instance so that you can secure your
    # traffic over ssl
    #
    # The varnish ssl service will be called NAME_ssl, or edge_ssl in this
    # example
    #
    ssl: true

    # Optionally load in a custom vcl file. This is relative to the app root
    #
    # You will not need to import the standard library or manage backends in this
    # file. Those are handled automatically.
    #
    # vcl: custom.vcl

    # There are various envvars you can specify to further customize how your
    # varnish works.
    #
    # See: https://hub.docker.com/r/eeacms/varnish/
    # Note: We set BACKENDS_PROBE_ENABLED to false by default
    #
    # overrides:
      # services:
        # environment:
          # BACKENDS_PROBE_ENABLED: false
          # BACKENDS_PORT: 8080
          # DNS_ENABLED: true
          # BACKENDS_PROBE_INTERVAL: 3s
          # BACKENDS_PROBE_TIMEOUT: 1s
          # BACKENDS_PROBE_WINDOW: 3
          # BACKENDS_PROBE_THRESHOLD: 2

  # set up Memcached cache
  cache:
    type: memcached:2.2

tooling:
  # Add in BLT command
  blt:
    service: appserver
    cmd: /usr/bin/blt

  # Add in routes to the varnish cli tools
  varnishadm:
    service: edge
    user: root
  varnishstat:
    service: edge
    user: root
  varnishlog:
    service: edge
    user: root
```
