### ISSUE TITLE
Empty "tooling:" key  in .lando.yml file prevents recipe tooling from loading.

### ISSUE THREAD

**Issue by Mvannes** [lando/lando#1051]
Bug Report
==========

Before we begin, here is some basic version information regarding the OS, lando, and docker.
**OS Version:**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
```
**Lando version:**
```
v3.0.0-beta.47
```
**Docker version:**
```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:16:34 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:14:43 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

Going into the actual issue:
Adding an empty `tooling:` key to a `.lando.yml` file seems to remove all tooling added from a recipe. 
The following `.lando.yml` file works correctly:

```yml
name: broken-tooling
recipe: drupal8
proxy:
  nginx:
    - test.localhost
config:
  php: '7.1'
  webroot: web
  via: nginx
  xdebug: false
  conf:
    php: config/develop/php/php.ini

services:
  appserver:
    overrides:
       services:
         volumes:
           - /app/vendor/
    build:
      - "mkdir -p ~/.drush/alias"
      - "ln -sf /app/drush/alias/test.aliases.drushrc.php ~/.drush/alias/build-umami.aliases.drushrc.php"

# NOTE HERE: commented tooling: key
#tooling:
events:
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cr -y && drush cim -y

  post-start:
     - appserver: composer global require hirak/prestissimo
     - appserver: cd $LANDO_MOUNT && composer install
```

If we go to this dir on our terminal and run `lando`, the following output is given:  

```
Usage: lando <command> [args] [options] [-- global options]

Commands:
  composer                 Run composer commands
  config                   Display the lando configuration
  db-export [file]         Export database from a service
  db-import [file]         Import <file> into database service
  destroy [appname]        Destroy app in current directory or
                           [appname]
  drupal                   Run drupal console commands
  drush                    Run drush commands
  info [appname]           Prints info about app in current
                           directory or [appname]
  init [method]            Initialize a lando app, optional
                           methods: github, pantheon
  list                     List all lando apps
  logs [appname]           Get logs for app in current
                           directory or [appname]
  mysql                    Drop into a MySQL shell on a
                           database service
  php                      Run php commands
  poweroff                 Spin down all lando related
                           containers
  rebuild [appname]        Rebuilds app in current directory
                           or [appname]
  restart [appname]        Restarts app in current directory
                           or [appname]
  share [appname]          Get a publicly available url
  ssh [appname] [service]  SSH into [service] in current app
                           directory or [appname]
  start [appname]          Start app in current directory or
                           [appname]
  stop [appname]           Stops app in current directory or
                           [appname]
  version                  Display the lando version

Global Options:
  --help, -h  Show help
  --verbose, -v, -vv, -vvv, -vvvv  Change verbosity of output

You need at least one command before moving on
```

If however we change our file to look as follows:
```yml
name: broken-tooling
recipe: drupal8
proxy:
  nginx:
    - test.localhost
config:
  php: '7.1'
  webroot: web
  via: nginx
  xdebug: false
  conf:
    php: config/develop/php/php.ini

services:
  appserver:
    overrides:
       services:
         volumes:
           - /app/vendor/
    build:
      - "mkdir -p ~/.drush/alias"
      - "ln -sf /app/drush/alias/test.aliases.drushrc.php ~/.drush/alias/build-umami.aliases.drushrc.php"

# NOTE HERE: uncommented tooling: key
tooling:
events:
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cr -y && drush cim -y

  post-start:
     - appserver: composer global require hirak/prestissimo
     - appserver: cd $LANDO_MOUNT && composer install
```
The following output is given instead when run `lando` in the dir:
```
Usage: lando <command> [args] [options] [-- global options]

Commands:
  config                   Display the lando configuration
  destroy [appname]        Destroy app in current directory or
                           [appname]
  info [appname]           Prints info about app in current
                           directory or [appname]
  init [method]            Initialize a lando app, optional
                           methods: github, pantheon
  list                     List all lando apps
  logs [appname]           Get logs for app in current
                           directory or [appname]
  poweroff                 Spin down all lando related
                           containers
  rebuild [appname]        Rebuilds app in current directory
                           or [appname]
  restart [appname]        Restarts app in current directory
                           or [appname]
  share [appname]          Get a publicly available url
  ssh [appname] [service]  SSH into [service] in current app
                           directory or [appname]
  start [appname]          Start app in current directory or
                           [appname]
  stop [appname]           Stops app in current directory or
                           [appname]
  version                  Display the lando version

Global Options:
  --help, -h  Show help
  --verbose, -v, -vv, -vvv, -vvvv  Change verbosity of output

You need at least one command before moving on
```
Note that all the tooling commands from our recipe have disappeared. 
This is still valid yml, and changing our `tooling:` key to look like `tooling: ~` instead will still remove the recipe's tooling.
This feels like its an issue that occurs due to some merging that fails when the `tooling:` key is empty, but I am not well versed enough in how Lando works to properly solve this myself.

**Steps to reproduce:**
1. Create a `.lando.yml` file somewhere that uses a recipe (drupal8 if you want to reproduce exactly) with tooling.
2. Ensure that the `.lando.yml` file contains an empty `tooling:` key, or a `tooling: ~` key value pair. 
3. Run `lando` to see the available commands. 
4. Note that the recipe's tooling is absent.

I am aware that it is not often that one will have an empty tooling key. But there are times when this happens during active development, such as when caching tools like Varnish are turned on and off by commenting out their tooling. 
As this is valid Yaml, I feel like Lando should be able to properly resolve the empty tooling key without removing the recipe's tooling.
