### ISSUE TITLE
Laravel Dusk does not work with the Laravel recipe.

### ISSUE THREAD

**Issue by colynb** [lando/lando#1052]
I installed Laravel Dusk according to the Laravel documentation and have an app running using Lando and everything is working as expected except when I run my dusk tests.

```
> lando artisan dusk
```

results in this error:

```
1) Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"chrome","platform":"ANY","chromeOptions":{"binary":"","args":["--disable-gpu","--headless"]}}}

Failed to connect to localhost port 9515: Connection refused

/app/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:292
/app/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:126
/app/tests/DuskTestCase.php:39
/app/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:189
/app/vendor/laravel/framework/src/Illuminate/Support/helpers.php:768
/app/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:190
/app/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:92
/app/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:64
/app/tests/Browser/ExampleTest.php:21
```

Lando Version: v3.0.0-beta.47
Laravel Version: 5.6.25
Laravel Dusk Version: 3.0.9

**Comment by dustinleblanc** [comment]
@colynb Dusk requires chromedriver by default, you'll need to add a chromedriver service, see #360 Checkin on Slack if you need some more nuanced help getting chromedriver running, but that last comment on the issue is the magic

**Comment by tylerssn** [comment]
For others who land here:

```yaml
# Landofile
services:
  chromedriver: # For Laravel Dusk
    type: compose
    services:
      image: robcherry/docker-chromedriver:latest
      command: /usr/local/bin/supervisord -c /etc/supervisord.conf
      expose:
        - '4444'
      environment:
        CHROMEDRIVER_WHITELISTED_IPS: ""
        CHROMEDRIVER_URL_BASE: "/wd/hub"
      security_opt:
        - seccomp:unconfined
```

```env
# .env file

# Dusk
DUSK_DRIVER_URL="http://chromedriver:4444/wd/hub" # The host is defined by Lando and the Landofile service name
```

In `DuskTestCase.php > driver()`, the first value passed to `RemoteWebDriver::create()` Should be `$_ENV['DUSK_DRIVER_URL']`. Or, if you don't want to use the ENV file, just set it statically to: `http://chromedriver:4444/wd/hub`

**Comment by yobottehg** [comment]
Just as an addition. Running on an Apple Silicon mac will need the seleniarm container wo work.

Heres a working lando container and dusk setup for an M2 mac with dusk 7

```
services:
   ...
  chromedriver:
    type: compose
    services:
      image: seleniarm/standalone-chromium:111.0-chromedriver-111.0
      command: opt/bin/entry_point.sh
      expose:
        - '4444'
```

Then in `DuskTestCase.php`:

`return RemoteWebDriver::create("http://chromedriver:4444/wd/hub", ...)`
