### ISSUE TITLE
Lando not recognizing custom Solr config

### ISSUE THREAD

**Issue by duartegarin** [lando/lando#1069]
**Tell us about your setup**

v3.0.0-beta.47 and MacOS High Sierra

**Tell us about your `.lando.yml`**

```yml
# Name the application the same as in your .platform.app.yaml.
name: drupal
# Use the recipe appropriate for your application.
recipe: drupal8

# The following additional build step will install the Platform CLI
# in the application container.
services:
  appserver:
    build:
      - "curl -sS https://platform.sh/cli/installer | php"
  # Spin up a solr container called "index"
  # NOTE: "index" is arbitrary, you could just as well call this "tswift" or "covfefe"
  index:

    # Use solr version 6.6
    type: solr:6.6

    # Optionally allow access to the database at localhost:9999
    # You will need to make sure port 9999 is open on your machine
    #
    # You can also set `portforward: true` to have Lando dynamically assign
    # a port. Unlike specifying an actual port setting this to true will give you
    # a different port every time you restart your app
    portforward: 9999

    # Optionally declare the name of the solr core.
    # This setting is only applicable for versions 5.5 and above
    core: main

    # Optionally use custom solr config files eg (schema.xml and solrconfig.xml)
    # This is helpful if frameworks require custom config eg Drupal.
    # This is relative to the app root (which may be different from your webroot).
    config:
      conf: .platform/solr-conf/6.x

# The following entry creates a `lando platform` command that will run
# any Platform CLI command from inside the container if desired.
tooling:
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd:
      - /var/www/.platformsh/bin/platform

config:
  # Lando defaults to Apache. Switch to nginx to match Platform.sh.
  via: nginx

  # Set the webroot to match your .platform.app.yaml.
  webroot: drupal/web

  # Lando defaults to the latest MySQL release, but Platform.sh uses MariaDB.
  # Specify the version to match what's in services.yaml.
  database: mariadb:10.1
```

**Tell us generally about your bug**

I can't get Solr to recognize my custom solr config

It always shows using "example-data-driven-schema" instead of the drupal one.
I can confirm this by opening Solr admin UI and checking the schema is not the expected one.
