### ISSUE TITLE
curl: (60) SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by RichardDavies** [lando/lando#1071]
Bug Report
==========

**Tell us about your setup**

v3.0.0-beta.47 on Windows 10 Professional

**Tell us about your `.lando.yml`**

```yml
name: portlandor
recipe: pantheon
config:
  framework: drupal8
  site: portlandor
  id: 5c6715db-abac-4633-ada8-1c9efe354629
framework: drupal8
xdebug: true
services:
  appserver:
    xdebug: true
    config:
      conf: xdebug.ini
drush: composer
tooling:
  drush:
    service: appserver
    cmd:
      - "drush"
      - "--root=/app/web"
```

**Tell us about your `pantheon.yml`**

```yml
# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1

web_docroot: true

php_version: 7.1

# Add a comment to trigger a deploy on Pantheon
workflows:
  clear_cache:
    after:
      - type: webphp
        description: Post deployment notification to Slack
        script: private/scripts/slack_deploy_notification.php
  clone_database:
    after:
      - type: webphp
        description: Post deployment notification to Slack
        script: private/scripts/slack_deploy_notification.php
  create_cloud_development_environment:
    after:
      - type: webphp
        description: Post deployment notification to Slack
        script: private/scripts/slack_deploy_notification.php
  deploy:
    after:
      - type: webphp
        description: Post deployment notification to Slack
        script: private/scripts/slack_deploy_notification.php
  sync_code:
    after:
      - type: webphp
        description: Post deployment notification to Slack
        script: private/scripts/slack_deploy_notification.php
```

**Tell us about the command you were running**

```bash
git clone -c core.symlinks=true git@github.com:eGovPDX/portlandor.git
git config core.autocrlf false
lando start
```

**Tell us about the error you got**

```bash
lando start -- -vvvv
.
.
.
verbose: Running spawn C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe with args ["--project-name","port
landor","--file","C:\\Users\\csrichardd\\.lando\\compose\\portlandor\\portlandor-2.yml","--file","C:\\Users\\csrichardd\
\.lando\\proxy\\portlandor-proxy-3.yml","exec","--user","www-data","appserver","/bin/sh","-c","cd /tmp && curl https://g
ithub.com/drush-ops/drush/releases/download/8.1.16/drush.phar -L -o drush.phar && chmod +x drush.phar && ./drush.phar co
re-status && mv drush.phar /usr/local/bin/drush"]
debug: In mode attach with detached false
debug: With env ACLOCAL_PATH=/mingw64/share/aclocal:/usr/share/aclocal, ALLUSERSPROFILE=C:\ProgramData, APPDATA=C:\Users
\csrichardd\AppData\Roaming, ChocolateyInstall=C:\ProgramData\chocolatey, ChocolateyLastPathUpdate=Wed Jan 31 15:13:00 2
018...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599    0   599    0     0   2715      0 --:--:-- --:--:-- --:--:--  2722
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
verbose: Spawn exited with code: 60
silly: Spawn finished with
error: Looks like one of your build steps failed...
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
verbose: Error {"code":60}
```

**Tell us generally about your bug**

I tried to create a Pantheon site but keep getting this curl error when it's attempting to download drush from github: "curl: (60) SSL certificate problem: unable to get local issuer certificate"

**Please detail the steps we can take to replicate this bug. Be as detailed as possible.**

Start command prompt as an administrator and run the following commands:

```bash
git clone -c core.symlinks=true git@github.com:eGovPDX/portlandor.git
cd portlandor
git config core.autocrlf false
lando start
```

You can also reproduce it this way if Lando is already running by mimicking the commands Lando executes :

```bash
lando ssh
cd /tmp
curl https://github.com/drush-ops/drush/releases/download/8.1.16/drush.phar -L -o drush.phar
```

**Tell us more**

As the curl error message states, you can bypass this error by disabling SSL certificate validation by using curl with the -k option.

Does this bug prevent you from using lando?

Yes
