### ISSUE TITLE
Database keeps disappearing

### ISSUE THREAD

**Issue by duartegarin** [lando/lando#1076]
**Tell us about your setup**

v3.0.0-beta.47 and MacOS High Sierra

**Tell us about your `.lando.yml`**

```yml
name: acquia

# Start with the default Drupal 7 recipe
recipe: drupal7

# add in the varnish edge
proxy:

  # Empty the proxy settings provided by drupal8 recipe
  nginx:

  edge:
    - postgradaustralia.acquia.lndo.site
    - theuniguide.acquia.lndo.site

# Configure the Drupal8 recipe
config:

  # See: https://www.drupal.org/docs/8/system-requirements

  # Optionally specify the php version to use.
  #
  # If ommitted this will default to the latest php version supported by Drupal 8.
  # Consult the `php` service to see what versions are available. Note that all
  # such versions may not be supported in Drupal 8s so YMMV.
  #
  # See: https://www.drupal.org/docs/8/system-requirements/php
  #
  # NOTE: that this needs to be wrapped in quotes so that it is a string
  #
  php: '5.6'

  # Optionally specify whether you want to serve drupal via nginx or apache
  #
  # If ommitted this will default to the latest apache
  #
  # See: https://www.drupal.org/docs/8/system-requirements/web-server
  #
  via: apache:2.4

  # Optionally specify the location of the webroot relative to your approot.
  #
  # If ommitted this will be your approot itself.
  #
  webroot: docroot

  # Optionally specify how you want Lando to handle Drush. There are a few options
  #
  # If omitted this will install the Drush Launcher and assume you've installed a
  # site-local version of Drush with Composer
  #
  # You can also configure it in the following ways:
  #
  # 1. Install via Composer
  #
  # This will install the Drush Launcher (https://github.com/drush-ops/drush-launcher)
  # and will delegate to the site-local version of Drush you've installed with Composer
  # http://docs.drush.org/en/master/install/
  # drush: composer
  #
  # 2. Install Globally
  #
  # This will globally install the corresponding Drush 8 PHAR posted over at
  # https://github.com/drush-ops/drush/releases
  drush: global:8.1.12
  #
  # This will ATTEMPT to globally install any pre Drush 8 versions via Composer
  # drush: global:~7
  #
  # 3. Specify a path
  #
  # This assumes the user has already installed Drush but wishes to tell Lando where
  # it exists.
  # drush: path:/app/vendor/bin/drush
  #
  # 4. Do nothing
  #
  # This will tell Lando to not do anything, e.g. it's up to the user
  # drush: false
  #
  #drush: composer

  # Optionally specify whether you want to disable the global install of drupal console.
  #
  # You should also consider a site-local install of drupal console via composer
  #
  # See: https://hechoendrupal.gitbooks.io/drupal-console/content/en/getting/composer.html
  #
  drupal: false

  # Optionally specify the database type, this can be one of:
  #
  #   - `mysql`
  #   - `mariadb`
  #   - `postgres`
  #
  # If ommitted this will default to the latest mysql. You can additionally provide
  # a version with `type:version` but you will need to consult the documentation
  # for the correct DB service to see what versions are available
  #
  # see: https://www.drupal.org/docs/8/system-requirements/database-server
  #
  database: mariadb

  # Optionally activate xdebug
  #
  # If you are having trouble getting xdebug to work please see:
  # https://docs.devwithlando.io/services/php.html#using-xdebug
  xdebug: false

  # Optionally mix in your own config files
  #
  # If ommitted this will use "sane defaults" for your recipe type
  # conf:

  # For more information on setting these files check out the documentation
  # and examples
  #
  # Docs: https://docs.devwithlando.io/services/php.html
  # Examples: https://github.com/lando/lando/tree/master/examples
  #
  # server: config/drupal8.conf
  # php: config/php.ini

  # For more information on setting these files check out the documentation
  # and examples for the relevant services:
  #
  # MySQL: https://docs.devwithlando.io/services/mysql.html
  # MariaDB: https://docs.devwithlando.io/services/mariadb.html
  # PostGres: https://docs.devwithlando.io/services/postgres.html
  #
  # Examples: https://github.com/lando/lando/tree/master/examples
  #
  # database: config/mysql

# add additional auxiliary services
services:

  # set up a Varnish edge
  edge:
    type: varnish:4.1
    backends:
      - appserver

    # Optionally spin up another nginx instance so that you can secure your
    # traffic over ssl
    #
    # The varnish ssl service will be called NAME_ssl, or edge_ssl in this
    # example
    #
    ssl: true

    # Optionally load in a custom vcl file. This is relative to the app root
    #
    # You will not need to import the standard library or manage backends in this
    # file. Those are handled automatically.
    #
    # vcl: custom.vcl

    # There are various envvars you can specify to further customize how your
    # varnish works.
    #
    # See: https://hub.docker.com/r/eeacms/varnish/
    # Note: We set BACKENDS_PROBE_ENABLED to false by default
    #
    # overrides:
      # services:
        # environment:
          # BACKENDS_PROBE_ENABLED: false
          # BACKENDS_PORT: 8080
          # DNS_ENABLED: true
          # BACKENDS_PROBE_INTERVAL: 3s
          # BACKENDS_PROBE_TIMEOUT: 1s
          # BACKENDS_PROBE_WINDOW: 3
          # BACKENDS_PROBE_THRESHOLD: 2

  # set up Memcached cache
  cache:
    type: memcached:1.5
  database1:
    type: mariadb
    portforward: 3307
    creds:
      user: postgradaustralia
      password: postgradaustralia
      database: postgradaustralia
  database2:
    type: mariadb
    portforward: 3308
    creds:
      user: theuniguide
      password: theuniguide
      database: theuniguide

tooling:
  # Add in BLT command
  blt:
    service: appserver
    cmd: /usr/bin/blt

  # Add in routes to the varnish cli tools
  varnishadm:
    service: edge
    user: root
  varnishstat:
    service: edge
    user: root
  varnishlog:
    service: edge
    user: root
```

**Tell us generally about your bug**

My databases work fine when I do lando start.
However, when I stop lando and then start again, my databases services seem to be gone and I get "Access denied for user " in Drupal.

It's strange because I do lando info, and it does give me the info on the DBs but it's as if they aren't there. If I then do lando destroy and lando start and then re-import the DB again it works again (until the next restart).

This makes the dev workflow quite painful as you can imagine.

Any issues on my config that could be causing this?
