### ISSUE TITLE
Changing solr port results in HostPort error

### ISSUE THREAD

**Issue by kvij** [lando/lando#1078]
Bug Report
==========

Setup:
v3.0.0-beta.47 on Windows 10 Professional

My `.lando.yml`:

```yml
# Change this name to something that makes sense for your project
name: media

# Use the recipe appropriate for your application.
recipe: drupal8

# Configure the D8 recipe to match up closer to a vanilla platform.sh stack
config:

  # Lando defaults to Apache. Switch to nginx to match Platform.sh.
  via: nginx

  # Set the webroot to match your .platform.app.yaml.
  webroot: web

  # Set this to match the version in your .platform.app.yaml.
  php: 7.1

  # Enable xdebug...
  xdebug: true

  # Lando defaults to the latest MySQL release, but Platform.sh uses MariaDB.
  # Specify the version to match what's in services.yaml.
  database: mariadb:10.1

# Url's for aditional services. Replace changeme with the project name
proxy:
  smtp:
    - mail.media.lndo.site

  search:
    - solr.media.lndo.site:8983

# The following additional build step will install the Platform CLI
# in the application container and auto-run `composer install`
services:
  appserver:
    build:
      - "cd /tmp && curl -sS https://platform.sh/cli/installer | php || true" # FIXME: Check forced success is still nessesary.
      - "composer global require hirak/prestissimo"
      - "cd $LANDO_MOUNT && composer install"
    overrides:
      services:
        environment:
          BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://nginx/"}, "Drupal\\DrupalExtension" : {"drush" :   {  "root":  "/app/web" }}}}'

  # Portforward can be set to a specific port for a subprocject
  # Imports default.sql.gz on first build. Use `lando db-export default.sql` to generate or update this file
  database:
    portforward: 3307
    build:
      - "cd $LANDO_MOUNT && scripts/ewise/conditional_import.sh"

  smtp:
    type: mailhog
    hogfrom:
      - appserver

  search:
    type: solr:6.6
    portforward: true
    core: d8
    port: 8080
    extras:
     - 'rm -r /opt/solr/server/solr/mycores/d8/conf && mkdir -p /opt/solr/server/solr/mycores/d8/conf'
     - 'cp -r $LANDO_MOUNT/web/modules/contrib/search_api_solr/solr-conf/6.x/* /opt/solr/server/solr/mycores/d8/conf'
     - 'chown -R solr:solr /opt/solr/server/solr/mycores/d8/conf'

# Ensure `composer install` also happens every time you start your site
# Ensure generated files are removed from cache before database is exported
events:
  post-db-import:
    - appserver: "cd $LANDO_MOUNT && composer install"
  pre-db-export:
    - appserver: "cd $LANDO_MOUNT && drush cache-rebuild"

# The following entry creates a `lando platform` command that will run
# any Platform CLI command from inside the container if desired.
tooling:
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd: /var/www/.platformsh/bin/platform
  phplint:
    service: appserver
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat
```

Triggering the error:
When a starting lando after adding the ```port:``` statement a rebuild of the containers is triggerd. This generates an error for the Solr container: 

**error: Cannot read property 'HostPort' of undefined** 

I wan't to set the port (and hostname which works) the same as it is going to be on platform.sh so we can use Drupal's configuration management without breaking the Solr setup every time. Platform.sh does not to configure the service port and is set to port 8080.
