### ISSUE TITLE
lando drush sql-sync uses www-data user not host user

### ISSUE THREAD

**Issue by tanc** [lando/lando#1082]
Bug Report
==========

v3.0.0-beta.47 on MacOS 10.13.5

`.lando.yml` file:

```
name: testd8
recipe: drupal8
config:
  webroot: gitroot/web
```

Command I was trying to run:
```
lando drush sql-sync @remote.production @self
```

Error produced:
```
 [error]  The external command could not be executed due to an application error. [1.21 sec, 7.57 MB]
 [error]  The command could not be executed successfully (returned: Permission denied (publickey).
, code: 255) [1.21 sec, 7.57 MB]
 [error]  Error: no database record could be found for source @remote.prod [1.22 sec, 7.59 MB]
```

While ssh keys are being forwarded properly the drush command `sql-sync` falls back to using the container's user `www-data` and not the host system user running the command.

One way around that is to specify the `remote-user` in the drush alias file but this would then render the alias incompatible with other team members.

Can you think of any way of getting Lando to use the host user name when running `sql-sync` and other ssh commands?

**Comment by tanc** [comment]
A solution to my issue is to pass through an environment variable in a `.env` file:
```
LANDO_HOST_USER=tanc
```
Then modify the drush aliases for the remote site to use the environment variable:
```
stage:
  host: stage.mycustomsite.org
  root: /var/www/stage.mycustomsite.org/gitroot/web/
  uri: default
  user: ${env.LANDO_HOST_USER}
```

It would be great if the host user name could automatically be available as an environment variable within containers without having to specify it in an `.env` file.

**Comment by tanc** [comment]
A slightly nicer solution is to add a `USER` global environment variable to `config.yml` (`~/.lando/config.yml`):
```
USER=tanc
```
This is then available in any container and as it is the same as the host system's environment variable it can be used in a more flexible way in drush alias files (e.g. `drush/sites/remote.site.yml`):
```
stage:
  host: stage.mycustomsite.org
  root: /var/www/stage.mycustomsite.org/gitroot/web/
  uri: default
  user: ${env.USER}
```
This will then work:
`lando drush sql-sync @remote.stage @self`

As will this (if you aren't using Lando):
`drush sql-sync @remote.stage @self`
