### ISSUE TITLE
Selenium "server error - container 38a124a.. is not connected to the network lando_bridge_network

### ISSUE THREAD

**Issue by welly** [lando/lando#1090]
I'm trying to add a selenium service to my lando environment. I've taken the docker-compose config from a docker-compose project and added it to my .lando.yml file. On running `lando start', I get the following error:

> error: (HTTP code 500) server error - container 38a4a6ca5e967a064f898896cd6be536376571c8971ecf9340fd60bef729a646 is not connected to the network lando_bridge_network

On running `docker logs 38a4a6ca5e96`, I see the following:

> user-perms.sh kicking off as user uid=1000(seluser) gid=1000(seluser) groups=1000(seluser),27(sudo)
> Lando ENVVARS set at
> LANDO_WEBROOT_USER: www-data
> LANDO_WEBROOT_GROUP: www-data
> LANDO_WEBROOT_UID: 33
> LANDO_WEBROOT_GID: 33
> mkdir: cannot create directory ‘/etc/ssh’: Permission denied
> Cert creation kicking off
> LANDO_CA_CERT: lando.pem
> LANDO_CA_KEY: lando.key
> CA_CERT_HOST: /lando/certs/lando.pem
> CA_DIR: /usr/share/ca-certificates
> CA_CERT_CONTAINER: /usr/share/ca-certificates/lando.pem
> mkdir: cannot create directory ‘/certs’: Permission denied
> Running command

**Tell us about your setup**

Lando version 3.0.0-beta.47 on OSX 10.12.6

**Tell us about your `.lando.yml`**

```
name: starter
proxy:
  appserver:
    - starter.lndo.site

services:
  appserver:
    type: php:7.1
    via: apache
    ssl: true
    webroot: web
    xdebug: true

  database:
    type: mysql
    portforward: 3308
    creds:
      user: drupal
      password: drupal
      database: drupal

  browser:
    type: compose
    services:
      image: selenium/standalone-chrome

tooling:
  composer:
    service: appserver
    description: Run composer commands
    cmd:
      - composer
      - --ansi
  php:
    service: appserver

  mysql:
    user: root
    service: database
    description: Drop into a MySQL shell
```

Any ideas would be most welcome!

**Comment by smmccabe** [comment]
The solution to your error log notices is to just add a `user: root` so that the selenium image has the sufficient permissions for lando to set itself up. However, that doesn't appear to fix the root problem of it not adding itself to the proper network bridge.

**Comment by smmccabe** [comment]
The issue for me seems to be that the selenium image crashes or somehow fails to finish starting? it is never visible via `docker ps` once the `lando rebuild` has run, networked or otherwise. Yet if i run it directly via docker it works no problem

**Comment by smmccabe** [comment]
Crap! i totally fixed this and forgot to respond.

You just need to specify the correct entry point

```
  selenium:
    type: compose
    services:
      image: selenium/standalone-chrome
      user: root
      ports:
        - "4444:4444"
      volumes: 
        - /dev/shm:/dev/shm
      command: /opt/bin/entry_point.sh
```
