### ISSUE TITLE
Run command only runs on first start

### ISSUE THREAD

**Issue by anthropos9** [lando/lando#1103]
Feature Requests and Bug Reports
--------------------------------

Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.
3.  Fill out either the `BUG REPORT` or `FEATURE REQUEST` below.

Bug Report
==========

**Tell us about your setup**

v3.0.0-beta.47 MacOS 10.13.5

**Tell us about your `.lando.yml`**
Here is the part of interest for this issue...

```yml
  database:
    type: mysql:5.6
    portforward: 3336
    creds:
      user: mysql
      password: secret
      database: database
    overrides:
      services:
        volumes:
          - lando_config/mysql:/var/lib/mysql
    run:
      - "mysql -u root < /app/lando_config/db/fast_shutdown.sql"
```

This is the contents of fast_shutdown.sql:
```sql
SET GLOBAL innodb_fast_shutdown = 0;
```

**Tell us about the error you got**

The first time I run this setup I get the correct result - namely that the innodb_fast_shutdown variable is set to 0. On subsequent runs it goes back to the default of 1 - as if the command was not run.

**Tell us more**

I am under the impression that the run command should run every time you start up Lando. The documentation seems to indicate that, but I could also be making an assumption based upon what I want to happen. Either way the documentation does not say that it only runs on the first start and ignored on subsequent starts or restarts.

**Does this bug prevent you from using lando?**
No, but it does make things less convenient for me in that it makes me have to manually set this setting every time.

Because I know you're curious the reason for having to set this is that there is something about the way using a shared volume for the mysql directory is causing my innodb tables to be corrupted when stopping Lando. Turning off innodb_fast_shutdown seems to prevent the corruption from happening. I'm still testing, but it does seem to be the trick.
