### ISSUE TITLE
Gatsbyjs with lando - Expose port 8000

### ISSUE THREAD

**Issue by alejodaraio** [lando/lando#1105]
Hey guys, i was shooting to Up a nodejs server with Gatsbyjs, but im getting some problems to see my website in the browsers.

This is my current lando:

```yml
name: mysite

proxy:
  appserver:
    - mysite.lndo.site

services:

  appserver:
    type: node:8.9
    overrides:
      services:
        ports:
          - "8000:8000"
    globals:
      gatsby-cli: "latest"

tooling:
  npm:
    service: appserver
  node:
    service: appserver
  gatsby:
    service: appserver
```
After startup my lando i run the gatsby command to startup my App as developer.

```
lando npm run develop
```

> As extra info Gatsbyjs startup the app with localhost:8000

But! when i go to **mysite.lndo.site** i get bad gateway response. I was looking some issues about how to expose ports, i tried disable the proxy but i can't see what is worng.

I tried **mysite.lndo.site:8000** but this doesn't exists.

**Comment by dustinleblanc** [comment]
@alejodaraio try this:

```yml
proxy:
  appserver:
    - mysite.lndo.site:8000
```

That should theoretically work so long as gatsby is propperly running on the port. You'll need to provide a command to get it running

**Comment by AaronFeledy** [comment]
This is how I got mine working:

```
name: mysite

proxy:
  nodejs:
    - mysite.lndo.site:8000

services:
  nodejs:
    type: node:8.9
    overrides:
      services:
        ports: [8000:8000]
    globals:
      gatsby-cli: "next"

tooling:
  npm:
    service: nodejs
  node:
    service: nodejs
  gatsby:
    service: nodejs
```

With the above .lando.yml, `lando gastby develop` still would not host outside of the container. It seems that you need to tell gatsby to host outside of the container by specifying the host as 0.0.0.0 when running the develop command. You can do this by running `lando gatsby develop --host 0.0.0.0`. Starting it in that way will make your site available on mysite.lndo.site:8000 on your host machine.

**Comment by tylerssn** [comment]
@alejodaraio & @AaronFeledy here is what I finally ended up with after a quick chat with @dustinleblanc & @pirog.

```yaml
name: gatsby

proxy:
  appserver:
    - gatsby.lndo.site

services:
  # Prefer appserver as a name since Lando defaults to it - making `lando ssh` functional as opposed to a required service name (`lando ssh nodejs`
  appserver:
    type: node:9
    # One-time build step
    install_dependencies_as_me:
      - yarn global add gatsby-cli
      # Initial build fail-safe for the Sharp NodeJS package.
      #  Sharp can be a pain. If installed on host, it may break in Lando.
      - rm -rf node_modules && yarn
    run_as_root:
      # Considering port 443 & 80, grant non-root access to lower port numbers
      - setcap 'cap_net_bind_service=+ep' `which node`
    command: gatsby develop --host 0.0.0.0 --port 80

####
# Irrelevant, but bonus tooling

tooling:
  yarn:
    service: appserver
  npm:
    cmd: Nope, try `lando yarn` instead.
    service: appserver
  node:
    service: appserver
  gatsby:
    service: appserver
  gatsby:start:
    cmd: gatsby develop --host 0.0.0.0 --port 80
    service: appserver
```
