### ISSUE TITLE
Unable to spin up an Elasticsearch instance

### ISSUE THREAD

**Issue by matthewbdaly** [lando/lando#1109]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

*v3.0.0-beta.47 on Xubuntu 18.04, although I have also been able to duplicate it on my work Macbook Pro running OS X High Sierra*

**Tell us about your `.lando.yml`**

Used the current example for Elasticsearch to replicate this, but have reproduced below:

```yml
# elasticsearch example
name: elasticsearch

#
# You need to run `lando npm install` before you run `lando start` for this
# example to work
#

# Give me http://elasticsearch.lndo.site
proxy:
  appserver:
    - elasticsearch.lndo.site

# Spin up a basic nodes server with elasticsearch backend
services:

  # Spin up a memcache container called "search"
  # NOTE: "search" is arbitrary, you could just as well call this "theboss" or "eljefe"
  search:

    # Use version 5.4 of elasticsearch
    type: elasticsearch:5.4

    # Optionally allow access to the cache at localhost:9999
    # You will need to make sure port 9999 is open on your machine
    #
    # You can also set `portforward: true` to have Lando dynamically assign
    # a port. Unlike specifying an actual port setting this to true will give you
    # a different port every time you restart your app
    portforward: 9999

    # Optionally load in a custom config file. This is relative to the app root.
    #
    # config: customElasticsearch.yml

    # There are various envvars you can specify to further customize how
    # elasticsearch works.
    #
    # See: https://hub.docker.com/r/itzg/elasticsearch/
    #
    # overrides:
      # services:
        # environment:
          # ES_JAVA_OPTS: -Xms16g -Xmx16g
          # PLUGINS: elasticsearch/marvel/latest

  # Spin up services to run a basic node server
  appserver:
    type: node:6.10
    command: npm start

# Add some nice command routing
tooling:
  yarn:
    service: appserver_cli
  npm:
    service: appserver_cli
  node:
    service: appserver_cli
```

**Tell us about the command you were running**

```bash
lando start -vvv
```

**Tell us about the error you got**

```bash
$ lando start -vvv
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "elasticsearch_default" with the default driver
Creating volume "elasticsearch_data" with default driver
Pulling appserver (node:6.10)...
        Pulling search (itzg/elasticsearch:5.4)...
Creating elasticsearch_appserver_cli_1 ... done
Creating elasticsearch_search_1        ... done
Creating elasticsearch_appserver_1     ... done
error: (HTTP code 500) server error - container 6eedfe7365827c6486abad09e6461c2e2affeff2eed020f0e379badfe8570b43 is not connected to the network lando_bridge_network 
```

**Tell us generally about your bug**

*When I try to use Lando with Elasticsearch as part of the the stack, the build process fails with an error such as `error: (HTTP code 500) server error - container 716679a162d134b0e01edf958854bc7474eb818e52c17c7c05d2c5137c175a7b is not connected to the network lando_bridge_network`*

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

```bash
1. Copied over the Elasticsearch .lando.yml example file to the current directory
2. Ran `lando start -vvv`
```

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

*No, it looks to be a bug*

**Does this bug prevent you from using lando?**

Only for projects where the stack includes Elasticsearch.
