### ISSUE TITLE
XSLTProcessor missing from Pantheon recipe

### ISSUE THREAD

**Issue by seanr** [lando/lando#1112]
**Tell us about your setup**

v3.0.0-beta.47, OS X 10.13.5

**Tell us about your `.lando.yml`**

```yml
# Pantheon recipe
name: [redacted]

# Start with the default Pantheon recipe
recipe: pantheon

# Configure the Pantheon recipe
config:

  # Optionally specify the type of Pantheon site this is. If ommitted this will
  # default to `drupal`. You can use the following options
  #
  #   - `backdrop`
  #   - `drupal` (for Drupal 6 and Drupal 7 sites)
  #   - `drupal8`
  #   - `wordpress`
  #
  framework: drupal8

  # Optionally activate xdebug
  #
  # If you are having trouble getting xdebug to work please see:
  # https://docs.devwithlando.io/services/php.html#using-xdebug
  xdebug: true

  # Optionally specify the site id, name and environment for your Pantheon site
  #
  # This is helpful for running terminus commands or performing similar operations
  id: [redacted]
  site: [redacted]
(...other irrelevant stuff)
```

**Tell us about the command you were running**

Pantheon's servers have the XSLTProcessor available, but Lando's Pantheon recipe does not. Test this by running `dpm((class_exists('XSLTProcessor')) ? 'true' : 'false');` from /devel/php on a Drupal install with the devel module enabled.

**Tell us about the error you got**

`Fatal error: Class 'XSLTProcessor' not found`

**Tell us generally about your bug**

As above; mismatch between actual Pantheon config and Lando Pantheon recipe.

**Comment by uberhacker** [comment]
In the meantime, you can fix this issue by adding the following in `.lando.yml`:
```
services:
  appserver:
    run_as_root: |
      # install missing xsl extension
      if [ ! -f /usr/include/libxslt/xslt.h ]; then apt update && apt install libxslt1-dev -y && docker-php-ext-install xsl && docker-php-ext-enable xsl; fi
```
To test if the extension was installed correctly, execute:
```
$ lando php -m | grep xsl
```
