### ISSUE TITLE
Feature request: Support for Elasticsearch 6

### ISSUE THREAD

**Issue by becizzz** [lando/lando#1114]
Feature Request
===============

It would be great if Lando officially supported newer Elasticsearch versions.
The docker images that are being [used right now](https://hub.docker.com/r/itzg/elasticsearch/) haven't been updated in 10 months.

As a workaround I'm running latest Elasticsearch like this:
```
elasticsearch:
  type: compose
  services:
    image: blacktop/elasticsearch:6.3
    command: /elastic-entrypoint.sh elasticsearch
    ports:
      - "9200:9200"
```

Maybe it makes sense switching to [these](https://hub.docker.com/r/blacktop/elasticsearch/) docker images.
