### ISSUE TITLE
Lando stop doesn't stop traefik

### ISSUE THREAD

**Issue by gonssal** [lando/lando#1120]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.0.0-beta.47 on Ubuntu 18.04

**Tell us about your `.lando.yml`**

```yml
name: on-viure
recipe: laravel
config:
  webroot: public
  php: '5.6'
  via: apache
  database: mysql:5.5
  xdebug: true
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
    overrides:
      services:
        environment:
          # PMA_ARBITRARY: 1
          # PMA_HOST: database
          PMA_USER: laravel
          PMA_PASSWORD: laravel
proxy:
  appserver:
    - onviure.lndo.site
    - "*.onviure.lndo.site"
  pma:
    - pma.lndo.site
```

**Tell us about the command you were running**

```bash
lando stop
```

**Tell us about the error you got**

None

**Tell us generally about your bug**

Run `lando stop`, see how the proxy, traefik, is still running with `docker ps`. Because the proxy is not stopped, the ports it was proxying are not freed.

If I run `lando stop`, I expect all the containers it started to stop.
