### ISSUE TITLE
Passphrase protected ssh key not being loaded

### ISSUE THREAD

**Issue by becizzz** [lando/lando#1143]
Bug Report
==========

**Tell us about your setup**

v3.0.0-beta17 on macOS High Sierra 10.13.6

**Tell us about your `.lando.yml`**

```yml
name: multisite
recipe: drupal8

compose:
  - compose.yml

config:
  webroot: web
  via: nginx
  php: '7.1'
  xdebug: true

tooling:
  build.sh:
    service: appserver
    description: Execute build.sh
    cmd:
      - ./build.sh
  codeception:
    service: appserver
    description: Run codeception
    cmd:
      - ./vendor/bin/codecept
  phpcs:
    service: appserver
    description: Run phpcs
    cmd:
      - ./vendor/bin/phpcs
  codesniff:
    service: appserver
    description: Run code sniffer with default config
    cmd:
      - ./vendor/bin/phpcs
      - "--standard=phpcs.xml"
  phpcbf:
    service: appserver
    description: Run phpcbf
    cmd:
      - ./vendor/bin/phpcbf
  codefix:
    service: appserver
    description: Run code autofix
    cmd:
      - ./vendor/bin/phpcbf
      - "--standard=phpcs.xml"
  theme-build:
    service: node
    description: Builds themes css files
    cmd: true
  sync.sh:
    service: appserver
    description: Execute sync.sh
    cmd:
      - ./sync.sh

services:  
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  
  appserver:
    ssl: true
    extras:
      - "/app/extras.sh"
    overrides:
      services:
        environment:
          WKV_SITE_ENV: lando

  elasticsearch:
    type: compose
    services:
      image: blacktop/elasticsearch:6.3
      command: /elastic-entrypoint.sh elasticsearch
      ports:
        - "9200:9200"

  kibana:
    type: compose
    services:
      image: blacktop/kibana:6.3
      environment:
        KIBANA_ELASTICSEARCH_URL: http://elasticsearch:9200
      ports:
      - "5601:5601"
      command: /docker-entrypoint.sh kibana

  node:
    type: node
    run:
      - cd $LANDO_MOUNT/web/themes/custom/defender/ && yarn install

  db_1:
    type: mariadb:10.1
    portforward: 32001
  db_2:
    type: mariadb:10.1
    portforward: 32002
  db_3:
    type: mariadb:10.1
    portforward: 32003
  db_4:
    type: mariadb:10.1
    portforward: 32004
  db_5:
    type: mariadb:10.1
    portforward: 32005
  db_6:
    type: mariadb:10.1
    portforward: 32006
  db_7:
    type: mariadb:10.1
    portforward: 32007

proxy:
  mailhog:
    - mail.lndo.site
  elasticsearch:
    - search.lndo.site:9200
  nginx:
    - site1.lndo.site
    - site2.lndo.site
    - site3.lndo.site
    - site4.lndo.site
    - site5.lndo.site
    - site6.lndo.site
    - site7.lndo.site
  kibana:
    - kibana.lndo.site:5601


events:
  post-start:
    appserver: cd $LANDO_MOUNT && composer install && ./vendor/bin/phpcs --config-set installed_paths /app/vendor/drupal/coder/coder_sniffer/
  post-theme-build:
    node: cd $LANDO_MOUNT/web/themes/custom/defender/ && npm run build
```

**Tell us about the command you were running**

```
# Edit the config
echo "loadPassphraseProtectedKeys: true" >> ~/.lando/config.yml

# Poweroff lando
lando poweroff

# Reboot an app
lando start
```

**Tell us generally about your bug**

I tried to use passphrase protected ssh keys. Set the global config according to documentation https://docs.devwithlando.io/config/ssh.html, but the ssh key in question is still not loaded.

**Tell us more**

My guess is that something from this old [commit](https://github.com/lando/lando/commit/8e6e6d482e809a5fe4c348111abda26fb2418520) has been lost. Looks like the variable `LANDO_LOAD_PP_KEYS` is always false.
