### ISSUE TITLE
Do not inherit case-insensitivity from system

### ISSUE THREAD

**Issue by aaronbauman** [lando/lando#1149]
I just got bit by a docker case-sensitivity bug when developing for PHP / drupal using a pantheon recipe: https://github.com/docker/for-mac/issues/320

Bug Report
==========

OSX 10.12.4
lando v3.0.0-beta.47

.lando.yml:
```yml
name: EXAMPLE
recipe: drupal8
config:
  framework: drupal8
  env: dev
  site: EXAMPLE
  webroot: web
id: EXAMPLE
```

My PHP filename did not match the case of the PHP class name within.
Locally, this did not cause any issue.
After deployment to Pantheon, the mismatch caused a failure.

Ultimately, the expected behavior is the same as the issue linked above:

> Mounting a folder from OSX in a non-OSX system shouldn't inherit the case insensitivity

I read through but did not exactly follow the thread therein, so I'm not sure what the fix should be.
