### ISSUE TITLE
Service nginx is unhealthy - App unreachable

### ISSUE THREAD

**Issue by eleftrik** [lando/lando#1150]
Lando version v3.0.0-beta.47 on Windows 10 Professional

.lando.yml:

```
name: foo
recipe: laravel
config:
  php: '7.2'
  via: nginx
  database: mariadb
  xdebug: true
  webroot: public
proxy:
  nginx:
  - foo.test
proxyDomain: test
services:
  mariadb:
    type: mariadb
    portforward: 3306
    creds:
      user: foo
      password: bar
      database: foo

```

On Git Bash (as administrator), after running `winpty lando start`, I got

```
Waiting until nginx service is ready...
Waiting until nginx service is ready...
warn: Service nginx is unhealthy
warn: Run "lando logs -s nginx"

BOOMSHAKALAKA!!!
```

...but the app is unreacheable (both on 80 and 443 ports), even if Lando says all services are up.
Already tried rebuilding, but didn't work.

If I run `lando logs -s nginx` I got

```
...
nginx_1      | Generating certs...
nginx_1      | Generating RSA private key, 2048 bit long modulus
nginx_1      | ..........+++
nginx_1      | ...............................................................................+++
nginx_1      | e is 65537 (0x010001)
nginx_1      | x509: Cannot open input file /lando/certs/lando.pem, No such file or directory
nginx_1      | x509: Use -help for summary.
nginx_1      | Running command /bin/sh -c envsubst '$LANDO_WEBROOT' </etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
nginx_1      | 2018/08/24 07:36:02 [emerg] 107#107: BIO_new_file("/certs/cert.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/certs/cert.crt','r
') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx_1      | nginx: [emerg] BIO_new_file("/certs/cert.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/certs/cert.crt','r') error:2006D080:BIO
routines:BIO_new_file:no such file)

```

Thank you
