### ISSUE TITLE
Lando Drupal 8 - editor support for drush/drupal console?

### ISSUE THREAD

**Issue by wturrell** [lando/lando#1151]
Is there a means to install/activate a working Vi or Vim in the Drupal recipe (i.e. from within `lando ssh`), so I can run commands like this, for editing Drupal configuration via the CLI:

    $ lando drupal config:edit system.maintenance

> sh: 1: vi: not found
>                                                                                                                         
>  [ERROR]  
> 

If I do `lando ssh --user=root` and use `apt-cache search`, I can't find 'vi','vim' or 'nano'.

(NB: Drupal console does allow you to [specify](https://hechoendrupal.gitbooks.io/drupal-console/en/commands/config-edit.html) it's choice of editor)

**Tell us about your setup**

Lando v3.0.0-beta.47
macOS Sierra 10.12.6
Docker Version 18.06.0-ce-mac70 (26399)

**Tell us about your `.lando.yml`**

```
name: mysite
recipe: drupal8
config:
  webroot: web
  via: nginx
  xdebug: true
  php: '7.1'
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: 1026
```
