### ISSUE TITLE
wp: not found

### ISSUE THREAD

**Issue by mordonez** [lando/lando#1170]
**Setup**

v3.0.0-beta.47 on **macOS v10.13.6**  (Darwin 17.7.0)

**.lando.yml**

```yml
name: seguros
recipe: wordpress
config:
  webroot: .
  xdebug: true

services:
# Additional services
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
```

**Tell us about the command you were running**

```bash
lando wp -vvvv
```

**Tell us about the error you got**

```bash
/bin/sh: 1: wp: not found
```

**Tell us generally about your bug**

I tried to run the wp command inside a worpress project
