### ISSUE TITLE
'lando push' fails: php: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lolusername** [lando/lando#1171]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.0.0-beta.47 on OSX High Sierra

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.
```
**.lando.yml:**
name: turbonomic
recipe: pantheon
config:
  framework: wordpress
  site: turbonomic
  id: 7f1eb375-22a2-47e9-bd60-b15424d01b1c
services:
  node:
    type: 'node:6.10'
    globals:
      gulp-cli: latest
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node

```

```
**pantheon.yml:**
# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1
```
```
**pantheon.upstream.yml:**
# IMPORTANT NOTE:
# Do not edit this file unless you are doing so in your custom upstream repository.
# Override the defaults specified here in a site-specific `pantheon.yml` file.
# For more information see: https://pantheon.io/docs/pantheon-upstream-yml
api_version: 1
php_version: 7.2
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

**Tell us about the command you were running**
```
lando push
```

Paste in a series of commands that caused the bug.
```

lando push
```

**Tell us about the error you got**

Rerun the command that produced your error in `verbose` mode. Paste in the error and the ~100 lines that proceeded it.
```
Error: Unsupported flag --verbose
```

**Tell us generally about your bug**

 I am unable to use lando to push to pantheon and it does prevent me from using pantheon

**Tell us more**

This problem started after I upgraded WP core through Pantheon

```
php: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```
