### ISSUE TITLE
Restoring database via `lando platform` does not complete

### ISSUE THREAD

**Issue by danielnitsche** [lando/lando#1174]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.0.0-beta.47 on macOS High Sierra

**Tell us about your `.lando.yml`**

```yml
# Change this name to something that makes sense for your project
name: myapp

# Use the recipe appropriate for your application.
recipe: drupal8

# Configure the D8 recipe to match up closer to a vanilla platform.sh stack
config:

  # Lando defaults to Apache. Switch to nginx to match Platform.sh.
  via: nginx

  # Set the webroot to match your .platform.app.yaml.
  webroot: web

  # Set this to match the version in your .platform.app.yaml.
  php: 7.1

  # Lando defaults to the latest MySQL release, but Platform.sh uses MariaDB.
  # Specify the version to match what's in services.yaml.
  database: mariadb:10.0

# Multisite
proxy:
  nginx:
    - db1.lndo.site
    - db2.lndo.site

services:
  db1:
    type: mariadb:10.1
    creds:
      user: db1
      password: password
      database: db1
  db2:
    type: mariadb:10.1
    creds:
      user: db2
      password: password
      database: db2

  # The following additional build step will install the Platform CLI
  # in the application container and auto-run `composer install`
  appserver:
    run:
      - "mkdir -p /var/www/.platformsh && mkdir -p /var/www/.platformsh/bin"
      - "curl -fsSL -o /var/www/.platformsh/bin/platform https://github.com/platformsh/platformsh-cli/releases/download/v3.33.6/platform.phar"
      - "chmod ug+x /var/www/.platformsh/bin/platform"
      - "cd $LANDO_MOUNT && composer install"
    overrides:
      services:
        environment:
          BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://nginx/"}, "Drupal\\DrupalExtension" : {"drush" :   {  "root":  "/app/web" }}}}'

# The following entry creates a `lando platform` command that will run
# any Platform CLI command from inside the container if desired.
tooling:
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd: /var/www/.platformsh/bin/platform
  phplint:
    service: appserver
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat
```

**.platform.app.yaml**

```yml
# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: 'app'

# The runtime the application uses.
type: 'php:7.2'

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    db1: 'mysqldb:db1'
    db2: 'mysqldb:db2'

# The size of the persistent disk of the application (in MB).
disk: 2048

...
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

```bash
lando platform sql --relationship db1 -e master < db1.sql
```

**Tell us about the error you got**

No error or message returned. But when I look at the remote database, not all my data is there, and a `show processlist` shows `Waiting for table metadata lock`. This seems to continue indefinitely -- I've given in over 2 hours.

Compare this to:
```bash
lando ssh appserver -c "/var/www/.platformsh/bin/platform sql --relationship db1 -e master < /app/db1.sql"
```

which works perfectly fine, as does:
```bash
platform sql --relationship db1 -e master < db1.sql
```

Also possibly relevant, if I create a file `test.sql` and put only the word `SELECT` in it (to trigger an error), this command returns no SQL error:
```bash
lando platform sql --relationship db1 -e master < test.sql
```

But these two do return an error (`ERROR 1064 (42000) at line 1: You have an error in your SQL syntax...`:
```bash
platform sql --relationship db1 -e master < test.sql
```
```bash
lando ssh appserver -c "/var/www/.platformsh/bin/platform sql --relationship db1 -e master < /app/test.sql"
```
