### ISSUE TITLE
Lando pull just hangs

### ISSUE THREAD

**Issue by vp123456** [lando/lando#1188]
Lando 3.0.0-rc.1 on Windows 10 Enterprise

.lando.yml

```
name: test
recipe: pantheon
config:
  framework: wordpress
  site: test
  id: 8d8ae673-018f-4509-b3e3-7ed97b7123ae
```

After doing `lando start` everything looks good but when I do `lando pull` and select dev for all the choices:

```
? Pull code from? dev
? Pull DB from? dev
? Pull files from? dev
```

It just hangs.
