### ISSUE TITLE
cp: cannot stat '/lando/keys/*': No such file or directory

### ISSUE THREAD

**Issue by blakestein** [lando/lando#1194]
**Tell us about your setup**

v3.0.0-rc1 on Windows 10 Enterprise

```
name: myproject
recipe: drupal8
config:
  webroot: docroot
  php: '7.2'

services:
  appserver:
      run:
        - if [ ! -L /usr/local/bin/blt ]; then ln -s /app/vendor/bin/blt /usr/local/bin/blt; fi;
  node:
    type: node:9
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

proxy:
  mailhog:
    - mailhog.myproject.lndo.site

tooling:
  node:
    service: node
  npm:
    service: node
  blt:
    service: appserver
    cmd: /usr/local/bin/blt
```

Running `lando start` or similar with an empty `~/.lando/keys` directory on Windows results in a error that seems to kill the rest of the key loading script and as a result no keys are loaded in the container.

*Example:*

```
appserver_1  | Copying keys from /user/.ssh...
appserver_1  | Copying keys from /lando/keys...
appserver_1  | cp: cannot stat '/lando/keys/*': No such file or directory
```

Throwing a key into the `~/.lando/keys` directory allows keys to load as expected.
