### ISSUE TITLE
DNS_PROBE_FINISHED_NXDOMAIN after a some time

### ISSUE THREAD

**Issue by edwinsiebel** [lando/lando#1201]
What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

*v3.0.0-beta.47 on Ubuntu 18.04*

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

*Example:*

```yml
name: test
recipe: wordpress

config:
    type: php:7.0
    via: nginx:1.13
    ssl: true
    webroot: htdocs
    xdebug: true

    conf:
      server: provision/nginx/default.conf

proxy:
  web:
  mailhog:
    - mail.test.lndo.site
  pma:
    - pma.test.lndo.site

services:
  web:
    type: php:7.0
  pma:
    type: phpmyadmin:4.6
    ssl: true
    hosts:
      - database
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  redis:
    type: redis:4.0
    portforward: 6380
    persist: true
  database:
    type: mariadb
    config:
      confd: provision/mysql

  appserver:
    run:
      - cd $LANDO_MOUNT && composer install

    overrides:
      services:
        environment:
          environment: 'development'
          DB_HOST: 'database'

    config:
      conf: provision/php/php.ini

    environment:
      - environment=development
      - DB_HOST=database

  node:
    type: node:6.10

    globals:
      webpack: "latest"
      npm: "latest"
      yarn: "latest"

tooling:
  deploy:
    service: appserver
    cmd: ./vendor/bin/dep deploy
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"

  webpack:
    service: node
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node```

**Tell us about the command you were running**

```bash
lando start
```

**Tell us about the error you got**

Lando starts perfect, nginx/database/redis/etc works perfect. However, after some time, Chrome give met the DNS_PROBE_FINISHED_NXDOMAIN error, and the page cannot be displayed anymore. Lando ssh, for example, still works.

**Tell us generally about your bug**

Lando starts perfect, nginx/database/redis/etc works perfect. However, after some time, Chrome give met the DNS_PROBE_FINISHED_NXDOMAIN error, and the page cannot be displayed anymore. Lando ssh, for example, still works.
So, this must be something related to DNS. 

Looking at the landoproxyhyperion/traefik container, no errors are shown.
A ```lando poweroff``` and a ```lando start``` will not result in success: nginx fails to start (however, in the logs nothing special is visible).
I have to do a reboot of the system to fix the problem.

Never had this before, but got a new laptop, and this recently appears.
