### ISSUE TITLE
Link to BIG CHANGES in release notes for rc.1 links to docs home

### ISSUE THREAD

**Issue by tanc** [lando/lando#1204]
Simple one, the [release notes](https://github.com/lando/lando/releases/tag/v3.0.0-rc.1) for rc.1 states:

> WHILE WE'VE TRIED TO MAINTAIN BACKWARDS COMPATIBILITY WE RECOMMEND YOU [CHECK OUT THE BIG CHANGES](
https://docs.devwithlando.io/) IN RC!

Unfortunately the link leads to the home page of the docs instead of somewhere listing the big changes!

**Comment by dustinleblanc** [comment]
@tanc I think this note might just be another subtle way that @pirog is attempting to get folks to read the documentation as we all tend to ignore them and ask for help instead 😆 Interestingly, the actual list of changes is listed below the paragraph...so I am not sure what better link could be substituted.

I am inclined to say let's just leave the link as is, but I can see how it'd be confusing.

**Comment by dustinleblanc** [comment]
Yes it definitely is, all of the changes are listed in the change log, I can only think of one breaking change, and that's the syntax for tooling commands.

```yaml
tooling:
  thing:
    service: appserver
    cmd:
      - foo
      - --bar=baz
```
Becomes
```yaml
tooling:
  thing:
    service: appserver
    cmd: foo --bar=baz
```

This is for consistency with how we parse build steps, etc. tooling was a special snowflake and is now consistent with the rest of the things.
