### ISSUE TITLE
Improve Composer speed by sharing cache

### ISSUE THREAD

**Issue by iBobik** [lando/lando#1206]
As an user using Lando for Drupal or PHP development using it for multiple project I want to speedup `composer install` by sharing composer cache between projects as if I run composer on host.

Currently I can do it by this setting in .lando.yml for all projects:
```
services:
  appserver:
    overrides:
      services:
        volumes:
          - ${HOME}/.lando/composer_cache:/var/www/.composer
```

Will be nice it this volume will be default in all PHP recipies.
