### ISSUE TITLE
Option to disable or configure the url scanner

### ISSUE THREAD

**Issue by vincenzo** [lando/lando#1207]
Feature Request
===============

AS a LANDO USER
I WANT the option to disable the container health checks on `lando start`
SO THAT the starting up of containers feels more rapid

## Rationale

The rationale behind this is that more often than not the services are ready to be used way before Lando comes back with `Your app has started up correctly`. This is normally ok, unless you have a team of very impatient and restless people, and a dev environment made up of several apps and services, not just one.

Incidentally, I have observed that while Lando waits for the services to be up and running, the CPU is at high usage, probably due to checks done a in a polling fashion? So this option would alleviate CPU usage too. 

Of course this is an option for "people who know what they're doing and are willing to take the risk".

## The way I see it working

I can see this working with a switch `--no-health-checks`, which causes Lando to skip the checks and present the end user with the usual relevant URLs for the service, but this time printed in white (neutral colour, as Lando hasn't checked them), accompanied with a message that says something like

> Service *should* be ready, but you have disabled checks, so Lando doesn't know for sure -- Give it a try

(ok, maybe not like that, but you get the gist)

**Comment by vincenzo** [comment]
Just realised that Lando hangs a lot with the healtchecks for apps that have a red `localhost:xyzw` url (though the ones specified via the proxy section in the config work just fine).

**Comment by sameronline** [comment]
+1 to this, ie: how do i add a service without health checks or even proxy settings? ie:
``` 
services:
  terminus:
    type: compose
    build:
      - "cd /tmp && curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install --install-dir=~/ --bin-dir=/usr/bin"
    services:
      image: composer
      command: terminus
```
How do i add something like that? that has no port exposed and only cli tool, so i want to do is:
1. disable proxy/routing to that container
2. disable health checks

**Comment by sameronline** [comment]
``` 
  node:
    type: compose
#    We should use lando's globals configs to install yarn/glup but it does not work due to permission issues
#    @see :https://www.screencast.com/t/wr7hbFeRH
#    globals:
#      yarn: "latest"
#      gulp-cli: "latest"
#   Using install_dependencies_as_root: as sudo instead for now
    install_dependencies_as_root:
      - "sudo npm i -g yarn gulp-cli"
    services:
      # @see https://github.com/thecodingmachine/docker-images-php
      image: thecodingmachine/php:7.2-v1-cli-node10
      # entrypoint from https://github.com/thecodingmachine/docker-images-php/blob/7.2-v1/Dockerfile.cli.node10
      command: /usr/local/bin/docker-entrypoint.sh
      environment:
        PHP_INI_MEMORY_LIMIT: 1g
      healthcheck:
        disable: true
      ports:
        - "3000:3000"
        - "3001:3001"
```
I expected that to at least disable healtchecks per https://docs.docker.com/compose/compose-file/#healthcheck but that didn't work.

Any ideas?
