### ISSUE TITLE
¿Cómo Instalar phppgadmin en lando?

### ISSUE THREAD

**Issue by joel7** [lando/lando#1208]
**¿Cómo puedo instalar phppgadmin ? (How can I install phppgadmin?)**

***Version of lando:**
	v3.0.0-beta.47

***Un ejemplo, pero no funciona** (An example, but it does not work): file ".lando.yml"
```
name: proy1laravel57
recipe: laravel
proxy:
  appserver:
    - proy1-laravel57.test
config:
  php: '7.2'
  webroot: proyecto1/public
  xdebug: true
services:
  appserver:
    extras:
      - apt-get update
      - apt-get install phppgadmin
  tswift:
    type: postgres
    portforward: 5444
    creds:
      user: joel
      password: joel
      database: laravel57pg
```
