### ISSUE TITLE
Compose service - error: (HTTP code 500) server error - container ### is not connected to the network lando_bridge_network

### ISSUE THREAD

**Issue by sameronline** [lando/lando#1212]
My .lando.yml file has this service as type: compose

```yaml
  node:
    type: compose
    services:
## @see https://github.com/thecodingmachine/docker-images-php/blob/7.2-v1/Dockerfile.cli.node10
      image: thecodingmachine/php:7.2-v1-cli-node10
      command: /usr/local/bin/docker-entrypoint.sh php
      ports:
        - "3000:3000"
        - "3001:3001"
```
on  ```bash lando rebuild ``` or ```bash lando start ``` I end up with this error

``` (HTTP code 500) server error - container CONTAINERID is not connected to the network lando_bridge_network ```

ie: ```  (HTTP code 500) server error - container 384e2d8c9c89413e1853824111f3d5c634fff962d0a9ef57e7146af5f
0cc4dfc is not connected to the network lando_bridge_network ```

My system is:
- Windows 10 Pro: 10.0.17134 Build 17134
- Docker: 18.06.1-ce-win73 (19507)
