### ISSUE TITLE
Invalid $LAND_INFO JSONobject

### ISSUE THREAD

**Issue by sameronline** [lando/lando#1214]
I have that .lando.yml file with the following services
``` yaml
name: TTT
recipe: drupal8
config:
  via: apache
  php: '7.2'
  webroot: web
  drush: path:/app/vendor/bin/drush
  drupal: false
  conf:
    database: .lando/mysql/config
    php: .lando/php/config/TTT.ini
proxy:
  solr:
    - admin.solr.TTT.lndo.site:8983
services:
  appserver:
    install_dependencies_as_root:
      - "docker-php-ext-install sockets"
      - "composer global config bin-dir /usr/bin"
    composer:
      pantheon-systems/terminus: "*"
  solr:
    type: solr:custom
    core: TTT
    config:
      conf: web/modules/custom/TTT_search/solr-conf
    overrides:
      services:
        image: library/solr:7.4-alpine
  node:
    type: compose
#    We should use lando's globals configs to install yarn/glup but it does not work due to permission issues
#    @see: https://www.screencast.com/t/wr7hbFeRH
#    globals:
#      yarn: "latest"
#      gulp-cli: "latest"
#   Using install_dependencies_as_root: as sudo instead for now
    install_dependencies_as_root:
      - "sudo npm i -g yarn gulp-cli"
    services:
      # @see https://github.com/thecodingmachine/docker-images-php
      image: thecodingmachine/php:7.2-v1-cli-node10
      # entrypoint from https://github.com/thecodingmachine/docker-images-php/blob/7.2-v1/Dockerfile.cli.node10
      command: /usr/local/bin/docker-entrypoint.sh
      environment:
        PHP_INI_MEMORY_LIMIT: 500M
tooling:
  terminus:
    service: appserver
  drupal:
    service: appserver
    cmd:
      - /app/vendor/bin/drupal
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  gulp:
    service: node
  git:
    service: appserver
```
Before lando's RC1 i was able to parse $LANDO_INFO as valid json at php level

After RC1 PHP failed to process it after investigation i found out this https://www.screencast.com/t/oa5QyJlgQ3W

the $LAND_INFO is not a valid JSON syntax so we can't process 

To avoid having this issue again, for now i used this on my php
```` php
if (getenv('LANDO_INFO') && $lando_info = json_decode(getenv('LANDO_INFO'), TRUE)) {
  if (isset($lando_info['database']) && !empty($lando_info['database'])) {
    $databases['default']['default'] = [
      'driver' => 'mysql',
      'database' => $lando_info['database']['creds']['database'],
      'username' => $lando_info['database']['creds']['user'],
      'password' => $lando_info['database']['creds']['password'],
      'host' => $lando_info['database']['internal_connection']['host'],
      'port' => $lando_info['database']['internal_connection']['port'],
    ];
    $settings['hash_salt'] = md5(getenv('LANDO_HOST_IP'));
  }
````

Any idea why the LANDO_INFO is not valid json string?
