### ISSUE TITLE
Assignment to constant variable line 41ish for pantheon.js

### ISSUE THREAD

**Issue by sameronline** [lando/lando#1221]
There is an issue since RC1  when you try to init terminus command on a container , it looks like the pantheon recipe is always enabled which causes several issues

Example .lando.yml
```yml
name: terminus-test
services:
  terminus:
    type: php:7.0
    via: cli
    xdebug: false
    build:
    - "cd $HOME && curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install --install-dir=$HOME --bin-dir=/bin"
tooling:
  terminus:
    service: terminus
```
Now try to run:
```bash
 lando terminus auth:login --machine-token=$(MACHINE_TOKEN)
```
This results in error like this: https://www.screencast.com/t/kB7plEAPzWr

The only solution to pass this error is to use tooling example like this:
```yml
tooling:
  anything:
    service: terminus
    cmd: terminus
```
running the below works fine now:
```bash
 lando anything auth:login --machine-token=$(MACHINE_TOKEN)
```

I'm pretty sure that this relates to https://github.com/lando/lando/blob/85dc5ff0bb550842d88e85fd2b06970ac72f31ec/plugins/lando-recipes/recipes/pantheon/pantheon.js#L35-L52

I don't understand why the pantheon recipe though is executing while i have no reference to it in my yml
