### ISSUE TITLE
[v3.0.0-rc.1] Permission issue with node service - Pantheon recipe

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#1223]
```bash
Creating mysite_node_1 ... done
Unhandled rejection Error: EACCES: permission denied, mkdir '/.npm'5cf2e15b5bdb


┌──────────────────────────────────────────────┐
│           npm update check failed            │
│     Try running with sudo or get access      │
│     to the local update config store via     │
│ sudo chown -R $USER:$(id -gn $USER) /.config │
└──────────────────────────────────────────────┘
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
error: Looks like one of your build steps failed with [object Object]
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
```
System specs:
```bash
$ uname -a
Linux Lenovo-Y70-70-Touch 4.15.0-33-generic #36~16.04.1-Ubuntu SMP Wed Aug 15 17:21:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya
$ lando version
v3.0.0-rc.1
$ docker -v
Docker version 18.06.1-ce, build e68fc7a
$ docker-compose -v
docker-compose version 1.22.0, build f46880fe
```
Contents of `.lando.yml`:
```yml
name: mysite
recipe: pantheon
config:
  framework: drupal8
  site: mysite
  id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  webroot: web 
  drush: ^8

# add additional auxiliary services
services:
  node:
    type: node:8.9
    overrides:
      services:
        ports:
          - 3000:3000
          - 3001:3001
tooling:
  node:
    service: node
    description: "Run node.js commands"
  npm:
    service: node
    description: "Run npm commands"
```
