### ISSUE TITLE
Nginx timeout in Drupal 8 recipe (and probably drupal 7)

### ISSUE THREAD

**Issue by hkirsman** [lando/lando#1226]
Drupal 8 can be really slow during first loads (in our case module listing page) and it can exceed 60 seconds which is the default timeout of nginx: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout.

I'm not sure how important it is to add also fastcgi_read_timeout but I saw it here in pantheon recipe. https://github.com/lando/lando/blob/80454d184e7a0108c825022edf87c19693eea2b3/plugins/lando-recipes/recipes/pantheon/nginx.conf: 

Anyways, when we got the latest drupal8.conf and added these next lines then site loaded over 60 seconds but the error was gone and page shows Drupal 8:
```
proxy_read_timeout 900s;
fastcgi_read_timeout 900s;
```

How could you test this? Do some custom php page, add sleep(5); and set the proxy_read_timeout + fastcgi_read_timeout to 1s.

**Comment by killua99** [comment]
enabling xdebug make me have 504 too

**Comment by ericpugh** [comment]
Just in case it's helpful, I've added some string replacement commands to tweak the PHP-FPM settings. (using the drupal8 recipe):
```
services:
  appserver:
    build_as_root:
      - echo "Updating PHP-FPM settings ..."
      - sed -i 's/pm.max_children = 5/pm.max_children = 128/g' /usr/local/etc/php-fpm.d/www.conf
      - sed -i 's/pm.min_spare_servers = 1/pm.min_spare_servers = 32/g' /usr/local/etc/php-fpm.d/www.conf
      - sed -i 's/pm.max_spare_servers = 3/pm.max_spare_servers = 64/g' /usr/local/etc/php-fpm.d/www.conf
      - sed -i 's/pm.start_servers = 2/pm.start_servers = 32/g' /usr/local/etc/php-fpm.d/www.conf
      - sed -i 's/;pm.max_requests = 500/pm.max_requests = 500/g' /usr/local/etc/php-fpm.d/www.conf
```
