### ISSUE TITLE
WPML - third level domain issue

### ISSUE THREAD

**Issue by davideprevosto** [lando/lando#1230]
Hi there,

I am using the last version of **lando** and I would like to setup a simple **WordPress** single installation, using WPML and third level domain:

1. example.test
2. fr.example.test
3. it.example.test

This was my original recipe:

```
name: myproject
recipe: wordpress
config:
  php: '7.2'
  via: nginx
  database: mariadb
  xdebug: true
  webroot: .
proxy:
  nginx:
  - example.test
mailhog:
  - mailhog.test
proxyDomain: test
services:
  database:
    type: mariadb
    portforward: 3306
    creds:
      user: homestead
      password: secret
      database: example
  mailhog:
    type: mailhog
    hogfrom:
    - appserver
    portforward: 1026
```

I did try to follow docs and issues on GitHub but I wasn't able to run fr.example.test or it.example.test (example.test it works fine).

I added appserver section to proxy... but I wasn't lucky.

Anyone should help? I am pretty sure WordPress is working fine, as I can run the same project with Local By Flywheel (for example).

Cheers
