### ISSUE TITLE
lando share command not working in rc.1

### ISSUE THREAD

**Issue by tanc** [lando/lando#1231]
Bug Report
==========

**Tell us about your setup**

Lando: v3.0.0-rc.1
OS: MacOS 10.14 (18A391)

**Tell us about your `.lando.yml`**

```yml
# The name of the app
name: share

# Give me http://share.lndo.site and https://share.lndo.site
proxy:
  appserver:
    - share.lndo.site

# Set up my services
services:

  # Set up a basic webserver running the latest nginx with ssl turned on
  appserver:
    type: nginx:1.12
    ssl: true
    webroot: www
```

**Tell us about the command you were running**

```
lando start
lando share -u http://localhost:32802
```

**Tell us about the error you got**

```
error: Assignment to constant variable.
```

**Tell us generally about your bug**

This has started happening since rc.1 version. Functional test to follow.
