### ISSUE TITLE
Node container GID and UID not matching local user's on Ubuntu

### ISSUE THREAD

**Issue by agilec-paul** [lando/lando#1240]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?
v3.0.0-rc.1 on Ubuntu 18.04

**Tell us about your `.lando.yml`**
The config does contain a custom image however that is not the cause of the issue as I get this problem without it too.
```yml
name: myproject # Insert the project name here in the format [client][project], i.e. oxfammain.
recipe: drupal8
config:
  xdebug: true
  webroot: web
  php: '7.0'
  conf: 
    php: .vscode/php.ini
proxy:
  mailhog:
    - mail.myproject.lndo.site
services:
  database:
    creds:
      user: database
      password: database
      database: database
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
  node:
    type: node:carbon
    build:
      - "if [ -d $LANDO_MOUNT/web/themes/custom/site_theme ]; then cd $LANDO_MOUNT/web/themes/custom/site_theme && yarn install --production; fi"
    overrides:
      services:
        image: agilecollective/lando-node:latest
        ports: [3070:3070] # You should change this port to something random and then update gulpconfig.js in the theme to match
tooling:
  npm:
    service: node
  yarn:
    service: node
  node:
    service: node
  gulp:
    service: node
  backstop:
    service: node
```
My php.ini is set only for xdebug:
```php
[PHP]

;;;;;;;;;;;;;;;
;IMPORTANT;
;PLACE THIS FILE UNDER .vscode folder;
;SO IT DOESNT GET COMMITTED;
;;;;;;;;;;;;;;;

; Xdebug
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
# Extra custom Xdebug setting for debug to work in VSCode.
xdebug.remote_enable = 1 
xdebug.remote_autostart = 1 
```

**Tell us about the command you were running**
`lando rebuild` or any command that would cause the node container to be rebuilt, meaning a `lando start` can also cause the issue.

**Tell us about the error you got**

The ownership permissions of my `~/.ssh` folder get's changed from `$User $User` to `$User www-data` as the node container is changing the group to www-data.

```bash
-rw-r--r--  1 paul www-data   397 Jan  5  2018 id_rsa.pub
```

**Tell us generally about your bug**

Locally my UID/GID is 1000, that is expected. The appserver container returns

```bash
uid=1000(www-data) gid=1000(www-data) groups=1000(www-data)
``` 
when running `id`.

However running `id` in the node container (`lando ssh node`) returns:
```bash
uid=1000(www-data) gid=33(www-data) groups=33(www-data)
```
Which is locally is assigned to the www-data group/user. This process seems to change ownership based on the GID, changing the www-data user's GID to something else still maps my folder to 33.

Not running node does not cause this issue.
