### ISSUE TITLE
SOLR core not created

### ISSUE THREAD

**Issue by MarkWittens** [lando/lando#1249]
**Tell us about your setup**
Lando v3.0.0-rc.1 on Mac OS HighSierra

**Tell us about your `.lando.yml`**
```yml
name: mysite
recipe: drupal8
config:
  webroot: ./public_html
  xdebug: true
  php: 7.1
proxy:
  appserver:
    - mysite.lndo.site
    - mysite.192.168.100.*.xip.io
  mailhog:
    - mail.mysite.lndo.site
  solr:
  - solr.lndo.site:8983
services:
  database:
    type: mysql:5.7
    creds:
      database: local_mysite
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  solr:
    type: solr:7.1
    core: solr
    config:
      conf: ./public_html/modules/contrib/search_api_solr/solr-conf/7.x
```
**Tell us generally about your bug**
SOLR instance is created but without a core, when I try to add a core manually I get an error:

Error CREATEing SolrCore 'new_core': Unable to create core [new_core] Caused by: Can't find resource 'solrconfig.xml' in classpath or '/opt/solr/server/solr/new_core'

**Tell us more**
This has worked before with the same config. Not sure what version of Lando it was.
