### ISSUE TITLE
Prisma as Compose service

### ISSUE THREAD

**Issue by cloudsociety** [lando/lando#1253]
I'm trying to use Prisma to develop GraphQL applications. The Prisma CLI generates a docker-compose file. The docker-compose file works as expected (when using a Heroku Postgres server). I tried to integrate that into Lando using the _compose_ service, but I get an error on `lando start`:

```
error: (HTTP code 409) unexpected - Container bd895e96fed4dbef223c5b1b0e472b0eede716920e198bb5ed4256c05807f549 is restarting, wait until the container is running
```

**The container never actually restarts. It gets "stuck" such that even `lando poweroff` doesn't kill the container. I end up having to `docker rm [containerID]`.

## Machine

2016 MBP
High Sierra
Lando v3.0.0-rc.1

## My _.lando.yml_ file

I've tried to set up a Node/Prisma/Postgres stack using this file (where Prisma is pointing to that Postgres service):

```yml
# The name of my app
name: prisma

# Use the lando proxy to map to the custom service
proxy:
  prisma:
    - prisma.lndo.site
  postgres:
    - postgres.lndo.site

services:
  prisma:
    type: compose
    portforward: 4466
    services:
      image: prismagraphql/prisma:1.12
      restart: always
      ports:
      - "4466:4466"
      environment:
        PRISMA_CONFIG: |
          port: 4466
          # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
          # managementApiSecret: my-secret
          databases:
            default:
              connector: postgres
              host: 'postgres.lndo.site'
              port: '5432'
              database: prismadb
              user: prismadb
              password: prismadb
              migrations: true
  node:
    type: node
    globals:
      prisma: "latest"
  postgres:
    type: postgres:10.1
    portforward: 5432
    creds:
      user: prismadb
      password: prismadb
      database: prismadb
tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  prisma:
    service: node
```

## The original docker-compose file

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: [HOST]
            port: '5432'
            database: [DATABASE]
            user: [USERNAME]
            password: [PASSWORD]
            migrations: true
            ssl: true
```

**I feel like the Lando file should just work, but I'm probably missing one little thing that links it all up. If anyone has insight into what I'm missing, please teach me.**

**Comment by cloudsociety** [comment]
No joy. I still get the same error. Is there any chance the `|` after _ PRISMA_CONFIG _ is causing Lando some trouble? I've heard people complaining about that in the Prisma forums, but there's not a lot of consensus about how to work around it (a passing reference to _PRISMA_CONFIG_PATH_ but no documentation on it).

**Comment by kristoftorfs** [comment]
The `command` option for compose services is required, take a look at the example at https://docs.devwithlando.io/services/compose.html.

**Comment by cloudsociety** [comment]
Thank you, @kristoftorfs. That did get me past that error. Now, I just need to sort out a "Bad Gateway/Could not connect to server" for the Prisma container. 😞 

I'll keep plugging away at it. Probably just pointing to the wrong URL in the Prisma config (currently set to `http://localhost:4466`, but I've tried every url Lando has given me). Current code is this:

```
# The name of my app
name: prisma

# Use the lando proxy to map to the custom service
proxy:
  prisma:
    - prisma.lndo.site
  postgres:
    - postgres.lndo.site

services:
  prisma:
    type: compose
    portforward: 4466
    services:
      image: prismagraphql/prisma:1.12
      command: "/bin/sh -c /app/start.sh"
      depends_on:
      - postgres
      restart: always
      ports:
      - "4466:4466"
      environment:
        PRISMA_CONFIG: |
          port: 4466
          databases:
            default:
              connector: postgres
              host: postgres
              port: '5432'
              database: prismadb
              user: prismadb
              password: prismadb
              migrations: true
  node:
    type: node
    globals:
      prisma: "latest"
  postgres:
    type: postgres:10.1
    portforward: 5432
    creds:
      user: prismadb
      password: prismadb
      database: prismadb
tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  prisma:
    service: node
```
