### ISSUE TITLE
Prisma as Compose service

### ISSUE THREAD

**Issue by cloudsociety** [lando/lando#1254]
I'm trying to use Prisma to develop GraphQL applications. The Prisma CLI generates a docker-compose file. The docker-compose file works as expected (when using a Heroku Postgres server). I tried to integrate that into Lando using the _compose_ service, but I get an error on `lando start`:

```
error: (HTTP code 409) unexpected - Container bd895e96fed4dbef223c5b1b0e472b0eede716920e198bb5ed4256c05807f549 is restarting, wait until the container is running
```

## My _.lando.yml_ file

I've tried to set up a node,prisma,postgres stack using this file:

```yml
# The name of my app
name: prisma

# Use the lando proxy to map to the custom service
proxy:
  prisma:
    - prisma.lndo.site
  postgres:
    - postgres.lndo.site

services:
  prisma:
    type: compose
    portforward: 4466
    services:
      image: prismagraphql/prisma:1.12
      restart: always
      ports:
      - "4466:4466"
      environment:
        PRISMA_CONFIG: |
          port: 4466
          # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
          # managementApiSecret: my-secret
          databases:
            default:
              connector: postgres
              host: 'postgres.lndo.site'
              port: '5432'
              database: prismadb
              user: prismadb
              password: prismadb
              migrations: true
  node:
    type: node
    globals:
      prisma: "latest"
  postgres:
    type: postgres:10.1
    portforward: 5432
    creds:
      user: prismadb
      password: prismadb
      database: prismadb
tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  prisma:
    service: node
```

## The original docker-compose file

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: [HOST]
            port: '5432'
            database: [DATABASE]
            user: [USERNAME]
            password: [PASSWORD]
            migrations: true
            ssl: true
```

**I feel like the Lando file should work but seem to be missing something. If someone could give me a nudge in the right direction, I'd appreciate it.**
