### ISSUE TITLE
Allow custom services to specify that they don't need a URL

### ISSUE THREAD

**Issue by cboyden** [lando/lando#1263]
Feature Request
===============
As a lando user who creates custom services with `compose`, I want to be able to specify that my custom service does not need a URL.

I am switching from docker-compose.yml to the `compose` method of creating custom services. When I set up my chromedriver service this way, Lando assumes that it should have a URL. When the app finishes building, it shows a red URL for chromedriver. Because that service doesn't need to have a URL, I'd rather have Lando not bother trying to set one up. (Lando already seems to know that `database` and `node` services don't need URLs by default.)

Section of .lando.yml:
```
services:
  chromedriver:
    type: compose
    services:
      image: robcherry/docker-chromedriver:latest
      volumes:
        - ${LANDO_APP_ROOT}/:/app/
      expose:
        - "4444"
      environment:
        CHROMEDRIVER_WHITELISTED_IPS: ""
        CHROMEDRIVER_URL_BASE: "/wd/hub"
      security_opt:
        - seccomp:unconfined
      command: ["/usr/local/bin/supervisord", "-c", "/etc/supervisord.conf"]
```

Results of lando rebuild:
```
BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME               openberkeley7
 LOCATION           /Users/cboyden/Sites/test/openberkeley-7
 SERVICES           appserver, nginx, database, pma, node, chromedriver
 NGINX URLS         https://localhost:32962
                    http://localhost:32963
                    http://openberkeley7.localhost
                    https://openberkeley7.localhost
 PMA URLS           http://localhost:32965
                    http://pma.openberkeley7.localhost
                    https://pma.openberkeley7.localhost
 CHROMEDRIVER URLS  http://localhost:32964
```
and imagine that the CHROMEDRIVER URL is red instead of green...
