### ISSUE TITLE
MySQL cannot connect from outside

### ISSUE THREAD

**Issue by vielhuber** [lando/lando#1280]
.lando.yml

```
name: test

proxy:
  appserver:
    - test.local.vielhuber.de

services:
  appserver:
      type: php:7.2
      via: apache
      ssl: true
  database:
    type: mysql:5.7
    portforward: 5000
    creds:
      user: root
      password: root
      database: test
```

```
lando start
````

Everything starts. But when I try to connect to the database e.g. via Navicat with Host: localhost and Port 5000, I get the message:

2013 - Lost connection to MySQL server at 'reading initial communication packet', system error: 0 "Internal error/check (Not system error)".
