### ISSUE TITLE
phpmyadmin: mysqli_real_connect(): (HY000/2002): Connection refused

### ISSUE THREAD

**Issue by vielhuber** [lando/lando#1281]
```
.lando.yml

name: test

proxy:
  appserver:
    - test.local.tld.com
  pma:
    - phpmyadmin-test.local.tld.com

services:
  appserver:
      type: php:7.2
      via: apache
      ssl: true
      webroot: .
  database:
    type: mysql:5.7
    portforward: true
    creds:
      user: root
      password: root
      database: test
  pma:
      type: phpmyadmin:4.7
      hosts:
       - database
```

I get the error:

 mysqli_real_connect(): (HY000/2002): Connection refused

When I remove the "creds" part in the database section, everything works.

I also tried to add

      overrides:
        services:
          environment:
              PMA_USER: root
              PMA_PASSWORD: root

to the pma section, but it still fails.

I appreciate any help!
