### ISSUE TITLE
Drush connection refused on Drupal 8

### ISSUE THREAD

**Issue by kevinquillen** [lando/lando#1286]
.lando.yml:

```
name: SITE1
recipe: drupal8
config:
  webroot: docroot
  php: 7.1
  xdebug: true
  conf:
    php: tools/lando/conf/php/php.ini
services:
  appserver:
    run:
      - "mkdir -p ~/.drush/sites"
      - "ln -sf /app/drush/sites/dev.site.yml ~/.drush/sites/dev.site.yml"
      - "ln -sf /app/drush/sites/test.site.yml ~/.drush/sites/test.site.yml"
      - "ln -sf /app/drush/sites/prod.site.yml ~/.drush/sites/prod.site.yml"
      - "ln -sf /app/drush/sites/local.site.yml ~/.drush/sites/local.site.yml"
      - "ln -sf /app/drush/sites/simpletest.site.yml ~/.drush/sites/simpletest.site.yml"
    run_as_root:
      - 'printf "%s\t%s\n" "127.0.0.1" "$LANDO_APP_NAME.$LANDO_DOMAIN" >> /etc/hosts'
      - 'printf "%s\t%s\n" "127.0.0.1" "SITE2.$LANDO_DOMAIN" >> /etc/hosts'
      - 'printf "%s\t%s\n" "127.0.0.1" "simpletest.$LANDO_DOMAIN" >> /etc/hosts'
  cache:
    type: memcached:1.4
  database:
    portforward: 3307
  database_foo:
    type: mysql
    portforward: 3308
    creds:
      user: drupal8
      password: drupal8
      database: drupal8_foo
  database_simpletest:
    type: mysql
    portforward: 3309
    creds:
      user: drupal8
      password: drupal8
      database: drupal8_test
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: 1026
proxy:
  appserver:
    - SITE1.lndo.site
    - SITE2.lndo.site
    - simpletest.lndo.site
  mailhog:
    - mailhog.lndo.site
```

Drush commands to the local site fail, all of them fail, with:

`ssh: connect to host SITE1.lndo.site port 22: Connection refused`

Drush commands to remote sites works.

Drush site yml:

```
local:
  host: SITE1.lndo.site
  options: { }
  root: /app/docroot
  uri: 'http://SITE1.lndo.site'
```

No idea what else to do here. The only log in the `lando logs` output that I see after trying Drush is:

```
[Thu Nov 08 20:28:34.670504 2018] [php7:notice] [pid 183] [client 172.18.0.2:44946] PDOException: SQLSTATE[HY000] [2002] Connection refused in /app/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /app/docroot/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(420): PDO->__construct('mysql:host=data...', 'drupal8', 'drupal8', Array)\n#1 /app/docroot/core/lib/Drupal/Core/Database/Database.php(371): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /app/docroot/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /app/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /app/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(260): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /app/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /app/docroot/core/lib/Drupal/Core/DrupalKernel.php(519): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /app/docroot/core/lib/Drupal/Core/DrupalKernel.php(880): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /app/docroot/core/lib/Drupal/Core/DrupalKernel.php(472): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /app/docroot/core/lib/Drupal/Core/DrupalKernel.php(668): Drupal\\Core\\DrupalKernel->boot()\n#13 /app/docroot/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
```
