### ISSUE TITLE
Feature request: Add pull-code, pull-db and pull-files commands for the Pantheon recipe

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#1287]
Can something like the following eventually become standard in every Pantheon recipe?
```
tooling:
  pull-code:
    service: appserver
    cmd: '/helpers/pull.sh --code=dev --database=none --files=none'
  pull-db:
    service: appserver
    cmd: '/helpers/pull.sh --code=none --database=dev --files=none'
  pull-files:
    service: appserver
    cmd: '/helpers/pull.sh --code=none --database=none --files=dev'
```
