### ISSUE TITLE
Getting 404 in web browser when accessing lando site

### ISSUE THREAD

**Issue by jasonpierson** [lando/lando#1298]
**Tell us about your setup**

`v3.0.0-rc.1 on Mac version 10.14.1`

**Tell us about your `.lando.yml`**

```yml
name: awananetwork
recipe: pantheon
config:
  framework: wordpress
  site: awananetwork
  id: [site ID removed for anonymity]
proxy:
  mailhog:
    - mailhog.awananetwork.lndo.site
services:
  appserver:
    config:
      server: nginx.conf
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
```

_pantheon.yml_

```# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1
```

**Tell us about the command you were running**

`lando start`

**Tell us about the error you got**

The URLs in the `EDGE URLS` and `EDGE_SSL URLS` sections were in red.
 ```
EDGE URLS      http://localhost:32797                                            
                http://awananetwork.lndo.site                                     
                https://awananetwork.lndo.site 
EDGE_SSL URLS  https://localhost:32798
```
**Tell us generally about your bug**

When I try to go to `http://awananetwork.lndo.site` or `https://awananetwork.lndo.site` in Chrome or Firefox in either a regular or private/incognito window, I get a 404 error.

This has been working for several months and stopped working about a week ago. I tried completely removing both docker and lando and reinstalling, but still have the same issue. There haven't been any software updates or upgrades that I am aware of lately that would've caused this. I updated OSX a few weeks ago and everything worked fine up until about a week ago.
