### ISSUE TITLE
Laravel storage symlink is not working

### ISSUE THREAD

**Issue by manojhl** [lando/lando#1300]
```bash
lando artisan storage:symlink
```

```bash
```

`.lando.yml`
```yml
name: laravel-31
recipe: laravel
config:
  via: nginx
  php: "7.2"
  xdebug: true
  webroot: public_html
```

Local setup MacOS Mojave 10.14.1
