### ISSUE TITLE
[Support or Feature Request] Install Java JDK

### ISSUE THREAD

**Issue by Shurrir** [lando/lando#1312]
Is there a way to install Java on a Lando container?
Can I add this to the lando.yml file somehow?
Or should I install it like you install Java on Linux? Using apt-get and all? Is this persistent or will I have to re-install is every time?

I use Lando for Drupal development and we'd like to start using Behat testing, which requires a Selenium server, which requires Java?
This is all very new to me, so all tips & advice is welcome!

I can imagine more Drupal devs will need this feature for Behat testing.

**Comment by Shurrir** [comment]
I tried adding install_dependencies_as_root:
but nothing seems to happen!

Tried several rebuilds, restarts and even destroy & start & rebuild.

```
name: xxx
recipe: drupal8
config:
  php: '7.2'
  via: apache
  webroot: www
  drush: global:8.1.15
  xdebug: true
proxy:
  appserver:
    - xxx.lndo.site
services:
  appserver:
    install_dependencies_as_root:
      - apt-get update -y
      - apt-get install openjdk-8-jdk -y
  pma:
    type: phpmyadmin:4.6
    hosts:
      - database
  database:
    type: mysql:5.7
    creds:
      user: xxx
      password: xxx
      database: xxx
```

**Comment by agilec-paul** [comment]
@Shurrir I haven't tried this locally but have you tried installing it manually? Then you could figure out where the issue is.

Assuming your containers are working as expected:
`lando ssh appserver` and then run your commands to install the JDK and try to debug from there.

However I don't think you need Java for Behat + Selenium. I've set up my Lando file to use Behat and PhantomJS for headless testing.

I see that you're using D8 as well so you can try copying my setup:  
This is my `require-dev` in my composer.json file

```json
"require-dev": {
        "behat/mink": "~1.7",
        "behat/mink-goutte-driver": "~1.2",
        "behat/behat": "3.3.1",
        "behat/gherkin": "4.4.5",
        "jcalderonzumba/gastonjs": "~1.0.2",
        "jcalderonzumba/mink-phantomjs-driver": "~0.3.1",
        "mikey179/vfsStream": "~1.2",
        "phpunit/phpunit": "~4.8",
        "symfony/css-selector": "~2.8",
        "drupal/drupal-extension": "~3.0",
        "guzzlehttp/guzzle" : "^6.0@dev"
    },
```
The key packages are the behat ones and the phantomjs driver ones then install these through composer.

Then you should have a Features folder and a `behat.yml` file that looks similar to this
```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2:
        wd_host: "http://localhost:8643/wd/hub"
      base_url: http://mysite.lndo.site
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drush:
        root: "/app/web"
      drupal:
        drupal_root: "/app/web"
      selectors:
        error_message_selector: '.status--error'
        success_message_selector: '.status--success'
      region_map:
        content: ".main-content"
        header: ".site-header"
        footer: ".site-footer"
        admin_content: "#block-adminimal-theme-content"
```
Finally my lando.yml file contains
```
appserver:
    run_as_root:
      - "apt-get update -y"
      - "apt-get install build-essential chrpath libssl-dev libxft-dev libfreetype6-dev libfreetype6 libfontconfig1-dev libfontconfig1 -y"
      - "wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2"
      - "tar xvjf /phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /usr/local/share/"
      - "ln -s /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/"
      - "phantomjs --version"
```
In order to install phantomjs on a rebuild, just note that if you rebuild a lot you might get temporarily blocked by the S3 server so you could keep the `.tar.bz2` file locally instead.

And to make running commands easier, under the `tooling:` I have
```behat:
    service: appserver
    description: "Run behat commands"
    cmd:
      - "bin/behat"
  phantomjs:
    service: appserver
    description: "Run PhantomJS commands"
  phantomstart:
    service: appserver
    description: "Start PhantomJS"
    cmd:
      - "phantomjs --webdriver=8643"
```
Otherwise you can ssh into the appserver container and run bin/behat manually.

You don't need PhantomJS, but it's useful for testing JS only functionality in Drupal such as the entity browser. You will also need to start PhantomJS before running any Behat tests with it as the driver needs to run at the same time.

I'll try to answer any questions you have, but I'm not a Behat master.
