### ISSUE TITLE
Second database container doesn't use 'creds' 

### ISSUE THREAD

**Issue by quietone1** [lando/lando#1314]
The credentials given for a second database container are not always used. After searching I found closed issue [#593](https://github.com/lando/lando/issues/593) which is the same problem.

In my case I'm usng a Drupal 8 .lando.yml file.

At first I used this:
```
  migrate:
    type: mariadb:10.3
    creds:
      database: drupal7
    portforward: 13311
```
to see what credentials would be used. But it produced a database called 'database' accessible via `lando mysql -h migrate`. Then I added user and password to the creds, did a rebuild and got the same result.

Then I  did `lando stop`, edited .lando.yml using only a new name for the second database.
```
  migrate2:
    type: mariadb:10.3
    creds:
      database: drupal7
      user: drupal7
      password: drupal7
    portforward: 13311
```
and rebuilt. The container, migrate2 now uses the credentials in the 'creds' property. 

To return to using the name 'migrate' for the container and not 'migrate2' I did `lando destroy`, edit .lando.yml to make the name change and then did `lando start`.

It seems that database, user and password need to be in creds or it will be skipped?

Lando version v3.0.0-rc.1
Debian 9.6
