### ISSUE TITLE
Pantheon D8 sh: 1: ssh: not found on Lando pull or lando drush @pantheon.site.env with local drush

### ISSUE THREAD

**Issue by aaron-capellic** [lando/lando#1315]
Bug Report
==========

**Tell us about your setup**
Lando: v3.0.0-rc.1 ubuntu 16.04

**Tell us about your `.lando.yml`**
```
name: olh
recipe: pantheon
# Uncomment and restart to enable PHPMyAdmin
proxy:
  pma:
    - pma.olh.lndo.site
config:
  framework: drupal8
  site: olh
  id: xxxxxx
  web: web

compose:
  - docker-compose.yml

events:
  post-pull:
    - appserver: cd $LANDO_WEBROOT && drush cc drush && drush sitesan

  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cc drush && drush sitesan

services:
  appserver:
    xdebug: true
    overrides:
      services:
        environment:
          BEHAT_PARAMS: >-
            {"extensions" : {"Behat\\MinkExtension" : {"base_url" :
            "http://nginx/", "files_path" : "/app/testing/features/fixtures/"}, "Drupal\\DrupalExtension" : {"drush" :   {
            "root":  "/app/web" }}}}
          CI_ENV: ci-${CIRCLE_BUILD_NUM}
          PANTHEON_SITE: ${TERMINUS_SITE}
          CIRCLE_BRANCH: ${CIRCLE_BRANCH}
          CIRCLE_USERNAME: ${CIRCLE_USERNAME}
          GIT_EMAIL: ${GIT_EMAIL}
# Uncomment and restart to enable PHPMyAdmin
  pma:
    type: phpmyadmin
    hosts:
      - database
tooling:
  behat:
    service: appserver
    cmd: "/app/vendor/bin/behat --config=/app/tests/behat.yml"


```
docker-compose.yml

```
version: '3'

services:
  chromedriver:
    image: robcherry/docker-chromedriver:latest
    volumes:
      - ${LANDO_APP_ROOT}/:/app/
      - /dev/shm:/dev/shm # See https://github.com/elgalu/docker-selenium/issues/20#issuecomment-325090454
    expose:
      - "4444"
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
      CHROMEDRIVER_URL_BASE: "/wd/hub"
    security_opt:
      - seccomp:unconfined

```
pantheon.yml
```
api_version: 1
web_docroot: true
php_version: 7.2
workflows:
  deploy_product:
    after:
      - type: webphp
        description: Sanitize databse
        script: private/scripts/site_sanitize.php
      -
        type: webphp
        description: 'Run composer prepare-for-pantheon'
        script: private/scripts/deploy_product/prepare-for-pantheon.php
      -
        type: webphp
        description: 'Run composer install & drupal-scaffold'
        script: private/scripts/deploy_product/composer-install.php

  clone_database:
    after:
      - type: webphp
        description: Sanitize database
        script: private/scripts/site_sanitize.php

```

**Tell us about the command you were running**

`lando drush @pantheon.site.env status`

This returns `sh: 1: ssh: not found`

with -vvvv

```lando drush -vvvv @pantheon.olh.dev status
Loaded alias @pantheon.olh.dev from file                                [notice]
/var/www/.drush/pantheon.aliases.drushrc.php
Begin redispatch via drush_invoke_process().                            [notice]
Calling proc_open(ssh -p 2222 -o "AddressFamily inet" dev.xxxxxx@appserver.dev.xxxxxx.drush.in 'drush  --root=/app/web --uri=https://uca.lndo.site --verbose --db-url='\''mysql://pantheon:xxxxx@dbserver.dev.xxxxx.drush.in:17764/pantheon'\''  core-status 2>&1' 2>&1);
sh: 1: ssh: not found
End redispatch via drush_invoke_process().         
```
`lando pull` returns:

```Logged in as aaron@capellic.com
Detected that olh is a drupal8 site
Checking for /lando/keys/pantheon.lando.id_rsa
Destroying all current tables in database... 
Downloading drush aliases...
 [notice] Aliases file written to ~/.drush/pantheon.aliases.drushrc.php.
@pantheon.olh.dev
Clearing remote cache to shrink db size
sh: 1: ssh: not found
 [notice] OK >> dev-olh.pantheonsite.io responded
Pulling database from dev...
  22 B 0:00:00 [36.1 B/s] [<=>                                                 ]
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'sh: 1: ssh: not found' at line 1

Pull complete!
```
**Tell us generally about your bug**

If I run lando ssh, and then run `ssh -p 2222 -o "AddressFamily inet" dev.xxxxxx@appserver.dev.xxxxxx.drush.in 'drush  --root=/app/web --uri=https://uca.lndo.site --verbose --db-url='\''mysql://pantheon:xxxxx@dbserver.dev.xxxxx.drush.in:17764/pantheon'\''  core-status 2>&1' 2>&1` the command succeeds, so it looks like something is happening when `lando` passes in the commandj.

This bug breaks `lando pull`, which breaks our CI process.

**Comment by aaron-capellic** [comment]
When using global drush ssh works as expected.
```config:
  drush: global:8.1.17
```

**Comment by jacine** [comment]
I'm having a similar issue here. I've reinstalled Lando and Docker entirely, deleting `.lando`, resetting Docker, with multiple versions, multiple times, and always end up with the same issue. Currently I have Lando `v3.0.0-rc.1`, with Docker `18.06.1-ce-mac73 (26764)` installed via the dmg, on OS X 10.14.1 (Mojave).

And the above suggestion to add `drush: global:8.1.17` config doesn't help.

With `lando pull`, the files and code steps complete successfully.  The database fails with the error:

```
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'sh: 1: ssh: not found' at line 1
```

Manually pulling the database with [documented commands](https://docs.devwithlando.io/tutorials/pantheon.html#2.-manually-importing-your-db-and-files) via terminus and db-import work, but only `drush uli` and `drush cr` seem to work.  Any other commands that involve bootstrapping, such as `drush cex` complain about not being able to bootstrap Drupal.

```
Command config-export needs a higher bootstrap level to run - you        [error]
will need to invoke drush from a more functional Drupal environment
to run this command.
...
```
This is the status it reports:

```
Drush was attempting to connect to:
 Drupal version         :  8.6.2
 Site URI               :  http://default
 Database driver        :  mysql
 Database hostname      :  database
 Database port          :  3306
 Database username      :  pantheon
 Database name          :  pantheon
 PHP executable         :  /usr/local/bin/php
 PHP configuration      :
 PHP OS                 :  Linux
 Drush script           :  /app/vendor/drush/drush/drush.php
 Drush version          :  8.1.17
 Drush temp directory   :  /tmp
 Drush configuration    :
 Drush alias files      :
 Drupal root            :  /app/web
 Drupal Settings File   :  sites/default/settings.php
 Site path              :  sites/default
 Sync config path       :  /app/config
```
So, there is no bootstrap, database connection, php config, or drush aliases. This is my current Lando file.

```yml
name: [redacted]
recipe: pantheon
config:
  framework: drupal8
  site: [redacted]
  id: [redacted]
  webroot: web
  xdebug: true
  drush: global:8.1.17 
```

I have also tried this without:

```yml
config:
  xdebug: true
  drush: global:8.1.17 
```

And with:

```yml
tooling:
  drush:
    cmd:
      - "drush --root=/app/web --uri=https://[redacted].lndo.site"
```

**Comment by pirog** [comment]
@aaron-capellic @jacine ive seen different flavors of this "binary not found" issue pop up over the last few days and i suspect it has to do with SOMETHING not playing nice with the `PATH`. Could you guys try running `lando ssh appserver -c "env | grep PATH"` and pasting in the output?

**Comment by aaron-capellic** [comment]
```web$ lando ssh appserver -c "env | grep PATH"
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/.composer/vendor/bin```

**Comment by pirog** [comment]
hmmm ok yah that looks about what id expect :/

**Comment by cainaru** [comment]
@pirog, I'm having same errors as @jacine. Running `lando ssh appserver -c "env | grep PATH"` gives me the following:

```
$ lando ssh appserver -c "env | grep PATH"
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/.composer/vendor/bin
```

**Comment by brysonca** [comment]
This error "sh: 1: ssh: not found" shows whenever drush aliases are used.  Simply running `lando drush @pantheon.site.env` will throw it.

**Comment by pirog** [comment]
So *i think* the issue here has to do with some breaking changes in newer versions of Drush 8. 

While we don't think this is fundamentally an issue with Lando, we've got some better drush management handling we plan to roll out in the next release.  in the meantime the workaround that worked for me was to update to the latest drush 9 via composer and set 

```yaml
tooling:
  drush:
    cmd: /app/vendor/bin/drush
```
In my `.lando.yml`

I've also heard that just removing the composer installed drush and using landos globally installed one seems to do the trick as a temp workaround

**Comment by jacine** [comment]
I went back to this yesterday, as other team members were also having issues, and I got it working...

-  **Drush 9**: Using Drush 9 does solve the problem... However, it breaks Behat tests in CircleCI with `Unable to access the response before visiting a page (Behat\Mink\Exception\DriverException)`.  I went down a rabbit hole trying to fix this, and was ultimately unsuccessful. I believe it has something do with backwards incompatible changes in Behat, which [drupal-extension](https://github.com/jhedstrom/drupalextension#backwards-incompatible-changes) dropped support for, and there appear to be dependency conflicts somewhere along the line (IIRC with Symfony versions) that prevent downgrading.   

-  **Global Drush 8.1.16**:  Using global Drush DOES work.  At first it didn't, I think because I had tried `drush: global:8.1.17`, but after changing that and rebuilding it is working for me now.  Below is the current Lando config, which is fully working again (locally and with tests on CI) in case it helps anyone else:

```yml
name: [redacted]
recipe: pantheon
config:
  framework: drupal8
  site: [redacted]
  id: [redacted]
  webroot: web
  php: '7.2'
  xdebug: true
  drush: global:8.1.16
```

Thanks for your help @pirog and @aaron-capellic! 👏

**Comment by ccharlton** [comment]
@jacine your changes worked for me.

**Comment by ccjjmartin** [comment]
I ran into this too I don't have a bin directory and I have a docroot so my solution looked liked this:

`    cmd: /app/vendor/drush/drush/drush --root=/app/docroot`

**Comment by shaal** [comment]
#1317 

@jacine to use drush 9.5 I added these lines to `lando.yml` -
```
tooling:
  drush:
    cmd:
      - /app/vendor/bin/drush
```
