### ISSUE TITLE
setting .lando.yml to use drush 9.5.2 that was set in composer

### ISSUE THREAD

**Issue by shaal** [lando/lando#1317]
Documentation Issue
================

**Tell us about your setup**
Lando v3.0.0-rc.1, Ubuntu 18.10, docker-ce 18.09.0

**Tell us about your `.lando.yml`**
```
name: spiewak
recipe: pantheon
config:
  framework: drupal8
  xdebug: true
  env: dev
  site: spiewak
  id: c1f2d565-ac04-47ad-b2ee-d19bf281e8dc
  drush: composer
```

according to the documentation - https://docs.devwithlando.io/tutorials/drupal8.html#recipe
the above .lando.yml with `drush:composer` should be the correct way to use the drush I set in composer.

I setup drush in composer.json - `"drush/drush": "^9.5"`
after `lando rebuild -y`, running `lando drush cr`, I get this error -
```/usr/bin/env: php: No such file or directory```

(I can run successfully `lando ssh`, and in there `../vendor/bin/drush cr`)

changing `.lando.yml` to 
```
name: spiewak
recipe: pantheon
config:
  framework: drupal8
  xdebug: true
  env: dev
  site: spiewak
  id: c1f2d565-ac04-47ad-b2ee-d19bf281e8dc
tooling:
  drush:
    cmd:
      - /app/vendor/bin/drush
```
now running `lando rebuild -y`, solves the problem.
`lando drush cr` works perfect, it's using drush 9.5.2
