### ISSUE TITLE
Solr errors, Could not load conf for core drupal8

### ISSUE THREAD

**Issue by gitressa** [lando/lando#1319]
Bug Report
==========
After installing a new site with Lando, the Solr core wasn't created.

Ubuntu 16.04
Lando v3.0.0-beta.47

**My `.lando.yml`:**

```yml
name: devsite
recipe: drupal8
config:
  webroot: web

# Get nice URLs for solr service.
proxy:
  search:
    - admin.devsite.lndo.site:8983

# Solr setup - see https://colorfield.be/blog/lando-configuration-solr7-drupal8-search-api-umami-profile
services:
  # Solr
  # Spin up a Solr container called "search".
  search:
    # Use a specific Solr version, same as the default one at the time of writing.
    type: solr:7.1
    # Optionally declare the name of the Solr core.
    # This setting is only applicable for versions 5.5 and above.
    core: drupal8
    # Optionally use custom Solr config files eg (schema.xml and solrconfig.xml).
    # This is relative to the app root (which may be different from your webroot).
    # This should be the directory containing the schema.xml and solrconfig.xml files, not the path to a certain file.
    config:
      conf: web/modules/contrib/search_api_solr/solr-conf/7.x

tooling:
  install-import:
    service: appserver
    description: "Build local dependencies, import config and run database updates"
    cmd: echo starting Drupal installation, config-import and other preparations

# Add in some custom event scripting
events:
  post-install-import:
    appserver: |
      cd $LANDO_WEBROOT # = cd /app/web, alternative: cd /app
      drush site-install --db-url=mysql://drupal8:drupal8@database/drupal8 --account-pass=admin --site-name=$LANDO_APP_NAME -y;

      # PRIVATE folder for uploaded files - set to safe permissions before launch
      chmod -R u+rw sites;

      # get UUID from base install with drush cget system.site uuid: 'system.site:uuid': 2be3702d-e362-44ea-940f-31x1aw2a4147
      drush cset system.site uuid 2be3702d-e362-44ea-940f-31x1aw2a4147 -y;

      # fix an error about shortcut_set, see: https://www.drupal.org/node/2583113
      drush ev '\Drupal::entityManager()->getStorage("shortcut_set")->load("default")->delete();';

      # import configuration
      drush config-import --debug -y;

      ### TRUSTED HOST PATTERNS settings.php
      # insert trusted host pattern domains at the bottom of settings.php:
      echo "/* trusted hosts */\n\$settings['trusted_host_patterns'] = array( '^localhost\$', '^$LANDO_APP_NAME\.lndo.site\$', );" >> sites/default/settings.php

      ### DEVELOPMENT: Disable caching, see https://www.drupal.org/node/2598914
      cp sites/example.settings.local.php sites/default/settings.local.php;
      echo "/* enable debugging */
      \$settings['cache']['bins']['render'] = 'cache.backend.null';
      \$settings['cache']['bins']['dynamic_page_cache'] = 'cache.backend.null';
      \$settings['cache']['bins']['page'] = 'cache.backend.null';
      " >> sites/default/settings.local.php

      echo "/* enable debugging */
      if (file_exists(\$app_root . '/' . \$site_path . '/settings.local.php')) {
        include \$app_root . '/' . \$site_path . '/settings.local.php';
      }" >> sites/default/settings.php

      ### DEVELOPMENT: Set site URL for drush
      echo "DRUSH_OPTIONS_URI=http://$LANDO_APP_NAME.lndo.site" >> ../.env

      # one-time login for admin
      drush cron;
      drush uli /;
```

I was triggering the install and import by running `lando install-import`:
```bash
lando stop && lando destroy -y && lando start && lando install-import
```

The error I got in Solr:
```
drupal8: org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Could not load conf for core drupal8: Can't load schema /opt/solr/server/solr/mycores/drupal8/conf/schema.xml: Plugin init failure for [schema.xml] fieldType "collated": Error loading class 'solr.ICUCollationField'
```
In `web/modules/contrib/search_api_solr/solr-conf/7.x/schema.xml` I removed this:
```
  <fieldType name="collated" class="solr.ICUCollationField"
               locale="en"
               strength="primary"
               caseLevel="false" />
```
Got this error:
```
drupal8: org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Could not load conf for core drupal8: Can't load schema /opt/solr/server/solr/mycores/drupal8/conf/schema.xml: Unknown fieldType 'collated' specified on field sort_*
```
I removed this bit in `web/modules/contrib/search_api_solr/solr-conf/7.x/schema.xml`:
```
  <!-- Sortable version of the dynamic string field. We need to store it for streaming expressions. -->
  <dynamicField name="sort_*" type="collated" indexed="false" stored="false" docValues="true"/>
```
There are no errors now, and the drupal8 Solr core is created. Search doesn't work, but at least the reason for core not getting created is found, and what remains is to fix the issue :-)
