### ISSUE TITLE
Controller edits not updating on frontend (WordPress, Sage9, Sober Controller, webpack) 

### ISSUE THREAD

**Issue by slamorte** [lando/lando#1321]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

*v3.0.0-rc.1 on MacOS*
*WordPress with Sage9 and Sober Controller*
*rendering via yarn/webpack*

**Tell us about your `.lando.yml`**

```
name: truthout4

recipe: wordpress

config:

  php: '7.2'

  via: nginx

  database: mysql:5.7

  xdebug: true

  conf:

    server: ./dev_assets/wordpress-dev-ngnix.conf

services:

  database:

    portforward: 33060

events:

    #  Installs blade generate plugin for WP-CLI
    post-start:
      - appserver: cd $LANDO_WEBROOT &&  wp package install git@github.com:alwaysblank/blade-generate.git
```

**Tell us about the command you were running**

```
lando start
editing a SoberWP controller file
```

**Tell us about the error you got**

Front end not updated.

**Tell us generally about your bug**

```bash
1. Start lando
2. Start webpack with `yarn run start`
3. Edit a Sober Controller file. Example: extend an object with a new key-value pair. 
4. Reload a webpage that is printing the object
5. The object is not updated
```

**Tell us more**

Project tree looks something like this:

Theme folder: `www/wp-content/themes/mytheme/`
Controller files: `www/wp-content/themes/mytheme/app/Controllers/`
Template files: `www/wp-content/themes/mytheme/app/resources/views`

If the container is restarted with `lando stop` and `lando start`, or `lando rebuild`, the webpage correctly displays the updated object. 

Any edits to any template file are correctly applied to the frontend; only Controller files are affected. 

Controller syntax looks like this:

```
  public function siteName()
  {
    return get_bloginfo('name');
  }
```

If I `lando ssh` into the container I see the Controller file is correctly updated; the local file and the container file are identical. But it's as if the file is caches or the object is cached. Memcache does not appear to be enabled, but I could be wrong, I'm new to working with caching. 

Any tips on troubleshooting this will be gladly accepted.
