### ISSUE TITLE
`lando pull` set files directories with the wrong permissions

### ISSUE THREAD

**Issue by shaal** [lando/lando#1325]
Bug Report
==========

**Tell us about your setup**
*v3.0.0-rc.1 on Ubuntu 18.10*

**Tell us about your `.lando.yml`**
```
name: [...]
recipe: pantheon
config:
  framework: drupal8
  xdebug: true
  env: dev
  site: [...]
  id: [...]
tooling:
  drush:
    cmd:
      - /app/vendor/bin/drush
```

After running `lando pull` and choose only *files* from `dev`.

Any image from sites/default/files cannot be opened
```(The requested URL "[...]/sites/default/files/2018-05/S2912_0.jpg" was not found on this server.)```
Unless it's an image that using image_style, and then it opens correctly.

This is what fixed it (need to be done for each directory under /sites/default/files)
* `lando ssh`
* `cd /app/web/sites/default/files/2018-05`
*  `ls -lat` and I see that `2018-05` directory is set to `750` (drwxr-x---)
* `chmod 755 .` fixes the issue (drwxr-xr-x)

This issue does not happen when I manually download the files from pantheon's backup, and open it with `tar xzvf`, in that case all permissions are set correctly.
