### ISSUE TITLE
Mariadb 10.x / can t connect to DB

### ISSUE THREAD

**Issue by kamalkech** [lando/lando#1332]
**lando version :** 
`v3.0.0-beta.47`

**.lando.yml :** 
```
name: my-project
recipe: drupal8
config:
  webroot: .
  via: nginx
  database: mariadb:10.1
```
After start my project successfully, when i try to connect to mysql i get this msg error : 

**lando mysql**
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")`

N.B : 

I already read this doc https://docs.devwithlando.io/issues/switching-dbs.html
`lando destroy && lando rebuild`
But get same error
