### ISSUE TITLE
Feature Request: Support for Acquia's drush aliases

### ISSUE THREAD

**Issue by gmercyutech** [lando/lando#1346]
I wanted to know if there would be any support to add Acquia Cloud's Drush Aliases to Lando.

**Comment by dustinleblanc** [comment]
@gmercyutech What does support entail in your mind? For Acquia projects we've worked in here at Tandem, we've just rolled some scripts that used Acquia CLI and/or aliases already stored in the site repository.

In general, Pantheon is the only provider we have a dedicated recipe for with deep integration, and while I could be wrong, I don't *think* there will be a similar integration for Acquia any time soon. You can certainly use the tools Lando provides to automate downloading of aliases though if you prefer not to commit them to the repo

**Comment by gmercyutech** [comment]
@dustinleblanc I have tried to add the Acquia alias to Lando but with no success.  How would I go about adding the Acquia CLI and/or aliases in the site repository?

**Comment by gmercyutech** [comment]
To add Acquia's Drush aliases (For Drupal 7 using Drush 8):

Follow the steps on downloading the Drush aliases: https://docs.acquia.com/acquia-cloud/manage/ssh/drush/aliases/

Create two folders "**drush**" and "**acquia**" and add the files from the download to the right folder.

![lando](https://user-images.githubusercontent.com/3801028/63190963-67df5500-c035-11e9-9796-b440666009c3.jpg)

Add the following code into you .lando.yml file.

```
services:
  appserver:
    build:
      - /bin/sh -c "mkdir -p ~/.drush"
      - /bin/sh -c "ln -sf /app/drush/[Acquia Instance Name].aliases.drushrc.php ~/.drush/[Acquia Instance Name].aliases.drushrc.php"
      - /bin/sh -c "ln -sf /app/drush/cloudapi.acquia.com.pem ~/.drush/cloudapi.acquia.com.pem"
      - /bin/sh -c "ln -sf /app/drush/acapi.drush.inc ~/.drush/acapi.drush.inc"
      - /bin/sh -c "mkdir -p ~/.acquia"
      - /bin/sh -c "ln -sf /app/acquia/cloudapi.conf ~/.acquia/cloudapi.conf"
```
Rebuild your Lando image and clear your Drush cash and you are done.
