### ISSUE TITLE
Windows 10: Pantheon + Drupal 7 Solr not connecting 

### ISSUE THREAD

**Issue by notserk** [lando/lando#1348]
**Tell us about your setup**

*v3.0.0-beta.47 on Windows 10 Professional*

**Tell us about your `.lando.yml`**

```yml
name: globalwaters
recipe: pantheon
config:
  framework: drupal
  site: globalwaters
  id: ed5cae06-3f07-4dbc-921e-03887cfc1ccf
  xdebug: true
```
Here's my Pantheon.yml file
```yml
# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1
php_version: 7.1

workflows:
#  sync_code:
#    before:
#      - type: webphp
#        description: Disable Workbench
#        script: private/scripts/disable_workbench.php
#    after:
#      - type: webphp
#        description: Clear Cache
#        script: private/scripts/clear_cache.php
  deploy:
    before:
      - type: webphp
        description: Disable Workbench
        script: private/scripts/disable_workbench.php
    after:
      - type: webphp
        description: Clear Cache
        script: private/scripts/clear_cache.php
```

**Tell us generally about your bug**
On Windows 10, I'm running into an issue where the appserver isn't able to connect to the index container. Below is the output of the error:
![pantheron apache solr status fail](https://user-images.githubusercontent.com/1950937/51130730-b3a9f180-17fb-11e9-807f-477f745ad5c9.png)

This affects the ability to index the solr server. 

Modules affected:
- Pantheon Apache Solr Module
- Search API module

This is a symptom of the appserver not being able to connect to the solr container. 

So far this only happens on Windows 10. It works perfectly on MacOS.
