### ISSUE TITLE
Unable to get install_dependencies_as_root  working 

### ISSUE THREAD

**Issue by thegurf** [lando/lando#1354]
v3.0.0-beta.47

**Tell us about your `.lando.yml`**

```yml
name: electronic-docs
recipe: drupal7
config:
  via: apache
  php: '7.1'
  conf: 
    # Tell Lando to use additional PHP settings.
    # The location of this file is arbitrary. 
    # We placed it inside .vscode/ folder simply because we find it convenient.
    # php: .vscode/php.ini
proxy:
  appserver: 
    - dev.docs.xyz.com
services: 
  appserver:
  # Install dependencies for wkhtmltopdf (0.12.5 with qt) and pdftk
    install_dependencies_as_root::
      - "apt update -y"
      - "apt install pdftk -y"
      - "wget https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.jessie_amd64.deb"
      - "dpkg -i wkhtmltox_0.12.5-1.jessie_amd64.deb"
      - "mkdir /tmp/watermarks"
      - "chown www-data:www-data /tmp/watermarks"
  solr:
    type: solr:6.6
    portforward: 9998
    config:
      conf: sites/all/modules/search_api_solr/solr-conf/6.x
```
**Tell us generally about your bug**

I'm attempting to extend the drupal7 recipe and use the install_dependencies_as_root configuration option that is described at https://docs.devwithlando.io/config/build.html to set up a few project dependencies. With the .lando.yml configuration pasted above, the dependencies are not getting installed. The project starts up without issue, but the dependencies aren't there. 

If I replace "install_dependencies_as_root" with "run_as_root", all of the dependencies are installed, but they also run again each time the project is restarted. Ideally, these would run only once (or on rebuild) and before the app starts.

Is there something I'm missing with regard to how install_dependencies_as_root is supposed to work or be configured? I've tried placing the block in a few different spots within .lando.yml to no avail.
