### ISSUE TITLE
Cannot connect to database when using custom recipe

### ISSUE THREAD

**Issue by wdeer** [lando/lando#1359]
Bug Report
==========

I have had no issue getting Wordpress or any other software (that has it's own lando recipe) to install, but when trying to install anything else I cannot get any  installer to connect to the database. I feel like I'm obviously missing something.. So far I've tried installing Mautic and SuiteCRM (and wordpress w/o the WP recipe) but keep getting the following error "**SQLSTATE[HY000] [2002] No such file or directory**"

I've tried looking through all of the previously submitted issues but didn't see anyone with quite the same issue which all tells me **"I'm definitely missing something probably obvious"**

##Using: 

* **Lando v3.0.0-rc.1 on OS X High Sierra via homebrew cask**

##.lando.yml

```yml
name: test
#recipe: lamp
proxy:
  appserver:
    - test.lndo.site
services:
  appserver:
    type: php:7.2
    #via: apache
    ssl: true
    install_dependencies_as_root:
      - apt-get update -y
      - apt-get install build-essential git cron unzip wget vim nano -y
    xdebug: true
  database:
    #type: mariadb
    type: mysql
    #portforward: 3309
    portforward: true
tooling:
  mysql:
    user: root
    service: database

```

## What i've attempted:

In every attempt to get a site working I ran `lando destroy` (instead of rebuild) based on the lando docs "[SWITCHING DATABASE CONFIGURATION](https://docs.devwithlando.io/issues/switching-dbs.html)" article.

```bash
lando destroy -y && lando start
wget https://www.mautic.org/download/latest
unzip -qq latest -d .
lando info
```

Afterward the web server starts up fine (on an installer page.) The database appears to start up fine as well since I can run `lando mysql` and am dropped into a mysql shell with no error and `lando logs -s database` doesn't show any glaring issues:

```
...
database_1   | 2019-01-20T08:46:41.820343Z 0 [Note] mysqld: ready for connections.
database_1   | Version: '5.7.24'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
...
```

I've tried using both the lemp and lamp recipes as well as no recipe at all. Also, tried both mariadb and mysql and setting the port to 3306, 3309, and just `true` to get a random port.

As a "control" I went ahead and attempted to install Wordpress (without the WP recipe) since I know it does work WITH the recipe. But I end up getting a similar error "**Warning: mysqli_real_connect(): (HY000/2002): No such file or directory**" Which tells me I'm clearly missing something.

## Additional Notes
Previously I had been using Valet alongside homebrewed nginx, php, and mariadb; but since discovering lando I'm attempting to switch everything over. I only did a simple `brew uninstall nginx php mariadb` but haven't done a deep deep dive to make sure everything is 100% uninstalled. I also still have dnsmasq installed. Not sure if any of those would be conflicting in any way, just thought i'd share in case.

## Plea for help

Please help 😩🤞
