### ISSUE TITLE
Postgres doesn't set user/password

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#1383]
When setting up a Laravel recipe, the creds reported by Lando info (and what we would normally set) are user=laravel, pass=laravel, db_name=laravel, but what actually works is user=postgres, pass="", db_name="laravel"

Should be fixable with some env vars per https://hub.docker.com/r/bitnami/postgresql

**Comment by sarath49** [comment]
Been spending 2 days with this being new to lando and needed postgres sql for drupal8 recipe. Unable to connect to database with username=drupal8 password=drupal8 and dbname=drupal8 with host=database and port=5432.

**Comment by Daisuke-sama** [comment]
I have same issue. 
environment variables aren't working and config replacement of lando provides same results
```
    creds:
      database: crmdb
      user: user
      password: secret
```
or
```
services:
  database:
    overrides:
       environment:
         POSTGRES_USERNAME: user
         POSTGRES_PASSWORD: secret
```

Only database name applies.
