### ISSUE TITLE
[v3.0.0-rc.3] Global config environment variables missing

### ISSUE THREAD

**Issue by rabauss** [lando/lando#1387]
*3.0.0-rc.3 on Windows 10 Professional*

**Global Config - all .lando.yml**

I'm missing some global config environment variables, that were accessable in ``rc.1`` - specially: ``$LANDO_ENGINE_CONF``, ``$LANDO_APP_ROOT_BIND``. Is there an alternative call for this variables? 
At the moment there is only one global variable listed via ``lando config``:
```
env: { ...
    LANDO_INSTALL_PATH: 'C:\\Program Files\\Lando', 
...}
```

That's also a problem for tooling + events - e.g.:
```
tooling:
    test-mount:
        service: appserver
        cmd:
            - echo $LANDO_MOUNT
events:
    post-start:
        - appserver: echo $LANDO_MOUNT
```

I know from the documentation that environment variables are only injected into the containers. But it would be nice, to have some global variables on the host, wouldn't it?
