### ISSUE TITLE
Document that service name changes when updating to v3.0.0-rc.2+

### ISSUE THREAD

**Issue by benjifisher** [lando/lando#1390]
**Link to the page that needs to be updated or changed.**

https://docs.devwithlando.io/guides/updating-to-rc2.html

**Describe the change you'd like**

Add a section on changes to recipes.

I am not sure how widely this applies, but I ran into it with the following in my `.lando.yml`:

```yaml
name: lando-gatsby-drupal

recipe: drupal8
config:
  via: nginx
  webroot: drupal/web
  php: 7.2
  database: mariadb

proxy:
  nginx:
    - drupal.lgd.lndo.site
```

This worked in Lando v3.0.0-rc.1: the recipe created services `appserver`, `database`, and `nginx`. After upgrading, it seems to create services `appserver`, `database`, and `appserver_nginx`.

After changing `nginx` to `appserver_nginx` in the `proxy` section, I was able to rebuild.
