### ISSUE TITLE
Cannot run db-export on Lando v3-RC4

### ISSUE THREAD

**Issue by shaal** [lando/lando#1394]
**Tell us about your setup**

What is your lando version and operating system?
*v3.0.0-rc.4 on Ubuntu 18.10*

**Tell us about your
`.lando.yml`**
```name: rosenberg
recipe: pantheon
config:
  framework: drupal8
  site: rosenberg
  id: d4f328b9-ac7b-4d84-a92e-8cc259a1bf65
```

**`pantheon.yml`**
```
api_version: 1
web_docroot: true
php_version: 7.1
workflows:
  deploy_product:
    after:
      -
        type: webphp
        description: 'Run composer prepare-for-pantheon'
        script: private/scripts/deploy_product/prepare-for-pantheon.php
      -
        type: webphp
        description: 'Run composer install & drupal-scaffold'
        script: private/scripts/deploy_product/composer-install.php
  sync_code:
    after:
      - type: webphp
        description: Push changes back to GitHub if needed
        script: private/scripts/quicksilver/quicksilver-pushback/push-back-to-github.php
```
**Tell us about the command you were running**
```lando rebuild -y
lando db-export
```

**Tell us about the error you got**
```/helpers/sql-export.sh: line 73: pantheon.2019-02-04-1549254703.sql: Permission denied
rm: cannot remove 'pantheon.2019-02-04-1549254703.sql': No such file or directory
Failed to create file: pantheon.2019-02-04-1549254703.sql
```

**Btw, when I tested `lando db-export --stdout > db-export.txt` - it works perfect.**

Rerun the command that produced your error in `debug` mode. Note that `debug` mode is run like this `lando command -vvv`. Paste in the error and the `~100` lines that proceeded it.
```
lando db-export -vvv
```
[db-export-error.txt](https://github.com/lando/lando/files/2826543/db-export-error.txt)
