### ISSUE TITLE
RC3 - pantheon recipe - env var CACHE_PORT=cache instead of 6379

### ISSUE THREAD

**Issue by wss-chadical** [lando/lando#1396]
Running RC3.
Coming from a working RC2 setup.

Pantheon recipe. The issue surfaced using Pantheon's object-cache plugin.

$ lando wp
PHP Warning:  Redis::connect() expects parameter 2 to be integer, string given in /app/web/wp-content/plugins/wp-redis/object-cache.php on line 1110

Did some debugging.

$ lando ssh
www-data@e8d021bdba8d:/app$ env|grep CACHE
CACHE_HOST=cache
CACHE_PASSWORD=
CACHE_PORT=cache

CACHE_PORT should be 6379.... 

$ lando info
...
{
    service: 'cache',
    urls: [],
    type: 'redis',
    internal_connection: {
      host: 'cache',
      port: '6379'
    },
    external_connection: {
      host: 'localhost',
      port: '32815'
    },
    config: {},
    version: '2.8',
    meUser: 'www-data',
    hostnames: [
      'cache.plwssdotcom.internal'
    ]
  },

.lando.yml
```yml
name: pl-wss-dot-com
recipe: pantheon
config:
  webroot: web
  framework: wordpress
  site: pl-wss-dot-com
  id: 141234123412341234
  # Disable the SOLR index
  index: false
services:
  appserver:
    overrides:
      depends_on:
        - database
    build:
      # authorize the containers with the dev environment so we can get the whole build out of the way
      - terminus auth:login --machine-token=4cQonNK-9v5_RL04WRc4V3BU4zl9PQ74fFIduGlwQw0Xh

      # fix for incorrect wordpress root path when using composer replace $LANDO_WEBROOT with $LANDO_WEBROOT/wp
      # WTF the webroot should be /app/web not /app/web/wp... the wp client complains with our setup if you pass in --path="/app/web"
      - sed -i 's/wp search-replace --path=\"\$LANDO\_WEBROOT\"/wp search-replace --path=\"\$LANDO\_WEBROOT\/wp\"/' /helpers/pull.sh

      # pull the database
      - /helpers/pull.sh --database=dev --code=none --files=none

      # setup .bashrc for work inside containers
      - cp /app/scripts/bash/.bashrc /var/www/.bashrc 

      # install micro editor for work inside containers
      - cd /usr/local/bin && curl https://getmic.ro | bash && cp micro m

      # terminus rsync - cause sometimes we just want to sync the files
      - rm -rf /var/www/.terminus/plugins/terminus-rsync-plugin ; mkdir -p ~/.terminus/plugins && composer create-project --no-dev -d ~/.terminus/plugins pantheon-systems/terminus-rsync-plugin:~1 ; cd ~/.terminus/plugins/terminus-rsync-plugin && composer update
      - cd /var/www/html/vendor/pantheon-systems/terminus && composer update

      # prevent composer & github complaining about too many api calls when pulling from private git repos
      - mkdir -p /var/www/.composer
      - cp /app/scripts/composer/auth.json /var/www/.composer/auth.json

      # pull pantheon wp uploads (files)
      - mkdir -p /app/web/wp-content/uploads
      - cd /app/web/wp-content/uploads && terminus rsync pl-wss-dot-com.dev:files/ .

      # base composer install
      - cd /app && composer install

      # theme composer install
      - cd /app/web/wp-content/themes/wholesalesolar && composer install
  sage:
    type: node
    overrides:
      links:
        - appserver_nginx:appserver_nginx.plwssdotcom.internal
      ports:
        # if you plan on running multiple local lando environments using this lando file then comment out the ports section below (one at a time), or change the ports - which would allso require a change to the web/wp-content/themes/wholesalesolar/resources/assets/config.json file!
        - 3000:3000
        - 3001:3001
    build:
      # theme yarn install
      - cd $LANDO_MOUNT/web/wp-content/themes/wholesalesolar && yarn install

      # theme yarn initial dev build
      - cd $LANDO_MOUNT/web/wp-content/themes/wholesalesolar && yarn build
    globals:
      gulp-cli: "latest"
      yarn: "latest"
tooling:
  yarn:
    service: sage
  # let's disable lando push so no one can use it because we DON'T push code to pantheon, we push it to github, which then triggers circleci build, which then pushes to pantheon!
  push: disabled
```
