### ISSUE TITLE
Pantheon+Wordpress+RC5 - Can no longer add/update/delete plugins via local lando

### ISSUE THREAD

**Issue by wss-chadical** [lando/lando#1405]
RC5
Recipe: Pantheon+Wordpress
```yml
name: pl-wp-plugins
recipe: pantheon
config:
  framework: wordpress
```

Try to add/update/delete a plugin via wp-admin.
![image](https://user-images.githubusercontent.com/41593218/52244580-29e9c300-2893-11e9-9153-5b16d60ffd75.png)
