### ISSUE TITLE
[3.0.0-rc.6+] xdebug:true + composer + phpstorm + cli

### ISSUE THREAD

**Issue by rabauss** [lando/lando#1406]
**Link to the page that needs to be updated or changed.**
https://docs.devwithlando.io/guides/lando-phpstorm.html

In rc.5 the config ``xdebug: true`` seems to be optimized.
But some advices for usage with phpstorm would be nice - especially for cli usage!
I didn't get it all to work...

1. ``PHP_IDE_CONFIG`` not set
![image](https://user-images.githubusercontent.com/14016098/52245669-e9199a80-28e2-11e9-9ebb-d0f60aef6ed7.png)
Our way at the moment is to set the variable in ``.lando.yml`` - but after rebuilding we break at point 2.
Would be nice, if this could be set globally...
````
        overrides:
            environment:
                PHP_IDE_CONFIG: "serverName=lando"
````

2. ``lando composer install`` is breaking with missing path mapping 
![image](https://user-images.githubusercontent.com/14016098/52244755-4ad80580-28df-11e9-87a0-69fee33131da.png) 
How should we map that or how can we disable xdebug for composer?

3. debugger settings for cli interpreters
the xdebug extension cannot be found in cli interpreters and with path it won't work too. What would be the right settings?
![image](https://user-images.githubusercontent.com/14016098/52245161-b40c4880-28e0-11e9-9c47-4f7a8f272133.png)

4. network + container path
It should be mentioned that the network has to be set to lando app network and the ``Container path`` has to be `/app`
Perhaps also the link to database container has to be defined here!
But at the moment I'm not sure, if the link is necessary, because I couldn't do cli debugging with integratet phpstorm debug configuration...
![image](https://user-images.githubusercontent.com/14016098/52245301-5f1d0200-28e1-11e9-9dea-703301372427.png)

Maybe someone already solved the problems above and can help ;-)

**Comment by rabauss** [comment]
The second problem can be solved by disabling the "Force break at first line when no path mapping specified" - of course after you've set the path mapping for lando app domain to ``/app``!

![image](https://user-images.githubusercontent.com/14016098/52382168-7e986400-2a74-11e9-8ba6-4a895d4d70b7.png)

For the third problem for cli interpeters I haven't found a possible solution yet.
Although this would give the possibility to use the one click debugging configuration, e.g. for symfony commands.

**Comment by jdleonard** [comment]
+1

Here's my .lando.yml on rc.13:

```yaml
name: myapp
recipe: pantheon
config:
  framework: drupal
  site: mysite
  id: my-id
  xdebug: true

tooling:
  composer:
    service: appserver
    description: Run composer commands
    cmd:
      - php -dmemory_limit=-1 /usr/local/bin/composer

services:
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: “serverName=myapp.lndo.site”
```

However, upon loading a page (after lando rebuild), I see the following in PhpStorm's event log:

> Cannot parse server name for external Xdebug connection.
> To fix it create environment variable PHP_IDE_CONFIG on the remote server.
> Windows: set PHP_IDE_CONFIG="serverName=SomeName"
> Linux / Mac OS X: export PHP_IDE_CONFIG="serverName=SomeName".

HALP!

**Comment by rabauss** [comment]
I guess your quotes are wrong - for me this is working with recipe lamp:
```
services:
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=lando"
```
