### ISSUE TITLE
Pantheon+Wordpress+Composer: wp search-replace fails when pulling database due to incorrect wp install path

### ISSUE THREAD

**Issue by wss-chadical** [lando/lando#1409]
We use the pantheon recipe with the wordpress framework.
We also use a Composer based wordpress codebase (example:  https://github.com/pantheon-systems/example-wordpress-composer )

Composer based wordpress setups rearrange the wordpress folder structures.
The result of this being that the "wordpress install dir" ends up being /app/web/wp instead of /app/web.

This causes the wp search-replace to fail when doing a lando pull database with an error stating that /app/web is not a wordpress installation.

Here is the code from the /helpers/pull.sh
line 176
```bash
wp search-replace --path="$LANDO_WEBROOT" "$ENV-$SITE.pantheonsite.io" "${LANDO_APP_NAME}.${LANDO_DOMAIN}"
```

This results in --path="/app/web"... instead of /app/web/wp

Not sure what the best solution is to this...

The work-around for us right now is to sed the pull.sh script during the build/run steps.
```yml
name: pantheon-lando
recipe: pantheon
config:
  webroot: web
  framework: wordpress
  site: pantheon-lando
  id: asdrfasdfasdfasdfasdf
env_file:
  - .env
services:
  appserver:
    run:
      # fix for incorrect wordpress install path when using composer. replace $LANDO_WEBROOT with $LANDO_WEBROOT/wp
      # per composer.json >> "wordpress-install-dir": "web/wp"
      - sed -i 's/wp search-replace --path=\"\$LANDO\_WEBROOT\"/wp search-replace --path=\"\$LANDO\_WEBROOT\/wp\"/' /helpers/pull.sh
```
