### ISSUE TITLE
Support relative paths for custom `compose` build paths

### ISSUE THREAD

**Issue by ElijahLynn** [lando/lando#1415]
**Tell us about your setup**

v3.0.0-rc.1 on Arch

Using a relative build path for compose service type and am getting:

> ERROR: build path /home/elijah/.lando/compose/vagovcms/docker-autossh either does not exist, is not accessible, or is not a valid URL. 

```yml
custom-service:
    type: compose
    services:
      image: autossh-socks-proxy
      build: ./docker-autossh
      ports:
        - '80'
    volumes:
      my-volume:
    networks:
      my-network:
        external: true
```
