### ISSUE TITLE
Definition for Cronjobs

### ISSUE THREAD

**Issue by rabauss** [lando/lando#1420]
Is there a way to define cronjobs for crontab of appserver in ``.lando.yml``?

Of course we could mount a crontab file from the host to the appserver, but for automatic cronjobs it would be nice to define periodical tasks easy in lando config.

**Comment by pirog** [comment]
@rabauss this seems like it would be a lot of extra engineering work esp since this is probably pretty easy to already do with a build step. 
https://docs.devwithlando.io/config/services.html#build-steps

**Comment by rabauss** [comment]
Well, just tried something like this:
```
    build_as_root:
      - apt-get update && apt-get install -y cron
      - mkdir -p /etc/cron.d
      - echo "* * * * * echo 'Hello $(date)' >> /var/log/cron.log" >> /etc/cron.d/test-cron
      - crontab /etc/cron.d/test-cron
```
But it's not working :-(
I have in mind, that docker + cronjobs are a general problem...

**Comment by acobster** [comment]
@rabauss you could try also running `service cron start` or equivalent.

https://medium.com/@jonbaldie/how-to-run-cron-jobs-inside-docker-containers-26964315b582

**Comment by rabauss** [comment]
possible solution with custom crontab container with docker image (to run commands in other containers):
````
services:
  crontab:
    type: compose
    scanner: false
    services:
      image: docker:stable
      command: crond -f
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./.lando/crontab.txt:/etc/crontabs/root
````

in crontab.txt you can define calls to other containers, e.g.:
````
*/5 * * * * docker exec -u www-data testproject_appserver_1 php /app/index.php
````

**Comment by rabauss** [comment]
> possible solution with custom crontab container with docker image (to run commands in other containers):
> 
> ```
> services:
>   crontab:
>     type: compose
>     scanner: false
>     services:
>       image: docker:stable
>       command: crond -f
>       volumes:
>         - /var/run/docker.sock:/var/run/docker.sock
>         - ./.lando/crontab.txt:/etc/crontabs/root
> ```
> 
> in crontab.txt you can define calls to other containers, e.g.:
> 
> ```
> */5 * * * * docker exec -u www-data testproject_appserver_1 php /app/index.php
> ```

this could be added to documentation!

**Comment by com2** [comment]
Not sure what goes wrong but I don't see this working here:

```
name: grc-dev
recipe: drupal7
config:
  webroot: ./grc
  php: '5.6'
services:
  pma:
    type: phpmyadmin:4.7
    hosts: []
  solr:
    type: solr:4.10
    config:
      conf: ./grc/sites/all/modules/apachesolr/solr-conf/solr-4.x
  appserver:
    build_as_root:
      - "apt update"
      - "apt -y install ffmpeg libapache2-mod-xsendfile mc"
    config:
      vhosts: .lando/appserver/config/xsendfile.conf
  crontab:
    type: compose
    scanner: false
    services:
      image: docker:stable
      command: crond -f
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./.lando/crontab.txt:/etc/crontabs/root
tooling:
  drush:
    cmd: "/usr/local/bin/drush --root=/app/grc"
proxy:
  pma:
    - pma-grc-dev.lndo.site
```
My .lando/crontab.txt:
```
*/10 * * * *  docker exec -u www-data /usr/local/bin/drush --root=/app/grc --quiet cron
* * * * *  docker exec -u www-data /usr/bin/flock -n /tmp/lock.video-scheduler -c "/usr/local/bin/drush --root=/app/grc video-scheduler"
```
Your advice is appreciated!

**Comment by jcandan** [comment]
I wrote this [article](https://dev.to/jcandan/cron-with-lando-4lnh) to address this question. It requires the three steps to be broken up:

```
  appserver:
    build_as_root:
      - apt-get update -y
      - apt-get install cron -y
    run_as_root:
      - service cron start
    run:
      - crontab /app/resources/config/cron.txt
```

**Comment by djboris88** [comment]
@jcandan I got it working with your example, but the `cron` service starts automatically only immediately after `lando rebuild`. After lando restarts, it doesn't start automatically, I have to ssh into the `appserver` and run `service cron start` for it to work.

@pirog Shouldn't `run_as_root` commands run on each start/restart of the lando service?

**Comment by pirog** [comment]
No. They shouldn’t.

They run the first time you boot up a new app and on subsequent rebuilds of
that app.

**Comment by djboris88** [comment]
Thanks for a quick reply. Is there any other way to run a command on each start of the service?

**Comment by djboris88** [comment]
Ok, I solved it by adding `service cron start` to `docker-php-entrypoint` which I overwritten during `build_as_root` stage. Now it starts automatically.

**Comment by jcandan-achieve** [comment]
nice! mind commenting what's needed at that dev.to article? I'll update it.

**Comment by jcandan** [comment]
nice! mind commenting what's needed at that dev.to article? I'll update it.

**Comment by djboris88** [comment]
Ok, I'll comment here and there.

Here is @jcandan 's script but updated with additional step:

```
appserver:
    build_as_root:
      - apt-get update -y
      - apt-get install cron -y
      - cp -f /app/.lando/docker-php-entrypoint.sh /usr/local/bin/docker-php-entrypoint
    run_as_root:
      - service cron start
    run:
      - crontab /app/resources/config/cron.txt
```

The only thing added is the command to copy a changed docker entrypoint bash script to the usual place. And here is the content of the changed entrypoint script:

```bash
#!/bin/sh
service cron start

set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- apache2-foreground "$@"
fi

exec "$@"
```

Here I only added `service cron start`, the rest was already there in the original entrypoint bash script. I actually used the same combo for getting the supervisor to work, for Laravel queue workers.
