### ISSUE TITLE
Volume configuration reference with custom compose service

### ISSUE THREAD

**Issue by trepmag** [lando/lando#1422]
Hello, I'm failing to setup a volume reference as stated at https://docs.docker.com/compose/compose-file/#volume-configuration-reference for a [custom compose service](https://docs.devwithlando.io/tutorials/compose.html).

I setup a .lando.yml file as follow:
```
name: mytest

services:
  database:
    type: compose
    services:
      image: postgres:9.4
      command: docker-entrypoint.sh postgres
      volumes:
        - data_volume:/var/lib/postgresql/data
    volumes:
      data_volume:
```

So, when I hit `lando start` it output `Creating volume "mytest_data_volume" with default driver` and I can find the corresponding item on my host file system at `/var/lib/docker/volumes/mytest_data_volume/`.

Now, it looks like the mounting didn't appends as the host `/var/lib/docker/volumes/mytest_data_volume/` directory is empty while in the container `/var/lib/postgresql/data/` is full of stuff...

I tried to use also the `mytest_data_volume` (instead of `data_volume`) key in my volumes but that didn't work either...

My question is: does this "Volume configuration reference" is available for lando custom compose service and if yes, what should be the syntax?

**Comment by pirog** [comment]
@trepmag let me check this out, could very well be a bug

**Comment by pirog** [comment]
yup this totally a bug @trepmag! pushing up a fix and test in a few

**Comment by pirog** [comment]
Alright @trepmag we've got this in 
https://github.com/lando/lando/releases/tag/v3.0.0-rc.8

And also got a VERY FAMILIAR LOOKING test for you
https://github.com/lando/lando/blob/master/examples/compose/.lando.yml

**Comment by trepmag** [comment]
@pirog, thanks a lot for this fix; it works great!

**Comment by silverham** [comment]
I would like to mention here that to configure external volumes with lando, the sample configuration below works:

Sample assumes an external volume created with `docker volume create amazeeio-ssh-agent-volume`

```yml
services:
  cli:
    api: 3
    type: lando
    services:
      [..]
      volumes:
        - ./local-folder:/app/local-folder
        - amazeeio-ssh-agent-volume:/tmp/amazeeio_ssh-agent
    volumes:
      amazeeio-ssh-agent-volume:
        external: true
```
