### ISSUE TITLE
NGINX catch all support

### ISSUE THREAD

**Issue by ro0NL** [lando/lando#1427]
After #307 closed, i still think lando could provide something generic that fits Symfony, .e.g

```
recipe: lemp
config:
   via: nginx
   catch-all: index.php # naming TBD
```

as currently all im doing to make it work is adding the catch all route: https://github.com/ro0NL/symfony-lando/blob/master/create-project.sh#L44

I started with the default nginx config provided by lando and only added the parts described in https://symfony.com/doc/4.1/setup/web_server_configuration.html#nginx, but i think it doesnt contain anything Symfony specific.
