### ISSUE TITLE
[v3.0.0-rc.7] PHP memory limit fatal error

### ISSUE THREAD

**Issue by xaqrox** [lando/lando#1429]
**Tell us about your setup**

Lando v3.0.0-rc.7
Ubuntu 16.04
PHP version 7.1.26
Docker 18.09.01

**Tell us about your `.lando.yml`**

Vanilla Pantheon recipe

.lando.yml
```yml
name: defenders
recipe: pantheon
config:
  framework: drupal8
  site: defenders
  id: [REDACTED]
```

pantheon.yml
```yml
api_version: 1
web_docroot: true
php_version: 7.1
workflows:
  deploy_product:
    after:
      -
        type: webphp
        description: 'Run composer prepare-for-pantheon'
        script: private/scripts/deploy_product/prepare-for-pantheon.php
      -
        type: webphp
        description: 'Run composer install & drupal-scaffold'
        script: private/scripts/deploy_product/composer-install.php
  sync_code:
    after:
      - type: webphp
        description: Push changes back to GitHub if needed
        script: private/scripts/quicksilver/quicksilver-pushback/push-back-to-github.php
```

**Tell us about the command you were running**

```bash
lando init --recipe pantheon
lando start
```

```bash
lando drush status
```

**Tell us about the error you got**

'lando start`
https://gist.github.com/xaqrox/76181c815db50868b322a088081d15e0#file-lando-error-log-L127

`lando drush status`
https://gist.github.com/xaqrox/a1114398d91ace76b18f7242732461b1#file-lando-drush-error-log-L84

Both produce
`PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 4096 bytes) in /app/vendor/composer/autoload_static.php on line 3937`

**Tell us generally about your bug**

Upgrading from beta47 to the most recent RC. I uninstalled lando and docker and deleted all their leftover files and started over. The site appears to run, I can pull the db from Pantheon and load the site in the browser, but I can't run drush commands. Definitely stopping me from using Lando.
