### ISSUE TITLE
Docker compose build context instruction doesn't work for custom compose service

### ISSUE THREAD

**Issue by trepmag** [lando/lando#1432]
Defining a [docker compose build](https://docs.docker.com/compose/compose-file/#build) context instruction return the following error:
```
$ lando start
Let's get this party started! Starting app..
error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
...
```

Here is the related .lando.yml:
```
name: mytest

services:
  database:
    type: compose
    services:
      image: mytest:1
      build:
        context: .
        #dockerfile: Dockerfile_database
      command: docker-entrypoint.sh postgres
```

And the Dockerfile:
```
FROM postgres:9.4

```
