### ISSUE TITLE
nginx 504 timeout: Adding custom config to Drupal 7 recipe to resolve

### ISSUE THREAD

**Issue by hydrantmark** [lando/lando#1434]
**Tell us about your setup**

Lando v3.0.0-beta.47 on Ubuntu 18.04

**Tell us about your `.lando.yml`**

```yml
name: site-name

recipe: drupal7

config:
  # Lando defaults to Apache. Switch to nginx to match Platform.sh.
  via: nginx
  webroot: web
  php: '5.6'
  # Lando defaults to the latest MySQL release, but Platform.sh uses MariaDB.
  # Specify the version to match what's in services.yaml.
  #database: mariadb:10.2
  config:
    server: ./config/drupal7.conf
    php: ./config/php.ini

# Spin up a basic nodes server with redis backend
#services:
#  cache:
#    type: redis:3.2
#    persist: true

# The following additional build step will install the Platform CLI
# in the application container and auto-run `composer install`
services:
  appserver:
    run:
      - "mkdir -p /var/www/.platformsh && mkdir -p /var/www/.platformsh/bin"
      - "curl -fsSL -o /var/www/.platformsh/bin/platform https://github.com/platformsh/platformsh-cli/releases/download/v3.33.6/platform.phar"
      - "chmod ug+x /var/www/.platformsh/bin/platform"
    overrides:
      services:
        environment:
          BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://nginx/"}, "Drupal\\DrupalExtension" : {"drush" :   {  "root":  "/app/web" }}}}'

# The following entry creates a `lando platform` command that will run
# any Platform CLI command from inside the container if desired.
tooling:
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd: /var/www/.platformsh/bin/platform
  phplint:
    service: appserver
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"
      - "--root=/app/web"
```

Custom drupal7.conf:
```nginx
server {
  listen 80 default_server;
  listen 443 ssl;

  server_name appserver;

  ssl_certificate           /certs/cert.crt;
  ssl_certificate_key       /certs/cert.key;
  ssl_verify_client         off;

  port_in_redirect off;
  client_max_body_size 100M;

  root ${LANDO_WEBROOT};

  location = /favicon.ico {
      log_not_found off;
      access_log off;
  }

  location = /robots.txt {
      allow all;
      log_not_found off;
      access_log off;
  }

  # Very rarely should these ever be accessed outside of your lan
  location ~* \.(txt|log)$ {
      allow 192.168.0.0/16;
      deny all;
  }

  location ~ \..*/.*\.php$ {
      return 403;
  }

  location ~ ^/sites/.*/private/ {
      return 403;
  }

  # Allow "Well-Known URIs" as per RFC 5785
  location ~* ^/.well-known/ {
      allow all;
  }

  # Block access to "hidden" files and directories whose names begin with a
  # period. This includes directories used by version control systems such
  # as Subversion or Git to store control files.
  location ~ (^|/)\. {
      return 403;
  }

  location / {
      # try_files $uri @rewrite; # For Drupal <= 6
      try_files $uri /index.php?$query_string; # For Drupal >= 7
  }

  location @rewrite {
      rewrite ^/(.*)$ /index.php?q=$1;
  }

  # Don't allow direct access to PHP files in the vendor directory.
  location ~ /vendor/.*\.php$ {
      deny all;
      return 404;
  }

  # In Drupal 8, we must also match new paths where the '.php' appears in
  # the middle, such as update.php/selection. The rule we use is strict,
  # and only allows this pattern with the update.php front controller.
  # This allows legacy path aliases in the form of
  # blog/index.php/legacy-path to continue to route to Drupal nodes. If
  # you do not have any paths like that, then you might prefer to use a
  # laxer rule, such as:
  #   location ~ \.php(/|$) {
  # The laxer rule will continue to work if Drupal uses this new URL
  # pattern with front controllers other than update.php in a future
  # release.
  location ~ '\.php$|^/update.php' {
      fastcgi_split_path_info ^(.+?\.php)(|/.*)$;
      # Security note: If you're running a version of PHP older than the
      # latest 5.3, you should have "cgi.fix_pathinfo = 0;" in php.ini.
      # See http://serverfault.com/q/627903/94922 for details.
      include fastcgi_params;
      # Block httpoxy attacks. See https://httpoxy.org/.
      fastcgi_param HTTP_PROXY "";
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_param PATH_INFO $fastcgi_path_info;
      fastcgi_param QUERY_STRING $query_string;
      fastcgi_intercept_errors on;
      request_terminate_timeout = 300;
      # PHP 5 socket location.
      #fastcgi_pass unix:/var/run/php5-fpm.sock;
      # PHP 7 socket location.
      #fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
      #lando
      fastcgi_pass fpm:9000;
  }

  # Fighting with Styles? This little gem is amazing.
  # location ~ ^/sites/.*/files/imagecache/ { # For Drupal <= 6
  location ~ ^(/[a-z\-]+)?/sites/.*/files/styles/ { # For Drupal >= 7
      try_files $uri @rewrite;
  }

  # Handle private files through Drupal. Private file's path can come
  # with a language prefix.
  location ~ ^(/[a-z\-]+)?/system/files/ { # For Drupal >= 7
      try_files $uri /index.php?$query_string;
  }

  location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
      expires max;
      log_not_found off;
  }

}
```

Custom php.ini:
```php
[PHP]

;;;;;;;;;;;;;;;
; PHP Globals ;
;;;;;;;;;;;;;;;

short_open_tag = Off
output_buffering = 4096
allow_call_time_pass_reference = Off
variables_order = "GPCS"
request_order = "GP"
register_long_arrays = Off
register_argc_argv = Off
magic_quotes_gpc = Off
enable_dl = Off
allow_url_fopen = OnFonts - All fonts glitch when page loads/refreshes/click through (flickers between 2 fonts)
General - RH column images/copy/buttons to align with top of body copy and all RH column content should left align. Everything to be pulled closer together.
Home page - Slide show tape at too acute an angle compared to designs, the text should also be orientated differently within the box -see designs / ask SWD
Shows - On individual show pages the bar that you click on to see the cast should say ' CLICK HERE to see full cast list' please amend - see designs.
Flickr icon - Missing Flickr Icon from website header can we have one, it was previously there on our old website, https://www.flickr.com/photos/youthmusictheatre/albums
realpath_cache_size = "800K"
realpath_cache_ttl = "86400"
disable_functions =
sendmail_path=/bin/true
;include_path = ".:/usr/share/pear:/usr/share/php"

[Date]
date.timezone = "UTC"

;;;;;;;;;;;;;;;;;;;;;;
;; PACKAGE SETTINGS ;;
;;;;;;;;;;;;;;;;;;;;;;

; Xdebug
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0

; Globals
expose_php = on
max_execution_time = 300
max_input_time = 900
max_input_vars = 10000
memory_limit = 512M
upload_max_filesize = 100M
post_max_size = 100M
error_reporting = E_ALL & ~E_DEPRECATED
ignore_repeated_errors = on
html_errors = off
display_errors = on
log_errors = on
```

**Tell us about the command you were running**

```bash
lando start
# Edited my lando.yml as above
lando restart
```

```bash
lando start
# Edited my lando.yml as above
lando rebuild
```

```bash
lando start
# Edited my lando.yml as above
lando destroy && lando start
```

**Tell us generally about your bug**

I have been experiencing intermittent 504 Gateway timeout, while navigating through the admin section of a Drupal website. (Addtionally tested against a fresh install of Drupal 7.)

Following the documentation, https://docs.devwithlando.io/tutorials/drupal7.html#using-custom-config-files, I have tried over-riding the default configuration to set the folllowing:

- PHP: max_execution_time = 300
- NGINX: fastcgi_read_timeout 300;

As per https://github.com/lando/lando/issues/1226

I also attempted to work-around this by updating the following default versions:

- ~/.lando/services/config/drupal7/drupal7.conf
- ~/.lando/services/config/drupal7/php.ini

**Comment by pirog** [comment]
@hydrantmark let us know when you arrive at config that works for your application, when we have that we can consider bumping some of our defaults to match

**Comment by oldravian** [comment]
24-06-2023
I'm facing this issue is laravel recipe

here is my .lando.yml

````
name: afp-admin
keys: false
recipe: laravel
config:
  php: "7.4"
  via: nginx:1.18
  composer_version: 2.0.8
  database: mariadb:10.4.17
  webroot: ./public
  cache: redis
  server: nginx.conf

proxy:
  appserver_nginx:
    - admin.afpdev
    - admin.afpdev.lndo.site
services:
  appserver_nginx:
    run_as_root:
      - ln -snf /usr/share/zoneinfo/America/Denver /etc/localtime
      - echo "UTC" > /etc/timezone
    config:
      server: nginx.conf
  db_gui:
    type: phpmyadmin
```



here is my nginx.conf

```
# Based on https://www.nginx.com/resources/wiki/start/topics/examples/full/#nginx-conf
user              root root;  ## Default: nobody

worker_processes  auto;
error_log         "/opt/bitnami/nginx/logs/error.log";
pid               "/opt/bitnami/nginx/tmp/nginx.pid";

events {
    worker_connections  1024;
}

http {
    include       mime.types;

    default_type  application/octet-stream;

    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;

    client_body_temp_path  "/opt/bitnami/nginx/tmp/client_body" 1 2;
    proxy_temp_path        "/opt/bitnami/nginx/tmp/proxy" 1 2;
    fastcgi_temp_path      "/opt/bitnami/nginx/tmp/fastcgi" 1 2;
    scgi_temp_path         "/opt/bitnami/nginx/tmp/scgi" 1 2;
    uwsgi_temp_path        "/opt/bitnami/nginx/tmp/uwsgi" 1 2;

    log_format    main '$remote_addr - $remote_user [$time_local] '
                       '"$request" $status  $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for"';

    access_log    "/opt/bitnami/nginx/logs/access.log";

    sendfile           on;

    tcp_nopush         on;
    tcp_nodelay        off;

    keepalive_timeout  65;
    gzip               on;
    gzip_http_version  1.0;
    gzip_comp_level    2;
    gzip_proxied       any;
    gzip_types         text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    ssl_protocols      TLSv1 TLSv1.1 TLSv1.2;

    map $http_x_forwarded_proto $lando_https {
      default '';
      https on;
    }

    map $http_x_forwarded_proto $http_user_agent_https {
      default '';
      https ON;
    }

    client_max_body_size 80M;
    server_tokens off;
    include  "/opt/bitnami/nginx/conf/vhosts/*.conf";

    # HTTP Server
    server {
        fastcgi_read_timeout 600;
        proxy_read_timeout 600;
        
        # port to listen on. Can also be set to an IP:PORT
        listen  8080;

        location /status {
            stub_status on;
            access_log   off;
            allow 127.0.0.1;
            deny all;
        }

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass php:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_read_timeout 600;
            request_terminate_timeout = 600;
        }
    }
}
```
