### ISSUE TITLE
rc9 solr start.sh is empty in container

### ISSUE THREAD

**Issue by simesy** [lando/lando#1442]
Lando version v3.0.0-rc.8 on osx. docker for mac version 18.09.1

**Tell us about your `.lando.yml`**

```
name: blah
recipe: drupal8
config:
  webroot: docroot

# Chrome and selenium.
compose:
  - scripts/lando/docker-compose-extra.yml

services:
  solr:
    type: solr:6
    portforward: true
    core: drupal
    config:
      dir: docroot/modules/contrib/search_api_solr/solr-conf/6.x
```

**Tell us about the error you got**

When i `lando start` or `lando rebuild`, and I inspect the solr container, i notice that the Drupal solr config has not been copied in. (Solr itself starts and I can access it but it has the wrong config.)

I see in the logs:
```
Running command /helpers/start.sh docroot/modules/contrib/search_api_solr/solr-conf/6.x
```

So i looked at this script in the container. It's empty. Does this seem right?

```
solr@4e447465c5c5:/helpers$ ls -la
total 80
drwxr-xr-x 20 www-data www-data  640 Feb  9 00:15 .
drwxr-xr-x  1 root     root     4096 Feb 10 00:06 ..
-rwxr-xr-x  1 www-data www-data 2700 Feb 10 00:08 add-cert.sh
-rwxr-xr-x  1 www-data www-data 1537 Feb 10 00:08 auth.sh
-rwxr-xr-x  1 www-data www-data  326 Feb 10 00:08 binding.sh
-rwxr-xr-x  1 www-data www-data  314 Feb 10 00:08 generate-key.sh
-rwxr-xr-x  1 www-data www-data 1541 Feb 10 00:08 get-remote-url.sh
-rwxr-xr-x  1 www-data www-data  740 Feb 10 00:08 lando-entrypoint.sh
-rwxr-xr-x  1 www-data www-data 2543 Feb 10 00:08 load-keys.sh
-rwxr-xr-x  1 www-data www-data  643 Feb 10 00:08 pantheon.sh
-rwxr-xr-x  1 www-data www-data 5912 Feb 10 00:08 pull.sh
-rwxr-xr-x  1 www-data www-data 4720 Feb 10 00:08 push.sh
-rwxr-xr-x  1 www-data www-data 1012 Feb 10 00:08 refresh-certs.sh
-rwxr-xr-x  1 www-data www-data 1241 Feb 10 00:08 setup-ca.sh
-rwxr-xr-x  1 www-data www-data 1818 Feb 10 00:08 sql-export.sh
-rwxr-xr-x  1 www-data www-data 3489 Feb 10 00:08 sql-import.sh
-rwxr-xr-x  1 www-data www-data    0 Feb  9 00:15 start.sh
-rwxr-xr-x  1 www-data www-data 1882 Feb 10 00:08 switch.sh
-rwxr-xr-x  1 www-data www-data 2553 Feb 10 00:08 user-perm-helpers.sh
-rwxr-xr-x  1 www-data www-data 2785 Feb 10 00:08 user-perms.sh
```
