### ISSUE TITLE
Using portforward: true results in port: true printed for Lando info

### ISSUE THREAD

**Issue by tanc** [lando/lando#1450]
**Tell us about your setup**

Lando version v3.0.0-rc.9

**Tell us about your `.lando.yml`**

Relevant section:
```yml
  bcbapidatabase:
    type: mysql
    portforward: true
    creds:
      user: database
      password: database
      database: bcbapidatabase
```

**Tell us about the command you were running**

```bash
lando info
```

**Tell us about the error you got**

Lando info displays `port: true` instead of the port number.

```bash
{
  service: 'bcbapidatabase',
  urls: [],
  type: 'mysql',
  internal_connection: {
    host: 'bcbapidatabase',
    port: '3306'
  },
  external_connection: {
    host: 'localhost',
    port: true
  },
  creds: {
    database: 'bcbapidatabase',
    password: 'database',
    user: 'database'
  },
  config: {},
  version: '5.7',
  meUser: 'www-data',
  hostnames: [
    'bcbapidatabase.iucnflr.internal'
  ]
},
```

**Tell us generally about your bug**

Looks like this was fixed in [this commit](https://github.com/lando/lando/commit/db1c951fc9f86c7e7655bdaf11b30d597ca1edc9?diff=unified) so may be a regression?

Also covered in closed #791
