### ISSUE TITLE
Unsupported config option for services.appserver: 'services'

### ISSUE THREAD

**Issue by ElijahLynn** [lando/lando#1452]
Just updated to Lando 3.0.0-rc7 for testing #1415 and using my standard config I am getting:

> ERROR: The Compose file '/home/elijah/.lando/compose/vagovcms/appserver-3.yml' is invalid because:
Unsupported config option for services.appserver: 'services'

appserver-3.yml
```
services:
  appserver:
    services:
      environment:
        PHP_IDE_CONFIG: serverName=appserver
version: '3.6'
```

.lando.yml
```
services:
  appserver:
    run_as_root:
      - "apt-get update -y"
      - "apt-get install build-essential chrpath libssl-dev libxft-dev libfreetype6-dev libfreetype6 libfontconfig1-dev libfontconfig1 -y"
#      - "tar xvjf /app/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /usr/local/share/"
#      - "mv /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/bin/"
#      - "cd /usr/bin"
#      - "chmod +x phantomjs"
    # Uncomment the below `xdebug: true` for Xdebug support
    # @todo Change this to pull in a local Lando settings variable and use that boolean variable
    # Run `lando rebuild` after uncommenting
    #xdebug: true
    overrides:
      services:
        environment:
          # Support debugging Drush with XDEBUG. Listen in PHPStorm then `lando drush` to trigger xdebug.
          PHP_IDE_CONFIG: "serverName=appserver"
```

It seems as if something broke here, not sure what it is yet, but config is same as before upgrade.
