### ISSUE TITLE
Unhandled rejection Error: mysql version 5.5 is not supported

### ISSUE THREAD

**Issue by andyxmas** [lando/lando#1456]
RC9. Getting this error when doing a lando start. Fresh install of lando and docker.

Works ok if I set mysql to 5.7. 

```
name: wodop
recipe: drupal8
config:
  webroot: .
  php: '5.6'
  database: mysql:5.5
  drush: global:8.1.12
```
