### ISSUE TITLE
Allow Drush to be found in custom bin-dir

### ISSUE THREAD

**Issue by tanc** [lando/lando#1471]
**Please explain your request and its importance in the form of a user story.**

*As a lando user who works with Drupal 8 sites, I want to be able to specify the location of the vendor bin directory using composer and have Drush work from that directory*

**Is your feature request related to a problem? Please describe.**

Currently Lando looks for Drush in `/app/vendor/bin` but in our composer files we specify:
```
"config": {
    "bin-dir": "bin/"
},
```
This results in Drush (and other vendor provided binaries) being available in `/app/bin` and Lando doesn't pick that up automatically.

**Describe the solution you'd like**

I don't know the technical solution but it would be good if Lando was able to find Drush when placed in a different location.

**Describe alternatives you've considered**

Currently I'm able to specify the Drush location using a tooling command so there is a workaround:
```
  drush:
    service: appserver
    description: runs drush from the correct location
    cmd: /app/bin/drush
```

**Comment by tanc** [comment]
Have just seen #861 and I can see other people have used similar workarounds so happy to stick with this solution if you feel like its an unusual enough set up that it doesn't warrant baking in a solution.

**Comment by pirog** [comment]
@tanc yeah i dont think this is something we can reliably (or even should) support. 

We document what things are in the `PATH` for each service eg https://docs.devwithlando.io/tutorials/php.html#path-considerations so if you are doing something outside of that its up to you to either modify the `PATH` or specify the tooling route directly.

**set tooling route explicitly**

```yaml
drush:
  service: appserver
  description: runs drush from the correct location
  cmd: /app/bin/drush
```

**modify the PATH**

```yaml
services:
  appserver:
    overrides:
      envrionment:
        PATH: /app/bin:/other/path1:/other/path2
```
