### ISSUE TITLE
App metacache never gets set on successful `pull` `switch` or `push`

### ISSUE THREAD

**Issue by Etroid** [lando/lando#1475]
**Tell us about your setup**

Running lando `v3.0.0-rc.10`On MacOS High Sierra

**Tell us about your `.lando.yml`**
```
name: test
recipe: pantheon
config:
  framework: drupal8
  id: xxx
  site: yyy
  env: dev
  xdebug: false
```

**Tell us about the command you were running**
```
lando pull
# Entered auth credentials (see image)
# Picked code, db and files
# Command finished successfully
```

![2019-02-19_10-43-05](https://user-images.githubusercontent.com/8611594/53039081-262d7300-3433-11e9-84e7-95f40dc9f042.png)

**Tell us generally about your bug**
- [ ] Subsequent `lando pull` command will ask for `auth` confirmation again
- [ ] `~/.lando/cache` does not appear to contain `test.meta.cache` file

Please detail the steps we can take to replicate this bug. Be as detailed as possible.
- [ ] Set up a test app with the .lando.yml configuration above - DO NOT USE `lando init`as this will also attempt to generate meta.cache file.
- [ ] Start up the app
- [ ] Run `lando pull`
- [ ] Assert `APPNAME.meta.cache` file does not get generated.

**Tell us more**

I stepped through the code and while the event `cli-${argv._[0]}-run` gets emitted in [cli.js](https://github.com/lando/lando/blob/master/lib/cli.js#L262), it never makes it inside [lando-pantheon/app.js](https://github.com/lando/lando/blob/master/plugins/lando-pantheon/app.js#L14) where the app cache metadata gets saved.

**Comment by amaisano** [comment]
Same, except for me, I get asked for a machine token instead of choosing an account:

**.lando.yml**:

```
name: mysite
recipe: pantheon
config:
  framework: drupal8
  site: mysite
  id: 12345
```

**Command history**:

```
Twix:custom amaisano$ l pull
? Enter a Pantheon machine token [input is hidden]
```
