### ISSUE TITLE
Home cannot be mounted via volumes

### ISSUE THREAD

**Issue by rabauss** [lando/lando#1483]
*v3.0.0-rc.12 on Windows 10 Professional*

```yml
name: test
recipe: lamp
services:
  appserver:
    type: php:7.2
    webroot: web
    xdebug: true
    config:
      php: .lando/php/php.ini
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=lando"
      volumes:
        - ~/.lando/composer_cache:/var/www/.composer/cache
```

Unfortunately in rc.12 the volumes mount to home is not working anymore.
We used that to have a global composer cache folder.

Since rc.2 we have changed `$LANDO_ENGINE_CONF` to `~/.lando`. But now the `~` is mounted to the app root folder and not to home of host.

Don't know since which rc this bug exists, but in rc.2 or rc.3 it worked for me - because I'm still on rc.1 and wanted to wait for more stable version...
