### ISSUE TITLE
Import to second database

### ISSUE THREAD

**Issue by kamalkech** [lando/lando#1508]
**lando version:**
`v3.0.0-rc.12`

**lando.yml:**
```
name: project-name
recipe: drupal8
config:
  webroot: .
  via: nginx
```
In documentation link https://docs.devwithlando.io/guides/db-import.html#examples
i try with command line : lando db-import dump.zip --host db2
but not wqorking and i get this error message : ERROR: No such service: drupal8_prod
and drupal8_prod is the second db

any idea ?
tnx.

**Comment by tanc** [comment]
Your `.lando.yml` file doesn't have a second database

**Comment by tylerssn** [comment]
To extend @tanc's comment. Add the second database.

```yaml
name: project-name
recipe: drupal8
config:
  webroot: .
  via: nginx

services:
  db2: # @see https://docs.devwithlando.io/tutorials/mysql.html#configuration
    type: mysql:5.7
    creds:
      user: mysql
      password: mysql
      database: database
```

**Comment by kamalkech** [comment]
1- Update lando to 

```
name: project-name
recipe: drupal8
config:
  webroot: .
  via: nginx
services:
  db2: # @see https://docs.devwithlando.io/tutorials/mysql.html#configuration
    type: mysql:5.7
    creds:
      user: mysql
      password: mysql
      database: secondDb
```

2- `lando mysql` and and create a new database secondDb with command `create database secondDb`

3- import data from dump to secondDb with this command: 
`lando db-import c0fmh2translate.sql --host db2
`

but i found the database is empty, so the import not working correctly. why ??!!
