### ISSUE TITLE
How to change a service's hostname?

### ISSUE THREAD

**Issue by KimchaC** [lando/lando#1511]
I have consulted the documentation, searched google and the issues here but couldn't find an answer to my question...

How can I change the hostname of a service that is displayed when I `lando ssh` into it?

I have a bunch of sites and would like to be able to distinguish between them.

So instead of seeing:

> $ lando ssh
> www-data@**1c6c69d17661**:/app$ 

I'd like to see:

> $ lando ssh
> www-data@**site-abcd**:/app$ 

Is this currently possible?

**Comment by ameenshake** [comment]
I too would be interested in this. I have tried changing it manually in the containers using the following:

`$ hostname {NEW_HOSTNAME}`

But even as root, I am unable to. I came upon this issue: https://github.com/moby/moby/issues/8902#issuecomment-218911749 and it seems like changing is not allowed directly due to some security issues.

**Comment by kimdcottrell** [comment]
Changing the actual hostname is a pita, but you can fake it.

In your `.lando.yml`, do something like:

```
services:
  appserver:
    run: # not sure if you need the run here 
      - source ~/.bashrc
    overrides:
      volumes:
        - ./config/.bashrc:/var/www/.bashrc
```

on your local machine, go to the project dir and `touch config/.bashrc`. in that file:

```
export PS1="\u@devcafe $ "
```

then after a `lando rebuild` you should see:

```
$ lando ssh
www-data@devcafe $     
```

A part of me wonders if this is also possible via an `env_file` and the `PS1` var getting set there, but it's 3:45am here and I am le tired.
