### ISSUE TITLE
MariaDB 10.3 is no longer supported

### ISSUE THREAD

**Issue by hussainweb** [lando/lando#1512]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.0.0-rc.13 on Mac OS Mojave

**Tell us about your `.lando.yml`**

(modified to remove sensitive details)
```yml
name: project

recipe: drupal8

proxy:
  appserver:
    - site1.project.lndo.site
    - site2.project.lndo.site

config:
  webroot: docroot
  database: mariadb:10.3

  # Uncomment it if you want xdebug in your setup.
  # xdebug: true

  php: '7.1'

  conf:
    php: .lando/php/php.ini

services:
  cache:
    type: memcached:1.5
    mem: 256

  db_site1:
    type: mariadb:10.3
  db_site2:
    type: mariadb:10.3

tooling:
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush
  drupal:
    service: appserver
    cmd: /app/vendor/bin/drupal
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

*Example:*

```bash
lando start
```

**Tell us about the error you got**

*Example:*

```bash
lando start -v
error: Error: mariadb version 10.3 is not supported
    at new LandoService (/snapshot/lando/build/cli/plugins/lando-core/compose/lando/builder.js:0:0)
    at new LandoService (/snapshot/lando/build/cli/plugins/lando-core/types/service/builder.js:0:0)
    at new LandoMariaDb (/snapshot/lando/build/cli/plugins/lando-services/services/mariadb/builder.js:0:0)
    at module.exports.app.events.on._.forEach.service (/snapshot/lando/build/cli/plugins/lando-services/app.js:0:0)
    at arrayEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9344:14)
    at AsyncEvents.module.exports.app.events.on (/snapshot/lando/build/cli/plugins/lando-services/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.init.loadPlugins.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js:0:0)
    at initAndReport (/snapshot/lando/build/cli/lib/app.js:0:0)
    at App.start (/snapshot/lando/build/cli/lib/app.js:0:0)
    at Object.exports.appToggle (/snapshot/lando/build/cli/plugins/lando-core/lib/utils.js:0:0)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

**Tell us generally about your bug**

This was working with Lando v3 RC1. I see this commit changing the supported versions array. As far as I can see, it was unintentional. https://github.com/lando/lando/commit/49a09201d1347323009672b4171e6d43c9123ba4
