### ISSUE TITLE
Badgateway when using phpmyadmin service in addition to node server application (loopback)

### ISSUE THREAD

**Issue by JorisInsign** [lando/lando#1513]
Hi,

I'm trying to run a loopback server into lando with a mysql database connection into an other lando service.
It seems to work correctly with this .lando.yml : 
```
name: example
services:
  database:
    type: mysql
    creds:
      user: myuser
      password: mypassword
      database: mydb
  api:
    type: node:10
    port: 3000
    build:
      - cd api-server && npm install
    command:
      - cd api-server && node .
#  phmyadmin:
#    type: phpmyadmin
#    hosts:
#      - database
proxy:
  api:
    - api.lndo.site:3000
```

I can access the http://localhost:xxxx/ or the api.lndo.site in order to acces my loopback running server.

But if I want to add "phpmyadmin" service (by uncommenting the related part in the .lando.yml below), the "api" service don't work anymore at start.
I got an "The connection has been reset" error or a "bad gateway" error with the lndo.site domain.

I have to `lando ssh -s api -c 'cd /app/api-server && node .'` in order to launch my node application.

I don't know where to look to solve this problem.

Additional question : is it possible to display standard output of "command" commands instead of only errors ?

Thanks for your help,
