### ISSUE TITLE
Commands run in events don't have a useful $PATH

### ISSUE THREAD

**Issue by nicrodgers** [lando/lando#1520]
lando rc13:

.lando.yml:
`name: my-lando-app
recipe: drupal8
config:
  webroot: web
events:
  post-db-import:
    - /app/vendor/bin/drush status`

when running lando db-import db.sql, we get:

> Importing /app/import.sql...
>
>Import complete!
>/usr/bin/env: 'php': No such file or directory
>warn: One of your event commands has failed! This may prevent your app from working correctly
>error: Event failed with code undefined and message 

I'd expect this to work and run drush cr.

This works:
lando ssh -c "drush status"

**Comment by pirog** [comment]
@nicrodgers i dont think this is an issue with Lando.

```yaml
name: my-lando-app recipe: drupal8 
config: 
  webroot: web 
events: 
  post-db-import: 
    - /app/vendor/bin/drush status
```

In the above scenario "drush" is going to run against the default service for the dynamic `db-import` tooling command which is probably "database". For the sake of explaining this lets assume that the default service is indeed database. Unless you've explicitly installed `drush` inside the `database` service what you are getting is the expected behavior. I'd recommend doing something like

```yaml
name: my-lando-app recipe: drupal8 
config: 
  webroot: web 
events: 
  post-db-import: 
    - appserver: /app/vendor/bin/drush status
```

This will explicitly run drush on the appserver which is generally where it is going to live. For further reading we document all of this over here:
https://docs.devwithlando.io/config/events.html#default-commands
