### ISSUE TITLE
Custom image override combined with recipe causes problems

### ISSUE THREAD

**Issue by tanc** [lando/lando#1521]
**Tell us about your setup**

Ubuntu 18.04 running Lando **v3.0.0-rc.13**

**Tell us about your `.lando.yml`**

Working:

```
name: test
services:
  node:
    type: 'node:10'
    overrides:
      image: 'agilecollective/lando-node:latest'
tooling:
  npm:
    service: node
```

Not working:

```
name: test
recipe: drupal8
services:
  node:
    type: 'node:10'
    overrides:
      image: 'agilecollective/lando-node:latest'
tooling:
  npm:
    service: node
```

**Tell us about the command you were running**

```
lando start
lando npm
```

**Tell us about the error you got**

When the drupal8 recipe is used and the lando file contains an overridden node image the wrong container is substituted for the node image (I think!).

*Example:*

```bash
lando npm
OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"npm\": executable file not found in $PATH": unknown
```

Whereas running the working lando file (without the recipe):

```bash
lando npm

Usage: npm <command>
```

**Tell us generally about your bug**

If you swap between the two `.lando.yml` files pasted above you will be able to replicate the problem.

Should this work? The documentation indicates it should so I'm assuming this is a bug.
