### ISSUE TITLE
Drupal 7 / Multi domaines

### ISSUE THREAD

**Issue by kamalkech** [lando/lando#1529]
- Lando version :  v3.0.0-rc.12

- Lando.yml : 

```
name: myproject
recipe: drupal7
config:
  webroot: .
  via: nginx
  php: '5.6'
proxy:
  appserver:
    - siteone.lndo.site:8888
    - two.siteone.lndo.site:8888
    - three.siteone.lndo.site:8888
```

All urls bellow not working and get with color red : 
 - siteone.lndo.site:8888
 - two.siteone.lndo.site:8888
 - three.siteone.lndo.site:8888

any idea plz

**Comment by danielnitsche** [comment]
@kamalkech `appserver` should read `appserver_nginx` if this is RC12.

https://docs.devwithlando.io/guides/updating-to-rc2.html

### old

```
proxy:
  nginx:
    - myapp.lndo.site
services:
  myservice:
    type: php
    via: nginx
```

### new

```
proxy:
  myservice_nginx:
    - myapp.lndo.site
services:
  myservice:
    type: php
    via: nginx
```

**Comment by danielnitsche** [comment]
It's also unusual to have `webroot: .` -- is this really where your Drupal installation is?

**Comment by kamalkech** [comment]
@danielnitsche yeh, lando.yml in the root of the project that raison i put `webroot: .`

**Comment by kamalkech** [comment]
```
name: myproject
recipe: drupal7
config:
  webroot: .
  php: '5.6'
proxy:
  myservice_nginx:
    - myproject-1.lndo.site
    - myproject-2.lndo.site
    - myproject-3.lndo.site
services:
  myservice:
    type: php
    via: nginx


```

this not working !
