### ISSUE TITLE
Can't get pre-destroy event to fire

### ISSUE THREAD

**Issue by skylennard** [lando/lando#1531]
When building a lando (Drupal 7 recipe) site, I'm defining a pre-destroy event to run a database backup prior to destroying my site.  The event doesn't seem to work however, as none of the commands are being run before the site is destroyed.

Here's my landofile:

```
name: my-website
recipe: drupal7
config:
  webroot: docroot
  php: 7.1
services:
  database:
    type: mysql
    creds:
      user: admin
      password: pass
      database: mydb
    run:
      # Automate database import on initial site build only
      - /helpers/sql-import.sh /app/mydb.sql.gz
  appserver:
    build_as_root:
      - /app/.build.sh
    xdebug: true
events:
  pre-destroy:
    - echo "...destroy!...?"
    - appserver: echo "Appserver = Destroy!?"
    - database: echo "Database = DESTROY!?"
```

When running `lando destroy`, I only see the following output:

```
Preparing to resign valley-metro-website to the dustbin of history...
Killing mywebsite_database_1  ... done
Killing mywebsite_appserver_1 ... done
Removing mywebsite_database_1  ... done
Removing mywebsite_appserver_1 ... done
Removing network mywebsite_default
Removing volume mywebsite_data_appserver
Removing volume mywebsite_home_appserver
Removing volume mywebsite_data_database
Removing volume mywebsite_home_database
Your app has paid the IRON PRICE. App destroyed!
```
