### ISSUE TITLE
lando pull of only pantheon db hangs at 0

### ISSUE THREAD

**Issue by possiBri** [lando/lando#1544]
**Tell us about your setup**

MacOS 10.4.3
Lando v3.0.0-rc.14

**Tell us about your `.lando.yml`**

```
name: calstates4
recipe: pantheon
config:
  framework: drupal
  env: local
  site: calstates4
  id: 23a4d2d1-ef2f-420d-8c62-1e78191e60b5
  drush: global:8.1.18
# Add in phpmyadmin
services:
  appserver:
    extras:
      - apt-get update -y
      - apt-get install nano -y
  database:
    type: mysql:5.7
```

`pantheon.yml` info:
```
api_version: 1
php_version: 7.0
drush_version: 8
```

**Tell us about the command you were running**

```lando pull
? Enter a Pantheon machine token [hidden]
? Pull code from? none
? Pull database from? live
? Pull files from? none

#Pantheon/terminus login and site checks

Pulling database from live...
0 B 0:43:00 [   0 B/s]
```

**Tell us about the error you got**

No error is received.

**Tell us generally about your bug**

After my work updated my MBP to Mojave I installed the newest version of Lando and went to pull the database from Live since it would've been lost in the wipe. I tried doing `lando pull` as I normally do, and everything seems to check out but the db never downloads. Also, I don't recall being asked for my machine-token on every attempt, which is also happening (not sure if related).

I have attempted several things, some suggested in other similar bugs (though not quite). Including:
`lando start` and `lando pull`
`lando start` then `lando rebuild`  and `lando pull`
`lando start` then `lando rebuild`  and `lando pull` (logged out of Docker)
`lando start` then `lando rebuild`  and `lando pull` (logged out of Docker and after running `lando destroy`
I also have attempted reinstalling Lando in case there was something funky in the initial install.

**Tell us more**

~~This bug prevents me from using lando.~~ I found the `lando import-db` command and was able to get a backup of the db into the appdb so I'm no longer in a total holding pattern. I'd still prefer to use the `lando pull` method though. Thanks for your help!
