### ISSUE TITLE
WP-CLI Errors

### ISSUE THREAD

**Issue by musicaljoeker** [lando/lando#1545]
Before you submit an issue make sure you have [downloaded](https://github.com/lando/lando/releases) the latest version of Lando and checked to see if the latest version resolves your issue! ✅ Done

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already. ✅ Done
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate. ✅ Done

If you are not sure how to do that then please complete as much of the below section as possible

**Tell us about your setup**

What is your lando version and operating system? v3.0.0-rc.14 on MacOS 10.14.3

**Tell us about your `.lando.yml`**

.lando.yml
```yml
name: schulze-family-foundation
recipe: pantheon
config:
  framework: wordpress
  site: schulze-family-foundation
  id: 8b640cc1-33ec-418a-829d-85689c799a57
```

pantheon.yml
```yml
# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1
```

pantheon.upstream.yml
```yml
# IMPORTANT NOTE:
# Do not edit this file unless you are doing so in your custom upstream repository.
# Override the defaults specified here in a site-specific `pantheon.yml` file.
# For more information see: https://pantheon.io/docs/pantheon-upstream-yml
api_version: 1
php_version: 7.2
```

*Example:*

```bash
lando wp
```

**Tell us about the error you got**

OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"wp\": executable file not found in $PATH": unknown

**Tell us generally about your bug**

Cloned a site directly from pantheon, started lando, and tried running the empty `wp` cli command.

**Tell us more**

Sorry I don't have much more information than this. The WP-CLI just doesn't seem to be working. I've tried restarting docker, lando, and completely reinstalling lando. None of it seems to resolve the issue.

**Comment by aromer** [comment]
I'm also getting the same error:
MacOS 14.4.4
Lando v3.0.0-rc.13

``` yml
name: <name>
recipe: pantheon
config:
  framework: wordpress
  site: <site>
  id: <id>
```

**Comment by spentro** [comment]
Same error:
MacOS 10.14.4
Lando v3.0.0-rc.14

```
name: <name>
recipe: pantheon
config:
  framework: wordpress
  site: <site>
  id: <id>
```

**Comment by nilsjesper** [comment]
Same issue

Lando v.3.0.0-rc.14

```
name: scdotorg
recipe: wordpress
config:
  webroot: .
```

**Comment by carlosesilva** [comment]
Same issue

Lando v.3.0.0-rc.13
```
name: <name>
recipe: pantheon
config:
  webroot: .
  framework: wordpress
  site: <site>
  id: <id>
  php: "7.2"
  database: mysql:5.7
  xdebug: true
  edge: false
  cache: false
```

**Comment by bsharpe** [comment]
Same Issue

MacOS 10.14.5
Lando v3.0.0-rc.16

```
name: <name>
recipe: wordpress
config:
  php: '7.3'
  via: nginx
  webroot: web
  database: mysql:5.7
  xdebug: true
```
