### ISSUE TITLE
Civicrm in Backdrop recipe "clean URLs" not working

### ISSUE THREAD

**Issue by ttrezren** [lando/lando#1546]
*CIVICRM in Backdrop -- upon successful install all civicrm pages return 404 not found if clean urls enabled*

Tried with lando rc.12, 13, 14

Apache mod_rewrite is enabled. Clean URLs are fine for backdrop pages. Don't know how to write a functional test for this.

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.0.0-rc.14 on Ubuntu 16.04 (have also replicated on OS X) 

**Tell us about your `.lando.yml`**

```yml
name: app
recipe: backdrop
config:
  webroot: backdrop
  php: 7.1
services:
  database:
    type: mysql
    portforward: true
    creds:
      user: backdrop
      password: backdrop
      database: backdrop
  cividata:
    type: mysql
    portforward: true
    creds:
      user: cividata
      password: cividata
      database: cividata
```

After lando init, download CMS and CRM

```bash
lando drush dlb backdrop --path="backdrop"
cd backdrop/modules
curl -LO https://sourceforge.net/projects/civicrm/files/civicrm-stable/5.11.0/civicrm-5.11.0-backdrop.tar.gz
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

- visit http:localhost:${port}
- initialize backdrop site
- visit http://localhost:${port}/modules/civicrm/install/index.php?q=civicrm_install_type=backdrop
- enter CMS and CRM database credentials and proceed to install
- upon successful install all civicrm pages return 404 not found

**Tell us about the error you got**
404 not found

**Tell us generally about your bug**
After install is successful, visit http://localhost:${port}/ and click civicrm menu item, result: 404 not found
Change /civicrm to ?q=civicrm and the page loads with error messages (submodules not found)
Can work around by turning off clean urls in backdrop
Clean urls work fine on backdrop pages
Have also replicated with single database (CRM and CMS in same db)

**Tell us more**
CiviCRM base_url appears to be correct
.htaccess and mod_rewrite are working for backdrop routes
I figure there must be something about being in a container that changes the way clean urls are resolved

Workaround is OK for development, so doesn't prevent using lando
