### ISSUE TITLE
Lando stopped working because of debian packages not found 404

### ISSUE THREAD

**Issue by dcorb** [lando/lando#1554]
It seems some packages were removed from mirrors ? https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

lando version beta47

**Comment by dcorb** [comment]
![image](https://user-images.githubusercontent.com/881333/54986415-44027080-4fbb-11e9-96d6-31d3bc2bc116.png)

**Comment by rabauss** [comment]
temporary solution would be:
````
services:
  appserver:
    build_as_root:
      - echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf
      - echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
      - sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list
````

see: https://unix.stackexchange.com/a/508948

**Comment by rabauss** [comment]
Unfortunately, the first line `echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf` is not working in rc.14 - but is working in rc.1 and via `lando ssh -u root`

@pirog why isn't the echo working in build_as_root with rc.14?

**Comment by acobster** [comment]
FYI, on rc.1 it didn't work to use `build_as_root` - I had to use `run_as_root` instead.

**Comment by tormi** [comment]
@pirog, using `php: '7.2'` resolved this for us in https://github.com/wunderio/WunderTools/pull/331.

**Comment by rabauss** [comment]
> FYI, on rc.1 it didn't work to use `build_as_root` - I had to use `run_as_root` instead.

Yes, you're right. At the moment I'm testing with rc.14 so sometimes some snippets won't work with rc.1 ;-)

My solution for the first line in rc.14 is now:

```
services:
    appserver:
        overrides:
            volumes:
                - ./.lando/apt.conf:/etc/apt/apt.conf
```

content of `./.lando/apt.conf`:
```
Acquire::Check-Valid-Until "false";
```

**Comment by tormi** [comment]
@rabauss , which PHP version you're using? Upgrading php to `7.2` fixed this issue for us without any additional hacks.

**Comment by rabauss** [comment]
yes, i know that php 7.2 and php 7.3 is running with stretch.

but umfortunately akeneo 2 requires php 7.1 - so we needed a workaround...

allthough I wonder why the echo for apt.conf won't work with rc.14

**Comment by pirog** [comment]
Ahhh right, looks like older jessie versions of debian are throwing this. Obviously upgrading to more recent versions of php is always a good and preferred mitigation step but we should handle this as well by switching to whatever is the new preferred source for jessie things.

**Comment by denics** [comment]
Dear all, 
I am a user with proxy and life is not easy. The solution proposed by @rabauss should be documented somewhere (I am using lando rc16) because it is the only way to run apt when behind a proxy.

As an improvement I would specify:

```yaml
    overrides:
      volumes:
        - ./.lando/apt_proxy.conf:/etc/apt/apt.conf.d/proxy.conf
```

and **apt_proxy.conf**

``
Acquire::http::Proxy "http://proxy.evil.com:8000";
``
