### ISSUE TITLE
Lando destroy only way to be able to restart SOLR and get new versions of configuration files

### ISSUE THREAD

**Issue by drupov** [lando/lando#1557]
**Tell us about your setup**

lando v3.0.0-rc.14
Ubuntu 18.10

**Tell us about your `.lando.yml`**

```
name: solr-test
services:
  solrsearch:
    type: solr:6.6
    core: solr
    portforward: 8983
    config:
      dir: ./files
```

**Tell us generally about your bug**

The files directory contains a bunch of configuration files for solr. Often these files have to be updated, in order to tune solr. After an update of such a file a restart of solr is needed.

Here is also the problem: only by running `lando destroy` I am able to get the updated version of the files.

`lando rebuild` and `lando restart`are not enough. To make things more interesting I was also not able to make these updates by deleting containers and even images directly through docker, `docker rm [container_id]` and `docker rmi [image_id]`.

The only thing that works is `lando destroy`, which is not ideal, as it means having to import databases anew on big project, that takes time etc.

Anyone has a clue on what's going on here?

**Comment by drupov** [comment]
Have kind of the same thing going on with a related issue:

If I launch a very plain lando environment with Drupal 8 with environment variables overrides only:

```
## .lando.yml
name: test
recipe: drupal8
config:
  via: nginx
  webroot: web
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/web
env_file:
  - .env
```

```
## .env
DB_USER=test
DB_PASSWORD=test
```

I am able to override the default database and username for that "drupal8"-recipe, which would be both "drupal8" (overridden by "test" with that).

If I decide later to not use the `.env`-file (so remove the file and remove the `env_file`-key in `.lando.yml` the only way to make the environment understand that is `lando destroy`. Not possible via `lando restart`, `lando rebuild` or by destroying containers and removing images via `docker rm` and `docker rmi`? Where is that data stored/cached? Can I purge it, without going the "destroy" route?
