### ISSUE TITLE
Installing terminus plugins creates a ~ directory on macOS

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#1560]
Please complete the following:

**Link to the page that needs to be updated or changed.**
https://docs.devwithlando.io/tutorials/pantheon.html#terminus-plugins

**Describe the change you'd like**
The current example of installing a terminus plugin is as follows:

```
services:
  appserver:
    build:
      - mkdir -p ~/.terminus/plugins
      - composer create-project -d ~/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:~1

```

This works for me on Windows 10.  But using the same code on macOS, I get a `~` directory with a `.terminus` subdirectory in my repository root.

Using lando v3.0.0-rc.14

Please update the example with correct code for macOS.
