### ISSUE TITLE
[v3.0.0-rc.14] Elasticsearch: primary shard is not active

### ISSUE THREAD

**Issue by rabauss** [lando/lando#1561]
We have some trouble with elasticsearch of bitnami since rc.14

In rc.1 everything worked fine with:
```
  elasticsearch:
    type: elasticsearch:5.5
    portforward: true
```

Our configuration to run akeneo2 has a lot of configuration params, which would be to much for here, because only elasticsearch is the problem now - just the main part:

```yml
name: akeneo2
recipe: lamp
config:
  php: '7.1'
  webroot: web
  database: mysql
  xdebug: true

services:
  elasticsearch:
    type: elasticsearch:5.6.15
    portforward: true
```
The containers are starting well and when we want to index products we get the error:

```
{"type":"unavailable_shards_exception","reason":"[akeneo_pim_product][3] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[akeneo_pim_product][3]] containing [21] requests]"}
```

We don't know if it's a lando problem or a general bitnami elasticsearch problem > then we would open an issue there...
It's not an akeneo problem because we had the same error with a non-akeneo project!

Can anyone help?

**Comment by rabauss** [comment]
for elasticsearch 5 in rc.14 I solved it by using the image of itzg.
this could be documented:
```
name: akeneo2
recipe: lamp
config:
  php: '7.1'
  webroot: web
  database: mysql
  xdebug: true

proxy:
  elasticsearch:
    - elasticsearch-akeneo2.lndo.site:9200
  kibana:
    - kibana-akeneo2.lndo.site:5601

services:
  elasticsearch:
    type: compose
    services:
      image: itzg/elasticsearch:5
      command: /start
      ports:
        - "9200"
        - "9300"
  kibana:
    type: compose
    services:
      image: itzg/kibana:5
      command: /start
      environment:
        ES_URL: http://elasticsearch:9200
      ports:
        - "5601"
      depends_on:
        - elasticsearch
```

for elasticsearch 6 we even use the official images:

````
name: es6
recipe: lamp
proxy:
  elasticsearch:
    - elasticsearch-es6.lndo.site:9200
  kibana:
    - kibana-es6.lndo.site:5601

services:
  elasticsearch:
    type: compose
    services:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
      command: docker-entrypoint.sh elasticsearch
      ports:
        - "9200"
        - "9300"
  kibana:
    type: compose
    services:
      image: docker.elastic.co/kibana/kibana:6.2.3
      command: ./bin/kibana
      ports:
        - "5601"
      depends_on:
        - elasticsearch
````

**Comment by kamalkech** [comment]
@rabauss and to add a config file "elasticsearch.yml" : 

recipe: lamp
proxy:
  elasticsearch:
    - elasticsearch-es6.lndo.site:9200
  kibana:
    - kibana-es6.lndo.site:5601

services:
  elasticsearch:
    type: compose
    services:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
      command: docker-entrypoint.sh elasticsearch
      ports:
        - "9200"
        - "9300"
     config:
      server: config/elasticsearch.yml
  kibana:
    type: compose
    services:
      image: docker.elastic.co/kibana/kibana:6.2.3
      command: ./bin/kibana
      ports:
        - "5601"
      depends_on:
        - elasticsearch

it s correct ?

**Comment by rabauss** [comment]
no because of custom container with `type: compose` you have to use volumes:
````
name: es6
recipe: lamp
proxy:
  elasticsearch:
    - elasticsearch-es6.lndo.site:9200
  kibana:
    - kibana-es6.lndo.site:5601

services:
  elasticsearch:
    type: compose
    services:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
      command: docker-entrypoint.sh elasticsearch
      ports:
        - "9200"
        - "9300"
      volumes:
        - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    type: compose
    services:
      image: docker.elastic.co/kibana/kibana:6.7.0
      command: ./bin/kibana
      ports:
        - "5601"
      depends_on:
        - elasticsearch
````

the config file has to be in the project folder in `./config/elasticsearch.yml`

see also: https://docs.devwithlando.io/tutorials/compose.html

**Comment by kamalkech** [comment]
@rabauss understood thank you

**Comment by kamalkech** [comment]
With file .lando.yml

```
name: drupal-8
recipe: drupal8
config:
  webroot: .
  via: nginx

proxy:
  elasticsearch:
    - elasticsearch-es6.lndo.site:9200
  kibana:
    - kibana-es6.lndo.site:5601

services:
  elasticsearch:
    type: compose
    services:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
      command: docker-entrypoint.sh elasticsearch
      ports:
        - "9200"
        - "9300"
  kibana:
    type: compose
    services:
      image: docker.elastic.co/kibana/kibana:6.7.0
      command: ./bin/kibana
      ports:
        - "5601"
      depends_on:
        - elasticsearch

```

I get this error :
![d8-el](https://user-images.githubusercontent.com/1313428/55674563-3946b600-58ae-11e9-8abf-5a0f45038184.png)


Elasticsearch server not working, any idea to understand why ?!!
