### ISSUE TITLE
SSH killed when node service `command` exits.

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#1562]
**Tell us about your setup**

What is your lando version and operating system?  v3.0.0-rc.14 on Ubuntu 18.04 LTS

**Tell us about your `.lando.yml`: "Broken" Version**

```yml
name: sonarqube

proxy:
  appserver:
    - sonar.lndo.site:3000

env_file:
  - .env

services:
  appserver:
    # Using a separate service to run the NPM command to prevent 'appserver' from booting the user when start command fails
    type: node:10
    command: "npm run start"
    build:
      - npm install
      - /app/setup/java/install_as_me.sh
    overrides:
      # These are good defaults to have for Lando. If needed, override them in the .env file
      environment: # Requires `lando rebuild` to apply
        SONARQUBE_WEB_HOST: appserver
        SONARQUBE_WEB_PORT: 3000
        SONARQUBE_JDBC_URL: jdbc:postgresql://database:5432/SonarQube
        SONARQUBE_JDBC_USERNAME: postgres
        SONARQUBE_JDBC_PASSWORD: postgres
```

**Tell us about your `.lando.yml`: Working Version**

```yml
name: sonarqube

proxy:
  appserver_proxy:
    - sonar.lndo.site:3000

env_file:
  - .env

services:
  appserver_proxy:
    # Using a separate service to run the NPM command to prevent 'appserver' from booting the user when start command fails
    type: node:10
    command: "npm run start"
    overrides:
      # These are good defaults to have for Lando. If needed, override them in the .env file
      environment: # Requires `lando rebuild` to apply
        SONARQUBE_WEB_HOST: appserver
        SONARQUBE_WEB_PORT: 3000
        SONARQUBE_JDBC_URL: jdbc:postgresql://database:5432/SonarQube
        SONARQUBE_JDBC_USERNAME: postgres
        SONARQUBE_JDBC_PASSWORD: postgres

  appserver:
    type: node:10
    build:
      - npm install
      - /app/setup/java/install_as_me.sh
```

**Tell us about the command you were running**

```bash
lando ssh appserver

while [ true ]; do echo "SSH 4 Life"; done
```

**Expected**: The `while` loop to continue until I stop it.

**Got:** Kicked out of the container because `command: npm run start` runs in the background on `lando ssh` and when the command fails, the SSH session ends.
