### ISSUE TITLE
Lando site loads extremely slow on local machine

### ISSUE THREAD

**Issue by klgh** [lando/lando#1573]
What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

* v3.0.0-rc.14 on macOS Mojave 10.14.3*

**Tell us about your `.lando.yml`**

```
name: (hidden)
excludes:
  - vendor
  - docroot/core
  - docroot/modules/contrib
  - docroot/themes/contrib
recipe: drupal8
config:
  php: 7.2
  webroot: ./docroot/
  xdebug: true
services:
  appserver:
    overrides:
      environment:
        SITE_HOST: (hidden).lndo.site
        MYSQL_HOST: database
        MYSQL_DATABASE: drupal8
        MYSQL_USER: drupal8
        MYSQL_PASSWORD: drupal8
        LEGACY_HOST: legacy-db
        LEGACY_DATABASE: legacy_db
        LEGACY_USER: legacy-user
        LEGACY_PASSWORD: legacy-pass
        LEGACY_SSH_HOST: ''
        LEGACY_SSH_USER: ''
        LEGACY_SSH_PASS: ''
        LEGACY_SSH_KEY: ''
        LEGACY_SFTP_PORT: ''
        LEGACY_SSH_LOCAL_HOST: ''
        LEGACY_SSH_PORT: ''
        LEGACY_SSH_REMOTE_PORT: ''
        PHP_IDE_CONFIG: "serverName=appserver"
  node:
    type: node
    globals:
      gulp-cli: latest
    build:
      - cd /app/docroot/themes/custom/dnh && yarn install
  # legacy-db for migration development. Can be commented out or removed after migrations are finalized.
  
 

tooling:
  site-install:
    service: appserver
    description: Install fresh drupal site from config.
    cmd: ./scripts/lando/site_install.sh
  run-test:
    service: appserver
    description: Run tests locally.
    cmd: composer test
  run-style-test:
    service: appserver
    description: Run style test locally.
    cmd: composer phpcs docroot tests
  sass-watch:
    service: node
    description: Watch sass directories and compiles on changes.
    cmd: "cd /app/docroot/themes/custom/dnh && gulp"
  js:
    service: node
    description: Make sure js files are available from libraries.
    cmd: "cd /app/docroot/themes/custom/dnh && gulp js"
  sass:
    service: node
    description: Compile sass files.
    cmd: "cd /app/docroot/themes/custom/dnh && gulp sass"
  theme-refresh:
    service: node
    description: Refresh theme dependant js and css files
    cmd: "cd /app/docroot/themes/custom/dnh && gulp refresh"
  migrate:
    service: appserver
    description: Run local migration.
    cmd: "./scripts/migrate/migrate-initial.sh"
```
Since this is a work project I put (hidden) where our client's name is

**Commands:**

```bash
lando stop
lando destroy -y
(Restart docker)
lando composer update
lando rebuild
lando start
lando site-install
```

**Tell us about the error you got**

site-install takes a long time to run, and once finished, the site loads extremely slow, making it difficult to do any development on. If I try to visit a new page, it takes at least 10 minutes to load, if not, more. 

**Tell us more**

Docker preferences are set to:  
CPUs: 6
Memory: 11.5 GiB
Swap: 3.0 GiB
