### ISSUE TITLE
XDebug broken after latest upgrade

### ISSUE THREAD

**Issue by barnettrob** [lando/lando#1575]
I just upgraded to v3.0.0-rc.14 and now XDebug is not working for me.

My .lando.yml file looks like:
```
name: edbd7
recipe: drupal7
config:
  webroot: docroot
  php: '7.1'
  drush: 8.1.15
  database: postgres
#  conf:
#    php: config/php.ini
services:
  cache:
    type: memcached:1.5.12
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  appserver:
    xdebug: true
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=edbd7.lndo.site"
proxy:
  mailhog:
    - mail.edbd7.lndo.site
```

When I remove the  PHP server settings for Xdebug, I'm able to get a prompt for "Incoming Connection From Xdebug" so I know lando is listening, however when I try to configure the server to the remote path, it doesn't work for me.

I have the Server settings as follows:
Name: edbd7.lndo.site
Host: edbd7.lndo.site
Port: 80
Debugger: Xdebug
checked for "Use path mappings"
I've tried mapping my local project root to /app but no luck.

Can someone please tell me how I should be mapping or if I should make a change to .lando.yml?

Thanks
