### ISSUE TITLE
db-import using stdin failing

### ISSUE THREAD

**Issue by aangelinsf** [lando/lando#1576]
What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**
v3.0.0.-rc-14 on macOS 10.14.3

**Tell us about your `.lando.yml`**
```
name: campaign-kit-standalone
recipe: drupal8
config:
  webroot: web
  php: '7.2'
  xdebug: true
  conf:
    php: config/php.ini
services:
  chromedriver:
    type: compose
    services:
      image: robcherry/docker-chromedriver:latest
      expose:
        - "4444"
      environment:
        CHROMEDRIVER_WHITELISTED_IPS: ""
        CHROMEDRIVER_URL_BASE: "/wd/hub"
      security_opt:
        - seccomp:unconfined
      command: ["/usr/local/bin/supervisord", "-c", "/etc/supervisord.conf"]
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=campaign-kit-standalone.lndo.site"
        PWD: /app
  database:
    portforward: 3307
tooling:
  drush:
    cmd: /app/vendor/bin/drush
  drupal:
    cmd: /app/vendor/bin/drupal
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
```

Perform the following:
```
lando db-export test.sql
cat test.sql | lando db-import
```

Result:
```
lando db-import <file>

Imports a dump file into a database service

Options:
  --clear        Clears the lando tasks cache                                                                               [boolean]
  --help         Shows lando or delegated command help if applicable                                                        [boolean]
  --verbose, -v  Runs with extra verbosity                                                                                    [count]
  --host, -h     The database service to use                                                                    [default: "database"]
  --no-wipe      Do not destroy the existing database before an import                                                      [boolean]

Not enough non-option arguments: got 0, need at least 1
```

And the import fails. Running with -vvv gives no extra information.
