### ISSUE TITLE
Using the same domain for multiple services but different ports

### ISSUE THREAD

**Issue by infernobass7** [lando/lando#1578]
Before you submit an issue make sure you have [downloaded](https://github.com/lando/lando/releases) the latest version of Lando and checked to see if the latest version resolves your issue!

**If you submit an issue against an older release of Lando there is a good chance your issues will not be addressed.** This is especially true if that issue is for 3.0.0-rc.1 or lower.

Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.

The **FASTEST** way for us to verify and resolve your bug if for you to [write a functional test that breaks](https://docs.devwithlando.io/dev/testing.html#functional-tests), submit it as a pull request and link to that pull request here.

If you are not sure how to do that then please complete as much of the below section as possible

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**
v3.0.0-rc.14 on Windows 10 Pro

*Example: v3.0.0-rc.2 on Windows 10 Professional*

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.
```yml
name: domain
recipe: laravel
config:
  php: "7.1"
  via: nginx
  webroot: public
  cache: memcached
proxy:
  pma:
    - pma-domain.lndo.site
  appserver_nginx:
    - domain2.lndo.site
    - domain.lndo.site
  node:
    - domain.lndo.site:6001 <--- I want to be able to hit this address and port externally
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
  redis:
    type: redis
  node:
    type: node
    globals:
      laravel-echo-server: latest
tooling:
  npm:
    service: node
events:
  post-start:
    - appserver: cd $LANDO_MOUNT && composer install
    - appserver: cd $LANDO_MOUNT && php artisan migrate
```

**Tell us generally about your bug**

I cannot access the `domain.lndo.site` and `domain.lndo.site:6001` when the services are separated. All traffic seems to be forwarded to the first service.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

*Example:*

1. Build the application
1. Setup Laravel using Laravel-echo and redis as broadcasting driver with socket.io
1. `lando ssh -s node`
1. `laravel-echo-server start`
1. Try to open the webpage using a private channel (requires authentication)
