### ISSUE TITLE
Elasticsearch container must be removed before each Lando restart in order to boot successfully

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#1592]
**Using:** v3.0.0-rc.14 on Ubuntu 18.04

**Tell us about your `.lando.yml`**

```yml
  ...
  recipe: lemp 
  search:
    type: elasticsearch:6
    plugins:
      - analysis-icu
```
**Error from `lando logs -s search`**

```
ERROR: plugin directory [/opt/bitnami/elasticsearch/plugins/analysis-icu] already exists; if you need to update the plugin, uninstall it first using command 'remove analysis-icu'
```

**Fix**

```yml
  search:
    type: elasticsearch:6
    build_as_root:
      - elasticsearch-plugin install analysis-icu
```
