### ISSUE TITLE
Support php 7.3 for pantheon recipe

### ISSUE THREAD

**Issue by jakebellacera** [lando/lando#1595]
## Issue overview

Lando >= v3.0.0-rc.13 supports PHP 7.3 (#1342), and Pantheon now forces PHP 7.3 on their upstream config, but the docker manifest for `devwithlando/pantheon-appserver:7.3-2` does not exist.

The suggested fix is to add the missing configuration to the manifest.

## Debug info

**Tell us about your setup**

Lando v3.0.0-rc.15 on macOS 10.14.4

**Tell us about your `.lando.yml`**

**.lando.yml**

```yml
name: REDACTED
recipe: pantheon
config:
  framework: wordpress
  env: dev
  site: REDACTED
  id: REDACTED
  index: false
  edge: false
  cache: false
  xdebug: true
```

**pantheon.upstream.yml**

```yaml
api_version: 1
php_version: 7.3
```

**Tell us about the command you were running**

```bash
# Edited my pantheon.yml as above
lando rebuild -y
```

**Tell us about the error you got**

This error is returned when `lando rebuild -y` is ran:

```bash
# ...
Pulling appserver (devwithlando/pantheon-appserver:7.3-2)...
ERROR: manifest for devwithlando/pantheon-appserver:7.3-2 not found
# ...
```
