### ISSUE TITLE
Override appserver_nginx image in Drupal 8 recipe

### ISSUE THREAD

**Issue by tanc** [lando/lando#1596]
As a lando user who works with Drupal sites, I want to be able to use a custom nginx image because I want to use Maxmind's GeoIP2 databases with a custom compiled nginx

I'm not sure whether its possible to do this at the moment. From issue #1487 it seems like overrides can only happen to both the appserver containers and therefore the image override wouldn't work.

Using the following bit of Lando config:
```
   appserver_nginx:
     overrides:
       image: nginx_geoip2
```

Throws: `TypeError: Cannot read property 'split' of undefined`

**Comment by tanc** [comment]
I was able to use a custom image by declaring the `appserver_nginx` config like this:
```
  appserver_nginx:
    type: nginx
    webroot: web
    config:
      vhosts: lando/default.conf
      server: lando/nginx.conf.tpl
    overrides:
      image: agilecollective/lando-nginx-geoip2:latest
```
For my purposes this works well enough so I'll close off this issue.
