### ISSUE TITLE
Defining an extra PHP based service in a Laravel App fails

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#160]
Bug Report
==========

**Tell us about your setup**

v3.0.0-alpha.13 on OSX Sierra

Have you previously installed lando? If so, what version?
I am sure I have, maybe alpha6 sounds familiar?

**Tell us about your bug**

Adding a second PHP service to a Laravel app results in Lando commands failing with a fatal JS error:

.lando.yml
```yaml
name: dropship
recipe: laravel

config:
  php: '7.1'
  via: nginx
  webroot: public
  database: postgres
  cache: redis
services:
  queue-worker:
    type: php:7.1

  node:
    type: node:6.10
    globals:
      yarn: "latest"

tooling:
  redis-cli:
    service: cache
  yarn:
    service: node
  node:
    service: node
  npm:
    service: node

```
```sh
dropship master % lando restart
error:  TypeError: Cannot read property 'split' of undefined
    at parseConfig (/snapshot/cli/plugins/lando-services/php/php.js:47:25)
    at Object.services (/snapshot/cli/plugins/lando-services/php/php.js:255:14)
    at Object.build (/snapshot/cli/plugins/lando-services/lib/services.js:259:38)
    at /snapshot/cli/plugins/lando-services/lib/config.js:28:41
    at isBind (/snapshot/cli/node_modules/lodash/lodash.js:4944:15)
    at baseForOwn (/snapshot/cli/node_modules/lodash/lodash.js:3001:24)
    at index (/snapshot/cli/node_modules/lodash/lodash.js:4913:18)
    at Function.forEach (/snapshot/cli/node_modules/lodash/lodash.js:9359:14)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-services/lib/config.js:20:9)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js:109:19)
    at /snapshot/cli/lib/events.js:170:19
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js:161:18)
    at /snapshot/cli/lib/app.js:157:25
From previous event:
    at instantiate (/snapshot/cli/lib/app.js:156:4)
    at /snapshot/cli/lib/app.js:341:16
From previous event:
    at Object.exports.get (/snapshot/cli/lib/app.js:325:4)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-tooling/lib/bootstrap.js:33:22)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js:109:19)
    at /snapshot/cli/lib/events.js:170:19
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js:161:18)
    at /snapshot/cli/lib/bootstrap.js:125:25
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at /snapshot/cli/lib/bootstrap.js:123:4
    at bitmask (/snapshot/cli/node_modules/lodash/lodash.js:10067:25)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js:17:1)
    at Module._compile (pkg/prelude/bootstrap.js:1151:22)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (pkg/prelude/bootstrap.js:1214:12)
    at run (bootstrap_node.js:432:7)
    at startup (bootstrap_node.js:192:9)
    at bootstrap_node.js:547:3
```

1. Add those contents to .lando.yml
2. run `lando`

Does this bug prevent you from using lando?
no
