### ISSUE TITLE
[v3.0.0-rc.15] OCI runtime failure, fresh lando install

### ISSUE THREAD

**Issue by merlinpatt** [lando/lando#1602]
I am seeing the same issue as #1424 on a new version. I have uninstalled both Docker and Lando and reinstalled them multiple times with no success. I have tried installing both via dmg and from source. I also tried both versions rc.7 and rc.8

Please help

*Version*: 
- v3.0.0-rc.15
- v3.0.0-rc.8
- v3.0.0-rc.7

*OS*: Mac

*Command*: `lando start`

*Error*

```bash
ERROR: for someproject_appserver_1  
Cannot start service appserver: OCI runtime create failed: 
container_linux.go:344: starting container process caused 
"process_linux.go:424: container init caused 
\"rootfs_linux.go:58: mounting \\\"/Users/merlin/.lando/engine/scripts/lando-entrypoint.sh\\\" to rootfs
\\\"/var/lib/docker/overlay2/62a2a75299b877e553a8fc40cd3eb7922a4b274a4ee68681087acf47408b7db6/merged\\\" at
\\\"/var/lib/docker/overlay2/62a2a75299b877e553a8fc40cd3eb7922a4b274a4ee68681087acf47408b7db6/merged/lando-entrypoint.sh\\\" 
caused \\\"not a directory\\\"\"": unknown: 
Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

*.lando.yml*

```yml
name: some-project
recipe: pantheon
config:
  framework: wordpress
  site: somesite
  id: 437a28ac-10fb-4cab-8652-637b2d924250
```

*pantheon.yml*

```yml
# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1
php_version: 7.2
```
