### ISSUE TITLE
`lando pull` does not download DB, hangs at 0 B/s

### ISSUE THREAD

**Issue by chrisrikli** [lando/lando#1605]
**Tell us about your setup**
MacOS 10.14.4 (18E226)
Lando v3.0.0-rc.15

**Tell us about your `.lando.yml`**

```
name: mypantheonsite
recipe: pantheon
config:
  framework: drupal
  site: mypantheonsite
  id: <redacted>
proxy:
  pma:
    - pma.mypantheonsite.lndo.site
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
  search:
    type: solr:5.5
    core: mypantheonsite
    config:
      conf: sites/all/modules/apachesolr/solr-conf/solr-5.x
```

`pantheon.yml`:
```
api_version: 1
php_version: 5.6
```

**Tell us about the command you were running**
```
> lando pull --code=none
? Choose a Pantheon account myaccount@domain.com
? Pull database from? live
? Pull files from? none

# Pantheon login etc
Pulling database from live...
live.12345@appserver.live.12345.drush.in's password:    0 B 0:00:01 [   0 B/s] [<=>                                                                                0 B 0:00:48 [   0 B/s] [<=>
```

**Tell us about the error you got**

No error is received; the clock just runs.

**Tell us generally about your bug**

Once I updated lando past RC2 this started happening on all of my lando containers.  I've destroyed and rebuilt, changed Pantheon terminus tokens, reinstalling Lando, reinstalling Docker, etc.  

**Tell us more**

Seeing this on all of my lando+Pantheon setups post RC2 upgrade.
