### ISSUE TITLE
Laravel 5.4.36 - Nginx 502 error

### ISSUE THREAD

**Issue by eleftrik** [lando/lando#1606]
I have and old Laravel project (version 5.4.36), previously running on Laradock and now on Lando (v3.0.0.-rc.14).

My .lando.yml:

```
name: my-app
recipe: laravel
config:
  php: '7.2'
  via: nginx
  database: mariadb
  xdebug: true
  webroot: public
proxy:
  appserver_nginx:
    - my.app.local.enc
domain: enc
proxyDomain: enc
services:
  appserver:
    type: php
    via: nginx
  database:
    type: mariadb
    portforward: 3306
    creds:
      user: user
      password: password
      database: database

```

As soon as I got a PHP error, I see in the browser a standard black & white "_502 Bad Gateway - nginx/1.14.2_".
I should instead see the classic Laravel error page...

`lando logs ` shows me the right PHP error and the stack. No other relevant information.

Can anybody help me? Thank you very much.
