### ISSUE TITLE
drush cc all / No Drupal Site found

### ISSUE THREAD

**Issue by eriksays** [lando/lando#1608]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**
lando version: v3.0.0-rc.15 on mac OS 10.14.4

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.
```
name: my-site
recipe: pantheon
config:
  framework: drupal
  site: lp-template
  id: [id]
  xdebug: true
```

**Tell us about the command you were running**
```
lando drush cc all
```

**Tell us about the error you got**
```
No Drupal site found, only 'drush' cache was cleared
```
