### ISSUE TITLE
Custom database config not being recognized

### ISSUE THREAD

**Issue by anakinjay** [lando/lando#1623]
**Tell us about your setup**
Basic lando setup using Drupal8 recipe

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**
v3.0.0-rc.16 on Mac OSX Mojave 10.14

**Tell us about your `.lando.yml`**
I'm attempting to increase the max_allowed_packet settings with a custom cnf

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

```yml
name: fs
recipe: drupal8
config:
  webroot: ./docroot
  config:
    database: config/my-custom.cnf
services:
  mail-hog:
    type: mailhog:v1.0.0
    portforward: false
    hogfrom:
    - appserver
tooling:
  blt:
    service: appserver
    cmd: blt

```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

config/my-custom.cnf:

```
[mysqldump]
max_allowed_packet = 500M
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

```
lando blt dsa
```
Also same error:
```
lando drush sql-sync @source @target
```

**Tell us about the error you got**
No error, but the setting does not take effect

**Tell us generally about your bug**
I'm trying to increase the max allowed packet size setting in the database using a custom CNF but nothing happens. No error, but the setting does not take effect.

**other**
this may also be helpful, running lando info shows that the config file is being picked up as it should.

```Javascript
{
    service: 'database',
    urls: [],
    type: 'mysql',
    internal_connection: {
      host: 'database',
      port: '3306'
    },
    external_connection: {
      host: 'localhost',
      port: '32786'
    },
    creds: {
      database: '****',
      password: '****',
      user: '****',
    },
    config: {
      database: 'config/my-custom.cnf'
    },
    version: '5.7',
    meUser: 'www-data',
    hostnames: [
      'database.fs.internal'
    ]
  },
```
