### ISSUE TITLE
Lando could not start after adding proxy

### ISSUE THREAD

**Issue by vothanhbinhlt** [lando/lando#1628]
Hello guys, I have had a problem after adding proxy to .lando.yml file. When I use `lando start` The console always show:
```
Writing lock file
Generating autoload files
Killing devpaneldrupal8lando_appserver_1 ... done
Creating devpaneldrupal8lando_phpmyadmin_1      ... done
Starting devpaneldrupal8lando_appserver_1  ... done
Creating devpaneldrupal8lando_database_1        ... done
Creating devpaneldrupal8lando_appserver_nginx_1 ... done
Waiting until appserver_nginx service is ready...
Waiting until database service is ready...
Waiting until phpmyadmin service is ready...
Waiting until appserver service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
...
```
Here is my .lando.yml file
```yaml
name: devpanel-drupal8-lando
recipe: drupal8
config:
  php: 7.1
  via: nginx
  database: mysql
  xdebug: false
  webroot: .
  drush: ^8
services:
  phpmyadmin:
    type: phpmyadmin:4.7
    hosts:
      - database
    overrides:
      environment:
        PMA_USER: drupal8
        PMA_PASSWORD: drupal8
proxy:
  appserver_nginx:
    - drupal-site1-ovz2tu.devpanel.io
  phpmyadmin:
    - phpadmin-site1-ovz2tu.devpanel.io
```
