### ISSUE TITLE
Pass info into custom tooling commands

### ISSUE THREAD

**Issue by barraponto** [lando/lando#1634]
Is it possible to pass lando info into custom tooling? For instance, I wanted to pass the appserver url into a drush command, like:

```yaml
tooling:
  login:
    service: appserver
    cmd: drush user-login --uri=`lando info --path [0]['urls'][0]`
```

What is the supported way to do that? The command above doesn't work.
Of course, I can pass that info as an option, but my goal was to just type `lando login`.
Hopefully, we could leverage info directly through special tokens, like `cmd: drush user-login --uri=@appserver.urls[0]`

**Comment by woodseowl** [comment]
@barraponto What I've found is by wrapping your command in a direct shell call you have access to the environment variables. Seems to work, if a little verbose. Here's my uli variant:
```
tooling:
  login:
    service: appserver
    description: Returns a one-time login for user 1 on local Lando site
    cmd:
      - /bin/sh -c 'drush uli --uri=https://$LANDO_APP_NAME.lndo.site'
```

Per the docs, there are lots of other environment variables you can hook into: https://docs.devwithlando.io/config/env.html
