### ISSUE TITLE
Allow multiple drupal installations under single lando instance

### ISSUE THREAD

**Issue by dawidnawrot** [lando/lando#1646]
I'd like to run several different drupal installations under one lando instance. In order to do that I need to somehow manage with dynamic webroot, so virtualhost redirects to different directory on each subdomain request. For example:

This is my proxy settings:
```
proxy:
  appserver:
    - "*.lm.lndo.site"
    - lm.lndo.site
```

I'd like `simple.lm.lndo.site` redirect to `sites/simple` directory and `simple` dir contains drupal installation. I tried to resolve it by overriding vhosts like so:

```
<VirtualHost _default_:80>
    ServerAlias *.localhost
    VirtualDocumentRoot "${LANDO_WEBROOT}/sites/%1"
    <Directory "${LANDO_WEBROOT}/sites/%1">
      Options Indexes FollowSymLinks
      AllowOverride All
      Require all granted
    </Directory>

    Error Documents
    ErrorDocument 503 /503.html
</VirtualHost>
```

I've also attached custom httpd.conf file which only differs from original one with enabling `vhost_alias_module` module:

`LoadModule vhost_alias_module modules/mod_vhost_alias.so`

But for some reason it doesn't work. It's giving me a 502 error on each subdomain request. Any help how to handle dynamic virtual hosts in lando? Or maybe someone has different idea how to solve it?

Lando file:
```
name: lm
recipe: drupal8
config:
  webroot: .
  config:
    server: config/httpd.conf
    vhosts: config/custom.conf
proxy:
  appserver:
    - "*.lm.lndo.site"
    - lm.lndo.site
tooling:
  drush:
    cmd:
      - /app/vendor/drush/drush/drush
  tooling:
  deploy:
    cmd:
      - database: /bin/bash /app/extras/scripts/db.sh
      #- appserver: /bin/bash /app/extras/scripts/deploy.sh
    level: app
    description: Deploys drupal single site
    options:
      word:
        passthrough: true
        describe: Print what the word is
        interactive:
          type: input
          message: What is the word?
          default: bird
          weight: 600
      color:
        passthrough: true
        describe: Print what the color is
        interactive:
          type: input
          message: What is the color?
          default: blue
          weight: 700
env_file:
  - extras/pl.env

```
