### ISSUE TITLE
Can't access Pantheon site via local IP - provided host name not valid

### ISSUE THREAD

**Issue by xaqrox** [lando/lando#1649]
**Tell us about your setup**

v3.0.0-rc16 on Ubuntu 16.04

**Tell us about your `.lando.yml`**

Vanilla Pantheon recipe:
```yml
name: defenders
recipe: pantheon
config:
  framework: drupal8
  site: defenders
  id: 0786b188-84e4-4b2f-99ec-5572fa5e8edb
```

With this `pantheon.yml`:
```yml
api_version: 1
web_docroot: true
php_version: 7.2
workflows:
  deploy:
    after:
      -
        type: webphp
        description: Import configuration
        script: private/scripts/drush_config_import.php
      -
        type: webphp
        description: Post to Slack
        script: private/scripts/slack_notification.php
  deploy_product:
    after:
      -
        type: webphp
        description: 'Run composer prepare-for-pantheon'
        script: private/scripts/deploy_product/prepare-for-pantheon.php
      -
        type: webphp
        description: 'Run composer install & drupal-scaffold'
        script: private/scripts/deploy_product/composer-install.php
  sync_code:
    after:
      - type: webphp
        description: Push changes back to GitHub if needed
        script: private/scripts/quicksilver/quicksilver-pushback/push-back-to-github.php
```

**Tell us about the command you were running**
1. Get your info.
```sh
lando start
lando info # look for edge_ssl's urls
hostname -I | cut -d' ' -f1 # get your local ip
```
2. Enter `https://[your local ip]:[port from edge_ssl's url]` into the address bar of Chrome.

**Tell us about the error you got**

3. See the error message in the browser:
> The provided host name is not valid for this server.

**Tell us generally about your bug**

I want to view my site on a different machine than the one that is running it. Since `lando share` seems to be broken right now (#1582) I'm trying to get it working over the LAN. I my understanding of this error suggests I need to get some service (edge_ssl?) to recognize that `[my local ip]` should be treated the same as `localhost` or `[my project].lndo.site` but I don't know where/how to do that. I tried using `[extra_hosts](https://docs.docker.com/compose/compose-file/#extra_hosts)` via a service override, but that only resulted in a non-functional app. Its quite possible I did that wrong.

**Tell us more**

If this is not a bug and just a quirk of the Pantheon recipe, then whatever technique is necessary should definitely be in the recipe's documentation. This isn't stopping me from using Lando but it is making testing this site in IE/Edge more of a pain than it already is...
