### ISSUE TITLE
Interactive options for tooling

### ISSUE THREAD

**Issue by dawidnawrot** [lando/lando#1655]
**Link to the page that needs to be updated or changed.**
https://docs.devwithlando.io/config/tooling.html

**Describe the change you'd like**
This is more a question rather than documentation change. So, lando comes with this handy  `interactive` feature for options we can pass. For now there's only an input option (or maybe there's more but it's not documented) so user can specify an option by typing a string, however it'd be awesome if user could select from predefined options. For example `lando init` comes with this feature (where you can select one of reciepes) and I'm wondering if there's a way to make it similarily in custom lando.yml tooling section, so instead of:

```
options:
      word:
        passthrough: true
        alias:
          - w
        describe: Print what the word is
        interactive:
          type: input
          message: What is the word?
          default: bird
          weight: 600
```

I could use something like this:
```
options:
      word:
        passthrough: true
        alias:
          - w
        describe: Print what the word is
        interactive:
          type: select
          message: What is the word?
          default: bird
          options: bird, dog, cat
          weight: 600
```
