### ISSUE TITLE
Running npm inside web container nodejs

### ISSUE THREAD

**Issue by sharique** [lando/lando#1659]
I'm a newbie here, I've a blt based project, during `blt setup` run few node commands to build drupal theme, giving error `npm command not found`.
Lando version rc16. 
Here my .lando.yml file.
```
name: myproject
recipe: drupal8
config:
  webroot: docroot

services:
  nodejs:
    type: node:10
    globals:
      gulp-cli: latest

  phpmyadmin:
    type: phpmyadmin

tooling:
  gulp:
    service: nodejs

  node:
    service: nodejs

  npm:
    service: nodejs

  blt:
    service: appserver
    cmd: /app/vendor/bin/blt

**Comment by pirog** [comment]
@sharique `blt` is running on your `appserver` service but your `node` runtime is isolated in a separate `nodejs` service so if you invoke `npm` from `appserver` this would be the expected behavior. 

A lot of our users have worked around this by installing `node` itself inside the `appserver` by using a lando build step. While this fundamentally breaks the "lando model" it is the best workaround for software packages that depend on more than one kind of language eg `nodejs` and `php`

**Comment by hotwebmatter** [comment]
Try something like this:

```
services:
  appserver:
    build_as_root:
      - apt update -y && apt install -y apt-transport-https
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - curl -sL https://deb.nodesource.com/setup_10.x | bash -
      - apt install -y nodejs
      - apt update -y && apt install -y yarn=1.12.3-1
    run:
      - cd $LANDO_MOUNT && composer install
      - cd $LANDO_MOUNT/docroot/themes/custom/custom_theme && yarn install
```

Watch out for issues raised here: https://github.com/yarnpkg/yarn/issues/7633

Yarn works now -- in the same container as BLT!
