### ISSUE TITLE
Allow faster xdebug on/off toggling

### ISSUE THREAD

**Issue by brooke-heaton** [lando/lando#1668]
**Please explain your request and its importance in the form of a user story.**

As a lando user who frequently needs to utilize xdebug to analyze php data, but also wants to use Lando 'at full speed', I want to be able to more quickly toggle xdebug on and off without a full Lando rebuild. The full rebuild process for some users can be VERY time intensive. 

**Please provide some detail on how lando can help solve this problem**

There are a couple of approaches to this that have been mentioned on the #docker channel on Drupal Slack. Both approaches utilize two php containers that are generated on docker start. One php container includes xdebug and the other does not. Deciding which php container to use is decided at run time by a cookie or environmental variable 

https://jtreminio.com/blog/developing-at-full-speed-with-xdebug/
Amazee labs Docker can toggle by restarting the container: https://github.com/drupal-graphql/drupal-decoupled-app/blob/master/docker-compose.yml#L20

**Is your feature request related to a problem? Please describe.**
Yes, I have a great deal of development friction from needing to have xdebug on all the time or from restarting my machine to turn it off. This seems like something that could easily be fixes by making it faster/simpler to toggle xdebug. 

**Describe the solution you'd like**
The ideal solution would not require restarting Lando and would utilize a cookie or variable to selection which php container to user for a given process.

**Comment by finnef** [comment]
I have found that by adding the following tooling to my .lando.yml I can quickly switch xdebug on and off:
`tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root
`
The equivalent for apache is 

`
tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root
`

**Comment by brooke-heaton** [comment]
Nice! Thanks for this @finnef I'm going to take it for a spin today.

**Comment by brooke-heaton** [comment]
@finnef I assume we then no longer need to set `config.xdebug` to true? or do you still set that?

**Comment by finnef** [comment]
No you don't need that. You can use it to set a default on lando rebuild/first run though.

**Comment by aklump** [comment]
@finnef Amazing solution, this is exactly what I was looking for!

**Comment by brooke-heaton** [comment]
@finnef this solution has been working very well for me. Nice add!

**Comment by finnef** [comment]
@pirog maybe this can be added as default tooling to various recipes?

**Comment by vasikgreif** [comment]
@finnef Thanks, this works great! My Wordpress install is still super slow with Xdebug enabled ( page load 1s with Xdebug disable, 20s with Xdebug enabled), not sure if this can be solved somehow, but at least there's an easy way to swich between on/off.

**Comment by osopolar** [comment]
I think `xdebug: true` is still required, setting `xdebug: false` for following drupal 8 recipe I get on `lando xdebug-off` the error: 

> rm: cannot remove '/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini': No such file or directory

```
recipe: drupal8
config:
  php: 7.2
  via: apache:2.4
  database: mysql:5.7
```

**Comment by hkirsman** [comment]
Wow, +10 for this. It really is the greatest annoyance for me at this time to enable/disable xdebug.

For apache, you could also do:

    service apache2 reload

**Comment by pirog** [comment]
This is a good idea so let's unstale for now!

**Comment by pirog** [comment]
Unstale x2

**Comment by hkirsman** [comment]
2 cents from me. I don't understand why but PhpStorm does not start listening Lando when you just use the fix above - xdebug-on. Only thing that seems to help is to rebuild. Wondering what is the magic and I think it's only possible to solve in Lando itself and not in the recipe. Should I ask PhpStorm helpdesk or you have hunch what is going on? All in all it's just port 9000 that PhpStorm is listening to, right?

**Comment by brooke-heaton** [comment]
@hkirsman Hm, sounds like your Xdebug server or php cli configuration may be off. You probably do need at least one build for PHPStorm to accept the connection, but it should be good to go after that. 

Do you have a `PHP_IDE_CONFIG` specified in your `.lando.yml` ?

For example:

```
services:
  appserver:
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
```

I'd take a gander at this helpful post by Mike Anello. 
https://www.drupaleasy.com/blogs/ultimike/2018/01/setting-xdebug-lando-and-phpstorm

**Comment by arischmod** [comment]
I confirm that the optional tooling script for nginx runs smooth.
Thanx!

**Comment by rxnlabs** [comment]
For anyone who needs to disable xdebug automatically when a WP CLI command is run (since xdebug for me at least greatly slows down WP CLI commands), you can combine events and tools to toggle xdebug. Drop this into your `.lando.yml` file

For Apache:
```yaml
events:
  pre-wp:
    - appserver: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload
  post-wp:
    - appserver: docker-php-ext-enable xdebug && /etc/init.d/apache2 reload
tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root
```

For NGINX:
```yaml
events:
  pre-wp:
    - appserver: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
  post-wp:
    - appserver: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root
```

With this, you can run your WP CLI commands like you regularly would `lando wp insert-command-here` and Xdebug will be disabled, your WP CLI command will execute, and when WP CLI is done, Xdebug will be re-enabled. You can still run the command `lando xdebug-off` and `lando xdebug-on` manually when you want.

**Comment by brooke-heaton** [comment]
Interesting - I'm not clear on the `pre-wp` event. For those using Drush with Drupal - is there a `pre-drush` event we can respond to?

**Comment by rxnlabs** [comment]
@brooke-heaton I'm sure there is. Since Drush is a built-in Lando tool that lando supports, I'm sure it will work for that. There is no actual documentation about `pre-wp` and `post-wp`. I just tried it out based on the Lando Event docs https://github.com/lando/lando/blob/master/docs/config/events.md. In particular this part of the doc https://github.com/lando/lando/blob/master/docs/config/events.md#default-commands . 

The section of the doc:

> In the above scenario, some-command will run on the web service by default instead of the appserver. For dynamic tooling routes events will use the default of the dynamic route.

```yaml 
events:
  post-dynamic:
    - some-command
tooling
  dynamic:
    cmd: env
    service: :host
    options:
      host:
        default: web2
        alias:
          - h
        describe: Run a different service```

The example in the docs talked about being able to hook into user-defined custom tooling for the tool that was created above and would be called using `lando dynamic`. I figured if there was a way to hook into a custom tool, there must be a way to hook into a built-in tool like `lando wp` since Lando installs WP-CLI in the appserver when you use the WordPress recipe. Tried it and bam it worked! 

I see no reason why this wouldn't work for Drush. 

```yaml events:
  pre-drush:
    - appserver: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
  post-drush:
    - appserver: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root```

This way you can type `lando drush insert-command-here` and before Drush is run, Xdebug will be disabled, NGINX restarted, your Drush command runs, and then Xdebug is re-enabled. The only downside is that I cannot refer to my custom tooling when I use Events, so I I have to have my command in the Lando YAML file twice. I would love it if I could just have my YAML file read:

```yaml events:
  pre-wp:
    - appserver: lando xdebug-off
  post-wp:
    - appserver: lando xdebug-on
tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root```

But sadly Lando does not support that since events and tooling work in the context of a "service" and Lando itself is not a "service".

**Comment by finnef** [comment]
+1 that would be a nice addition.

**Comment by martin-klima** [comment]
Stalebot, here is still hidden activity ;)

**Comment by rabauss** [comment]
Since rrc.2 I have had the problem that the very helpful xdebug toggle, results in a `502 Bad Gateway` after xdebug-off on apache - does anyone else know that problem?

**Comment by milkovsky** [comment]
Lando xdebug-on/off does not work for me.

I did the following:

1. - added the tooling commands from https://github.com/lando/lando/issues/1668#issuecomment-507191275
2. - removed `xdebug: true` from the `.lando.yml`
3. - `lando rebuild`

My setup: Lando v3.0.14, Ubuntu 18.04.5 LTS, `recipe: drupal8`.

**Comment by tormi** [comment]
I have a bit different approach by introducing `lando xdebug <mode>` tool, but it needs some final touches.

`.lando.yml`:

```
config:
  xdebug: off
services:
  appserver:
    overrides:
      environment:
        XDEBUG_MODE:
tooling:
  xdebug:
    description: Loads Xdebug in the selected mode.
    cmd: 
      - appserver: /app/.lando/xdebug.sh
    user: root
```

`/app/.lando/xdebug.sh`:

```
#!/bin/bash

if [ "$#" -ne 1 ]; then
  mode=off
  rm -rf /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  pkill -o -USR2 php-fpm
  echo "Xdebug is turned off."
  echo "Use 'lando xdebug <mode>' to load Xdebug in the selected mode."
  echo "Valid modes: https://xdebug.org/docs/all_settings#mode."
else
  mode="$1"
  docker-php-ext-enable xdebug
  echo xdebug.mode = "$mode" > /usr/local/etc/php/conf.d/xdebug.ini
  pkill -o -USR2 php-fpm
  echo "Xdebug is loaded in "$mode" mode."
fi
```

The problem is how to use a dedicated `/usr/local/etc/php/conf.d/xdebug.ini` file for Xdebug - it doesn't get loaded currently.

Tried also to use the `PHP_INI_SCAN_DIR` method described here: https://sheershoff.ru/custom-php-ini-docker-php-docker-compose-config/, but no luck.

**Comment by tormi** [comment]
> I have a bit different approach by introducing `lando xdebug <mode>` tool, but it needs some final touches. It would allow to load Xdebug modes on the fly, f.ex `lando xdebug debug,develop`.

Alright, let's fly - this is working now!! :tada:

`.lando.yml`:

```
config:
  xdebug: off
services:
  appserver:
    overrides:
      environment:
        XDEBUG_MODE:
        PHP_IDE_CONFIG: "serverName=appserver"
tooling:
  xdebug:
    description: Loads Xdebug in the selected mode.
    cmd: 
      - appserver: /app/.lando/xdebug.sh
    user: root
```

`/app/.lando/xdebug.sh`:

```
#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Xdebuf has been turned off, please use the following syntax: 'lando xdebug <mode>'."
  echo "Valid modes: https://xdebug.org/docs/all_settings#mode."
  echo xdebug.mode = off > /usr/local/etc/php/conf.d/zzz-lando-xdebug.ini
  pkill -o -USR2 php-fpm
else
  mode="$1"
  echo xdebug.mode = "$mode" > /usr/local/etc/php/conf.d/zzz-lando-xdebug.ini
  pkill -o -USR2 php-fpm
  echo "Xdebug is loaded in "$mode" mode."
fi
```

`README.md`:

```
## [Tools](https://docs.lando.dev/config/tooling.html)

- `lando xdebug <mode>` - load [Xdebug](https://xdebug.org/) in the selected [mode(s)](https://xdebug.org/docs/all_settings#mode)
```
