### ISSUE TITLE
Unable access new plugins and themes from wordpress

### ISSUE THREAD

**Issue by yashas-bhandary** [lando/lando#1670]
Wordpress is running fine. But it is not accessing the internet to load new plugins and themes. I am getting error when I access this page http://localhost:32789/wordpress/wp-admin/plugin-install.php
![localhost_32789_wordpress_wp-admin_plugin-install php(Laptop with MDPI screen)](https://user-images.githubusercontent.com/29854066/59654946-0f671500-91b6-11e9-81c0-22c388b67726.png)

> An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums.

.lando.yml :
```
name: web-server
recipe: lamp
config:
  webroot: www
  database: mysql:5.7
  php: '7.3'
services:
  phpmyadmin:
    type: phpmyadmin:4.7
    hosts:
      - database
```
