### ISSUE TITLE
Elasticsearch service configuration

### ISSUE THREAD

**Issue by jhoopes** [lando/lando#1672]
Hello, just a quick summary at the top with more specifics below... 

but it seems that bitnami changed their elasticsearch configuration (at least with version 6), and the service setup within lando no longer satisfies what needs to happen for elasticsearch to run as a single node instance.  This may be related to #1561, but the bitnami image no longer sets the default elasticsearch container up as a container that can be run as a standalone node, since it sets ```node.master:true```, but ```node.data:false``` and ```node.injest:false```, signifying that this particular node can no longer do things like search queries or run analysis on the data.

Additionally the custom config file we could specify now no longer actually does anything due to the configuration now needing to overwrite the elasticsearch.yml file directly, instead of copying to a "custom" configuration file the service recipe currently does

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**
v3.0.0-rc.17 on Windows 10 Pro

**Tell us about your `.lando.yml`**

```yml
name: my-app
recipe: laravel
config:
  php: '7.2'
  via: nginx
  webroot: public
services:
  database:
    type: mysql:8.0
    creds:
      user: lando
      password: lando
      database: lando
    portforward: 3307
    config:
      database: .lando/my_custom.cnf
  elasticsearch:
    type: elasticsearch:6
    portforward: true
    config:
      server: .lando/elasticsearch.yml
  redis:
    type: redis
excludes:
    - .idea
    - .git
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

```
[mysqld]
default-authentication-plugin=mysql_native_password
```

elasticsearch.yml (an attempt to fix the problem, but this also fails due to the config file not being used by the bitnami setup)
```
cluster.name: "my-app"
node:
  data: true
  injest: true
```

**Tell us about the command you were running**
lando start

**Tell us about the error you got**

elasticsearch service with the default configuration no longer functions as an injest or data node in the node cluster

**Tell us more**

In came to the summary above from trying a few things and also reading through the readme  on the bitnami github page for the elasticsearch image  https://github.com/bitnami/bitnami-docker-elasticsearch

As a workaround, and what I did to get it to work was, after setup, I did the following

```
lando ssh --service elasticsearch --user root
> apt-get update && apt-get install vim
> cd /opt/bitnami/elasticsearch/config
> vim elasticsearch.yml
## Edit the elasticsearch configuration to turn data to true and ingest to true
>exit
lando restart
```

After restarting the docker containers, which restarts elasticsearch with the updated configuration, the elasticsearch node operates as normal
