### ISSUE TITLE
vnu as a service

### ISSUE THREAD

**Issue by risker** [lando/lando#1686]
Hey all,

I'm trying to start the [nu html validator](https://github.com/validator/validator) as a lando service. However, it does not seem to start properly.

**Tell us about your setup**

What is your lando version and operating system?

*v3.0.0-rc.17 on Windows 10 Professional*

**Tell us about your `.lando.yml`**

```yml
name: project
recipe: wordpress
proxy:
  vnu:
    - vnu.project.lndo.site:8888
services:
  vnu:
    type: compose
    services:
      image: validator/validator:17.11.1
      ports:
        - '8888:8888'
```

**Tell us about the command you were running**

`lando start`

**Tell us about the error you got**

> ERROR: No container found for vnu_1
> error: Looks like vnu is not running! It should be so this is a problem.

**Tell us generally about your bug**

I'd expect the vnu service to be available to me at `vnu.project.lndo.site` (or at least running in the background), but it's not.

`docker ps -a` shows that the container `Exited (0) About a minute ago`.

If I use the docker-compose example from validator docs, the service starts successfully:

```yml
version: '3'
services:
  vnu:
    image: validator/validator
    ports:
      - "8888:8888"
    network_mode: "host"
```

The only difference between my lando config and the docker-compose config is `network_mode` key, but if I add it to my lando config, I get the following error:

> ERROR: 'network_mode' and 'networks' cannot be combined

**Comment by pirog** [comment]
@RichardDavies best guess here is you need to specify the `command`, take a note at teh config docs for compose services, specifically the part about configuring the entrypoint/command
https://docs.devwithlando.io/tutorials/compose.html#configuration

**Comment by risker** [comment]
Thanks @pirog!

I went on a little wild goose chase here since the `validator/validator` Dockerfile has changed a bit since last tagged release, so I spent _some_ time figuring out why the newer commands did not work.

For anyone stumbling here, the following worked:
```
name: project
recipe: wordpress
proxy:
  vnu:
    - vnu.project.lndo.site:8888
services:
  vnu:
    type: compose
    services:
      image: validator/validator:17.11.1
      command: java -cp dist/vnu.jar nu.validator.servlet.Main 8888
      ports:
        - '8888:8888'
```

Interesting that the container itself does just `java -cp vnu.jar nu.validator.servlet.Main 8888` (note no `dist` folder), but I have to target the dist folder... Guess it's a lando thing?
