### ISSUE TITLE
Database operations fail immediately after lando starts

### ISSUE THREAD

**Issue by danepowell** [lando/lando#1688]
**Tell us about your setup**

master (HEAD) as well as v3.0.0-rc.17 on Ubuntu 19.04

**Tell us about your `.lando.yml`**

```yml
name: dt524
recipe: drupal8
config:
  webroot: docroot
```

**Tell us about the command you were running**

We have a custom node.js script that runs lando start, and immediately after it finishes runs Drush commands (`drush uli`, etc) against the container. Use the Drush alias below and run this command (without having previously started this lando container): `lando start && drush @dt524.local uli`

```
local:
  docker:
    service: appserver
    exec:
      options: --user www-data
  uri: dt524.lndo.site
  root: /app
  paths:
    drush-script: /app/vendor/bin/drush
```

**Tell us about the error you got**

Drush fails with `SQLSTATE[HY000] [2002] Connection refused`.

**Tell us generally about your bug**

This is a closely-related follow-up to https://github.com/lando/lando/issues/677 (the error is basically the same). I think the fix that was implemented after that issue is incomplete.

Looking at the logs from the database service creation, I can see that after the mysql service is first started and ready, it takes 1-2 seconds longer for the `drupal8` user to be created. The fix in #677 doesn't use an actual db user for the healthcheck, it only uses the root user, so it reports the container as ready 1-2 seconds before it actually is.

I think the MySQL health check here should use an actual user instead of root. I've verified that this solves the problem, but I'm not sure how to do it in a more general way (I don't know how to access the db creds for the healthcheck).

https://github.com/lando/lando/blob/97986cb0f5dde2c4dc2705fd977a58c43aabbc5e/plugins/lando-services/services/mysql/builder.js#L19

**Comment by danepowell** [comment]
Oh... it appears that performing the healthcheck from the db service with the actual db user isn't even a complete fix. You can still get a failure when running commands in the appserver that access the database remotely (as with `drush @dt524.local uli`).

I've adjusted my `.lando.yml` as follows and this seems to be a complete fix, but obviously it couples the appserver to the db container which is less than ideal.

```
name: dt524
recipe: drupal8
config:
  webroot: docroot
services:
  appserver:
    overrides:
      healthcheck:
        test: mysql -udrupal8 -pdrupal8 --host=database drupal8 --silent --execute "SHOW TABLES;"
        interval: 1s
        timeout: 10s
        retries: 25
```

**Comment by pirog** [comment]
@danepowell great report here. 

So, we definitely dont want to couple the healthcheck of one service to another. I think that is going to make things pretty hard to manage. Trying to use the lando-created db user seems the better bet and i *think* should be possible to do programmatically.

**Comment by danepowell** [comment]
@pirog just checking using the db user still isn't sufficient. That healthcheck can pass and still later connections will be refused.

I have a theory based on [my database container logs](https://gist.github.com/danepowell/3565ee31149aae141e76e0fa044a5c1a): I think the MySQL server is actually starting, stopping, then starting again. This would explain why the healthcheck might pass (after the server initially starts), but a connection a moment later might be refused, and then just moments after that everything's working again.

**Comment by danepowell** [comment]
Upstream issue. Not so much a bug as a support request: https://github.com/bitnami/bitnami-docker-mysql/issues/73

**Comment by danepowell** [comment]
Upstream PR: https://github.com/bitnami/bitnami-docker-mysql/pull/74

If that gets merged, then Lando could simply add this healthcheck:
`bash -c "[ -f /bitnami/mysql/.mysql_initialized ]" && mysql -udrupal8 -pdrupal8 --host=database drupal8 --silent --execute "SHOW TABLES;"`

**Comment by pirog** [comment]
@danepowell got it. thanks for the awesome research on this. seems easy enough to fix once this is merged upstream.

do you suspect we have a similar issue with the mariadb and postgres images?

**Comment by danepowell** [comment]
I've never used those services, but yes, from the looks of it they would be equally affected by this. Both follow the pattern of starting the db server, terminating it, then starting it again:

- https://github.com/bitnami/bitnami-docker-mariadb/blob/d649319b93f29431e6eb818a8149367a70231af1/10.1/debian-9/rootfs/setup.sh#L19
- https://github.com/bitnami/bitnami-docker-postgresql/blob/2c2038e0472012a4e23565a7cafcbcdd46a66c0f/9.6/debian-9/rootfs/setup.sh#L26

**Comment by kimdcottrell** [comment]
Chiming in here since I may have a solution. It's specific to Docker tho, but Lando uses Docker under the hood so you can probably make sense of this and add it in. I don't know node so I can't. :( 

The MySQL container in Docker (not even using Lando) can't rely on healthchecks to determine when to import a database. I'm not exactly sure why, but something in MySQL seems to make this unreliable. In my experience, certain tables can't be found during the `INSERT` statements, despite their `CREATE` statements clearly being above the `INSERT`s in the sql file.

The solution to this is to create a named volume for a folder in the MySQL container called `/docker-entrypoint-initdb.d/` that contains all .sql files seen on your local machine. So in `docker-compose.yml`, you would write something like so:

```
services:
    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql:delegated
            - ./tmp:/docker-entrypoint-initdb.d
            - ./config/my.cnf:/etc/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: coffee
            MYSQL_PASSWORD: coffee
            MYSQL_DATABASE: espresso_machine
        healthcheck:
            test: mysqladmin ping -ucoffee -pcoffee -hlocalhost || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
```

And on your local machine you'd have your app's `tmp` dir have things like:

```
setup-test-database-and-users.sql # e.g. for wordpress's testing suite, you may want to include a basic user and testing database
production-backup.sql 
```

And then when you run `docker-compose up`, the mysql container will - in most cases - properly import the database. The only issue I've hit so far is when mysql is looking for lowercase tables when someone has used camelCase. To fix this, I've added these lines to my `my.cnf` file that also gets volumed to the container:

```
# mysql will check if tables exist using the lower case value during data import
lower_case_table_names = 1
```

Afaik, something like this exists in every version of the mysql container's entrypoint code. You can review the code part of it here: https://github.com/mysql/mysql-docker/blob/mysql-server/5.7/docker-entrypoint.sh#L149

Hope it helps! :D
