### ISSUE TITLE
Configuring Drush root dir prevents Backdrop Drush working properly

### ISSUE THREAD

**Issue by BWPanda** [lando/lando#1692]
When you configure the Drush root directory in Backdrop as per https://docs.devwithlando.io/tutorials/backdrop.html#configuring-your-root-directory, Drush stops working properly, defaulting to Drupal commands instead of Backdrop ones.

**Steps to reproduce:**

1. `mkdir drush`
1. `cd drush`
1. `lando init`
    - Codebase: current working directory
    - Recipe: backdrop
    - Webroot: www
    - Name: drush
1. `git clone git@github.com:backdrop/backdrop.git www`
1. `lando start`
1. Access the site's URL to run the installer
1. `cd www`
1. `lando drush dl simplify`
    - "Success: Project simplify downloaded to /app/www/modules/simplify." :+1: 
1. `rm -r modules/simplify/`
1. Add the following to `.lando.yml`:
    ```yml
    tooling:
      drush:
        service: appserver
        cmd: drush --root=www
    ```
1. `lando drush dl simplify`
    - "Success: Project simplify (8.x-1.0) downloaded to /app/www/simplify." :-1: 
      (Wrong version and wrong directory)

**What is your lando version and operating system?**

v3.0.0-rc.17 on Linux Mint 19.1 Cinnamon

**Tell us about your `.lando.yml`**

```yml
name: drush
recipe: backdrop
config:
  webroot: www
tooling:
  drush:
    service: appserver
    cmd: drush --root=www
```
