### ISSUE TITLE
Can you use arguments in tooling cmd's?

### ISSUE THREAD

**Issue by purdy** [lando/lando#1697]
I'm creating a custom tooling to pull down a database backup and I'd like to be able to use a parameter to specify which environment to pull from. Here's my idea:

```
tooling:
  latest:
    service: appserver
    description: Updates the database from the latest backup
    cmd:
      - mkdir -p /app/artifacts
      - rm -f /app/artifacts/database.sql.gz
      - terminus backup:get [SITENAME].:env --element=db --to=/app/artifacts/database.sql.gz
      - database: cd /app && /helpers/sql-import.sh artifacts/database.sql.gz
      - cd /app/web && drush cr && drush sql-sanitize --sanitize-password="1234" --yes && drush config-split-import config_dev -y
    options:
      env:
        default: live
        describe: Which environment do you want the backup from (default live).
```

But when I try to run this, it says:

```
$ lando latest --env dev
mkdir: unrecognized option '--env'
Try 'mkdir --help' for more information.
```

**Comment by pirog** [comment]
@purdy this is already possible by combining your commands into a bash script and using lando's tooling "options". Here are the relevant docs and examples for you to consider
https://docs.devwithlando.io/config/tooling.html#options-driven-tooling
https://github.com/lando/lando/blob/master/examples/tooling/.lando.yml#L22
https://github.com/lando/lando/blob/master/examples/tooling/word.sh

**Comment by purdy** [comment]
My lando cmd does one thing in the database service, though. If I used this approach, it would run that command in the appserver service, and not sure how it could then do a database import.

**Comment by pirog** [comment]
not sure why that is relevant. you can still define options/arguments and have them passed into whatever combinations of scripts/commands in whatever combination of services you want. you also have access to `/helpers` and your database container from within `appserver` so not even necessary to run commands outside of the appserver if you prefer.

this is to say we are pretty sure our existing configuration around tooling covers all the major use cases and we dogfood that exact functionality within lando to provide pretty complicated options/interactive functionality across multiple services.

**Comment by ericwong3** [comment]
@pirog I have another case which requires similar feature that cannot be worked around like that. 

In my case, I have a node js (next.js) application which has to be built (using `yarn run build`). And I also have a custom service which run ansible for deploying to our staging and production server.

In this case, I need to run `yarn build` on appserver and `ansible-playbook` on ansible (the service). I have a wrapper script for ansible-playbook which takes some arguments but then problem will arise. In particular, imagine that my wrapper script has signature `/app/script/deploy.sh [env]`, and my Landofile has:
```
tooling:
  'deploy [env]':
    cmd:
      - appserver: yarn run build
      - ansible: /app/script/deploy.sh
```

Now that it becomes a problem when I execute `lando deploy staging` because appserver will run `yarn run build staging` and that is not what I intend (i.e. there might be side effect adding a parameter there).

Though I could add a /app/script/yarn-run-build.sh which is just `yarn run build` such that the parameter is dropped/filtered when calling yarn run build, but that is some extra indirection which I wish could be avoided. Or better yet, be solved by OC's suggestion.
