### ISSUE TITLE
Xdebug Connection Timeout due to LANDO_HOST_IP not updating when network changes

### ISSUE THREAD

**Issue by snipebin** [lando/lando#1700]
# Setup

Lando Version: v3.0.0-rc.17
OS: 
```
Distributor ID:	Ubuntu
Description:	Pop!_OS 19.04
Release:	19.04
Codename:	disco
```

# .lando.yml

```
# Name the application the same as in your .platform.app.yaml.
name: poc
# Use the recipe appropriate for your application.
recipe: drupal8

excludes:
  - vendor
  - node_modules
  - web/modules/contrib
  - web/core

config:
  # Lando defaults to Apache. Switch to nginx to match Platform.sh.
  via: nginx

  # Set the webroot to match your .platform.app.yaml.
  webroot: web

  # Lando defaults to the latest MySQL release, but Platform.sh uses MariaDB.
  # Specify the version to match what's in services.yaml.
  database: mariadb:10.1

  xdebug: true
  config:
    php: php.ini

proxy:
  appserver_nginx:
    - poc.lndo.site
    - olivers.lndo.site
    - shivs.lndo.site

# Add additional services
services:
  appserver:
    build_as_root:
      - apt-get update
      - apt-get install -y gnupg2
      - apt-get install -y software-properties-common
      - apt-get install -y apt-transport-https ca-certificates
      - wget -q https://packages.sury.org/php/apt.gpg -O- | apt-key add -
      - echo "deb https://packages.sury.org/php/ stretch main" | tee /etc/apt/sources.list.d/php.list
    build:
      - composer install
    webroot: web
    xdebug: true
    config: 
      php: php.ini
  rediscache:
    type: redis
    persist: true
    portforward: true
  redisqueue:
    type: redis
    persist: true
    portforward: true
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
      - oliversdb
      - shivsdb
  oliversdb:
    type: mariadb:10.1
    portforward: true
  shivsdb:
    type: mariadb:10.1
    portforward: true
  mailhog:
    type: mailhog:v1.0.0
    portforward: false
    hogfrom:
      - appserver

# Add additional tooling
tooling:
  redis-cli:
    service: redisqueue
```

# .php.ini

```
[PHP]

; Xdebug
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
; Extra custom Xdebug setting for debug to work in VSCode.
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_host = ${LANDO_HOST_IP}
; xdebug.remote_connect_back = 1
xdebug.remote_log = ./xdebug.log
```

# Tell us about the command you were running / Steps to Reproduce

```bash
# from the root dir where .lando.yml is found
1. lando start
2. lando ssh
3. echo $LANDO_HOST_IP
> 192.168.42.5
4. ping $LANDO_HOST_IP
> PING 192.168.42.5 (192.168.42.5) 56(84) bytes of data.
> 64 bytes from 192.168.42.5: icmp_seq=1 ttl=64 time=0.187 ms
5. Start Xdebug Session
6. Load/Request Lando site/app
7. cat xdebug.log 
>  # empty file
8. exit
9. *Change WIFI network to one with a different gateway & address range*
10. lando restart
11. lando ssh
12. echo $LANDO_HOST_IP
> 192.168.42.5
13. ping $LANDO_HOST_IP
> PING 192.168.42.5 (192.168.42.5) 56(84) bytes of data.
14. ^C
> --- 192.168.42.5 ping statistics ---
> 137 packets transmitted, 0 received, 100% packet loss, time 139271ms
15. Start Xdebug Session
16. Load/Request site/app
17. cat xdebug.log
>  opened at 2019-07-16 01:27:39
> Log opened at 2019-07-16 01:27:39
> Log opened at 2019-07-16 01:27:39
> I: Connecting to configured address/port: 192.168.42.5:9000.
> E: Time-out connecting to client (Waited: 200 ms). :-(
> Log closed at 2019-07-16 01:27:39
```

# Tell us about the error you got

Xdebug cannot connect to xdebug client  running on the host because `LANDO_HOST_IP` has the wrong outdated address after network changes. This breaks xdebug implementation given usage in https://github.com/lando/lando/blob/2e8746e825b025590dea66cf349f168c912bb1c6/docs/guides/lando-with-vscode.md#L65 and https://github.com/lando/lando/blob/970fece27d6e6afba84f79c14258c1bbc570fbfa/plugins/lando-services/services/php/builder.js#L140

Changing the value directly in php.ini does not work either, I think because `XDEBUG_CONFIG` env value ends up taking "Local" php config preference.

Wondering if there's a workaround with overrides, build/post build steps or service status "hook" if any available? I switch networks a lot so this is a real pain.
