### ISSUE TITLE
Broken HTTPS after last update

### ISSUE THREAD

**Issue by vasikgreif** [lando/lando#1703]
After updating to Lando RC17, my https URL's stopped working. Updating to RC18 did not help. I didn't change any configuration.

My config is:
```
name: hyponamiru
recipe: wordpress
excludes:
  - web/wp-content/plugins
  - web/wp-content/uploads
  - web/wp-admin
  - web/wp-includes
  - web/wp-content/themes/astra-child/node_modules
  - web/wp-content/themes/astra-child/.git
  - web/wp-content/themes/astra-child/vendor
config:
  php: 7.2
  via: nginx
  database: mariadb
  webroot: web
  xdebug: true
proxy:
  mailhog:
    - mail.hyponamiru.lndo.site
services:
  mailhog:
      type: mailhog
      hogfrom:
        - appserver
      portforward: true

```

And the result (the https URL's are red):

```
BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME                  hyponamiru                                    
 LOCATION              /Users/vasik/Dev/hyponamiru                   
 SERVICES              appserver_nginx, appserver, database, mailhog 
 APPSERVER_NGINX URLS  https://localhost:32789                       
                       http://localhost:32790                        
                       http://hyponamiru.lndo.site:8000              
                       https://hyponamiru.lndo.site                  
 MAILHOG URLS          http://localhost:32788                        
                       http://mail.hyponamiru.lndo.site:8000         
                       https://mail.hyponamiru.lndo.site         
```

The http URLs with port work fine. I did try rebuilding the app multiple times. Any fix for that?
