### ISSUE TITLE
Drupal 8 allow syslog to be catch by `lando logs`

### ISSUE THREAD

**Issue by JorisInsign** [lando/lando#1705]
Hello,

As a lando user who works with Drupal, I want to be able to use the syslog module rather than the dblog one.
The final goal is to be able to see "drupal logs" via `lando logs`.

Is there a way to configure drupal syslog module or lando to do that ?

Thanks a lot,

**Comment by pirog** [comment]
@JorisInsign so `lando logs` is just a light wrapper around `docker logs` which usually just reads from `stdout` and/or `stderr`. So you've need to configure your application to write messages to either of those file descriptors. 

This is actually in our `lando logs` docs
https://docs.devwithlando.io/cli/logs.html
see the BRIGHT BLUE BOX ;)

**Comment by maskedjellybean** [comment]
I wanted something similar, mainly because Drush 10 no longer allows tailing with `drush wd-show`. I don't have an answer to merge Drupal logs with `lando logs`, but I was able to tail syslog using a custom tooling command `lando logs-drupal` (or whatever you want to call it).

**Comment by maskedjellybean** [comment]
I wanted something similar, mainly because Drush 10 no longer allows tailing with `drush wd-show`. I don't have an answer to merge Drupal logs with `lando logs`, but I was able to tail syslog using a custom tooling command `lando logs-drupal` (or whatever you want to call it). Here's what I came up with.

Some of this is extra complicated because I don't want the syslog module enabled on production. To solve that I created a config split using the config_split module, allowing me to enable syslog only when necessary. The machine name of the config_split is `config_dev_syslog`. https://www.drupal.org/docs/contributed-modules/configuration-split/creating-a-simple-split-configuration-dev-modules-only. If syslog can be enabled on production, you can simplify this significantly.

**.lando.yml**
```
services:
  appserver:
    build_as_root:
      # We want to remove drupal.log so it doesn't get too big,
      # but we want to allow rsyslog to create it so it has correct permissions.
      - rm -f /app/lando/logs/drupal.log
      # Install and configure rsyslog. This will allow us to use the Drupal core syslog
      # module to tail logs in CLI. (Drush 9 removed the ability to tail the dblog).
      # See logs-drupal Lando tooling command.
      - apt-get update && apt-get -y install rsyslog
      - cat /app/lando/rsyslog-conf/rsyslog.conf >> /etc/rsyslog.conf
      - service rsyslog start
 tooling:
    service: appserver
    description: Displays and tails Drupal logs using syslog module (because drush wd-show no longer supports tail)
    cmd:
      - /app/lando/scripts/logs-drupal.sh
    user: root
```

**/lando/rsyslog-conf/rsyslog.conf**
```
#
# Configure syslog facility configured in Drupal
# at /admin/config/development/logging to output to
# custom log file.
#
local7.* /app/lando/logs/drupal.log
```

**/lando/scripts/logs-drupal.sh**
```
#!/usr/bin/env bash

# This file is configured in .lando.yml. Run: lando logs-drupal.
# It will enable the syslog module using config_split module,
# start the rsyslog service and tail the log file. This is really
# only necessary because Drush 10 removed the ability to tail `drush wd-show`.

NORMAL="\033[0m"
RED="\033[31m"
YELLOW="\033[32m"
ORANGE="\033[33m"
PINK="\033[35m"
BLUE="\033[34m"

echo
echo -e "${YELLOW}Enabling syslog module...${NORMAL}"
echo
sed -i "s/config_dev_syslog']\['status'] = FALSE/config_dev_syslog']\['status'] = TRUE/" /app/web/sites/default/settings.local.php
drush cr
drush config-split:import config_dev_syslog -y
service rsyslog start;
echo
echo -e "${YELLOW}Tailing logs...${NORMAL}"
echo
tail -f /app/lando/logs/drupal.log | tr -s '|' \\t
```

**/web/sites/default/settings.local.php**
```
$config['config_split.config_split.config_dev_syslog']['status'] = FALSE;
```

In the Drupal syslog module configuration:

- In the Syslog format field, format the fields like "!timestamp | !type" (separating the fields with |. If you use a different separator, you'll have to tweak the `tail` command in `/lando/scripts/logs-drupal.sh`.
- In Syslog facility field, choose LOG_LOCAL7. If you choose a different facility, you need to modify `/lando/rsyslog-conf/rsyslog.conf`.

Run `lando rebuild`. After rebuild completes, you should be able to tail syslog by running `lando logs-drupal`.
