### ISSUE TITLE
Granting IDs to proxies routes

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#1706]
**Please explain your request and its importance in the form of a user story.**

*Example: As a lando user who works with multiple proxies for a single service, I want the option to add IDs to the proxies so that my app knows how to assign URLs when parsing a routes environment variable*

*Example from Platform.sh routes.yaml*

```yaml

####
# In this example, disregard "type" and "upstream" properties.
###

"https://{default}/": # Define the primary app route
  primary: true
  id: base-path # Our app can use the ID to identify or the "primary" property
  type: upstream
  upstream: "corp-americas:php"

"https://media.{default}/": # Declare CDN domain for media
  id: cdn-media # Note, no "primary" property here. It can only be assigned once.
  type: upstream
  upstream: "corp-americas:php"

"https://static.{default}/":  # Declare CDN domain for static JS/CSS
  id: cdn-static  # Note, no "primary" property here. It can only be assigned once.
  type: upstream
  upstream: "corp-americas:php"

"https://backend1912.{default}/": # Declare an admin path
  id: admin-magento  # Note, no "primary" property here. It can only be assigned once.
  type: upstream
  upstream: "corp-americas:php"
```

**Is your feature request related to a problem? Please describe.**
If I can not assign ID's to routes, then my app must have hard-coded logic assuming the base route and how to parse that route in order to assign the subdomains to the route. This would break if one of the routes did not use the same host as the "primary" proxy

**Describe the solution you'd like**
Create a LANDO_ROUTES environment variable that parses to an array or otherwise a backward-compatible LANDO_INFO update that includes the IDs of the routes

**Describe alternatives you've considered**
- Hard-coding dev routes
- Parsing a proxy to get the {domain}.lndo.site and then prepending hard-code subdomain assumptions such as "media.", "cdn.", "static.", etc..
- Forcing all URLs in development to use a single app proxy

**Additional context**

> Forcing all URLs in development to use a single app proxy

The downfall here is that I am unable to know if a change is going to break my CORS policies in
