### ISSUE TITLE
Container IP instead of external one is shown in logs

### ISSUE THREAD

**Issue by drupov** [lando/lando#1713]
.lando.yml file, nothing special here:

```
name: mysite
recipe: drupal7
config:
  webroot: web
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/web
```

Every logged event shows the internal container IP and this is the same for all logs.

![image](https://user-images.githubusercontent.com/1836325/61689852-aaf92180-ad30-11e9-923d-494fbaa46eba.png)

How can this be changed to show the real IP?

Thanks!
