### ISSUE TITLE
Error: elasticsearch 7 MINOR versions are not supported

### ISSUE THREAD

**Issue by tormi** [lando/lando#1729]
**Tell us about your `.lando.yml`**

```
services:
  elasticsearch:
    type: elasticsearch:7.3
    portforward: "9200"
```

gives `Error: elasticsearch version 7.3 is not supported`.
