### ISSUE TITLE
How to expose additional ports?

### ISSUE THREAD

**Issue by eleftrik** [lando/lando#1732]
Sorry for the _trivial_ question, but I could't find any solution in the documentation.
How to expose additional ports?

I'm using `laravel` recipe (PHP, Nginx, MariaDB). Everything's good with http, https and db access from the host (my pc).
Inside the appserver container, I need to launch a cli application which listens on port 6001, then I need to expose that port so I can connect from the host.
How to do that?
Currently I'm using Lando v3.0.0-rc.14

Thanks for any help

**Comment by pirog** [comment]
@eleftrik without knowing a ton of details about the cli application i'd suggest you check out 
https://docs.lando.dev/config/services.html#localhost-assignment which is an advanced feature that allows lando to expose and scan for additional ports

**Comment by idrislab** [comment]
I have same setup as @eleftrik, i'm exposing 6001 for a websocket server.

**Comment by eleftrik** [comment]
> @pirog I have same setup as @eleftrik, i need to expose 6001 for a websocket server.

I solved it introducing another application container. Don't know if it's best way, but it works. I tried to expose port 6001 in the appserver container, but in my case it didn't work.

Here my .lando.yml:

```
name: myproject
recipe: laravel
config:
  php: '7.3'
  via: nginx
  database: mariadb
  xdebug: true
  webroot: public
proxy:
  appserver_nginx:
    - myproject.test
domain: test
proxyDomain: test
services:
  appserver:
    type: php
    via: nginx
  websockets:
    type: php
    via: cli
    overrides:
      ports:
        - 6001:6001
  database:
    type: mariadb
    portforward: 3306
    creds:
      user: user
      password: password
      database: database
  redis:
    type: redis:5
    portforward: 6379

```

The `websockets` container allows me to SSH into it and then run `php artisan websockets:serve` (it's a Laravel project with [Laravel Websockets](https://github.com/beyondcode/laravel-websockets) replacing a Pusher server)

**Comment by Simoneu01** [comment]
@eleftrik can u share your env file ?

**Comment by eleftrik** [comment]
> @eleftrik can u share your env file ?

@Simoneu01 Do you mean my .env Laravel file? Which part are you interested in ?

**Comment by Simoneu01** [comment]
I can't get the websocket to work using the https protocol.

i wanted to know what you wrote as "host" and as ssl file

**Comment by eleftrik** [comment]
> I can't get the websocket to work using the https protocol.
> 
> i wanted to know what you wrote as "host" and as ssl file

This is my configuration in production:

```
APP_URL=https://api.domain.tld
...
BROADCAST_DRIVER=pusher
...
WEBSOCKETS_SERVER_HOST=127.0.0.1
WEBSOCKETS_SERVER_PORT=6001
WEBSOCKETS_SERVER_HTTPS=false
```

Despite the last property is set to false, everything works under HTTPS.

Nginx is configured to proxy websockets requests (coming over SSL) to Laravel websockets worker, which is listening on port 6001.

Something like this:

```
map $http_upgrade $type {
    default "web";
    websocket "ws";
}

server {
    listen 10.100.10.192:6001 ssl;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name api.domain.tld;

.......

    location @web {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location @ws {
        proxy_pass             http://127.0.0.1:6001;
        proxy_set_header       X-Forwarder-For $remote_addr;
        proxy_set_header Host  $host;
        proxy_read_timeout     86400;
        proxy_connect_timeout  86400;
        proxy_redirect         off;

        # Allow the use of websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

```

Supervisord is monitoring the execution of the aforementioned worker, which is launched via this command:

`php /var/www/api.domain.tld/htdocs/current/artisan websockets:serve --host=127.0.0.1 --port=6001`

Hope this helps!

**Comment by eminos** [comment]
@eleftrik Did you ever solve the laravel-websockets with lando issue? Portforwarding 6001?
I can't figure out how to open up port 6001 on the custom websockets lando service.
Also proxy, because my site is on a custom dev domain...?

**Comment by eleftrik** [comment]
> @eleftrik Did you ever solve the laravel-websockets with lando issue? Portforwarding 6001?
> I can't figure out how to open up port 6001 on the custom websockets lando service.
> Also proxy, because my site is on a custom dev domain...?

Yes, as I wrote, I used this configuration: https://github.com/lando/lando/issues/1732#issuecomment-531726063
I'm using a custom dev domain too.

**Comment by silverham** [comment]
I'd like to note, especially for nodejs lando plugin (could work with other plugins), the following worked for me to assign internal ports to a random free host port. Note that the ports must be assigned to both `moreHttpPorts` and `overrides => ports`, as `moreHttpPorts` will only scan for the port and enable it if already open, whilst the seconds keeps it open.

```yml
services:
  nodejs:
    type: node:custom
    moreHttpPorts:
      - '3000'
      - '3001'
    overrides:
      # Build key is unrelated, used to add gulp and set working directory in the image.
      build:
        context: .
        dockerfile: docker-build-files/Dockerfile.nodejs
      ports:
       - '3000'
       - '3001'
```
Check host assigned ports via `lando info -s nodejs`:
```js
[ { service: 'nodejs',
    urls: [ 'http://localhost:50903', 'http://localhost:50904' ],
    type: 'node',
    healthy: true,
    config: {},
    version: 'custom',
    meUser: 'node',
    hasCerts: false,
    hostnames: [ 'nodejs.mynodeapp.internal' ] } ]
```
@see also https://docs.lando.dev/core/v3/services.html#localhost-assignment
