### ISSUE TITLE
Disabling opcache for Drupal 8

### ISSUE THREAD

**Issue by jigarius** [lando/lando#1734]
* I am using the `drupal8` recipe and I would like to disable opcache.
* When I run `lando ssh` and try to edit the relevant `php.ini` file, I find that there is no editor available.
  * This brings me to the first requirement – how do I run custom commands during the build process to make `nano` or `vim` available inside the container(s)?
* When I am doing dev tasks and editing PHP, I see that `opcache` is enabled and my changes to PHP files are not detected.
  * This brings me to the second requirement – how do I disable opcache, possible, without having to manually edit the `php.ini` file.

**Comment by daltonrooney** [comment]
I was having crazy issues with caching on a new LAMP container this morning. Not just PHP files, but all assets were stale and would not refresh until I rebuilt the server. I reverted to a PHP 7.2 image and everything seems fine. So maybe not as simple as just disabling the opcache?

**Comment by ericpugh** [comment]
@jigarius you can easily add nano or vi under "[tooling](https://docs.lando.dev/config/tooling.html#usage)", For example:
```
tooling:
  nano:
    service: appserver

```

**Comment by jigarius** [comment]
Thanks. I tried as you suggested, but with `vim` and it didn't work. I ended up adding the following lines though and it worked:
```yaml
config:
  services:
    appserver:
      extras:
        - apt update -y
        - apt install -y vim
```

**Comment by jigarius** [comment]
Right when I thought it was working, it wasn't. Having added the above lines, I get an additional appserver server named `appserver_nginx`. Is there a way to avoid that?

More than being able to install `nano`, I'd be interested in running custom commands like `apt update -y && apt install imagemagick`, etc. Any help will be appreciated.

**Comment by eelkeblok** [comment]
Use build or build_as_root:

```
services:
  appserver:
    build_as_root:
      - apt update -y && apt install imagemagick
    build:
      - composer install
```
