### ISSUE TITLE
https does not work with wildcard subdomain

### ISSUE THREAD

**Issue by JasonTheAdams** [lando/lando#1744]
**Tell us about your setup**
v3.0.0-rc.19 on MacOS 10.14.5

**Tell us about your `.lando.yml`**
```yml
name: giveio
recipe: laravel
services:
  database:
    portforward: 3310
  mailhog:
    type: mailhog
    portforward: true
config:
  webroot: public
  php: 7.2
  database: mysql:5.7
  via: nginx
  xdebug: true
proxy:
  appserver_nginx:
    - giveio.lndo.site
    - "*.giveio.lndo.site"
```

**Tell us generally about your bug**
When viewing a domain that uses the wildcard the SSL certificate does load, but is marked as invalid by the browser:
![Screenshot](https://cl.ly/c59edc96a159/download/Image%2525202019-08-14%252520at%25252012.55.07%252520PM.png)

The root domain certificate works just fine, and I ran the command that adds it to keychain, and I can see the certificate in keychain as fully trusted.

For all intents and purposes it seems like it should be trusted. I'm not sure what's causing the issue. 🤔
