### ISSUE TITLE
Unable to connect to MySQL database on Laravel

### ISSUE THREAD

**Issue by JasonTheAdams** [lando/lando#1746]
**Tell us about your setup**
MacOS v3.0.0-rc.20 on MacOS 10.14.5

**Tell us about your `.lando.yml`**
```yml
name: hasonethrough
recipe: laravel
services:
  database:
    portforward: 3310
  mailhog:
    type: mailhog
    portforward: true
config:
  webroot: public
  php: 7.2
  database: mysql:5.7
  via: nginx
  xdebug: true
proxy:
  appserver_nginx:
    - test.lndo.site
```

**Tell us about the command you were running**
```bash
lando start
php artisan migrate
```

**Tell us about the error you got**
Last command outputs:
```
   Illuminate\Database\QueryException  : SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known (SQL: select * from information_schema.tables where table_schema = laravel and table_name = migrations and table_type = 'BASE TABLE')

  at /Users/jason/Sites/laravel-hasonethrough-bug/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   PDOException::("PDO::__construct(): php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known")
      /Users/jason/Sites/laravel-hasonethrough-bug/app/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  2   PDO::__construct("mysql:host=database;port=3306;dbname=laravel", "laravel", "laravel", [])
      /Users/jason/Sites/laravel-hasonethrough-bug/app/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70
```

**Tell us generally about your bug**
Simply unable to do anything with the database from Laravel. It _is_ connecting to the database, but then it fails to perform any operation. I am able to connect to the database externally via Sequel Pro, however, just not internally via Laravel.

**Tell us more**
Definitely can't use Laravel with Lando if I'm unable to connect to the database. 😄
