### ISSUE TITLE
Support Request: Using Solr 4.5 service

### ISSUE THREAD

**Issue by jigarius** [lando/lando#1748]
I am using the `drupal8` recipe for a Drupal 8 project. However, I have to use Solr 4.5 which is not supported by Lando. I read the docs, but didn't find any examples for doing it. Can someone kindly help me with an example?

This is how my `services` part of the `.lando.yml` looks right now:

```yaml
services:
  solr:
    # I need this to be solr:4.5 somehow.
    type: solr:5.5
    portforward: true
    core: foobar
    config:
      # This I can change to 4.x so, no worries.
      conf: docroot/modules/contrib/search_api_solr/solr-conf/5.x
```

Any help will be appreciated. Go Lando!

**Comment by jigarius** [comment]
Also, the reason why I need to use Solr 4.5 is because the project already uses it and Acquia is using 4.5 also (at least on that subscription).

**Comment by pirog** [comment]
@jigarius use our legacy solr version `4` or `4.10` its probably sufficient for your use case.
https://docs.lando.dev/config/solr.html#legacy-versions

**Comment by jigarius** [comment]
Thanks for the prompt reply, but I already tried 4.10 and it wasn't sufficient. Hence, I am still struggling to install Solr 4.5.x because that's what Acquia has setup for my site. A sample `services` entry would be sufficient to get me going. Especially, the `volume` line. Here's what I have so far:

```yaml
services:
  solr:
    type: compose
    services:
      image: catchdigital/solr:4.5.1
      container_name: solr
      ports:
        - "8983:8983"
      restart: always
      #      volumes:
      #        - ./example/
      command: ["/opt/solr/bin/solr", "start", "-f"]
```

I need to specify / know the Solr core and the URL. I'm very new to this, so kindly excuse any dumb questions.
