### ISSUE TITLE
Give an end user plugin/task creation example.

### ISSUE THREAD

**Issue by JorisInsign** [lando/lando#1751]
Hello,

**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/contrib/plugins.html

**Describe the change you'd like**
I would like to have more real world end user plugin/tooling creation example.
For example : Is it possible to have a plugin "per project" ? In order for example to declare custom tasks but related to this particular project ?

Is it possible to create "tooling" with interactive options but with choices processed via a script ? 
For exemple : a tool for erasing a directory : 

```
tooling:
  erasedir:
    service: appserver
    description: Erase a directory
    cmd: /app/lando/synclocal.sh
    level: app
    options:
      directory:
        passthrough: true
        describe: Which directory do you want to eras ?
        interactive:
          type: list
          message: Which directory ?
          choices: `find . -maxdepth 1 -type d`
```

Thanks for your help,
