### ISSUE TITLE
Angular Recipe

### ISSUE THREAD

**Issue by neuronick** [lando/lando#1752]
Could somebody share / post Angular Recipe for Lando?

I have tried bundled MEAN Recipe, but cannot access Angular app from outside the app container (inside the container, when doing lando ssh, I am able to access the Angular app by using CURL).

I have tried to change ports with no results.

I get either 'Bad gateway' message or nothing at all (ERR_CONNECTION_REFUSED).

Thanks in advance.

**Comment by andreiscripcaru22** [comment]
@neuronick Hi there! Did you find any solution finally?

**Comment by garrettw** [comment]
I have this issue as well. I think part of the problem is that, while `npm start` is run automatically, any errors from that are not output, so if it fails, we don't know.

I just tried running `npm start` explicitly after booting up my container, and only then did I discover an error preventing it from working.

**Comment by xXCalleManXx** [comment]
I have a "recipe" here if anyone can use it:

```
name: <project>
excludes:
  - ./node_modules
services:
  angular:
    type: node
    command: npm run start
    port: 4200
    ssl: true
proxy:
  angular:
    - <project>.lndo.site:4200
tooling:
  npm:
    service: angular
    command: npm
```

Inside you package.json you should have a script called "start" with this value
```
ng serve --host 0.0.0.0 --disable-host-check
```
