### ISSUE TITLE
Unable to pass shell input to Lando command

### ISSUE THREAD

**Issue by ivangrynenko** [lando/lando#1762]
Please complete the following:

**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/config/tooling.html#usage

**Describe the change you'd like**
I cannot find a way to pass a command argument to a lando tooling script.
For example: `lando download-db "databasename"` 
Not sure if possible at all, as the documentation does not show such an option.

**Comment by tormi** [comment]
### .lando/name.sh

```
#!/bin/sh

NAME=$1
echo "Hello," $NAME
```
### .lando.yml

```
tooling:
  name:
    service: appserver
    cmd: 
      - .lando/name.sh
```

Rebuild Lando with `lando rebuild` and use tool with `lando name Tormi` (outputs _Hello, Tormi_).
