### ISSUE TITLE
.lando.local.yml: PORTFORWARD: {PORT} does not override PORTFORWARD: true on rebuild

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#1781]
1. [x]  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
2. [x] Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.

**Tell us about your setup**

- **Lando Version:** v3.0.0-rc.20
- **OS:** Ubuntu 18.04.3 LTS
- **Lando File:**
```yml
name: magento
recipe: lemp
env_file:
  - .env

proxy:
  appserver_nginx:
    - magento.lndo.site
  pma: 
    - pma.lndo.site

config:
  webroot: pub
  php: 7.1
  xdebug: false
  database: mariadb:10.2
  config:
    php: .lando/config/php.ini
    database: .lando/config/mysql.cnf

services:
  appserver:
    build:
      -  composer install -o

  database:
    portforward: true
  magento-db:
    type: mariadb:10.2
    portforward: true
    creds:
      user: magento
      password: magento
      database: magento

  wp-db:
    type: mariadb:10.2
    portforward: true
    creds:
      user: wordpress
      password: wordpress
      database: wordpress

  pma:
    type: phpmyadmin
    hosts:
      - database
      - magento-db
      - wp-db
```

- **.lando.local.yml**

```yaml
services:
  database:
    portforward: 33070
  wp-db:
    portforward: 33071
  magento-db:
    portforward: 33072
```

After running `lando rebuild` I still get random ports assigned to my databases.
