### ISSUE TITLE
Lando Config: PHP & MSSQL

### ISSUE THREAD

**Issue by mikemilano** [lando/lando#1796]
No issue. Just capturing for reference and search:

Martin Kilma (`martin_kilma`) posted in Slack for `sqlsrv + pdo_sqlsrv` PHP extension which he used to migrate data from a remote MS SQL server to Drupal. He followed the steps [here](https://www.microsoft.com/en-us/sql-server/developer-get-started/php/ubuntu) to make it.

```
services:
  appserver:
    overrides:
      environment:
        ACCEPT_EULA: "Y"
    build_as_root:
      - apt-get update -y
      - apt-get install apt-transport-https -y
      - curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
      - curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
      - apt-get update -y
      - apt-get install msodbcsql17 -y
      - apt-get install unixodbc-dev -y
      - pecl install sqlsrv
      - pecl install pdo_sqlsrv
      - docker-php-ext-enable sqlsrv
      - docker-php-ext-enable pdo_sqlsrv
```
