### ISSUE TITLE
Use variables in .lando.yml

### ISSUE THREAD

**Issue by jigarius** [lando/lando#1809]
This is more like a support request, but I couldn't find a category like that, so I made it a feature request.

* Say, I have many projects powered by Lando
* For each project, I use a port-prefix, e.g. `99`
* I use the port prefix to generate ports for all services, e.g. port `80` is exposed at `9080` and so on.

Is there a way I can emulate this using lando? For example,
```yaml
services:
  mailhog:
    type: mailhog
    portforward: "{prefix}80"
```
