### ISSUE TITLE
Wordpress gets cycle redirect

### ISSUE THREAD

**Issue by Deyter** [lando/lando#1810]
Today I tried latest version of lando and:
1. adminer don't start
`ERROR: for adminer  Cannot start service adminer: OCI runtime create failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/app\") set in config.json failed: permission denied": unknown
`
2. I got cycle redirect on wp-admin page

Previous version worked ok.

My config:
```yaml
name: project
recipe: wordpress
config:
  webroot: web
  xdebug: true
  php: '7.2'
  via: nginx
services:
  cli:
    type: 'node:8'
  adminer:
    type: compose
    services:
      image: adminer
      environment:
        - ADMINER_DEFAULT_SERVER=database
      command: docker-php-entrypoint php -S [::]:8080 -t /var/www/html
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
proxy:
  mailhog:
    - mail.twinning.lndo.site
  adminer:
    - adminer.twinning.lndo.site:8080
events:
  post-wp-init:
    - appserver: >
        cd $LANDO_MOUNT/web/
        && [ ! -f index.php ] && wp core download --version="5.2.2" --force --skip-content
        || echo "WordPress appears to already be installed, skipping"
        && [ ! -f wp-config.php ] && cp ../.lando/lando-wp-config wp-config.php
        || echo "WordPress appears to already be configured, skipping"
        && mkdir -p $LANDO_MOUNT/web/logs
        && [ ! -f .htaccess ] && cp ../.lando/lando.htaccess .htaccess
        || echo ".htaccess found, skipping"
        && echo "\n**** init command finished ****\n"
tooling:
  wp-init:
    description: Initial container setup for this project.
    cmd: true
    service: appserver
  npm:
    service: cli
  node:
    service: cli
  grunt:
    service: cli
  bower:
    service: cli
```

**Comment by Deyter** [comment]
Sorry. I forgot write adminer config which works with cycle redirect.
```yaml
services:
    adminer:
      type: compose
      services:
        image: dehy/adminer
        command: /bin/s6-svscan /etc/services.d
      portforward: true
proxy:
    adminer:
      - adminer.projectname.lndo.site
```
