### ISSUE TITLE
postgres issues.. again again again.

### ISSUE THREAD

**Issue by thursdaybw** [lando/lando#1811]
**Tell us about your setup**

What is your lando version and operating system?
```
Linux catau-syd-desktop0315 4.15.0-64-generic
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
```

Lando version:
```
lando version
v3.0.0-rc.21
```

**Tell us about your `.lando.yml`**

```
name: catauweb
recipe: drupal8

config:
  php: 7.2
  webroot: web
  database: postgres:10.6.0
  xdebug: true

services:
  database:
    creds:
      database: catau_web_drupal_stage
  node:
    type: node
    # see https://github.com/StryKaizer/lando/blob/72f119318bc40a4dc5be04e40ff1c0357b9f3748/docs/guides/frontend.md
    overrides:
      environment:
        # This must match on of the ports specified below.
        # This envvar is accessed in webpack to set the browserSync port.
        # web/themes/custom/catalyst_radix/webpack.mix.js
        # if you run more than one lando with browser sync you'll need to change this port.
        browserSyncPort: 3000
      ports:
        - 3000:3000
        - 3001:3001
    build:
      - cd web/themes/custom/catalyst_radix/ && npm install
    globals:
      gulp-cli: latest

tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
  watch:
    description: Runs npm watch.. builds sass and runs browsersync. point your browser at http://localhost:3000
    service: node
    cmd: cd /app/web/themes/custom/catalyst_radix/ && npm run watch
  theme-dev:
    service: node
    description: Converts the theme files into dev state.. minified and uglified etc.
    cmd:
     - cd /app/web/themes/custom/catalyst_radix/ && npm run dev
  drupal-dev:
    service: appserver
    description: Sets drupal's dev settings, aggregation, caching and theme loading/debuggin.
    cmd:
     - chmod ug+rw /app/web/sites/default /app/web/sites/default/services.yml
     - drupal site:mode dev
  theme-prod:
    description: Converts the theme files into production state. Uglifies and minifies. Do this before pushing to master.
    service: node
    cmd:
      - cd /app/web/themes/custom/catalyst_radix/ && npm run production
  drupal-prod:
    description: Sets drupal's prod settings, aggregation, caching and theme loading/debugging. Run before committing (pushing) to master
    service: appserver
    cmd:
     - chmod ug+rw /app/web/sites/default web/sites/default/services.yml
     - drupal site:mode prod
```

**Tell us about the command you were running**
`lando start`

I have also run

```
lando destroy
rm -rf ~/.lando
docker stop `docker ps -qa`
docker rm `docker ps -qa`
docker rmi -f `docker images -qa `
docker volume rm $(docker volume ls -qf)
docker network rm `docker network ls -q`
```

```
$ lando start
Let's get this party started! Starting app..
Creating network "landocasetupkenobi38ahsoka65fb8d6a26bf933ae1b45566343f774fe41790af_default" with the default driver
Pulling ca (devwithlando/util:stable)...
stable: Pulling from devwithlando/util
8ac9f5ca4429: Pull complete
725c55c4c2b4: Pull complete
Creating landocasetupkenobi38ahsoka65fb8d6a26bf933ae1b45566343f774fe41790af_ca_1 ... done
Looks like you do not have a Lando CA for lndo.site yet! Let's set one up!
Trying to setup root CA with...
LANDO_CA_CERT: /lando/certs/lndo.site.pem
LANDO_CA_KEY: /lando/certs/lndo.site.key
/lando/certs/lndo.site.pem not found... generating one
Generating RSA private key, 2048 bit long modulus
........+++
.................+++
e is 65537 (0x10001)
/lando/certs/lndo.site.pem not found... generating one
CA generated at /lando/certs/lndo.site.pem
Stopping landocasetupkenobi38ahsoka65fb8d6a26bf933ae1b45566343f774fe41790af_ca_1 ... done
Going to remove landocasetupkenobi38ahsoka65fb8d6a26bf933ae1b45566343f774fe41790af_ca_1
Removing landocasetupkenobi38ahsoka65fb8d6a26bf933ae1b45566343f774fe41790af_ca_1 ... done
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Pulling proxy (traefik:1.6.3-alpine)...
1.6.3-alpine: Pulling from library/traefik
605ce1bd3f31: Pull complete
9e3eb27e4ab8: Pull complete
c3e998f85b4a: Pull complete
0908932c917b: Pull complete
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "catauweb_default" with the default driver
Creating volume "catauweb_data_appserver" with default driver
Creating volume "catauweb_home_appserver" with default driver
Creating volume "catauweb_data_database" with default driver
Creating volume "catauweb_home_database" with default driver
Creating volume "catauweb_data_node" with default driver
Creating volume "catauweb_home_node" with default driver
Pulling node (node:10)...
10: Pulling from library/node
092586df9206: Pull complete
ef599477fae0: Pull complete
4530c6472b5d: Pull complete
d34d61487075: Pull complete
87fc2710b63f: Pull complete
e83c771c5387: Pull complete
7e2d41c53938: Pull complete
a51441770e67: Pull complete
e9542e67f971: Pull complete
Creating catauweb_node_1 ... done
Stopping catauweb_node_1 ... done
Pulling appserver (devwithlando/php:7.2-apache-2)...
7.2-apache-2: Pulling from devwithlando/php
8f91359f1fff: Pull complete
bf2faaedf741: Pull complete
24cd1299a53e: Pull complete
17091cc665e4: Pull complete
ac9365919f9b: Pull complete
4f1b34e209ee: Pull complete
832757fa04a4: Pull complete
6872b25b9fab: Pull complete
f54b85668b74: Pull complete
da8b7d356bcd: Pull complete
66af909c41ea: Pull complete
b1b423bb6eee: Pull complete
cb5858fd8d0c: Pull complete
bc2466f7d00f: Pull complete
Creating catauweb_appserver_1 ... done
Stopping catauweb_appserver_1 ... done
Starting catauweb_appserver_1 ... done
Stopping catauweb_appserver_1 ... done
Starting catauweb_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599    0   599    0     0    639      0 --:--:-- --:--:-- --:--:--   638
100 4673k  100 4673k    0     0  1042k      0  0:00:04  0:00:04 --:--:-- 1857k
Drush Commandline Tool 9.5.2
Stopping catauweb_appserver_1 ... done
Starting catauweb_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  811k  100  811k    0     0   312k      0  0:00:02  0:00:02 --:--:--  312k
Stopping catauweb_appserver_1 ... done
Starting catauweb_node_1 ... done
/var/www/.npm-global/bin/gulp -> /var/www/.npm-global/lib/node_modules/gulp-cli/bin/gulp.js
+ gulp-cli@2.2.0
added 235 packages from 156 contributors in 18.999s
Stopping catauweb_node_1 ... done
Starting catauweb_node_1 ... done

> catalyst_radix@ postinstall /app/web/themes/custom/catalyst_radix
> find node_modules/ -name '*.info' -type f -delete

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 19607 packages in 6.146s
found 424 vulnerabilities (1 low, 2 moderate, 421 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Stopping catauweb_node_1 ... done
Pulling database (bitnami/postgresql:10.6.0)...
10.6.0: Pulling from bitnami/postgresql
6fcef73cb140: Pull complete
3678a27e6317: Pull complete
3f2c1028abf7: Pull complete
62e904dc5deb: Pull complete
9711dda369fc: Pull complete
538fb169a8e2: Pull complete
741e57bee557: Pull complete
91e8cbd4c71d: Pull complete
219a783a5540: Pull complete
4ac57581c495: Pull complete
31c5c0426d54: Pull complete
a13ac5a579e8: Pull complete
5a99fd8d9235: Pull complete
2273806cd663: Pull complete
Creating catauweb_database_1  ... done
Starting catauweb_appserver_1 ... done
Starting catauweb_node_1      ... done
Waiting until database service is ready...
Waiting until appserver service is ready...
Waiting until node service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
warn: Service database is unhealthy
warn: Run "lando logs -s database"
Starting catauweb_database_1 ... done
Stopping catauweb_database_1 ... done

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME            catauweb                                         
 LOCATION        /home/bevan/workspace/catalyst-australia-website 
 SERVICES        appserver, database, node                        
 APPSERVER URLS  https://localhost:32787                          
                 http://localhost:32788                           
                 http://catauweb.lndo.site                        
                 https://catauweb.lndo.site
```

And then restarted my workstation.

**Tell us about the error you got**
```
$ lando logs -s database
Attaching to catauweb_database_1
database_1   | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
database_1   | mkdir: cannot create directory ‘/etc/ssh’: Permission denied
database_1   | Running command /entrypoint.sh /run.sh
database_1   | Running with exec!
database_1   | 
database_1   | Welcome to the Bitnami postgresql container
database_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
database_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
database_1   | 
database_1   | nami    ERROR com.bitnami.postgresql is not fully installed. You cannot execute commands
database_1   | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
database_1   | mkdir: cannot create directory ‘/etc/ssh’: Permission denied
database_1   | Running command /entrypoint.sh /run.sh
database_1   | Running with exec!
database_1   | 
database_1   | Welcome to the Bitnami postgresql container
database_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
database_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
database_1   |
```
**Tell us generally about your bug**

Postgres no go

**Tell us more**

This is about the 10th time postgres has fallen over on one or all of my lando sites.
I've spent more time debugging postgres issues with lando than any other task.

I'd happily move to mysql but my organisations policies dictate postgres.. and postgres support is a must for me to continue using lando.

**Comment by cleverhoods** [comment]
I have the same issue on the same OS

**Comment by cleverhoods** [comment]
I followed the suggestion from [#1612](https://github.com/lando/lando/issues/1612#issuecomment-491876894) it worked.

`  database:
    type: postgres:custom
    overrides:
      image: bitnami/postgresql:10.7.0-r68`

**Comment by thursdaybw** [comment]
I'm using
```
  postgres:
    type: postgres:custom
    overrides:
      image: bitnami/postgresql:9.6.12-r68
```

I need postgres 9 because that's what's in our production env.

**Comment by thursdaybw** [comment]
I guess I'll have to check the project above. I switched that to mysql because I could and it got me going again.
I have another project locked in to postgres, using the exact code referenced above:
```
services:
  database:
    type: postgres:custom
    overrides:
      image: bitnami/postgres:9.6.12-r68
```
and that gives the exact same issue described above.

**Comment by thursdaybw** [comment]
Logs:
```
$ lando logs -s database
Attaching to ebscockn_database_1
database_1   | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
database_1   | mkdir: cannot create directory ‘/etc/ssh’: Permission denied
database_1   | Running command /entrypoint.sh /run.sh
database_1   | Running with exec!
database_1   | 
database_1   | Welcome to the Bitnami postgresql container
database_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
database_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
database_1   | 
database_1   | postgres: could not access directory "/bitnami/postgresql/data": No such file or directory
database_1   | Run initdb or pg_basebackup to initialize a PostgreSQL data directory.
database_1   | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
database_1   | mkdir: cannot create directory ‘/etc/ssh’: Permission denied
database_1   | Running command /entrypoint.sh /run.sh
database_1   | Running with exec!
database_1   | 
database_1   | Welcome to the Bitnami postgresql container
database_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
database_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
database_1   | 
database_1   | postgres: could not access directory "/bitnami/postgresql/data": No such file or directory
database_1   | Run initdb or pg_basebackup to initialize a PostgreSQL data directory.
```
.lando.yml
```
name: myproject
recipe: drupal7
config:
  webroot: .
  xdebug: true
  drush: ^7
services:
  appserver:
    volumes:
      - ./www-home:/var/www
    build_as_root:
      - apt-get update -y && apt-get install -y vim
  database:
    type: postgres:custom
    overrides:
      image: bitnami/postgresql:9.6.12-r68
  node:
    type: node
    # see https://github.com/StryKaizer/lando/blob/72f119318bc40a4dc5be04e40ff1c0357b9f3748/docs/guides/frontend.md
    overrides:
      environment:
        # This must match on of the ports specified below.
        # This envvar is accessed in webpack to set the browserSync port.
        # web/themes/custom/catalyst_radix/webpack.mix.js
        # if you run more than one lando with browser sync you'll need to change this port.
        browserSyncPort: 3000
      #ports:
        #- 3000:3000
        #- 3001:3001
    build:
      - npm install
    globals:
      gulp-cli: latest

tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
  watch:
    description: Runs npm watch.. builds sass and runs browsersync. point your browser at http://localhost:3000
    service: node
    cmd: npm run watch
```
:man_shrugging: :man_shrugging: :man_shrugging: I'm at a loss of what to do about postgres with lando.

**Comment by thursdaybw** [comment]
Well.. I've gone back to attempt this on the other project to due the due diligence.
Maybe I"m making some silly mistakes. here's my lando config from that:
```
name: myotherpoject
recipe: drupal8

config:
  php: 7.2
  webroot: web
  xdebug: true

services:
  database:
    type: postgres:custom
    overrides:
      image: bitnami/postgres:9.6.12-r68
```

And after a `lando destroy; lando rebuild -y` this happens:

```
 lando rebuild
? Are you sure you want to rebuild? Yes
Rising anew like a fire phoenix from the ashes! Rebuilding app...
No stopped containers
Pulling database ... error
Pulling node     ... done

ERROR: for database  pull access denied for bitnami/postgres, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: pull access denied for bitnami/postgres, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Pulling database ... error
Pulling node     ... done
```

**Comment by thursdaybw** [comment]
Meh.. I've made that same mistake before.. copy pasting the settings.. and the comment has postgres: intead of postgresql.

So that's resolved the access denied issue..

Even so.. Same problem exists on both projects:
Postgres settings (not pasing entire .lano.yml or logs as I've done this above.

```
  database:
    type: postgres:custom
    overrides:
      image: bitnami/postgresql:9.6.12-r68
```

To be fair, this would be far less frustrating if I didn't like lando so much.

**Comment by thursdaybw** [comment]
Righto.. having reverted back to previously working config.. the fix in https://github.com/lando/lando/issues/1612#issuecomment-491909162 works..

I'm adding that changing, and very interested to see how long before I start these projects and postgres borks again.

**Comment by thursdaybw** [comment]
specifically..  `bitnami/postgresql:9.6.12-r68` failed. 
Currently the combination of 
```
config:
  database: postgres
services:
  database:
    type: postgres:custom
    overrides:
      image: bitnami/postgresql:9.6
```
Is the magic combination.

**Comment by JorisVanEijden** [comment]
Still an issue with Lando v3.0.0-rc.23
Workaround in https://github.com/lando/lando/issues/1811#issuecomment-544312602 still works.

**Comment by thursdaybw** [comment]
As of today, the above workaround no longer works for me for postgres 9.6,

The database container failed to start the log showing lando_entrypoint.sh could find entrypoint.sh

the only way I know to know the correct entry point is to inpect a running container and look at the Path value, and it's associated Args value.

```
 database: 
    type: postgres:custom 
    overrides: 
      image: bitnami/postgresql:9.6 
      command: "/opt/bitnami/scripts/postgresql/entrypoint.sh /opt/bitnami/scripts/postgresql/run.sh"
```
