### ISSUE TITLE
Different node user and group behavior between various host platforms

### ISSUE THREAD

**Issue by RichardDavies** [lando/lando#1813]
Our development team uses Lando on a mix of Windows, Mac, and Linux machines. We've encountered some interesting differences in our Node containers across the various platforms, mostly related to the handling of users and groups.

**Tell us about your setup**

Multiple installations of v3.0.0-rc.14 through rc.21 on Windows 10 Professional, Mac OS X, and Ubuntu 18.04 Desktop.

**Tell us about your `.lando.yml`**

Here is a simplified version, reduced to the relevant parts:

```yml
name: portlandor
recipe: pantheon
config:
  framework: drupal8
  site: portlandor
  id: 5c6715db-abac-4633-ada8-1c9efe354629
  index: false
  edge: false
  cache: false
services:
  appserver:
    build_as_root:
      - /bin/sh -c "cp /app/cop_ca_*.crt /usr/local/share/ca-certificates/"
      - update-ca-certificates
    run_as_root:
      - /bin/sh -c "if [ ! -d /var/www/.terminus/plugins/terminus-secrets-plugin ]; then { mkdir -p /var/www/.terminus/plugins; composer create-project -d /var/www/.terminus/plugins pantheon-systems/terminus-secrets-plugin:~1; chown -R www-data:www-data /var/www/.terminus; } fi"
    xdebug: false
    config:
      conf: xdebug.ini
  node:
    type: node
    overrides:
      environment:
        # LANDO_WEBROOT_USER: www-data
        # LANDO_WEBROOT_GROUP: node
        NODE_EXTRA_CA_CERTS: /app/cop_ca.pem
    run_as_root:
      - /bin/sh -c "adduser www-data node"
      - /bin/sh -c "adduser node dialout"
      - /bin/sh -c "chmod -R 775 /var/www"
    run:
      - echo "Updating npm..."
      - npm install -g npm
      - echo "Installing Node.js dependencies..."
      - cd /app/web/themes/custom/cloudy && npm install

events:
  post-start:
    - node: echo "Updating npm..."
    - node: npm install -g npm
    - node: echo "Building theme asset files..."
    - node: cd /app/web/themes/custom/cloudy && npm run build:dev
tooling:
  drush:
    description: Run drush commands
    service: appserver
    cmd: drush --root=/app/web
  npm:
    description: Run npm commands
    service: node
    cmd: cd /app/web/themes/custom/cloudy && npm
  node:
    description: Run node commands
    service: node
  refresh:
    description: Refresh branch by installing Composer dependencies and importing Drupal config, etc. Run after every merge from master.
    cmd:
      - appserver: echo "Installing Composer dependencies..."
      - appserver: composer install -d /app
      - appserver: echo "Clearing cache..."
      - appserver: drush cr -y
      - appserver: echo "Run database updates..."
      - appserver: drush updb -y
      - appserver: echo "Importing Drupal config..."
      - appserver: drush cim -y
      - appserver: echo "Running cron..."
      - appserver: drush core:cron -y
      - appserver: echo "Clearing cache..."
      - appserver: drush cr -y
      - node: echo "Building theme asset files..."
      - node: cd /app/web/themes/custom/cloudy && npm run build:dev
```

**Tell us generally about your bug**

There are differences in a Node container when used on multiple host OSes. These differences are mostly related to the handling of user and group ownership of files and inconsistent effects of the LANDO_WEBROOT_USER environment variable.

**Tell us more**

Run `lando ssh -s node -c id`. On Windows and Linux the user's default group is node (1000). On Mac, it's dialout (20).

Run `lando ssh -s node -c "ls -la /var/www"`. On Windows and Linux the directory and files are owned by the node user and node group. On Mac they're owned by node user and dialout group.

Change the environment variable LANDO_WEBROOT_USER to www-data with the following node service definition:

```yaml
 node:
    type: node
    overrides:
      environment:
        LANDO_WEBROOT_USER: www-data
```

After rebuilding the service, this change has the following effects:

1. On Windows and Linux, the default user is changed from node to www-data. i.e. `lando ssh -s node` now logs in the www-data user. On Mac the default user remains node.
2. On Windows and Linux, the www-data user becomes an "alias" for the node user. `cat /etc/passwd` shows that both users are assigned the same user ID 1000. On Mac, the www-data user and node user remain separate users with distinct UIDs.
3. On Windows and Linux, files in /var/www are now owned by user www-root and group node. On Mac, the files are owned by user www-data and group dialout.

These differences may seem trivial but they have caused us significant grief because we have a tooling command (`lando refresh`) that executes a series of commands, some on our appserver container and others on our node container. These commands are all executed as the www-data user because Lando doesn't provide a way to change the user for the commands executed on the node service.

We also have other tooling commands (`lando npm`) that only execute on the node service and therefore run as the default node user. As a result, the commands executed as www-data were unable to access the files owned by the node user and group and caused "permission denied, mkdir '/var/www/.npm-global'" permission errors when running `npm install -g npm`. We've been able to work around this issue by adding the www-data user to the node group and giving the group write access to the files in /var/www. 

We had also tried to set `LANDO_WEBROOT_USER=www-data` in order to make all tooling  commands run as the www-data user but that didn't work on a Mac due to the differences outlined above.

We wanted to report our findings in case it helps anyone else and also to make you aware of these differences because ideally, everything should be identical and behave the same inside the containers, regardless of what host OS they're using.
