### ISSUE TITLE
Introduce `include` functionality in .lando.yml

### ISSUE THREAD

**Issue by tormi** [lando/lando#1830]
I'm proposing to introduce `include` key in `.lando.yml` so that one can easily include a sub-recipe for some functionality. Let me give an example:

`.lando.yml`:

```
name: project
recipe: drupal8

include:
  - .lando.elasticsearch.yml
```

`.lando.elasticsearch.yml`:

```
services:
  elasticsearch:
    type: compose
    services:
      image: blacktop/elasticsearch:7
      command: /elastic-entrypoint.sh elasticsearch
      ports: 
        - "9200:9200"
      volumes:
        - ./.lando/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    build_as_root:
      - apk --no-cache add openjdk11
    run_as_root:
      - elasticsearch-plugin install analysis-icu

proxy:
  elasticsearch:
    - elasticsearch-project.lndo.site:9200
```

Basically, I’d like to use `postLandoFiles` functionality so that I can override `.lando.yml` using `.lando.yml` itself, not `~/.lando/config.yml` (which is not part of the project).
