### ISSUE TITLE
Ability to pipe commands in tooling

### ISSUE THREAD

**Issue by neclimdul** [lando/lando#1832]
These issues are closed but it is still not possible to use pipes in tooling or other commands 
#951 #967

Like this redirection
```
name: landobrokenpipe
recipe: custom
config:
  webroot: .
services:
  test:
    type: node:8
tooling:
  compile:
    service: test
    cmd: 
       - echo "Do some compile steps..."
       - sed ERROR compile.log > errors.txt
```

or this pipe I'd like to use to test pecl yaml libraries in d8.
```
name: d8
recipe: drupal8

services:
  appserver:
    run_as_root:
      - "apt-get update"
      - "apt-get install -y libyaml-dev"
      - "printf \"\n\" | pecl install yaml-2.0.4"
```
