### ISSUE TITLE
Odd Behavior with Drupal 8 / Apache (needs repro)

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#1838]
Version:

rc20 and rc22 on Pop OS / Ubuntu*

Example Landofile

```yml
name: client

excludes:
  - drush
  - scripts
  - vendor
  - docroot/core
  - docroot/modules/contrib
  - docroot/profiles/contrib
  - docroot/sites/default/files
  - docroot/themes/contrib

recipe: drupal8
config:
  via: apache
  webroot: docroot
  php: 7.2
  database: mysql
  xdebug: false

env_file:
  - .env

proxy:
  mannequin:
    - client-styleguide.lndo.site
  node:
    - client-bs.lndo.site:3000
services:
  memcached:
    type: memcached
  mannequin:
    type: compose
    services:
      image: devwithlando/php:7.3-fpm-2
      command: docker-php-entrypoint /app/vendor/bin/mannequin start -c /app/.mannequin.php 0.0.0.0:80
  node:
    type: node
    build:
      - "cd /app && yarn install"
      - "cd /app && yarn dev"
    command: cd /app && yarn watch
    port: 3000
  appserver:
    # Installing yarn in appserver so BLT can compile assets on deploy :(
    build_as_root:
      - curl -sL "https://deb.nodesource.com/setup_10.x" | bash
      - apt install -y nodejs
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update && apt-get install --no-install-recommends yarn
    build:
      - "mkdir -p /var/www/.platformsh/bin"
      - "curl -fsSL -o /var/www/.platformsh/bin/platform https://github.com/platformsh/platformsh-cli/releases/download/v3.40.2/platform.phar"
      - "chmod ug+x /var/www/.platformsh/bin/platform"
      - "cd /app && composer install -n"
    overrides:
      environment:
        PLATFORMSH_CLI_TOKEN: "$PLATFORMSH_CLI_TOKEN"
        PLATFORMSH_PROJECT_ID: "REDACTED"

tooling:
  deploy:
    service: appserver
    cmd: /app/vendor/bin/blt artifact:deploy
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
  lint:
    service: appserver
    cmd:
      - /app/vendor/bin/blt validate:all
  fix:
    service: appserver
    cmd: /app/vendor/bin/blt source:fix:php-standards
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd: /var/www/.platformsh/bin/platform
  phplint:
    service: appserver
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  phpstan:
    service: appserver
    cmd: /app/vendor/bin/phpstan
  yarn:
    service: node
  pull-acquia:
    service: appserver
    description: Pull database and files from an Acquia Cloud Instance
    cmd: /app/scripts/lando/pull-acquia.sh
    level: app
    options:
      environment:
        passthrough: true
        alias:
          - e
        describe: Which environment to pull
        interactive:
          type: list
          message: Which environment do you want to pull?
          default: dev
          choices:
            - dev
            - test
            - live
          weight: 600
  pull-platform:
    service: appserver
    description: Pull the prod instance
    cmd:
      - appserver: /var/www/.platformsh/bin/platform auth:info || /var/www/.platformsh/bin/platform auth:login
      - appserver: /var/www/.platformsh/bin/platform db:dump --gzip --project=REDACTED --file=/app/dump.sql.gz --environment=master
      - database: /app/scripts/lando/import-db.sh
      - appserver: rm -f /app/dump.sql.gz
      - appserver: mkdir -p /app/docroot/sites/default/files
      - appserver: /var/www/.platformsh/bin/platform mount:download --project=REDACTED --mount docroot/sites/default/files --target /app/docroot/sites/default/files --environment master
  test:
    service: appserver
    description: Run Tests Locally
    cmd:
      - /app/vendor/bin/blt validate:all
      - /app/vendor/bin/blt tests:phpunit:run
      - /app/vendor/bin/blt tests:deprecated:modules
      - /app/vendor/bin/blt tests:deprecated:themes

```
On start, Lando just hangs waiting for services to be ready. Swapping to `via: nginx` resolves the issue so this appears to be apache/7.2 related?
