### ISSUE TITLE
Initialize database with custom name instead default drupal8

### ISSUE THREAD

**Issue by faiwiz** [lando/lando#1845]
I have set following configs in my .lando.yml file and it's still creating default database , username, password `drupal8`.
services:
  db_service:
    type: mysql
    creds:
      user: db_username_instead_drupal8
      password: db_password_instead_drupal8
      database: my_lando_db_name_instead_drupal8

also it showing same default info drupal8  in `lando.info` command

question is how to change databasename, username, password of mysql from default drupal8 to mysql custom provided name.

**Comment by adam-delaney** [comment]
I'm interested knowing how to do this as well.

**Comment by nirodaonline** [comment]
+1

**Comment by CarolinaLonghini** [comment]
Just in case someone lands here. This worked for me under a drupal8 recipe:
```
[...]
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - maindb
  customDb:
    type: mysql
    portforward: true
    creds:
      user: customDb
      password: customDb
      database: customDb
[...]
```
