### ISSUE TITLE
SOLVED: Lando on Mac: Authentication required on composer install

### ISSUE THREAD

**Issue by AnnoyedDeveloper** [lando/lando#1852]
Hello there

I have tried to lift a Drupal Project to run on PHP 7.2 and for that I wanted to install the newest packages using the `composer install` command.

It works fine until I come to a DEV-Version of a module and then suddenly it asks for authentication for git.drupalcode.org

```bash
  - Installing drupal/drupalmonitor (dev-1.x 706d31a):     Authentication required (git.drupalcode.org):
      Username: martinpe
      Password:
Cloning 706d31a7ea
    Authentication required (git.drupalcode.org):
      Username: martinpe
      Password:
```

Upon more detailed inspection I have found out, that composer tries to install the Git project using `git clone` and the error is the following:

```
[RuntimeException]
  Failed to execute git clone --no-checkout 'https://martinpe:***@git.drupalcode.org/project/drupalmonitor.git' 'web/modules/contrib/drupalmonitor' && cd 'web/modules/contrib/drupalmonitor' && git remote add composer 'https://martinpe:***@git.drupalcode.org/project/drupalmonitor.git' && gi
  t fetch composer && git remote set-url origin 'https://git.drupalcode.org/project/drupalmonitor.git' && git remote set-url composer 'https://git.drupalcode.org/project/drupalmonitor.git'

  Cloning into 'web/modules/contrib/drupalmonitor'...
  fatal:***@git.drupalcode.org/project/drupalmonitor.git/': Problem with the SSL CA cert (path? access rights?)
```

My coworker uses a linux machine and his lando runs smoothly and installs all packages without hassle, but not with my Lando on Mac. 

I am using `v3.0.0-rc.22`. 

and here is my `.lando.yml`

```yml
# Change this name to something that makes sense for your project
name: example.ch

# Use the recipe appropriate for your application.
recipe: drupal8

# Configure the D8 recipe to match up closer to a vanilla platform.sh stack
config:

  # Match PHP version on the production hosting.
  php: '7.2'

  # Optionally activate xdebug
  #
  # If you are having trouble getting xdebug to work please see:
  # https://docs.devwithlando.io/services/php.html#using-xdebug
  xdebug: false

  # Set the webroot to match your .platform.app.yaml.
  webroot: httpdocs

  config:
    #    # Tell Lando to use additional PHP settings.
    #    # The location of this file is arbitrary.
    #    # We placed it inside .vscode/ folder simply because we find it convenient.
    php: .lando.php.ini

# Services
# More info on https://docs.lando.dev/config/services.html
services:
  appserver:
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=example.ch.trip"
    run:
      - cd /app && bash .lando/scripts/project/init.sh

  database:
    # Static port in order to facilitate access with DB GUI tools such as MySQL Workbench or Sequel Pro
    portforward: 9999
  pma:
    type: phpmyadmin
    hosts:
      - database

```

What seems to the problem here?
