### ISSUE TITLE
Support request: How to create a file before the container is ran?

### ISSUE THREAD

**Issue by martin-klima** [lando/lando#1855]
I need to create a file on the host file system automatically before the container is built or started.
Time sequence:
1) `lando start` or `lando rebuild` command
2) command `touch some_file.ext` or some similar is processed on the host
3) lando continues with spinning up the containers...

Any idea? Thank you for help.

## Question background:
I'm mapping the appserver bash history file to some file on the host to preserve bash history (in my example `.appserver_bash_history.txt`). It works. But the file on the host MUST already exist before the container is trying to map the volumes. If the file doesn't exist, a directory with the same name is created. That's why I need to create the history file on the host before the container is built or started.

```yaml
services:
  appserver:
    overrides:
      environment:
        PROMPT_COMMAND: "history -a"
      volumes:
        - ${PWD}/.appserver_bash_history.txt:/var/www/.bash_history
```

**Comment by uberhacker** [comment]
@martin-klima: You could use events.  See https://docs.lando.dev/config/events.html.  Example:
```
events:
  pre-start:
    - appserver: 'touch some_file.ext'
```
This will create a file on your host system in the `/app` directory (aka your project root directory).

**Comment by martin-klima** [comment]
@uberhacker Thank you for your response. I tried that way with no success yesterday.

The appserver container always tries to map the volume before the file is created by the command in the events section.

**Comment by uberhacker** [comment]
Ah, I see your dilemma now.  Apparently, you need to build a new image with that file "touched" in your Dockerfile with `RUN touch .appserver_bash_history.txt`.

**Comment by martin-klima** [comment]
I solved my problem. I set the history file into a custom directory and map volume to this directory. It works perfectly and the custom directory cannot be created manually.

```yaml
services:
  appserver:
    overrides:
      environment:
        PROMPT_COMMAND: "history -a"
        HISTFILE: /var/www/.history/hist.txt
      volumes:
        - ${PWD}/.history:/var/www/.history   
```
