### ISSUE TITLE
Quote passthrough arguments

### ISSUE THREAD

**Issue by barraponto** [lando/lando#1863]
Lando interactive options do not shell escape (quote) the arguments. If the user inputs a value with spaces, it breaks the passthrough argument syntax. Tested on Lando 3 RC22 (on Arch Linux but it's a container issue ).

Here's a sample tooling with an interactive option:

```yml
tooling:
  wp-install:
    service: appserver
    description: Runs 5-minute install in seconds (sets user/pass to admin/admin)
    cmd: wp core install --url=http://$LANDO_APP_NAME.$LANDO_DOMAIN --skip-email
    level: app
    options:
      admin_user:
        describe: The default admin user
        passthrough: true
        default: admin
      admin_password:
        describe: The default admin password
        passthrough: true
        default: admin
      admin_email:
        describe: The default admin email
        passthrough: true
        default: admin@lndo.site
      url:
        describe: The local site url
        passthrough: true
        default: http://localhost:1337
      title:
        describe: The Wordpress site title
        passthrough: true
        interactive:
          type: input
          message: What is the Wordpress site title going to be?
```

And here's how to reproduce the issue:

```
1. lando init with wordpress recipe.
2. have the tooling above in .lando.yml
3. use wp core config to create wp-config.php 
4. lando --clear to ensure tooling is loaded
4. use the tooling to install: lando wp-install
5. use the interactive option to set a title with spaces in it like MY WORDPRESS
```

I believe this can be fixed in the tooling plugin, by shell escaping [during `handlePassthruOpts`](https://github.com/lando/lando/blob/master/plugins/lando-tooling/lib/utils.js#L97).
