### ISSUE TITLE
Node commands as part of build step run as wrong user.

### ISSUE THREAD

**Issue by mishac** [lando/lando#1877]
**Tell us about your setup**

What is your lando version and operating system? v3.0.0-rc.23 on Ubuntu 19.10

**Tell us about your `.lando.yml`**

```yml
name: mishac
recipe: drupal8
config:
  php: '7.2'
  webroot: web
excludes:
  - vendor
  - web
  - '!web/modules/custom'
  - '!web/sites'
  - '!web/themes/custom'
  - web/themes/custom/mishac/node_modules
services:
  pma:
    type: phpmyadmin
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward:  true
  node:
    type: node
    globals:
      yarn: latest
tooling:
  drush:
    service: appserver
    cmd:
      - "drush --root=/app/web --uri=https://mishac.lndo.site"
  yarn:
    service: node
    cmd:
      - "yarn --cwd /app/web/themes/custom/mishac"
  build:
    cmd:
      - node: "whoami"
      - node: "id"
  test:
    description: Run ALL THE TESTS
    cmd:
      - appserver: composer test
proxy:
  pma:
    - pma.mishac.lndo.site
  mailhog:
    - mailhog.mishac.lndo.site

```

**Tell us about the error you got**

Lando tooling commands that run as part of `build` show the wrong user:

```bash
$ lando build
www-data
uid=33(www-data) gid=33(www-data) groups=33(www-data)
$ lando ssh -s node
node@2aba07e7a79a:/app/web $ whoami
node
node@2aba07e7a79a:/app/web $ id
uid=1000(node) gid=1000(node) groups=1000(node)
node@2aba07e7a79a:/app/web $ 
```

**Tell us more**

This is affecting yarn commands that I want to run as part of the build tool...since the commands run as uid 33, I get permission denied errors.

Running `lando yarn` and `lando ssh` work fine, running as 'me' (uid 1000).

Services in the appserver container don't seem to be having this same issue, just the node one.

**Comment by mishac** [comment]
Same thing happens with the same .lando.yml file on another machine running Lando 3.0.0-rc.22 on macOS Catalina

Also tried node:8 and node:10 containers just in case it was a bug with the latest container version.

**Comment by philoSurfer** [comment]
Bump... having the same problem.  on rc.22 and rc.23 ( I have not tried others ) 

When trying to install any yarn or npm install after the container is built we are getting permission write errors to the cache directories. 

`npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /var/www/.npm
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 33:33 "/var/www/.npm"
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /var/www/.npm
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 33:33 "/var/www/.npm"
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /var/www/.npm
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 33:33 "/var/www/.npm"
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /var/www/.npm
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 33:33 "/var/www/.npm"
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /var/www/.npm
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 33:33 "/var/www/.npm"
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /var/www/.npm
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 33:33 "/var/www/.npm"
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /var/www/.npm
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 33:33 "/var/www/.npm"
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /var/www/.npm
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 33:33 "/var/www/.npm"
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /var/www/.npm
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 33:33 "/var/www/.npm"
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /var/www/.npm
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 33:33 "/var/www/.npm"`

**Comment by vaish** [comment]
I run into the same issue. Using Lando v3.0.0-rc.23 on KDE Neon (Ubuntu 18.04). And just to add that this issue occurs only wen multi-service tooling is used. 

This works fine. Command is run as user `node`.
```yaml
tooling:
  build:
    service: node
    cmd: whoami
```

However, the following fails. Command is run as user `www-data`.
```yaml
tooling:
  build:
    cmd:
      - node: whoami
```

**Comment by SebastienVanRintel** [comment]
You coud add the user property to the tooling cmd:

`
tooling:
  build:
    cmd:
      - node: whoami
    user: root
`

**Comment by vaish** [comment]
Thanks for the suggestion @SebastienVanRintel but I don't think it solves my problem. Main reason, and the only one I can think of right now, why would I want to use multi-service tooling is to be able to run multiple commands each one within different container. For example:

```
tooling:
  build:
    cmd:
      - appserver: composer install
      - node: npm install
```

Is there a way to specify correct user property for each of the above commands? It has to be correct user that is normally used to run commands for the given service. Using root for all commands wouldn't work because it would mess up file permissions for commands defined elsewhere that run as a regular user.

**Comment by smutlord** [comment]
Good error report here @mishac. I can replicate with the helpful example in this comment https://github.com/lando/lando/issues/1877#issuecomment-578766970 thanks @vaish.

**Comment by smutlord** [comment]
Interestingly enough it seems like a multicommand event seems to get the correct user.

```yaml
events:
  post-start:
    - node: whoami | grep node
```

The above succeeds
