### ISSUE TITLE
How to compile php extensions from source

### ISSUE THREAD

**Issue by sarath49** [lando/lando#1894]
**Below links define how to install extension using pecl.**
https://docs.lando.dev/config/php.html#adding-or-removing-extensions

Need a documentation example to compile a source package with lando

**Comment by marufmax** [comment]
i did it by using service and a docker command. its good to have this on documentation 
```yaml
services:
  my-service:
    type: php
    build_as_root:
      - apt-get update -y
      - pecl install stats-2.0.3
      - docker-php-ext-enable stats
```
