### ISSUE TITLE
Installing php xsl extension in LAMP

### ISSUE THREAD

**Issue by Clindbergh** [lando/lando#1906]
I'm trying to install the xsl extension within the LAMP package. 
 
My `.lando.yml`:

```
name: solid-invoice
recipe: lamp
config:
  webroot: web
  xdebug: true
#  config:
#    php: .lando/config/php.ini

services:
  appserver:
    build_as_root:
      - apt install libxslt
      - docker-php-ext-install xsl
      - docker-php-ext-enable xsl
      - composer install
```

This runs fine. Once I hit `lando composer install`, I'm still greeted with

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-xsl * is missing from your system. Install or enable PHP's xsl extension.
```

**When I use** 

```
config:
  config:
    php: .lando/config/php.ini
``` 
with `.lando/config/php.ini`:

```
extension=php_xsl.so
```

`lando rebuild -y` results in:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_xsl.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20180731/php_xsl.so (/usr/local/lib/php/extensions/no-debug-non-zts-20180731/php_xsl.so: cannot open shared object file: No such file or director
y), /usr/local/lib/php/extensions/no-debug-non-zts-20180731/php_xsl.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20180731/php_xsl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

What am I missing here?

**Comment by uberhacker** [comment]
@Clindbergh:  This works for me:
```
services:
  appserver:
    build_as_root:
      - apt update && apt install libxslt1-dev -y && docker-php-ext-install xsl
```
```
$ lando php -m | grep xsl
xsl
```

**Comment by smutlord** [comment]
https://docs.lando.dev/guides/installing-php-extensions-on-lando.html

**Comment by sovetski** [comment]
I followed the docs from: https://docs.lando.dev/plugins/php/guides/installing-extensions.html

And added this to my `.lando.yml`

```
services:
    myservice:
        type: php
        build_as_root:
            - apt-get update -y
            - apt install libxslt1-dev -y
            - docker-php-ext-install xsl
```

After doing `lando start`, I still get the same error: 

```
 Problem 1
    - lorenzo/pinky is locked to version 1.1.0 and an update of this package was not requested.
    - lorenzo/pinky 1.1.0 requires ext-xsl * -> it is missing from your system. Install or enable PHP's xsl extension.
  Problem 2
    - lorenzo/pinky 1.1.0 requires ext-xsl * -> it is missing from your system. Install or enable PHP's xsl extension.
    - twig/inky-extra v3.8.0 requires lorenzo/pinky ^1.0.5 -> satisfiable by lorenzo/pinky[1.1.0].
    - twig/inky-extra is locked to version v3.8.0 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - 
    - /usr/local/etc/php/conf.d/docker-fpm.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-bz2.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-calendar.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-exif.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-gd.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-gettext.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-imagick.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-imap.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-intl.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-ldap.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-oauth.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pcntl.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-redis.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-soap.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-xhprof.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
    - /usr/local/etc/php/conf.d/xx-php-ext-memcached.ini
    - /usr/local/etc/php/conf.d/xxx-lando-default.ini
    - /usr/local/etc/php/conf.d/zzz-lando-my-custom.ini
```
