### ISSUE TITLE
lando.yml can't see nginx configuration

### ISSUE THREAD

**Issue by kufdaw** [lando/lando#1917]
Hi,

Not sure if this is my fault or the unclear instructions but whatever I put on nginx.conf that's not affecting the page. 

I want to exceed the nginx request timeout cos I have big math calculations and I want to exceed the timeout to like 300000s. However, whenever I use the php.ini and `max_execution_time = 5` - it gets triggered after 5 seconds.

```
504 Gateway Time-out
nginx/1.14.2
```
- this is basically what I want to get rid off - thats nginx fault not php. 

and this 
```
proxy_connect_timeout 3;
proxy_send_timeout 3;
proxy_read_timeout 3;
send_timeout 3;
fastcgi_send_timeout 3;
fastcgi_read_timeout 3;
```

inside the server.conf doesn't work (just want to put 3 seconds to check if everyth is working). 

```
name: envelope
recipe: laravel
config:
  webroot: public
  php: '7.3'
  via: nginx
  database: mysql
  config:
    php: php.ini
    server: server.conf
services:
  phpMyAdmin:
    type: phpmyadmin
  node:
    type: node
tooling:
  yarn:
    service: node
```
