### ISSUE TITLE
env_file config does not result in set env vars

### ISSUE THREAD

**Issue by xaqrox** [lando/lando#1921]
**Tell us about your setup**

What is your lando version and operating system?

v3.0.0-rc.23 on macOS Mojave 10.14.6

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

```yml
name: mysite
recipe: pantheon
config:
  framework: drupal8
  site: mysite
  id: [redacted pantheon id]

services:
  appserver:
    build:
      - composer install
    overrides:
      environment:
        BEHAT_PARAMS: >-
          {"extensions" : {"Behat\\MinkExtension" : {"base_url" :
          "http://nginx/"}, "Drupal\\DrupalExtension" : {"drush" :   {
          "root":  "/app/web" }}}}
  node:
    type: node:10
    globals:
      gulp-cli: "latest"
    run:
      - "cd $LANDO_MOUNT/web/themes/custom/mysite_theme && npm install && npm rebuild node-sass && gulp"

env_file:
  - local.env

tooling:
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat --config=/app/tests/behat-pantheon.yml
  drupal:
    cmd: /app/vendor/bin/drupal --root=/app/web
  gulp:
    service: node
    cmd: gulp
  npm:
    service: node
    cmd: npm
  phplint:
    service: appserver
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit

```

local.env:
```sh
DRUSH_OPTIONS_URI=https://mysite.lndo.site
```

**Tell us about the command you were running**

```
$ lando drush status
 Drupal version   : 8.8.1                             
 Site URI         : http://default                    
 DB driver        : mysql                             
 DB hostname      : database                          
 DB port          : 3306                              
 DB username      : pantheon                          
 DB name          : pantheon                          
 Database         : Connected                         
 Drupal bootstrap : Successful                        
 Default theme    : mysite                          
 Admin theme      : seven                             
 PHP binary       : /usr/local/bin/php                
 PHP config       :                                   
 PHP OS           : Linux                             
 Drush script     : /app/vendor/drush/drush/drush     
 Drush version    : 9.7.1                             
 Drush temp       : /tmp                              
 Drush configs    : /app/vendor/drush/drush/drush.yml 
 Install profile  : standard                          
 Drupal root      : /app/web                          
 Site path        : sites/default                     
 Files, Public    : sites/default/files               
 Files, Private   : sites/default/files/private       
 Files, Temp      : /var/www/tmp                      
```

**Tell us about the error you got**

Site URI should be "https://mysite.lndo.site", is "http://default" instead.

Popping into an interactive php session via `lando php -a` also shows no value for `DRUSH_OPTIONS_URI`

**Tell us generally about your bug**

I'm trying to set the Drush URI option according to this documentation: https://docs.drush.org/en/9.x/using-drush-configuration/

FWIW I've never been able to get the `env_file` config working in other projects either...

**Comment by xaqrox** [comment]
This just needed a rebuild, all good.

**Comment by gitressa** [comment]
Thanks for sharing, I found this issue while looking for info on setting the `uri`. Shortly after I found out it is possible to define it directly in `.lando.yml`:
```
services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "http://mysite.lndo.site"
```
https://docs.lando.dev/config/drupal8.html#default-url-setup
