### ISSUE TITLE
Edge URLs stopped working

### ISSUE THREAD

**Issue by cjyabraham** [lando/lando#1923]
My *.lndo.site Edge URLs have stopped working about a week ago across all my lando instances.  Anytime this would happen in the past I could fix them by running `docker system prune`.  This time it doesn't work.  I tried going back to previous versions of docker but that didn't help either.  Did something change recently to cause this?  How can I get them working again?  This is what I see when I `lando start` with the lines that light up red pointed out:
```
NAME                  lfeventsci                                                         
 LOCATION              /Users/cjyabraham/Sites/lfeventsci                                 
 SERVICES              appserver_nginx, appserver, database, cache, edge, edge_ssl, index 
 APPSERVER_NGINX URLS  https://localhost:32849                                            
                       http://localhost:32850                                             
 EDGE URLS             http://localhost:32847                                             
                       http://lfeventsci.lndo.site                        <-- red                
                       https://lfeventsci.lndo.site                       <-- red                
 EDGE_SSL URLS         https://localhost:32851    
```

Here are my versions and configuration:

lando version v3.0.0-rc.23
docker version 2.1.0.5
macos 10.15.2

lando.yml
```yml
name: lfeventsci
recipe: pantheon
config:
  framework: wordpress
  site: lfeventsci
  id: f74d847c-e689-4631-a91b-24b7f897139b
```

pantheon.yml
```yml
api_version: 1
web_docroot: true
php_version: 7.3
workflows:
  sync_code:
    after:
      - type: webphp
        description: 'Push changes back to GitHub if needed'
        script: private/scripts/quicksilver/quicksilver-pushback/push-back-to-github.php
```

**Comment by cjyabraham** [comment]
Just an FYI that my EDGE URLs started to work again a couple of days ago.  I don't think I upgraded anything so not sure what fixed this.

**Comment by dchaffin** [comment]
Mine have stopped working now as well ... 

```
name: mysitezzz
recipe: pantheon
config:
  framework: drupal8
  webroot: web
  site: mysitezzz
  id: ########-####-####-###-############
proxy:
  edge:
    - mysitezzz.lndo.site
tooling:
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"
      - "--root=/app/web"
```

lando version
v3.0.0-rc.23

docker version
2.1.0.5

Windows 10
