### ISSUE TITLE
Drupal site name is set as the intended site name but wrapped in quotes when running `drush si` from an event or from the `run` build step

### ISSUE THREAD

**Issue by philwolstenholme** [lando/lando#1926]
Hi, I'm using v3.0.0-rc.23 on MacOS High Sierra 10.13.6. I've found Lando very useful, so thank you very much for your work on it.

I have a Drupal 8 environment and am trying to run the `drush si` (site install) command when my Lando instance is created.

Here's my Lando file:

```yml
name: heroheadertest
recipe: drupal8
config:
  webroot: www
services:
  appserver:
    type: php
    overrides:
      environment:
        PROJECT_KEY: 'drupal8'
        DB_USER: 'drupal8'
        DB_PASS: 'drupal8'
        DB_HOST: 'database'
        DB:PORT: '3306'
        DRUSH_OPTIONS_URI: 'https://heroheadertest.lndo.site'
    run:
      - composer global require hirak/prestissimo
      - composer install
      - ln -sf ../../../docker/config/sites/default/settings.local.php www/sites/default/settings.local.php
      - ln -sf ../../docker/config/sites/services.local.yml www/sites/services.local.yml
      - drush si standard --site-name="Example Drupal site" --account-name=root --account-pass=password --verbose -y
```

When my site finishes installing it has the Drupal site name of `"Example Drupal site"`, so the quotes have been passed through as part of the string.

If I do a ` lando ssh -s appserver` and run `drush si standard --site-name="Example Drupal site" --account-name=root --account-pass=password --verbose -y` to bypass Lando, then my site gets the name `Example Drupal site` (no extra quotes this time).

How can I escape/alter my Drush command to avoid the extra quotes reaching Drupal?
