### ISSUE TITLE
lando db-import does not respect drupal db host setting

### ISSUE THREAD

**Issue by markdorison** [lando/lando#1929]
## Summary
I believe `db-import` used to work on multi-sites without specifying `--host` but now it does not.

## Details
I am attempting to import a database into a drupal multisite where I have a database container for each site. I am running `db-import` from within the multisite's site directory but the only way I can get `db-import` to import to the correct host is to manually specify it using the `--host` flag. I did not have to do this previously as I believe it detected the appropriate database configuration settings from the site's settings file where I am specifying `host => alpha`. Was this an intentional change, a bug, or am I thinking about this incorrectly? 

## Steps to Reproduce
```bash
cd web/sites/alpha/
lando db-import alpha-latest.sql.gz
```

## Actual Results
```bash
Preparing to import /app/web/sites/alpha/alpha-latest.sql.gz into drupal8 on **localhost**:3306 as root...
```

## Expected Results
```bash
Preparing to import /app/web/sites/alpha/alpha-latest.sql.gz into database on **alpha**:3306 as root...
```

## Versions
Lando v3.0.0-rc.23
macOS 10.15.2

## .lando.yml

```yml
name: redacted-name
recipe: drupal8

config:
  webroot: web
  php: '7.2'
  drupal: true
  xdebug: false

proxy:
  appserver:
    - "*.lndo.site"

services:
  node:
    type: node:10
    globals:
      yarn: "1.17.3"
  alpha:
    type: mysql:5.7
    portforward: 33061
  bravo:
    type: mysql:5.7
    portforward: 33062
```

## Drupal DB Config
```php
$databases['default']['default'] = array(
  'database' => 'database',
  'username' => 'mysql',
  'password' => 'mysql',
  'host' => alpha,
  'driver' => 'mysql',
  'port' => 3306,
  'prefix' => '',
);
```
