### ISSUE TITLE
Lando Proxy Edge URLs stopped working after update

### ISSUE THREAD

**Issue by dchaffin** [lando/lando#1933]
I recently upgraded to: lando version v3.0.0-rc.23 docker version 2.1.0.5

... on Windows 10. Now my proxy edge URLs have stopped working. Is there a recent change to how these should be configured? Below is my .lando.yml file. Thanks!

```
name: mysitezzz
recipe: pantheon
config:
  framework: drupal8
  webroot: web
  site: mysitezzz
  id: ########-####-####-###-############
proxy:
  edge:
    - mysitezzz.lndo.site
    - mysiteyyy.lndo.site
    - mysitexxx.lndo.site
    - mysitewww.lndo.site
tooling:
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"
      - "--root=/app/web"
```
