### ISSUE TITLE
Debian 10 - Lando performance randomly degrades while in use

### ISSUE THREAD

**Issue by cchoe1** [lando/lando#1935]
Lando version: v3.0.0-rc23

My landofile (details removed)

```
name: mysite
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: mysite
  id: ID
  xdebug: true
tooling:
  drush:
    cmd: /app/vendor/bin/drush
proxy:
  pma:
    - pma.my-site.lndo.site
services:
  appserver:
    type: php
    xdebug: true
    config:
      xdebug: true
  database:
    portforward: 32111
    healthcheck:
  pma:
    type: phpmyadmin
    hosts:
      - database
```

Computer specs:
 - Ryzen 3700x 8-core (16 hyperthreaded) CPU
 - 32GB DDR4 3000mhz RAM
 - /dev/sda1 = 120GB SSD
 - /dev/sdc1 = 240GB SSD

Currently on Debian Buster.  I have my lando project in a secondary internal SSD drive (`sdc`) which is mounted onto my root (/) partition which is contained on drive `sda`.  Something will trigger `lando drush cr` to jump from 3.5 seconds to 45-70 seconds.  My computer is extremely beefy so 3.5 seconds sounds like the normal speed while 45-70 seconds seems to be the result of *some* bug.

I've also tried setting up my project directly onto drive `sda` thus completing cutting off `sdc` from the picture.  It doesn't do anything so I don't think this has anything to do with the drives I'm using.  All drives use ext4 for the filesystem.

I can reset this anomaly by unmounting /dev/sdc1 (my secondary drive) and then remounting it onto a *different* directory (still within my root partition).  Once I do this and restart lando (no rebuild necessary) a `lando drush cr` will take 3-4 seconds again and my site will run lightning fast.  If I remount it onto the same directory as before, there will be no performance change.  The site continues to run lightning fast despite multiple cache-rebuilds, database imports.  Then, all of a sudden and without warning, the cache rebuilds will go from 3s to 70s.

I've done a bit of surface-level debugging using `docker stats`.  In the lightning fast state with `lando drush cr`, the `appserver` container will utilize about 50-60% of my CPU while the `cache` container will use about 40-50%.  In the slow state, the `appserver` container will sit at 99% CPU utilization without the `cache` ever stepping in.

I'm very much unsure of how lando works under the hood but I'd presume this has something to do with the caching container.  Something is causing it to get 'stuck' or unusable or otherwise out-of-commission at some point and then my cache rebuilds will drop to incredibly slow speeds.  

 - Edited the title to be more precise
