### ISSUE TITLE
Trying to expose additional PORT fails

### ISSUE THREAD

**Issue by coolemur** [lando/lando#1937]
Hi

I tried to expose additional ports using:

https://docs.lando.dev/config/proxy.html#routing-to-a-different-port

```
proxy:
  appserver:
    - myapp.lndo.site:8888
```
(tried to change 'myapp.lndo.site:8888' with different variations with no success)

https://docs.lando.dev/config/services.html#localhost-assignment

```
services:
  my-service:
    type: apache
    moreHttpPorts:
      - '8888'
    overrides:
      ports:
       - '8888'
```
(didn't work either)

After lando start using these settings, urls stays the same.

Any ideas why it's not working ?

**Comment by pirog** [comment]
@coolemur read the documentation again. In your config

```yaml
proxy:
  appserver:
    - myapp.lndo.site:8888
```

The expected result here is that visiting `myapp.lndo.site` will serve up `appserver:8888` as opposed to the default of `appserver:80`. The expected result is NOT that you visit `myapp.lndo.site:8888` and see your `appserver`.
