### ISSUE TITLE
lando restart triggers build and build-as-root steps 

### ISSUE THREAD

**Issue by TMFEspresso** [lando/lando#1947]
lando version and operating system:

```bash
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226

$ lando version
v3.0.0-rc.23
```

.lando.yml (there's a lot here, but even with just the basic configuration and recipe, I can re-create this issue)

```yml
name: fool-ca
recipe: wordpress
config:
  php: '7.3'
  webroot: public
  via: nginx
  ssl: true
  xdebug: false
  database: mysql:5.7
  config:
    vhosts: config/default.conf.tpl

env_file:
- local.env

services:
  database:
    portforward: true
    config:
      database: config/my.cnf
    creds:
      user: wordpress
      password: wordpress
      database: wp_foolca
  appserver:
    build_as_root:
    - /app/scripts/build-steps/build-as-root.sh
    build:
    - /app/scripts/build-steps/build.sh
    config:
      php: config/php.ini
    overrides:
      volumes:
      - ./config/.bashrc:/var/www/.bashrc
      - ~/.hgrc:/var/www/.hgrc
      - ./wp-cli.yml:/app/wp-cli.yml

events:
  pre-start:
  - /app/scripts/events/pre-start.sh
  post-db-import:
  - /app/scripts/events/post-db-import.sh

tooling:
  calrissian:
    service: appserver
    cmd: /app/scripts/tooling/calrissian.sh
  wp:
    service: appserver
    cmd: /app/public/vendor/wp-cli/wp-cli/bin/wp
  db-download:
    service: appserver
    description: Pulls a stale or fresh database down and imports it
    cmd: /app/scripts/tooling/db-download.sh
    options:
      fresh:
        description: Downloads a database dump from WPEngine
        boolean: false
```

build-as-root.sh:

```
#!/usr/bin/env bash

export PATH="$PATH:/app/public/vendor/bin:/app/.composer/vendor/bin"

# Setup required packages for our codebase
apt-get update \
    && echo "postfix postfix/mailname string example.com" | debconf-set-selections \
    && echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections \
    && apt-get install -y \
		make \
		less \
		postfix \
		gnupg \
		vim \
		mercurial \
		lftp \
		iproute2 \
		python \
		ruby-full \
		vim \
		nano \
		locales \
		openssh-client \
		subversion \
		jq \
    && apt-get remove -y build-essential

# setup any extra PHP modules/extensions
docker-php-ext-install sockets

# for some reason, these files can appear in lando as giant sparsefiles
#rm -rf /var/log/lastlog
#rm -rf /var/log/faillog
```

build:

```
#!/usr/bin/env bash

source /app/scripts/helpers/functions.sh

# prep for psysh
mkdir /usr/local/share/psysh/
touch /usr/local/share/psysh/php_manual.sqlite
curl -L http://psysh.org/manual/en/php_manual.sqlite > /usr/local/share/psysh/php_manual.sqlite

# setup logging files and dirs so the rest of the application has the proper read/write privileges
mkdir /app/logs /app/logs/mysql /app/logs/php
touch /app/logs/mysql/slow-queries.log
touch /app/logs/mysql/error.log
touch /app/logs/php/debug.log
```

Series of commands that caused the bug:

```bash
$ lando restart
Stopping your app... just so we can start it up again ¯\_(ツ)_/¯
Stopping foolca_appserver_1 ... done
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Starting foolca_appserver_1 ... done
Stopping foolca_appserver_1 ... done
Starting foolca_appserver_1 ... done
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://apt.postgresql.org/pub/repos/apt stretch-pgdg InRelease [51.4 kB]          
Get:4 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [514 kB]
Get:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [173 kB] 
Get:6 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64 Packages [211 kB]
Ign:7 http://deb.debian.org/debian stretch InRelease
Get:8 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:9 http://deb.debian.org/debian buster InRelease [122 kB]
Get:10 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:11 http://deb.debian.org/debian stretch Release [118 kB]    
Get:12 http://deb.debian.org/debian stretch Release.gpg [2365 B]
Get:13 http://deb.debian.org/debian stretch-updates/main amd64 Packages [27.9 kB]
Get:14 http://deb.debian.org/debian buster/main amd64 Packages [7908 kB]
Get:15 http://deb.debian.org/debian buster-updates/main amd64 Packages [5792 B]                                                           
Get:16 http://deb.debian.org/debian stretch/main amd64 Packages [7086 kB]                                                                 
Fetched 16.5 MB in 8s (1899 kB/s)                                                                                                         
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gnupg is already the newest version (2.1.18-8~deb9u4).
gnupg set to manually installed.
less is already the newest version (481-2.1).
less set to manually installed.
make is already the newest version (4.1-9.1).
...
```

Here in the documentation, it says that `lando restart` should not cause the rebuild steps to run, but they do: https://docs.lando.dev/basics/restart.html
