### ISSUE TITLE
Windows10 Pro lando drush issue

### ISSUE THREAD

**Issue by UrielNicolas** [lando/lando#1949]
Basically any other task or issue should go here. Try to frame it as a user story if it makes sense.
I'm trying to make Lando work in Windows10
I was able to install lando, it actually works, but I have issues with Drush

`OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec format error": unknown`

This is my .lando.yml
`
name: sitename
recipe: pantheon
config:
  webroot: web
  framework: drupal8
  site: sitename
  id: ID
tooling:
  local-load-db:
    service: appserver
    description: Load database
    cmd: /app/local/import.sh
    level: app
`

I'm not sure what the issue is, and I've been trying to find out what is happening, but I have no idea.

I also have issues at running our local scripts, but unless Drush works first, it's futile.

**Comment by TMFEspresso** [comment]
The OCI runtime exec errors are more Docker erring than Lando failing. 

Try restarting Docker - sometimes Docker just glitches out and can cause weird errors.

My other guess is this: https://www.lewuathe.com/exec-format-error-in-docker-container.html

**Comment by UrielNicolas** [comment]
I will check this and let you know. This is working 100% in ubuntu, so I know for sure the problem is in Windows10 and some of the setup I made.

**Comment by UrielNicolas** [comment]
Ok, not working. I did some testing inside lando ssh and it seems drush it's not working there either, I get the following error `/usr/bin/env: 'php\r': No such file or directory`

But I do have php
www-data@fdaf4ce1ecab:/app/vendor/drush/drush$ php --version
PHP 7.3.13 (cli) (built: Dec 28 2019 21:49:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.13, Copyright (c) 1999-2018, by Zend Technologies

Anyone knows where to go from there?

**Comment by idpokute** [comment]
I have the same issue. I use windows 10 pro.

**Comment by UrielNicolas** [comment]
> I have the same issue. I use windows 10 pro.

I tried Windows Linux Subsystem and it's not working either. I'm starting to think you need to d something different when building a lando for windows

**Comment by uberhacker** [comment]
@UrielNicolas @TMFEspresso @idpokute: In what terminal app did you notice this error?  I found out if I ran `dos2unix` on the files causing the errors in Git Bash, it fixed the issue.  It appears certain files that have CRLF instead of LF endings can cause this issue.

**Comment by UrielNicolas** [comment]
I'm runing this in PowerShell or CommandPrompt, a lando environment for Pantheon

When starting lando I get this error
/app/vendor/bin/drush: 1: /app/vendor/bin/drush: ../drush/drush/drush: not found

any command, I get this
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "no such file or directory": unknown

**Comment by notserk** [comment]
Any updates on this issue? I'm still dealing with this issue.

**Comment by notserk** [comment]
I'm also running on windows 10 pro.
It seems drush doesn't get loaded during the bootstrap process:
`Getting CA Private Key
/usr/share/ca-certificates/lndo.site.pem not found... copying /lando/certs/lndo.site.pem over
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599  100   599    0     0   3477      0 --:--:-- --:--:-- --:--:--  3482
100 4673k  100 4673k    0     0  7391k      0 --:--:-- --:--:-- --:--:-- 7391k
/app/vendor/bin/drush: 1: /app/vendor/bin/drush: ../drush/drush/drush: not found
error: Looks like one of your build steps failed! with Error
    at C:\snapshot\lando\build\cli\lib\shell.js
From previous event:
    at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js)
    at Object.dc (C:\snapshot\lando\build\cli\lib\bootstrap.js)
    at compose (C:\snapshot\lando\build\cli\lib\bootstrap.js)
From previous event:
    at C:\snapshot\lando\build\cli\lib\router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Object.run (C:\snapshot\lando\build\cli\lib\router.js)
    at run (C:\snapshot\lando\build\cli\lib\engine.js)
    at C:\snapshot\lando\build\cli\lib\router.js
`

**Comment by Asterovim** [comment]
https://github.com/lando/lando/issues/2085
I think is a related problem. I have the same error with lando drush.

`OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "function not implemented": unknown`

**Comment by Opswatch** [comment]
Same issue as me, Windows 10 pro, I tried both the docker release that comes with v3.0.0-rrc.3 as well as docker 2.1.0.5 just to be sure, I do have wsl installed going to try without it.

**Comment by jan-di** [comment]
> 
> I'm runing this in PowerShell or CommandPrompt, a lando environment for Pantheon
> 
> When starting lando I get this error
> /app/vendor/bin/drush: 1: /app/vendor/bin/drush: ../drush/drush/drush: not found
> 
> any command, I get this
> OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "no such file or directory": unknown

Maybe it helps someone: I had a similar problem when working on windows. Everytime when I start lando the "build_as_root" step failed with the error message from @UrielNicolas comment. 
The problem was indeed, that the git on windows checked out all the files with CRLF file endings, including the shell scripts. When those shell scripts are executed in the appserver container, linux can't find the shell defined in the shebang (because it tries `/bin/sh\r` instead of `/bin/sh`). 

So the solution for me was to setup git that it always check out file endings as-is:
`$ git config --global core.autocrlf input`

https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace

**Comment by pirog** [comment]
I am not able to replicate this using the following:

**system**
```yaml
OS: Windows 10 Pro
Docker Desktop: 2.2.0.5
Lando: 3.0.0-rrc.7
Recipe: Pantheon with vanilla latest Drupal 8
```

**pantheon.yml**
```yaml
# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1
drush_version: 10
php_version: 7.3
```

**landofile**
```yaml
name: landobot-drupal8
recipe: pantheon
config:
  framework: drupal8
  site: landobot-drupal8
  id: 0831109d-10e9-426a-845a-e8396554acfa
```

**Comment by flyke** [comment]
I just got this error on my windows 10 machine after rebuilding a project after updating lando to 3.0.5.
These steps fixed it for me:
- delete vendor/drush folder
- restart docker
- lando rebuild
Hope this helps someone else with the same problem someday.

My .lando.yml file:
```
name: myproject
recipe: drupal8

config:
  webroot: web
  drush: ^10
  php: 7.4
  via: apache:2.4
  database: mysql:5.7
  xdebug: false

# Get nice URL's
proxy:
  mailhog:
    - mail.myproject.lndo.site
  pma:
    - pma.myproject.lndo.site

services:
  # Automatically composer install before my app starts - for site local Drush
  appserver:
    build:
      - composer install
    config:
      php: scripts/lando.php.ini

  # MailHog
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

  # PhpMyAdmin
  pma:
    type: phpmyadmin
    hosts:
      - database
```

**Comment by tmsss** [comment]
I'm afraid I've bumped into the same error on the drupal 9 recipe and @flyke's solution didn't worked for me.  The site-local drush instalation documentation [here](https://docs.lando.dev/config/drupal9.html#configuration) also didn't work for me.

Does anyone have further suggestions, an exxample of drupal 9 lando recipe for windows 10 it would be of great value. Thanks!

**Comment by tmsss** [comment]
I've experimented with the tooling configuration and looks like the traditional path in `/app/vendor/bin/drush` doesn't work on Windows 10. This was what fixed it for me:

```
name: myproject
recipe: drupal9
config:
  webroot: ./web
  drush: ^10
  xdebug: true
  tooling:
    drush:
      service: appserver  
      cmd: php /app/vendor/drush/drush/drush
```

**Comment by Asterovim** [comment]
I can also suggest to use the Docker with WSL2. Lando is very better with wsl2 (more speed, more stable, no erreur of permission and many more..).

**Comment by web-assistant** [comment]
I'm using Docker Desktop with WSL2. I did both steps:
  - [@flyke #issuecomment-644193677](https://github.com/lando/lando/issues/1949#issuecomment-644193677)
  - [@tmsss #issuecomment-652504780](https://github.com/lando/lando/issues/1949#issuecomment-652504780)

And this fixed the error for me. Thank you 😊

**Comment by flyke** [comment]
When it dod not work for me in another project, I had to add drush to the tooling section too. Since I have my vendor folder in the root of my project, this was the correct tooling section to get drush working for me:
```
tooling:
  drush:
    service: appserver
    cmd:
      - "vendor/drush/drush/drush"
```
The nice thing about this is that these changes are immediate. No need to lando restart or lando rebuild, the drush command works instantly after saving the modified .lando.yml file

**Comment by Chaquea** [comment]
Using a custom lando file for drupal 8, where the vendor folder is placed under "docroot", this worked for me in windows 10 and Docker Desktop with WSL2,as https://github.com/lando/lando/issues/1949#issuecomment-668538569 describes, didnt had to rebuild or restart lando for it to work.

```
tooling:
  drush:
    service: appserver
    cmd:
      - php "vendor/drush/drush/drush"
```

**Comment by UrielNicolas** [comment]
Using WSL2 I was able to use lando.
I also had to add something to start docker when I open WSL2

**Comment by flyke** [comment]
I had this a couple more times where I got this error on a custom lando command:
`/app/vendor/bin/drush: 1: /app/vendor/bin/drush: ../drush/drush/drush: not found`
Even after adding the tooling drush section into the .lando.yml file.

This usually happens on a (git) project where both a developer with a windows machine and a developer with a Mac machine are working on. The working solution is this for your windows machine:
- delete `vendor/bin/drush` file
- delete `vendor/drush` folder
- run a `composer install`. I am assuming that you have added drush for your project via composer. This wil re-install drush
- Now the error is fixed and you can run your lando command successfully.

**Comment by permanaj** [comment]
I have similar usecase @poindexterous , I currently solve this by adding

```
windrush:
    service: appserver
    description: Run drush in Windows host OS
    cmd: php /app/vendor/drush/drush/drush
``` 

to `tooling` section, and then run `lando windrush cr` on Windows OS and `lando drush cr` in MacOS.
Project currently use lightning distribution. And I have not try drush nuke.
