### ISSUE TITLE
Pantheon recipe does not use correct appserver image

### ISSUE THREAD

**Issue by pcfreak30** [lando/lando#1950]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

 v3.0.0-rc.2 Manjaro Linux 18.1.5

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

```
name: test
recipe: test
config:
  framework: wordpress
  site: test
  id: 74433384-be67-455a-83e3-5cf137673ca7
  xdebug: true
services:
  appserver:
    overrides:
      image: devwithlando/pantheon-appserver:7.0-2
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

 `pantheon.yml`

```
api_version: 1
php_version: 7.0
```

**Tell us about the command you were running**

`lando init --source pantheon`

**Tell us about the error you got** / **Tell us generally about your bug**

It  appears to use the general nginx server as `appserver` vs the php-fpm image. I had to use an override base on the `builder.js` code to force it to use the correct one.

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
Does this bug prevent you from using lando?

If I was not able to work around this, it would have forced me yo use a generic LEMP recipe.
