### ISSUE TITLE
Documentation says Node Patch versions can be used

### ISSUE THREAD

**Issue by generalredneck** [lando/lando#1981]
Please complete the following:

**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/config/node.html#patch-versions

**Describe the change you'd like**
I would like for this page to describe the actual behavior when you try to use a patch version from the tags list linked on that page. Example, I'm using node:10.19.0 which is clearly a tag https://hub.docker.com/layers/node/library/node/10.19.0/images/sha256-5d138d5adb4b73ff6a322e71a2c9c8c9102c340e61afd5c2f610b302a75e7789?context=explore that I chose from the list. Instead, Lando says 
```
error: node version 10.19.0 is not supported
```
The page DOES say that patch images are not *officially* supported... however, the wording and the examples provide the air that it should *work*.

Here is my configuration just in case it's a PEBCAK problem instead of a documentation problem:

```
name: ###REDACTED###
recipe: pantheon
config:
  framework: drupal
  env: dev
  site: ###REDACTED###
  id: ###REDACTED###
services:
  appserver:
    config:
      conf: config/php.ini
  database:
    config:
      confd: config/mysql
  node:
    type: node:10.19.0
    build:
      - "cd $LANDO_MOUNT && npm install"
tooling:
  node:
    service: node
  npm:
    service: node
  drush:
    service: appserver
    cmd: "drush --root=/app/web"
```
