### ISSUE TITLE
Solr 7: /solr/drupal/select Not Found

### ISSUE THREAD

**Issue by milkovsky** [lando/lando#1982]
v3.0.0-rc.23 on Ubuntu 18.04.4 LTS

I've added a Solr search service to lando yml. But I can not do any query in my Solr index.
I can see my Solr instance at `http://localhost:33215/solr/drupal`.
But when I visit `http://localhost:33215/solr/drupal/select?q=*:*`, I get 404 error:
```
HTTP ERROR 404
Problem accessing /solr/drupal/select. Reason:
    Not Found
```

It looks like an error inside the docker image to me.

My `.lando.yml`

```yml
name: test
recipe: drupal8

services:
  search:
    type: solr:7.6
    portforward: true
    core: drupal
    config:
      dir: docroot/modules/contrib/search_api_solr/solr-conf-templates/7.x
```

P.S. Query works if I use `solr:6.6`.
