### ISSUE TITLE
PostgreSQL administration, like phpMyAdmin?

### ISSUE THREAD

**Issue by gitressa** [lando/lando#1991]
MySQL has phpMyAdmin integration with Lando for administration, is there a similar solution for PostgreSQL?

**Comment by jordan8037310** [comment]
Check these out:

* https://www.pgadmin.org/
* https://hub.docker.com/r/dpage/pgadmin4

**Comment by gitressa** [comment]
Thanks, I also found pgAdmin when I was looking for the available options. But I am looking for a PostgreSQL GUI with Lando integration, like [PhpMyAdmin](https://docs.lando.dev/config/phpmyadmin.html) has.

Ideally I would like to be able set up a GUI (like pgAdmin) for PostgreSQL database with something like this:
```
name: postgres
recipe: drupal8
config:
  webroot: web
  database: postgres

proxy:
  pgadmin:
    - pgadmin.postgres.lndo.site

services:
  pgadmin:
    type: pgadmin
    hosts:
      - database
```
For fun, I tried with both `pgadmin` and `pgadmin4`, but got this message:
> ...
> warn: pgadmin4 is not a supported service type.

Is there some other way of getting a GUI for PostgreSQL in Lando?

**Comment by pirog** [comment]
I think we should bump this to a feature request to add a `pgadmin` service to go along with the `phpmyadmin` one we already have. Here are the relevant things we'd need to do/use to make this happen

* Use their official Docker images - https://hub.docker.com/r/dpage/pgadmin4
* Add a pgaadmin service to Lando, here is the phpmyadmin one as a model - https://github.com/lando/lando/tree/master/plugins/lando-services/services/phpmyadmin
* Document the service, here are the phpmyadmin docs as a model - https://github.com/lando/lando/blob/master/docs/config/phpmyadmin.md
* Add functional test examples, again, here are the pma ones - https://github.com/lando/lando/tree/master/examples/pma

Also going to flag this as a good first time issue, anyone game to give it a shot?

**Comment by gitressa** [comment]
This feature would still be quite useful.

**Comment by pirog** [comment]
Agreed. Right now we are focusing on a better way to handle plugins and once we do that i think it will be a lot easier to handle things like this

**Comment by gitressa** [comment]
Sounds good, thanks.

**Comment by gitressa** [comment]
Thanks Stalebot, but this issue is till relevant.

**Comment by wesleyduff** [comment]
Ditto.. looking into building one now

**Comment by wesleyduff** [comment]
OK got it..

```
name: podcast
services:
  postgreService:
    type: postgres:13
    creds:
      database: database
      user: postgres
      password:
  pgadmin:
    type: compose
    app_mount: false
    services:
      image: dpage/pgadmin4
      command: /entrypoint.sh
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "127.0.0.1::80"
  nodeServer:
    type: node:14
    ssl: false
    command: npm run start:webpack
    build:
      - npm install
      - npm run prepare
      - npm run build:dev
    globals: []
    port: 3000
tooling:
  npm:
    service: node
  node:
    service: node
    
    ```
    
Username : admin@admin.com
password: root

... 


DB connection info: or use `lando info` to get it 

hose : postgreService
port: 5432

Maintenance Database : database
user: postgres

-----


Hope this helps someone out...
