### ISSUE TITLE
lando db-import command line output prints the incorrect host

### ISSUE THREAD

**Issue by markdorison** [lando/lando#2027]
## Summary
`lando db-import`'s command line output prints the incorrect host.

## Details
When importing databases using the `lando db-import` command with the `--host` flag, the database is imported to the specified host, but the output on the command line always shows `localhost` as the host. 

Note: This is similar to https://github.com/lando/lando/issues/1929, but while https://github.com/lando/lando/issues/1929 is about functionality, this ticket is strictly about the command line output of `lando db-import`.

## Steps to Reproduce
```bash
lando db-import alpha-latest.sql.gz --host=alpha
```

## Actual Results
```bash
Preparing to import /app/alpha-latest.sql.gz into database on **localhost**:3306 as root...
```

## Expected Results
```bash
Preparing to import /app/alpha-latest.sql.gz into database on **alpha**:3306 as root...
```

## Versions
Lando v3.0.0-rc.23
macOS 10.15.3

## .lando.yml

```yml
name: site-name
recipe: drupal8

config:
  webroot: web
  php: '7.2'
  database: mariadb:10.3
  drupal: true
  xdebug: false

proxy:
  appserver:
    - "*.lndo.site"

services:
  node:
    type: node:10
    globals:
      yarn: "1.17.3"
  alpha:
    type: mariadb:10.3
    portforward: 33061
  bravo:
    type: mariadb:10.3
    portforward: 33062
```

## Drupal DB Config
```php
$databases['default']['default'] = array(
  'database' => 'database',
  'username' => 'mysql',
  'password' => 'mysql',
  'host' => alpha,
  'driver' => 'mysql',
  'port' => 3306,
  'prefix' => '',
);
```
