### ISSUE TITLE
How to use docker image which already has /app folder

### ISSUE THREAD

**Issue by JorisVanEijden** [lando/lando#2029]
I want to use this docker image: https://registry.hub.docker.com/r/ankane/pghero
The application inside it lives in `/app`
Lando always mounts an `/app` volume, thus overwriting the actual app.
How do I prevent this?

Minimal reproduction .lando.yml:
```yml
name: tst
services:
  pghero:
    type: compose
    services:
      image: ankane/pghero
      command: puma -C config/puma.rb
```
The log shows the app fails to start:
```
Running command puma -C config/puma.rb
/usr/local/bundle/gems/puma-4.3.0/lib/puma/dsl.rb:46:in `read': No such file or directory @ rb_sysopen - config/puma.rb (Errno::ENOENT)
```
Which makes sense because lando has overwriiten the /app directory with a volume.

Inspecting the created `globals-0.yml` shows these volumes:
```yml
volumes:
  - '/home/jvaneijden/pgherotest:/app:delegated'
  - '/home/jvaneijden/.lando/scripts:/helpers'
```

**Comment by TMFEspresso** [comment]
Would this work?

```
name: tst
services:
  pghero:
    type: compose
    services:
      image: ankane/pghero
      command: puma -C config/puma.rb
      volumes:
        - ./app:/app/puma
```

**Comment by pirog** [comment]
@JorisVanEijden im not sure you can with the compose service. You could try loading the image directly with a docker compose file which _i think_ should bypass most if not all of landos usual setup.

See the `compose` top level key in the docs here
https://docs.lando.dev/basics/basics.html#so-what-does-this-landofile-look-like-anyway

**Comment by JorisVanEijden** [comment]
Sorry for the late reply, this dropped off my radar.

Unfortunately using a separate compose file is unable to work around this. The end result is eaxctly the same.

.lando.yml:
```yml
name: tst
compose:
  - pghero-docker-compose.yml
```
pghero-docker-compose.yml:
```yml
version: "3.6"
services:
  pghero:
    image: ankane/pghero
```

`docker-compose -f pghero-docker-compose.yml up`:
```
Creating network "tst_default" with the default driver
Creating tst_pghero_1 ... done                                                                                          Attaching to tst_pghero_1
pghero_1  | [1] Puma starting in cluster mode...
pghero_1  | [1] * Version 4.3.3 (ruby 2.7.1-p83), codename: Mysterious Traveller
pghero_1  | [1] * Min threads: 1, max threads: 16
pghero_1  | [1] * Environment: production
pghero_1  | [1] * Process workers: 3
```

`lando start`:
```
Let's get this party started! Starting app tst...
Creating network "tst_default" with the default driver
Creating tst_pghero_1 ... done                                                                                          ERROR: No container found for pghero_1
error: Looks like pghero is not running! It should be so this is a problem.
warn: Try running `lando logs -s pghero` to help locate the problem!
```

`lando logs -s pghero`:
```
Attaching to tst_pghero_1
pghero_1  | /usr/local/bundle/gems/puma-4.3.3/lib/puma/dsl.rb:46:in `read': No such file or directory @ rb_sysopen - /app/config/puma.rb (Errno::ENOENT)
pghero_1  |     from /usr/local/bundle/gems/puma-4.3.3/lib/puma/dsl.rb:46:in `_load_from'
pghero_1  |     from /usr/local/bundle/gems/puma-4.3.3/lib/puma/configuration.rb:195:in `block in load'
pghero_1  |     from /usr/local/bundle/gems/puma-4.3.3/lib/puma/configuration.rb:195:in `each'
pghero_1  |     from /usr/local/bundle/gems/puma-4.3.3/lib/puma/configuration.rb:195:in `load'
pghero_1  |     from /usr/local/bundle/gems/puma-4.3.3/lib/puma/launcher.rb:58:in `initialize'
pghero_1  |     from /usr/local/bundle/gems/puma-4.3.3/lib/puma/cli.rb:71:in `new'
pghero_1  |     from /usr/local/bundle/gems/puma-4.3.3/lib/puma/cli.rb:71:in `initialize'
pghero_1  |     from /usr/local/bundle/gems/puma-4.3.3/bin/puma:8:in `new'
pghero_1  |     from /usr/local/bundle/gems/puma-4.3.3/bin/puma:8:in `<top (required)>'
pghero_1  |     from /usr/local/bundle/bin/puma:23:in `load'
pghero_1  |     from /usr/local/bundle/bin/puma:23:in `<main>'
```

globals-0.yml:
```yml
services:
  pghero:
...
    volumes:
      - '/home/jvaneijden/pgherotest:/app:delegated'
      - '/home/jvaneijden/.lando/scripts:/helpers'
...
```

It would be nice if we could get a flag/option to _not_ get the current dir mounted to `/app`.
I was hoping I'd overlooked an option, setting or workaround but it seems you really cannot use any docker image that uses an `/app` directory with Lando.

If you like I can try to find some time to work on this, but since it seems to be quite low-level maybe someone with a bit more insight into the Lando fundamentals might be a better fit?
