### ISSUE TITLE
Ruby / Compass Guide Example

### ISSUE THREAD

**Issue by labboy0276** [lando/lando#2039]
As requested, here is a Lando config file that use ruby, gems, & compass...

```
name: site
recipe: drupal7
config:
  via: nginx
  php: '7.2'
  xdebug: true
services:
  ruby:
    type: ruby:2.4
    build:
      - gem install compass
tooling:
  gem:
    service: ruby
  ruby:
    service: ruby
  compass:
    service: ruby

```
