### ISSUE TITLE
Support LocalStack

### ISSUE THREAD

**Issue by adamzerella** [lando/lando#2040]
**Please explain your request and its importance in the form of a user story.**

As a lando user who works with a Node microservice application, It's really useful for me to stub out interactions with popular cloud providers, LocalStack provides this interface for me but I cannot use this easily with Lando without resorting to Docker Compose woes.

**Is your feature request related to a problem? Please describe.**
I'm trying to use LocalStack and Lando services.

**Describe the solution you'd like**
Provide a service container for me to interact with LocalStack.

**Comment by serundeputy** [comment]
Hello @adamzerella thanks for opening this issue.

I'm not familiar w/ LocalStack, but perhaps this image https://hub.docker.com/r/localstack/localstack and the `lando` compose key can get you what you want/need? 

https://docs.lando.dev/config/compose.html#configuration

under the `compose` key in your `.lando.yml` file specify the `localstack` docker image.

**Comment by WayneBrummer** [comment]
Hello it has some user specific issues when it comes to Localstack.

**Comment by generalredneck** [comment]
I came across this while I was poking around localstack support. Here's how I used the compose plugin to add a localstack service to my site.

```yaml
services:
  localstack:
    type: compose
    services:
      image: localstack/localstack:0.14.2
      environment:
        - AWS_DEFAULT_REGION=us-east-1
        - EDGE_PORT=4566
        - SERVICES=s3
        - DEBUG=1
        - DATA_DIR=/tmp/localstack/data
      ports:
        - '4510-4559:4510-4559'
        - '4566:4566'
      command: "docker-entrypoint.sh"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "./localstack:/tmp/localstack"
```
