### ISSUE TITLE
rsync not working in the new PHP 7.4 container (v3.0.0-aft.1)

### ISSUE THREAD

**Issue by BramDriesen** [lando/lando#2056]
**Tell us about your setup**
v3.0.0-aft.1 on MacOS

**Tell us about your `.lando.yml`**

```yml
name: be-blog
recipe: drupal8
config:
  php: 7.4
  via: nginx
  webroot: web
  xdebug: true
  drush: 9
proxy:
  appserver_nginx:
    - local-blog.XXX.be
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
```

**Tell us about the command you were running**

```bash
lando drush sql:sync @server @self -y
lando drush rsync @server:%files @self:%files -y
```

**Tell us about the error you got**

```bash
> sh: 1: rsync: not found
```

**Tell us generally about your bug**
Rsync is failing in the PHP 7.4 container, on the 7.3 version it's working fine.
