### ISSUE TITLE
Cannot start database container

### ISSUE THREAD

**Issue by paulpopus** [lando/lando#2061]
**Tell us about your setup**

Ubuntu 18.04 with latest system updates
On latest docker 19.03.8
Using lando v3.0.0-aft.2

*My .lando.yml file*

```yml
name: espmain
recipe: drupal7
config:
  xdebug: true
  webroot: web
  php: '5.6'
proxy:
  mailhog:
    - mail.espmain.lndo.site
  adminer:
    - adminer.espmain.lndo.site
services:
  database:
    creds:
      user: database
      password: database
      database: database
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: '/bin/s6-svscan /etc/services.d'
    portforward: true
  node:
    type: 'node:10'
    globals:
      gulp-cli: latest
    overrides:
      ports:
        - '33753:33753'
  appserver:
    run:
      - '/bin/sh -c "if [ ! -d ~/.drush/registry_rebuild ]; then drush @none dl registry_rebuild-7.x; fi"'
    overrides:
      environment:
        DRUSH_OPTIONS_ROOT: /app/web
        DRUSH_OPTIONS_URI: 'http://espmain.lndo.site'
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  drush:
    service: appserver
    cmd:
      - 'drush --root=/app/web'
  xdebug-on:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root
```

**Tell us about the command you were running**

Trying to build the project using `lando start`. Tried destroying or rebuilding.

**Tell us about the error you got**

It would hang on `Waiting until database service is ready...` which it would repeat several times before printing
```bash
warn: Service database is unhealthy
warn: Run "lando logs -s database"
```

The logs command returns this
```bash
$ lando logs -s database
Attaching to espmain_database_1
database_1   | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
database_1   | mkdir: cannot create directory '/etc/ssh': Permission denied
database_1   | Running command /bin/sh -c chmod +x /launch.sh && /launch.sh
database_1   | Running with exec!
database_1   | chmod: changing permissions of '/launch.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
database_1   | mkdir: cannot create directory '/etc/ssh': Permission denied
database_1   | Running command /bin/sh -c chmod +x /launch.sh && /launch.sh
database_1   | Running with exec!
database_1   | chmod: changing permissions of '/launch.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
database_1   | mkdir: cannot create directory '/etc/ssh': Permission denied
database_1   | Running command /bin/sh -c chmod +x /launch.sh && /launch.sh
database_1   | Running with exec!
database_1   | chmod: changing permissions of '/launch.sh': Operation not permitted
```

I've tried lando, docker and system restarts and removing the images manually. It pulled new images but the issue persisted. I have checked for memory and disk space but there's plenty of that.

Worth noting that this issue looks related to the memcache issue here https://github.com/lando/lando/issues/1827
