### ISSUE TITLE
Support phpmyadmin 5.0

### ISSUE THREAD

**Issue by rabauss** [lando/lando#2062]
Due to login problems in `phpmyadmin:4.7` with `mysql:8.0` the version 5.0 of phpmyadmin should get supported.

I guess `/docs/config/phpmyadmin.md` and `/plugins/lando-services/services/phpmyadmin/builder.js` should get updated. But I'm not sure with contributing or testing, so I can only suggest the files ;-)

Custom definition is also working for me at the moment with `lamp` recipe:
```yml
recipe: lamp
services:
  database:
    type: mysql:8.0
  phpmyadmin:
    type: compose
    services:
      image: phpmyadmin/phpmyadmin:5.0
      command: /docker-entrypoint.sh apache2-foreground
      environment:
        PMA_HOST: database
        PMA_USER: lamp
        PMA_PASSWORD: lamp
```
