### ISSUE TITLE
mariadb: Access denied for user 'mysql'@'172...

### ISSUE THREAD

**Issue by markdorison** [lando/lando#2065]
## Summary
Unable to connect to MariaDB host.

## Details
Unable to connect to MariaDB host after updating to Lando v3.0.0-aft.2. Drupal seems to convert each hostname specified to an IP address that fails. I am not familiar with this IP and it seems to remain the same regardless of which database host I attempt to connect to.

The issue occurs with `mariadb:10.3` and `mariadb:10.2`.

It works as expected when I switch to `mysql:5.7`. (see example `.lando.yml` configs below.

Note: When switching db versions I ran `lando destroy` and then `lando start` between each change.

## Steps to Reproduce
```bash
lando drush @alpha.local sqlc
```

## Actual Results
```bash
ERROR 1045 (28000): Access denied for user 'mysql'@'172.23.0.2' (using password: YES)
```

## Expected Results
```bash
Welcome to the MariaDB monitor.  Commands end with ; or \g.
```

## Versions
Lando v3.0.0-aft.2
Docker 2.1.0.5
macOS 10.15.3

## .lando.yml (not working)

```yml
name: site-name
recipe: drupal8

config:
  webroot: web
  php: '7.2'
  database: mariadb:10.3
  drupal: true
  xdebug: false

proxy:
  appserver:
    - "*.lndo.site"

services:
  node:
    type: node:10
    globals:
      yarn: "1.17.3"
  alpha:
    type: mariadb:10.3
    portforward: 33061
  bravo:
    type: mariadb:10.3
    portforward: 33062
```

## .lando.yml (working)

```yml
name: site-name
recipe: drupal8

config:
  webroot: web
  php: '7.2'
  database: mysql:5.7
  drupal: true
  xdebug: false

proxy:
  appserver:
    - "*.lndo.site"

services:
  node:
    type: node:10
    globals:
      yarn: "1.17.3"
  alpha:
    type: mysql:5.7
    portforward: 33061
  bravo:
    type: mysql:5.7
    portforward: 33062
```

## Drupal DB Config
```php
$databases['default']['default'] = array(
  'database' => 'database',
  'username' => 'mysql',
  'password' => 'mysql',
  'host' => alpha,
  'driver' => 'mysql',
  'port' => 3306,
  'prefix' => '',
);
```
