### ISSUE TITLE
lando composer doesn't work

### ISSUE THREAD

**Issue by thasmo** [lando/lando#2076]
`lando composer` only prints a message. Actually, any composer command just prints a message and doesn't run the desired action.

**Tell us about your setup**
* Windows 10
* Lando *3.0.0-aft.2*

**Tell us about your `.lando.yml`**
```yml
name: project
recipe: lemp
config:
  webroot: public
  database: mysql
  php: 7.2
  xdebug: true
  config:
    php: php.ini
tooling:
  npm:
    service: node
  node:
    service: node
services:
  node:
    type: node:10
    globals:
      npm: 6
    run:
      - npm ci
```

**Tell us about the command you were running**
```bash
lando destroy -y
lando start
lando composer install
```

**Tell us about the error you got**
```bash
> lando composer install
You must set up the project dependencies using `composer install`
See https://getcomposer.org/download/ for instructions on installing Composer
```

**Tell us generally about your bug**
```bash
1. Updated to AFT 2.
2. Destroyed the lando project.
2. Deleted all Docker images/containers.
3. Restarted Docker for Windows.
4. Ran the commands above.
```
