### ISSUE TITLE
Install or upgrade dependencies using build steps

### ISSUE THREAD

**Issue by thasmo** [lando/lando#2077]
At the moment, when I run `lando npm ci` on the `node` service it complains with the following, when trying to install Git hooks via husky.js:

```
Husky requires Git >=2.13.0. Got v2.11.0.
husky > Failed to install
```

It seems that most of the Docker images have Git `2.11.0` preinstalled; in my case the Docker image `node:10` used for the `npm` command, also has Git `2.11.0` preinstalled.

Is there a way to update the Git version inside the services/containers to the latest release?

**Comment by thasmo** [comment]
I kinda solved this by overriding the used docker image:
```
services:
  node:
    type: node:10
    overrides:
      image: node:10-buster
```

Wondering if lando could even use newer distros/images by default?
