### ISSUE TITLE
elasticsearch  | mkdir: cannot create directory '/etc/ssh': Permission denied

### ISSUE THREAD

**Issue by Asterovim** [lando/lando#2084]
Hello.

I use lastest version of lando (v3.0.0-rrc.1) Windows 10 and .lando.yml :
```
name: myname
recipe: drupal8
config:
  type: php:7.2
  via: nginx
  webroot: web
  database: mariadb:10.1
  drush: "*"
services:
  elasticsearchlando:
    type: elasticsearch:6.5.4
    portforward: true
  appserver:
    build:
      - composer install
```

When i start i have this error with elastic search :
`elasticsearchlando_1  | mkdir: cannot create directory '/etc/ssh': Permission denied`

After that, i have "lando rebuild -y" and it's work's. But why this error ?

Thanks you.
