### ISSUE TITLE
MIME type issue in pantheon recipe

### ISSUE THREAD

**Issue by keithdoyle9** [lando/lando#2093]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**
v3.0.0-rrc.2 on Windows 10 Enterprise
Docker Desktop 2.2.0.3

**Tell us about your `.lando.yml`**
```yml
name: xxxx
recipe: pantheon
config:
  framework: drupal8
  site: xxx
  id: xxxx-xxxx-xxxx-xxxx
  index: false
  xdebug: true
  php: .vscode/php.ini
proxy:
  mailhog:
    - mail.xxxx.lndo.site
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/web
```

pantheon.yml

```yml
api_version: 1
web_docroot: true
php_version: 7.3
drush_version: 9

# Protected Web Paths
# https://pantheon.io/docs/pantheon-yml#protected-web-paths
protected_web_paths:
   - /AutoDiscover/autodiscover.xml
   - /autodiscover/autodiscover.xml

workflows:
  # Product deployments
  deploy_product:
    after:
      - type: webphp
        description: Post to Slack after site creation
        script: private/scripts/slack_notification.php

  # Multi-dev creation
  create_cloud_development_environment:
    after:
      - type: webphp
        description: Post to Slack after Multidev creation
        script: private/scripts/slack_notification.php

  # Code Deploys
  deploy:
    after:
      - type: webphp
        description: Log to New Relic
        script: private/scripts/new_relic_deploy.php
      - type: webphp
        description: Import configuration from .yml files and update database
        script: private/scripts/drush_config_import.php
      - type: webphp
        description: Post to Slack after deploy
        script: private/scripts/slack_notification.php

  # Database Clones
  clone_database:
    after:
      - type: webphp
        description: Import configuration from .yml files and update database
        script: private/scripts/drush_config_import.php
      - type: webphp
        description: Sanitize the db after each database clone
        script: private/scripts/db_sanitization_drupal.php
      - type: webphp
        description: Post to Slack after database cloned
        script: private/scripts/slack_notification.php

  # Sync code from one environment to the next
  sync_code:
    after:
      - type: webphp
        description: Log to New Relic
        script: private/scripts/new_relic_deploy.php
      - type: webphp
        description: Push changes back to GitHub if needed
        script: private/scripts/quicksilver/quicksilver-pushback/push-back.php
      - type: webphp
        description: Import configuration from .yml files and update database
        script: private/scripts/drush_config_import.php
      - type: webphp
        description: Post to Slack after code commit
        script: private/scripts/slack_notification.php

  # Clearing cache
  clear_cache:
    after:
      - type: webphp
        description: Someone is clearing the cache again
        script: private/scripts/slack_notification.php
```

**Tell us about the error you got**

Rerun the command that produced your error in `debug` mode. Note that `debug` mode is run like this `lando command -vvv`. Paste in the error and the `~100` lines that proceeded it.

*Example:*

```bash
Refused to execute script from 'https://xxxx.lndo.site/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

Refused to apply style from 'https://xxxx.lndo.site/' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

**Tell us generally about your bug**
I am trying to bring my site up after upgrading from rc23. I've completely uninstalled and reinstalled Docker and Lando multiple times and rebuilt the containers multiple times.

Does this bug prevent you from using lando?
Yes
