### ISSUE TITLE
The latest and greatest uses a lot of cpu

### ISSUE THREAD

**Issue by bond708** [lando/lando#2103]
If you are not sure how to do that then please complete as much of the below section as possible

**Tell us about your setup**

What is your lando version and operating system? 
v3.0.0-rrc.2 Ubuntu 19.10

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.
```
name: h
recipe: drupal7
config:
  webroot: web
  php: '5.6'
  config:
    php: .lando/config/php.ini

proxy:
  appserver:
    - h.lndo.site
    - o.lndo.site
  # solr:
  #   - admin.solr.lndo.site:8983
  pma:
    - admin.pma.lndo.site
  # mail:
  #   - admin.mail.lndo.site

services:

  # APPSERVER: Web container.
  appserver:
    build:
      # Default startup tasks.
      - echo -e "\n### Start default build tasks ..."
      - cd /app && git submodule update --init --recursive
      - cd /app && git submodule update --remote tools
      - echo -e "### End of default build tasks ...\n"

  # DATABASE: Mysql server
  database:
    creds:
      user: yes
      password: difficult
      database: default

  # STYLE: Frontend tooling.
  style:
    type: node # E.g. node or ruby
    overrides:
      environment:
        LANG: C.UTF-8
    run:
      - /app/tools/scripts/style.sh --style=sass --type=install

  # SOLR: Search server.
  # solr:
  #   type: solr:5
  #   portforward: TRUE
  #   core: h
  #   config:
  #     dir: tools/solr_config/d7/5.x
    # run_as_root:
    #   # Create extra cores.
    #   - /app/tools/d7/tools.sh --solr=h --type=create --version=7
    #   - /app/tools/scripts/solr.sh --core=h --type=create

  # PHPMYADMIN: Database management.
  pma:
   type: phpmyadmin
   hosts:
     - database

  # MAILHOG: Email testsuite.
  # mail:
  #   type: mailhog
  #   portforward: TRUE
  #   hogfrom:
  #     - appserver

tooling:

  drush:
    service: appserver
    cmd: drush --root=/app/web

  errors:
    service: appserver
    describe: Show php errors
    cmd: tail -f /app/.lando/log/php_error.log

  patch:
    service: appserver
    cmd: /app/tools/scripts/patch.sh

  patch-all:
    service: appserver
    cmd: /app/tools/scripts/patch.sh --all

  database:
    service: appserver
    cmd: /app/tools/scripts/database.sh --root=/app/web --alias=dev --revert=true --url=https://xxx.xxx.xx/h-site
    level: app
    describe: Import or export database
    options:
      site:
        passthrough: true
        interactive:
          message: Choose the site to operate on (default = h-site).
          type: list
          choices:
            - default
            - o
          default: default
      type:
        passthrough: true
        interactive:
          message: Import from server, file or export
          type: list
          choices:
            - server
            - file
            - export
          default: server

  conf:
    service: appserver
    cmd: /app/tools/scripts/config.sh --alias=dev --root=/app/web --revert=true
    level: app
    options:
      site:
        passthrough: true
        interactive:
          message: Choose the site you want to use (default = h-site).
          type: list
          choices:
            - default
            - o
          default: default
      type:
        passthrough: true
        interactive:
          message: Revert features or update database
          type: list
          choices:
            - revert
            - revert-all
            - update-db
          default: revert

  style:
    service: style
    cmd: /app/tools/scripts/style.sh --style=sass --root=/app/web/sites/all/themes --if=sass --of=css
    level: app
    options:
      theme:
        passthrough: true
        interactive:
          type: list
          message: Choose the theme you want to compile.
          choices:
            - h
#            - h_2016
            - h_mini
            - h_o
          default: h
      type:
        passthrough: true
        interactive:
          message: Compile or watch
          type: list
          choices:
            - compile
            - watch
          default: compile

events:

  pre-start:
    # Default startup tasks.
    - appserver: echo -e "\n### Start default pre-start tasks ..."
    - appserver: cd /app && git submodule update --init --recursive
    - appserver: cd /app && git submodule update --remote tools
    - appserver: echo -e "### End of default pre-start tasks ...\n"

  post-start:
    # Default theme tasks.
    - appserver: echo -e "\n### Start default post-start tasks ..."
    - style: /app/tools/scripts/style.sh --style=sass --theme=h--type=compile --root=/app/web/sites/all/themes --if=sass --of=css
    - style: /app/tools/scripts/style.sh --style=sass --theme=h_mini --type=compile --root=/app/web/sites/all/themes --if=sass --of=css
    - style: /app/tools/scripts/style.sh --style=sass --theme=o --type=compile --root=/app/web/sites/all/themes --if=sass --of=css
    - appserver: echo -e "### End of default post-start tasks ...\n"

    # Show tips and tricks.
    - appserver: /app/tools/scripts/tips.sh --root=/app/web --alias=dev

  pre-stop:
    - appserver: cd /app && git status
```

**Tell us about your bug**

My cpu is going sky high, though enough memory and power. Happens since last 2 releases.
On startup, on features etc. Pretty simple to reproduce.
According to my monitor apache is taking a lot but on the other hand, I am a frontend developer.
No problems in earlier versions.
