### ISSUE TITLE
Tooling: Allow Setting Environment Variables

### ISSUE THREAD

**Issue by AaronFeledy** [lando/lando#2128]
As a Lando user who frequently creates tooling to simplify complex commands, I frequently find that I need to pass additional information into the service along with my tooling command.

Lando could help with this by allowing me to set environment variables as part of my tooling config.

Currently, environment variables can be set as part of a command like so:
```yaml
    cmd: COMPOSER_PROCESS_TIMEOUT=600 composer install`
```
The simplest usage of this new feature, which would have the same effect as the above, might look something like this:
```yaml
tooling:
  install:
    service: appserver
    environment:
      - COMPOSER_PROCESS_TIMEOUT: 600
    cmd: composer install
```

The above usage is useful for commands like `composer` that accept options via environment variables, but you could also set arguments like so:
```yaml
tooling:
  db-dump:
    service: appserver
    environment:
      - REMOTE_ENV: develop
    cmd: platform db:dump --gzip --environment=$REMOTE_ENV --file=db_dump.sql.gz --yes
```
So far, this new feature just looks like a syntax change for passing information that could just as easily be part of the command. However, multi-command tooling could take advantage of a set of variables being defined once but all commands have them available, so there's an improvement there.

This feature really becomes powerful when you take advantage Lando's tooling options functionality:
```yaml
tooling:
  db-dump:
    service: appserver
    environment:
      - REMOTE_ENV: :env
    cmd: platform db:dump --gzip --environment=$REMOTE_ENV --file=db_dump.sql.gz --yes
    options:
      env:
        default: develop
        describe: Get database from a specific environment
```
This example would pass `develop` to the `--environment` option by default, but if the need arises, the user can set that option like `lando db-dump --env=production`. This also allows passing variables from your host into the app like `lando db-dump --env=$MY_FAV_ENVIRONMENT`.

**Comment by jonathanjfshaw** [comment]
Setting an environment variable as part of a command is something I find myself wanting to do.
I can do `export VAR=1 && run command && export VAR=0" but it's ugly.

**Comment by pirog** [comment]
I think this is already possible, but not yet documented, as of `3.0.4` anyway. The syntax is
```
tooling:
  db-dump:
    service: appserver
    env:
      - REMOTE_ENV: :env
    cmd: platform db:dump --gzip --environment=$REMOTE_ENV --file=db_dump.sql.gz --yes
    options:
      env:
        default: develop
        describe: Get database from a specific environment
```

I think the caveat here is you'll need to make sure that if you use `$REMOTE_ENV` in the cmd that this is being used correctly. eg i think in the example here `cmd` would use the `$REMOTE_ENV` set on your HOST not in the CONTAINER`
