### ISSUE TITLE
Impossible to mount a volume from my local host

### ISSUE THREAD

**Issue by sebastienserre** [lando/lando#2129]
Hello,
I'm running Lando v3.0.0-rrc.3 on Ubunut 18.04
Here's my `.lando.yml`:
```name: dev-polylang
recipe: wordpress
config:
  php: 7.4
  webroot: .
  xdebug: true
  database: mariadb
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    hogfrom:
    - appserver
  appserver:
    overrides:
      volumes:
      #  - /home/sebastien/polylang:/appserver/wp-content/plugins/polylang/
        - /appserver/wp-content/plugins/polylang/:/home/sebastien/polylang

tooling:
  composer:
    service: appserver

```
I'm trying to mount my local directory 'polylang' in my Lando container under the folder /appserver/wp-content/plugins without any success

I don't know if I am the bug or something is wrong with Overrides... Is someone can help me to solve it out ?

Thanks

**Comment by pirog** [comment]
@sebastienserre we test this out pretty extensively, many of our examples make use of this override and i think this is a fairly common thing our power users do. 

In particular this example https://github.com/lando/lando/tree/master/examples/services tests this specific override, so i'd recommend trying it out as a sanity check so you can at least determine that the problem here is not Lando. 

My suspicion is your issue is with the config syntax. The volumes format should be something like this

```
  appserver:
    overrides:
      volumes:
        - /path/on/host:/path/in/container
        - ./relative/to/app/root/on/host:/path/in/container
        - /home/me:/me
        - ./somefolder:/tmp
```

You'll want to `lando rebuild` afterwards and make sure what you are sharing actually exists on the host.
