### ISSUE TITLE
compose service proxy gives ERR_INVALID_REDIRECT

### ISSUE THREAD

**Issue by tormi** [lando/lando#2149]
`v3.0.0-rrc.3`, `v3.0.0-rrc.4` (or latest Docker shipped with it) breaks one of my compose services, namely adminer - it's proxy gives ERR_INVALID_REDIRECT after the upgrade. Setup has been working until `v3.0.0-rrc.2` (including).

Reference to @pirog's suggestion on Slack to file an issue: https://devwithlando.slack.com/archives/C2XBSHX8R/p1586678412457800

**Tell us about your setup**

*v3.0.0-rc.4 on macOS Catalina 10.15.4 (19E287)*

**Tell us about your `.lando.yml`**

```
services:
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: /bin/s6-svscan /etc/services.d
    portforward: true
proxy:
  adminer:
    - adminer.lndo.site
```

The whole project and `adminer` service setup: https://github.com/wunderio/drupal7-project/blob/master/.lando.yml#L8-L16

**Tell us about the command you were running**

Service's proxy is green after the build, but it gives before mentioned `ERR_INVALID_REDIRECT` error when trying use it (to log in to Adminer via UI).

Not sure if this is Lando's bug, but let's start here ;)

**Comment by tormi** [comment]
Downgraded Docker to `2.2.0.3`, but no change. So it could be related to latest changes in Lando. @dustinleblanc pointed out in Slack that #1824 seems the most likely candidate.

**Comment by tormi** [comment]
Seems like `portforward` needs some more Lando secret sauce to work with `compose` services :) . Got it working by using Docker Compose syntax for ports:

```
    ports:
      - "8080:8080"
```

And the new _adminer_ setup:

```
services:
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: /bin/s6-svscan /etc/services.d
    ports:
      - "8080:8080"
    depends_on:
      - database
proxy:
  adminer:
    - adminer.lndo.site
```
