### ISSUE TITLE
Set static port for PHPMyAdmin service for hostname proxy

### ISSUE THREAD

**Issue by raddevon** [lando/lando#2163]
Not sure if I'm not doing this right or if there is a problem here. I'd like to proxy a hostname to my PHPMyAdmin service, but I'm having trouble getting it to work.

I noticed when I run `lando start`, my PMA service's port is different every time. I think Docker Compose does this if you don't specify the host port to map to the exposed container port. I believe the port exposed on the container is 80, so I tried an override on the service to map a local port to that container port. Here's my .lando.yml:

```yaml
name: vrc
recipe: wordpress
config:
  webroot: wordpress
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
    overrides:
      ports:
        - '81:80'
proxy:
  pma:
    - pma.lndo.site:81
```

In spite of this, `lando start` still reports back the localhost URL for the service with an ephemeral port number. The hostname does not work (give me "Bad Gateway") unless I also use the ephemeral port number with it.

`docker container ls` shows that the container is up but that my port override doesn't seem to be working.

```
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                   PORTS                                                                                       NAMES
2ef2c3d2b845        phpmyadmin/phpmyadmin:5.0.2          "/lando-entrypoint.s…"   18 hours ago        Up 3 minutes             0.0.0.0:33156->80/tcp, 0.0.0.0:3005->3306/tcp
```

I found issue #2055 which seemed to suggest I could use a proxy without setting a static port, but that only works if I include the port number when referencing the hostname.

Am I doing the override to set the ports incorrectly, or is it just not working? Am I taking the wrong approach altogether?

**Comment by pirog** [comment]
@raddevon as far as i know something like this should work

```yaml
name: vrc
recipe: wordpress
config:
  webroot: wordpress
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
proxy:
  pma:
    - pma.lndo.site
```
