### ISSUE TITLE
Document inability to override arrays in landofiles

### ISSUE THREAD

**Issue by jdleonard** [lando/lando#2165]
Please complete the following:

**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/config/lando.html

**Describe the change you'd like**
It would be helpful for any limitations to the ability to override landofiles to be spelled out. For example, if I have this in lando.yml:
```yml
services:
  appserver:
    run:
      - command1
      - command2
```
and this in lando.local.yml:
```yml
services:
  appserver:
    run:
      - command3
      - command4
```

I would expect only command3 and command4 to run, but all four commands are running. 

@dustinleblanc said 
> I think we’re using _.merge to merge the data objects together, and I bet it just concats arrays

I'm not sure whether this is a bug or a documentation need.
