### ISSUE TITLE
Can no longer override core commands

### ISSUE THREAD

**Issue by dalin-** [lando/lando#2166]
**Tell us about your setup**

v3.0.0-rrc.3 on OSX 10.15.3

**Tell us about your `.lando.yml`**

```yml
name: some-site
recipe: pantheon
config:
  framework: drupal
  env: dev
  site: some-site
  id: some-uuid
services:
  appserver:
    install_dependencies_as_me:
      - /app/private/lando/lando-install-drush-make-sync
    run:
      - ln -fs ../../private/lando/git-push-hook .git/hooks/pre-push
  backstopserver:
    type: 'node:10'
    overrides:
      image: 'backstopjs/backstopjs:4.0.6'
tooling:
  some-site-db-pull:
    service: appserver
    description: |
      Import the some-site database from a Pantheon environment into Lando.  E.g.
        lando some-site-db-pull test
      Uses an SSH tunnel to work with the extra encryption that Pantheon has
      set up for this site. Works with multi-devs too.
      Avoid importing from the live environment.
      If this doesn't work, try
        lando ssh
        ./private/lando/pantheon-db-dump-wrapper dev
      If this doesn't work, try
        https://github.com/Advomatic/pantheon-tools#pantheon-db-dump
    cmd:
      - /app/private/lando/pantheon-db-dump-wrapper
  some-site-db-cli:
    service: appserver
    description: |
      Access the database from a Pantheon environment.  E.g.
        lando some-site-db-cli my-multi-dev
      Uses an SSH tunnel to work with the extra encryption that Pantheon has
      set up for some-site. Works with multi-devs too.
      Avoid connecting to the live database.
    cmd:
      - /app/private/lando/pantheon-db-cli some-site-d7
  pull:
    cmd:
      - "echo 'Instead use `lando some-site-db-pull <environment>` to pull a database, `git pull` to pull code, and Stage File Proxy for files.'"
  backstop:
    service: backstopserver
    description: |
      Run BackstopJS for visual regression testing.  E.g.
        lando backstop test
      See tests/backstop/README.md for more info.
    cmd:
      - >-
        cd /app/tests/backstop && backstop
        --config=/app/tests/backstop/backstop-local.json
  drush-make-sync:
    service: appserver
    description: >-
      Run Drush Make Sync to confirm that all files in the repo are supposed to
      be there.
    cmd:
      - /app/private/lando/lando-run-drush-make-sync

```

**Tell us about the command you were running**

This Pantheon site has special requirements for how to pull down a DB.  The config above overrides `lando pull` to instead print out some help text.  This used to work, but no longer in recent Lando builds. 

*Example:*

```bash
✦ ➜ lando pull
? Choose a Pantheon account (Use arrow keys)
❯ me@example.com
```

instead it should be

```bash
✦ ➜ lando pull
Instead use `lando some-site-db-pull <environment>` to pull a database, `git pull` to pull code, and Stage File Proxy for files.'
```

**Comment by pirog** [comment]
@dalin- i can sort of replicate this. seems to work as expected for some commands but not others. not completely sure why.

**Comment by pirog** [comment]
Ok so i think this works as expected but there were a few things that made it a bit weird. One of them we can improve on the lando site, the other we cannot.

**1. Options**

```yaml
tooling:
  pull:
    cmd: echo "hello"
    description: HI
```

The reason why it **appears** your command is not being overridden is because the pull commands non-interactive options are showing up. If you actually go through the options it will run the `cmd` when you are done. You can get around this by also overriding the options

```yaml
tooling:
  pull:
    cmd: echo "hello"
    description: HI
    options: 
```
2. post-pull

Lando's Pantheon recipe
