### ISSUE TITLE
Connect to appserver container with SSH (without cli)

### ISSUE THREAD

**Issue by Bouhnosaure** [lando/lando#2188]
Hi !

Thanks you for this project, i use it with Laravel every day on Fedora since I've left Windows and Laragon.

My question is about connecting with ssh into the appserver without the lando CLI because i use Tinkerwell and it has remote support with ssh.

Since i don't want to install PHP on my local machine just for this it could be great to have a guide how to use ssh without the CLI.

Also I've noticed that my keys had been imported into the container so i might not be far from being able to connect with the container.

![78649038-2994ef80-78bd-11ea-992f-2dbc65bb2c16](https://user-images.githubusercontent.com/3416579/80367768-f0ccb280-888b-11ea-9825-86fe4dc9ad2d.png)

And here is a copy of my .lando.yml

```yaml
name: back-end
recipe: laravel
config:
  webroot: public
  php: '7.4'
  via: apache
  database: mysql:5.7
  cache: redis
  xdebug: false
services:
  appserver:
    ports:
      - "22:22" <---- I've tried this but this port is commented in sshd_config on appserver
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    portforward: 1025
  node:
    type: node
  gotenberg:
    type: compose
    services:
      image: thecodingmachine/gotenberg:6
      command: gotenberg
      ports:
        - "3000:3000"
tooling:
  node:
    service: node
  npm:
    service: node
  yarn:
    service: node
proxy:
  phpmyadmin:
    - phpmyadmin.lndo.site
  mailhog:
    - mailhog.lndo.site
  gotenberg:
    - gotenberg.lndo.site
```
