### ISSUE TITLE
Can't build a drupal8 recipe having mysql:8.0

### ISSUE THREAD

**Issue by introfini** [lando/lando#2191]
I'm on v3.0.0-rrc.5.

**The error:** 

`ERROR: for database  Cannot create container for service database: invalid mode: /opt/bitnami/mysql/conf/my_custom.cnf`

**My .lando.yml:**
```yml
name: iupki
recipe: drupal8
config:
  webroot: htdocs
  xdebug: false
  config:
    php: .lando.php.ini
    database: mysql:8.0
#proxy:
#  mailhog:
#    - mail.origensbio.lndo.site
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    build_as_root:
      - apt-get update -y && apt install ffmpeg -y
#  mailhog:
#    type: mailhog
#    hogfrom:
#      - appserver
tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root
```

**Comment by pirog** [comment]
@introfini i cannot replicate this manually.  We also test a similar configuration in our automated functional tests. As a sanity check I would recommend trying to manually run through that test and see if you end up with the same result:
https://github.com/lando/lando/tree/master/examples/drupal8

Note that if you change database type or major version you _may_ need to `lando destroy && lando start` instead of the usual `lando rebuild`
https://docs.lando.dev/help/switching-dbs.html#switching-database-configuration

**Comment by introfini** [comment]
@pirog running manually the tests everything worked. But when I'm using a .lando.yml file it didn't, I've tried it in different existing projects. 

**Anyway, It works when I add a custom MySQL config file:**

```yml
name: iupki
recipe: drupal8
config:
  webroot: htdocs
  xdebug: false
  config:
    php: .lando.php.ini
    drush: 10.2.1
services:
  database:
    type: mysql:8.0
    config:
      database: .lando.mysql.cnf
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
```
**.lando.mysql.cnf**

```ini
[mysqld]
default_authentication_plugin=mysql_native_password
```
