### ISSUE TITLE
Really unclear on how proxies and ports work

### ISSUE THREAD

**Issue by CrashyBang** [lando/lando#2193]
Please complete the following:

**Link to the page that needs to be updated or changed.**

https://docs.lando.dev/config/proxy.html#proxy
https://docs.lando.dev/config/services.html#localhost-assignment

**Describe the change you'd like**

I just think it is a sever lack of understanding on my part despite reading the docs with a fine tooth comb 🤣 however there could be a bug or two in here muddying my understanding.

There are a range of config options that I can not get my head around and I found the docs didn't accurately outline how they are intended to function, these config options are:

- `proxy`
- `port` (`node` specific)
- `ssl`
- `scanner`
- `overrides` (this one is relatively clear I just think there are some caveats)
- `moreHttpPorts`

I have included my config below as well as my accompanying deductions about how these config options work.

Provided my understanding of these options is correct I would like to work towards improving there documentation as a whole as well as individually.

<details>
 <summary>My configuration file</summary>

```yml
name: portfolio

proxy:
  server:
    - portfolio.lndo.site:5000

services:
  server:
    type: node
    # port: 5000
    ssl: true
    # scanner: false
    # Livereload port
    moreHttpPorts:
     - '35729'
    overrides:
      ports:
       - '35729:35729'
    run_as_root:
     - chown node -R /certs

tooling:
  npm:
    service: server
  node:
    service: server
```
</details>

And this currently gives the following output when starting up:

```
 SERVER URLS  http://localhost:35729
              https://localhost:32797
              http://portfolio.lndo.site/
              https://portfolio.lndo.site/
```

Now from toggling things on and off here is what I get:

- `proxy` seems to work as expected and the `portfolio.lndo.site` URL's work perfectly when using it, however when I tried to remove the `proxy` and use `port: 5000` the website no longer renders, despite the fact that `port` seems to be specifically enabled to help with `node` apps running on strange ports
- Enabling `ssl: true` creates a URL with a **random port** every time I rebuild, in this case `https://localhost:32797` and logs it to the console
- `scanner: false` does not disable the URL with the **random port** from `ssl: true` which based on it's description I thought it would have
- `overrides` maps the port to my host machine without actually adding anything to the console (that is to say that `overrides` works without `moreHttpPorts` but you get no output in the console)
- `moreHttpPorts` simply seems to log ports to the console on startup but doesn't actually work without the `overrides` block.
- The URL's logged out by `moreHttpPorts` can actually be `https` or `http` so perhaps both should be logged?

If the above is correct or even partially correct it was the result of much commenting lines on and off in an attempt to distil how they operate together, I believe this could be better documented.

**Comment by chopfitzroy** [comment]
Still relevant to myself and potentially other people (given reactions), would still be interested in helping to resolve this one.

**Comment by roberttolton** [comment]
Replying in a relevant open thread instead of creating a new one, as I'm facing this same issue.

I can second that the documentation seems to assume a lot, or just generally is lacking examples for some situations.

I'm currently just trying to run a Webpack dev server on port 35729 inside a `node` service and have it be accessible on my machine, but it is proving to be very hard work.

My closest config is this:

```
services:
  node:
    type: node:14
    ssl: false
    moreHttpPorts:
      - '35729'
    overrides:
      ports:
        - '35729:35729'
    build:
      - npm install
 
proxy:
  node:
    - roberttolton-node.lndo.site:5000
```

And this gives me the console output:

```
 NODE URLS             http://localhost:35729
                       http://roberttolton-node.lndo.site/
```

I then run `lando npm run dev` to start my server, and it correctly boots and uses port `35729` as it's told to.
So at this point it looks like everything lines-up, but all I get via the proxy is a `BAD GATEWAY` error and that's it..!

**Comment by roberttolton** [comment]
Finally managed to get it working by starting my Webpack dev server on host `0.0.0.0` port `80` and with this config:

```
services:
  node:
    type: node:14
    ssl: false
    build:
      - npm install
    overrides:
      ports:
        - '8081:80'
tooling:
  npm:
    service: node
  node:
    service: node
proxy:
  node:
    - roberttolton-node.lndo.site:80
```

I can now successfully load my manifest at `http://roberttolton-node.lndo.site/manifest-legacy.json` on my host, and inside the container.
