### ISSUE TITLE
Update browsersync/gulp guide to set ssl: true on node service.

### ISSUE THREAD

**Issue by serundeputy** [lando/lando#2194]
Inroducding traffic2 changed how ssl certs are issued and we need to explicitly say that we want them for the services.

For https://docs.lando.dev/guides/how-to-wire-up-browsersync-and-gulp-in-my-lando-app.html#configuring-gulp-to-push-scss we'll need to update the Guide to request an ssl cert for the node service.

i.e. add in `ssl: true` in the `.lando.yml`:

```yaml
services:
  node:
    ssl: true
    type: node
    command: cd /app/path/to/gulpfile && node_modules/.bin/gulp watch
```
