### ISSUE TITLE
Docs: Example how to install `oci8` php extension

### ISSUE THREAD

**Issue by hexblot** [lando/lando#2201]
This example of build steps can help developers to install Oracle OCI8 extension easily, now that Oracle allows direct download. These extensions are required when PHP application needs a connection to Oracle databases.

This is similar to the SQL Server threads:
https://github.com/lando/lando/issues/1796
https://github.com/lando/lando/pull/1795

Mostly following the items in the [official Oracle documentation](https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html#ic_x64_inst)

This has been tested with rrc3 and default php7.2 via apache2.4 .

````yaml
services:
  appserver:
    build_as_root:
      - mkdir /opt/oracle
      # Fetch binaries directly from Oracle (!)
      - curl https://download.oracle.com/otn_software/linux/instantclient/19600/instantclient-basic-linux.x64-19.6.0.0.0dbru.zip > /opt/oracle/instantclient-basic.zip
      - curl https://download.oracle.com/otn_software/linux/instantclient/19600/instantclient-sdk-linux.x64-19.6.0.0.0dbru.zip > /opt/oracle/instantclient-sdk.zip
      # Unzip and delete
      - unzip /opt/oracle/instantclient-basic.zip -d /opt/oracle
      - unzip /opt/oracle/instantclient-sdk.zip -d /opt/oracle
      - rm /opt/oracle/instantclient-basic.zip
      - rm /opt/oracle/instantclient-sdk.zip
      # Make OS aware of newly installed libraries
      - echo /opt/oracle/instantclient_19_6 > /etc/ld.so.conf.d/oracle-instantclient.conf
      - ldconfig -v
      # Install and enable OCI8
      - echo "instantclient,/opt/oracle/instantclient_19_6" | pecl install oci8
      - docker-php-ext-enable oci8
````
