### ISSUE TITLE
Unable to load a custom php.ini configuration with laravel recipes

### ISSUE THREAD

**Issue by francesco-taioli** [lando/lando#2223]
Hi, sorry for the question but i cannot load a custom php.ini conf with laravel recipes.
I want to change the upload_max_filesize

**This is the structure of the app**
--.lando.yml
--app
&nbsp;&nbsp;&nbsp;&nbsp;-- app
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- controller
&nbsp;&nbsp;&nbsp;&nbsp;-- public 
&nbsp;&nbsp;&nbsp;&nbsp;-- routes
&nbsp;&nbsp;&nbsp;&nbsp;--other folder
&nbsp;&nbsp;&nbsp;&nbsp;-- php.ini
   
**This is my .lando.yml**
```
name: myapp
recipe: laravel
services:
  database:
    portforward: 3307
    type: mysql:5.7.28
config:
  php: 7.4
  conf:
    php: app/php.ini
  webroot: app/public
```

**This is my conf**
```
upload_max_filesize = 410M
post_max_size = 410M

```
I've try to 

-  `php: absoluteLocationTo/php.ini`

-  `php: php.ini` and put the php.ini in the same folder as lando.yml

If i enter with lando ssh, and then `php -i | grep 'upload_max_filesize'` it show always 100M.

For trying to fix the configuration, i tried to put php.ini in other various location, but it didn't work.
Can you guys help me?

**Comment by pirog** [comment]
The documentation says the key is called `config` not `conf`

```
name: myapp
recipe: laravel
services:
  database:
    portforward: 3307
    type: mysql:5.7.28
config:
  php: 7.4
  config:
    php: app/php.ini
  webroot: app/public
```

**Comment by francesco-taioli** [comment]
> The documentation says the key is called `config` not `conf`
> 
> ```
> name: myapp
> recipe: laravel
> services:
>   database:
>     portforward: 3307
>     type: mysql:5.7.28
> config:
>   php: 7.4
>   config:
>     php: app/php.ini
>   webroot: app/public
> ```

this was the issue.
If i could ask, why lando in the rebuild stage doesn't let me know that conf doesn't exist? or it exists but with another usage?

**Comment by pirog** [comment]
Because lando didn’t have a stable api until yesterday

**Comment by Rufus13apostol** [comment]
Hi all,

I´m afraid that I´m encountering the same problem, with wordpress recipe. Here is the .yaml:
```
name: standalone
recipe: wordpress
config:
  php: "7.4"
  via: apache
  webroot: .
  xdebug: true
  config:
    php: config/php.ini
```

It create a directory named "php.ini", but not the file. If I create the file, it does not load it. It does not show it on phpinfo or in the terminal, if I try to load some values there, it does not work...whatm Im doing wrong?

Thanks in advanced

**Comment by Rufus13apostol** [comment]
I fixed it. I don´t lnow why, but changing the php,ini file name did the trick:

This does not work:
```
name: standalone
recipe: wordpress
config:
  php: "7.4"
  via: apache
  webroot: .
  xdebug: true
  config:
    php: config/php.ini
```


This does:
```
name: standalone
recipe: wordpress
config:
  php: "7.4"
  via: apache
  webroot: .
  xdebug: true
  config:
    php: config/custom_php.ini
```
