### ISSUE TITLE
WebP support for Pantheon recipe to match Pantheon PaaS

### ISSUE THREAD

**Issue by dalin-** [lando/lando#2230]
Currently:

Pantheon:
* PHP GD - no WebP support
* ImageMagick - yes WebP support

Lando Pantheon recipe:
* PHP GD - yes WebP support
* ImageMagick - no WebP support
🙃

It would be great if Lando Pantheon's ImageMagick supported WebP so that we could just use one setup everywhere.  

Currently we work around this by:

```yml
  appserver:
    build_as_root:
      - ./installwebp.sh
```

and

```sh
#!/bin/bash

apt-get update
apt-get --yes install webp
```
