### ISSUE TITLE
Choosing no when overwriting a database export with a custom name results in a message saying that the file was created.

### ISSUE THREAD

**Issue by kcolwell** [lando/lando#2231]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

* Lando v3.0.0-rrc.3 on Mac 10.15.4*

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

```
name: red8
env_file:
  - defaults.env
recipe: drupal8
config:
  webroot: drupal/web
  php: '7.1'  
services:
  frontend:
    type: node
    build_as_root:
      - cd app/frontend_react && npm install
    port: 3000 
    ssl: 3001    
    command: npm start --prefix app/frontend_react      
  backend:
    type: node
    globals:
      nodemon: latest    
    build_as_root:
      - cd /app/app/backend_express && npm install
    port: 8080
    ssl: 8081    
    command: cd /app/app/backend_express && nodemon server.js   
  d7_db:
    type: mysql
    creds:
      user: d7_db
      password: d7_db
      database: d7_db
    config:
      database: 'drupal7/config/mysql.cnf'      
  d7:
    type: php:7.1
    via: apache:2.4
    webroot: drupal7/web
    config:
      vhosts: drupal7/config/vhost_default.conf
proxy:
  frontend:
    - react.lndo.site:3000
  backend:
    - express.lndo.site:8080  
  d7:
    - d7.lndo.site
tooling:
  npm:
    service: frontend
  node:
    service: backend
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

```
lando db-export -h database drupal8.sql     
Preparing to export /app/drupal8.sql from database 'drupal8' on service 'database' as user root...
gzip: /app/drupal8.sql.gz already exists; do you wish to overwrite (y or n)? n
	not overwritten
Success /app/drupal8.sql.gz was created!
```

**Tell us about the error you got**

Two messages:
not overwritten
Success /app/drupal8.sql.gz was created!

**Tell us generally about your bug**

Choosing no when overwriting a database export with a custom name results in a message saying that the file was "not overwritten" and "Success the file was created."
