### ISSUE TITLE
HTTPS Proxy missing after upgrade to v3.0.1

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#2233]
**Tell us about your setup**

What is your lando version and operating system? 

* Ubuntu Focal LTS (20.04)
* Lando 3.0.1

**Tell us about your `.lando.yml`**

```yml
####
# Compatibility: Lando 3.0.0 RC 13
###

name: business-api
recipe: laravel

proxy:
  appserver_nginx:
    - api-business.lndo.site
  node: # For Laravel's BrowserSync -- Not available until `lando yarn watch` is launched
    - api-watch-business.lndo.site:3000

config:
  php: '7.3'
  via: nginx
  webroot: public
  database: mariadb
  cache: redis
  xdebug: false

services:
  node:
    type: node:11
    globals:
      gulp-cli: latest
    port: 3000 # For Laravel's BrowserSync

tooling:
  redis-cli:
    service: cache
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
```
**Tell us about the command you were running**

1. Install lando-v3.0.0-rrc.3.deb
2. ```bash
    lando start
    # Start Lando BrowserSync
    lando yarn watch
    (curl -LI https://api-watch-business.lndo.site/ -o /dev/null -w '%{http_code}\n' -s | grep 200) && echo OK
   # Output: "OK"
    lando stop
    ```
3. Install lando-v3.0.1.deb
2. ```bash
    lando rebuild -y
    # Start Lando BrowserSync
    lando yarn watch
    (curl -LI https://api-watch-business.lndo.site/ -o /dev/null -w '%{http_code}\n' -s | grep 404) && echo "Could not load api-watch-business.lndo.site"
   # Output: "Could not load api-watch-business.lndo.site"
    ```

**Tell us about the error you got**

Lando returns a 404 when attempting to access the HTTPS version of the proxy in Lando v3.0.1

**Tell us generally about your bug**

My landofile has a proxy configured for the node service. At Lando start, the BrowserSync process is not running and therefore I expect to see a 404 at https://api-watch-business.lndo.site. On `lando yarn watch` I expect to see my website rendered.

This works as expected in v3.0.0-rrc.3.

It does not work as expected in v3.0.1
