### ISSUE TITLE
Getting MySQL access denied with minimal Drupal 8 multisite setup

### ISSUE THREAD

**Issue by raymondcheung** [lando/lando#2254]
I went through the documentation on drupal8 recipe and looked at [#433](https://github.com/lando/lando/issues/433) about setting up a multisite recipe.  I've created a very minimal setup with my existing Drupal 8 multisite project, but I am getting an access denied error from the MySQL service when trying to access any of the sites:

Error:
```
array(8) { ["driver"]=> string(5) "mysql" ["database"]=> string(7) "drupal8" ["username"]=> string(7) "drupal8" ["password"]=> string(7) "drupal8" ["prefix"]=> array(1) { ["default"]=> string(0) "" } ["port"]=> int(3306) ["host"]=> string(15) "cannabudexpress" ["pdo"]=> array(5) { [3]=> int(2) [1000]=> bool(true) [1005]=> bool(true) [20]=> bool(true) [1013]=> bool(false) } } The website encountered an unexpected error. Please try again later.
Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'drupal8'@'172.24.0.2' (using password: YES) in Drupal\Core\Database\Driver\mysql\Connection::open() (line 424 of /app/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php).
Drupal\Core\Database\Driver\mysql\Connection::open(Array) (Line: 371)
Drupal\Core\Database\Database::openConnection('default', 'default') (Line: 166)
Drupal\Core\Database\Database::getConnection('default')
call_user_func_array('Drupal\Core\Database\Database::getConnection', Array) (Line: 79)
Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database') (Line: 173)
Drupal\Component\DependencyInjection\Container->get('database', 1) (Line: 212)
Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array) (Line: 62)
Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container') (Line: 173)
Drupal\Component\DependencyInjection\Container->get('cache.container') (Line: 544)
Drupal\Core\DrupalKernel->getCachedContainerDefinition() (Line: 910)
Drupal\Core\DrupalKernel->initializeContainer() (Line: 477)
Drupal\Core\DrupalKernel->boot() (Line: 707)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

Here is my .lando.yml:

```
name: my-lando-app
recipe: drupal8
config:
  webroot: web
  config:
    database: .lando.mysql.cnf
proxy:
  appserver:
    - cannabudexpress.com
    - default.com
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  default:
    type: mysql:8.0
    portforward: true
    config:
      confd: .lando.mysql.cnf
  cannabudexpress:
    type: mysql:8.0
    portforward: true
    config:
      confd: .lando.mysql.cnf
```

and relevant portion of my webroot/sites/cannabudexpress/settings.local.php:
```

/**
 * Database configuration.
 */
$databases['default'] = array (
  'default' => array (
    'driver' => 'mysql',
    'database' => 'drupal8',
    'username' => 'drupal8',
    'password' => 'drupal8',
    'prefix' => '',
    'port' => 3306,
 )
);
$databases['default']['default']['host'] = 'cannabudexpress';
```

.lando.mysql.cnf
```
[mysqld]
default-authentication-plugin=mysql_native_password
```
I have done a `lando db-import` to import my existing database dumps.  I've checked out the database and confirmed that the username and password are both "drupal8", and password hashing set to: "Native MySQL authentrication".  I've tried changing the password hashing to SHA256 but that didn't have any effect.  Any help figuring this out would be greatly appreciated.
