### ISSUE TITLE
db-import unable to chown dump file

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#2255]
## System specs
Confirmed on two machines:
1. `Linux DESKTOP-AKIHMQ9 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux` (WSL 2 with Ubuntu 20.04)
2. `Linux localhost.localdomain 5.6.11-300.fc32.x86_64` (Fedora 32)

## Lando Version
Both machines just installed v3.0.2

## Example Output
```
Creating gzipped SQL dump file: /app/dump.sql.gz
chown: changing ownership of '/app/dump.sql.gz': Operation not permitted
```

```
$ lando db-import dump.sql
chown: changing ownership of '/app/dump.sql': Operation not permitted
```
seems related to #2170 and https://github.com/lando/lando/commit/5f78ccefab569660ef7b50d9339ba473fd3eb6f7#diff-1ef7c056e1ac254429dcc2e637e2f87aR66

**Comment by fyaconiello** [comment]
```
name: lcldnet
proxy:
    appserver:
        - lcldnet.lndo.site
services:
  appserver:
    type: python:3.7
    command: sh /app/docker-entrypoint.sh
    ports:
    - '80'
    environment:
    - DJANGO_SETTINGS_MODULE=lcldnet.settings.lando
  # database layer
  database:
    type: mariadb
    portforward: true
    creds:
      user: user
      password: password
      database: database
    config:
      database: .lando/config/mariadb/my.cnf
  # Spin up a node tooling service layer
  node:
    type: node:custom
    ssl: true
    overrides:
      ports:
        # expose port 3000 for BrowserSync
        - "3000"
      # use a custom Docker image
      image: colab/buildtools:node-8

# Additional "lando" commands
tooling:
  npm:
    service: node
  yarn:
    service: node
  node:
    service: node
  gulp:
    service: node
  google-chrome-stable:
    service: node
  pipinstall:
      service: app
      cmd: pipenv install --clear --verbose
  backstop:
    service: node
  'db-import <file>':
    service: :host
    description: Imports a dump file into a database service
    cmd: /helpers/sql-import.sh
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
      no-wipe:
        description: Do not destroy the existing database before an import
        boolean: true
```

**Comment by pirog** [comment]
@fyaconiello we were able to track this down, `db-import` is supposed to run as root now, which is fine if you use the version that comes with the `lamp` recipe but is a problem for people who have defined it themselves. 

We are going to put together a fix that is more backwards compatible, but in the meantime you can probably do this as a workaround:

```yaml
  'db-import <file>':
    service: :host
    description: Imports a dump file into a database service
    cmd: /helpers/sql-import.sh
    user: root
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
      no-wipe:
        description: Do not destroy the existing database before an import
        boolean: true
```

Note the `user: root` addition
