### ISSUE TITLE
[v3.0.2] Host permissions change after lando rebuild

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#2260]
My `~/.ssh` files change from 600 to 700 after a `lando rebuild`.  Basic wordpress recipe with no build steps.  See below:
Before:
```
ed@dell-precision-m6700 ~/.ssh $ ls -la
total 532
drwx------   2 ed ed   4096 May 14 21:16 .
drwxr-xr-x 127 ed ed  12288 May 14 22:01 ..
-rw-------   1 ed ed   5266 May 14 15:21 config
-rw-------   1 ed ed    116 Jul 30  2016 credentials
-rw-------   1 ed ed   3243 Feb 18 10:34 id_rsa
-rw-------   1 ed ed    741 Feb 18 10:34 id_rsa.pub
```
After:
```
ed@dell-precision-m6700 ~/.ssh $ ls -la
total 532
drwx------   2 ed ed   4096 May 14 21:16 .
drwxr-xr-x 127 ed ed  12288 May 14 22:01 ..
-rwx------   1 ed ed   5266 May 14 15:21 config
-rwx------   1 ed ed    116 Jul 30  2016 credentials
-rwx------   1 ed ed   3243 Feb 18 10:34 id_rsa
-rw-------   1 ed ed    741 Feb 18 10:34 id_rsa.pub
```
Notice `id_rsa.pub` has not been affected.

Contents of `.lando.yml`:
```yaml
name: mysite                                                                                                                                                                               
recipe: wordpress                                                                                                                                                                            
config:                                                                                                                                                                                      
  webroot: .                                                                                                                                                                                 
  php: 7.2
```
System specs:
```
$ lando version
v3.0.2
$ lsb_release -a
No LSB modules are available.
Distributor ID: MX
Description:    MX 18.3 Continuum
Release:        18.3
Codename:       Continuum
$ uname -a
Linux dell-precision-m6700 4.19.0-5-amd64 #1 SMP Debian 4.19.37-2~mx17+1 (2019-05-15) x86_64 GNU/Linux
$ docker -v
Docker version 19.03.8, build afacb8b7f0
$ docker-compose -v
docker-compose version 1.25.1, build a82fef07
$ node -v
v12.16.3
$ yarn -v
1.22.4
```
