### ISSUE TITLE
Drupal 8 Nginx blocks `/.well-known` routes, works on Apache

### ISSUE THREAD

**Issue by dwkitchen** [lando/lando#2272]
```
recipe: drupal8
config:
  webroot: web
  php: '7.2'
  via: apache
  database: mariadb:10.1
  drush: ^10
```
`.well-known/openid-jwks` works with openid_connect_autodiscovery module

```
recipe: drupal8
config:
  webroot: web
  php: '7.2'
  via: nginx
  database: mariadb:10.1
  drush: ^10
```
`.well-known/openid-jwks` if 404 file not found Nginx responce
