### ISSUE TITLE
Pantheon nginx config doesn't work with jsonapi

### ISSUE THREAD

**Issue by void--** [lando/lando#2276]
**Tell us about your setup**

Running lando v3.0.1 on macOS Catalina v10.15.4

**Tell us about your `.lando.yml`**

```yml
name: test
recipe: pantheon
config:
  framework: drupal
  site: test
  id: [redacted]
```

**Tell us generally about your bug**

Tried to use jsonapi w/ pantheon recipe, got the following error (from jsonapi): "The following query parameters violate the JSON:API spec: 'q'."

Found the following issue, and was able to resolve by overriding the vhosts config and applying the changes in the following comment: https://www.drupal.org/project/jsonapi/issues/2984044#comment-12981964 (comment 10)

To reproduce

```bash
1. Create new project with pantheon recipe
2. lando drush en jsonapi -y
3. visit sitename.lndo.site/jsonapi
4. observe 400 bad request error w/ the message mentioned above
```
