### ISSUE TITLE
Skip Scanning to determine which services are ready... Please standby... ?

### ISSUE THREAD

**Issue by web-assistant** [lando/lando#2281]
When starting Lando it all starts works fairly quickly apart from the last process when it says:

> Scanning to determine which services are ready... Please standby...

The site seems to work during this stage. Is this process necessary, can I skip this stage to allow me to start working on the command line?

**Comment by rabauss** [comment]
see: https://docs.lando.dev/config/services.html#service-url-scanning
what is your `.lando.yml`? because normally the service check should not take long time!

**Comment by web-assistant** [comment]
@rabauss Thanks. I might disable the scanner. It takes a good few minutes to complete. Could it be taking so long as they are Drupal sites with all the caching turned off?

My .lando.yml file is
```
name: thingymajig
recipe: drupal7
config:
  php: '7.2'
  via: apache
  webroot: web
  database: mariadb
  drush: ^8
  xdebug: false
  config:
    php: .lando/.lando.php.ini
    database: .lando/.lando.mysql.cnf
    server: .lando/httpd.conf
    vhosts: .lando/default.conf

proxy:
  appserver:
    - thingymajig.lndo.site
    - www.thingymajig.lndo.site
  mailhog:
    - mail.thingymajig.lndo.site
  pma:
    - pma.thingymajig.lndo.site
  adminer:
    - adminer.thingymajig.lndo.site

services:
  database:
    creds:
      database: thingymajig
      user: thingymabob
      password: easylike123
  appserver:
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
  pma:
    type: phpmyadmin
    hosts:
      - database
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: /bin/s6-svscan /etc/services.d
    portforward: true

tooling:
  xon:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xoff:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root

excludes:
  - .idea
  - .git
```

**Comment by web-assistant** [comment]
It's definitely the `appserver` service that's taking a long time. I added `scanner: false` just to that service and the scanning is finishes in a second. I'm happy with that now though, starting/rebuilding now is very fast.

```
services:
  appserver:
    scanner: false
        PHP_IDE_CONFIG: "serverName=appserver"
```

**Comment by gitressa** [comment]
I also get this, with one Solr port, where the first one in the list below is marked red. The others work well.

```
 SEARCH URLS     https://localhost:49216      
                 http://localhost:49215       
                 http://search.lndo.site/     
                 https://search.lndo.site/    
```
It's a huge relief to be able to skip the 30 seconds of looking at `Scanning to determine which services are ready... Please standby...`:

```
services:
  search:
    type: solr:7
    core: mycore
    portforward: true
    scanner: false
    ssl: true
    sslExpose: true
    config:
      dir: config/solr-conf/7.x/conf
```
