### ISSUE TITLE
Nginx reverse proxy error: host not found in upstream "appserver.clojureapp.internal"

### ISSUE THREAD

**Issue by acobster** [lando/lando#2303]
**Self-contained minimal repro steps are here:** https://github.com/acobster/lando-clojure-nginx-min

**Tell us about your setup**

* Lando v3.0.1
* Docker version 19.03.10, build 9424aeaee9
* Ubuntu 18.04

**Tell us about your `.lando.yml`**

```yml
name: clojure-app

services:
  appserver:
    type: compose

    services:
      image: acobster/lando-clojure:cli-tools
      command: clojure -m app

      # Removing this and the dbhost block below fixes the Nginx error???
      depends_on:
        - dbhost

  dbhost:
    type: postgres:11
    creds:
      database: rtc

  nginx:
    type: nginx:1.14
    webroot: resources/public
    ssl: true

    config:
      server: lando/nginx.conf

    overrides:
      depends_on:
        - appserver

proxy:
  nginx:
    - clojure-app.lndo.site
```

lando/nginx.conf:

```yml
events {

}

http {
  server {
    listen 80;
    server_name clojure-app.lndo.site;

    proxy_connect_timeout 600s;
    proxy_send_timeout 600s;
    proxy_read_timeout 600s;
    send_timeout 600s;

    # Nginx correctly serves index.html if I comment out this block:
    location / {
      proxy_pass http://appserver.clojureapp.internal:8080;
    }
    # ...and instead uncomment this block:
    # location / {
    #   root /app/public;
    #   index index.html;
    # }
  }
}
```

**Tell us about the command you were running**

```bash
lando start
lando logs -s nginx
```

I also tried:

```bash
lando poweroff
docker network prune
docker system prune
lando destroy -y
lando start
```

...and when that didn't work, I completely uninstalled Docker and Lando.

**Tell us about the error you got**

Looking at the nginx service logs, I see:

```
nginx_1      | INFO  ==> ** Starting NGINX setup **
nginx_1      | INFO  ==> Validating settings in NGINX_* env vars...
nginx_1      | INFO  ==> Initializing NGINX...
nginx_1      | DEBUG ==> Custom configuration detected. Using it...
nginx_1      | 
nginx_1      | INFO  ==> ** NGINX setup finished! **
nginx_1      | INFO  ==> ** Starting NGINX **
nginx_1      | 2020/05/29 21:29:28 [emerg] 176#0: host not found in upstream "appserver.clojureapp.internal" in /opt/bitnami/nginx/conf/nginx.conf:17
nginx_1      | nginx: [emerg] host not found in upstream "appserver.clojureapp.internal" in /opt/bitnami/nginx/conf/nginx.conf:17
```

**Tell us generally about your bug**

What's odd is that if I take steps that seemingly have only tangentially to do with the Nginx host itself, it starts partially "working." For example removing `dbhost` consistently allows the nginx service to detect the appserver internal host and start up correctly. Or if I remove the `proxy_pass` directive, Nginx starts up correctly and is subsequently able to connect to `appserver.clojureapp.internal:8080`. So it seems to have to do with the order in which the services are started, and how long they take before they can detect each other.

More details are in the repo linked above, along with precise steps for the partial "fixes."

For some additional context, in my actual project I was getting `container xxxxx is not connected to lando_bridge_network`, which brought me to [this Slack thread](https://devwithlando.slack.com/archives/C2XBSHX8R/p1584717516231000), hence the scorched earth approach above. That error turned out to be seemingly intermittent depending on some non-deterministic network internals, but what I do consistently get is the nginx "host not found" error.

**Please detail the steps we can take to replicate this bug. Be as detailed as possible.**

As linked above: https://github.com/acobster/lando-clojure-nginx-min
