### ISSUE TITLE
Drush aliases are created for wordpress_network sites

### ISSUE THREAD

**Issue by nullvariable** [lando/lando#2321]
Example config:
```
name: xxxxx
recipe: pantheon
config:
  framework: wordpress_network
  site: xxxxxxxxxxx
  id: xxxxxxxxxxxxxxxxx
```
In https://github.com/lando/lando/blob/master/plugins/lando-pantheon/scripts/pull.sh#L148-L152

the logic for drush aliases is only constrained to `wordpress` but there are a couple other framework types that are not drupal.
