### ISSUE TITLE
Proper Apache2 Custom Configuration Setup and Questions

### ISSUE THREAD

**Issue by shane-rand** [lando/lando#2341]
Hi,

I am struggling to get a custom apache2 configuration file to work on the wordpress recipe.

landofile:
```
name: 'dpl'
recipe: wordpress
config:
  php: '7.2'
  database: mysql:5.7
  webroot: 'www/personal-loans/resources'
  config:
    server: config/server.conf
```
I've been going through the Docs over and over but I seem to be missing some crucial piece somewhere? Does the configuration file need to be named `httpd.conf` or `apache2.conf`? Is my pathing wrong?

I've been checking `/etc/apache2/` for the existence of my custom config file but it doesn't seem to be there inside the appserver container. Am I looking in the wrong place?

Any help would be appreciated, thanks.

**Comment by gobinathm** [comment]
This would be an ideal way to provide a custom apache config. The service definition is missing on your lando file

```
name: 'dpl'
recipe: wordpress
config:
  php: '7.2'
  database: mysql:5.7
  webroot: 'www/personal-loans/resources'
  
services:
  appserver:
    config:
      server: config/server.conf
```

As far as I have done there is no mandate to use a specific file name for custom apache / mysql config.
