### ISSUE TITLE
Python dependencies do not install correctly for p.sh services

### ISSUE THREAD

**Issue by pirog** [lando/lando#2367]
This is easy enough to replicate.

1. `lando init` the `lando-d8` example
2. Modify the `.platform.app.yaml` to include the `python` dependencies suggested in the platform.sh docs eg

```yaml
dependencies:
  python: # Specify one Python 2 package per line.
    behave: '*'
  python2: # Specify one Python 2 package per line.
    requests: '*'
  python3: # Specify one Python 3 package per line.
    numpy: '*'
```

3. `lando start` or `lando rebuild` 

Best guess here is we need to make sure the python deps are installed somewhere writable by the `web` user that runs the build steps. This may be accomplished by modifying the python config, either by ENVVAR or other mechanism so it runs in a directory and by a user of our choosing
