### ISSUE TITLE
lando restart Stopping and restarting your app...Shiny! ERROR ==> Invalid Version: null 

### ISSUE THREAD

**Issue by renatog-cit** [lando/lando#2374]
Hello guys, how are you?

After upgrade for last version of lando (v3.0.5) I get this error on land start:

```
lando start
ERROR ==> Invalid Version: null message=Invalid Version: null, stack=TypeError: Invalid Version: null
    at new SemVer (/snapshot/lando/build/cli/node_modules/semver/classes/semver.js:22:13)
    at compare (/snapshot/lando/build/cli/node_modules/semver/functions/compare.js:3:3)
    at Object.gte (/snapshot/lando/build/cli/node_modules/semver/functions/gte.js:2:30)
    at new LandoDrupal (/snapshot/lando/build/cli/plugins/lando-recipes/types/drupaly/builder.js)
    at new LandoDrupal8 (/snapshot/lando/build/cli/plugins/lando-recipes/recipes/drupal8/builder.js)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-recipes/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js)
    at initAndReport (/snapshot/lando/build/cli/lib/app.js)
    at App.stop (/snapshot/lando/build/cli/lib/app.js)
    at App.restart (/snapshot/lando/build/cli/lib/app.js)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/restart.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, __stackCleaned__=true

██╗   ██╗██╗  ██╗     ██████╗ ██╗  ██╗██╗
██║   ██║██║  ██║    ██╔═══██╗██║  ██║██║
██║   ██║███████║    ██║   ██║███████║██║
██║   ██║██╔══██║    ██║   ██║██╔══██║╚═╝
╚██████╔╝██║  ██║    ╚██████╔╝██║  ██║██╗
 ╚═════╝ ╚═╝  ╚═╝     ╚═════╝ ╚═╝  ╚═╝╚═╝
                                         

An error occurred while starting up your app!
Here are a few things you can try to get back into a good state:

  ■ Try running lando rebuild
  ■ Try restarting in debug mode lando restart -vvv
  ■ Try checking the logs with lando logs

If those fail then consult the troubleshooting materials:

  ■ https://docs.lando.dev/help/logs.html
  ■ https://docs.lando.dev/help/updating.html

Or post your issue to Slack or GitHub

  ■ Slack - https://launchpass.com/devwithlando
  ■ GitHub - https://github.com/lando/lando/issues/new/choose

ERROR ==> Invalid Version: null 
```

Do you have any idea about how to solve this?

This is my .lando.yml file:

```
name: project

# Start with the default Drupal 8 recipe
recipe: drupal8

# Configure the Drupal8 recipe
config:
  php: 7.3
  via: apache
  webroot: docroot
  drush: "*"
  drupal: true
  ssl: true
  database: mariadb:10.1
  xdebug: true
services:
  appserver:
    build_as_root:
      # add a2enmod headers to enable mod_headers
      # for add in header "Access-Control-Allow-Origin" for specific json files
      - a2enmod headers
      - service apache2 reload
      - apt-get update && apt-get install -y imagemagick
      - docker-php-ext-install sysvsem && docker-php-ext-enable sysvsem
    build:
      # prestissimo is a composer plugin that downloads packages in parallel to speed up the installation process.
      - "composer global require hirak/prestissimo"
      - "composer install"
      - "vendor/squizlabs/php_codesniffer/bin/phpcs --config-set installed_paths /app/vendor/drupal/coder/coder_sniffer"
  # Mailhog
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  # Memcached
  memcached:
    type: memcached
    portforward: true
    run:
      - /bin/sh -c '/opt/bitnami/memcached/bin/memcached start -d'

  solr:
    type: solr:4.10
    portforward: true

tooling:
  drush:
    cmd: cd docroot/ && ../vendor/drush/drush/drush
    service: appserver
  drupal:
    service: appserver
    cmd: "/app/vendor/bin/drupal --root=/app/docroot"
  composer:
    service: appserver
    cmd: "/usr/local/bin/composer --working-dir=/app"
  phpcs:
    service: appserver
    cmd: "/app/vendor/squizlabs/php_codesniffer/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,info,txt,md"
    description: Run phpcs for given folder or file.
  phpcbf:
    service: appserver
    cmd: "/app/vendor/squizlabs/php_codesniffer/bin/phpcbf --standard=Drupal --extensions='php,module,inc,install,test,profile,theme,css,info,txt,md'"
    description: Run phpcbf for given folder or file.
  phpunit:
    service: appserver
    cmd: "/app/vendor/bin/phpunit "
    description: Run phpunit for given folder or file. i.e. lando phpunit --configuration myfileTest.php
  sync-database:
    description: Reset database on local machine.
    service: appserver
    stdout:
      description: Synchronizing the database...
  sync-files-br:
    description: Sync files on local
    service: appserver
    stdout:
      description: Synchronizing files ...
proxy:
  mailhog:
    - mailhog-project.lndo.site
```
