### ISSUE TITLE
Semantic drush version config does not work with lando v3.0.6

### ISSUE THREAD

**Issue by janadam** [lando/lando#2386]
Using latest drush 8 with latest 3.0.6 is not working.
My test recipe:
```
cat .lando.yml 
name: test
recipe: drupal8
config:
  php: '7.2'
  via: apache:2.4
  webroot: .
  database: mysql:5.7
  drush: ^8
```
Error when trying to run drush:
`OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec format error": unknown
`
I guess it was this change:
https://github.com/lando/lando/commit/997a7e44b9611d164c3e0a21f83d23d769d93635#diff-b79126f26284ff4ed6725c2d8a37fa83R47
