### ISSUE TITLE
Lando Pull dropping table gives ERROR 1451 (23000) a foreign key constraint fails

### ISSUE THREAD

**Issue by thetwopct** [lando/lando#2391]
I'm just upgraded from v3.0.0-rc.21 to v3.0.5.

On an older project, I've run `lando rebuild`. I've then run `lando pull --database=dev --files=dev --code=none --rsync` to pull in latest DB from Pantheon.

```
Destroying all current tables in database if needed... 
Dropping wp_shortpixel_folders table from lando database...
ERROR 1451 (23000) at line 1: Cannot delete or update a parent row: a foreign key constraint fails
```

Is there a way to turn off foreign key checks? Or force dropping table?

Possible related feature request - https://github.com/lando/lando/issues/1850

My yml file is nothing special

```
name: sitename
recipe: pantheon
config:
  framework: wordpress
  site: sitename
  id: XXXXXXX
keys:
  - sitename_rsa
```

My pantheon yml file much the same:

```
api_version: 1
web_docroot: true
php_version: 7.3
```

I would presume a way around this is to `lando destroy` the current site if the data isn't needed, but I wonder if I did need the database what steps would be required to solve this issue?
