### ISSUE TITLE
Changes required for xdebug when using lando with VPN (NordVPN)

### ISSUE THREAD

**Issue by drupov** [lando/lando#2396]
I have a general question: when using my normal internet connection, xdebug with PhpStorm works like a charm (see my setup below).

When I connect to NordVPN the setup does not get it, resulting in my xdebug session totallybeing ignored (same breakpoints do not stop at all).

My `.lando.yml`-file looks like this:

```
name: drupal8
recipe: drupal8
config:
  via: nginx
  php: '7.2'
  webroot: web
  xdebug: true
services:
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: 'serverName=appserver'
    config:
      php: php.ini
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/web
  drupal:
    service: appserver
    cmd: drupal --root=/app/web
```

What can be the cause here?
