### ISSUE TITLE
Add symlink to /code from /app for pantheon

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#2421]
As a lando user who writes behat tests on Pantheon, I want to be able to run the same drush commands from pantheon and lando.

For example:

`And I run drush "-y cim --partial --source=/code/config/behat-restore"` 

Lando uses `/app`; Pantheon uses `/code`. I want to write my tests so I only have to worry about one path, regardless of whether I'm testing on lando or pantheon.

**How to solve this in lando now:**

In `lando.yml`:
```

services:
  appserver:
    build_as_root:
      # Symlink app to code to match pantheon structure in order to run drush cim in behat.
      # Command is run from /app so symlink destination must use ../.
      - ln -s app/ ../code
```

**What would be more awesome**

If lando automatically created this automatically for Pantheon sites.
