### ISSUE TITLE
Implement !includes YAML tag for psh

### ISSUE THREAD

**Issue by pirog** [lando/lando#2445]
platform.sh implements two custom YAML tags: `!archive` and `!includes`. We have already implemented the `!archive` tag but we want to support the `!includes` tag as well. It is defined in the platform docs here: 
https://docs.platform.sh/configuration/yaml.html#includes

Note that there are three different `!includes` types: `yaml`, `string` and `binary` with `yaml` as the default.  

- [x] Support`string`
- [x] Support `binary`
- [x] Support `yaml` (as object)
- [x] Support `yaml` (as string)

Also note that the referenced file is always relative to the YAML file’s directory.

```yaml
# Load YAML by default
web:
    locations:
        '/': !include "main.yaml"

# Otherwise use the "type"
properties:
    favicon: !include
        type: binary
        path: favicon.ico
```

In order to implement the custom tag you should add it to the platform yaml module here
https://github.com/lando/lando/blob/master/experimental/plugins/lando-platformsh/lib/yaml.js
and make sure you add it to the array here
`this.PLATFORM_SCHEMA = yaml.Schema.create([this.ArchiveYamlType]);`

You may need to add an additional parameter to `load` for awareness of the "base" path that the `!includes` must be loaded relative to.

Once the flag is implemented we should add "implicit" tests to the `kitchensink` example. Implicit in this context means we should just use the `!includes` flag to load things required by other tests eg if we loaded a few services via include types `yaml` and `string` and the tests continue to pass then we should be good. 

Testing the `binary` type may be best done with an explicit test where we can just test the existing of the favicon and make sure its size is correct or some such.
