### ISSUE TITLE
mycli tooling command output format is broken, but works inside the box

### ISSUE THREAD

**Issue by mortona42** [lando/lando#2453]
I installed mycli, a nicer mysql client with autocomplete.

```yml
services:
  appserver:
    build_as_root:
      - apt update && apt install -y mycli
tooling:
  mycli:
    service: appserver
    description: mycli client
    cmd: mycli mysql://drupal8:drupal8@database/drupal8
```

Here's what it looks like after ssh'ing into the box and running it:
![Screenshot from 2020-07-06 10-54-44](https://user-images.githubusercontent.com/696005/86623904-3639ea00-bf77-11ea-9f78-eeb127fb6c0c.png)

When I run `lando mycli` the read line is below the screen. The output is printed, but the autocomplete and function bar at the bottom of the screen are missing.
