### ISSUE TITLE
Add docker-compose.override.yml merging to Lagoon integration

### ISSUE THREAD

**Issue by tobybellwood** [lando/lando#2454]
Adding the ability to read a docker-compose.override.yml to the docker-compose.yml file as read by Lando would easily allow a project to add the necessary Lando labels to an existing project

Given this docker-compose.override.yml - it would add the necessary labels to the services already in https://www.github.com/amazeeio/drupal-example, meaning that only it and .lando.yml need adding to the repo.
```
version: '2.3'

services:
  cli:
    labels:
      lando.type: php-cli
  nginx:
    labels:
      lando.type: nginx-drupal
  php:
    labels:
      lando.type: php-fpm
  mariadb:
    labels:
      lando.type: mariadb-drupal
  redis:
    labels:
      lando.type: redis
    ports:
      - "6379" # Find port on host with `docker-compose port redis 6379`
  solr:
    labels:
      lando.type: solr-drupal
```

From my quick look, js-yaml doesn't support merging YAML files, but there are other packages that provide this ability that should work with the rest of the stack.  Obviously the file shouldn't need to exist, but be read if it is.

Lagoon doesn't use the override functionality from docker-compose, so any changes to that file should be Lagoon-safe.  I'd also propose limiting the functionality to a named `docker-compose.override.yml` file (as per the docker-compose guidelines) - and leaving the other various permutations to more advanced users.
