### ISSUE TITLE
v3.0.7 does not recognize machine token for Pantheon

### ISSUE THREAD

**Issue by romerocs** [lando/lando#2458]
I upgraded from v3.0.5 to v3.0.7. Once I did that I was unable to run `lando pull` or `lando push` without getting an error saying I needed to generate a machine token. Reverting back to v3.0.5 fixed the issue.

**Environment**
v3.0.7 on Mac OS 10.15.5

**Lando config**
```yml
name: blog
recipe: pantheon
config:
  framework: wordpress
  site: blog
  id: 20cdce8f-ff7b-410a-9510-5b52c28c616b
```

<img width="844" alt="Screen Shot 2020-07-08 at 1 06 53 PM" src="https://user-images.githubusercontent.com/7998286/87052693-0e44c380-c1cf-11ea-9866-e01d7c7e8bcc.png">
