### ISSUE TITLE
Configure a PHP container to run a command on startup

### ISSUE THREAD

**Issue by alex-osborn** [lando/lando#2479]
I'm trying to set up a Laravel application to run inside Lando. All is going well apart from configuring queue workers.

A number of background workers are required for the application and should be launched when the containers are started, i.e.  `lando start`.

Workers are managed via [Laravel Horizon](https://laravel.com/docs/7.x/horizon), which provides a single command to spawn/run multiple workers:
    
    php artisan horizon

In production, we run Horizon using [Supervisor](http://supervisord.org/). This command will run until stopped, so isn't suitable to include in a run step.

What I'm not sure how to approach is how to trigger an initial command when the service starts, in other words just the same as the [command](https://docs.lando.dev/config/node.html#specifying-a-command) option allowed for the node service.

I've set up a tool to run Horizon but this doesn't feel like the correct approach as I need to a) run the command from the host after startup, b) keep a terminal window open running the command

1. Am I missing something obvious and this is supported but not documented?
2. Should I be trying to start a PHP container and run Horizon?
3. Should I be using a custom service/compose and installing Supervisor, and running in the same way as production?

Appreciate any input!

Landofile for reference:

```
name: trev
recipe: laravel
config:
  php: '7.4'
  webroot: src/public
  via: nginx
  database: mysql:5.7
  cache: redis
services:
  horizon:
    type: php:7.4
    via: cli
tooling:
  horizon:
    service: horizon
    cmd: php /app/src/artisan horizon
```

**Comment by pirog** [comment]
@alex-osborn this should either be very easy to add support for or is something that already works but is undocumented.

**Comment by pirog** [comment]
@alex-osborn we did not actually support this but was easy enough to add so it should be in the next release.

**Comment by dustinleblanc** [comment]
fwiw I had just been doing this for a long time:
```yml
  queue:
    type: php:7.3
    via: cli
    overrides:
      command: php artisan queue:listen --timeout=600
```

**Comment by pirog** [comment]
ahh nice, good call @dustinleblanc! totally forgot you could do that.... well at least we have an "easy button" for it now i guess.

**Comment by alex-osborn** [comment]
Awesome, thanks. Appreciate the quick responses!

**Comment by garrettw** [comment]
Was this not already possible with the following?
```yaml
services:
  appserver:
    run:
      - php src/artisan horizon
```
