### ISSUE TITLE
Segmentation fault during Platform.sh build

### ISSUE THREAD

**Issue by xaqrox** [lando/lando#2482]
**Tell us about your setup**

Lando v3.0.8 on MacOS 10.14.6

**Tell us about your `.lando.yml`**

.lando.yml
```yml
name: [MY PROJECT]
recipe: platformsh
config:
  id: [PLATFORM ID]
```

.platform.app.yaml (lightly adapted from https://github.com/platformsh-templates/drupal8/blob/f6f019f2e508c51456458f079db77be4601754d6/.platform.app.yaml)
```yml
# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: 'app'

# The runtime the application uses.
type: 'php:7.4'

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: 'db:mysql'
    redis: 'cache:redis'

# The size of the persistent disk of the application (in MB).
disk: 4056

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
    '/web/sites/default/files':
        source: local
        source_path: 'files'
    '/tmp':
        source: local
        source_path: 'tmp'
    '/private':
        source: local
        source_path: 'private'
    '/.drush':
        source: local
        source_path: 'drush'
    '/drush-backups':
        source: local
        source_path: 'drush-backups'
    '/.console':
        source: local
        source_path: 'console'

# Configuration of the build of this application.
build:
    flavor: composer

# The hooks executed at various points in the lifecycle of the application.
hooks:
    # The build hook runs after Composer to finish preparing up your code.
    build: |
        set -e
        bash install-redis.sh 4.3.0
        echo $NPM_CONFIG_PREFIX
        unset NPM_CONFIG_PREFIX
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | dash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 10.17.0
        cd web/themes/custom/[MY PROJECT]
        npm install
        npm run production
    # The deploy hook runs after your application has been deployed and started.
    deploy: |
        set -e
        php ./drush/platformsh_generate_drush_yml.php
        cd web
        drush -y cache-rebuild
        drush -y updatedb
        drush -y config-import

# The configuration of app when it is exposed to the web.
web:
    # Specific parameters for different URL prefixes.
    locations:
        '/':
            # The folder from which to serve static assets, for this location.
            #
            # This is a filesystem path, relative to the application root.
            root: 'web'

            # How long to allow static assets from this location to be cached.
            #
            # Can be a time in seconds, or -1 for no caching. Times can be
            # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
            # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
            # 365 days).
            expires: 5m

            # Whether to forward disallowed and missing resources from this
            # location to the application.
            #
            # Can be true, false or a URI path string.
            passthru: '/index.php'

            # Deny access to static files in this location.
            allow: false

            # Rules for specific URI patterns.
            rules:
                # Allow access to common static files.
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true

                # Deny direct access to configuration files.
                '^/sites/sites\.php$':
                    scripts: false
                '^/sites/[^/]+/settings.*?\.php$':
                    scripts: false

        '/sites/default/files':
            # Allow access to all files in the public files directory.
            allow: true
            expires: 5m
            passthru: '/index.php'
            root: 'web/sites/default/files'

            # Do not execute PHP scripts.
            scripts: false

            rules:
                # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
                '^/sites/default/files/(css|js)':
                    expires: 2w

# The configuration of scheduled execution.
crons:
    drupal:
        spec: '*/20 * * * *'
        cmd: 'cd web ; drush core-cron'
```

**Tell us about the command you were running**

```sh
lando init # Using already-standing platform project
lando rebuild -y
```

**Tell us about the error you got**

Build proceeded successfully until the very end, right before the lando WARNING ASCII art.

```
Cleaning up...
/helpers/psh-build.sh: line 35:   365 Segmentation fault      platform local:build $PLATFORM_APPLICATION_NAME
ERROR ==> /helpers/psh-build.sh: line 35:   365 Segmentation fault      platform local:build $PLATFORM_APPLICATION_NAME
```

**Tell us generally about your bug**

Trying out the Platform recipe, was using vanilla d8 recipe before v3.0.8. This is my first platform.sh project so the release was good timing! But I get this error, and a 502 Bad Gateway when I try to visit the site in the browser.
