### ISSUE TITLE
Bind address gone. ~/.lando/config.yml seems to get overwritten

### ISSUE THREAD

**Issue by thejacer87** [lando/lando#2519]
**Tell us about your setup**

v3.0.7 on Ubuntu 20.04

**Tell us about your `.lando.yml`**

```yml
name: mysite
recipe: laravel

proxy:
  mail:
    - mailhog.mysite.lndo.site
  appserver:
    - mysite.lndo.site

services:
  appserver:
    webroot: public
    config:
      php: .vscode/php.ini
    build:
      - composer install
      - cp .githooks/pre-commit .git/hooks/
    run:
      - rm -rf ./vendor/squizlabs/php_codesniffer/src/Standards/Silvertip
      - cp -r Silvertip ./vendor/squizlabs/php_codesniffer/src/Standards/Silvertip
    environment:
      PHP_IDE_CONFIG: serverName=mysite.lndo.site
  database:
    type: mysql:8.0
    run_as_root:
       - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS testdatabase; GRANT ALL PRIVILEGES ON testdatabase.* TO 'laravel'@'%';"
    config:
      database: .lando/mysql.cnf
    portforward: 13306
  chromedriver:
    type: compose
    services:
      image: selenium/standalone-chrome-debug:3.141.59-oxygen
      user: seluser
      command: /opt/bin/entry_point.sh
      ports:
        - '4444'
      volumes:
        - '/dev/shm:/dev/shm'
      environment:
        START_XVBF: 'false'
  nodejs:
    type: node
    build:
      - npm install
  mail:
    type: mailhog
    hogfrom:
      - appserver

tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit \nCan run --filter testFunctionName ClassNameTest /path/to/class"
    cmd: /app/vendor/bin/phpunit
  phpcs:
    service: appserver
    description: "Run PHPCS: lando phpcs"
    cmd: /app/vendor/bin/phpcs --colors --standard=Silvertip
  npm:
    service: nodejs
    cmd: npm --root=/app/public
  npx:
    service: nodejs
    cmd: npx --root=/app/public
  dusk:
    service: appserver
    description: "Run Laravel Dusk tests: lando dusk"
    cmd: php artisan dusk
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

```
$ cat .lando/config.yml 
bindAddress: 0.0.0.0
```

**Tell us about the error you got**
**Tell us generally about your bug**

could not connect to site from phone, followed the security docs and modified the config.yml as suggested. then a few days later, went to check on my phone again, and site was inaccessible again.

went back to check the config.yml, and the file was reset to `{ }`

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

i don't know

i feel like something must have overwritten the file, since it had the brackets `{ }` replacing my config

also, the first time i mentioned this in the slack channel, the entire `~/.lando` dir was gone. so not sure what the hell is going on. i definitely don't *intentionally* delete this directory
