### ISSUE TITLE
nginx 500 Internal Server Error

### ISSUE THREAD

**Issue by arcataroger** [lando/lando#2520]
Fresh pull of a previously-working Pantheon repo/recipe on a new Windows 10 computer is resulting in an nginx 500 "Internal Server Error" at http://localhost

Tried under Lando 3.0.9 and 3.0.7 with included Docker (WSL2 enabled).

lando logs shows:
```
appserver_nginx_1  | 2020/07/24 17:14:04 [error] 234#0: *13 rewrite or internal redirection cycle while redirect to named location "@cleanurl", client: 172.19.0.2, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
appserver_nginx_1  | 172.19.0.2 - - [24/Jul/2020:17:14:04 +0000] "GET / HTTP/1.1" 500 572 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"
appserver_nginx_1  | 2020/07/24 17:14:04 [error] 234#0: *14 rewrite or internal redirection cycle while redirect to named location "@cleanurl", client: 172.19.0.2, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
appserver_nginx_1  | 172.19.0.2 - - [24/Jul/2020:17:14:04 +0000] "GET /favicon.ico HTTP/1.1" 500 572 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"
```

.lando.yml:
```
name: field-museum1 # Keep the same as Pantheon's actual name for us
recipe: pantheon # https://docs.lando.dev/config/pantheon.html

# Framework, site, and id were set automatically during Lando init. Do not change without good reason.
config:
  framework: drupal
  site: field-museum1
  id: 760355b6-48f8-46e8-a197-48a47b5443b5
  xdebug: true # Listens on port 9000 by default, at the same URL as appserver_nginx (the main site container)
  cache: true # We need Redis caching to maintain compatibility with Pantheon
  index: false # Disable unneeded Apache Solr search indexing
  edge: false # Disable unneeded Varnish page cache

proxy:
  appserver_nginx:
    - localhost
```

Pantheon.yml:
```
api_version: 1
web_docroot: true
php_version: 7.3
drush_version: 8
enforce_https: transitional
```
