### ISSUE TITLE
ERROR: No container found for mounter_1

### ISSUE THREAD

**Issue by mtellenbach** [lando/lando#2528]
Using the following YAML:
```yaml
name: lando-test
recipe: lamp
excludes:
- themes/**/node_modules

proxy:
    yarn:
    - dev.lndo.site:3000
    mailhog:
    - mail.lando-test.lndo.site

config:
    webroot: .
    services:
        appserver:
            composer:
                offline/oc-bootstrapper: ^0.8.0
            overrides:
                depends_on: [database]
            build:
            - october install
        yarn:
            type: node
            build:
            - "cd themes/* && yarn"
            command: "cd themes/* && yarn dev"
            overrides:
                depends_on: [appserver]
        mailhog:
            type: mailhog
            portforward: true
            hogfrom:
            - appserver


tooling:
    artisan:
        service: appserver
        cmd: php artisan
    october:
        service: appserver
    yarn:
        service: yarn
        cmd: "cd themes/* && yarn"
```

I get the following output:
```
$ lando rebuild -y
Rising anew like a fire phoenix from the ashes! Rebuilding app...
No stopped containers
Pulling database  ... done                                                                                                                                                   
Pulling mailhog   ... done                                                                                                                                                   
Pulling appserver ... done                                                                                                                                                   
Pulling yarn      ... done                                                                                                                                                   
mailhog uses an image, skipping
database uses an image, skipping
appserver uses an image, skipping
yarn uses an image, skipping
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "landotest_default" with the default driver
Creating volume "landotest_exclude_themesnode_modules" with default driver
Creating volume "landotest_data_mounter" with default driver
Creating volume "landotest_home_mounter" with default driver
Creating landotest_mounter_1 ... done
ERROR: No container found for mounter_1
Removing landotest_mounter_1 ... done
Removing network landotest_default
Removing volume landotest_exclude_themesnode_modules
Removing volume landotest_data_mounter
Removing volume landotest_home_mounter
ERROR ==>
```

What am I doing wrong? I'm using Windows 10

```
$ docker --version
Docker version 19.03.8, build afacb8b

$ lando version
v3.0.9
```

**Comment by pirog** [comment]
@mtellenbach i dont think wildcard syntax is supported so that is probably the issue

**Comment by mtellenbach** [comment]
Yes, the problem was that the `excludes` with the asterisk in path failed on Windows.
The error persisted, until docker was restarted.

Simply editing the file wasn't enough.

**Comment by tobias-kuendig** [comment]
I just had this problem again on Windows:

```yml
name: project
recipe: lamp
excludes:
  - themes/project.tld/node_modules

proxy:
  yarn:
    - dev.lndo.site:3000
  mailhog:
    - mail.project.lndo.site

config:
  webroot: .
  services:
    appserver:
      composer:
        hirak/prestissimo: ^0.3.10
        offline/oc-bootstrapper: ^0.8.0
      overrides:
        depends_on: [database]
      build:
        - october install
    yarn:
      type: node
      scanner: false
      build:
        - "cd themes/project.tld && yarn"
      command: "cd themes/project.tld && yarn dev"
      overrides:
        depends_on: [appserver]
    mailhog:
      type: mailhog
      portforward: true
      hogfrom:
        - appserver
    database:
      portforward: 3306

tooling:
  artisan:
    service: appserver
    cmd: php artisan
  october:
    service: appserver
```

A `lando restart` results in the following error:

```
Stopping and restarting your app...Shiny!
Killing projecttld_mailhog_1   ... done                                                                                               
Killing projecttld_yarn_1      ... done                                                                                               Killing projecttld_appserver_1 ... done                                                                                               Killing projecttld_database_1  ... done
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Removing orphan container "projecttld_database_1"
Removing orphan container "projecttld_mailhog_1"
Removing orphan container "projecttld_appserver_1"
Removing orphan container "projecttld_yarn_1"
Creating projecttld_mounter_1 ... done
ERROR: No container found for mounter_1
Removing projecttld_mounter_1 ... done
Removing network projecttld_default
Removing volume projecttld_exclude_themesprojecttldchnode_modules
Removing volume projecttld_data_mounter
Removing volume projecttld_home_mounter
ERROR ==>  message=, stack=Error
    at C:\snapshot\lando\build\cli\lib\shell.js
From previous event:
    at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js)
    at Object.dc (C:\snapshot\lando\build\cli\lib\bootstrap.js)
    at compose (C:\snapshot\lando\build\cli\lib\bootstrap.js)
From previous event:
    at C:\snapshot\lando\build\cli\lib\router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Object.run (C:\snapshot\lando\build\cli\lib\router.js)
    at run (C:\snapshot\lando\build\cli\lib\engine.js)
    at C:\snapshot\lando\build\cli\lib\router.js
From previous event:
    at Object.eventWrapper (C:\snapshot\lando\build\cli\lib\router.js)
    at Engine.engineCmd (C:\snapshot\lando\build\cli\lib\engine.js)
    at Engine.run (C:\snapshot\lando\build\cli\lib\engine.js)
    at C:\snapshot\lando\build\cli\plugins\lando-sharing\app.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at AsyncEvents.<anonymous> (C:\snapshot\lando\build\cli\plugins\lando-sharing\app.js)
    at AsyncEvents.handle (C:\snapshot\lando\build\cli\lib\events.js)
    at C:\snapshot\lando\build\cli\lib\events.js
From previous event:
    at AsyncEvents.emit (C:\snapshot\lando\build\cli\lib\events.js)
From previous event:
    at App.start (C:\snapshot\lando\build\cli\lib\app.js)
    at C:\snapshot\lando\build\cli\lib\app.js
From previous event:
    at App.restart (C:\snapshot\lando\build\cli\lib\app.js)
    at Object.run (C:\snapshot\lando\build\cli\plugins\lando-core\tasks\restart.js)
From previous event:
    at C:\snapshot\lando\build\cli\lib\cli.js
From previous event:
    at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js)
    at Object.runCommand (C:\snapshot\lando\build\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.init (C:\snapshot\lando\build\cli\lib\cli.js)
    at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js)
    at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, __stackCleaned__=true
```

Any idea what causes this problem? The problem persists until Docker itself is restarted.
