### ISSUE TITLE
Add one or more url to my project

### ISSUE THREAD

**Issue by rpayanm** [lando/lando#2545]
Hello,

Thanks for this awesome project!

I have a drupal 8 site with this config:
```
name: my-site
recipe: drupal8
config:
  webroot: web
  php: '7.4'
  xdebug: true
  via: nginx
  database: mariadb
```

I saw on terminal:
```
 APPSERVER_NGINX URLS  https://localhost:32826                           
                       http://localhost:32827                            
                       http://my-site.lndo.site/                         
                       https://my-site.lndo.site/ 
```

My question is:
How could I add one or more alias/hostname/url ?

I would like have a output like that, for example:
```
 APPSERVER_NGINX URLS  https://localhost:32826                           
                       http://localhost:32827                            
                       http://my-site.lndo.site/                         
                       https://my-site.lndo.site/ 
                       http://my-site1.lndo.site/                         
                       https://my-site1.lndo.site/ 
                       http://my-site2.lndo.site/                         
                       https://my-site2.lndo.site/ 
```
I added the 2 urls (my-site1.lndo.site and my-site1.lndo.site).

I can use http://my-site.lndo.site/ or http://my-site1.lndo.site/ or http://my-site2.lndo.site/ to access to the same site.

**Comment by dustinleblanc** [comment]
Hey @rpayanm ! You can do this with the Proxy system: https://docs.lando.dev/config/proxy.html

e.g
```yml
proxy:
  appserver_nginx:
    - my-site1.lndo.site
    - my-site2.lndo.site
```

Thanks!

**Comment by rpayanm** [comment]
Thanks for the fast answer!

Here my config again:
```
name: my-site
recipe: drupal8
config:
  webroot: web
  php: '7.4'
  xdebug: true
  via: nginx
  database: mariadb
proxy:
  appserver_nginx:
    - my-site1.lndo.site
    - my-site2.lndo.site
```

My output:
```
 APPSERVER_NGINX URLS  https://localhost:32887                           
                       http://localhost:32888                            
                       http://my-site1.lndo.site/                       
                       https://my-site1.lndo.site/                      
                       http://my-site2.lndo.site/                       
                       https://my-site2.lndo.site/                      
```

But on the browser i got `404 page not found`:
![image](https://user-images.githubusercontent.com/6087454/89309337-48c04580-d641-11ea-8ae4-730ddffae2b9.png)

The `http://localhost:32888` page works fine, with error but it loads:
![image](https://user-images.githubusercontent.com/6087454/89309639-a94f8280-d641-11ea-98aa-3b2ee2f8aa39.png)

I added `my-site1.lndo.site` and `my-site2.lndo.site` in my `/etc/hosts` file:
![image](https://user-images.githubusercontent.com/6087454/89310001-27ac2480-d642-11ea-826d-1df2d2218308.png)
