### ISSUE TITLE
PHPStorm + PHPUnit + Lando on Ubuntu 18.04

### ISSUE THREAD

**Issue by raaaahman** [lando/lando#2551]
Hi, I've followed the guide by @joshmiller83 in #2232 trying to adapt it to an Ubuntu 18.04 environment. I am currently able to run with CLI from inside the container, but trying to run them through PHPStorm gives me some error messages:

```
Fatal error: Uncaught Error: Class 'PHP_CodeSniffer\Tests\Standards\AbstractSniffUnitTest' not found in /app/polylang-pro/vendor/automattic/vipwpcs/WordPressVIPMinimum/Tests/Classes/DeclarationCompatibilityUnitTest.php:17
Stack trace:
#0 /app/polylang-pro/vendor/phpunit/phpunit/src/Util/Fileloader.php(52): include_once()
#1 /app/polylang-pro/vendor/phpunit/phpunit/src/Util/Fileloader.php(36): PHPUnit_Util_Fileloader::load('/app/polylang-p...')
#2 /app/polylang-pro/vendor/phpunit/phpunit/src/Framework/TestSuite.php(316): PHPUnit_Util_Fileloader::checkAndLoad('/app/polylang-p...')
#3 /app/polylang-pro/vendor/phpunit/phpunit/src/Framework/TestSuite.php(393): PHPUnit_Framework_TestSuite->addTestFile('/app/polylang-p...')
#4 /app/polylang-pro/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php(57): PHPUnit_Framework_TestSuite->addTestFiles(Array)
#5 /app/polylang-pro/vendor/phpunit/phpunit/src/TextUI/Command.php(138): PHPUnit_Runner_BaseTestRunner->getTest('/app/polylang-p...', '', Array)
#6 /app/polylang-pro/vendor/phpunit/p in /app/polylang-pro/vendor/automattic/vipwpcs/WordPressVIPMinimum/Tests/Classes/DeclarationCompatibilityUnitTest.php on line 17

Process finished with exit code 255
```

Because I'm working on a WordPress plugin, the latest PHPUnit version I can use is 5.7.27. But this doesn't break my tests with CLI (although, they are very slow).

I'm using the WordPress recipe as a base:

```yaml
name: polylang-dev-2
recipe: wordpress
config:
  webroot: ./wordpress-develop/build/
  xdebug: true
  database: mariadb
  config:
    php: php.ini
services:
  appserver:
    run:
      - cd /app && cp -r wordpress-develop/tests/phpunit/includes includes
      - cd /app/polylang-pro && composer install
  pma:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    hogfrom:
    - appserver
tooling:
  composer:
    service: appserver
proxy:
  appserver:
  - polylang-dev-2.lndo.site
  - "*.polylang-dev-2.lndo.site"
  mailhog:
    - mailhog-polylang-dev-2.lndo.site
  pma:
    - pma-polylang-dev-2.lndo.site
env_file:
  - tests.env
```

Should I switch from the standard `php-apache` image to `php-fpm`?

I've selected the 'Unix Socket' option to connect to Docker (successful):

![Capture d’écran de 2020-08-06 14-31-24](https://user-images.githubusercontent.com/16425382/89532293-d8a4f180-d7f1-11ea-8141-a1355795b215.png)

Set my network Id and container path:

![Capture d’écran de 2020-08-06 14-32-40](https://user-images.githubusercontent.com/16425382/89532562-46511d80-d7f2-11ea-8e07-73009ad8e6de.png)

Strange thing is that I had to redefine the environment variable, having already included it in Lando through an environment file (see .lando.yml above).

Then I configured my CLI interpreter

![Capture d’écran de 2020-08-06 14-30-33](https://user-images.githubusercontent.com/16425382/89533148-3ede4400-d7f3-11ea-8699-7661c8d24a05.png)

Another strange behavior is that the image keep going back to `bitnami/mariadb:10.3.23` regardless of how many times I change it, whether I select `devwithlando/php:7.3-apache-2`, `devwithlando/php:7.4-apache-2` or `devwithlando/php:7.2-apache-2`.

Finally, I created an alternate configuration file to include the following:

```xml
	<php>
		<env name="SIMPLETEST_BASE_URL" value="http://appserver.polylangdev2.internal"/>
		<env name="SIMPLETEST_DB" value="mysql://wordpress:wordpress@database/wordpress"/>
	</php>
```

Although I am not sure if I should keep the names `SIMPLETEST_BASE_URL` and `SIMPLETEST_DB` or adapt it to my case.

Thank you for your time.
