### ISSUE TITLE
custom set ports from node project not shown in lando info

### ISSUE THREAD

**Issue by kinglouie** [lando/lando#2560]
I'm currently trying to setup lando for a node project where I have two node services running. For the services to communicate they need to have fixed ports, from my understanding reading several issues, the only way to do that is by overriding on docker compose level.

My issue is that the services are in fact accessible on the ports I set but when I run `lando start` the scanner hangs for a very long time and ultimately shows localhost urls with random ports and not the actual working ports.

I already tried the following config options on the service level with no change in behaviour:

```
moreHttpPorts:
ports:
```

So how do I let lando know, that I set custom ports?

This is my lando file:
```
name: example
services:

  api:
    type: node:13
    overrides:
      ports: 
        - 4000:4000
    build:
      - cd api && rm -rf ./node_modules && npm install && npm run build
    command: cd api && npm run dev

  db_api:
    type: postgres:10
    portforward: true

  admin:
    type: node:13
    overrides:
      ports: 
        - 8085:8085
    build:
      - cd admin && rm -rf ./node_modules && yarn install
    command: cd admin && yarn dev

```

my lando version is the most recent available.

**Comment by pirog** [comment]
Check out these docs https://docs.lando.dev/config/node.html#setting-a-port that is probably what you want

should be something like:

```
name: example
services:

  api:
    type: node:13
    port: 4000
    build:
      - cd api && rm -rf ./node_modules && npm install && npm run build
    command: cd api && npm run dev

  db_api:
    type: postgres:10
    portforward: true

  admin:
    type: node:13
    port: 8085
    build:
      - cd admin && rm -rf ./node_modules && yarn install
    command: cd admin && yarn dev
```
