### ISSUE TITLE
`lando drupal` broken due to upstream issue/breaking changes

### ISSUE THREAD

**Issue by mrweiner** [lando/lando#2573]
Per https://github.com/hechoendrupal/drupal-console/issues/4262, there appears to be an issue with the installer (https://drupalconsole.com/installer) being unavailable. This is ca

**Comment by mrweiner** [comment]
Alright I've got another workaround for the meantime, assuming you've already ran `composer drupal/console`, so it's sitting in your project's dir, you can add this to your `.lando.yml`

```
services:
  appserver:
    build:
      - "rm /usr/local/bin/drupal; ln -s /app/path_to_your/vendor/drupal/console/bin /usr/local/bin/drupal"
```

**Comment by mrweiner** [comment]
Started getting a permission denied error with the above, not sure why, so for the time-being I just added some custom tooling to override the built-in command:

```
tooling:
  drupal:
    service: appserver
    description: Override for broken `lando drupal`
    cmd: cd /app/dywm8_project/vendor/bin && ./drupal
    user: www-data
```
