### ISSUE TITLE
Accessing lando via SSL from another docker container (standalone-chrome-debug)

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#2597]
I have a Pantheon Drupal 8 install that uses a version of the selenium standalone-chrome-debug to do behat tests.

However, when I VNC into the standalone-chrome-debug image, I can only access my local site (great!), not the wider Internet.  (I can't open any URLs to sites on the web from Chrome via VNC in the standalone-chrome-debug container, which is causing Stripe to break (because it needs to download stripe.js) and causing my Behat tests to fail.)

So how can I tell lando to use my machine's Internet connection for the standalone-chrome-debug container?

Here's the relevant part of my `lando.yml`:

```
name: MYSITE
recipe: pantheon
config:
  env: lando
  xdebug: true
  framework: drupal8
  webroot: web

  seleniumchromedriver:
    type: compose
    services:
      # Set the same image in .circleci/config.yml.
      image: ptmkenny/standalone-chrome-debug-ffmpeg:latest
      command: /opt/bin/entry_point.sh
      ports:
        - '4444'
        - '5900'
      volumes:
        - '/dev/shm:/dev/shm'
      environment:
        TZ: 'Asia/Tokyo'
        START_XVBF: 'false'
```

Generally these questions should end up as guides
https://docs.lando.dev/contrib/guides-intro.html#what-is-a-guide
