### ISSUE TITLE
lando db-import crashes when trying to delete views beforehand in mysql

### ISSUE THREAD

**Issue by pvanhemmen** [lando/lando#2605]
**Tell us about your setup**

*v3.0.11 on Ubuntu 20.04.1*

**Tell us about your `.lando.yml`**

```yml
name: custom-project
recipe: lamp
config:
  webroot: source
  php: '7.1'
  xdebug: true
proxy:
  appserver:
    - custom-project.example.com
services:
  appserver:
    build_as_root:
      - apt-get update -y && apt-get install nano -y
      - export PHP=7.1 && export IC_SO="ioncube_loader_lin_$PHP.so" && export PHP_EXT_DIR=`php-config --extension-dir` && cd /tmp && curl -o ioncube.tar.gz http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz && tar -xvvzf ioncube.tar.gz && mv "ioncube/$IC_SO" $PHP_EXT_DIR && rm -Rf ioncube.tar.gz ioncube && echo "zend_extension=$PHP_EXT_DIR/$IC_SO" > /usr/local/etc/php/conf.d/00_docker-php-ext-ioncube_loader.ini
  database:
    portforward: 34006
  node:
    type: node:12
    build:
      - npm install
      - cd $LANDO_MOUNT/source/modules/custom-project/custom-module/ui && npm install
    globals:
      gulp-cli: latest
tooling:
  npm:
    service: node
  gulp:
    service: node
  npm-run-serve:
    service: node
    description: Runs the vuejs server for custom-module development
    cmd: cd $LANDO_MOUNT/source/modules/custom-project/custom-module/ui && npm run serve
  db-sync:
    description: import mysqldump from live system
    cmd:
      - appserver: rsync *** .
      - database: gunzip < db.gz | mysql -u root lamp
      - database: mysql -u root lamp < build/tools/sync/reset.sql
      - appserver: rm db.gz
  assets:
    service: appserver
    description: Pulls assets from the live server
    cmd:
      - rsync ***
```

**Tell us about the command you were running**

```bash
lando db-import db.sql.gz
```

**Tell us about the error you got**

```bash
ERROR 1051 (42S02) at line 2: Unknown table 'lamp.view_table'
```

**Tell us generally about your bug**

The lando db-import command crashes when it deletes existing data beforehand and the mysql database to be deleted contains views (https://dev.mysql.com/doc/refman/5.7/en/views.html). The command crashes on the first view it encounters. This bug is reproducable 100% of the time.
