### ISSUE TITLE
Weird options asked after `lando start`ing a platform.sh recipe project

### ISSUE THREAD

**Issue by thasmo** [lando/lando#2612]
**TL/DR**
When running `lando init` when setting up a `platform.sh` project before setting up the actual `platform.sh` project (e.g by running `platform project:set-remote ...` in the project directory) the behavior described below happens.

---

When running `lando start` and after the `platform.sh` CLI got installed within that process, two options need to be provided:
* Source directory (default: .):
* Build destination (default: _www):

After `lando start` has finished there's a new symlink `_www/` which points to the `public/` directory, which is the actual webroot.
It seems something is triggering some kind of setup/install routine which creates this symlink?

The `.lando.yml` file was created running `lando init` selecting `current directory` and the `platform.sh` recipe. I had to provide an access token which enabled me to select the desired platform.sh project.

**Steps**
```bash
git clone <platform.sh project>
lando init
lando start
```

**Terminal Excerpt**
```bash
To use the Platform.sh CLI, run:
platform
    Source directory (default: .):
    Build destination (default: _www):
Building application app (runtime type: php:7.4)
Found a composer.json file; installing dependencies
```

**.lando.yml**
```yaml
name: <projectname>
recipe: platformsh
config:
  id: <platformsh-identifier>
```

**.platform.app.yaml**
```yaml
name: app

type: php:7.4
build:
    flavor: composer

variables:
    env:
        APP_ENV: 'prod'
        APP_DEBUG: 0
        TYPO3_CONTEXT: 'Production'

runtime:
    extensions:
        - apcu
        - imagick
    
relationships:
    database: 'mysqldb:mysql'
    rediscache: 'rediscache:redis'

disk: 3072

mounts:
    'var/cache':
        source: local
        source_path: var/cache
    'var/charset':
        source: local
        source_path: var/charset
    'var/lock':
        source: local
        source_path: var/lock
    'var/log':
        source: local
        source_path: var/log
    'var/session':
        source: local
        source_path: var/session
    'var/transient':
        source: local
        source_path: var/transient
    'public/fileadmin':
        source: local
        source_path: fileadmin
    'public/uploads':
        source: local
        source_path: uploads
    'public/typo3temp':
        source: local
        source_path: typo3temp
    'public/typo3conf/writeable':
        source: local
        source_path: typo3-config

web:
    locations:
        '/':
            root: 'public'
            passthru: '/index.php'
            index:
                - 'index.php'
            allow: false
            rules:
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    expires: 7d
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true
                '/Sitemap\.xsl$':
                    allow: true
                '^/google3927d432d1e8f4f4\.html$':
                    allow: true
                '^/BingSiteAuth\.xml$':
                    allow: true
            headers: &headerControls
                X-Content-Type-Options: nosniff
                X-Frame-Options: SAMEORIGIN
                X-XSS-Protection: 1; mode=block
        '/static':
            root: 'public/static'
            expires: 1y
            scripts: false
            allow: true
            passthru: false
            headers:
                Service-Worker-Allowed: '/'
                X-Content-Type-Options: nosniff
            rules:
                '\.webmanifest$':
                    headers:
                        <<: *headerControls
                        Content-Type: application/manifest+json
        '/fileadmin':
            root: 'public/fileadmin'
            scripts: false
            allow: true
            passthru: '/index.php'
            headers: *headerControls
        '/fileadmin/_processed_':
            root: 'public/fileadmin/_processed_'
            expires: 1y
            scripts: false
            allow: true
            passthru: false
            headers: *headerControls
        '/fileadmin/csv':
            root: 'public/fileadmin/csv'
            expires: 1y
            scripts: false
            allow: true
            passthru: false
            headers: *headerControls
        '/fileadmin/domain-verification':
            root: 'public/fileadmin/domain-verification'
            expires: 1y
            scripts: false
            allow: true
            passthru: false
            headers: *headerControls
        '/fileadmin/form':
            root: 'public/fileadmin/form'
            expires: 1y
            scripts: false
            allow: true
            passthru: false
            headers: *headerControls
        '/fileadmin/handwerkprofis':
            root: 'public/fileadmin/handwerkprofis'
            expires: 1y
            scripts: false
            allow: true
            passthru: false
            headers: *headerControls
        '/fileadmin/sg_cookie_optin':
            root: 'public/fileadmin/sg_cookie_optin'
            expires: 1y
            scripts: true
            allow: true
            passthru: false
            headers: *headerControls
        '/uploads':
            root: 'public/uploads'
            scripts: false
            allow: true
            passthru: '/index.php'
            headers: *headerControls
        '/typo3temp/assets':
            root: 'public/typo3temp/assets'
            expires: 7d
            scripts: false
            allow: true
            passthru: false
            rules:
                '\.js\.gzip$':
                    headers:
                        <<: *headerControls
                        Content-Type: text/javascript
                        Content-Encoding: gzip
                '\.css\.gzip$':
                    headers:
                        <<: *headerControls
                        Content-Type: text/css
                        Content-Encoding: gzip
        '/typo3conf/LocalConfiguration.php':
            allow: false
        '/typo3conf/AdditionalConfiguration.php':
            allow: false

hooks:
    build: |
        if [ -s .nvmrc ]; then
            unset NPM_CONFIG_PREFIX
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | dash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install --latest-npm
        fi

        set -ex

        bash install-redis.sh 5.2.2

        if [ -s package.json ] && [ -s package-lock.json ]; then
            npm ci
            npm run build:production
            rm -rf node_modules/
        fi

        cd public/typo3conf/
        ln -s writeable/ENABLE_INSTALL_TOOL ENABLE_INSTALL_TOOL
    deploy: |
        set -x

        bin/console cache:clear --no-warmup || rm -rf var/cache/*
        bin/console cache:warmup
        vendor/bin/typo3cms cache:flushgroups system

        touch public/typo3conf/ENABLE_INSTALL_TOOL
        vendor/bin/typo3cms database:updateschema safe

        vendor/bin/typo3cms cache:flushgroups pages
    post_deploy: |
        set -x

        vendor/bin/typo3cms install:fixfolderstructure

        vendor/bin/typo3cms upgrade:prepare
        vendor/bin/typo3cms upgrade:run all

crons:
    typo3:
        spec: '*/5 * * * *'
        cmd: 'vendor/bin/typo3cms scheduler:run'
```

**Environment**
```
Lando v3.0.12
Windows 10.0.19041 Build 19041
Docker for Windows 2.3.0.5 (48029)
Docker Engine 19.03.12
Hyper-V 10.0.19041.488
Hyper-V Manager 10.0.19041.1
WSL2 Ubuntu 20.04
```
