### ISSUE TITLE
Portforwarding and proxy not working for custom service?

### ISSUE THREAD

**Issue by iKlsR** [lando/lando#2621]
I was poking around earlier and by a stroke of luck and <strike>black magic</strike> good documentation everything worked?!

I can access [meilisearch](https://www.meilisearch.com/) inside laravel using the hostname I get when I run `lando info` but the portforwarding doesn't seem to be enabled, any idea what I could be doing wrong? PS, this could make a good candidate for a supported service.

```yml
 { service: 'meilisearch',
    urls: [ 'http://meili.money.lndo.site/' ],
    type: 'compose',
    healthy: true,
    config: {},
    version: 'custom',
    meUser: 'www-data',
    hasCerts: false,
    hostnames: [ 'meilisearch.money.internal' ] },
```

Relevant section from my config.

```yml
proxy:
  meilisearch:
    - meili.money.lndo.site

services:
  meilisearch:
    type: compose
    app_mount: delegated
    portforward: true
    services:
      image: getmeili/meilisearch
      command: ./meilisearch
      ports:
        - '7700'
    volumes:
      meili_volume:
    # networks:
    #   meili_network:
```
