### ISSUE TITLE
Nginx allow access to custom directory in Drupal 7 site

### ISSUE THREAD

**Issue by maskedjellybean** [lando/lando#2632]
I have a Drupal 7 site running via Nginx with this directory structure:
```
docroot/
-- misc/
-- modules/
-- profiles/
-- reader/
    -- index.html
    -- app.js
-- sites/
(etc)
```

`docroot/reader` is a custom directory which contains an Angular app. 

The Angular app should be accessible _in browser_ at /reader/#/book/453742  (where 453742 is an argument which loads a different book depending on the node id passed).

However, going to /reader/#/book/453742 in browser responds with 404. This is exactly the same behavior as if you were to go to /sites or /modules.

This makes perfect sense as a default configuration for Drupal 7, but how could I override the default configuration in order to allow access to /reader/* in browser? Based on my Googling it would involve a custom `nginx.conf` file which I would load in `.lando.yml` using `vhosts` like so:

**.lando.yml**
```
name: mysite
recipe: drupal7
config:
  framework: drupal7
  php: '7.1'
  via: nginx
  database: mariadb
  webroot: docroot
  drush: ^8
  xdebug: false
  config:
    vhosts: lando/nginx-conf/nginx.conf
```

However I have no idea what my custom `nginx.conf` should look like. Any help would be appreciated!
