### ISSUE TITLE
Service "appserver_nginx" is not running

### ISSUE THREAD

**Issue by maskedjellybean** [lando/lando#2634]
**Tell us about your setup**

MacOS Catalina 10.15.7
Lando v3.0.14
Docker Desktop 2.3.0.5

**`.lando.yml`**

```yml
name: cebf
recipe: pantheon
config:
  framework: drupal7
  site: solar4schools
  id: REMOVED IN CASE THIS IS SENSITIVE INFO
  api_version: 1
  database: pantheon
  username: pantheon
  password: pantheon
  host: database
  port: 3306
  xdebug: false
  config:
    # Custom PHP config overrides.
    # @TODO: Need to allow overrides per developer.
    php: lando/php-conf/php.ini
proxy:
  appserver_nginx:
    # Add reliable domain. Requires adding to /etc/hosts on local machine to work.
    - cebf.lando
  solr:
    - solr.cebf.lndo.site:8985
services:
  appserver:
    build_as_root:
      # Install Nano for debugging purposes.
      - apt-get update && apt install nano
    overrides:
      environment:
        # Support debugging Drush with Xdebug.
        PHP_IDE_CONFIG: "serverName=appserver"
  database:
    portforward: 32807
  solr:
    type: solr:3.6
    # Solr port will most likely be 8983 and is not configurable. 8985 is only for accessing admin.
    # See: https://github.com/lando/lando/issues/1078
    portforward: 8985
    core: cebf_search_local
    config:
      dir: lando/solr-conf/3.x
tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root
  env-deploy:
    service: appserver
    description: Deploys to test or live Pantheon env (deploys code, updates database, imports config and clears caches)
    cmd:
      # /app is root of codebase inside container.
      - /app/lando/scripts/deploy-env.sh
  env-import:
    service: appserver
    description: Updates database, imports config and clears caches on a Pantheon env or on your local Lando env
    cmd:
      # /app is root of codebase inside container.
      - /app/lando/scripts/import-env.sh
  reindex-env:
    service: appserver
    description: Reindexes Solr on a Pantheon env or on your local Lando env
    cmd:
      # /app is root of codebase inside container.
      - /app/lando/scripts/reindex-env.sh

```

**Tell us about the command you were running**

```bash
lando start
```

After running `lando start` or `lando rebuild` I see:

```bash
solr version 3.6 is a legacy version! We recommend upgrading.
Let's get this party started! Starting app cebf...
solr version 3.6 is a legacy version! We recommend upgrading.
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "cebf_default" with the default driver
Creating volume "cebf_data_appserver_nginx" with default driver
Creating volume "cebf_home_appserver_nginx" with default driver
Creating volume "cebf_data_appserver" with default driver
Creating volume "cebf_home_appserver" with default driver
Creating volume "cebf_data_database" with default driver
Creating volume "cebf_home_database" with default driver
Creating volume "cebf_data_cache" with default driver
Creating volume "cebf_home_cache" with default driver
Creating volume "cebf_data_edge" with default driver
Creating volume "cebf_home_edge_ssl" with default driver
Creating volume "cebf_home_edge" with default driver
Creating volume "cebf_data_index" with default driver
Creating volume "cebf_home_index" with default driver
Creating volume "cebf_data_solr" with default driver
Creating volume "cebf_home_solr" with default driver
Creating cebf_appserver_1 ... done
Pantheon pre-run scripting
Generating RSA private key, 2048 bit long modulus
.......+++++
.........+++++
e is 65537 (0x010001)
Signature ok
subject=C = US, ST = California, L = San Francisco, O = Lando, OU = Bespin, CN = appserver.cebf.internal
Getting CA Private Key
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [53.0 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [602 kB]
Get:4 http://apt.postgresql.org/pub/repos/apt stretch-pgdg InRelease [76.6 kB] 
Get:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [233 kB]
Get:6 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64 Packages [247 kB]
Ign:7 http://deb.debian.org/debian stretch InRelease
Get:8 http://deb.debian.org/debian stretch-updates InRelease [93.6 kB]
Get:9 http://deb.debian.org/debian buster InRelease [121 kB]
Get:10 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:11 http://deb.debian.org/debian stretch Release [118 kB]   
Get:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages [2596 B]
Get:13 http://deb.debian.org/debian stretch Release.gpg [2410 B]
Get:14 http://deb.debian.org/debian buster/main amd64 Packages [7906 kB]
Get:15 http://deb.debian.org/debian buster-updates/main amd64 Packages [7868 B]
Get:16 http://deb.debian.org/debian stretch/main amd64 Packages [7080 kB]
Fetched 16.7 MB in 6s (2681 kB/s)                                              
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  spell
The following NEW packages will be installed:
  nano
0 upgraded, 1 newly installed, 0 to remove and 9 not upgraded.
Need to get 485 kB of archives.
After this operation, 2092 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 nano amd64 2.7.4-1 [485 kB]
Fetched 485 kB in 0s (1658 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package nano.
(Reading database ... 45203 files and directories currently installed.)
Preparing to unpack .../nano_2.7.4-1_amd64.deb ...
Unpacking nano (2.7.4-1) ...
Setting up nano (2.7.4-1) ...
update-alternatives: using /bin/nano to provide /usr/bin/editor (editor) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/editor.1.gz because associated file /usr/share/man/man1/nano.1.gz (of link group editor) doesn't exist
update-alternatives: using /bin/nano to provide /usr/bin/pico (pico) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/pico.1.gz because associated file /usr/share/man/man1/nano.1.gz (of link group pico) doesn't exist
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   632  100   632    0     0   2146      0 --:--:-- --:--:-- --:--:--  2142
100 4879k  100 4879k    0     0  2100k      0  0:00:02  0:00:02 --:--:-- 3945k
 Drush Version   :  8.3.5 

Killing cebf_appserver_1 ... done
Starting cebf_appserver_1       ... done
Creating cebf_cache_1           ... done
Creating cebf_solr_1            ... done
Creating cebf_appserver_nginx_1 ... done
Creating cebf_index_1           ... done
Creating cebf_database_1        ... done
Creating cebf_edge_1            ... done
Creating cebf_edge_ssl_1        ... done
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Scanning to determine which services are ready... Please standby...
Starting cebf_appserver_nginx_1 ... done
ERROR: Container 15fc62bb03ac81427a4abb7b1bc99144c466ec8d7d3c556ea5e28bdaedc91fa1 is not running
ERROR ==>  message=, stack=Error
    at /snapshot/lando/build/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js)
    at Object.dc (/snapshot/lando/build/cli/lib/bootstrap.js)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/lando/build/cli/lib/router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Object.run (/snapshot/lando/build/cli/lib/router.js)
    at run (/snapshot/lando/build/cli/lib/engine.js)
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/lando/build/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/lando/build/cli/lib/engine.js)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js)
    at /snapshot/lando/build/cli/plugins/lando-core/app.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-core/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
From previous event:
    at /snapshot/lando/build/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, __stackCleaned__=true
Starting cebf_appserver_nginx_1 ... done
Starting cebf_edge_1            ... done
Killing cebf_edge_1 ... done

  _      __              _           __
 | | /| / /__ ________  (_)__  ___ _/ /
 | |/ |/ / _ `/ __/ _ \/ / _ \/ _ `/_/ 
 |__/|__/\_,_/_/ /_//_/_/_//_/\_, (_)  
                             /___/     

Your app started up but we detected some things you may wish to investigate.
These only may be a problem.


 ■ The service "appserver_nginx" is not running!
   This is likely a critical problem and we recommend you run the command below to investigate
   lando logs -s appserver_nginx


Here are some vitals:

 NAME                  cebf                                                                     
 LOCATION              /Users/blt/Sites/cebf                                                    
 SERVICES              appserver_nginx, appserver, database, cache, edge_ssl, edge, index, solr 
 APPSERVER_NGINX URLS  http://cebf.lando/                                                       
                       https://cebf.lando/                                                      
 EDGE_SSL URLS         https://localhost:32776                                                  
 EDGE URLS             http://cebf.lndo.site/                                                   
                       https://cebf.lndo.site/                                                  
 SOLR URLS             http://solr.cebf.lndo.site/
```

**Tell us generally about your bug**

All app URLs are reported as unhealthy and don't work.

Running `lando logs -s appserver_nginx` reveals nothing that appears to be an error except this:

```bash
appserver_nginx_1  | landonginx 23:44:43.17 DEBUG ==> user root root; ## Default: nobody worker_processes auto; error_log "/opt/bitnami/nginx/logs/error.log"; pid "/opt/bitnami/nginx/tmp/nginx.pid"; events { worker_connections 1024; } http { include mime.types; default_type text/plain; client_body_temp_path /tmp 1 2; proxy_temp_path /tmp 1 2; fastcgi_temp_path /tmp 1 2; uwsgi_temp_path /tmp 1 2; scgi_temp_path /tmp 1 2; log_format time_combined '$remote_addr - $remote_user [$time_local] ' '"$request" $status $body_bytes_sent ' '"$http_referer" "$http_user_agent" $request_time ' '"$http_x_forwarded_for"'; access_log "/opt/bitnami/nginx/logs/access.log"; server_tokens off; aio off; directio off; sendfile off; gzip on; # Use large enough buffers for Content Security Policy support. fastcgi_buffers 16 16k; fastcgi_buffer_size 32k; # On the nginx version we have on F20 (nginx/1.4.7), nginx sends a malformed HTTP # response for 'Request-URI Too Large' # http://mailman.nginx.org/pipermail/nginx/2012-July/034578.html # # This is bad because styx considers this an error, and will mark the binding # unhealthy. As a workaround, we are going to bump this buffer # size to avoid hitting 'Request-URI Too Large' # large_client_header_buffers 4 32k; proxy_read_timeout 900s; fastcgi_read_timeout 900s; auth_basic_user_file htpasswd; add_header X-Pantheon-Endpoint lando; map $http_user_agent $auth_basic_realm { default off; Photon/1.0 "off"; } map $http_x_forwarded_proto $lando_https { default ''; https on; } map $http_x_forwarded_proto $http_user_agent_https { default ''; https ON; } include "/opt/bitnami/nginx/conf/vhosts/*.conf"; }
appserver_nginx_1  | landonginx 23:44:43.17 INFO  ==> copying /tmp/server.conf.lando to /opt/bitnami/nginx/conf/nginx.conf
appserver_nginx_1  | landonginx 23:44:43.18 INFO  ==> copying /tmp/fastcgi_params.lando to /opt/bitnami/nginx/conf/fastcgi_params
appserver_nginx_1  | sed: read error on /tmp/vhosts.conf.lando: Is a directory
```

**Things I've tried:**

* `lando rebuild` - Same error
* `lando destroy && lando start` - Same error
* Restarting Docker Desktop and then `lando start` - Same error
* `lando poweroff && lando start` - Same error
* `lando stop`. `docker ps -a`. Find container ID for traefik. `docker stop CONTAINER_ID && docker rm CONTAINER_ID && lando start` - Same error

How else can I troubleshoot this?
