### ISSUE TITLE
Proxy routing to a different Python port 

### ISSUE THREAD

**Issue by com2** [lando/lando#2656]
Python app is listening to port 8000 and I want the proxy to forward requests to this port the  standard HTTP port.  So far I could not find a really clear example of this but by reading from different sources I came up with this:

```
name: myapp
services:
  python:
    type: python:3.6
    portforward: true
    ports:
      - '8000'
    build:
      - pip install $(cat requirements.txt)
    command:
      - ./manage.py runserver
proxy:
  python:
    - myapp.lndo.site:8000
```
After a long delay the URLs come back in red and don't work, the myapp.lndo.site responding with "Bad Gateway". What am I doing wrong? With `lando ssh -c 'curl localhost:8000'` I see a http response so the python app seems to be running all right. I tried removing the portforward and ports but that did no make a difference. What is it that I seem to misunderstand in https://docs.lando.dev/config/proxy.html#routing-to-a-different-port ?
