### ISSUE TITLE
How to run Puppeteer in Node

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#2659]
**Please explain your request and its importance in the form of a user story.**

As a lando user who is making progressive web apps, I want to use [pwa-asset-generator](https://github.com/onderceylan/pwa-asset-generator) to generate icons, splash screeens, and so on.

This package requires puppeteer, which I am having trouble installing on lando.

**Please provide some detail on how lando can help solve this problem**

Puppeteer has [instructions for installing on Docker](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker) which I'm doing my best to follow but I'm stuck.

Here's my `.lando.yml` now:
```

  node:
    type: node:12
    globals:
      gulp-cli: latest
    extras:
      - apt-get update
      - apt-get -y install xvfb gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
      - rm -rf /var/lib/apt/lists/*
      - groupadd -r pptruser
      - useradd -r -g pptruser -G audio,video pptruser
      - mkdir -p /home/pptruser/Downloads
      - chown -R pptruser:pptruser /home/pptruser
```

In the Puppeteer document example, they say to do this:
```

# Run everything after as non-privileged user.
USER pptruser

CMD ["google-chrome-stable"]
```

But I don't know how to translate this into something that will work in `.lando.yml`.  As a result, when I try to run puppeteer, I get this error:

```
Error: Failed to launch the browser process!
[1026/084656.108343:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.


```

**Comment by rorymcdaniel** [comment]
@ptmkenny did you ever find a way to do this? I'm also trying to install Puppeteer, only for a different library.

**Comment by ptmkenny** [comment]
@rorymcdaniel No, I didn't.  I switched libraries to one that doesn't use puppeteer.

**Comment by rorymcdaniel** [comment]
I'm using this in a Laravel/PHP project, specifically for the Spatie Browsershot package. I took a few things from their site and then kept playing with it until I came up with this in my .lando.yml. This works now.

```
  appserver:
    type: php:7.3
    env:
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chrome
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libgbm-dev
      - npm install --global --unsafe-perm puppeteer
      - chmod -R o+rx /usr/lib/node_modules/puppeteer/.local-chromium
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome-stable_current_amd64.deb
      - apt-get install -f -y
 ```

I would have preferred a separate node service, that likely would have been cleaner, but this works, so I'm happy.

**Comment by maskedjellybean** [comment]
Does anyone have an example of using Puppeteer via a Node service in order to allow running via Gulp? I already have a Node service and can run `lando gulp`. I'm trying to use https://www.npmjs.com/package/critical which relies on Puppeteer. When I run my Gulp command which in turns runs Critical, I get:

```
Error: Failed to launch the browser process!
/app/web/themes/custom/overlake/node_modules/penthouse/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
```

This error is all over Google, but none of the suggested solutions have worked for me.

**Comment by roberttolton** [comment]
I'm also facing this issue, even following something that seems like it should work:
https://www.cloudsavvyit.com/13461/how-to-run-puppeteer-and-headless-chrome-in-a-docker-container/

```
  node:
    type: node:14
    ssl: false
    build:
      - npm install
    extras:
      - apt-get update -y
      - apt-get install -y \
        fonts-liberation \
        gconf-service \
        libappindicator1 \
        libasound2 \
        libatk1.0-0 \
        libcairo2 \
        libcups2 \
        libfontconfig1 \
        libgbm-dev \
        libgdk-pixbuf2.0-0 \
        libgtk-3-0 \
        libicu-dev \
        libjpeg-dev \
        libnspr4 \
        libnss3 \
        libpango-1.0-0 \
        libpangocairo-1.0-0 \
        libpng-dev \
        libx11-6 \
        libx11-xcb1 \
        libxcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxext6 \
        libxfixes3 \
        libxi6 \
        libxrandr2 \
        libxrender1 \
        libxss1 \
        libxtst6 \
        xdg-utils
```

The Node service docker container just cannot install any of these extra services either due to `Unable to locate package` or `Couldn't find any package by glob` errors.

```
E: Unable to locate package  fonts-liberation
E: Unable to locate package  gconf-service
E: Unable to locate package  libappindicator1
E: Unable to locate package  libasound2
E: Unable to locate package  libatk1.0-0
E: Couldn't find any package by glob ' libatk1.0-0'
E: Couldn't find any package by regex ' libatk1.0-0'
E: Unable to locate package  libcairo2
E: Unable to locate package  libcups2
E: Unable to locate package  libfontconfig1
E: Unable to locate package  libgbm-dev
E: Unable to locate package  libgdk-pixbuf2.0-0
E: Couldn't find any package by glob ' libgdk-pixbuf2.0-0'
E: Couldn't find any package by regex ' libgdk-pixbuf2.0-0'
E: Unable to locate package  libgtk-3-0
E: Unable to locate package  libicu-dev
E: Unable to locate package  libjpeg-dev
E: Unable to locate package  libnspr4
E: Unable to locate package  libnss3
E: Unable to locate package  libpango-1.0-0
E: Couldn't find any package by glob ' libpango-1.0-0'
E: Couldn't find any package by regex ' libpango-1.0-0'
E: Unable to locate package  libpangocairo-1.0-0
E: Couldn't find any package by glob ' libpangocairo-1.0-0'
E: Couldn't find any package by regex ' libpangocairo-1.0-0'
E: Unable to locate package  libpng-dev
E: Unable to locate package  libx11-6
E: Unable to locate package  libx11-xcb1
E: Unable to locate package  libxcb1
E: Unable to locate package  libxcomposite1
E: Unable to locate package  libxcursor1
E: Unable to locate package  libxdamage1
E: Unable to locate package  libxext6
E: Unable to locate package  libxfixes3
E: Unable to locate package  libxi6
E: Unable to locate package  libxrandr2
E: Unable to locate package  libxrender1
E: Unable to locate package  libxss1
E: Unable to locate package  libxtst6
E: Unable to locate package  xdg-utils
ERROR ==> E: Unable to locate package  xdg-utils
```

I've also tried adding Google's DNS servers to my Docker Daemon config, but that hasn't helped at all.

**Comment by Pindagus** [comment]
@roberttolton I don't know why, but your solution didn't work until I made the install a one-liner.

This works for me with critical in gulp:
```
services:
    node:
        build_as_root:
            - apt update
            - apt install -y fonts-liberation gconf-service libappindicator1 libasound2 libatk1.0-0 libcairo2 libcups2 libfontconfig1 libgbm-dev libgdk-pixbuf2.0-0 libgtk-3-0 libicu-dev libjpeg-dev libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libpng-dev libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 xdg-utils
```
