### ISSUE TITLE
Support for Mercure hub?

### ISSUE THREAD

**Issue by yobottehg** [lando/lando#2661]
We are trying to run [api platform](https://github.com/api-platform/api-platform) inside lando.

Currently we are struggling to run the mercure hub inside the lando network. Because Mercure is not an official supported service we tried to run it via the provided docker container like the following:

```
    hub:
        type: compose
        services:
            image: dunglas/mercure
```

This fails with an "ERROR: No container found for hub_1" error message.

We also tried various setups with networks and so on based on the lando compose configuration.
Did someone manage to set this up and can share some insights?

**Comment by pirog** [comment]
Check out the docs on the compose service
https://docs.lando.dev/config/compose.html

In particular check out the "Setting the command" section

**Comment by yobottehg** [comment]
Thanks for the hint @pirog .

I looked up the original dockerfile and start command from mercure [here](https://github.com/dunglas/mercure/blob/master/Dockerfile#L4)

The [original api platform docker-compose](https://github.com/api-platform/api-platform/blob/master/docker-compose.yml#L74) does not use an entrypoint.

So i tried to specify the command like the original dockerfile:

```
    hub:
        type: compose
        services:
            image: dunglas/mercure
            command: "/mercure"
```

or running the main.go directly:

```
    hub:
        type: compose
        services:
            image: dunglas/mercure
            command: "run /app/main.go"
```

Both are running "Scanning to determine which services are ready... Please standby..." which will after some seconds result in `ERROR: No container found for hub_1`

If i try to specify the same with ports:

```
    hub:
        type: compose
        services:
            image: dunglas/mercure
            ports:
                - "1337"
            command: "/mercure"
```

I'm getting a different error:
```
Creating zone_hub_1 ... done
ERROR ==> (HTTP code 500) server error - container 57e48a6a10e2da39acc763ee8b7878f7d1515e4c9f2770da6a430dcad22bd1e3 is not connected to the network lando_bridge_network  
```

**Comment by pirog** [comment]
All docker containers use an entry point, it’s likely in the docker file
not the compose file

**Comment by iluuu1994** [comment]
This worked for me.

```yml
services:
    mercure:
        app_mount: false
        services:
            command: caddy run -config /etc/caddy/Caddyfile.dev
            environment:
                MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
                MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
                SERVER_NAME: ':80'
            image: dunglas/mercure
            ports:
                - 3000:80
        type: compose
```

Exposed to port `3000` so you can connect to it with the browser (http, not https). On the server you'll want to connect with `mercure` (also http). You might also be able to use `proxy` to get rid of the hard-coded port.
