### ISSUE TITLE
Build_as_root running after restart

### ISSUE THREAD

**Issue by Eldair** [lando/lando#2674]
**Tell us about your setup**

v3.0.14 on windows 10 via wsl 2
Docker engine 20.10.0-beta1

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

*Example:*

```yml
name: reportz
recipe: laravel
proxy:
  appserver_nginx:
    - dashboard.test
config:
  php: '7.4'
  via: nginx
  cache: redis
  database: mysql:8.0
  xdebug: false
  webroot: public
services:
  appserver:
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_15.x | bash -
      - apt-get install -y nodejs
      - apt-get install -y ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

```bash
lando poweroff
lando start
lando restart
```

**Tell us about the error you got**

Build as root steps always runs

![image](https://user-images.githubusercontent.com/470003/97989440-d34e4780-1dde-11eb-801d-a735706bf392.png)

At the end I get a warning that some build steps possibly failed. Could it be because of composer 2 & `hirak/prestissimo`?

![image](https://user-images.githubusercontent.com/470003/97989828-64252300-1ddf-11eb-9258-31c4a77d331c.png)
