### ISSUE TITLE
Xdebug with lando 3.0.18

### ISSUE THREAD

**Issue by jhoopes** [lando/lando#2687]
Lando version 3.0.18 on Windows 10.  Running docker desktop 2.5

I am running this through the WSL2 backend, but the problem seems independent of WSL 2 itself, so the configuration file includes some extra items for the lando host ip to get it to see my windows host instead of the WSL host.

```yml
name: app
recipe: laravel
config:
  php: '7.4'
  via: nginx
  webroot: public
  xdebug: true
  composer_version: 1.10.13
services:
  appserver:
    xdebug: true
    composer:
      phpunit/phpunit: "*"
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
        LANDO_HOST_IP: "host.docker.internal"
        XDEBUG_CONFIG: "remote_enable=1 remote_host=host.docker.internal"
  database:
    type: mysql:8.0
    creds:
      user: lando
      password: lando
      database: primary
    portforward: 3330
    config:
      database: .lando/my_custom.cnf
excludes:
  - vendor
  - node_modules
  - .idea
  - .git

```

The issue I'm having is getting xdebug to load as an extension in the web / php fpm side.  With the above config, the CLI output when running `php -v` shows the following:

```
PHP 7.4.12 (cli) (built: Nov  5 2020 20:24:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
```

which shows xdebug is loaded normally.  But when I run phpinfo through just a basic php file on the public folder, there is no xdebug section or module information showing that it's loading.  Additionally the loaded conf files doesn't include the xdebug.ini file.  Here is what it shows on a fresh build:

![image](https://user-images.githubusercontent.com/3297518/98731268-1a9a8200-2363-11eb-877e-a9d06734334b.png)

going into the conf.d directory I find that there is indeed a docker-php-ext-xdebug.ini file, but it is owned by root instead of being owned by www-data

![image](https://user-images.githubusercontent.com/3297518/98731334-369e2380-2363-11eb-9aeb-857083e33ced.png)

After changing the owner of this file through

```bash
lando ssh -u root
chown www-data:www-data /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
```

and then restarting the containers, this then shows the xdebug extension being loaded through the web side of phpinfo.  Upon starting of the containers I do also see a message saying "xdebug is already loaded" which is lando probably trying to inject the extension first, and then this ini file being loaded next.  So I'm wondering if there's another config setting or file that I'm missing somewhere or some other setting?

Here is part of the phpinfo after restarting:
![image](https://user-images.githubusercontent.com/3297518/98731920-0f942180-2364-11eb-84f4-e97bf25f56f3.png)

Thanks for any help.  I might get some time to create a test for this, but am pretty busy at the moment.

**Comment by anibalsanchez** [comment]
Same issue here. Suddenly, all the local setups are not debugging. I've been testing different Lando versions but the problem remains. I have no clue how to solve it, none of the usual suspects seems to be the issue.

**Comment by anibalsanchez** [comment]
In my case, I'm on Ubuntu 20.10. Node v14.15.0. Docker version 19.03.13.

**Comment by anibalsanchez** [comment]
In my case, this issue #1301 gave me the fix:

```
sudo iptables -A INPUT -p tcp -d 0/0 -s 0/0 --dport 9000 -j ACCEPT
```

For some reason, the port has been filtered.... I'm puzzled what enacted the filter. It took me 6 hours of debugging!

**Comment by labboy0276** [comment]
@jhoopes For me it was Xdebug 3 causing havoc.

I did this in my lando setup and I can debug again:

```
services:
  appserver:
    type: php
    build_as_root:
      - pecl uninstall xdebug
      - pecl install xdebug-2.9.8
```
