### ISSUE TITLE
Question | Laravel | Imagick JPG to PDF Conversion  | Operation not allowed by the security policy

### ISSUE THREAD

**Issue by StanBarrows** [lando/lando#2689]
Hey there

I recently switched to Lando as my main development environment but currently facing some issues with the PHP Imagick library.
 
**Error Message**

```
 attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408
```

I know there are some changes required within the **/etc/ImageMagick-6/policy.xml** file. But how am I able to edit those file?

```
  appserver:
    build_as_root:
      - apt update -y && apt install nano
      - apt update -y && apt install sudo nano

```

I've tried to install these libraries to edit the file by myself but somehow it's not quite working because I do not have the _sudo_ password.

Is there any other solution?

Cheers
Sebastian

**PHP Code**

```
$file = Storage::disk(config('filesystems.default'))->get($get_path);

$image = new \Imagick();
$image->readImageBlob($file);
$image->setImageFormat($pdf_extension);

$image-> writeImage($file_path)
```

**lando.yml**

```
name: www-app
recipe: laravel
config:
  php: 7.4
  via: nginx
  webroot: public
  xdebug: false

services:
  database:
    type: mysql:8.0
    portforward: 3306
```

**Comment by drubb** [comment]
Here's at least a temporary workaround using a custom lando command:

Add this to the tooling section in lando.yml:

```
tooling:
  fix-imagick:
    service: appserver
    description: Update Imagick policy for PDF
    cmd: sed -i 's/<policy domain="coder" rights="none" pattern="PDF" \/>/<policy domain="coder" rights="read|write" pattern="PDF" \/>/g' /etc/ImageMagick-6/policy.xml
    user: root
```
You can run this with `lando fix-imagick`.

Basically this command will update the policy file to allow PDF read/write access. It's temporary because the file will be reset whenever the container is stopped.
For other options take a look at Lando's build_as_root / run_as_root commands used to run se.d
