### ISSUE TITLE
tooling dir not changing work directory

### ISSUE THREAD

**Issue by com2** [lando/lando#2696]
To reproduce: 
```
name: testtoolingdir
recipe: wordpress
config:
  webroot: wordpress
services:
  pma:
    type: phpmyadmin
proxy:
  pma:
    - pma-fotowp.lndo.site
tooling:
  testing:
    service: appserver
    dir: /app/wordpress
    cmd: pwd
```
Result: 
```
$ lando testing
/app
```
Expected result:
 ```
$ lando testing
/app/wordpress
```
