### ISSUE TITLE
Open up port 6001 for laravel-websockets (php via cli service)

### ISSUE THREAD

**Issue by eminos** [lando/lando#2697]
I'm trying to figure out how to run laravel-websockets with lando.
https://beyondco.de/docs/laravel-websockets/getting-started/introduction
laravel-websockets is a PHP CLI Ratchet application running on port 6001.

This is my lando file:

```yaml
name: lintex
recipe: laravel
config:
  webroot: public
  php: '7.4'
  composer_version: '2.0.4'
  via: nginx
  database: mysql:8.0
  cache: redis
excludes:
  - vendor
  - node_modules
proxy:
  appserver_nginx:
    - lintex.local
    - "*.lintex.local"
  websockets:
    - lintex.local:6001
services:
  database:
    type: mysql:8.0
    portforward: 3306
    creds:
      user: lintex
      password: lintex
      database: lintex
  horizon:
    type: php:7.4
    via: cli
    command: php /app/artisan horizon
  websockets:
    type: php:7.4
    via: cli
    portforward: 6001
    ports:
      - '6001'
    command: php /app/artisan websockets:serve
bindAddress: "0.0.0.0"
```

It seems the port 6001 is not accessible from the host.
The websockets service also needs to be accessable from the other services.

**Comment by dustinleblanc** [comment]
@eminos the way the proxy works, it is proxying port 6001 inside the container to ports 80/443 (or whatever ports you have the proxy bound to) on the host, so what you really want to do is bind it to a DIFFERENT domain than the nginx appserver, like `ws-lintext.local` or `ws.lintex.local` etc. 

This definitely isn't intuitive when the standard way to run stuff is `localhost:newport` but its how things work with our proxy.

**Comment by eminos** [comment]
Thank you @dustinleblanc ! I do have some more questions. I wrote to you on the Laravel Discord. (Couldn't get access to Lando Slack.)

**Comment by dustinleblanc** [comment]
Hey @eminos! I don't see the question, just made sure to login, my username over there is `dustin#0971`. I might have signed up with a couple of accounts over time as discord is weird with accounts/emails, but you can hit me there!

**Comment by eminos** [comment]
After a long chat with Dustin he helped me figure it all out! Thanks Dustin!

So for anyone wondering or having the same issue...
The key seems to be to proxy the websockets to a custom subdomain, and access websockets through that subdomain on port 80/443 instead. Also I'm running `php artisan websockets:serve --port=80`, which is the default proxy port, and makes so there is no need for `ws.lintex.local:6001`.

This is my `.lando.yml`. I hope it might help someone stumbling upon this issue.
```yaml
name: lintex
recipe: laravel
config:
  webroot: public
  php: '7.4'
  ssl: true
  composer_version: '2.0.4'
  via: nginx
  database: mysql:8.0
  cache: redis
excludes:
  - vendor
proxy:
  appserver_nginx:
    - lintex.local
  websockets:
    - ws.lintex.local
services:
  database:
    type: mysql:8.0
    portforward: 3306
    creds:
      user: lintex
      password: lintex
      database: lintex
  horizon:
    type: php:7.4
    via: cli
    command: /app/lando.horizon.sh
    overrides:
      depends_on:
        - database
  websockets:
    type: php:7.4
    via: cli
    ssl: true
    command: /app/lando.websockets.sh
    scanner: false
    overrides:
      depends_on:
        - database
bindAddress: "0.0.0.0" # that probably goes in your global .lando/config.yml file
```
