### ISSUE TITLE
Database service fails

### ISSUE THREAD

**Issue by maddentim** [lando/lando#2700]
**Tell us about your setup**

Lando v3.0.19 on Mac 10.15.7

**Tell us about your `.lando.yml`**

```yml
name: cheried7
recipe: drupal7
config:
  webroot: .
  php: '7.3'
services:
  phpmyadmin:
    type: phpmyadmin
    hosts: []
  appserver:
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
```

**Tell us about the command you were running**

```bash
lando rebuild -y
```

**Tell us about the error you got**

Well, turns out that Docker has a storage limit setting. I had written up a long issue here and then it occurred to me that I should check Docker Dashboard settings. Of course for a long time I was blaming the new version and reinstalling 3.0.14 which did nothing. Destroying and recreating containers. Generally pulling ones hair! ¯\_(ツ)_/¯

Looking at the error messages and documentation, I did not see a suggestion to check my settings in Docker. A section in the troubleshooting might be helpful to some souls or even better if a error message appeared saying to check your Disc Image Size setting (because who reads the manual!)

Thanks for a great thing you all have built!
