### ISSUE TITLE
Update SQLite to Drupal 9 minimally required 3.26

### ISSUE THREAD

**Issue by jcandan** [lando/lando#2703]
*Lando v3.0.19 on macOS*

**The `.lando.yml`**

```yml
name: my-project
recipe: drupal9
config:
  webroot: web
services:
  appserver:
    overrides:
      environment:
        SIMPLETEST_BASE_URL: "https://appserver"
        SIMPLETEST_DB: "sqlite://localhost/tmp/db.sqlite"
        MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless", "--no-sandbox"]}}, "http://chrome:9515"]'
        DRUSH_OPTIONS_ROOT: '/app/web'
        DRUSH_OPTIONS_URI: 'http://my-project.lndo.site'
  chrome:
    type: compose
    app_mount: false
    services:
      image: drupalci/webdriver-chromedriver:production
      command: chromedriver --log-path=/tmp/chromedriver.log --verbose --whitelisted-ips=
  node:
    type: node:12
tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd: /app/vendor/bin/phpunit --configuration /app/web/core/phpunit.xml.dist
```

With `lando composer require drupal/core-dev` to provide `phpunit`.

**The command to run**

```bash
lando phpunit web/core/modules/node/tests/src/Kernel/NodeBodyFieldStorageTest.php 
```

**The error**

```
The database server version 3.16.2 is less than the minimum required version 3.26.
```

**General bug info**

With the release of [SQLite version requirements raised to 3.26](https://www.drupal.org/node/3119118) , Drupal 9 PHPUnit tests with SQLite require version 3.26 minimum. The Drupal9 recipe comes with 3.16.0.

The relevant test can be found at https://github.com/lando/lando/pull/2704.
