### ISSUE TITLE
Tooling on host machine

### ISSUE THREAD

**Issue by xXCalleManXx** [lando/lando#2705]
Normally when writing a custom tooling command, it will be executed in a service container.
Is it possible to execute a command on the host machine?

My specific scenario.
I need to copy a database dump file from a remote server with the scp command. After the database dump file is downloaded I want to run `$ lando db-import <filename>`. So with a single command like `$ lando fresh-db-import`, I can get a fresh database.

The cmd option in the lando.yml file would look something like:
```
tooling:
  fresh-db-import:
    service: :host
    description: Import a fresh database from remote host
    cmd: "scp backup@remote.host.net:/backup/backup.sql . && lando-db-import backup.sql && rm backup.sql"
```
