### ISSUE TITLE
Pick up Cluster Configurations from Dedicated P.sh Config

### ISSUE THREAD

**Issue by chris-archer-whisky** [lando/lando#2710]
Hi, we use Platform.sh for hosting sites and are using the P.sh recipe but are having trouble replicating prod as our environment is made up of 3 nodes we need to increment the db by 3 locally we have added
```
services:
  db:
    config:
      database: custom/my-custom.cnf
```
and in that file we have
```
[mysqld]
auto_increment_increment = 3
```
But the change is not been picked up, it only works if you use a the Drupal7 recipe.  After chatting with P.sh they say its not possible to override these changes.
