### ISSUE TITLE
Database lost after restart

### ISSUE THREAD

**Issue by mrtronje** [lando/lando#2711]
Hi

When I stop lando and start lando again my microsfot sql server database is lost. 

lando.yml
```
name: my-project
lando 
excludes: 
    - vendor
    - node_modules

recipe: lemp

services:
    appserver:
        build_as_root:
            - apt-get update -yqq
            - apt-get install -y apt-transport-https curl
            - curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
            - curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list
            - apt-get update -yqq
            - ACCEPT_EULA=Y apt-get install -yqq msodbcsql17 unixodbc-dev
            - ACCEPT_EULA=Y pecl install pdo_sqlsrv
            - docker-php-ext-enable pdo_sqlsrv
        type: php:7.4

    database:
        type: mssql
        portforward: true
        creds:
            user: sa
            password: *********
    node:
        type: node

tooling:
    yarn:
        service: node
```
OS: macOS Sur
Lando Version: 3.0.19
Docker Desktop: 2.5.0.0

Do I need to take additional steps to persist the database? Or any idea why the database is not persisted?

**Comment by iluuu1994** [comment]
We still have this issue. Commenting to remove the stale label.

**Comment by iluuu1994** [comment]
Oh, I noticed this issue is not accurate. We don't lose the database after `stop`/`start` but rather `rebuild`. According to the docs a rebuild should not destroy the volume of the given containers. This seems to work when using MySQL or Postgres in other projects but for Sql Server it does not work.

**Comment by ccjjmartin** [comment]
Same issue here, I am using the pantheon recipe.  I had just imported the database, did a rebuild, then connected to the database to see what was there, and all the tables were gone.  The docker volume still exists and nothing appeared in the rebuild output showing the volume was deleted or recreated (as with lando destroy).  It seems like the data should still be there but it is being lost somehow.

This happens on other recipes too but I am currently working on a Pantheon one.

**Comment by mattneal-stafflink** [comment]
I don't have anything to contribute but I just wanted to say that I'm experiencing the same thing using the WordPress recipe.

**Comment by awm086** [comment]
same here .. I am experincing the same issue. One way to get over it, is to override the database service with:
```
  database:
    portforward: 33074
    ports:
      - "3306"
    type: compose
    volumes:
      db_data: {}
    services:
      image: mariadb:10.6.5
      command: docker-entrypoint.sh mariadbd
      volumes:
        - db_data:/var/lib/mysql
        - .lando/my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
      restart: always
      ports:
        - "3306"
      environment:
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'true'
        MARIADB_DATABASE: 'pantheon'
        MARIADB_USER: 'pantheon'
        MARIADB_PASSWORD: 'pantheon'
        ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_DATABASE: 'pantheon'
        MYSQL_PASSWORD: 'pantheon'
        LANDO_EXTRA_DB_EXPORT_ARGS: '--protocol=socket'
        LANDO_EXTRA_DB_IMPORT_ARGS: '--protocol=socket'
        LANDO_NEEDS_EXEC: 'DOEEET'
```

**Comment by mattneal-stafflink** [comment]
@awm086 I'm new to docker, what exactly is physically happening here? How does this stop it from losing the data? Am I right in assuming you're using another DB somewhere that doesn't get destroyed on rebuild?

**Comment by awm086** [comment]
here is another configuration that's possibly can fix it for now without having to use compose.
```
  database:
    volumes:
      db_data: { }
    build_as_root:
      - cp  /app/.lando/my_custom.cnf /etc/mysql/conf.d/my_custom.cnf
    overrides:
      volumes:
        - db_data:/var/lib/mysql

```
@mattneal-stafflink the issue here is volume mounting that is used to persist data between the container and the host. This is my understanding.
