### ISSUE TITLE
Tooling on the host machine

### ISSUE THREAD

**Issue by xXCalleManXx** [lando/lando#2716]
New feature to run tooling directly on the host machine instead of inside a container. This would help combining multiple toolings and downloading sql dumps or other files from a remote host.

A way to do this is to set the service to be the host. Example:
```
tooling:
  host-tool:
    service: host
    description: Do stuff on host
    cmd: 'scp root@stage.server.net:/data/dump.sql . && lando db-import dump.sql'
  npm-install:
    service: node
    description: Install node_modules
    cmd: 'npm i'
  composer-install:
    service: node
    description: Install composer
    cmd: 'composer install'
  vendor-reinstall:
    description: Reinstall all vendors
    cmd:
      - host: "rm -rf node_modules && rm -rf vendor"
      - host: "lando composer-install"
      - host: "lando npm-install"
```

If this would be the solution, lando have to be able to differentiate between _host_ and any other service name. 

**Describe alternatives you've considered**
An alternative to this could be creating a service called host, which have the host mapped into it. In that way the service can use the samme commands as the host and use the hosts ssh keys.

Hope it make sense and is useful for other than me.
