### ISSUE TITLE
Support Xdebug 3

### ISSUE THREAD

**Issue by rabauss** [lando/lando#2718]
Xdebug 3 is out and comes with a lot of performance optimization - see: https://xdebug.org/announcements/2020-11-25

I'm not sure which PHP Images should get the Update - what do you think?
See the upgrade guide for all necessary steps: https://xdebug.org/docs/upgrade_guide

The Update also supports PHP 8, so it's related to: https://github.com/lando/lando/issues/2660

**Comment by labboy0276** [comment]
Xdebug 3 is included with the newer docker images.  If you do a lando rebuild, it should be there.

**Comment by rabauss** [comment]
That's nice! But unfortunately the settings have to change:

To make sure that just Step Debugging is active, instead of:

````
xdebug.remote_enable=1
xdebug.default_enable=0
xdebug.profiler_enable=0
xdebug.auto_trace=0
xdebug.coverage_enable=0
````
You now only do:
````
xdebug.mode=debug
````
Or, on the command line:
````
export XDEBUG_MODE=debug
php script-name.php
````

see: https://xdebug.org/docs/upgrade_guide

**Comment by Tigatok** [comment]
@rabauss Trying to get this to work with a D8 recipe, how are you setting your php.ini file? Under appserver, or under the top-level config?

**Comment by rabauss** [comment]
Oh, seems good to me!
It was too late for me this night and I did not see the obvious duplicate of `xdebug.start_with_request`

**Comment by ds-santos** [comment]
I try the @Tigatok  solution in drupal 8 installatio with no success :(

**Comment by labboy0276** [comment]
@pirog I can confirm @Tigatok solution works

**Comment by ds-santos** [comment]
Hi @Tigatok, thanks for disponibility to help me :) , luckily I have already managed to make the wings work again

The configurations I have used  for drupal 8 installation + vscode are:

/.vscode/launch.json
`{
 "version": "0.2.0",
 "configurations": [
   {
     "name": "Listen for XDebug",
     "type": "php",
     "request": "launch",
     "port": 9003,
     "pathMappings": {
       "/app/": "${workspaceFolder}"
     }
   }
 ]
}
`
/home/ds/projects/drupaldemo/.vscode/php.ini

`[PHP]
 
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.client_host = ${LANDO_HOST_IP}
xdebug.log = /tmp/xdebug.log
xdebug.mode = debug
xdebug.start_with_request = yes   `

**Comment by pirog** [comment]
Support for xdebug 2/3 will be in the next release, which should be out sometime in the next hour. here are the docs about how it will work
https://docs.lando.dev/config/php.html#configuration

**Comment by tsega** [comment]
@ds-santos what does your `.lando.yml` file look like? I've used the following but Xdebug is now showing on `phpinfo()` page:

```
name: test
recipe: drupal8

config:
  webroot: web

services:
  appserver:
    type: php
    config:
      php: .vscode/php.ini
```

**Comment by anibalsanchez** [comment]
For the record, the alternative Xdebug 3 configuration for VSCode / felixfbecker/vscode-php-debug:

```
xdebug.mode = debug
xdebug.start_with_request = yes

;; xdebug.client_host = ${LANDO_HOST_IP}
;; Alternative to avoid binding the IP
xdebug.discover_client_host = true

xdebug.client_port = 9099
```

```json
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9099,

            "pathMappings": {
                "/app/www": "${workspaceRoot}/www"
            }
        },
```

Please, note that `xdebug.start_with_request = trigger` doesn't work on VSCode / felixfbecker/vscode-php-debug.

**Comment by ds-santos** [comment]
> @ds-santos what does your `.lando.yml` file look like? I've used the following but Xdebug is now showing on `phpinfo()` page:
> 
> ```
> name: test
> recipe: drupal8
> 
> config:
>   webroot: web
> 
> services:
>   appserver:
>     type: php
>     config:
>       php: .vscode/php.ini
> ```

My ."lando.yml"

> name: drupal
> recipe: drupal8
> config:
>   php: '7.4'
>   via: apache
>   database: mysql:5.7
>   webroot: web
> services:
>   database:
>     creds:
>       user: drupal
>       password: drupal
>       database: database
>   appserver:
>     webroot: web
>     xdebug: true
>     config:
>       php: .vscode/php.ini

**Comment by tsega** [comment]
Thanks @ds-santos, I was missing that `xdebug: true` part. This is what my currently working setup looks like:

`.lando.yml`

```
name: d8
recipe: drupal8
config:
  webroot: web
services:
  appserver:
    type: php
    xdebug: true
    config:
      php: .lando/php.ini
```

`.vscode/php.ini`

```
[PHP]

; Xdebug
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.client_host = ${LANDO_HOST_IP}
xdebug.log = /tmp/xdebug.log
xdebug.mode = debug
xdebug.start_with_request = yes
```

`.vscode/launch.json`

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9003, // Notice: Default port changed to 9003
      "log": true,
      "pathMappings": {
        "/app/": "${workspaceFolder}",
      }
    }
  ]
}
```

**Comment by andreityuhai** [comment]
I there an option to force using xdebug 2 at lando while it's not officially supported?

**Comment by pirog** [comment]
version 3 is officially supported as of the release last night
https://github.com/lando/lando/issues/2718#issuecomment-737539280

**Comment by fmitchell** [comment]
This worked for me PHPStorm 2020.3, drupal9

```
name: foo
recipe: drupal9
config:
  webroot: ./web
  php: '7.4'

services:
  appserver:
    xdebug: true
    config:
      php: config/php.ini
```

config/php.ini
```
; php.ini file for use with lando locally
; to avoid out of memory errors
memory_limit = -1
; Xdebug
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.client_host = ${LANDO_HOST_IP}
xdebug.log = /tmp/xdebug.log
xdebug.mode = debug
xdebug.start_with_request = yes
```

I also made sure to choose the right docker image in my CLI setup: https://www.evernote.com/l/AOyDM2RT8ENO5LfrAXKzbdL5kRft4k_BpW0

Optional: I also have this in my lando file to switch xdebug off and on:
```
tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root

  xdebug-off:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root
```

**Comment by tsega** [comment]
@fmitchell that optional xdebug on/off is something I have been looking for. How do you use it?

**Comment by fmitchell** [comment]
@tsega `lando xdebug-off` will turn it off. When you want to use it again, `lando xdebug-on`. It is cribbed from: https://github.com/AaronFeledy/lando-examples/blob/master/xdebug/.lando.yml

His version handles whether your lando is apache2 or php-fpm

**Comment by tsega** [comment]
This is awesome! 🔥 

Since discovering how Drupal's performance is hit so badly when xdebug is enabled, I've been looking for such a command to enable/disable it with minimum fuss. 

Thanks again!

**Comment by Tigatok** [comment]
For nginx, the tooling is similar

```
tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root
```

**Comment by generalredneck** [comment]
wanna throw out there that the documentation is still lagging behind over at https://docs.lando.dev/guides/lando-with-vscode.html#debugging-phpunit

**Comment by pirog** [comment]
@dustinleblanc ^ i think you're the best person to do this

**Comment by pirog** [comment]
NM it looks like @RichardDavies already got to it: https://github.com/lando/lando/pull/2741/files

@dustinleblanc could you just do a review of that PR and merge?

**Comment by dustinleblanc** [comment]
Will test with a fresh D8 site and see what's what. I never use the debugger so I guess I am a good canidate to ingest the doc

**Comment by paulostarling** [comment]
I updated my Lando, I changed the port to 9003 and it works for Drupal 9.
I'll try now to debug PhpUnit.

**Comment by paulostarling** [comment]
Which port do we need to use to debug PhpUnit? Currently I'm using 9001 but it is not working.

**Comment by jjcarrion** [comment]
Same problem here, I changed the .lando.yml to make it work with xdebug3 on version 3.0.21-1, everything was working fine. But now that I have updated to 3.0.23-1 and xdebug stopped to work. I have downgraded to 3.0.21-1 for now.

**Comment by rabauss** [comment]
CLI debugging is only working for me with custom php.ini
```
xdebug.start_with_request = yes
```

**Comment by juampynr** [comment]
I ended up having to do a mix of https://github.com/lando/lando/pull/2741 plus feedback provided here in order to get it working at PHPStorm (even for Drush commands):

lando v3.0.23

.lando.yml
```
services:
  appserver:
    xdebug: true
    config:
      php: .lando/php.ini
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
```

.lando/php.ini
```
[PHP]
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
xdebug.mode = debug
xdebug.client_host = ${LANDO_HOST_IP}
xdebug.client_port = 9003
xdebug.start_with_request = yes
xdebug.log = /tmp/xdebug.log
```

**Comment by uberhacker** [comment]
@juampynr: Nice!  I can confirm this works.

**Comment by jaybabak** [comment]
**For VSCODE**
Port needs to default to 9000 to work with the xdebug extension using the following:
`xdebug.client_port=9000`

Reference:
https://github.com/xdebug/vscode-php-debug

For XDebug v3.x.x:
```
xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.client_port = 9000
```

For XDebug v2.x.x:
```
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
```

**Comment by zahardev** [comment]
Now the default Xdebug port is 9003 - https://xdebug.org/docs/upgrade_guide#Step-Debugging. So for me just changing the debug port in IDE to 9003 fixed the problem.

**Comment by jnfDev** [comment]
Unable to configure Lando with Xdebug 3 with WSL2. Version 2 of Xdebug works fine, but this new one was impossible to configure out. I need help, here my current configuration:

php.ini
```
[PHP]
; Xdebug
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.client_host = ${LANDO_HOST_IP}
xdebug.log = /tmp/xdebug.log
xdebug.mode = debug
xdebug.start_with_request = yes
```
.lando.yml

```
name: my-wpsite
recipe: wordpress
services:
  appserver:
    webroot: .
    xdebug: true
    config:
      php: .vscode/php.ini
    overrides:
      environment:
        LANDO_HOST_IP: host.docker.internal
```

**Comment by jnfDev** [comment]
> I there an option to force using xdebug 2 at lando, while version 3 is not officially supported?

Yes, you can do something like this:

```
services:
  appserver:
     #other-service's directives
     build_as_root:
      - pecl uninstall xdebug
      - pecl install xdebug-2.9.8
```

**Comment by rabauss** [comment]
"Xdebug's default debugging port has changed from 9000 to 9003."
see: https://xdebug.org/docs/upgrade_guide#Step-Debugging

**Comment by tormi** [comment]
We have the following configuration for Xdebug 3, which introduces the `lando xdebug` tool. Modes (incl. `profile`) can be defined in the .lando/php.ini file, default value is `debug`. `lando xdebug off` turns Xdebug off.

`.lando.yml`

```
config:
  xdebug: false
  config:
    php: .lando/php.ini

services:
  appserver:
    overrides:
      environment:
        XDEBUG_MODE:
        PHP_IDE_CONFIG: "serverName=appserver"

tooling:
  xdebug:
    description: Loads Xdebug in the mode defined in the .lando/php.ini file. Run `lando xdebug off` to turn Xdebug off.
    cmd:
      - appserver: /app/.lando/xdebug.sh
    user: root
```

`.lando/php.ini`
```
; Valid Xdebug modes: https://xdebug.org/docs/all_settings#mode.
xdebug.mode = debug
```

`.lando/xdebug.sh`
```
#!/bin/bash

if [ "$#" -ne 1 ]; then
  docker-php-ext-enable xdebug
  pkill -o -USR2 php-fpm
  echo "Xdebug is loaded in the mode defined in the .lando/php.ini file."
  echo "Valid modes: https://xdebug.org/docs/all_settings#mode."
else
  rm -rf /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  pkill -o -USR2 php-fpm
  echo "Xdebug is turned off."
fi
```

**Comment by tormi** [comment]
Waiting for the feedback for my proposal here to get things even easier: https://github.com/lando/lando/issues/1668#issuecomment-770186410

It would allow to load Xdebug modes on the fly via `lando xdebug <mode(s)>`, f.ex `lando xdebug debug,develop`.

**Comment by Tigatok** [comment]
@jnfDev Did you ever figure out your WSL2 stuff?

**Comment by tormi** [comment]
> Waiting for the feedback for my proposal here to get things even easier: https://github.com/lando/lando/issues/1668#issuecomment-770186410
> 
> It would allow to load Xdebug modes on the fly via `lando xdebug <mode(s)>`, f.ex `lando xdebug debug,develop`.

This is working now: https://github.com/lando/lando/issues/1668#issuecomment-772829423.

**Comment by brandonratz** [comment]
@Tigatok I have WSL2 working w/ PHP Storm with the following

Changed port in IDE to 9003

`/app/php.ini`
```
;Xdebug2
xdebug.max_nesting_level=256
xdebug.show_error_trace=1
xdebug.show_exception_trace=0
xdebug.collect_params=3
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.remote_connect_back=0
xdebug.remote_host=${LANDO_HOST_IP}
xdebug.remote_port=9000
xdebug.idekey=PHPSTORM
xdebug.var_display_max_children=3
;xdebug.remote_log=/app/xdebug.log

;Xdebug3
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
xdebug.mode = debug
xdebug.client_host = ${LANDO_HOST_IP}
xdebug.client_port = 9003
xdebug.start_with_request = yes
;xdebug.log = /app/xdebug.log
```

I left my Xdebug2 settings in the ini as they don't seem to cause any conflict

Note: I also have in `.lando.yml`
```
appserver:
  overrides:
    environment:
      LANDO_HOST_IP: "host.docker.internal"
      XDEBUG_CONFIG: "remote_enable=1 remote_host=host.docker.internal"
```

I am just now fixing this with Xdebug3 so I don't know if some of my past settings are irrelevant. I was able to add those Xdebug3 settings to my php.ini and get it working.

**Comment by tormi** [comment]
@brandonratz , I'm on Mac and the only thing needed from the above for Xdebug 3 setup is `xdebug.start_with_request = yes` and even that's only if using PhpStorm.

Could you to try out this recipe and report back if it's working with WSL2: https://github.com/lando/lando/issues/1668#issuecomment-772829423?

**Comment by brandonratz** [comment]
@tormi I added the following to `.lando.yml`

```
tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root
```

```
❯ lando xdebug-on
Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(
Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(

warning: xdebug (xdebug) is already loaded!
```

```
❯ lando xdebug-off
rm: cannot remove '/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini': No such file or directory
```

**Comment by tormi** [comment]
@brandonratz , there's a readme part as well in that recipe. Try using `lando xdebug <mode>` instead of `lando xdebug-on / off`.

**Comment by brandonratz** [comment]
@tormi My apologies, the link to your comment bugged out when I initially clicked on it.

I can confirm your shell script and tooling setup work in my WSL2 environment!

**Comment by Tigatok** [comment]
It appears to me that it is very inconsistent. I sometimes have to reboot my machine and `lando rebuild` multiple times before Xdebug will work.

I think this is a port/ip networking related issue where perhaps some times things pick up and sometimes they don't? Anyone with a similar experience?

**Comment by Tigatok** [comment]
> > It appears to me that it is very inconsistent.
> 
> @Tigatok, are you referring to [#1668 (comment)](https://github.com/lando/lando/issues/1668#issuecomment-772829423) recipe?

Ah sorry I should have been clear. The entire thread (and many others online) in terms of getting the Xdebug in the container to listen seems to be inconsistent. Specifically which part, I am not 100% sure. That being said I trust the tooling you have in your comment is working just fine.

**Comment by maskedjellybean** [comment]
Just wanted to add that none of this worked for me with Xdebug 3 until I added to `.lando.yml`:

```
services:
  appserver:
    overrides:
      environment:
        XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003 start_with_request=yes log=/app/lando/logs/xdebug.log"
        XDEBUG_MODE: "debug"
```

The key to figuring it out was to look at phpinfo(). Although the Xdebug section matched what I had configured in `php.ini`, `XDEBUG_CONFIG` and `XDEBUG_MODE` did not. I'm assuming it was configuration coming from Lando. Apparently this takes priority over the Xdebug section?
