### ISSUE TITLE
Lando 3.22 -- PHP version: ERROR ==> Invalid Version: 8.0 

### ISSUE THREAD

**Issue by sebastienserre** [lando/lando#2722]
Hello,

I've just installed lando 3.22 over the 3.21 with deb package on Ubuntu 20.04

Here's my config file:
```
name: main
recipe: wordpress
config:
  php: 8.0
  webroot: .
  xdebug: true
  database: mariadb
  config:
    php: php.ini
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    hogfrom:
    - appserver
  redis:
    type: redis
    portforward: true
tooling:
  composer:
    service: appserver
proxy:
  pma:
    - pma-main.lndo.site
  mailhog:
    - mailhog-main.lndo.site
events:
   post-start:
    - appserver: wp core update
    - appserver: wp plugin update --all
    - appserver: wp theme update --all
    - appserver: wp language core update
    - appserver: wp language plugin update --all
    - appserver: wp language theme update --all

```
and then:
```
$ lando rebuild --y
ERROR ==> Invalid Version: 8.0 
$
```

When I comment the PHP line in the config file and rebuild, it built an environment with php 7.3

**Comment by pirog** [comment]
@mikemilano any insight here? Not sure why this wouldnt work

**Comment by pirog** [comment]
FWIW i was able to get our example wordpress project working with

```yaml
name: lando-wordpress
recipe: wordpress
config:
  webroot: wordpress
  php: "8.0"
```

**Comment by pirog** [comment]
@sebastienserre its worth pointing out that the version in yaml needs to be a string so `"8.0"` or `'8.0'` is not the same as `8.0` which is probably cast to integer `8`

**Comment by sebastienserre** [comment]
OH yes @pirog, you'right, it's working with "8.0" but why does adding 
```
name: lando-wordpress
recipe: wordpress
config:
  webroot: wordpress
  php: 7.3
```
is working .... here no problem. I maybe exploited a bug :-)

**Comment by pirog** [comment]
@sebastienserre its not a bug. this is just how YAML is parsed if you dont explicitly tell it what type of thing your data is.

Its a good practice to remember that versions are always strings and not numbers so you always want to wrap them in quotes.

**Comment by jigarius** [comment]
Cool! Adding quotes to `"8.0"` makes it work.

Surprisingly, typing `php: 7.4` (no quotes around the version) works. Maybe it's the way the YAML parser works, but thinking aloud, either `8.0` without quotes should also work or `7.4` without quotes should also not work (to standardize things).

**Comment by jitujain** [comment]
recipe: drupal9
config:
  webroot: web
  via: nginx
  php: "8.0"
  database: mysql:8.0
  
  Error: php version 8.0 is not supported 
  This is not working. Can anyone help me?

**Comment by mashirulcts** [comment]
@ijf8090 I am also facing the same issue white trying to run lando rebuild for php version 8.0. Could you please let me know if you found any solution to fix that.

`ecipe: drupal9
  name:xyz
  config:
    webroot: docroot
    php: "8.0"
    database: mysql:5.7
    drush: ^9`

**Comment by labboy0276** [comment]
I am unable to reproduce @mashirulcts.  I used this recipe:

```
name: lando-rando
recipe: drupal9
config:
  webroot: docroot
  php: "8.0"
  database: mysql:5.7
  drush: ^9
```

These are the results from a `lando start` and `lando rebuild`:

```
john@tandem:~/lando/1-test-sites/rando-tests$ lando start
Let's get this party started! Starting app lando-rando...
Recreating landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "landorando_default" with the default driver
Creating volume "landorando_data_appserver" with default driver
Creating volume "landorando_home_appserver" with default driver
Creating volume "landorando_data_database" with default driver
Creating volume "landorando_home_database" with default driver
Pulling appserver (devwithlando/php:8.0-apache-4)...
...
john@tandem:~/lando/1-test-sites/rando-tests$ lando php -v
PHP 8.0.17 (cli) (built: Mar 18 2022 19:54:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.17, Copyright (c), by Zend Technologies



john@tandem:~/lando/1-test-sites/rando-tests$ lando rebuild
? Are you sure you want to rebuild? Yes
Rising anew like a fire phoenix from the ashes! Rebuilding app...
Killing landorando_database_1  ... done
Killing landorando_appserver_1 ... done
Going to remove landorando_database_1, landorando_appserver_1
Removing landorando_database_1  ... done
Removing landorando_appserver_1 ... done
Pulling database  ... done
Pulling appserver ... done
database uses an image, skipping
appserver uses an image, skipping
Recreating landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating landorando_appserver_1 ... done
usermod: no changes
usermod: no changes
All settings correct for using Composer
Downloading...

Composer (version 2.2.6) successfully installed to: /usr/local/bin/composer
Use it: php /usr/local/bin/composer

Killing landorando_appserver_1 ... 
Killing landorando_appserver_1 ... done
Creating landorando_database_1  ... done
Starting landorando_appserver_1 ... done
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Scanning to determine which services are ready... Please stand by...

   ___                      __        __        __     __        ______
  / _ )___  ___  __ _  ___ / /  ___ _/ /_____ _/ /__ _/ /_____ _/ / / /
 / _  / _ \/ _ \/  ' \(_-</ _ \/ _ `/  '_/ _ `/ / _ `/  '_/ _ `/_/_/_/ 
/____/\___/\___/_/_/_/___/_//_/\_,_/_/\_\\_,_/_/\_,_/_/\_\\_,_(_|_|_)  
                                                                       

Your app has started up correctly.
Here are some vitals:

 NAME            lando-rando                               
 LOCATION        /home/john/lando/1-test-sites/rando-tests 
 SERVICES        appserver, database                       
 APPSERVER URLS  https://localhost:49172                   
                 http://localhost:49173                    
                 http://lando-rando.lndo.site:8080/        
                 https://lando-rando.lndo.site/            

john@tandem:~/lando/1-test-sites/rando-tests$ lando php -v
PHP 8.0.17 (cli) (built: Mar 18 2022 19:54:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.17, Copyright (c), by Zend Technologies
john@tandem:~/lando/1-test-sites/rando-tests$ 
```

My guess is something else is going on in your system.  I would recommend purging all you containers: https://docs.lando.dev/help/purging-containers.html and starting over.  

Since this can't be reproduced and we have hundreds of users using the php 8+ recipes, I am, going to lock the issue.
