### ISSUE TITLE
Do mysql query on build

### ISSUE THREAD

**Issue by Aldo-f** [lando/lando#2723]
On every build I need to do this command:
```
lando mysql
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY','')); 
```

It it possible to do this automatically? 
With mysql-config files, or in ``.lndo.yml``? 
https://docs.lando.dev/config/mysql.html#configuration

**Comment by pirog** [comment]
yes! Use https://docs.lando.dev/config/services.html#build-steps

**Comment by Aldo-f** [comment]
This ``.lando.yml``
``` yml
name: some_name
recipe: lamp
services:
  database:
    run:
      - SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
```

Give this error:
``` sh
/bin/sh: 1: Syntax error: "(" unexpected
ERROR ==> /bin/sh: 1: Syntax error: "(" unexpected 

```

Did I use some wrong characters?

**Comment by pirog** [comment]
@Aldo-f you might want to wrap the whole thing in `"`


```yaml
name: some_name
recipe: lamp
services:
  database:
    run:
      - "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));"
```

**Comment by Aldo-f** [comment]
I have tried all possible ways to write that line:
```
name: some_name
recipe: lamp
services:
  database:
    run:
      - SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));       # Works in `lando mysql`
      -  SET GLOBAL sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION";     # Works in `lando mysql`

      - "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));"     # Does not work in `lando mysql`: You have an error in your SQL syntax
      - 'SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));'     # Throws error: ensure it's valid YAML
      - \"SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));\"   # Does not work with in `lando mysql`: Unknown command '\"'.
      - "SET GLOBAL sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION;'";   # Does not work in `lando mysql`: You have an error in your SQL syntax

```

Two lines are working, but only with `lando mysql `

```
- SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
- SET GLOBAL sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"; 
```

Could I add some more details to fix this?
