### ISSUE TITLE
How to disable the automatic database connection for Backdrop recipes

### ISSUE THREAD

**Issue by BWPanda** [lando/lando#2727]
I'm trying to test Backdrop's install process, specifically the "Set up your database" step of the install profile. However this step is always skipped because Lando sets the database connection string in the `BACKDROP_SETTINGS` environment variable. Because of https://github.com/backdrop/backdrop-issues/issues/281, that variable overrides anything in `settings.php`. So the only way to have Backdrop use `settings.php` instead is to either not set the environment variable in the first place, or to somehow unset it. But how do I do that?

Here's what I've tried (I also tried both rebuilding and destroying between each attempt):

- Adding
  ```
  services:
    appserver:
      overrides:
        environment:
          BACKDROP_SETTINGS: null
  ```
  to my Lando config - result was a fatal error: `The values in $_SERVER[BACKDROP_SETTINGS] could not be read.`

- Adding an `.env` file containing `BACKDROP_SETTINGS=` - result was that Backdrop installed as normal, reading the DB connection string from the still-existant environment variable.

- Adding
  ```
  services:
    appserver:
      build_as_root:
        - unset BACKDROP_SETTINGS
  ```
  to my Lando config - result was that Backdrop installed as normal, reading the DB connection string from the still-existant environment variable.
