### ISSUE TITLE
Xdebug 3 XDEBUG_CONFIG and XDEBUG_MODE environment variables prevents changing Xdebug config without rebuild

### ISSUE THREAD

**Issue by tbfisher** [lando/lando#2728]
f6bf4944724ae45eeed28e2900a021b8b7aec015 added `XDEBUG_CONFIG` and `XDEBUG_MODE` env vars.

I want to be able to change my php ini on the fly via tooling and change `xdebug.mode` to another value, but the `XDEBUG_MODE` env variable overrides this. Same for other values in the `XDEBUG_CONFIG` env var.

To reproduce

1. Set `xdebug: "debug,develop"` on your php-fpm service.
2. Start up and verify step debug.
3. Change the value via an ini file to `off` or to `develop` for example, restart the php-fpm service, verify the change.
4. The step debug still works.

**Comment by dustinleblanc** [comment]
@tbfisher could you accomplish the same thing by using `export` to override the env var?

**Comment by tbfisher** [comment]
@dustinleblanc for CLI yes, but not for HTTP afaik.

**Comment by tbfisher** [comment]
I guess I should have specified that the env variables are set such that they override ini settings for both CLI and HTTP requests.

**Comment by jcandan** [comment]
Could we swap the order of the merge items below to allow these environment variables to be overridden?

```diff
-        environment: _.merge({}, options.environment, {
+        environment: _.merge({}, {
           PATH: options.path.join(':'),
           LANDO_WEBROOT: `/app/${options.webroot}`,
           XDEBUG_CONFIG: `remote_enable=true remote_host=${options._app.env.LANDO_HOST_IP}`,
           XDEBUG_CONFIG: xdebugConfig(options._app.env.LANDO_HOST_IP),
           XDEBUG_MODE: (options.xdebug === true) ? 'debug' : options.xdebug,
-        }),
+        }, options.environment),
```

**Comment by jcandan** [comment]
Tested locally. Happy to report that this change allows us to do the following again:

```yml
config:
  xdebug: false
services:
  appserver:
    overrides:
      environment:
        XDEBUG_MODE: debug
tooling:
  xdebug-on:
    user: root
    service: appserver
    description: Enable Xdebug.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
  xdebug-off:
    user: root
    service: appserver
    description: |-
      Disable Xdebug.
      (Recommended for performance when not actively debugging)
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
```

**Comment by tbfisher** [comment]
With xdebug 3 you don't need to disable the extension to get a performance benefit, but you do need to modify the ini setting `xdebug.mode`

The environment variables prevents this, as well as changing any of the other ini settings in those env vars.

**Comment by jcandan** [comment]
With the following, we now can pass any of the accepted xdebug mode values.

```
XDEBUG_MODE: (options.xdebug === false) ? 'off' : options.xdebug,
```

If true, it will default to `debug`.

```
      // If xdebug is set to "true" then map it to "debug"
      if (options.xdebug === true) options.xdebug = 'debug';
```

This means the `xdebug.mode` is now set by the `config.xdebug` config--no need to override via env vars.

```
config:
  xdebug: trace
```

**Comment by jcandan** [comment]
However, my PR is still needed in order to override `XDEBUG_MODE` without having xdebug enabled because of:

```
      // Add activate steps for xdebug
      if (options.xdebug) {
        utils.addBuildStep(['docker-php-ext-enable xdebug'], options._app, options.name, 'build_as_root_internal');
      }
```

**Comment by tbfisher** [comment]
The env vars need to be removed, since they prevents modifying xdebug mode without rebuilding.

**Comment by tbfisher** [comment]
The `client_host` (v3) and `remote_host` (v2) are convenient, but I'm not sure whey they can't be set in an ini file.

**Comment by pirog** [comment]
The envvars are not going to be removed. You can modify or unset them if you don't like what Lando is doing with a service level override eg

```yaml
myservice:
    type: php:8.0
    composer_version: false
    xdebug: true
    overrides:
      environment:
        XDEBUG_MODE:
    config:
      php: config/php.ini
```

^ That will activate the `xdebug` extension but allow `xdebug.mode` to be set in `config/php.ini`

**Comment by tbfisher** [comment]
@pirog that works, thanks!

**Comment by pirog** [comment]
I also added this workaround to the docs, should be shipped soonish

**Comment by tbfisher** [comment]
I think the unset override is fine, and better than complicating the meaning of Lando's `xdebug`.

**Comment by tormi** [comment]
> With xdebug 3 you don't need to disable the extension to get a performance benefit, but you do need to modify the ini setting `xdebug.mode`

@tbfisher, are you absolutely sure about this?

**Comment by tbfisher** [comment]
@tormi I haven't measured it (though google it, others have), but with xdebug 3 I leave the extension enabled all the time, changing the `xdebug.mode` value as needed. With xdebug 2 I would enable/disable the extension, since my environment was sluggish when enabled.

**Comment by tormi** [comment]
Ok, I'll take your word ;)

**Comment by tormi** [comment]
@tbfisher, using it here now: https://github.com/lando/lando/issues/1668#issuecomment-772829423

**Comment by tormi** [comment]
You were correct:
> When xdebug.mode=off is set, there is close to zero performance impact.

https://php.watch/articles/xdebug2-vs-3-benchmark#summary

**Comment by zahardev** [comment]
Hi guys!
Wanted to share my approach without `xdebug-on` `xdebug-off`. The idea is to add needed variables on the fly with lando tooling for `phpdebug` command:


```
#.lando.yml
tooling:
  phpdebug:
    service: appserver
    cmd:
      - php
    env:
      XDEBUG_TRIGGER: 1
      PHP_IDE_CONFIG: "serverName=localhost"
```

Now, if you do 
`lando php test.php` - xdebug session doesn't start.
And if you do
`lando phpdebug test.php `- xdebug session starts
