### ISSUE TITLE
Using vnu with lando

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#2731]
There was [already a thread about this before](https://github.com/lando/lando/issues/1686), but vnu has changed and the suggested code in the linked issue no longer works.

vnu is updated fairly often, and old releases are apparently deleted from Docker Hub (getting a `manifest unknown` error when I try to use `17.11.1`.

The problem with using `vnu` in lando is that vnu uses `network_mode: "host"`, which can't be used in lando because it gives the error `ERROR: 'network_mode' and 'networks' cannot be combined`.

Based on the linked issue, here's my `lando.yml`.

```
proxy:
  vnu:
    - vnu.MYSITE.lndo.site:8888
services:
  vnu:
    type: compose
    services:
      image: validator/validator
      command: java -cp dist/vnu.jar nu.validator.servlet.Main 8888
      ports:
        - '8888:8888'
```

The problem is that the command is wrong, so the vnu container doesn't run; it starts and immediately stops.

In the logs, I get this error:

`/lando-entrypoint.sh: 27: /lando-entrypoint.sh: touch: not found`

I read the [Dockerfile for vnu](https://hub.docker.com/r/validator/validator/dockerfile) but I don't understand how I can change the command to get it working on lando.

**Comment by mihkeleidast** [comment]
This is working for me:
```yaml
name: project
proxy:
  vnu:
    - vnu.project.lndo.site:8888
services:
  vnu:
    type: compose
    ssl: true
    sslExpose: false
    services:
      image: validator/validator:20.6.30
      command: java -cp ~/vnu.jar nu.validator.servlet.Main 8888
      ports:
        - '8888:8888'
```
