### ISSUE TITLE
502 when working with latest v3.0.22

### ISSUE THREAD

**Issue by GiorgosK** [lando/lando#2739]
2 days ago I updated to latest version

> $ lando version
> v3.0.22

I am on Ubuntu
> $ uname -a
> Linux ThinkPad-E590 5.7.1-050701-generic #202006071230 SMP Sun Jun 7 12:32:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

my `.lando.yml` 
```yml
name: Demo
recipe: drupal8

config:
  php: '7.3'
  via: nginx

services:
  appserver:
    webroot: web
    xdebug: debug
    config:
      php: .lando.php.ini
  database:
    type: mariadb
    portforward: 32777
    creds:
      database: demo

tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/web
```

my `.lando.php.ini` as taken from this issue https://github.com/lando/lando/issues/2732
```ini
[PHP]
xdebug.mode=debug
xdebug.start_with_request = yes
xdebug.client_host = ${LANDO_HOST_IP}
xdebug.log = /tmp/xdebug.log
```

After updating to this version I realized my xdebug and vscode debugger were not cooperating but after updating to the above setup all worked smoothly.

The system is working nicely with this setup but after a few hours of working with it I get `502` on all pages and running `lando drush cr` seems it never completes.  I have used lando extensively over the last 2 years and have never seens this.  This behaviour happened already 3 times but I can't pinpoint at what point it blows up.

After I `lando rebuild -y` the system is smooth again.

After rebuild I get this error on `lando drush cr` 

> Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.1.17:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(

But I assume it is understandable since this rebuild I will try to keep the vscode debugger disabled and see if it makes any difference and next iteration I will try to disable xdebug if that makes a difference.

Is there something I should be looking for in the logs to help me/us debug this ? Any other hints ?
