### ISSUE TITLE
Error with finding primary route on PlatformSH

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#2740]
Getting this error:
```
Unhandled rejection TypeError: Cannot set property 'primary' of undefined
    at setPrimaryRoute (/snapshot/lando/build/cli/integrations/lando-platformsh/lib/config.js)
    at /snapshot/lando/build/cli/integrations/lando-platformsh/lib/config.js
    at Function.thru (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:8817:14)
    at /snapshot/lando/build/cli/node_modules/lodash/lodash.js:4388:28
    at arrayReduce (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:683:21)
    at baseWrapperValue (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:4387:14)
    at LodashWrapper.wrapperValue (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9072:14)
    at Object.parseRoutes (/snapshot/lando/build/cli/integrations/lando-platformsh/lib/config.js)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/integrations/lando-platformsh/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js)
    at /snapshot/lando/build/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11
```

Here is the anonymized Lando config.

```yml
name: someclient
recipe: platformsh
excludes:
  - drush
  - vendor
  - web/core
  - web/modules/contrib
  - web/profiles/contrib
  - web/sites/default/files
  - web/themes/contrib
config:
  id: someid
proxy:
  mailhog:
    - mail-someclient.lndo.site
  node:
    - bs-someclient.lndo.site:3000
env_file:
  - .env
services:
  app:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: http://someclient.lndo.site
  node:
    type: node
    command: cd /app/web/themes/custom/someclient_theme && yarn watch
    scanner: false
    ssl: true
    overrides:
      environment:
        BS_DOMAIN: "http://app"
        BS_SOCKET_DOMAIN: "https://bs-someclient.lndo.site"
        BS_SOCKET_PORT: 80
    build:
      - cd /app/web/themes/custom/someclient_theme && yarn install
      - cd /app/web/themes/custom/someclient_theme && yarn dev
  mailhog:
    type: mailhog
    hogfrom:
      - app
  d7db:
    type: mariadb:10.4
    config:
      database: config/my-custom.cnf
    creds:
      user: drupal7db
      password: drupal7db
      database: drupal7db
    portforward: true
tooling:
  drush:
    service: app
    cmd: /app/vendor/bin/drush --root=/app/web
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
    cmd: yarn
```

Looking at the `setPrimaryRoute` method, it assumes the incoming argument is an array, when I dump the value for this app, it is an empty object (`{}`).
