### ISSUE TITLE
Fixing DB port with portforward is not working

### ISSUE THREAD

**Issue by aimfeld** [lando/lando#2749]
I'm trying to set a fixed port for the DB connection according to the [guide](https://docs.lando.dev/guides/external-access.html#locking-down-ports). However, the port keeps getting assigned randomly on every `lando rebuild` and `lando restart`, as shown by `lando info`. Maybe this doesn't work with the `platformsh` recipe?

I have this in my .lando.yaml (I tried other port numbers, no luck):
```
services:
  database:
    portforward: 3307
```

**Comment by pirog** [comment]
@aimfeld it should work but there is a good chance your service isn't called `database`. Should match up with what is in your `services.yaml`

**Comment by pirog** [comment]
@aimfeld interesting. I'll see if i can replicate.

**Comment by iKlsR** [comment]
I'm getting this for regular mysql but it only seems to happen when I'm running multiple lando projects. I tend to increase my ports by 1000 starting from 3306 when forwarding.

**Comment by Hazmatyre** [comment]
Ports aren't being locked down for me etiher on a latest Lando stable release.

**Comment by pirog** [comment]
I can replicate this and looking at the code it definitely looks like either a bug or just an oversight.

**Comment by pirog** [comment]
Ok this should be resolved in v3.1.0 once the release posts. https://github.com/lando/lando/releases/tag/v3.1.0

Def remember that you need to use the service names you define in your Platform.sh `services.yaml`

**Comment by aimfeld** [comment]
Works for me in v3.1.0, thanks for fixing! :+1:

**Comment by kwiechmann** [comment]
I have the latest version of lando installed: v3.1.4 but have not been able to lock the port. Although I can initially see my target port of 3307 with **lando info**, it eventually migrates to a random database port. Here are my configuration files:

.platform/services.yaml:
```
# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

db:
    type: mariadb:10.2
    disk: 2048
```

.lando.yml
```
name: sandbox
recipe: platformsh
config:
  id: na4ynz2lwtdyd
services:
  db:
    portforward: 3307
```
