### ISSUE TITLE
recipe "webserver only"

### ISSUE THREAD

**Issue by zdenekgebauer** [lando/lando#2750]
Would it be possible to create a recipe without PHP and database? Something like "apache only" or "nginx only". It would be suitable for the development of "static" websites with javascript.
Or is there a way to remove the service database from the LAMP recipe?
Thanks

**Comment by lochmueller** [comment]
hey @zdenekgebauer 
Do you try to use no recipe at all if you are need only a single service?
I think this is the easiest way: Define your appserver by yourself and remove the recipe line.
Regards,
Tim

**Comment by zdenekgebauer** [comment]
hi, @lochmueller , thanks for the idea. I tested this config file:
```yaml
name: apache
services:
  appserver:
    type: apache:2.4
    webroot: .
    ssl: true
proxy:
  appserver:
    - apache.lndo.site
```
It works. Or I didn't notice problem yet. 
I still believe that predefined recipe would be useful.
