### ISSUE TITLE
Specify services/tooling via "lando init"

### ISSUE THREAD

**Issue by klonos** [lando/lando#2751]
I've already read https://docs.lando.dev/basics/init.html and know that I can for example do this:

```bash
lando init \
  --source remote \
  --remote-url https://github.com/drupal/drupal.git \
  --remote-options="--branch 8.9.x --depth 1" \
  --recipe drupal8 \
  --webroot ./docroot \
  --name d8test \
  --option composer_version=2.0.7 \
  --option database=mariadb
```

Which results in this:

```yaml
name: d8test
recipe: drupal8
config:
  webroot: ./docroot
  composer_version: 2.0.7
  database: mariadb
```

Can `lando init` accept parameters for setting other things, like `services` and `tooling`? For example, I would like to end up with:

```yaml
name: d8test
recipe: drupal8
config:
  webroot: ./docroot
  composer_version: 2.0.7
  database: mariadb

services:
  appserver:
    extras:
      - bla bla
      - bla bla bla
  phpmyadmin:
    type: phpmyadmin
    hosts: database

tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/docroot --uri=http://d8test.lndo.site
```

**Comment by pirog** [comment]
@klonos i dont think so, probably not something we will support in this iteration of lando but could be a cool feature for the future.

**Comment by klonos** [comment]
Thanks for considering this @pirog 👍 

I would like to note that the workaround for this so far has been to be using "template" .lando.yml files, with "placeholders" in them, and then using custom scripts + `sed` and the likes to do replacements and copying. Not ideal.

**Comment by klonos** [comment]
I think that this is still relevant and worth pursuing.

For parity between command parameters and what gets added to the .lando.yml file, I'd ideally expect things like this:

- `--config database=mariadb` (with the current `--option` still working for backwards compatibility of course) to result in this:
  ```yml
  config:
    ...
    database: mariadb
  ```
- `--services phpmyadmin.type = phpmyadmin` and `--services phpmyadmin.hosts = database` to result in this:
  ```yml
  services:
    phpmyadmin:
      type: phpmyadmin
      hosts: database
  ```
- `--tooling drush.service = appserver` and `--tooling drush.cmd = "drush --root=/app/docroot --uri=http://d8test.lndo.site"` to result in this:
  ```yml
  tooling:
    drush:
      service: appserver
      cmd: drush --root=/app/docroot --uri=http://d8test.lndo.site
  ```
