### ISSUE TITLE
Using node, getting "Error: The environment variable CHROME_PATH must be set"

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#2753]
I'm trying to run [Lighthouse CI / NPM version](https://github.com/andreasonny83/lighthouse-ci#readme) on Lando and I'm getting the following error:

`Error: The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.`

I also tried a different batch Lighthouse tool, [Lighthouse Batch](https://github.com/mikestead/lighthouse-batch), and I got the same error.

The Google documentation on [adding environment variables for Chrome](https://developer.chrome.com/docs/native-client/sdk/examples/) states you can do this on Linux:

`$ export CHROME_PATH=<Path to google-chrome>`

But, I don't know how to set this `CHROME_PATH` variable inside node in Lando.

Any ideas?

My `.lando.yml` looks like this:

```
  node:
    type: node:12
    globals:
      gulp-cli: latest
      pa11y-ci: latest
      lighthouse: latest
      lighthouse-batch: latest
      lighthouse-ci: latest
    extras:
      - apt-get update
      - apt-get -y install xvfb gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
      - rm -rf /var/lib/apt/lists/*
      - groupadd -r pptruser
      - useradd -r -g pptruser -G audio,video pptruser
      - mkdir -p /home/pptruser/Downloads
      - chown -R pptruser:pptruser /home/pptruser

  tooling:
    lighthouse:
      service: node
    lighthouse-batch:
      service: node
    lighthouse-ci:
      service: node
```
