### ISSUE TITLE
Cannot install extensions / Too many levels of symbolic links

### ISSUE THREAD

**Issue by metalbote** [lando/lando#2756]
Sys: v3.0.23 on openSuSE Tumbleweed, Docker version 19.03.12, build 48a66213fe17, kernel 5.9.12

```yml
name: drupal
recipe: drupal9

config:
  php: "7.4"
  via: apache:2.4
  webroot: html

proxy:
  appserver:
    - drupal.lando
  node:
    - js.drupal.lando
  mail:
    - mail.drupal.lando
  pma:
    - pma.drupal.lando

services:
  appserver:
    build_as_root:
      ## Update container
      - "apt-get update -y"
      - "apt-get upgrade -y"
      - "apt-get install -y libxslt1-dev"
      ## Install additional extensions
      - "docker-php-ext-install sockets"
      - "docker-php-ext-install xsl"
    build:
      - "env COMPOSER_MEMORY_LIMIT=-1"
      - "composer install --no-interaction"
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://drupal.lando"
        PHP_IDE_CONFIG: "serverName=drupal.lando"

  database:
    type: mariadb:10.4
    portforward: false
    creds:
      user: drupal
      password: drupal
      database: drupal

  node:
    type: node:12
    globals:
      gulp-cli: latest

  mail:
    type: mailhog:v1.0.0
    portforward: false
    hogfrom:
      - appserver

  pma:
    type: phpmyadmin
    hosts:
      - database
```

With the latest version i am getting problems spinning up my projects. I depend on the xsl extension but on `lando build` I am getting following error (and also funny `1000` outputs...):
```
Setting up libxslt1-dev:amd64 (1.1.32-2.2~deb10u1) ...
Processing triggers for libc-bin (2.28-10) ...
tar (child): xz: Cannot exec: Too many levels of symbolic links
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
ERROR ==> tar: Error is not recoverable: exiting now 
```

Complete output:
```
Let's get this party started! Starting app drupal...
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating network "drupal_default" with the default driver
Creating volume "drupal_data_appserver" with default driver
Creating volume "drupal_home_appserver" with default driver
Creating volume "drupal_data_database" with default driver
Creating volume "drupal_home_database" with default driver
Creating volume "drupal_data_node" with default driver
Creating volume "drupal_home_node" with default driver
Creating volume "drupal_data_mail" with default driver
Creating volume "drupal_home_mail" with default driver
Creating volume "drupal_data_pma" with default driver
Creating volume "drupal_home_pma" with default driver
Creating drupal_node_1 ... done
1000
1000
Creating drupal_appserver_1 ... done
1000
1000
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://apt.postgresql.org/pub/repos/apt buster-pgdg InRelease [104 kB]
Get:3 http://security.debian.org/debian-security buster/updates/main amd64 Packages [255 kB]
Get:4 http://apt.postgresql.org/pub/repos/apt buster-pgdg/main amd64 Packages [216 kB]
Get:5 http://deb.debian.org/debian buster InRelease [121 kB]
Get:6 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:7 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:8 http://deb.debian.org/debian buster-updates/main amd64 Packages [7856 B]
Fetched 8728 kB in 4s (2199 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
libxslt1.1
The following NEW packages will be installed:
libxslt1-dev libxslt1.1
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 756 kB of archives.
After this operation, 3001 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 libxslt1.1 amd64 1.1.32-2.2~deb10u1 [237 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 libxslt1-dev amd64 1.1.32-2.2~deb10u1 [519 kB]
Fetched 756 kB in 1s (569 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libxslt1.1:amd64.
(Reading database ... 30506 files and directories currently installed.)
Preparing to unpack .../libxslt1.1_1.1.32-2.2~deb10u1_amd64.deb ...
Unpacking libxslt1.1:amd64 (1.1.32-2.2~deb10u1) ...
Selecting previously unselected package libxslt1-dev:amd64.
Preparing to unpack .../libxslt1-dev_1.1.32-2.2~deb10u1_amd64.deb ...
Unpacking libxslt1-dev:amd64 (1.1.32-2.2~deb10u1) ...
Setting up libxslt1.1:amd64 (1.1.32-2.2~deb10u1) ...
Setting up libxslt1-dev:amd64 (1.1.32-2.2~deb10u1) ...
Processing triggers for libc-bin (2.28-10) ...
tar (child): xz: Cannot exec: Too many levels of symbolic links
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
ERROR ==> tar: Error is not recoverable: exiting now
Creating drupal_mail_1     ... done
Creating drupal_database_1 ... done
Creating drupal_pma_1      ... done
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Scanning to determine which services are ready... Please standby...

_      __              _           __
| | /| / /__ ________  (_)__  ___ _/ /
| |/ |/ / _ `/ __/ _ \/ / _ \/ _ `/_/
|__/|__/\_,_/_/ /_//_/_/_//_/\_, (_)
/___/

Your app started up but we detected some things you may wish to investigate.
These only may be a problem.
```
