### ISSUE TITLE
Can't debug tests after update

### ISSUE THREAD

**Issue by paulostarling** [lando/lando#2761]
After I updated my lando, I'm not able to debug tests.
My lando.yml file
```
name: drupalphp8
recipe: drupal9
config:
  webroot: drupal
  xdebug: true
  php: '7.4'
  conf:
    php: .vscode/php.ini
services:
  appserver:
    overrides:
      environment:
        MINK_DRIVER_ARGS_WEBDRIVER: >-
          ["chrome",
          {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless",
          "--no-sandbox", "--disable-dev-shm-usage"]}}, "http://chrome:9515"]
  chrome:
    type: compose
    services:
      image: 'drupalci/webdriver-chromedriver:production'
      command: chromedriver --log-path=/tmp/chromedriver.log --verbose --whitelisted-ips=
tooling:
  test:
    service: appserver
    cmd: php -d xdebug.remote_port=9003 /app/drupal/vendor/bin/phpunit -c /app/drupal/phpunit.xml
  drush:
    service: appserver
    cmd: /app/drupal/vendor/bin/drush
```
My php.ini file:
```
[PHP]

; Xdebug
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
; Extra custom Xdebug setting for debug to work in VSCode.
xdebug.client_host = ${LANDO_HOST_IP}
xdebug.client_port = 9003
xdebug.start_with_request = yes
xdebug.mode = debug
; xdebug.remote_connect_back = 1
xdebug.remote_log = /tmp/xdebug.log

```
My launch.json file:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9003,
      "log": true,
      "pathMappings": {
        "/app/": "${workspaceFolder}/",
      }
    },
    {
      "name": "PhpUnit dummy",
      "type": "php",
      "request": "launch",
      "port": 9001,
    }
  ],
  "compounds": [
    {
      "name": "PhpUnit",
      "configurations": [
        "Listen for XDebug",
        "PhpUnit dummy"
      ]
    }
  ]
}
```
