### ISSUE TITLE
Lando Pull and Lagoon Drupal File Directories

### ISSUE THREAD

**Issue by owenbush** [lando/lando#2762]
**Tell us about your setup**

Lando v3.0.23 on MacOSX Catalina

**Tell us about your `.lando.yml`**

```yml
name: dcoag
recipe: lagoon
config:
  build:
    - composer install
```

`.lagoon.yml`

```yml
docker-compose-yaml: docker-compose.yml

project: dcoag

tasks:
  post-rollout:
    - run:
        name: IF no Drupal installed and we are not master branch, sync from master branch
        command: |
            if tables=$(drush sqlq 'show tables;') && [ -z "$tables" ] && [[ "$LAGOON_GIT_BRANCH" != "master" ]]; then
                # no drupal installed, sync DB from master branch
                drush -y sql-sync @master @self
            fi
        service: cli
        shell: bash
    - run:
        name: drush cim
        command: drush -y cim
        service: cli
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli

environments:
  master:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli

```

**Tell us about the command you were running**

```bash
lando start
lando pull # or lando pull -d dcoag-master -f dcoag-master
```

**Tell us about the error you got**

When attempting to pull files from an existing lagoon instance we end up getting an error stating that the `web/sites/default/files` directory does not exist. This is not surprising to me as we use `docroot` as our Drupal webroot directory, not `web`. Also, the fact that the public file path is configurable and may not always be `sites/default/files` is somewhat problematic.

The issue arises from [this line within the lagoon-pull.sh file](https://github.com/lando/lando/blob/72fa3dd4641cd8b6b8b23aa59e8d58d14939a3d9/integrations/lando-lagoon/scripts/lagoon-pull.sh#L158)

`web/sites/default/files` is hardcoded to the `drush rsync` command.

The error we get is:

```bash
> rsync: change_dir "/app//web/sites/default" failed: No such file or directory (2)
> command terminated with exit code 23
> rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1659) [Receiver=3.1.3]
> rsync: [Receiver] write error: Broken pipe (32)

In RsyncCommands.php line 82:

  Could not rsync from dcoag-master@ssh.lagoon.amazeeio.cloud:web/sites/default/files to web/sites/default
```

**Tell us generally about your bug**

The issue is that there is an assumption that the webroot will always be under `web` and that the public files will always be in `sites/default/files`

**Tell us more**

My proposed solution, and I will attach a PR to this issue, is that we actually use drush to tell us where the public file system lives. There is a drush command `drush dd files` which does exactly that. So I propose that instead of making an assumption we can actually use drush to tell us exactly where the files exist.

As an aside to this issue I also noticed that there was a bug in the code if you chose not to import the database (choosing, or writing `none`) but still opted to import the files. 

```bash
if [[ "${LANDO_DB_ALIAS}" != "${LANDO_LAGOON_PROJECT}"* ]]; then
  LANDO_DB_ALIAS="${LANDO_LAGOON_PROJECT}-${LANDO_DB_ALIAS}"
  LANDO_FILES_ALIAS="${LANDO_LAGOON_PROJECT}-${LANDO_FILES_ALIAS}"
fi
```

This code should only affect the db alias, and there should be an equivalent for the files alias. I have corrected that issue as part of the PR too as it relates to the overall importing of remote files. 

Without this fix, opting not to import a db, but import the files you end up with an error like this:

```bash
lando pull -d none -f dcoag-master
Refreshing aliases...
Skipping database
Validating lagoon.dcoag-dcoag-master exists and you have access to it...
lagoon.dcoag-dcoag-master does not appear to be a valid environment!
```

Notice the duplicated `dcoag-` in that files alias?

I also have done a bit of cleanup because anytime a drush command was run the output of that drush command was being printed in console, under some circumstances that is fine, but under other circumstances it doesn't make sense to print out the output of `drush status` twice each time you run `lando pull`. So I have cleaned up the output and added some additional debug/notice messaging where it seemed to make sense.

One thing to point out at this point is that this only affects `lando pull` and not `lando push`. In all likelihood that code needs to be reviewed and updated too, maybe as part of a separate issue.
