### ISSUE TITLE
SSL cert authority invalid for proxied service

### ISSUE THREAD

**Issue by maximilianoertel** [lando/lando#2764]
I'm attempting to run `browser-sync-webpack-plugin` within Lando, but am running into some problems in regards to the SSL certificate. Looked through the documentation and issues here on GitHub but didn't find anything that got this working. 

This is the `.lando.yml` configuration: 
```
name: my-app
recipe: wordpress
config:
  php: '7.2'
  via: nginx
  webroot: web
  database: mariadb
  xdebug: true
  keys: false
proxy:
  node:
    - my-app.lndo.site:3000
services:
  node:
    type: node
    ssl: 3000
    overrides:
      ports:
        - 3000:3000
    build:
      - npm install
  appserver:
      run:
        - composer install
tooling:
  npm:
    service: node
```

And this is the browsersync configuration: 
```
new BrowserSyncPlugin({
    proxy: 'https://appserver_nginx',
    host: 'my-app.lndo.site',
    port: 3000
})
```

Using this setup, I can access `https://my-app.lndo.site` without any problems as I've taken the necessary steps to trust the Lando CA. Whenever I try to access `https://my-app.lndo.site:3000` however, I get an `ERR_CERT_AUTHORITY_INVALID` error in the browser, showing that the certificate is not Lando CA but Internet Widgits Pty Ltd instead. 

As an alternative, I've attempted to change the configurations to the following but ended up running into the same problem. 
`.lando.yml`. 
```
proxy:
  node:
    - bs.my-app.lndo.site:3000
``` 

`webpack.config.js`
```
new BrowserSyncPlugin({
    proxy: 'https://appserver_nginx',
    host: 'bs.my-app.lndo.site',
    port: 3000,
    …
})
```

Following the existing [Lando guide](https://docs.lando.dev/guides/how-to-wire-up-browsersync-and-gulp-in-my-lando-app.html#configuring-lando-for-browsersync) doesn't work either as starting Browsersync on port 80 only produces `Error: listen EACCES: permission denied 0.0.0.0:80` 

Am I doing something wrong? Any help would be greatly appreciated and I'd be happy to write a guide for using `browser-sync-webpack-plugin` with Lando afterwards.
