### ISSUE TITLE
Node Service: Disable localhost mapping?

### ISSUE THREAD

**Issue by wreality** [lando/lando#2768]
Is it possible to disable the localhost mapping for the node service?  

In my particular scenario, nginx is proxying to the node service and the PHP service via the vhosts config.  

The additional URL displayed in `lando start` is a source of confusion about the correct way to access the application under lando.

```
name: ccr
recipe: laravel
config:
  php: '8.0'
  webroot: backend/public
  via: nginx
  config:
    vhosts: .lando/default.conf.tpl
services:
  client:
    type: node
    build:
      - cd /app/client && yarn install
    command: cd /app/client && yarn dev
    overrides:
      ports: []
```
