### ISSUE TITLE
XDebug not showing up as installed for Laravel recipe

### ISSUE THREAD

**Issue by JasonTheAdams** [lando/lando#2771]
**Tell us about your setup**

What is your lando version and operating system?

Lando 3.0.23 on MacOS Big Sur

**Tell us about your `.lando.yml`**

```yml
name: give
recipe: laravel
config:
    via: nginx
    webroot: public
    php: '7.4'
    cache: redis
    database: mysql:8.0
    xdebug: true
proxy:
    appserver_nginx:
        - give.local.test
        - "*.give.local.test"
services:
    mail:
        type: mailhog
    database:
        portforward: 3307

    # Disable the scanner since home is a 404
    appserver_nginx:
        scanner: false

```

As you can see, I have `xdebug: true` within the config. I've tried running `lando rebuild` to make sure it's being applied. However, when I follow the [PhpStorm instructions for Lando and Xdebug](https://docs.lando.dev/guides/lando-phpstorm.html), I notice in the video that the xdebug version shows up in PhpStorm. In mine, however, it says it's not installed:
![image](https://user-images.githubusercontent.com/2024145/102940176-914b9480-4464-11eb-9228-40470dfbad87.png)

Am I missing something? I've tried different Image Names, but nothing seems to have XDebug installed.
