### ISSUE TITLE
Add node to Laravel recipe

### ISSUE THREAD

**Issue by Haqz** [lando/lando#2774]
So what im trying to do is add to my laravel container a node. I tried only this:
```
tooling:
  node:
    service: appserver
  npm:
    service: appserver
```
But when i execute `lando npm i` i get error
```
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "npm": executable file not found in $PATH: unknown
```
Am i missing something or is it impossible to add node to recipe?
