### ISSUE TITLE
How to get wkhtmltopdf working with lamp recipe?

### ISSUE THREAD

**Issue by Vandaahl** [lando/lando#2786]
I can not figure this out because I keep getting dependency errors when I ssh in the appserver service and run:

`wkhtmltopdf http://google.com google.pdf`

Output:

> wkhtmltopdf: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by wkhtmltopdf)

> wkhtmltopdf: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by wkhtmltopdf)

> wkhtmltopdf: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.28' not found (required by wkhtmltopdf)

This is on Ubuntu 20.10. Has anybody managed to get a working wkhtmltopdf install in a lamp recipe?

**Comment by rabauss** [comment]
something like this should work:
```yml
recipe: lamp
services:
    appserver:
      build_as_root:
        - "apt-get update -y && apt-get install -y libxrender1 libfontconfig1 xfonts-75dpi xvfb wkhtmltopdf"
```
