### ISSUE TITLE
Redis extension unknown with platform.sh recipe and PHP 8

### ISSUE THREAD

**Issue by aimfeld** [lando/lando#2788]
After changing changing the php version from 7.4 to 8.0 in .platform.app.yaml, I get the following error after `lando destroy` and `lando rebuild`: `Exception: Extension '{'configuration': {}, 'name': u'redis'}' is unknown`. Is the redis extension not available yet for PHP 8?

![image](https://user-images.githubusercontent.com/760330/103551595-d4692700-4eaa-11eb-9a7e-37135ce249ad.png)

.platform.app.yaml:
```
# The name of this app. Must be unique within a project.
name: "surveylab"
type: php:8.0
build:
  flavor: composer
timezone: Europe/Zurich
runtime:
  extensions:
    - redis
relationships:
  database: "mysql:mysql"
  rediscache: "cacheredis:redis"
disk: 2048
mounts:
  "/data": "shared:files/data"
  "/temp": "shared:files/temp"
  "/filebeat": "shared:files/filebeat"
dependencies:
  nodejs:
    gulp: "4.0.2"
    yarn: "1.22.5"  # The yarn version should match the yarn version in build.xml
variables:
  env:
    # Update these for your desired NVM and Node versions.
    NVM_VERSION: v0.37.0
    NODE_VERSION: v12.19.1
hooks:
  build: |
    set -e
    curl -sS https://platform.sh/cli/installer | php
    ###################################################################################
    # Use custom nodejs version, see https://docs.platform.sh/languages/nodejs/nvm.html
    ###################################################################################
    unset NPM_CONFIG_PREFIX
    export NVM_DIR="$PLATFORM_APP_DIR/.nvm"
    # install.sh will automatically install NodeJS based on the presence of $NODE_VERSION
    # Create directory if not exists (needed for Lando)
    mkdir -p .nvm
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    # Run phing tasks
    vendor/bin/phing deploy-db-migrations
    vendor/bin/phing create-local-platform-php
    vendor/bin/phing create-platform-index-php
    yarn install
    vendor/bin/phing deploy-assets
  deploy: |
    set -e
    cd
    # Wait a few seconds until DB container is running, otherwise phinx migrate fails on lando
    if [ "$PLATFORM_ENVIRONMENT" = "lando" ]; then echo "Sleeping to wait for DB container..."; sleep 15; fi
    vendor/bin/phinx migrate --configuration phinx-platform.php
    vendor/bin/phing clear-data
    vendor/bin/doctrine orm:generate-proxies
    vendor/bin/phing clear-caches
    vendor/bin/phing import-project
    vendor/bin/phing reset-accounts
crons:
  events:
    spec: "*/5 * * * *"
    cmd: "cd /app/public ; php index.php cron event-flow-update"
  offsite-backup:
    spec: "0 2 * * *"
    cmd: "cd /app/public ; php index.php cron offsite-backup"
  snapshot:
    spec: "0 4 * * *"
    cmd: |
      if [ "$PLATFORM_BRANCH" = master ]; then
          platform snapshot:create --yes --no-wait
      fi
  renewcert:
    spec: "0 3 1,15 * *"
    cmd: "platform redeploy --yes --no-wait"
  filebeat: # Filebeat for Logz
    spec: "0 6 * * *"
    cmd: |
      if [ "$USE_LOGZ" = true ]; then
          /app/build/filebeat/install.sh
          /app/filebeat/src/filebeat -c /app/filebeat.yaml run --once
      fi
web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      headers:
        X-Frame-Options: SAMEORIGIN
      rules:
        # CSS and Javascript.
        \.(css|js|hbs)$:
          allow: true
          headers:
            Access-Control-Allow-Origin: "*"

        # pdf
        \.pdf$:
          allow: true

        # image/* types.
        \.(gif|jpe?g|png|tiff?|wbmp|ico|jng|bmp|svgz?)$:
          allow: true

        # audio/* types.
        \.(midi?|mpe?ga|mp2|mp3|m4a|ra|weba)$:
          allow: true

        # video/* types.
        \.(3gpp?|mp4|mpe?g|mpe|ogv|mov|webm|flv|mng|asx|asf|wmv|avi)$:
          allow: true

        # application/ogg.
        \.ogx$:
          allow: true

        # application/x-shockwave-flash.
        \.swf$:
          allow: true

        # application/java-archive.
        \.jar$:
          allow: true

        # fonts types.
        \.(ttf|eot|woff|woff2|otf)$:
          allow: true
          headers:
            Access-Control-Allow-Origin: "*"

        # robots.txt.
        /robots\.txt$:
          allow: true
```

.lando.yml:
```
name: blueprint
recipe: platformsh

services:
  mysql:
    # Using fixed DB port so there's no need to change it every time in the SQL client.
    # See https://docs.lando.dev/guides/external-access.html#checking-connection-info
    # Currently not working, see https://github.com/lando/lando/issues/2749
    portforward: 3307

config:
  id: bftge3smv4qgi
  variables:
    surveylab:
      php:
        xdebug.remote_connect_back: 1
  overrides:
    surveylab:
      runtime:
        extensions:
          - redis
          - xdebug
          # Make xdebug work. Resources:
          # - https://docs.lando.dev/guides/lando-phpstorm.html
          # - https://untoldhq.com/blog/2019/08/02/when-lando-phpstorm-and-xdebug-setup-gets-hairy

env_file:
  - .env

# Improve performance by excluding some stuff, see https://docs.lando.dev/config/performance.html#performance
# The excluded files are decoupled from the host, which means that changes made to these files on the host won't
# be synchronized to the container. On the downside, lando rebuild will be slower because of excludes.
excludes:
  - .idea
  - .platform
  - .yarn
  - node_modules
  - vendor
  - "!vendor/cloud-solutions"
```
