### ISSUE TITLE
Custom nginx service for Laravel app.

### ISSUE THREAD

**Issue by Haqz** [lando/lando#2797]
Hello, i have question. For some reason when i create own nginx service i get error 403, here's log of service:
```
2021/01/07 11:18:56 [error] 186#0: *1 directory index of "/app/public/" is forbidden, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:49259"
```
As i searched web someone said to use `autoindex on;` but it didnt do anything.

nginx config:
```
server {
    user www-data;
    listen 80;
    listen [::]:80 ipv6only=on;

    # For https
    # listen 443 ssl;
    # listen [::]:443 ssl ipv6only=on;
    # ssl_certificate /etc/nginx/ssl/default.crt;
    # ssl_certificate_key /etc/nginx/ssl/default.key;

    server_name localhost;
    root /app/public/;
    index index.php index.html index.htm;
    location / {
         try_files $uri /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }


    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }

}
```

.lando.yml:
```
name: test
services:
  appserver:
    type: php:7.4
    webroot: public
    config:
      php: config/php.ini
      server: test.conf
    composer_version: 1
    overrides:
      build:
        context: ./
        dockerfile: Dockerfile.node
  appserver_nginx:
    type: nginx
    webroot: public
    ssl: false
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  database:
    type: mysql:5.7
    portforward: false
    creds:
      user: test
      password: test
      database:  test
  node:
    type: node:14
  mongodb:
    type: mongo
tooling:
  node:
    service: appserver
  npm:
    service: appserver
proxy:
  appserver_nginx:
    - test.lndo.site
```
I know i can use laravel recipe, but it doesnt include node, so i made own Dockerfile to improve `lando rebuild` time, and because of that i had to setup php and nginx service to make everything work
