### ISSUE TITLE
Help using Xdebug with VSCode and the Pantheon recipe

### ISSUE THREAD

**Issue by jacine** [lando/lando#2798]
Hi! 

While spending the last few hours trying to debug why xDebug is no longer working, I realized there is a new version of xDebug, and tried to adjust the configuration to what [xDebug 3 needs](https://xdebug.org/docs/upgrade_guide). No matter what I do, my custom `php.ini` file is NOT being loaded, and apparently that seems to be on purpose with the Pantheon recipe according to https://github.com/lando/lando/issues/986#issuecomment-391401941.

I realize it will be supported in the next version of Lando, but until that happens is it possible to downgrade xDebug to version 2, so it can be used right now? Or do I need to dump the Pantheon recipe entirely (super frustrated with it and leaning toward this anyway, but I'm curious)?  

Any help would be greatly appreciated! Thank you! 😄

**Comment by jacine** [comment]
I see the code to support v3 is in the latest release. However, it does not work, because `xdebug.start_with_request` needs `yes`, as opposed to `trigger`, and potentially [other settings](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug)... Hacking the `php.ini` files directly doesn't work, because they just get overridden when lando starts. 😭

**Comment by derickr** [comment]
`trigger` should work in combination with any of the browser extensions to "trigger" the debugging request: https://xdebug.org/docs/step_debug#browser-extensions

**Comment by jacine** [comment]
Hi @derickr,

Thank you so much for your help! 😄

I read that `trigger` should work as well, but for whatever reason it just didn't, until I changed that setting to `yes` (which I cannot do with the Pantheon recipe, because it doesn't allow a custom `php.ini`).

However, after your post, I went back and kept trying, because I can't see anyone else knowing better than you... and after more trial and error, I was able to get it working. It's still not 100%. I get an error (notice?) in the terminal with every Lando command, but it works where I need it, so I'm happily ignoring it for now.

Long story short:

- I needed `develop,debug` to activate step debugging.
- I needed to set `XDEBUG_SESSION_START: LANDO`

---

Here's the working config for anyone else that runs into this.

## Working config with Pantheon Recipe

```yml
name: name
recipe: pantheon
config:
  framework: drupal8
  xdebug: develop,debug
services:
  appserver:
    overrides:
      environment:
        # NOTE: Without this line, no local variables are available; only superglobal and user defined constants.
        XDEBUG_SESSION_START: LANDO
```

While the above works, I get this error/notice with every Lando command (sometimes multiple):

`Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(`

## VS Code Config

Just in case it helps someone else, here is my `launch.json` file:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9003,
      "log": true,
      "pathMappings": {
        "/app": "${workspaceRoot}",
      }
    }
  ]
}
```

**Comment by rbomhof** [comment]
@jacine Thank you so much for posting this, was extremely helpful for me this morning trying to get XDebug back up and running with the Pantheon recipe!

**Comment by rabauss** [comment]
You can even simply add `xdebug:true` - but for CLI debugging you need the environment variable!

````yml
...
services:
    appserver:
        xdebug: true
        overrides:
            environment:
                XDEBUG_SESSION_START: lando
````
We should add that config to the docs for xdebug!
