### ISSUE TITLE
/etc/hosts changes after restart

### ISSUE THREAD

**Issue by jigarius** [lando/lando#2799]
## The objective

  * I need to set up `sendmail` in a `ruby` container.
    * The Ruby part is working correctly.
  * I need to set `/etc/hosts` to be `example.com`.

## The approach

```yml
services:
  appserver:
    type: compose
    services:
      image: ruby:custom
      command: tail -f /dev/null
    overrides:
      build: lando/spca-scanner
      # Ideally, these should come from the .env file in the same directory as the .lando.yml
      # After many attempts, I accepted defeat and chose to put the vars under here.
      environment:
        HOSTNAME: example.com
        MAILER_FROM: no-reply@example.com
        MAILER_TO: john.doe@example.com
    build:
      - bundle install
    run_as_root:
      - echo $HOSTNAME > /etc/hostname
      - echo -e "127.0.0.1\t\t$HOSTNAME" >> /etc/hosts
```

## The problem

  * After the first `lando start`, the `/etc/hostname` is just the way I want it.
  * After `lando restart`, the `/etc/hostname` becomes something else, e.g. `ad2e83145257`.
  * How do I make the `/etc/hostname` to stay as `$HOSTNAME`?
  * Additionally, is there a way to make `env_file` use the `.env` file at the root of my project?
    * At the moment, it seems to be looking for one at some path like `.lando/compose/projectname/.env`.
