### ISSUE TITLE
Force https

### ISSUE THREAD

**Issue by sgurlt** [lando/lando#2811]
Hey,

i am currently trying to run lando on a remote host, therefor i changed the bind port to 0.0.0.0 as reported here: https://github.com/lando/lando/issues/2807

I am now facing the issue that my Drupal site is redirecting me from https to http, but just on the frontpage :-P
![image](https://user-images.githubusercontent.com/8554668/104728081-adc2b000-5736-11eb-91fd-b6d69793699e.png)

All other pages are loading just fine via https.
I have added the following within my .htaccess to enforce https:

`RewriteCond %{HTTP_HOST} ^www\.(.+)$ [NC]`
`RewriteRule ^ http%{ENV:protossl}://%1%{REQUEST_URI} [L,R=301]`

This is the Drupal default .htaccess file and normally this works very well.
I keep and searching and post the solution here when I found it, maybe someone else faces the same issue :)

Btw. is it possible to tell lando to enforce https?

**Comment by sgurlt** [comment]
So after days of debugging i figured out that the reason why I am getting thrown back to http is that the X-Forward-Proto on the server is set to http instead of https.
The reason for that is that the site is sitting behind an load balancer and the traefic needs to be configured to forward incoming headers.
Therefor I have to add: https://doc.traefik.io/traefik/v2.3/routing/entrypoints/#forwarded-headers to my configuration.
What I have tried for now is:

```
proxy:
  appserver:
    - hostname: "default-export.d9.integration-tests.cms-content-sync.io"
      port: 80
      pathname: /
      middlewares:
        - name: web-secure
          key: forwardedHeaders
          value: insecure
```

But when I do that the page shows me a 404 and I can not see any errors in the log...
