### ISSUE TITLE
Platform.sh multiapp applications.yaml not picked up

### ISSUE THREAD

**Issue by markushausammann** [lando/lando#2822]
> What is your lando version and operating system?
latest lando (v3.0.23), latest MacOS (Big Sur)

```yml
name: web
recipe: platformsh
config:
  id: <actual id>
proxy:
  web:
    - web.lndo.site
```

The project defines four platform.sh apps in `.platform/applications.yaml`. The separate apps therefore have no `.platform.app.yaml` files.

When running `lando start` inside the source root for the applications, e.g. in the `web` directory that contains the lando config posted above, I get the error:

> **ERROR** ==> Could not detect any valid .platform.app.yaml files in /Users/markushausammann/LocalDev/ba-web-environment/web or its subdirs! 

This is correct, there aren't any and there shouldn't be any. Lando is supposed to look for `.platform/applications.yaml` but it does not seem to do that.

The whole error message is:
```
ERROR ==> Could not detect any valid .platform.app.yaml files in /Users/markushausammann/LocalDev/ba-web-environment/web or its subdirs! 
Unhandled rejection TypeError: Cannot read property 'name' of undefined
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/integrations/lando-platformsh/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js)
    at /snapshot/lando/build/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11
```

**Comment by pirog** [comment]
@markushausammann i'm not able to replicate this. Multi-app seems to load from `.platform/applications.yaml` as expected. That said, the error message is out of date so that should at least be updated. 

If you post the `applications.yaml` or a redacted version thereof i can give yours a whirl.

**Comment by pirog** [comment]
@markushausammann one caveat that might be relevant here is that the lando recipe currently only supports php applications so if your multiapp contains only non-php applications then that might explain the behavior. I'll update the message here to be more explicit.

**Comment by markushausammann** [comment]
@pirog thanks for getting back to me, here's the respective `applications.yaml`. Nothing to redact so it's the full file. Does that help to understand where the problem might be?

```
- name: science
  source:
    root: science
  type: "php:7.4"
  build:
    flavor: none
  timezone: Europe/Zurich
  disk: 256
  web:
    locations:
      "/":
        "root": "public"
        index:
          - "index.html"
        # The number of seconds whitelisted (static) content should be cached.
        expires: 600
        scripts: true
        allow: true
        rules:
          \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
            allow: true

- name: styleguide
  source:
    root: styleguide
  type: "php:7.4"
  build:
    flavor: none
  timezone: Europe/Zurich
  disk: 256
  web:
    locations:
      "/":
        "root": "public"
        index:
          - "index.html"
        # The number of seconds whitelisted (static) content should be cached.
        expires: 600
        scripts: true
        allow: true
        rules:
          \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
            allow: true

- name: web
  source:
    root: web
  type: "php:7.4"
  build:
    flavor: none
  timezone: Europe/Zurich
  runtime:
    extentions:
      - imagick
  hooks:
    build: |
      set -e
      curl -sS https://platform.sh/cli/installer | php
  crons:
    renewcert:
      spec: "0 3 1,15 * *"
      cmd: "platform redeploy --yes --no-wait"
  relationships:
    "database": "mysqldb:mysql"
  disk: 256
  web:
    locations:
      "/":
        "root": "public"
        # The front-controller script to send non-static requests to.
        passthru: "/index.php"
        headers:
          X-Frame-Options: SAMEORIGIN
          Strict-Transport-Security: max-age=31536000; includeSubDomains
          X-Content-Type-Options: nosniff
          Referrer-Policy: strict-origin-when-cross-origin
        # Wordpress has multiple roots (wp-admin) so the following is required
        index:
          - "index.php"
        # The number of seconds whitelisted (static) content should be cached.
        expires: 600
        scripts: true
        allow: true
        rules:
          \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
            allow: true
          ^/sitemap\.xml$:
            allow: true

- name: world-domination
  source:
    root: world-domination
  type: "php:7.4"
  build:
    flavor: none
  timezone: Europe/Zurich
  disk: 256
  web:
    locations:
      "/":
        "root": "public"
        index:
          - "index.php"
        headers:
          X-Frame-Options: SAMEORIGIN
          Strict-Transport-Security: max-age=31536000; includeSubDomains
          X-Content-Type-Options: nosniff
          Referrer-Policy: strict-origin-when-cross-origin
        # The number of seconds whitelisted (static) content should be cached.
        expires: 600
        scripts: true
        allow: true
        rules:
          \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
            allow: true
```
