### ISSUE TITLE
Pantheon Drupal 9 recipe/framework combo not working.

### ISSUE THREAD

**Issue by aaronlsilber** [lando/lando#2831]
**Tell us about your setup**
Lando v3.0.24 on WSL2

**Tell us about your `.lando.yml`**

```yml
name: [omitted]
recipe: pantheon
config:
  framework: drupal9
  site: [omitted]
  id: [omitted]
```

**Tell us about the command you were running**

I ran lando init, chose the pantheon recipe, selected a new site running on Pantheon's Drupal 9 Early Access (integrated composer), and pulled the codebase down.

**Tell us about the error you got**

When running `lando start`, I receive an error that declares;
`The services "appserver_nginx" is not running!`
and I can't access the site.

If I manually insert the `drupal8` framework and rebuild, I can access the site, though it notes that an outdated MariaDB version (10.1.44-MariaDB) is installed.

@dustinleblanc noted that "I bet they added a Drupal 9 framework and we just haven't caught up" in the Slack. Lauren from Pantheon confirmed.

**Comment by pirog** [comment]
@aaronlsilber i still get `drupal8` as the framework for a new D9 site. How did you get a site using `drupal9`? 

@dustinleblanc, care to figure out how we can get a site spun that has `drupal9` as the framework?

**Comment by aaronlsilber** [comment]
Sorry @pirog , I wasn't very clear. When running `lando init` the first time, I choose a Drupal 9 site on Pantheon and it does indeed use the `drupal8` framework, which doesn't work.

```yml
name: [omitted]
recipe: pantheon
config:
  webroot: web
  framework: drupal8
  site: [omitted]
  id: [omitted]
```

I tried to be sneaky by swapping it out for `drupal9`.
