### ISSUE TITLE
How to map root folder to container sub-directory correctly?

### ISSUE THREAD

**Issue by maximilianoertel** [lando/lando#2836]
I'm attempting to setup Lando on a repo that is used for WP plugin development. That repo structure looks something like this: 

```
wp/
dist/
src/
vendor/
node_modules/
my-plugin.php
.lando.yml
package.json
composer.sjon
…
```
WordPress being installed from the `wp` directory, I need a way to mount the plugin inside `wp/wp-content/plugins/my-plugin/` so I figured I could just mount this as volume like this in my `.lando.yml`: 

```
name: my-plugin
recipe: wordpress
config:
  php: '7.4'
  via: nginx
  webroot: wp
  database: mariadb
  xdebug: true
  keys: false
services:
  appserver:
    overrides:
      volumes:
        - ./:/app/wp/wp-content/plugins/my-plugin
        - ./wp:/app/wp
    run:
      - wp core download
      - wp config create --skip-check --force
      - wp core install --title="Dev Env" --admin_user=root --admin_password=root --admin_email=admin@example.com --skip-email
      - wp theme activate twentytwentyone
      - composer install
events:
  pre-destroy: 
    - rm -rf wp/
  pre-rebuild: 
    - rm -rf wp/
``` 

And this works as expected, but I must be doing something wrong because when running `lando rebuild -y` Lando deletes the complete content of my local repo folder, except the folder path `wp/wp-content/plugins/my-plugin` (just the folders, the files are gone). 

Removing the `rm -rf wp/` from the `pre-destroy` and `pre-rebuild` events seems to resolve the problem. However I would like to remove the `wp` folder when rebuilding the containers to force a WP re-install.

Any idea what I might be doing wrong here? Any help would be much appreciated!
