### ISSUE TITLE
lando start/rebuild fails

### ISSUE THREAD

**Issue by heymarkreeves** [lando/lando#2847]
> Before you submit an issue make sure you have [downloaded](https://github.com/lando/lando/releases) the latest version of Lando and checked to see if the latest version resolves your issue!

It doesn't.

> 1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.

I did.

> 2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.

I did.

> What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.0.25 on macOS 10.15.7.

> **Tell us about your `.lando.yml`**

```
name: ####
recipe: lamp
config:
  php: '7.4'
  database: mysql:8.0.23
  webroot: ./####.com
services:
  appserver:
    xdebug: true
    config:
      php: .lando/php.ini
tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root

  xdebug-off:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root
```

> It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our default config.

```
[PHP]
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
xdebug.mode = debug
xdebug.client_host = ${LANDO_HOST_IP}
xdebug.client_port = 9003
xdebug.start_with_request = yes
xdebug.log = /tmp/xdebug.log
```

**Tell us about the command you were running**

Whether I do `lando start` or `lando rebuild` or `lando destroy` and then `lando rebuild`, it hangs after:

```
Creating ####_appserver_1 ... done
```

It's always at this spot if I look in Docker:

```
time="2021-02-04T03:32:26Z" level=debug msg="Creating middleware" entryPointName=https middlewareName=traefik-internal-recovery middlewareType=Recovery
```

This isn't the first time this has happened. If I hit ctrl+c, it breaks and then resumes to set up the database server. But if I don't do that it's hung forever at this spot and I can't use lando. And when it resumes and starts up the database server, it says there were errors.

```
Creating network "####_default" with the default driver
Creating volume "####_data_appserver" with default driver
Creating volume "####_home_appserver" with default driver
Creating volume "####_data_database" with default driver
Creating volume "####_home_database" with default driver
Creating ####_appserver_1 ... done
#### 22:39:11 DEBUG ==> process pid8 finished with exit code 0
#### 22:39:11 DEBUG ==> process pid9 running /Applications/Docker.app/Contents/Resources/bin/docker-compose/docker-compose exec appserver /helpers/user-perms.sh cstdio=inherit, silent=false, mode=spawn, detached=false
#### 22:39:12 DEBUG ==> process pid9 finished with exit code 0
#### 22:39:12 DEBUG ==> process pid10 running /Applications/Docker.app/Contents/Resources/bin/docker-compose/docker-compose exec appserver /bin/sh docker-php-ext-enable xdebug cstdio=[inherit, pipe, pipe], silent=false, mode=spawn, detached=false
#### 22:39:13 DEBUG ==> process pid10 finished with exit code 0
#### 22:39:13 DEBUG ==> process pid11 running /Applications/Docker.app/Contents/Resources/bin/docker-compose/docker-compose exec appserver /bin/sh /helpers/install-composer.sh 2.0.7 cstdio=[inherit, pipe, pipe], silent=false, mode=spawn, detached=false
```
