### ISSUE TITLE
404  not found for wp-admin

### ISSUE THREAD

**Issue by danharper83** [lando/lando#2857]
I have spun up a default wordpress recipe and the site works correctly until I try and access an admin page.

I get 404 not found when trying to access /wp-admin my config is as follows

```
name: site-wp
recipe: wordpress
config:
  webroot: wordpress
  via: nginx
  database: mariadb
services:
  appserver:
    run_as_root:
      # Symlink theme
      - ln -snf /app/themes/decksaver /app/wordpress/wp-content/themes/
      # Symlink plugins (temporary until they can be moved to composer)
      - ln -snf /app/plugins/acf-extended /app/wordpress/wp-content/plugins/
      - ln -snf /app/plugins/advanced-custom-fields-pro /app/wordpress/wp-content/plugins/
      - ln -snf /app/plugins/advanced-custom-fields-font-awesome /app/wordpress/wp-content/plugins/
      - ln -snf /app/plugins/gravityforms /app/wordpress/wp-content/plugins/
      - ln -snf /app/plugins/instagram-feed-pro /app/wordpress/wp-content/plugins/
      - ln -snf /app/plugins/wp-all-import-pro /app/wordpress/wp-content/plugins/
      - ln -snf /app/plugins/wp-control /app/wordpress/wp-content/plugins/
      - ln -snf /app/plugins/wpai-acf-add-on /app/wordpress/wp-content/plugins/
      - ln -snf /app/plugins/wpai-woocommerce-add-on /app/wordpress/wp-content/plugins/
```
