### ISSUE TITLE
Solr 8.6 fails to start

### ISSUE THREAD

**Issue by dedavidson** [lando/lando#2866]
**What is your lando version and operating system?**

v3.0.24 on MacOS Big Sur 11.2.1

**Tell us about your `.lando.yml`**

```yml
name: xxxx
recipe: wordpress
config:
  php: '7.4'
  webroot: docroot
  config:
    database: lando-config/my-custom.cnf
proxy:
  search:
    - search.xxxx.lndo.site:8983
services:
  search:
    type: solr:8.6
    portforward: true
    core: xxxx
    config:
      dir: lando-config/solr
```

**Tell us about the command you were running**

```bash
lando start
```

**Tell us about the error you got**

The search service fails to start and fails its healthcheck. The logs show the following:

```bash
search_1     | Executing /start-solr.sh lando-config/solr
search_1     | Booting solr with...
search_1     | CORE: xxxx
search_1     | CONFIG CUSTOM: lando-config/solr
search_1     | DATADIR: /opt/solr/server/solr/mycores
search_1     | INSTALL DIR: /opt/solr
search_1     | Executing /opt/docker-solr/scripts/precreate-core xxxx /solrconf
search_1     | Created xxxx
search_1     | cp: cannot create directory '/opt/solr/server/solr/mycores/xxxx/conf/': No such file or directory
```

**Tell us more**

This may be similar to issue #2830 although the log contents are different. This is preventing me from using lando as I need to replicate the production environment. I can get Solr 8.2 to work but the Solr config needs 8.6 as features used are only available in 8.6+

*Note I have replaced client name with xxxx*

**Comment by ayalon** [comment]
I have the same problem. Solr 8.6 does not work. This one is critical.

**Comment by justafish** [comment]
I had the same issue when I switched to custom config and needed to switch the data dir
```
  solr:
    type: solr:8.4.0
    portforward: false
    core: newevergreen
    config:
      dir: modules/contrib/search_api_solr/jump-start/solr8/config-set
    overrides:
      environment:
        LANDO_SOLR_DATADIR: /var/solr/data
```
