### ISSUE TITLE
Pantheon recepie - How to configure custom domain on 80/443?

### ISSUE THREAD

**Issue by hades200082** [lando/lando#2869]
I have this in my lando.yml

```
name: mysite
recipe: pantheon
config:
  framework: wordpress
  site: mysite
  id: <removed>
proxy:
  edge:
    - mysite.local
```

I have created a local CA and certificate for `*.local` on my PC.

Every time I do `lando start` it gives me the following URLs:

```
 NAME                  leeconlin
 LOCATION              D:\Projects\Personal\Pantheon\leeconlin
 SERVICES              appserver_nginx, appserver, database, cache, edge_ssl, edge, index
 APPSERVER_NGINX URLS  https://localhost:32949
                       http://localhost:32950
 EDGE_SSL URLS         https://localhost:32952
 EDGE URLS             http://localhost:32951
                       http://mysite.local:8000/
                       https://mysite.local:444/
```

I just want to be able to open `mysite.local` in my browser and have it work. This is crucial because a lot of premium wordpress plugins require their licenses to be activated on a specific "site" and that includes the port number... but .local doesn't count as a license requirement in some.
