### ISSUE TITLE
Curl from a custom container to Varnish SSL not working

### ISSUE THREAD

**Issue by sgurlt** [lando/lando#2882]
Hi,

I am currently facing an issue where I want to call a Rest Interface within my Appserver, which is sitting behind varnish (ssl), from another custom container within my lando env.

Here is my lando config:

```
name: cs-integrations_tests-drupal_9
recipe: drupal9
config:
  webroot: docroot
  drush: "^9"
  xdebug: false
  config:
    php: hosting/php/.lando.php.ini
proxy:
  varnish:
    - "default-export.d9.localhost"
    - "default-import.d9.localhost"
    - "syndication-site-1.d9.localhost"
    - "syndication-site-2.d9.localhost"
    - "syndication-site-3.d9.localhost"
    - "fresh-export.d9.localhost"
    - "fresh-import.d9.localhost"
    - "default-export.d9.integration-tests.example.io"
    - "default-import.d9.integration-tests.example.io"
    - "syndication-site-1.d9.integration-tests.example.io"
    - "syndication-site-2.d9.integration-tests.example.io"
    - "syndication-site-3.d9.integration-tests.example.io"
    - "fresh-export.d9.integration-tests.example.io"
    - "fresh-import.d9.integration-tests.example.io"

services:
  # Drupal
  appserver:
    scanner: false
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=d9"

  varnish:
    type: varnish
    scanner: false
    backends:
      - appserver
    backend_port: 80
    ssl: true

  redis:
    type: redis
    portforward: true

  # Drupal - Databases
  default-export:
    type: mysql:5.7
    config:
      confd: lando/mysql/conf.d

  default-import:
    type: mysql:5.7
    config:
      confd: .lando/mysql/conf.d

  syndication-site-1:
    type: mysql:5.7
    config:
      confd: .lando/mysql/conf.d

  syndication-site-2:
    type: mysql:5.7
    config:
      confd: .lando/mysql/conf.d

  syndication-site-3:
    type: mysql:5.7
    config:
      confd: .lando/mysql/conf.d

  fresh-export:
    type: mysql:5.7
    config:
      confd: .lando/mysql/conf.d

  fresh-import:
    type: mysql:5.7
    config:
      confd: .lando/mysql/conf.d

  # Content Sync
  sync-core-mongo:
    type: mongo
    portforward: true

  sync-core-main:
    type: compose
    app_mount: delegated
    overrides:
      environment:
        NODE_TLS_REJECT_UNAUTHORIZED: 0
    services:
      image: myImage
      command: bash -c "[ -d config ] && cp -R config/. docroot/; ./forever.sh"
      ports:
        - '8691'
      depends_on:
        - sync-core-mongo
      volumes:
        - ./hosting/config/sync-core/main:/srv/api-unify/config

  sync-core-content-syndication:
    type: compose
    app_mount: delegated
    overrides:
      environment:
        NODE_TLS_REJECT_UNAUTHORIZED: 0
    services:
      image: myImage
      command: bash -c "[ -d config ] && cp -R config/. docroot/; ./forever.sh"
      ports:
        - '8691'
      depends_on:
        - sync-core-mongo
      volumes:
        - ./hosting/config/sync-core/content-syndication:/srv/api-unify/config

  sync-core-fresh-installation:
    type: compose
    app_mount: delegated
    overrides:
      environment:
        NODE_TLS_REJECT_UNAUTHORIZED: 0
    services:
      image: myImage
      command: bash -c "[ -d config ] && cp -R config/. docroot/; ./forever.sh"
      ports:
        - '8691'
      depends_on:
        - sync-core-mongo
      volumes:
        - ./hosting/config/sync-core/fresh-installation:/srv/api-unify/config

tooling:
  redis-cli:
    service: redis
  xdebug:
    description: Loads Xdebug in the selected mode.
    cmd:
      - appserver: /app/hosting/scripts/xdebug.sh
    user: root
  update-syndication-sites:
    service: appserver
    description: Update database, Import configuration, Export config to sync core.
    dir: /app/docroot
    cmd:
      - "echo 'Updating: @d9.syndication-site-1.local' && drush @d9.syndication-site-1.local cr && drush @d9.syndication-site-1.local updb -y && drush @d9.syndication-site-1.local cim -y && drush @d9.syndication-site-1.local cse"
      - "echo 'Updating: @d9.syndication-site-2.local' && drush @d9.syndication-site-2.local cr && drush @d9.syndication-site-2.local updb -y && drush @d9.syndication-site-2.local cim -y && drush @d9.syndication-site-2.local cse"
      - "echo 'Updating: @d9.syndication-site-3.local' && drush @d9.syndication-site-3.local cr && drush @d9.syndication-site-3.local updb -y && drush @d9.syndication-site-3.local cim -y && drush @d9.syndication-site-3.local cse"
  update-default-sites:
    service: appserver
    description: Update database, Import configuration, Export config to sync core.
    dir: /app/docroot
    cmd:
      - "echo 'Updating: @d9.default-export.local' && drush @d9.default-export.local cr && drush @d9.default-export.local updb -y && drush @d9.default-export.local cim -y && drush @d9.default-export.local cse"
      - "echo 'Updating: @d9.default-import.local' && drush @d9.default-import.local cr && drush @d9.default-import.local updb -y && drush @d9.default-import.local cim -y && drush @d9.default-import.local cse"
```

What I am trying is do a curl from `sync-core-main` to one of the varnished served ssl domains.
The sites can be opened without any problem via my browser, but curl returns me:

```
curl: (7) Failed to connect to default-import.d9.integration-tests.example.io port 443: Connection refused
```

Any idea what is going wrong here?

Best regards,
Sebastian

**Comment by pirog** [comment]
@sgurlt varnish does not serve over https itself, it requires ssl termination to be provided for it. Lando uses nginx to do this. I _think_ if you run `lando info` you should be able to see the name of the service that is providing this. You will want to use that.

**Comment by sgurlt** [comment]
> @sgurlt varnish does not serve over https itself, it requires ssl termination to be provided for it. Lando uses nginx to do this. I _think_ if you run `lando info` you should be able to see the name of the service that is providing this. You will want to use that.

I see, so i checked `lando info`:

```
{ service: 'varnish_ssl',
    urls: [ 'https://localhost:37173' ],
    type: 'nginx',
    healthy: true,
    backend: 'edge',
    managed: true,
    config: '/home/ec2-user/.lando/config/varnish/ssl-termination.conf.tpl',
    version: 'custom',
    meUser: 'www-data',
    hasCerts: true,
    hostnames: [ 'varnish_ssl.csintegrationstestsdrupal9.internal' ] },
  { service: 'varnish',
    urls:
      [ 'http://localhost:37169',
        'http://default-export.d9.localhost/',
        'https://default-export.d9.localhost/',
        'http://default-import.d9.localhost/',
        'https://default-import.d9.localhost/',
        'http://syndication-site-1.d9.localhost/',
        'https://syndication-site-1.d9.localhost/',
        'http://syndication-site-2.d9.localhost/',
        'https://syndication-site-2.d9.localhost/',
        'http://syndication-site-3.d9.localhost/',
        'https://syndication-site-3.d9.localhost/',
        'http://fresh-export.d9.localhost/',
        'https://fresh-export.d9.localhost/',
        'http://fresh-import.d9.localhost/',
        'https://fresh-import.d9.localhost/',
        'http://default-export.d9.integration-tests.example.io/',
        'https://default-export.d9.integration-tests.example.io/',
        'http://default-import.d9.integration-tests.example.io/',
        'https://default-import.d9.integration-tests.example.io/',
        'http://syndication-site-1.d9.integration-tests.example.io/',
        'https://syndication-site-1.d9.integration-tests.example.io/',
        'http://syndication-site-2.d9.integration-tests.example.io/',
        'https://syndication-site-2.d9.integration-tests.example.io/',
        'http://syndication-site-3.d9.integration-tests.example.io/',
        'https://syndication-site-3.d9.integration-tests.example.io/',
        'http://fresh-export.d9.integration-tests.example.io/',
        'https://fresh-export.d9.integration-tests.example.io/',
        'http://fresh-import.d9.integration-tests.example.io/',
        'https://fresh-import.d9.integration-tests.example.io/' ],
    type: 'varnish',
    healthy: true,
    backends: [ 'appserver' ],
    ssl_served_by: 'varnish_ssl',
    config: {},
    version: '4.1',
    meUser: 'varnish',
    hasCerts: true,
    hostnames: [ 'varnish.csintegrationstestsdrupal9.internal' ] },
```

How can I ensure that `varnish_ssl` also listens to `https://default-import.d9.integration-tests.example.io/'` e.g.?
I tried the following:

```
proxy:
  varnish:
    - "default-export.d9.localhost"
    - "default-import.d9.localhost"
    - "syndication-site-1.d9.localhost"
    - "syndication-site-2.d9.localhost"
    - "syndication-site-3.d9.localhost"
    - "fresh-export.d9.localhost"
    - "fresh-import.d9.localhost"
    - "default-export.d9.integration-tests.example.io"
    - "default-import.d9.integration-tests.example.io"
    - "syndication-site-1.d9.integration-tests.example.io"
    - "syndication-site-2.d9.integration-tests.example.io"
    - "syndication-site-3.d9.integration-tests.example.io"
    - "fresh-export.d9.integration-tests.example.io"
    - "fresh-import.d9.integration-tests.example.io"
  varnish_ssl:
    - "default-export.d9.localhost"
    - "default-import.d9.localhost"
    - "syndication-site-1.d9.localhost"
    - "syndication-site-2.d9.localhost"
    - "syndication-site-3.d9.localhost"
    - "fresh-export.d9.localhost"
    - "fresh-import.d9.localhost"
    - "default-export.d9.integration-tests.example.io"
    - "default-import.d9.integration-tests.example.io"
    - "syndication-site-1.d9.integration-tests.example.io"
    - "syndication-site-2.d9.integration-tests.example.io"
    - "syndication-site-3.d9.integration-tests.example.io"
    - "fresh-export.d9.integration-tests.example.io"
    - "fresh-import.d9.integration-tests.example.io"
 ```

And:

```
proxy:
  varnish_ssl:
    - "default-export.d9.localhost"
    - "default-import.d9.localhost"
    - "syndication-site-1.d9.localhost"
    - "syndication-site-2.d9.localhost"
    - "syndication-site-3.d9.localhost"
    - "fresh-export.d9.localhost"
    - "fresh-import.d9.localhost"
    - "default-export.d9.integration-tests.example.io"
    - "default-import.d9.integration-tests.example.io"
    - "syndication-site-1.d9.integration-tests.example.io"
    - "syndication-site-2.d9.integration-tests.example.io"
    - "syndication-site-3.d9.integration-tests.example.io"
    - "fresh-export.d9.integration-tests.example.io"
    - "fresh-import.d9.integration-tests.example.io"
```

Without any luck for now.
