### ISSUE TITLE
Unable to add route via proxy when using Lagoon integration

### ISSUE THREAD

**Issue by tobybellwood** [lando/lando#2887]
When using the Lando Lagoon integration, we should be able to add a custom route (either lndo.site or custom DNS) as per https://docs.lando.dev/guides/lando-101/lando-proxy.html

However, when trying this, even with a vanilla project (such as https://github.com/amazeeio/drupal-example-simple) the custom routes defined in the .lando.yml are not usable - but the default routes (eg mailhog) are.
```
name: drupal8-example-simple
recipe: lagoon
config:
  flavor: drupal
  build:
    - composer install
proxy:
  nginx:
    - abcde.lndo.site
```
![image](https://user-images.githubusercontent.com/4373945/109570993-12976580-7b3f-11eb-9f08-c6e416c1c836.png)

I have tested alongside this with a default (non-lagoon) Lando project and it all works as expected as per documentation.

**Comment by pirog** [comment]
@tobybellwood thanks for the report. Let me see if i can replicate.

**Comment by pirog** [comment]
Running against latest Lando 3.0.26, steps to replicate:

1. `git clone --branch 8.x https://github.com/amazeeio/drupal-example-simple.git amazee-d8-example`
2. `cd amazee-d8-example`
3. `lando start`

4. Above seems to work as expected. Now, replace the `.lando.yml` with:

```yaml
name: drupal8-example-simple
recipe: lagoon
config:
  flavor: drupal
  build:
    - composer install
proxy:
  nginx:
    - abcde.lndo.site
```
5. `lando rebuild`

<img width="824" alt="Screen Shot 2021-03-02 at 8 26 04 AM" src="https://user-images.githubusercontent.com/713424/109655141-eecd2300-7b30-11eb-9c73-364af31a4a6b.png">

A key difference for me here is that i am getting a `502` Bad Gateway and not a `404` which is what @tobybellwood said he had.

**Comment by pirog** [comment]
@tobybellwood, try this

```yaml
name: drupal8-example-simple
recipe: lagoon
config:
  flavor: drupal
  build:
    - composer install
proxy:
  nginx:
    - abcde.lndo.site:8080
```

The `lagoon` nginx service runs on port `8080` by default so you need the extra `:8080`. If you omit it defaults to `:80` which is what the `lando` nginx service uses. We might just want to document this somewhere.
