### ISSUE TITLE
Wrong webroot generated inside appserver service

### ISSUE THREAD

**Issue by introfini** [lando/lando#2907]
(I'm running v3.0.26 on macOS BigSur)

If I run the following command that sets the **webroot** to **web**:

```lando init --source cwd --recipe drupal9 --webroot web --name my-site --full```

The generated `.lando.yml` is generated with a `webroot: .` inside `appserver`. 

Is this a bug?

***.lando.yml file:***

```yml
name: my-site
recipe: drupal9
config:
  webroot: web
proxy:
  appserver:
    - my-site.lndo.site
services:
  appserver:
    build_internal: []
    composer: {}
    config: {}
    ssl: true
    type: 'php:7.4'
    via: apache
    xdebug: false
    webroot: .
    overrides:
      environment:
        SIMPLETEST_BASE_URL: 'https://appserver'
        SIMPLETEST_DB: 'mysql://drupal9:drupal9@database/drupal9'
  database:
    config: {}
    authentication: mysql_native_password
    type: mysql
    portforward: true
    creds:
      user: drupal9
      password: drupal9
      database: drupal9
tooling:
  composer:
    service: appserver
    cmd: composer --ansi
  db-import <file>:
    service: ':host'
    description: Imports a dump file into a database service
    cmd: /helpers/sql-import.sh
    user: root
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
      no-wipe:
        description: Do not destroy the existing database before an import
        boolean: true
  'db-export [file]':
    service: ':host'
    description: Exports database from a database service to a file
    cmd: /helpers/sql-export.sh
    user: root
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
      stdout:
        description: Dump database to stdout
  php:
    service: appserver
    cmd: php
  mysql:
    service: ':host'
    description: Drops into a MySQL shell on a database service
    cmd: mysql -uroot
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
  drush:
    service: appserver

```

**Comment by Unifex** [comment]
This just happened to me so it is still an ongoing thing.

Until this is resolved it can resolved with setting:
```yaml
services:
  appserver:
    webroot: web
```
Follow up with a `lando rebuild` to have it recognised.
