### ISSUE TITLE
Running WordPress on Lando: "Could not reach WordPress.org"

### ISSUE THREAD

**Issue by leoloso** [lando/lando#2913]
**Tell us about your setup**

What is your lando version and operating system?

`v3.0.26` on MacOS

**Tell us about your `.lando.yml`**

```yml
name: graphql-api
recipe: wordpress
config:
  webroot: wordpress
  php: '7.4'
  ssl: true
  database: mariadb
  xdebug: false
  config:
    php: ../shared/config/php.ini
services:
  database:
    portforward: true
  appserver:
    overrides:
      volumes:
        - >-
          ../../layers/GraphQLAPIForWP/plugins/graphql-api-for-wp:/app/wordpress/wp-content/plugins/graphql-api
    run:
      - >-
        wp config create --dbname=wordpress --dbuser=wordpress
        --dbpass=wordpress --dbhost=database --skip-check --force
        --path=wordpress
      - >-
        wp core install --url=graphql-api.lndo.site --title="GraphQL API"
        --admin_user=admin --admin_password=admin
        --admin_email=admin@example.com --path=wordpress
      - cp assets/.htaccess wordpress
      - wp rewrite structure '/%postname%/' --hard --path=wordpress
      - wp plugin activate graphql-api --path=wordpress
      - wp plugin install wordpress-importer --activate --path=wordpress
      - wp import assets/graphql-api-sample-data.xml --authors=create --path=wordpress
      - >-
        sed 's/__DIR__/dirname(__DIR__)/' wordpress/index.php >
        wordpress/Schema/index.php
      - cp wordpress/Schema/index.php wordpress/API/index.php
      - cp wordpress/Schema/index.php wordpress/Engine/index.php
      - cp wordpress/Schema/index.php wordpress/GraphQLByPoP/index.php
env_file:
  - ../../layers/GraphQLAPIForWP/plugins/graphql-api-for-wp/lando/defaults.env

```

`php.ini`:

```ini
[PHP]

; Xdebug
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
; Extra custom Xdebug setting for debug to work in VSCode.
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_host = ${LANDO_HOST_IP}
; xdebug.remote_connect_back = 1
xdebug.remote_log = /tmp/xdebug.log
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

```bash
lando start
```

**Tell us generally about your bug**

Since upgrading to `v3.0.26`, my WordPress site cannot reach wordpress.org anymore.

I tried with 2 different WordPress sites:

- One, after changing PHP to `8.0` and then doing `lando rebuild`
- Another one, without changing anything, still built from version `v3.0.23`, just doing `lando start`

In both cases, I get the following error in WordPress' Site Health screen:

```
Could not reach WordPress.org

Communicating with the WordPress servers is used to check for new versions, and to both install and update WordPress core, themes or plugins.

Error Your site is unable to reach WordPress.org at 198.143.164.251, and returned the error: cURL error 28: Resolving timed out after 10002 milliseconds

Get help resolving this issue. (opens in a new tab)
```

<img width="1140" alt="Screenshot 2021-03-17 at 5 10 23 PM" src="https://user-images.githubusercontent.com/1981996/111442868-c7d33b80-8743-11eb-93a9-08139906ad66.png">

In the first case, the `rebuild` also partially failed, because I'm installing the WordPress importer in `.lando.yml` and that failed, with error:

```
Warning: wordpress-importer: An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/forums/">support forums</a>.
Error: No plugins installed.
ERROR ==> Error: No plugins installed. 
```

<img width="937" alt="Screenshot 2021-03-17 at 5 11 45 PM" src="https://user-images.githubusercontent.com/1981996/111442978-e33e4680-8743-11eb-930c-8c94df32a88f.png">

This is not an issue with WordPress.org: I can communicate perfectly from my non-Lando sites.
