### ISSUE TITLE
NGINX Using multiple php-fpm containers

### ISSUE THREAD

**Issue by Xilonz** [lando/lando#2921]
I'm trying to create a setup where we can quickly check if our plugin is working in \w multiple PHP versions.

NGINX is cycling through the available PHP services, no matter what NGINX service you are visiting. On each visit, the next service will be used.

The cause of this issue is the static network name that is used for the php-fpm service ([defined here](https://github.com/lando/lando/blob/2f11e2e48b70d5622834a616adf2350d0b3f140a/plugins/lando-services/services/php/builder.js#L158)). All the services will get the same network alias, so NGINX doesn't have a clue which PHP service belongs to him.

```yml
recipe: wordpress
name: myphpproject
config:
  php: '7.4'
  config:
    vhosts: .lando/default.conf.tpl
proxy:
  appserver_nginx:
    - myphpproject.lndo.site
  php80_nginx:
    - 80-myphpproject.lndo.site
  php56_nginx:
    - 56-myphpproject.lndo.site
services:
  php80:
    type: php:8.0
    via: nginx
    webroot: .
  php56:
    type: php:5.6
    via: nginx
    webroot: .
```

/w overrides it would (probably, untested) look like this:
```yml
  php56:
    type: php:5.6
    via: nginx
    config:
       vhosts: .lando/56-default.conf.tpl #we need to change file so we can change the upsteam php
    overrides:
      networks:
        default:
          aliases: 
            - fpm3
```yml

Ideally, we would be able to attach multiple PHP services to one NGINX service. I've tried setting the `via` to `cli` and `image` to `fpm` so no additional NGINX service will be created and used the overrides mentioned above. This seems to work, however, I haven't figured out the correct NGINX config yet.

Any other suggestions for quickly switching between PHP versions are also welcome. NGINX is required.
