### ISSUE TITLE
Platform.sh recipe SSL connection between containers

### ISSUE THREAD

**Issue by simonkey** [lando/lando#2926]
I've a multi app setup with the platform.sh recipe. Everything works fine, except it is not possible to make a curl request from one service to another.

Setup (simplified):
Service: api -> api.test.lndo.site
Service: app -> www.test.lndo.site
Both services have an own `.platform.app.yaml`
Lando Version: v3.0.26

Two upstreams in the `routes.yaml`

```yaml
"https://www.{default}/": &upstreamApp
    type: upstream
    upstream: "app:http"

"https://api.{default}/": &upstreamApi
    type: upstream
    upstream: "api:http"
```

`.lando.yml`

```yml
name: test
recipe: platformsh
config:
  id: xxxx
  via: nginx
  xdebug: true
```

Both services are accessable via the browser via https://api.test.lndo.site and https://www.test.lndo.site, so the proxies does work. But if I try the following:
* Access to one of the services (e.g. the api service): `lando ssh`
* Make a curl request: `curl https://www.test.lndo.site/`
* The curl request results in `curl: (7) Failed to connect to api.mayspeedguide.lndo.site port 443: Connection refused`
* A non https-request works without problems

I've tried the symfony recipe and here the communication between the services works fine.
