### ISSUE TITLE
platform.sh recipe: CLI xdebug not working

### ISSUE THREAD

**Issue by simonkey** [lando/lando#2927]
There seems to be a problem with the platform.sh recipe and xdebug for CLI commands, e.g. via lando php bin/console some:cli:command.

Lando version: v3.0.26

`.platform.app.yaml`:
```yml
name: api
type: php:7.4
build:
    flavor: composer
runtime:
    xdebug:
        idekey: PHPSTORM
    extensions:
...
        - xdebug # tried with and without extension
        - ...
```
`.lando.yml`:
```yml
name: mayspeedguide
recipe: platformsh
config:
  id: xxx
  via: nginx
  xdebug: true
```
I've followed the instructions in https://docs.lando.dev/guides/lando-phpstorm.html#debugging-drush-commands, but its *only* working for requests from the browser and not via CLI command.

As solution I've tried to set the enviroment variable `XDEBUG_CONFIG` manually, with `remote_enable=1 remote_mode=req remote_port=9000 remote_host=xxx remote_connect_back=0`. Unfortunately this seems not to work, especially the dynamic ip for `remote_host` cannot be set easily. Furthermore change this settings depending on the xdebug version (2 or 3).

I've tried the symfony recipe and here the debugging worked nearly out of the box for CLI commands.

**Comment by pirog** [comment]
@simonkey have you done cli debugging directly on platform.sh itself? Did that work as expected? If so, can you give me some steps to replicate. 

I know that platform.sh actually runs a separate php-fpm instance for xdebug so its possible that is set up to handle xdebug requests but the php binary is still configured to handle the non-debug requests.

**Comment by simonkey** [comment]
@pirog No, I haven't done any cli debugging on platform.sh itself. I've done the whole debugging stuff on my local machine and so there wasn't any need to debug on platform.sh.

I've taken a look in the code and found the "normal" php service the following

```javascript
 const php = {
...
        environment: _.merge({}, options.environment, {
          PATH: options.path.join(':'),
          LANDO_WEBROOT: `/app/${options.webroot}`,
          XDEBUG_CONFIG: xdebugConfig(options._app.env.LANDO_HOST_IP),
          XDEBUG_MODE: (options.xdebug === false) ? 'off' : options.xdebug,
        }),
...
      };
```
https://github.com/lando/lando/blob/ff53f2c23732e395f224aee77cbf84edc5806b60/plugins/lando-services/services/php/builder.js#L152

Maybe something similar should be added in https://github.com/lando/lando/blob/master/integrations/lando-platformsh/services/platformsh-php/builder.js.

**Comment by pirog** [comment]
Have you tried setting those envvars directly?

**Comment by simonkey** [comment]
So after some research and trying, I've found out how to enable xdebug for the platform.sh recipe.

The most important part is to enable the xdebug-Extension in the `.platform.app.yaml`. After this, the `XDEBUG_CONFIG` and `PHP_IDE_CONFIG` variables can be set via `lando ssh`. 

**Setup for xdebug 2:**
- Enable the xdebug-Extension in `.platform.app.yaml`
- `lando rebuild`
- `lando ssh`
- `export XDEBUG_CONFIG="remote_enable=1 remote_mode=req remote_port=9000 remote_host=$LANDO_HOST_IP remote_connect_back=0" && export PHP_IDE_CONFIG="serverName=appserver"`
- `php your-script-to-debug.php`

**Setup for xdebug 3:**
`.lando.yml`:
- remove `xdebug: true`
- add the following:
```yaml
config:
    variables:
        app:
            php:
                xdebug.discover_client_host: true
                xdebug.mode: debug
```

Debugging itself:
- Enable the xdebug-Extension in `.platform.app.yaml`
- `lando rebuild`
- `lando ssh`
- `export XDEBUG_CONFIG="client_host=$LANDO_HOST_IP" && export PHP_IDE_CONFIG="serverName=appserver"`
- `php your-script-to-debug.php`

For the export of the variables, I've made a `.bashrc` with a bash-alias. So I can call `lando ssh`, `. .bashrc`, `xdebug`, `php script-to-debug.php`. 
Is there a way to add a .bashrc file, that it is added to the other bash scripts?

I've tried tooling, but there seems to be a problem with the `source` command (
https://github.com/lando/lando/issues/2941).

Maybe you can add these steps to the documentation.
