### ISSUE TITLE
EDGE URLS are red, and page loads with 404

### ISSUE THREAD

**Issue by HeatherC747** [lando/lando#2931]
**Tell us about your setup**

v3.0.26 on macOS Big Sur version 11.2.3

**Tell us about your `.lando.yml`**

```yml
name: heather-onboarding
recipe: pantheon
config:
  framework: wordpress
  site: heather-onboarding
  id: 7c0980c2-550f-44ce-a154-6df0695efd8a
```

`pantheon.yml`
# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1
```

**Tell us about the command you were running**

```bash
lando start
```

**Tell us generally about your bug**

Lando starts up just fine and the app server URLs load the page fine and in terminal they display in GREEN.  However the Edge URLs in terminal display in RED, and when trying to access the url in the browser it returns a 404 page.

**Tell us more**

Warning Message:
Using an unsupported version of DOCKER DESKTOP
   You have version 3.3.0 but Lando wants something in the 2.1.0.0 - 3.1.99 range.
   If you have purposefully installed an unsupported version and know what you are doing
   you can probably ignore this warning. If not we recommend you use a supported version
   as this ensures we can provide the best support and stability.
   https://docs.docker.com/docker-for-mac/release-notes/

I am on a Mac machine with an M1 processor and am forced to use the new Docker Desktop for Apple Silicon.  So I don't think I can revert to a previous version of Docker...
