### ISSUE TITLE
Options in the middle of the command

### ISSUE THREAD

**Issue by rpayanm** [lando/lando#2937]
I would like to make a tooling like this: `drush @:alias sql:drop -y && pv :file | drush @:alias sql:cli`:

```
drush-db-restore:
    description: Restores a db
    service: appserver
    cmd: /app/vendor/bin/drush @:alias sql:drop -y && pv :path | /app/vendor/bin/drush @:alias sql:cli
    options:
      alias:
        describe: Drush alias
     file:
       describe: File path
``` 

But when I run this command:
```
lando drush-db-restore --alias=lando.mysite --path=/tmp/dump063645.sql
```
I got this error:
```
Command @:alias was not found. Drush was unable to query the database. As a result, many commands are unavailable. Re-run your command with --debug to see relevant log messages.
```

How can I pass an option in the middle of the command?
