### ISSUE TITLE
chmod: changing permissions of '/user/.ssh/id_rsa': Operation not permitted

### ISSUE THREAD

**Issue by wesleymusgrove** [lando/lando#2938]
**Tell us about your setup**

What is your lando version and operating system?

v3.0.26 on Windows 10 Enterprise

**Tell us about your `.lando.yml`**

```yml
name: exampled8

recipe: drupal8

config:
  php: '7.4'
  ## Bypass this receipe's default /helpers/install-composer.sh because it doesn't use the proxy stream context.
  composer_version: false
  via: apache:2.4
  webroot: docroot
  database: mysql:5.7
  drush: ^9
  xdebug: true
  ssl: true

proxy:
  appserver:
    - www.exampled8.lando

## Password protected keys are supposed to work, but I ran into this error: "Permissions 0755 for '/user/.ssh/id_rsa' are too open".
## And I was never being prompted to enter a password when the SSH key was being used during a build step so I converted it to be a non-password protected key.
keys:
  - id_rsa

services:
  appserver:
    ## Use a custom php.ini to instruct curl and openssl to use the ca-all.pem, which includes the Zscaler Root CA.
    config:
      php: .lando/config/php.ini
    build_as_root:
      - cp /app/.lando/config/ZscalerRootCertificate2048SHA256.pem /usr/local/share/ca-certificates/ZscalerRootCertificate2048SHA256.crt && chmod 644 /usr/local/share/ca-certificates/ZscalerRootCertificate2048SHA256.crt
      - cp /app/.lando/config/ca-all.pem /usr/local/share/ca-certificates/ca-all.pem && chmod 644 /usr/local/share/ca-certificates/ca-all.pem
      - update-ca-certificates
    build:
      - cp /app/.lando/config/.curlrc ~/.curlrc
      - cp /app/.lando/config/config ~/.ssh/config
      - mkdir -p ~/.drush/site-aliases
      - ln -sf /app/drush/sites/www.site.yml ~/.drush/site-aliases/www.site.yml
      ## Install composer using a custom script instead of letting Lando's recipe do it because I need to set the default stream context inline for php's copy command.
      - /app/.lando/scripts/install-composer.sh 2-latest
      - composer --version
      - composer install
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://www.exampled8.lando"
        SITE_ENVIRONMENT: "local"
        AH_SITE_ENVIRONMENT: "local"
        COMPOSER_PROCESS_TIMEOUT: "2000"
        COMPOSER_MEMORY_LIMIT: "-1"
        HTTP_PROXY: "http://host.docker.internal:9000"
        HTTPS_PROXY: "http://host.docker.internal:9000"
        HTTP_PROXY_REQUEST_FULLURI: 0
        HTTPS_PROXY_REQUEST_FULLURI: 0
        ## This defaults to 9003, which was already set to both 9001 and 9003 in PHPStorm somehow.
        #XDEBUG_CONFIG: "client_port=9001"
        PHP_IDE_CONFIG: "serverName=lando"
    ## You have to run this as root user since the temporary database gets written to /tmp and is root only
    ## Permissions seemed to be correct in Windows after adding Write Deny for all users, but not with the files when they were copied over to /user/.ssh in the appserver
    run_as_root:
      #- /app/scripts/scripts/dev-sql-sync.sh
      - cd /app/docroot && drush sql:sync @www.remote_prod @www.local -y
    run:
      - cd /app/docroot && drush config:import --yes

  database:
    type: mysql:5.7
    ## Use a dedicated external port so PHPStorm can connect to it.
    ## The internal lando port will always be 3306, which is what the appserver uses to connect to the database container.
    portforward: 3307

tooling:
  drupal:
    service: appserver
    cmd: drupal
  drush:
    service: appserver
    cmd: /app/vendor/drush/drush/drush --root=/app/docroot
  pull-dev-db:
    service: appserver
    user: root
    cmd: drush sql:sync @www.remote_dev @www.local -y
  config-import:
    service: appserver
    dir: /app/docroot/
    cmd: cd /app/docroot && drush config:import
  config-export:
    service: appserver
    dir: /app/docroot/
    cmd: cd /app/docroot && drush config:export
  acli-install:
    service: appserver
    cmd: 
      ## Uncomment this if you need to remove it and re-install it
      #- rm /usr/local/bin/acli && rm -rf ~/.acquia && rm -rf ~/.acquia*
      - curl -OL https://github.com/acquia/cli/releases/latest/download/acli.phar
      - chmod +x acli.phar
      - mv acli.phar /usr/local/bin/acli
      - /app/.lando/scripts/acli-setup.sh
  acli:
    service: appserver
    cmd: acli
  acli-pull-database:
    service: appserver
    cmd: acli pull:database
  acli-pull-files:
    service: appserver
    cmd: acli pull:files
```

**Tell us about the command you were running**

```bash
lando start

# Edited my lando.yml as above
lando rebuild -y

# And specifically when this command runs as a "run_as_root" build step:
run_as_root:
      - cd /app/docroot && drush sql:sync @www.remote_prod @www.local -y
```

**Tell us about the error you got**

When the appserver builds it throws this error trying to chmod my id_rsa SSH key:
`Ensuring permissions and ownership of /user/.ssh/id_rsa...
chmod: changing permissions of '/user/.ssh/id_rsa': Operation not permitted`

```
STARTING UP

██  █████  ███  ██ ██████  ██████ 
██  ██   ██ ████  ██ ██   ██ ██    ██ 
██  ███████ ██ ██  ██ ██  ██ ██  ██ 
██  ██   ██ ██  ██ ██ ██  ██ ██  ██ 
███████ ██  ██ ██   ████ ██████   ██████  

The best local development tool in the galaxy!            

===============================================================

userperms 05:56:16.61 INFO ==> Symlinked users .gitconfig.
userperms 05:56:16.62 INFO ==> Symlinked users known_hosts
userperms 05:56:16.63 INFO ==> This is a debian container
userperms 05:56:16.65 INFO ==> user-perms.sh kicking off as user uid=0(root) gid=0(root) groups=0(root)
userperms 05:56:16.65 DEBUG ==> Lando ENVVARS set at
userperms 05:56:16.66 DEBUG ==>
userperms 05:56:16.66 DEBUG ==> ========================================
userperms 05:56:16.67 DEBUG ==> LANDO_WEBROOT_USER : www-data
userperms 05:56:16.68 DEBUG ==> LANDO_WEBROOT_GROUP : www-data
userperms 05:56:16.69 DEBUG ==> LANDO_WEBROOT_UID : 33
userperms 05:56:16.69 DEBUG ==> LANDO_WEBROOT_GID : 33
userperms 05:56:16.70 DEBUG ==> LANDO_HOST_UID : 1000
userperms 05:56:16.71 DEBUG ==> LANDO_HOST_GID : 1000
userperms 05:56:16.72 DEBUG ==> ========================================
userperms 05:56:16.74 DEBUG ==>
userperms 05:56:16.76 INFO ==> Making sure correct user:group (www-data:www-data) exists...
userperms 05:56:17.02 INFO ==> Remapping ownership to handle docker volume sharing...
userperms 05:56:17.03 INFO ==> Resetting www-data:www-data from 33:33 to 1000:1000
userperms 05:56:17.47 INFO ==> www-data:www-data is now running as uid=1000(www-data) gid=1000(www-data) groups=1000(www-data)!
userperms 05:56:17.48 INFO ==> And here. we. go.
userperms 05:56:17.49 INFO ==> Doing the permission sweep.
loadkeys 05:56:17.75 WARN ==> Creating a special not-mounted key directory for Windows
loadkeys 05:56:17.78 DEBUG ==> Copying /lando/keys/acli_keys from /lando/keys to /lando_keys
loadkeys 05:56:17.83 INFO ==> Scanning /lando_keys for keys...
loadkeys 05:56:17.86 INFO ==> Found keys /lando_keys/acli_keys /user/.ssh/id_rsa
loadkeys 05:56:17.88 DEBUG ==> Ensuring permissions and ownership of /lando_keys/acli_keys...
loadkeys 05:56:17.90 DEBUG ==> Checking whether /lando_keys/acli_keys is a private key...
loadkeys 05:56:17.91 DEBUG ==> Ensuring permissions and ownership of /user/.ssh/id_rsa...
chmod: changing permissions of '/user/.ssh/id_rsa': Operation not permitted
loadkeys 05:56:17.95 DEBUG ==> Checking whether /user/.ssh/id_rsa is a private key...
loadkeys 05:56:17.98 DEBUG ==> Checking whether /user/.ssh/id_rsa is formatted correctly...
loadkeys 05:56:18.02 INFO ==> Using the following keys: /user/.ssh/id_rsa
addcert 05:56:18.15 INFO ==> Enabling apache ssl modz
addcert 05:56:18.17 INFO ==> Cert creation kicking off....
```

I think because the appserver isn't able to change the permissions of the id_rsa file, I get the following error when trying to use that id_rsa file for a drush command which tries to pull the database down locally from a remote site:

```yml
run_as_root:
      - cd /app/docroot && drush sql:sync @www.remote_prod @www.local -y
```

Here's the error is gets:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0755 for '/user/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/user/.ssh/id_rsa": bad permissions
exampled8.prod@exampled8.ssh.prod.acquia-sites.com: Permission denied (publickey).
```

I can see that in `C:\Users\username\.lando\scripts\load-keys.sh` on line 91, it's trying to `chmod 600 "$SSH_CANDIDATE` this id_rsa file.  That seems to be where the failure is happening when my appserver builds.
```
# Go through and validate our candidates
for SSH_CANDIDATE in "${SSH_CANDIDATES[@]}"; do
  lando_debug "Ensuring permissions and ownership of $SSH_CANDIDATE..."
  chown -R $LANDO_WEBROOT_USER:$GROUP "$SSH_CANDIDATE"
  chmod 600 "$SSH_CANDIDATE"
  lando_debug "Checking whether $SSH_CANDIDATE is a private key..."
...
```

I'm aware that file permissions in Windows are really dumb compared to *nix.  I followed these instructions for how to change the file permissions in Windows from someone who was experiencing a similar "file permissions are too open" error: https://stackoverflow.com/questions/9270734/ssh-permissions-are-too-open-error/53679145#53679145

I have added "Deny" write permissions to the id_rsa file in Windows.  Other than denying write permissions, it has full control.  I'm not sure if it should be anything different from this?  Whether or not I deny write permissions, the appserver still fails to `chmod 600` the id_rsa file.

![image](https://user-images.githubusercontent.com/1711791/112726398-31dda480-8eeb-11eb-9679-ff0e4bc8a223.png)

I'm copying over my SSH config in a build step like this:
```
build:
      - cp /app/.lando/config/config ~/.ssh/config
```

This SSH config file looks like this:
```
Host exampled8.prod
  HostName web-1234.prod.hosting.acquia.com
  Port 22
  User exampled8.prod
  ForwardAgent yes
  IdentityFile ~/.ssh/id_rsa
```

You can see that this config is using the same id_rsa file and interestingly I am able to ssh into my appserver and then ssh into my remote server without error.
```
$ lando ssh
www-data@477f30fdec2f:/app$ ssh exampled8.prod

Welcome to Acquia Cloud. For information about shell access on this
server, please see: https://docs.acquia.com/cloud-platform/manage/ssh/

Usage may be monitored and audited.

exampled8@web-1234:~$
```

So is it the drush command that's throwing a fit about the permissions of that file because the Lando appserver failed to `chmod 600` it?
