### ISSUE TITLE
Installing a custom PHP extension (grpc)

### ISSUE THREAD

**Issue by psaikali** [lando/lando#2940]
Hi,

I'm trying to install the `grpc` extension on a Lando install using the WordPress recipe following https://docs.lando.dev/guides/installing-php-extensions-on-lando.html#_1-using-build-steps

My `.lando.yml` looks like that:
```
name: freebulle
recipe: wordpress
config:
  webroot: .
  php: '7.4'
  via: apache
  database: mariadb
  config:
    php: config/php.ini
services:
  grpc:
    type: php
    build_as_root:
      - pecl install grpc
      - docker-php-ext-install grpc
      - docker-php-ext-enable grpc
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts:
      - database
proxy:
  appserver:
    - freebulle.wp
    - freebulle.eu.ngrok.io
  mailhog:
    - mail.freebulle.wp
  pma:
    - db.freebulle.wp
```

My `config/php.ini` files contains:
```
extension=grpc.so
```

Here is the key part of what happens after rebuild:

```
Build process completed successfully
Installing '/usr/local/lib/php/extensions/no-debug-non-zts-20190902/grpc.so'
install ok: channel://pecl.php.net/grpc-1.36.0
configuration option "php_ini" is not set to php.ini location
You should add "extension=grpc.so" to php.ini
error: /usr/src/php/ext/grpc does not exist

usage: /usr/local/bin/docker-php-ext-install [-jN] [--ini-name file.ini] ext-name [ext-name ...]
   ie: /usr/local/bin/docker-php-ext-install gd mysqli
       /usr/local/bin/docker-php-ext-install pdo pdo_mysql
       /usr/local/bin/docker-php-ext-install -j5 gd mbstring mysqli pdo pdo_mysql shmop

if custom ./configure arguments are necessary, see docker-php-ext-configure

Possible values for ext-name:
bcmath bz2 calendar ctype curl dba dom enchant exif ffi fileinfo filter ftp gd gettext gmp hash iconv imap intl json ldap mbstring mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql pdo_oci pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline reflection session shmop simplexml snmp soap sockets sodium spl standard sysvmsg sysvsem sysvshm tidy tokenizer xml xmlreader xmlrpc xmlwriter xsl zend_test zip
```

I'm not sure what's going on. Does anybody know how I could fix this?

Thanks a lot!

**Comment by psaikali** [comment]
Playing with things...

```
name: freebulle
recipe: wordpress
config:
  webroot: .
  php: '7.4'
  via: apache
  database: mariadb
services:
  grpc:
    type: php
    build_as_root:
      - pecl install grpc
      - pecl install protobuf
      - docker-php-ext-install grpc
      - docker-php-ext-enable grpc
      - docker-php-ext-install protobuf
      - docker-php-ext-enable protobuf
    config:
      php: config/php.ini
```

If I `lando ssh -s grpc -c "php -m"` after rebuild, I do see the grpc and protobuf extension. But a `phpinfo()` on my site does not show me these extensions. I'm missing some relationship logic between services I guess...

**Comment by psaikali** [comment]
```
...
services:
  appserver:
    type: php
    build_as_root:
      - pecl install grpc
      - pecl install protobuf
      - docker-php-ext-enable grpc
      - docker-php-ext-enable protobuf
...
```

This worked! See https://docs.lando.dev/config/services.html#build-steps

Credits to @dustinleblanc 💟
