### ISSUE TITLE
platform.sh recipe: source in multi command tooling not working

### ISSUE THREAD

**Issue by simonkey** [lando/lando#2941]
When using the platform.sh recipe the tooling does not work as expected as described in https://docs.lando.dev/config/tooling.html#multi-command-tooling. 

I've created a simple tooling command

```yaml
tooling:
    test:
        cmd:
            - source .bashrc
            - echo "hello"
    test2:
        cmd:
            - echo "hello"
```

Calling `lando test` results in the error: 
`/helpers/psh-exec.sh: 36: exec: source: not found`

If I call `lando test2` "hello" is echoed.

Lando version: 3.0.28

**Comment by pirog** [comment]
@simonkey i needed to wrap `source` in `bash` for it to work as expected. I _think_ although im not 100% sure that the testing commands are run with `sh` and `source` is a `bash` specific thing.

```yaml
tooling:
  test:
    service: app
    cmd:
        - bash -c "source .bashrc"
        - echo "hello"
```

All that said i think the best way to handle sourcing for platform apps is to probably use of it's `.environment` file, see https://github.com/lando/lando/issues/2927#issuecomment-813406329
