### ISSUE TITLE
Lando tooling for a one off command: What's best practice?

### ISSUE THREAD

**Issue by edwardcrompton** [lando/lando#2944]
Do all lando services have to contain a process that runs indefinitely? What is the best practice way to create a service for a command that runs once and then exits?

Here's some context:

I want to create a lando command to run a one-off process (to export a mysql database to sqlite). It seems like a clean approach to run this command in a service of its own since there are a few dependencies which I would prefer not to clutter other services with.

I've set up a new custom service of type 'compose' and I'm using a custom Dockerfile to define this service:

```
services:
  ...  
  sequel:
    type: compose
    services:
      build:
        context: ./lando/sequel
      command: 'sequel'

tooling:
  db-dump-sqlite:
    service: sequel
    description: Export sanitised database to Sqlite
    cmd: 'sequel ...'
```
When I restart Lando the command in the sequel service runs and then exits. Lando throws a warning with the error: 

```
Starting testlando_sequel_1 ... done
ERROR: No container found for sequel_1
```

Then if I run

`lando db-dump-sqlite`

I again get an error because the sequel container is not running. I understand that this is because the lando tooling runs a command using `docker exec`, not `docker run`, so it's assumed that there is already a running container to issue the command in. 

Should I make some sort of dummy process that persists inside my custom service container inorder to ensure the container is always running? I wondered if there is another approach for one off commands or whether I'm just approaching this with the wrong mindset to begin with?
