### ISSUE TITLE
Drupal 8 recipe is overriding Composer 2 install

### ISSUE THREAD

**Issue by justafish** [lando/lando#2946]
```
name: arboreal
recipe: drupal8
config:
  php: '7.4'
  composer_version: 2
.
.
.
```

This installs Composer 2 to `/usr/local/bin/composer`, but this is overridden by a binary of Composer 1 at `/app/vendor/bin/composer`

My temporary workaround -
```
services:
  appserver:
    # Composer 2 is installed to /usr/local/bin/composer, delete this binary
    # of Composer 1 which is overriding it.
    run:
      - rm -f /app/vendor/bin/composer

```
