### ISSUE TITLE
Acquia Recipe Always Uses Composer 2

### ISSUE THREAD

**Issue by anthonybarsotti** [lando/lando#2964]
I have an Acquia site that I'm trying to clone down into lando but the site needs Composer version ^1.0 and regardless of the version specified in the .lando.yml files' `config.composer_version` setting, it's still using version 2.0.12. I've tried destroying and rebuilding after updating the .lando.yml with several different values specified for the `composer_version` setting (I tried `1`, `'1'`, and `'1.10.21'`) and it still used 2.0.12. I was able to get around this issue in my case by using the `config.build.run_scripts: false` option to disable `acli pull:run-scripts` which prevented it from using composer during the init step but I'm still curious as to why it wouldn't use version 1 based on my config.

Lando YML:
```yml
name: test
recipe: acquia
config:
  acli_version: master
  ah_application_uuid: // removed for security reasons
  ah_site_group: test
  php: '7.3'
  composer_version: 1
```
