### ISSUE TITLE
Database data volumes

### ISSUE THREAD

**Issue by xenx-efy** [lando/lando#2971]
Hi guys, sorry, maybe I should read documentation more attentively, but still how I can share database data folder to my local machine? ‘overriding‘ statement allow only override /bitnami/mariadb/data to my local folder content, for example. 
In 'compose' way of resolving my problem I have not figured it out.  

I tried that code:
```
database:
    overrides:
      volumes:
        - ./backups/mysql:/var/lib/mysql
```
