### ISSUE TITLE
Platformsh basic template fails to start

### ISSUE THREAD

**Issue by steviewanders** [lando/lando#2981]
1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.

`Done`

2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.

`Done`

The **FASTEST** way for us to verify and resolve your bug if for you to [write a functional test that breaks](https://docs.devwithlando.io/dev/testing.html#functional-tests), submit it as a pull request and link to that pull request here.

^ is a broken link...

If you are not sure how to do that then please complete as much of the below section as possible

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

`v3.0.26, macOS Big Sur 11.3`

**Tell us about your `.lando.yml`**

```yml
name: hakai-ssg-test
recipe: platformsh
config:
  id: zqmls2lc3q572
```

`.platform/services.yml`

```yml
db:
    type: mariadb:10.4
    disk: 512
```

` .platform/services.yaml`

```yml

db:
    type: mariadb:10.4
    disk: 512
```

**Tell us about the command you were running**

Any combination of `lando init` and `lando start` or any `lando <command>` using the above config files produces the error.

```bash
lando init 
lando start
```

**Tell us about the error you got**

Rerun the command that produced your error in `debug` mode. Note that `debug` mode is run like this `lando command -vvv`. Paste in the error and the `~100` lines that proceeded it.

```bash
lando start -vvv
Unhandled rejection TypeError: Cannot read property 'split' of undefined
    at /snapshot/lando/build/cli/integrations/lando-platformsh/lib/config.js
    at arrayMap (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:639:23)
    at Function.map (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9580:14)
    at interceptor (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:17046:35)
    at Function.thru (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:8817:14)
    at /snapshot/lando/build/cli/node_modules/lodash/lodash.js:4388:28
    at arrayReduce (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:683:21)
    at baseWrapperValue (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:4387:14)
    at LodashWrapper.wrapperValue (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9072:14)
    at Object.getSyncableRelationships (/snapshot/lando/build/cli/integrations/lando-platformsh/lib/config.js)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/integrations/lando-platformsh/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js)
    at /snapshot/lando/build/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11
```

**Tell us generally about your bug**

Just trying to run a Platform.sh template locally

**Tell us more**

Does this bug prevent you from using lando? `Yes`

**Comment by pirog** [comment]
@steviewanders do you have the application config? eg the stuff in `.platform.app.yaml` or `applications.yaml`? Would be useful to help replicate

**Comment by steviewanders** [comment]
Hey @pirog! Thank you for Lando! Saved me and others countless time trying to reproduce it in Docker Compose

`gatsby/.platform.app.yaml`

```yml

# The name of this application, which must be unique within a project.
name: 'gatsby'

# The type key specifies the language and version for your application.
type: 'nodejs:14'

# Restrict Yarn memory use when running during post deploy hook.
variables:
    env:
        NODE_OPTIONS: --max_old_space_size=1536

# The hooks that will be triggered when the package is deployed.
hooks:
    # Post deploy hook builds Gatsby frontend now that backend content is available.
    post_deploy: |
        npm run build

relationships:
    wordpress: "wordpress:http"

# The size of the persistent disk of the application (in MB).
disk: 1280

# The configuration of the application when it is exposed to the web.
web:
    locations:
        '/':
            # The public directory of the application relative to its root.
            root: 'public'
            index: ['index.html']
            scripts: false
            allow: true

mounts:
  '/.cache':
      source: local
      source_path: cache
  '/.config':
      source: local
      source_path: config
  'public':
      source: local
      source_path: public
```

`wordpress/.platform.app.yaml`

```yml
# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: wordpress

# The runtime the application uses.
type: "php:7.4"

# Configuration of the build of the application.
build:
    flavor: composer

dependencies:
    php:
        composer/composer: '^2'
        wp-cli/wp-cli: "^2.2.0"

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "db:mysql"

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: "wordpress"
            # The front-controller script to send non-static requests to.
            passthru: "/index.php"
            # Wordpress has multiple roots (wp-admin) so the following is required
            index:
                - "index.php"
            # The number of seconds whitelisted (static) content should be cached.
            expires: 600
            scripts: true
            allow: true
            rules:
                ^/composer\.json:
                    allow: false
                ^/license\.txt$:
                    allow: false
                ^/readme\.html$:
                    allow: false
        "/wp-content/cache":
            root: "wordpress/wp-content/cache"
            scripts: false
            allow: false
        "/wp-content/uploads":
            root: "wordpress/wp-content/uploads"
            scripts: false
            allow: true

# The size of the persistent disk of the application (in MB).
disk: 1280

# The mounts that will be performed when the package is deployed.
mounts:
    "wordpress/wp-content/cache":
        source: local
        source_path: "cache"
    "wordpress/wp-content/uploads":
        source: local
        source_path: "uploads"
```

Can you recommend something I can run myself e.g. linter/etc. - on these config files to get a more useful debugging output in future?
