### ISSUE TITLE
appserver recreated without running build_as_root

### ISSUE THREAD

**Issue by iluuu1994** [lando/lando#2994]
We're using Sql Server instead of MySQL. Thus we have to install an additional driver with pecl in the appserver container. To achieve this we're using the `build_as_root` option.

Somewhat simplified **.lando.yml**

```yml
name: xyz
recipe: lemp
appserver:
    build_as_root:
        - apt-get update -yqq
        - apt-get install -y apt-transport-https curl
        - curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
        - curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list
        - apt-get update -yqq
        - ACCEPT_EULA=Y apt-get install -yqq msodbcsql17 unixodbc-dev
        - ACCEPT_EULA=Y pecl install pdo_sqlsrv
        - docker-php-ext-enable pdo_sqlsrv
    type: php:7.4
database:
    overrides:
        image: 'mcr.microsoft.com/mssql/server:2019-latest'
    portforward: true
    type: mssql
```

This works fine. However, sometimes after starting the driver seems to be missing. Unfortunately we weren't able to recognize a pattern yet. `ssh`ing into the container, both the .so and .ini files are missing. So it looks like a fresh container without running the `build_as_root` steps.

![image](https://user-images.githubusercontent.com/1752683/117288823-33947380-ae6c-11eb-946c-d23f9037d181.png)

The only resolution for this is to rebuild the application with `lando rebuild`. Looking at the docker containers it looks like the appserver is newer than the other containers even though I have not explicitly deleted or rebuilt it.

![image](https://user-images.githubusercontent.com/1752683/117288558-ea442400-ae6b-11eb-89f9-c6853064d023.png)

I'm suspecting Lando recreated the container on the fly for some reason but did not re-run the `build_as_root` commands. I'm not familiar with the internals of Lando so I'm not sure if that's possible. Please let me know if you suspect something of if I'm doing something wrong.

**Tell us about your setup**

We have two setups but it happens on both of them. Our entire team faces this issue from time to time (probably once a week).

* Kubuntu (21.04)
* Windows 10 + WSL

Thanks for the response!
