### ISSUE TITLE
Acquia: lando ssh doesn't run remote commands on server

### ISSUE THREAD

**Issue by msbodetti** [lando/lando#2995]
**Tell us about your setup**

*v3.1.2 on macOS Big Sur 11.3*

**Tell us about your `.lando.yml`**

```yml
name: mtndecoupled
recipe: acquia
config:
  acli_version: master
  ah_application_uuid: uuid
  ah_site_group: mtndecoupled
  php: '7.4'
services:
  appserver:
    composer_version: 1-latest
```

**Tell us about the command you were running**

```bash
lando ssh mtndecoupled.ode15
.../app $ drush cim 
```

**Tell us generally about your bug**

I tried to use `lando ssh mtndecoupled.ode15` to connect and run drush commands on the remote server. But it looks like it's reflecting the local environment and not the remote, example is I have outstanding Drupal config to import on remote server but it's showing as nothing to import but on the remote Drupal CMS backend, there's config to be imported.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

```bash
1. Started up local environment: lando start
2. Remotely connect to server: lando ssh mtndecoupled.ode15
3. Run command on remote server: drush cim or drush cex etc.
```

**Tell us more**

I'm not too sure if I am use `lando ssh` correctly. Please let me know if there's an alternative or if I need to use/do something else.
