### ISSUE TITLE
Platform.sh custom xdebug configuration example not working

### ISSUE THREAD

**Issue by scottfalkingham** [lando/lando#3012]
**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/config/platformsh.html#xdebug

**Describe the change you'd like**
The example custom xdebug configuration is not picked up by lando.

```
config:
  id: PROJECT_ID
  overrides:
    app:
      runtime:
        extensions:
          - redis
          - xdebug
      php:
        # XDEBUG 2
        xdebug.remote_enable: 1
        xdebug.remote_mode: req
        xdebug.remote_port: 9000
        xdebug.remote_connect_back: 0
```

After placing the configuration in many different places, the following location was discovered to work correctly.
```
name: PROJECT_ID
config:
  variables:
    app:
      php:
        xdebug.remote_enable: 1
        xdebug.remote_mode: req
        xdebug.remote_port: 9000
        xdebug.remote_connect_back: 0
  overrides:
    app:
      runtime:
        extensions:
          - redis
          - xdebug
```
