### ISSUE TITLE
How do I enable alternate domains using the proxy syntax in .lando.yml

### ISSUE THREAD

**Issue by alphex** [lando/lando#3015]
I've got a D7 site, (From pantheon) that we're trying to enable the DOMAIN module for.

So that it can render at  `sitename.lndo.site` + `site2.lndo.site` + `site3.lndo.site`

Here's my (sanitized) .lando.yml file

```
name: sitename
recipe: pantheon
config:
  framework: drupal
  site: sitename
  id: xxx-xxx-xxx-xxx-xxx
  xdebug: true
proxy:
  mailhog:
    - mailhog-sitename.lndo.site:8001
  node:
    - bs-sitename.lndo.site:3000
  appserver:
    - site2.lndo.site
    - site3.lndo.site
services:
  node:
    type: node:6
    build:
      - "cd /app/sites/all/themes/themename && npm install"
      - "cd /app/sites/all/themes/themename && bower install"
      - "cd /app/sites/all/themes/themename && gulp css"
    command: cd /app/sites/all/themes/themename && gulp serve
    globals:
      gulp-cli: "latest"
      bower: "latest"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
tooling:
  node:
    service: node
  npm:
    service: node
  gulp:
    service: node
  bower:
    service: node
```

When I lando start this, the alternate domains from the proxy section show up, but they show up RED in the start dialog.

```
 NAME                  sitename                                                             
 LOCATION              /Users/duran/dev/sites/sitename/NEW/www                              
 SERVICES              appserver_nginx, appserver, database, cache, edge_ssl, edge, index 
 APPSERVER_NGINX URLS  https://localhost:52596                                            
                       http://localhost:52595                                             
 APPSERVER URLS        http://site2.lndo.site/ {shows up red}                                              
                       http://site3.lndo.site/ {shows up red}                            
 EDGE_SSL URLS         https://localhost:52612                                            
 EDGE URLS             http://localhost:52604                                             
                       http://sitename.lndo.site/                                           
                       https://sitename.lndo.site/   
```

When I try to hit those URLs, it says bad gateway.

The primary, `sitename.lndo.site` domain DOES work.

So I feel like its close, but not quite there.

What am I missing?

Thanks!

Update.
When I run LANDO INFO

I see this in the `appserver` block

```
  {
service: 'appserver',
    urls: [ 'http://site2.lndo.site/', 'http://site3.lndo.site/' ],
    type: 'php',
    healthy: true,
    via: 'nginx:1.16',
    served_by: 'appserver_nginx',
    webroot: '.',
    config:
     { php: '/Users/duran/.lando/config/pantheon/php.ini',
       server: '/Users/duran/.lando/config/pantheon/nginx.conf.tpl',
       vhosts: '/Users/duran/.lando/config/pantheon/drupal.conf.tpl' },
    version: '7.2',
    meUser: 'www-data',
    hasCerts: false,
    hostnames: [ 'appserver.sitename.internal' ]
},
```

**Comment by alphex** [comment]
Ok, I've updated the lando.yml file

```
  edge:
    - mainsite.lndo.site 
    - site1.lndo.site
    - site2.lndo.site
  edge_ssl:
    - mainsite.lndo.site 
    - site1.lndo.site
    - site2.lndo.site
```

Now I can resolve the other domains, BUT
All of them report a 502 error "Bad Gateway" on EVERY OTHER page load.

For example see these two screen shots : https://i.alphex.io/rRuG2qRm and https://i.alphex.io/6qu8y94e

This is showing the exact same CSS file, which on one page load,  loads...
and hitting refresh shows a bad gateway...   IF I reload again, it shows up, if I reload ... it "bad gateway"...

**Comment by pirog** [comment]
@alphex im surprised it even lets you assign the same url to two separate services. i think you just want something like

```
  edge:
    - mainsite.lndo.site 
    - site1.lndo.site
    - site2.lndo.site
```

**Comment by alphex** [comment]
This is solved!
Thank you @pirog 

Here's the final .lando.yml file for everyones reference.

```
name: sitename
recipe: pantheon
config:
  framework: drupal
  site: sitename
  id: xxx-xxx-xxx-xxx-xxx
  xdebug: true
proxy:
  mailhog:
    - mailhog-sitename-recruiting.lndo.site:8001
  node:
    - bs-sitename-recruiting.lndo.site:3000
  edge:
    - sitename.lndo.site 
    - site1.lndo.site
    - site2.lndo.site
services:
  node:
    type: node:6
    build:
      - "cd /app/sites/all/themes/themename && npm install"
      - "cd /app/sites/all/themes/themename && bower install"
      - "cd /app/sites/all/themes/themename && gulp css"
    command: cd /app/sites/all/themes/themename && gulp serve
    globals:
      gulp-cli: "latest"
      bower: "latest"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
tooling:
  node:
    service: node
  npm:
    service: node
  gulp:
    service: node
  bower:
    service: node

```

My original problem was that I was using the APPSERVER service, which, after thinking about it, isn't what your browser talks to.

I then tried to use both EDGE and EDGE_SSL ... and as Pirog said, that will cause errors.

Removing `edge_ssl` solved the issue.

In Drupal,  (this is a Drupal 7 site) I've set up the DOMAIN module, and configured the three domains, and now can move forward using the DOMAIN module (and its family of sub modules) to configure the site as needed.
