### ISSUE TITLE
Provide support for documenting positional arguments

### ISSUE THREAD

**Issue by codebymikey** [lando/lando#3020]
**Please explain your request and its importance in the form of a user story.**

As a lando user who utilizes custom tooling, it'd be nice to be able to provide documentation for positional arguments.

**Describe the solution you'd like**
Provide a configuration tooling property for describing the `yargs` positional argument.
https://github.com/yargs/yargs/blob/master/docs/advanced.md#describing-positional-arguments

With something along the lines of this:
```yaml
tooling:
  test <source>:
    service: appserver
    description: Test tool
    cmd: /app/scripts/testing.sh
    positional:
      source:
        type: string
        default: http://www.google.com
        describe: This is a description of the required positional argument.
```
