### ISSUE TITLE
Running multiple lando instances using d8/9 recipes

### ISSUE THREAD

**Issue by awm086** [lando/lando#3023]
I am trying to run multiple lando projects at the same time but so far I am running into connection issues to the db container when both are running. For example:
I have `acme 1` site with the following config:
```
name: acme
recipe: drupal8

excludes:
  - .idea
  - .git
  - .vscode
config:
  webroot: docroot
  composer_version: '2.0.13'
  php: '7.3'
  drush: ^10
  drupal: true
  config:
    php: .lando/xdebug.ini
proxy:
  pma:
    - pma.lndo.site
services:
  pma:
    type: phpmyadmin
  appserver: 
    environment:
      HASH_SALT: notsosecurehash

    xdebug: true
    pma:
      type: phpmyadmin
    build:
      - composer install
    run:
      - composer self-update

  acme:
    type: mysql:5.7
    portforward: 5433
    config:
      confd: .lando/mysql/conf.d
tooling:
  npm:
    service: appserver
  gulp:
    service: appserver
    
  drush:
    service: appserver
    cmd: /app/vendor/drush/drush/drush

  drupal:
    service: appserver
    cmd: "/app/vendor/bin/drupal --root=/app/docroot"

  xdebug:
    description: Loads Xdebug in the selected mode
    cmd:
      - appserver: /app/.lando/xdebug.sh
    user: root
  xdebug-on:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root


env_file:
  - .lando/.env
```
And I have `ACME 2`
```
name: acme2
recipe: drupal9
# Exclud some directories to improve fs performance.
excludes:
  - .idea
  - .git
  - .vscode
config:
  webroot: docroot
  php: '7.4'
  drush: ^10
  xdebug: on
  drupal: true
  config:
    php: .lando/xdebug.ini
proxy:
  pma:
    - pma.lndo.site
services:

  appserver:
    environment:
      # @TODO
      HASH_SALT: notsosecurehash

    xdebug: true
    build:
      - composer install
    run:
      - composer self-update
  acme2:
    type: mysql:5.7
    portforward: 33068
    config:
      confd: .lando/mysql/conf.d

tooling:

  drush:
    service: appserver
    cmd: /app/vendor/drush/drush/drush

  xdebug:
    description: Loads Xdebug in the selected mode
    cmd:
      - appserver: /app/.lando/xdebug.sh
    user: root
  xdebug-on:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root

env_file:
  - .lando/.env
```

But when I try to run both I get db connection issue:
```
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed
```
**update** 
while reviwing the yml files I noticed there may be conflict with phpmyadmin server and possible mysql port for external connection. That said, I am looking for a guid or a recommended way of doing this.
