### ISSUE TITLE
It is not possible to connect to the database anymore

### ISSUE THREAD

**Issue by ollie-db** [lando/lando#3035]
I am sure I was able to connect to a databases few days ago with phpmyadmin on my local machine that I run on `php -S localhost:8000`

My lando file was like this
````
name: newspaper-app
recipe: drupal9
config:
  webroot: web
````

Now I tried to edit it becuase I am not able to connect, I get `mysqli::real_connect(): (HY000/2002): Connection refused`

So now my lando file looks like this:
````
name: newspaper-app
recipe: drupal9
config:
  webroot: web
services:
  myservice:
    type: php
    config:
      php: php.ini
  phpmyAdmin:
    type: phpmyadmin
    user: drupal9
    password: drupal9
    database: drupal9
    hosts:
      - mysql57
````

And when I follow ` PHPMYADMIN URLS  http://localhost:49170 ` I get 
````
Welcome to  phpMyAdmin 
Cannot connect: invalid settings.
mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
Retry to connect
mysqli::real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
phpMyAdmin tried to connect to the MySQL server, and the server rejected the connection. You should check the host, username and password in your configuration and make sure that they correspond to the information given by the administrator of the MySQL server.
````

**Comment by ollie-db** [comment]
I don't get it. When I use .lando.yml
````
name: newspaper-app
recipe: drupal9
config:
  webroot: web

````

I am able to connect to the database from local machine's phpmyadmin with this
```
root
empty password
$cfg['Servers'][$i]['host'] = '127.0.0.1:49180';
$cfg['Servers'][$i]['AllowNoPassword'] = true;
````

If I add into the recipe
````
name: newspaper-app
recipe: drupal9
config:
  webroot: web
services:
  myservice:
    type: php
    config:
      php: php.ini
````
I can not connect anymore.
And also with lando's phpmyadmin as I stated above.
Can somebody explain me the right way to be able to connect to the database and also be able to use php.ini

**Comment by kburakozdemir** [comment]
I am aware of your scenario is different, however I tried to install Drupal 9 Umami Profile with drupal9 recipe, and then add phpmyadmin service and it works. I mean I can access the drupal9 database through lando's phpmyadmin service.

Hope that this helps.

This is my land config file:

```yaml
name: d9test
recipe: drupal9
config:
  webroot: web
services:
  pma:
    type: phpmyadmin
```

Please make sure that you run `lando rebuild` after making changes to lando config file.

![image](https://user-images.githubusercontent.com/1656836/122377386-b6c9de80-cf6d-11eb-81aa-139816688063.png)

![image](https://user-images.githubusercontent.com/1656836/122377903-28a22800-cf6e-11eb-870b-5ad76531c2eb.png)

**Comment by kburakozdemir** [comment]
in order to use php.ini you could change the lando config file like this and then run `lando rebuild`. (Reference: [Lando Docs PHP](https://docs.lando.dev/config/php.html))

```yaml
name: d9test
recipe: drupal9
config:
  webroot: web
services:
  appserver:
    config:
      php: path/to/php.ini
  pma:
    type: phpmyadmin
```
