### ISSUE TITLE
Proxy wildcard domain routes to localhost from within containers

### ISSUE THREAD

**Issue by drjayvee** [lando/lando#3037]
I'm running Lando ~~3.1.4~~ 3.6.4 on Windows WSL 2 with Docker Desktop ~~1.29.1~~ 4.5.1.

# Setup
My Lando config boils down to
```yaml
name: mos-eisley-scum
services:
  greedo:
    type: php:7.4
    via: apache:2.4

  jabba:
    type: php:7.4
    via: apache:2.4

proxy:
  greedo:
    - "firstshot.lndo.site"
    - "*.greedo.lndo.site"
```

The regular domain (`firstshot.lndo.site`) works fine (see below).

The wildcard domain `*.greedo.lndo.site` works fine from "outside" (my Windows host). (I did have to set up a rebind protection exception in my router as documented.)

# Problem
From inside any container however, it always resolves to `localhost`, i.e. the container itself.
```shell
# pass
docker exec $jabba  sh -c 'curl http://firstshot.lndo.site'   # reaches greedo

docker exec $greedo sh -c 'curl http://greedo.lndo.site'      # reaches greedo

# fail
docker exec $jabba  sh -c 'curl http://evil.greedo.lndo.site' # reaches jabba
docker exec $jabba  sh -c 'curl http://greedo.lndo.site'      # reaches jabba
```

# Expected result
The [documentation](https://docs.lando.dev/config/networking.html#automatic-hostnames) states
> This means that you should also be able to access services across apps using any of their proxy hostnames.

So I expected this to work.
