### ISSUE TITLE
Lando Pushing DB to Pantheon: ERROR 2013 (HY000)

### ISSUE THREAD

**Issue by rayskin** [lando/lando#3043]
Any help on this issue would be greatly appreciated.

Recently upgraded Mac OS to Big Sur, previously Catalina. And now can no longer push DB to Pantheon without this error. 

"ERROR 2013 (HY000) at line 940: Lost connection to MySQL server during query".

I've tried reinstalling a fresh copy of MYSQL, Docker & Lando. 

- Docker: 3.3.3
- Lando 3.1.4
- Mac OS 11.2.3

.Lando.yml
------------------------------------
```
name: wordpress-default-theme
recipe: pantheon
config:
  framework: wordpress
  site: wordpress-default-theme
  id: [REDACTED]
```

Pantheon.yml
------------------------------------
```
# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1
php_version: 7.2
```
