### ISSUE TITLE
Drupal 9 and Drupal Console! 

### ISSUE THREAD

**Issue by mimalef70** [lando/lando#3044]
Hi Guys, 

why we haven't drupal console on Drupal 9 recipe; in Drupal 8 we have "Lando drupal" but in Drupal 9 we can't use this command.

and when I use "vendor/bin/drupal" after installing it with a composer I get this error: 

[ERROR] SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not             known

**Comment by hexblot** [comment]
For me, these are the steps that work:
1. Require drupal console via composer:
````bash
lando composer require drupal/console
````
2. Add the following tooling into .lando.yml file:
````yml
tooling:
  drupal:
    service: appserver
    description: Runs Drupal console
    cmd: /app/vendor/bin/drupal
    user: www-data
````
3. Use it via Lando
````bash
lando drupal generate:module
````
