### ISSUE TITLE
Using vnu in Lando (2021 edition)

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#3077]
Related: [Using vnu with lando in 2020](https://github.com/lando/lando/issues/2731)

[vnu](https://github.com/validator/validator/) has drastically changes its docker image and I'm having trouble getting it to work on lando.

As shown in the [vnu docker file](https://github.com/validator/validator/blob/e68bf0a46f626307a3580f61e60ee2b4a312afe8/Dockerfile#L36), it is using the following command to launch vnu as a local webserver:

`vnu-runtime-image/bin/java -m vnu/nu.validator.servlet.Main 8888`

So I tried configuring my `lando.yml` with the new command:

```
  vnu:
    type: compose
    ssl: true
    sslExpose: false
    services:
      image: ghcr.io/validator/validator:latest
      command: vnu-runtime-image/bin/java -m vnu/nu.validator.servlet.Main 8888
      ports:
        - '8888:8888
```

Unfortunately this doesn't work; `lando start` fails to start the vnu container.

The error in the logs is:

`/lando-entrypoint.sh: 27: /lando-entrypoint.sh: touch: not found`

So I assume I need to slightly adjust the command somehow (for example, `/vnu-runtime-image/bin/java`), but none of the variations I tried got it working.

If I run the container with `docker run ghcr.io/validator/validator` and then ssh into the container via `sh` and execute the command manually, it works.  So the question is, how do I format this command to work in `lando.yml`?
