### ISSUE TITLE
How to allow a Lando app to send a GET request to a VSCode devcontainer

### ISSUE THREAD

**Issue by benterova** [lando/lando#3081]
Hello there!

I'm currently running a Rails app in a VScode Devcontainer, and a WordPress installation running in Lando. The WordPress installation is trying to make a cURL GET request to the app running in the Devcontainer on port 3000

I have made port 3000 active & forwarded according to [this guide](https://code.visualstudio.com/docs/remote/containers#_forwarding-or-publishing-a-port), and ensured the two containers are on the same Docker network. 

When doing `docker network inspect lando_app_default`, I see the following example output under the "Containers" section:

```
"Containers": {
            "c22b4e8b0252d2e5aaa5a57cf834a81e3fe5111860746cc66c081d60c6603c87": {
                "Name": "lando_app_database_1",
                "EndpointID": "9d926fcd68e5455abe9081d3832a6c9edb49050c34653d616d02c078bbf305ff",
                "MacAddress": "02:42:ac:16:00:03",
                "IPv4Address": "172.22.0.3/16",
                "IPv6Address": ""
            },
            "d2032013b3178c2f936c56ee38d3fc51e6dafddc72a436537c3f5b7c5d8c6122": {
                "Name": "portal_devcontainer_web_1",
                "EndpointID": "722cea33efb7040c4d812f4409f26bc3c15859c1b0e438733ec33da0326a441b",
                "MacAddress": "02:42:ac:16:00:04",
                "IPv4Address": "172.22.0.4/16",
                "IPv6Address": ""
            },
            "f9a824de48ba4c0ebe8977d0076c09a8aa60c1f776a7acde4052934af148fb78": {
                "Name": "lando_app_appserver_1",
                "EndpointID": "72367c878ab2f9a73f5ee505ddbe08813586849859c6ee44d870fe652cd66bf3",
                "MacAddress": "02:42:ac:16:00:02",
                "IPv4Address": "172.22.0.2/16",
                "IPv6Address": ""
            }
        }
```

From the container `portal_devcontainer_web_1`, I am able to ping the Docker address `172.22.0.2` and see a response, however I'm not able to replicate the same behavior on the Lando application with the Devcontainer address of `172.22.0.2`

There is a very good chance I'm misunderstanding how Lando's networking works, but I'd love some help in figuring out how to make these two platforms communicate.

EDIT:

My devcontainer's `docker-compose.yml`

```
web:
    user: vscode
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    ports:
      - "3000"
    environment:
      DEV_DB_HOST: db
      DEV_REDIS_HOST: redis
    depends_on:
      - db
      - redis
    volumes:
      - ..:/portal:delegated
   ```

My `.lando.yml`

```
recipe: wordpress
config:
  webroot: .
  php: '7.4'
  via: apache
  database: mysql
  xdebug: true
```
