### ISSUE TITLE
xDebug problem on WSL2 inside Docker

### ISSUE THREAD

**Issue by ulziibat-n** [lando/lando#3087]
Hello guys!

I installed Lando on WSL2 inside Docker setup. 
Trying to configure xDebug by this guide https://docs.lando.dev/guides/lando-with-vscode.html#getting-started I can't get success. 

Has anyone successfully run xDebug on a WSL2 inside Docker? Please help if you have any solution for it 🙏🙏🙏

**Comment by lrsen** [comment]
Have you looked into this section to figure out your issue? https://docs.lando.dev/guides/lando-with-vscode.html#known-issues

**Comment by tudatn** [comment]
You will need to override the LANDO_HOST_IP for your .lando.yml. This [article ](https://www.justwrite.link/posts/setup-xdebug-3-for-lando-in-wsl2) may help.

**Comment by deshiloh** [comment]
Hi, 
I noticed that xdebug seems to be not installed. here my lando.yml config : 

```
name: my-symfony
recipe: symfony
config:
  webroot: public
  via: 'nginx'
  php: '7.4'
  database: 'mariadb'
  xdebug: true
services:
  database:
    creds:
      user: mariadb
      password: mariadb
      database: database
  phpmyadmin:
    type: phpmyadmin
  mailhog:
    type: mailhog
    portforward: true
```
and here the php config interpreter cli : 

![lando](https://i.ibb.co/cDfDxDq/lando.png)

anything about it ?
