### ISSUE TITLE
lando pull fails to get database with Pantheon recipe

### ISSUE THREAD

**Issue by brentratliff** [lando/lando#309]
Please complete the following steps.

Bug Report
==========

What is your lando version and operating system?

v3.0.0-beta10 on Windows 10 Professional

**Tell us about your `.lando.yml`**

```
name: myapp
recipe: pantheon
config:
  framework: drupal
  xdebug: true
  env: dev
  site: usna97-v2
id: 
```

Pantheon.yml

```
api_version: 1
php_version: 7.0
```

**Tell us about the command you were running**

```
lando init pantheon (works)
lando start (hangs)
lando pull
```

**Tell us about the error you got**

```Pulling database...
ERROR 2005 (HY000): Unknown MySQL server host 'database' (0)
0 B 0:00:05
```

**Tell us generally about your bug**

Pulling the files and code worked perfectly but the database failed which causes 'lando start' to hang.
