### ISSUE TITLE
Platform.sh mounts created relative to .lando.yml, not .platform.app.yml

### ISSUE THREAD

**Issue by dwkitchen** [lando/lando#3090]
I have a multi-app setup with .platform.app.yml files in the folders for the app

```yml
.git/
.platform/
drupal/
  .platform.app.yaml
  ...
angular/
  .platform.app.yaml
```
ref: https://docs.platform.sh/configuration/app/multi-app.html#discrete-code-bases

`drupal/.platform.app.yaml` defines a set of mounts:

```yml
mounts:
    '/web/sites/default/files':
        source: local
        source_path: 'files'
    '/tmp':
        source: local
        source_path: 'tmp'
    '/private':
        source: local
        source_path: 'private'
    '/.drush':
        source: local
        source_path: 'drush'
    '/drush-backups':
        source: local
        source_path: 'drush-backups'
    '/.console':
        source: local
        source_path: 'console'
```

When running `lando start` the folders are created relative to the `.lando.yml` file not the `.platform.app.yml` ie:

`/web/sites/default/files`, but should be `/drupal/web/sites/default/files`

I tried adding the following to `.platform.app.yml` as https://docs.platform.sh/configuration/app/multi-app.html#explicit-sourceroot but this didn't resolve the problem.

```
source:
  root: drupal
```

**Tell us about your setup**

v3.1.4 on Mac OS 11.5

**Tell us about your `.lando.yml`**

```yml
name: ***
recipe: platformsh
config:
  id: ***
```
