### ISSUE TITLE
SSH Keys are not forwarded in Platform.sh multi-app

### ISSUE THREAD

**Issue by dwkitchen** [lando/lando#3091]
Standard Lando App

Result of `lando ssh -s appserver -c "cat /etc/ssh/ssh_config"` ref: https://docs.lando.dev/config/ssh.html#ssh-keys

```
Host *
  User "dwkitchen"
  StrictHostKeyChecking no
  UserKnownHostsFile=/dev/null
  LogLevel=FATAL
  IdentityFile "/lando/keys/platformsh.lando.id_rsa"
  IdentityFile "/user/.ssh/id_rsa"
```

### Platform.sh Multi App

Result of `lando ssh -s drupal -c "cat /etc/ssh/ssh_config"` ref: https://docs.lando.dev/config/ssh.html#ssh-keys

```
Host *
  User "dwkitchen"
  StrictHostKeyChecking no
  UserKnownHostsFile=/dev/null
  LogLevel=FATAL
```

**Tell us about your setup**

v3.1.4 on Mac OS 11.5

**Tell us about your .lando.yml**

```
name: ***
recipe: platformsh
config:
  id: ***
```

**Comment by dwkitchen** [comment]
```yml
name: ***
recipe: platformsh
config:
  id: ***
keys:
  - id_rsa
```
Key added to both apps but "Cannot read property 'split' of undefined" as in #2817

```yml
name: ***
recipe: platformsh
config:
  id: ***
  overrides:
    app1:
      keys:
        - id_rsa
    app2:
      keys:
        - id_rsa
```
Key added to app1 but not app2

```yml
name: ***
recipe: platformsh
config:
  id: ***
  overrides:
    app2:
      keys:
        - id_rsa
```
Key added to app1 and app2
