### ISSUE TITLE
Platform.sh wildcard routes are not compatible with Lando

### ISSUE THREAD

**Issue by dwkitchen** [lando/lando#3092]
routes.yaml:

```yml
"https://www.{default}/":
    type: upstream
    upstream: "app2:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://*.{default}/":
  type: upstream
  upstream: "app1:http"
  cache:
    enabled: true
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
```

As app1 is in order before app2 it handles all the routes even though one is defined for www. first.
