### ISSUE TITLE
Pantheon recipe xdebug 3 issue

### ISSUE THREAD

**Issue by miiimooo** [lando/lando#3093]
I'm not sure when exactly this started happening but with this .lando.yml
```
name: d8hrw
recipe: pantheon
config:
  framework: drupal8
  site: XXX
  id: XXX
  index: false
  cache: false
services:
  database:
    type: mariadb:10.4
    config:
      database: config/my_custom.cnf
  appserver:
    webroot: web
    xdebug: true
```

Just testing xdebug 3 with this:
web/i.php
``` 
<?php
$i = 0;
while($i < 5) {
  sleep(1);
  $i++;
}
phpinfo();
```
In my browser I go to /i.php?XDEBUG_SESSION_START

I have dbgpClient from the xdebug site listening:
```
Connect from 172.25.0.4:42480
DBGp/1.0: Xdebug 3.0.4 — For PHP 7.3.27
Debugging file:///srv/includes/prepend.php (ID: 182/)
(cmd) 
1 | 
1 | Error(4): unimplemented command

(cmd) 
 |  > stopping/ok

(cmd) 
2 | 
2 | Error(4): unimplemented command

(cmd) 
2021-08-06 09:48:16.928 [err ] [dbgp-client] Error writing data ' -i 4': write tcp 172.18.0.1:9003->172.25.0.4:42480: write: broken pipe
Error while handling connection: write tcp 172.18.0.1:9003->172.25.0.4:42480: write: broken pipe
Disconnect
```

I have been using lando for a long time so it might be caused by legacy stuff.

I'm seeing this
```
WARN ==> Version 1 Landonet detected, attempting upgrade... 
```

after doing
```
rm -rf ~/.lando/cache ~/.lando/compose ~/.lando/config ~/.lando/proxy ~/.lando/scripts
```

I noticed this in the output from phpinfo():
```
auto_prepend_file	/srv/includes/prepend.php	/srv/includes/prepend.php
```

```
www-data@c5c68c506fac:/app$ fgrep -R auto_prepend /usr/local/etc/
/usr/local/etc/php/conf.d/zzz-lando-my-custom.ini:auto_prepend_file = /srv/includes/prepend.php
/usr/local/etc/php/php.ini-production:auto_prepend_file =
/usr/local/etc/php/php.ini-development:auto_prepend_file =
```

Looks to me like the wiring for pantheon is somewhere broken..
