### ISSUE TITLE
Acquia Recipe Performance Issues

### ISSUE THREAD

**Issue by mikemadison13** [lando/lando#3095]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

* Mac OS Catalina, 2.3 GHz 8-Core Intel Core i9 16gb Memory
* Lando version 3.1.4
* Docker Desktop version 3.3.3

**Tell us about your `.lando.yml`**

See https://github.com/Drupal4Gov/Drupal-GovCon-2017/blob/develop/.lando.yml

**Tell us about the command you were running**

This project has been using the drupal9 recipe for quite some time and we recently swapped to the Acquia recipe to help test. While things "work" what I'm noticing is that after running the VM / running commands in the VM (like automated tests, code linting, etc.) the VM just starts to crawl and becomes unresponsive. Pages won't load, commands seemingly silently fail (they just hang forever). If I destroy the VM and swap back to the drupal9 recipe I don't experience this. Nothing else changes other than the recipe (and the settings for the database, of course). 

I've tried a fair bit of troubleshooting when this happens.... restart Lando, restart Docker, restart the computer, destroy and rebuild the vm, etc. The behavior is consistent with the Acquia recipe (and consistently not a problem with the drupal9 recipe). 

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

1. Clone the govcon repository
2. composer install
3. lando start
4. install all the things (lando blt setup)
5. run / log into the site and browse around AND/OR run a command like lando blt validate. i typically start to see the issue within a few clicks in the UI or a minute or two into the validate run.

This bug is preventing me from using the acquia recipe.

**Comment by poindexterous** [comment]
I'm having a similar experience to @mikemadison13. We're in the middle of upgrading from d8 to d9 and decided to try out the Acquia recipe (since we have to revise our .lando.yml either way) but it's incredibly slow right from the start. Page load time is several minutes, cim sync and other drush commands are equally slow, and there seem to be some other oddities where "lando pull" doesn't seem to behave as expected when specifying an environment database even when using the --on-demand flagl it seems to be copying an old DB backup instead of copying the current active DB for the specified environment. I was previously testing the d9 recipe and it seemed to have much better performance. I wonder if it's the settings I have in the landofile? I have memcache turned off but I didn't think it would make a huge difference. This is still an experiment in progress for us. 
```

name: {mysite}
recipe: acquia
config:
  acli_version: latest
  ah_application_uuid: {mysite uuid}
  ah_site_group: {mysite}
  php: '7.4'
  xdebug: true
  # Disable local mailhog by default.
  inbox: false
  # Disable local memcache by default.
  cache: false
  composer_version: '1.8.6'

services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database

proxy:
  phpmyadmin:
    - phpmyadmin.lndo.site
```
