### ISSUE TITLE
Syncing local database with a downloaded database file

### ISSUE THREAD

**Issue by jfcartier** [lando/lando#3096]
**Goal** : I want to download a database file from a remote server with scp and sync my local database, all that in one lando command.

**Working solution** : 

```
name: website
recipe: drupal9
config:
  webroot: .
  drush: true
tooling:
  update-db:
    service: appserver
    user: root
    description: Import a fresh database from remote host
    cmd:
      - scp user@www.website.ca:/var/backups/database.sql.gz .
      - drush sql:drop -y
      - zcat database.sql.gz | drush sql:cli
      - rm database.sql.gz
```

**Problem** : As you can see, I use drush commands to update my database, but it will work for Drupal sites only. I would have prefered using a command such as : 

```
    cmd:
      - ...
      - /helpers/sql-import.sh database.sql.gz
      - ...
```

but there was a problem with the chosen database/server. Here's the difference : 

```
#when you use sql-import in a cmd command
Preparing to import /app/database.sql.gz into database 'database' on service 'appserver' as user root...

#when you use lando db-import
Preparing to import /app/database.sql.gz into database 'drupal9' on service 'database' as user root...
```

We can see that the wrong database and the wrong service is used. So yeah here's my question. 

**Question** : Is there a way to use lando's `sql-import` command as a tooling cmd ?
