### ISSUE TITLE
Solr core not installed

### ISSUE THREAD

**Issue by st0rmblessed** [lando/lando#3101]
**Tell us about your setup**

What is your lando version and operating system? 

Lando: v3.1.4
Windows 10 using wsl2

**Tell us about your `.lando.yml`**

```yml
name: drupal9
recipe: drupal9
config:
  webroot: .
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  database:
    type: mysql:5.7
  solr:
    type: solr:8
    portforward: true
    core: lando
    config:
      dir: solr-conf/8.x
tooling:
  drupalcs:
    service: appserver
    cmd: "/app/vendor/bin/phpcs --standard=Drupal,DrupalPractice"
    description: Run phpcs Drupal Coding Standards against a given file or directory.
  drupalcbf:
    service: appserver
    cmd: "/app/vendor/bin/phpcbf --standard=Drupal,DrupalPractice"
    description: Automatically fix Drupal coding standards suggestions.
  drupal-check:
    service: appserver
    cmd: /app/vendor/bin/drupal-check -ad
    description: Check Drupal code for deprecations and discover bugs via static analysis
  test:
    service: appserver
    cmd: "php /app/vendor/bin/phpunit -c /app/phpunit.xml"
    description: Run PHPUnit tests on a specific file or Drupal module.
```

**Tell us about the error you got**

I added the solr service to my lando file and when accessing the solr url i got an error saying

lando: org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Could not load conf for core lando: Error loading solr config from /var/solr/data/lando/conf/solrconfig.xml

Aditionally from the drupal side, it seems it can access the solr server but not his core. When accessing the solr url it shows that "No cores available" so it seems that lando didn't properly install the solr core. 

Any ideas? Am I doing anything wrong? I found some issues that seem similar but they were a bit old.

Thanks in advance
