### ISSUE TITLE
var_dump is not styling as expected with mode "develop"

### ISSUE THREAD

**Issue by stloc** [lando/lando#3105]
var_dump is not styling as expected with mode "develop"

.lando.yml :
```
name: data-ecriture
recipe: symfony
config:
  webroot: public
  php: 7.4
  via: apache:2.4
  xdebug: 'develop,debug'
```

lando version : v3.1.4

var_dump test 
![image](https://user-images.githubusercontent.com/4832070/130206775-8014d7fd-6cd8-42db-8002-775afef70168.png)

phpinfo xdebug v3 : 
![image](https://user-images.githubusercontent.com/4832070/130206870-f55fd58f-e9c3-400f-8158-29d286418192.png)
