### ISSUE TITLE
How to add a healthcheck to a compose service

### ISSUE THREAD

**Issue by pauarge** [lando/lando#3117]
I am trying to set up a custom MariaDB image in the following way (notice that I want to do so to use the official Maria image instead of Bitnami's):

```
database:
    type: compose
    services:
      image: mariadb:10.3
      command: docker-entrypoint.sh mysqld
      environment:
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
        MARIADB_DATABASE: 'database'
        MYSQL_DATABASE: 'database'
        MARIADB_PASSWORD: 'mariadb'
        MARIADB_USER: 'mariadb'
        LANDO_NEEDS_EXEC: 'DOEEET'
```

The image works well and I can use the database correctly. However, I have some set-up scripts that fail if the database is not properly initialized. The solution I have right now is to use bash `sleep`. 

I see that the bundled service has a [defined healthcheck](https://github.com/lando/cli/blob/fe36cbaed7a47513e1387f9bcd49003bf3c93245/plugins/lando-services/services/mariadb/builder.js#L26) and that Lando [waits for that healthcheck if exists](https://github.com/lando/cli/blob/fe36cbaed7a47513e1387f9bcd49003bf3c93245/plugins/lando-core/app.js#L167). 

Ideally I would like to define the healthcheck command in my `.lando.yml` file, so it could get picked up as the bundled service does. Something like:

```
database:
    type: compose
    healthcheck: 'mysql -uroot --silent --execute "SHOW DATABASES;"'
    services:
      image: mariadb:10.3
      command: docker-entrypoint.sh mysqld
      environment:
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
        MARIADB_DATABASE: 'database'
        MYSQL_DATABASE: 'database'
        MARIADB_PASSWORD: 'mariadb'
        MARIADB_USER: 'mariadb'
        LANDO_NEEDS_EXEC: 'DOEEET'
```

Is that possible?
