### ISSUE TITLE
the ATOM of lando share should be the URL, not the service

### ISSUE THREAD

**Issue by nalipaz** [lando/lando#312]
I work on a project which is a Drupal multisite and I find it useful to share a url for each site in the multisite install, however I can't currently do such a thing. Would it be possible to allow sharing more than one url, similar to how we add extra urls?
```
proxy:
  appserver:
    - extrasite.thing
```
but for the share configuration somehow.

**Comment by pirog** [comment]
@nalipaz by share you mean via `lando share`?

**Comment by nalipaz** [comment]
@pirog yes, exactly. I would like to be able to expose more than one url to the public.

**Comment by pirog** [comment]
So i don't *think* there is a way to do this currently since we are operating on the service level and not the url level. This model definitely falls flat for things like multisite where you have one appserver service that potentially has multiple sites contained within it, accessible by different urls. 

I think we might just want to change the `-s` service option in `lando share` to `--url` and have it able to handle multiple values.

Feel free to make this into a feature request!

**Comment by nalipaz** [comment]
@pirog yeah, I think lando is missing this as a much needed feature. I mean there are other use-cases aside from multi-site even. Say mobile subdomain, translation subdomains, and etc. It seems very useful to be able to expose more than one url via the share option. My lando file looks something like:

```
recipe: drupal7
name: projectname
compose:
  - lando/compose.yml
config:
  webroot: docroot
  php: 5.6
  database: mysql:5.7
  conf:
    php: lando/php/php.ini
proxy:
  appserver:
    - site1.lndo.site
    - site2.lndo.site
    - site3.lndo.site
    - site4.lndo.site
    - site5.lndo.site
    - site6.lndo.site
    - site7.lndo.site
  edge:
    - edge.acquia.lndo.site
services:
  cache:
    type: memcached:1.4
  edge:
    type: varnish:4.1
    backends:
      - appserver
    ssl: true
  site1_com_db:
    type: mysql:5.7
    config:
      confd: lando/mysql/conf.d
  site2_db:
    type: mysql:5.7
    config:
      confd: lando/mysql/conf.d
  site3_com_db:
    type: mysql:5.7
    config:
      confd: lando/mysql/conf.d
  site4_com_db:
    type: mysql
    config:
      confd: lando/mysql/conf.d
  site5_com_db:
    type: mysql:5.7
    config:
      confd: lando/mysql/conf.d
  site6_com_db:
    type: mysql:5.7
    config:
      confd: lando/mysql/conf.d
  site7_com_db:
    type: mysql:5.7
    config:
      confd: lando/mysql/conf.d
  appserver:
    build:
      - |
         cp -rf /app/lando/drush/.drush /var/www/
         cd /tmp
         cp /app/acquiacloud.tar.gz ./
         tar -zxf acquiacloud.tar.gz
         mv .acquia /var/www/
         mv .drush/cloudapi.acquia.com.pem /var/www/.drush/
         printf "$(cat /app/lando/drush/projectname-custom-aliases.txt)" >> .drush/projectname.aliases.drushrc.php
         mv .drush/projectname.aliases.drushrc.php /var/www/.drush/site-aliases/
      - /app/lando/tooling/sql-sync-all.sh prod
    overrides:
      services:
        environment:
          AH_SITE_ENVIRONMENT: lando
          AH_NON_PRODUCTION: 1
```

And I am suggesting that somewhere in there we be able to set something like:
```
share:
  - site1.localtunnel.me
  - site2.localtunnel.me
  - site3.localtunnel.me
  - site4.localtunnel.me
  - site5.localtunnel.me
  - site6.localtunnel.me
  - site7.localtunnel.me
```

BTW, this most certainly is and has been a feature request since my initial post, sorry for any confusion on that part.
