### ISSUE TITLE
Event variations depending on host

### ISSUE THREAD

**Issue by edurenye** [lando/lando#3126]
**Please explain your request and its importance in the form of a user story.**

As a lando user  I have two database services and I want to run different scripts depending onto which database host I'm importing to.

**Please provide some detail on how lando can help solve this problem**

We could extend the way that we have now appending the host/service name to the event like follows:
`post-db-import-database`
`post-db-import-drupald7db`

Or we could have it as a key inside the event as follows:
```
events:
  post-db-import:
    - appserver:
        host: database
        cmd: echo "Importing configuration" && drush cim -y
    - appserver:
        host: drupald7db
        cmd: echo "D7 db imported"
  post-other-comand:
    service: appserver
    host: database
    cmd: echo "doing something"
```

**Is your feature request related to a problem? Please describe.**
I can't use post-db-import events because the import of the secondary database breaks the site.
