### ISSUE TITLE
Databases keep stopping on Mac with M1 and Pantheon recipes

### ISSUE THREAD

**Issue by andileco** [lando/lando#3137]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

Machine: MacBook Pro, BiG Sur v 11.5.2, Apple M1, 16GB memory
Docker: 3.6.0 (packaged with Lando)
Lando: 3.3.2

**Tell us about your `.lando.yml`**
```
name: my-site
recipe: pantheon
config:
  framework: drupal8
  site: my-site
  id: [the ID]
```
*pantheon.yml"

```
api_version: 1
web_docroot: true
php_version: 7.4
database:
  version: 10.4
enforce_https: full+subdomains
workflows:
  deploy_product:
    after:
      -
        type: webphp
        description: 'Run composer prepare-for-pantheon'
        script: private/scripts/deploy_product/prepare-for-pantheon.php
      -
        type: webphp
        description: 'Run composer install & drupal-scaffold'
        script: private/scripts/deploy_product/composer-install.php
  sync_code:
    after:
      - type: webphp
        description: Push changes back to GitHub if needed
        script: private/scripts/quicksilver/quicksilver-pushback/push-back-to-github.php
```

**Tell us about the command you were running**

After I run `lando rebuild -y` or `lando start`, the database basically immediately stops (I see this in the Docker dashboard), sometimes before even accessing the site, sometimes it will let me touch one or two pages before the container stops. I also stops in the middle of a `lando pull` - in this case, it generates an error like, "ERROR 2013 (HY000) at line 4753: Lost connection to MySQL server during query". 

**Tell us about the error you got**

Other than the error during the database pull, there's no error, the database just stops. If I click into the database container, I see this:

```
Connection ID (thread ID): 8

Status: NOT_KILLED


Optimizer switch: index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materialization=on,in_to_exists=on,semijoin=on,partial_match_rowid_merge=on,partial_match_table_scan=on,subquery_cache=on,mrr=off,mrr_cost_based=off,mrr_sort_keys=off,outer_join_with_cache=on,semijoin_with_cache=on,join_cache_incremental=on,join_cache_hashed=on,join_cache_bka=on,optimize_join_buffer_size=on,table_elimination=on,extended_keys=on,exists_to_in=on,orderby_uses_equalities=on,condition_pushdown_for_derived=on,split_materialized=on,condition_pushdown_for_subquery=on,rowid_filter=on,condition_pushdown_from_having=on


The manual page at https://mariadb.com/kb/en/how-to-produce-a-full-stack-trace-for-mysqld/ contains

information that should help you find out what is causing the crash.

Writing a core file...

Working directory at /bitnami/mariadb/data

Resource Limits:

Limit                     Soft Limit           Hard Limit           Units     

Max cpu time              unlimited            unlimited            seconds   

Max file size             unlimited            unlimited            bytes     

Max data size             unlimited            unlimited            bytes     

Max stack size            8388608              unlimited            bytes     

Max core file size        0                    unlimited            bytes     

Max resident set          unlimited            unlimited            bytes     

Max processes             unlimited            unlimited            processes 

Max open files            1048576              1048576              files     

Max locked memory         65536                65536                bytes     

Max address space         unlimited            unlimited            bytes     

Max file locks            unlimited            unlimited            locks     

Max pending signals       10433                10433                signals   

Max msgqueue size         819200               819200               bytes     

Max nice priority         0                    0                    

Max realtime priority     0                    0                    

Max realtime timeout      unlimited            unlimited            us        

Core pattern: core


qemu: uncaught target signal 11 (Segmentation fault) - core dumped

/launch.sh: line 11:    39 Segmentation fault      /opt/bitnami/scripts/mariadb/entrypoint.sh /opt/bitnami/scripts/mariadb/run.sh
```

**Tell us generally about your bug**

This basically happens on all my Pantheon sites. SOMETIMES I can get the database to be stable for a few minutes by basically running a lot of Docker restarts, `lando destroy`, `lando rebuild -y`, `lando start`, but it doesn't seem like there's a perfect sequence of these commands that works every time.

**Tell us more**

Does this bug prevent you from using lando? YES
