### ISSUE TITLE
platformsh recipe, no routes available from inside of lando if `{all}` is set as upstream in routes.yaml

### ISSUE THREAD

**Issue by gilzow** [lando/lando#3147]
**Tell us about your setup**  
Lando v3.3.0 on macOS 11.6 

**Tell us about your `.lando.yml`**
```yml
name: multisite-multidomain
recipe: platformsh
config:
  id: 6ienq4p4y6ita

env_file:
  - .env

proxy:
  app:
    - wpmultidomain.plat.farm.lndo.site
    - wpmultidomain2.friday.dev.lndo.site
```

Contents of `./.platform/routes.yaml`:
```yml
"https://{all}/":
    type: upstream
    upstream: "app:http"
    <snip>

"https://www.{all}/":
    type: redirect
    to: "https://{default}/"
```

**Tell us about the command you were running**
Working on multisite support and attempted to retrieve the list of routes from platform. Inside of lando, the env var `PLATFORM_ROUTES` is set to an empty json:
```bash
web@3053da3ae445:/app$ printenv | grep PLATFORM_ROUTES
PLATFORM_ROUTES=e30=
```
Attempting to use the cli inside of lando to retrieve the routes returns "No routes":
```bash
web@3053da3ae445:/app$ platform routes
No routes found
```
and
```bash
web@3053da3ae445:/app$ platform routes -e master
No routes found
```
Though _outside_ of lando, I am able to retrieve the correct routes
```bash
❯ platform routes
Enter a number to choose an environment:
Default: master
  [0] Master (master) (type: production)
  [1] ms-improve (type: development)
 > 0

Routes on the project multisite-multidomain (6ienq4p4y6ita), environment Master (master) (type: production):
+--------------------+----------+----------------------------------------+
| Route              | Type     | To                                     |
+--------------------+----------+----------------------------------------+
| https://{all}/     | upstream | app:http                               |
| https://{all}/     | upstream | app:http                               |
| https://www.{all}/ | redirect | https://wpmultidomain.plat.farm/       |
| https://www.{all}/ | redirect | https://wpmultidomain2.friday.dev/     |
| http://{all}/      | redirect | https://wpmultidomain.plat.farm/       |
| http://{all}/      | redirect | https://wpmultidomain2.friday.dev/     |
| http://www.{all}/  | redirect | https://www.wpmultidomain.plat.farm/   |
| http://www.{all}/  | redirect | https://www.wpmultidomain2.friday.dev/ |
+--------------------+----------+----------------------------------------+
```

Performing `platform cc` inside of lando and then trying again had no affect.

I will assume this issue is related to #3145 and/or #3146 ?
