### ISSUE TITLE
Starting Something as Root Every Start up

### ISSUE THREAD

**Issue by ajmeireles** [lando/lando#3150]
Hi!

I'm new to Lando.dev and would like to ask a question about the events. I have a system with Laravel and I need that every time the appserver is started, it executes a command (as root) to trigger the `supervisor` which will automatically bind the Laravel Websocket and Laravel Queues. This is my lando.yml configuration:

```
name: conquistabomnegocio
recipe: laravel
config:
  webroot: ./public/
  cache: redis
services:
  appserver:
    type: php
    scanner: false
    config:
      php: ./.lando/php.ini
    overrides:
      ports:
      - 6001:6001
    build_as_root:
      - "apt-get update -y && apt-get install cron -y && apt-get install supervisor -y"
      - cp -f /app/.lando/docker-php-entrypoint.sh /usr/local/bin/docker-php-entrypoint
      - cp -f /app/.lando/laravel-worker-queue.conf /etc/supervisor/conf.d/laravel-worker-queue.conf
      - cp -f /app/.lando/laravel-worker-socket.conf /etc/supervisor/conf.d/laravel-worker-socket.conf
    run_as_root:
      - service cron start
      - service supervisor start
    run:
      - "cd $LANDO_MOUNT && composer install && php /app/artisan migrate --step && php /app/artisan optimize:clear"
      - crontab /app/.lando/cron.txt
  database:
    type: mariadb
    creds:
      user: goodcoin
      password: 1234
      database: goodcoin
  phpmyadmin:
    type: phpmyadmin
    scanner: false
    hosts:
      - database
  node:
    type: node:14
    globals:
      webpack: "latest"
      npm: "latest"
tooling:
  npm:
    service: node
  redis-cli:
    service: cache
  supervisor:
    service: appserver
    description: "[CUSTOM] Start the supervisor process workers"
    cmd: service supervisor start
    user: root
proxy:
  phpmyadmin:
    - goodcoin.phpmyadmin.lndo.site
```

**Currently, after the appserver turns on I do this manually using the command I created: `lando supervisor` every time after `appserver` is started**, but this work is tiring. Is there any way to automate? Let's say... Make the `post-start` event consume a `tooling` (custom: supervisor) so that `tooling` executes the command as `root`? Because when I try to start the supervisor as my user, I can't do it due the permission.
