### ISSUE TITLE
blackfire is not a supported service type

### ISSUE THREAD

**Issue by rpayanm** [lando/lando#3158]
I followed these instructions:
https://blackfire.io/docs/integrations/paas/lando

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.3.2 on Pop!_OS 21.04

**Tell us about your `.lando.yml`**

```yml
name: test
recipe: drupal9
services:
  appserver:
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=lando"
  database:
    portforward: 3306
  blackfire:
    type: blackfire
    server_id: my_id
    server_token: my_server_token
    client_id: my_client_id
    client_token: my_client_token
tooling:
  drushd:
    description: Debugs drush command
    service: appserver
    cmd: php -dxdebug.mode=debug -dxdebug.remote_enable -dxdebug.client_port=9003 -dxdebug.start_with_request=yes /app/vendor/bin/drush
  blackfire:
    # Replace "appserver" by your app container name if needed
    service: appserver
  blackfire-player:
    service: appserver

config:
  webroot: web
  via: nginx
  database: mariadb
  xdebug: true
proxy:
  appserver_nginx:
    - "*.local"
```

**Tell us about the command you were running**

```bash
lando rebuild -y
```

**Tell us about the error you got**

```bash
WARN ==> blackfire is not a supported service type. 
ERROR ==> Cannot read property 'builder' of undefined
```
