### ISSUE TITLE
Pantheon Recipe - OpenSSL Root Certificate for Let's Encrypt Not Trusted (OpenSSL 1.0.2 is Out of Date)

### ISSUE THREAD

**Issue by GuyPaddock** [lando/lando#3162]
## Tell us about your setup
v3.4.0 on Ubuntu 20.04.2 LTS (WSL2 on Windows 10.0.19043 Build 19043)

### `.lando.yml`
```yml
name: my_app
recipe: pantheon
config:
  webroot: web
  drush: 9
  php: '7.3'
  framework: drupal8
  site: REDACTED
  id: REDACTED
services:
  database:
    portforward: 3307
  appserver:
    type: php:7.3
    webroot: web
    xdebug: true
```

### `pantheon.yml`
```yml
api_version: 1
web_docroot: true
php_version: 7.3
enforce_https: transitional
```

**Tell us about the command you were running**
```bash
# In the example command below, `myapp` is the name of our app
docker exec -it myapp_appserver_1 curl https://mam.inveniem.com/ -vvv
```

This mimics the behavior that PHP curl calls inside the container also experience.

**Tell us about the error you got**
With the command above:
```
*   Trying 52.183.29.73...
* TCP_NODELAY set
* Connected to mam.inveniem.com (52.183.29.73) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: certificate has expired
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

While inside Drupal, making cURL calls with PHP:
```
 cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

**Tell us generally about your bug**
The problem is that we can't connect to any of our line-of-business services that are secured by Let's Encrypt from PHP in Lando now that the old [Let's Encrypt Root Certificate Has Expired](https://scotthelme.co.uk/lets-encrypt-old-root-expiration/). All of our certificates on the server side are up-to-date, but cURL calls from PHP and CLI inside Lando-managed Pantheon containers fail to recognize that `ISRG Root X1` is a root certificate, so it's falling over to the old certificate chain that uses the expired `DST Root CA X3` root certificate instead.

![Our certificate chain looks all right as long as the correct root certificate is used](https://user-images.githubusercontent.com/2631799/135547387-f41f6798-a1da-4f00-a28d-e38b67b0d069.png)

Consequently, the trusted root certificates inside the container lead the command above to fail.

This issue does not occur on Pantheon itself (especially after last night's updates rolled out to update certificates), so Lando is not accurately replicating the behavior locally that we have in production environments.

**Tell us more**
It appears that manually entering the app server container and running `apt update && apt install` does update the root certificates, allowing the CLI cURL command to validate the certificates. However, that has no effect on PHP FPM processes that are already running and does not persist through a restart of containers (as expected).

This prevents us from using Lando without modifying our application to disable SSL verification, which is insecure.

**Comment by GuyPaddock** [comment]
It looks like a way to workaround this issue is to override the container for the app server with a custom Docker image, as follows:

### `.lando.yml`
```yml
name: my_app
# ... lines omitted ...
services:
  # ... lines omitted ...
  appserver:
    # ... lines omitted ...
    overrides:
      build: ./docker/pantheon-appserver-7.3-2
      image: inveniem/pantheon-appserver-with-ssl-updates:7.3-2
# ... lines omitted ...
```

And then the Docker file:
### `docker/pantheon-appserver-7.3-2/Dockerfile`
```Dockerfile
FROM devwithlando/pantheon-appserver:7.3-2

RUN apt update && apt install libssl1.0.2
```

This may mean that the certificates themselves aren't out of date but perhaps there was a bug in the previous version of libSSL 1.0.2. APT reports the new version as `libssl1.0.2/oldoldstable 1.0.2u-1~deb9u6 amd64`, while the old version was `1.0.2u-1~deb9u4`.

**Comment by GuyPaddock** [comment]
I found a security advisory to explain the problem (was fixed in `libssl1.0.2` version `1.0.2u-1~deb9u6`):
https://linuxsecurity.com/advisories/deblts/debian-lts-dla-2761-1-openssl1-0-security-update-18-58-09

**Comment by pirog** [comment]
@GuyPaddock i think the `3.4.0` release should resolve this. You can test the images in that release if you want with:

```
name: my_app
# ... lines omitted ...
services:
  # ... lines omitted ...
  appserver:
    # ... lines omitted ...
    overrides:
      image: devwithlando/pantheon-appserver:7.3-3
# ... lines omitted ...
```
