### ISSUE TITLE
CURL Error: "No route to host", between services.

### ISSUE THREAD

**Issue by ajmeireles** [lando/lando#3181]
Hi! 

I use **Fedora 34 and Lando has always worked well.** However **tonight I noticed that there were some Docker updates (I don't know if that was it, but I noticed the problem after that)** and with that I can no longer communicate two services internally via cURL.

The service I want to communicate is an CDN **(simple PHP API to delivery and receive images)**

### .lando.yml of the Main Service:
```
name: conquistabomnegocio
recipe: laravel
config:
  webroot: ./public/
  cache: redis
services:
  appserver:
    type: php
    scanner: false
    config:
      php: ./.lando/php.ini
    build_as_root:
      - "apt-get update -y && apt-get install cron supervisor sudo -y && adduser www-data sudo && echo \"www-data ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers"
      - cp -f /app/.lando/laravel-worker-queue.conf /etc/supervisor/conf.d/laravel-worker-queue.conf
      - cp -f /app/.lando/laravel-worker-socket.conf /etc/supervisor/conf.d/laravel-worker-socket.conf
    run:
      - "cd $LANDO_MOUNT && composer install && php artisan migrate --step --force"
    overrides:
      ports:
       - '6001:6001'
  database:
    type: mariadb
    creds:
      user: conquistabomnegocio
      password: 1234
      database: conquistabomnegocio
  phpmyadmin:
    type: phpmyadmin
    scanner: false
    hosts:
      - database
  node:
    type: node:14
    globals:
      webpack: "latest"
      npm: "latest"
tooling:
  npm:
    service: node
  redis-cli:
    service: cache
proxy:
  phpmyadmin:
    - conquistabomnegocio.phpmyadmin.lndo.site
events:
  post-start:
    - appserver: "sudo service cron start && crontab /app/.lando/cron.txt && sudo service supervisor start"
```

### CDN .lando.yml:
```
name: cdnconquistabomnegocio
services:
  appserver:
    webroot: ./public/
    type: php
    scanner: false
    run:
      - "cd $LANDO_MOUNT && composer install && chmod -R 777 /app/writable/"
  cache:
    type: redis
proxy:
  appserver:
    - cdn.conquistabomnegocio.lndo.site
tooling:
  spark:
    service: appserver
    cmd: php /app/spark
```

### Steps to reproduce the error
When I try to run ```lando ssh -c "curl -I cdn.conquistabombusiness.lndo.site"``` from the main service to the CDN API service I get the error: ```curl: (7) Failed to connect to cdn.conquistabomnegocio.lndo.site port 80: No route to host```, but a while ago it worked perfectly.

**I can say that the networking documentation example** (https://docs.lando.dev/config/networking.html#automatic-hostnames) **is not working on my case.**

### Entire Docker Version

```
Client: Docker Engine - Community
 Version: 20.10.10
 API version: 1.41
 Go version: go1.16.9
 Git commit: b485636
 Built: Mon Oct 25 07:43:57 2021
 OS/Arch: linux/amd64
 Context: default
 experimental: true

Server: Docker Engine - Community
 Engine:
  Version: 20.10.10
  API version: 1.41 (minimum version 1.12)
  Go version: go1.16.9
  Git commit: e2f740d
  Built: Mon Oct 25 07:41:40 2021
  OS/Arch: linux/amd64
  experimental: false
 container:
  Version: 1.4.11
  GitCommit: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version: 1.0.2
  GitCommit: v1.0.2-0-g52b36a2
 docker-init:
  Version: 0.19.0
  GitCommit: de40ad0
```
