### ISSUE TITLE
Support lando tooling which executes `lando` / host commands

### ISSUE THREAD

**Issue by xurizaemon** [lando/lando#3190]
A feature request I've seen come up twice, so opening a ticket.

[Use case 1](https://devwithlando.slack.com/archives/C2XBSHX8R/p1631674324203400) - multi-step command including `lando` commands

> Here's a set of commands I want to run in a single "lando reset-to-branch" (name undefined as yet):

```
    lando destroy -y
    lando start
    lando some-custom (a custom command that imports config and does things)
    lando drush uli
```

> As I understand it,  I could chain the last two since they both occur in the appserver container (omit `lando` prefix from commands), but the first two can't be combined into a Lando command since they actually require calling `lando`).

[Use case 2](https://github.com/lando/lando/issues/2506#issuecomment-954112243) - tooling which extracts data from `lando info`

> If lando tooling allowed chaining custom commands (even lando commands), then this would be easy to implement like so:

```
tooling:
  vitals:
    description: Show a list of services URLs
    cmd:
      - lando: info --format json | jq -r '.. | objects | with_entries(select(.key | contains("urls"))) | select(. != {}) | .urls | select(. != []) | .[]' | sed 's/\/*$//g'
```

What would it take to deliver these? Are the two use cases similar enough that a common solution in Lando's tooling would do it?
