### ISSUE TITLE
using curl against Facebook properties in Laravel recipe on M1 causes segmentation fault

### ISSUE THREAD

**Issue by ceejayoz** [lando/lando#3200]
Not sure what to provide debug-wise on this; I'm on Apple Silicon, OSX 11.6.1, Docker Desktop 4.1.1.

Any use of curl against the following domains results in a segmentation fault, whether it's in `lando ssh` on the CLI, or in Laravel doing `Http::get()` (which uses curl under the hood).

* facebook.com
* graph.facebook.com
* instagram.com

I haven't found any non-Facebook domains that cause this; have checked lando.dev, twitter.com, google.com, and a random smattering of others.

`.lando.yml` contents:

```
name: mbx
recipe: laravel
config:
  webroot: public
  php: '8.0'
  composer_version: 2
  via: nginx
  database: postgres:13
  cache: redis:6
```

**Comment by reynoldsalec** [comment]
I'm able to replicate this on the Laravel recipe (and a D7 recipe) on my M1. Confirmed that, on the same D7 app, the command works on my Intel Mac, so this does seem to be M1-specific.

1. `lando init --recipe=laravel --source=remote --remote=https://github.com/laravel/laravel.git --web-root=public`
1. `lando start`
2. `lando ssh`
3. `curl https://www.facebook.com`

This returns the text `Segmentation fault` on the command line. There aren't any entries in the`lando logs`.

Interestingly, `curl http://www.facebook.com` returns nothing. cURLing different https domains returns the full page text (ex: `curl https://www.google.com`) as expected. cURL commands to facebook work fine from my host machine.

When running cURL with `-v`, I get the following output:

```
*   Trying 157.240.22.35...
* TCP_NODELAY set
* Expire in 149945 ms for 3 (transfer 0xaaaad428ef30)
* Expire in 200 ms for 4 (transfer 0xaaaad428ef30)
* Connected to www.facebook.com (157.240.22.35) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
Segmentation fault
```

I'm guessing there's an issue specific to Facebook's cert not playing nice with Lando's setup.

**Comment by resyncdigital** [comment]
It's not a permanent fix but I found changing the image version fixes it for now.
Try this (then `lando rebuild`)

```
name: mbx
recipe: laravel
config:
  webroot: public
  php: '8.0'
  composer_version: 2
  via: nginx
  database: postgres:13
  cache: redis:6

services:
  appserver:
    overrides:
      image: devwithlando/php:8.0-fpm-2
```
