### ISSUE TITLE
Pantheon recipe: 500 error and database "Got an error reading communication packets"

### ISSUE THREAD

**Issue by AleMadLei** [lando/lando#3207]
All the pages as anonymous user work without problems.

As a admin, I start getting error on some pages (particularly when adding new paragraph fields or rendering a remote youtube media)

I also get this on every connection.
`Aborted connection 34 to db: 'pantheon' user: 'pantheon' host: '172.27.0.2' (Got an error reading communication packets)`

This is my lando file:

```
name: mydemo
recipe: pantheon
config:
  framework: drupal9
services:
  appserver:
    run:
      - composer install
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "http://mydemo.lndo.site"
  node:
    type: node:14
    ssl: true
proxy:
  node:
    - watch.mydemo.lndo.site:3000
    - watch-ui.mydemo.lndo.site:3001
tooling:
  npm:
    service: node
    cmd: npm --prefix=/app/web/themes/custom/mydemo
  "drupal:reinstall":
    service: appserver
    cmd:
      - composer install
      - rm -rf /app/web/sites/default/files/*
      - drush search-api:clear || true
      - drush si -y --existing-config
      - drush cim -y
      - drush search-api:index
      - drush uli
  "theme:watch":
    service: node
    cmd: cd web/themes/custom/mydemo&& npm install && npm run watch
  "theme:build:prod":
    service: node
    cmd: cd web/themes/custom/mydemo&& npm install && npm run prod
```

The 500 error seems related to edge container.

After running `lando destroy -y`, adding `edge: false`  under `config` after `framework` and running `lando rebuild -y` I no longer get the 500 error buy I keep getting the database warning.
