### ISSUE TITLE
xdebug 3 not working with lando 3.5 on windows 11 & WSL2

### ISSUE THREAD

**Issue by tkezell** [lando/lando#3212]
I've tried every fix that I've found on the internet and still no luck getting xdebug to work with PHPStorm on my setup.  When I load a page in the browser, I get the below error.  Any help you can give would be greatly appreciated.  I'm wondering could it be because I'm on docker 4.1.1 instead of some version of docker 3?

**Error**
```[Step Debug] ERR: Time-out connecting to debugging client, waited: 200 ms. Tried: 172.19.0.1:9003 (from HTTP_X_FORWARDED_FOR HTTP header), 172.23.85.84:9003 (fallback through xdebug.client_host/xdebug.client_port)```

**Configuration**
Lando 3.5.1
xdebug 3
Windows 11
WSL2
Ubuntu 18.04 LTS
PHPStorm 2021.2.3 (on Windows)
Docker Desktop 4.1.1 (on Windows)

**.lando.yml**
```
name: river-gallery
recipe: wordpress
config:
  php: '7.4'
  webroot: .
  xdebug: true
services:
    config:
      php: .lando.php.ini
```

**.lando.php.ini**
```
xdebug.mode = debug
xdebug.idekey = PHPSTORM
xdebug.log = ./xdebug.log
xdebug.start_with_request = yes
xdebug.client_port = 9003
xdebug.client_host = ${LANDO_HOST_IP}
```
