### ISSUE TITLE
"Cannot read property 'run' of undefined" when trying to import database

### ISSUE THREAD

**Issue by khorporative** [lando/lando#3223]
We are experiencing error **Cannot read property 'run' of undefined** when trying to install the database into newly installed Lando. The error is both on Windows and Linux. The database itself is from the production system. We are trying to setup a Drupal website.

![image](https://user-images.githubusercontent.com/18428628/143762964-b3a1ab55-e01c-4e71-bb85-dfe1107525e6.png)

Any hints?

On Linux there is an interesting warning:
■ Using an unsupported version of DOCKER ENGINE
   You have version 18.0.0 but Lando wants something in the 18.09.3 - 20.10.99 range.
   
However, docker -v returns:
Docker version 20.10.11, build dea9396

```
nz    17:12:40 VERBOSE ==> perm sweeping flagged non-root containers ... 0=database
nz    17:12:40 VERBOSE ==> analyzing user ssh keys... using 1 of 1 
nz    17:12:40 VERBOSE ==> setting LANDO_INFO... 
nz    17:12:40 VERBOSE ==> app is ready! 
nz    17:12:40 VERBOSE ==> discovering dynamic portforward info... 
lando 17:12:40 ERROR ==> TypeError: Cannot read property 'run' of undefined
    at /snapshot/cli/lib/bootstrap.js
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47 
lando 17:12:40 VERBOSE ==> reporting error action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
lando 17:12:41 VERBOSE ==> checking docker version compatibility... 
```

**Comment by labboy0276** [comment]
@khorporative did you get this resolved?  Also can you paste your `.lando.yml` file as well.

**Comment by Herbis** [comment]
@labboy0276 sorry for late response.
We did not resolve it, but we worked around the issue by calling drush database import commands. 
I think it was the `lando drush sql-cli < nz-latest.sql`


.lando.yml:
```
services:
  database:
    portforward: 6668
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://nz.lndo.site"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

proxy:
  mailhog:
    - mailhog-nz.lndo.site

events:
  pre-start:
    - appserver: composer install
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cache:rebuild -y && drush @local user:login

env_file:
  - .lando/.env

# Tested with Lando version
version: v3.0.1
```
