### ISSUE TITLE
Lando 3.6.0 -- Xdebug not launched

### ISSUE THREAD

**Issue by sebastienserre** [lando/lando#3245]
Hello,

I've updated lanfo from 3.5.1 to 3.6.0. From this, Xdebug breakpoint are  ignored.
```
name: myproject
recipe: wordpress
config:
  webroot: .
  xdebug: true
  database: mariadb
  config:
    php: ./../../php.ini
services:
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
        LANDO_HOST_IP: "host.docker.internal"
        XDEBUG_CONFIG: "remote_enable=1 remote_host=host.docker.internal"
  pma:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    hogfrom:
    - appserver
tooling:
  composer:
    service: appserver
```

php.ini:
```
[PHP]

; Xdebug
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
; Extra custom Xdebug setting for debug to work in VSCode.
xdebug.mode = debug
xdebug.client_host = ${LANDO_HOST_IP}
xdebug.client_port = 9003
xdebug.start_with_request = trigger
; xdebug.remote_connect_back = 1
xdebug.log = /tmp/xdebug.log
```

I'm on Ubuntu 20.04.3

In PHPStorm, validating debug conf says:
![screenshot-2021-12-11-20-56](https://user-images.githubusercontent.com/3902621/145689965-882e7e9d-2ff3-49ed-985a-fdfcb926b90c.png)

Thank you for your help
