### ISSUE TITLE
Lando 3.6.0 with Pantheon recipe doesn't install imagemagick for php 8 (drupal 9.3.0)

### ISSUE THREAD

**Issue by alphex** [lando/lando#3246]
pantheon.yml file

```
api_version: 1
php_version: 8.0
```

.lando.yml file

```
name: sitename
recipe: pantheon
config:
  php: '8.0'
  framework: drupal9
  database: mariadb:10.4
  site: sitename
  id: xxx-123-zzz-abc-def
  composer_version: 2-latest
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://sitename.lndo.site"
```

I have imagemagick installed for the site via composer.
```
        "drupal/imagemagick": "^3.1",
```

Imagemagick works on my multidev where I'm testing the 9.3 upgrade.
but is now failing on Lando 3.6.0 with PHP 8

`/admin/reports/status` shows

"sh: 1: convert: not found" as an error for IMAGEMAGICK.

Same error on `/admin/config/media/image-toolkit`

Is there a .lando.yml tooling that I can use to install it?

Or, as a feature request, can we make sure that gets added to the pantheon plugin?

Thank you!
