### ISSUE TITLE
Drupal Page Unavailable

### ISSUE THREAD

**Issue by dchaffin** [lando/lando#3257]
I'm sorry, I know this is going to be vague, but that's how stuck I am. I upgraded to v3.6.0 from v3.3.2 Debian on Windows 10 WSL. Now, I can get to my admin pages, but not my themed (public-facing pages). Most of the time, it simply says, "Page Unavailable: The page you requested is temporarily unavailable." I've tried lando rebuild. I've tried changing to a stock theme. I'm really not sure what else to try.

Any ideas? Thanks!

**Comment by melissaevans** [comment]
I'm getting a similar behavior after upgrading to v3.6.0 last night on Mac OSX.

Start lando
Page loads

Log into site and I see 
Page Unavailable
The page you requested is temporarily unavailable.

Lando drush cache:rebuild
The site loads again and I am able to click around

Log in again
Url forwards to user/291 (my id)

Visit user/logout
Site loads again fine

When logged in and seeing the Page Unavailable message, I am able to switch to /admin and then see Drupal's backend at /admin.  If I click on the Content link to go to /admin/content I get the Page Not Available message again.

I'm going to try to roll back my version of Lando for now.

**Comment by melissaevans** [comment]
@dchaffin I joined the devwithlando slack group and found this question there as well.  In this case the solution for me was disabling varnish edge per John B's note in [this thread on slack](https://devwithlando.slack.com/archives/C2XBSHX8R/p1637600034425100).

recipe: pantheon
config:
  # Disable the VARNISH edge
  edge: false

**Comment by dchaffin** [comment]
@melissaevans Thanks, I'm not sure I can do that though? To complicate matters, I'm using [Domain](https://www.drupal.org/project/domain) on my site and unless I'm mistaken, edge is what lets me test all those locally. My .lando.yml file ...

```
name: mysite
recipe: pantheon
config:
  framework: drupal8
  webroot: web
  site: mysite
  id: 4932...
proxy:
  edge:
    - mysite01.lndo.site
    - mysite02.lndo.site
    - mysite03.lndo.site
    ...
services:
  database:
    type: mariadb:10.4    
tooling:
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"
      - "--root=/app/web"
```

I have downgraded Lando to v3.5.1 and am now getting messages like ... 

`Fatal error: Allowed memory size of _n_ bytes exhausted...`

**Comment by labboy0276** [comment]
@dchaffin if you downgraded, you will need to destroy and start over with the app.

I am curious though, why do you have proxy domains on the edge?

**Comment by reynoldsalec** [comment]
@dchaffin and to disable the edge cache on the Pantheon service, you'll want to set the `edge` attribute as mentioned by @melissaevans. Example (note the `edge: false` underneath `config`):

```
name: mysite
recipe: pantheon
config:
  framework: drupal8
  webroot: web
  site: mysite
  id: 4932...
  edge: false
```

Docs: https://docs.lando.dev/config/pantheon.html#configuration
