### ISSUE TITLE
Throwing errors when Pantheon D7 site is using PHP 5.3 [bug fix]

### ISSUE THREAD

**Issue by miller2676** [lando/lando#328]
Which leads me to the following question: Does Lando require apps to be running a minimum PHP version?

I'm new to Lando and was getting the following error when trying to pull existing sites from Pantheon. I get this at the end of 'lando start'

```
     [success]
/bin/sh: 1: terminus: not found
error:  message=/bin/sh: 1: terminus: not found
, code=127
```
We are still running PHP 5.3 on sites in our D7 distro. So I decided to test a few other scenarios -- both D7 with PHP 5.6 and D8 with PHP 7.0 seem to work fine -- again I'm new to Lando, but I didn't get error and was able to navigate to those sites. 

Bug Report
==========
OSX 10.12.6
Lando 3.0.0-beta.13

Does this bug prevent you from using lando?
Yes!

Lando
```yml
name: ep-osu
recipe: pantheon
config:
  framework: drupal
  env: dev
  site: ep-osu
  id: 0c5c2c6d-d3f8-4280-9050-84a019ff0e73
```

Pantheon
```yml
api_version: 1

php_version: 5.3

drush_version: 7

workflows:
  deploy:
    after:
        - type: webphp
          description: Post to Slack after deploy
          script: private/scripts/slack_notification.php
```

Verbose output of lando start is in attached file.
[lando-start.txt](https://github.com/kalabox/lando/files/1282339/lando-start.txt)
