### ISSUE TITLE
lando acli pull:db not working as expected

### ISSUE THREAD

**Issue by msbodetti** [lando/lando#3294]
I tried searching the issues, but couldn't find the same issue I'm having. I've noticed an issue with the recent version of Lando (v3.6.0) that the `lando acli pull:db` does not work like it used to.

Whilst running it, I see this notice:
```
 ! [NOTE] Acquia CLI assumes that the Lando database name for the mtndecoupled database is mtndecoupled
✔ Importing mtndecoupled database download
```
The default database created is setup with:
```
      user: acquia
      password: acquia
      database: acquia
```

I tried adding in my default database details, but it doesn't connect to the database when trying to run the command again. Neither does the Drupal site (can't connect to the database).

Adding the default database details in the `.lando.yml` file:
```
name: mtndecoupled
recipe: acquia
config:
  acli_version: master
  ah_site_group: mtndecoupled
  php: '7.4'
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  database:
    type: mysql
    portforward: true
    creds:
      user: acquia
      password: acquia
      database: mtndecoupled
```

Not sure if I'm doing this correctly for config, any help would be appreciated on that.

The other solution seems to be working `lando pull --code=none --database=dev --files=none` which is great and might be more ideal to use, but just want to find out if this is the recommended way now so I can let my team know.
