### ISSUE TITLE
mongo service not ready 

### ISSUE THREAD

**Issue by vijaymayekar** [lando/lando#3305]
**Tell us about your setup**

Lando v3.6.1 on macos Monterey 12.1 (Apple M1 Pro) with docker for mac v20.10.8

**Tell us about your .lando.yml**
```
name: test
recipe: laravel
config:
  php: '8.0'
  via: apache:2.4
  webroot: app
  database: mysql
  xdebug: true
services:
  myservice:
    type: mongo
    portforward: true
```
**Tell us about the command you were running**

lando start
**Tell us about the error you got**

```
ERROR ==> myservice reported as unhealthy.
Scanning to determine which services are ready... Please standby...
Starting test_myservice_1 ... done
Killing test_myservice_1 ... done
```

**Logs**
```
myservice_1  | mongodb 22:55:56.47 INFO  ==> Initializing MongoDB...
myservice_1  | mongodb 22:55:56.67 INFO  ==> Deploying MongoDB from scratch...
myservice_1  | mongodb 22:55:56.73 DEBUG ==> Starting MongoDB in background...
myservice_1  | about to fork child process, waiting until server is ready for connections.
myservice_1  | forked process: 147
myservice_1  | ERROR: child process failed, exited with error number 51
myservice_1  | To see additional information in this output, start without the "--fork" option.
```

Mongo service is not ready
