### ISSUE TITLE
Lando prompting to trust hirak/prestissimo right before it gets removed

### ISSUE THREAD

**Issue by davereid-pfg** [lando/lando#3307]
```
All settings correct for using Composer
Downloading...

Composer (version 2.2.5) successfully installed to: /usr/local/bin/composer
Use it: php /usr/local/bin/composer

Changed current directory to /var/www/.composer
hirak/prestissimo contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "hirak/prestissimo" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] n
./composer.json has been updated
Running composer update hirak/prestissimo
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 0 updates, 1 removal
  - Removing hirak/prestissimo (0.3.10)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 0 updates, 1 removal
  - Removing hirak/prestissimo (0.3.10)
Generating autoload files
Changed current directory to /var/www/.composer
./composer.json has been updated
Running composer update drush/drush
Loading composer repositories with package information
Updating dependencies
```

It would be good if this composer command when first starting a drupal9 Pantheon lando container ran with the `-n` flag to disable interaction, since it's touching an internal composer.json file.

**Comment by labboy0276** [comment]
@davereid-pfg can you provide your `.lando.yml` so I can see whats up.

**Comment by davereid-pfg** [comment]
The .lando.yml (at least the parts that 

```yml
recipe: pantheon
config:
  framework: drupal9
  index: false
  edge: false
  cache: false

services:
  appserver:
    composer_version: 2
    drupal: true
    xdebug: off
```

The pantheon.yml:

```yml
api_version: 1
drush_version: 10
web_docroot: true
php_version: 7.3
database:
  version: 10.4
```

I believe this is what triggers this since by default the image uses Composer 1 with hirak/presstimmio enabled but on update to 2.2+, Composer requires manual intervention for it's global /var/www/.composer/composer.json file due to the "More secure plugin execution" part of https://blog.packagist.com/composer-2-2/
