### ISSUE TITLE
Passthrough tooling options are duplicated

### ISSUE THREAD

**Issue by edaemon** [lando/lando#3308]
When some tooling is configured with a passthrough option, running that tooling with a non-default option results in duplication. For example (the `echo` is just for debugging):

```
tooling:
  word:
    service: appserver
    cmd: echo
    options:
      word:
        passthrough: true
        describe: Print what the word is
        default: bird
```

Running `lando word` yields: `--word=bird`

Running `lando word --word=foo` yields: `--word=foo --word=foo`

That makes for odd situations when using real commands, especially because any arguments provided will be placed after the first `--word=foo`. E.g. `lando word lorem ipsum dolor --word=foobar sit amet` yields `--word=foobar lorem ipsum dolor --word=foobar sit amet`. Many commands can tolerate repeated options but the ordering can break some tools. Subcommands, for example, often take different options; I came across this when trying to configure Lando to run Playwright with `lando playwright test --project=dev`, which consistently places the `--project` option _before_ the `test` subcommand, throwing an error because that option only exists for the `test` subcommand.

Note that this does seem to be related to the `passthrough: true` setting, though I may just be misunderstanding the purpose of that setting. Removing it gets rid of the duplicated option, but it also essentially means the tooling option simply doesn't do anything (as far as I can tell). Without `passthrough: true` the default option value doesn't appear in the command. It can be provided explicitly but that's no different than how it works without the tooling option configured.
