### ISSUE TITLE
Update behat-ish docs with some windows caveats

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#331]
Feature/Enhancement Request
===========================

Documentation request:
I want to add behat support to lando for an app I created with the pantheon recipe.

Please provide some detail on how lando can help solve this problem

I am on Windows 10 Pro with landov3-beta13. I created a lando app with the pantheon recipe (drupal 8). 
 When I enter `lando behat`, I get `Unknown argument: behat`.

I read [the page about Lando and Behat](https://docs.lndo.io/tutorials/lando-pantheon-workflow.html), which says to add `BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://lando-pantheon-workflow.lndo.site/"}, "Drupal\\DrupalExtension" : {"drush" :   {  "root":  "/app/web" }}}}'` to `lando.yml`.

I did that and restarted the app as suggested but it still doesn't recognize the behat argument.

I also checked out issue #149 which has some issue on behat with the pantheon composer repo but it doesn't mention anything about using lando to run behat.

Any help about how to get this going would be much appreciated.

**Comment by dustinleblanc** [comment]
to run `lando behat` you'd need to define a tooling entry that used the appserver:

```yaml
tooling:
  behat:
    service: appserver
```

**Comment by ptmkenny** [comment]
@dustinleblanc Thanks, I added that to my `lando.yml` and then ran `lando rebuild`.

Then I tried running `lando behat`, but I'm getting:

`/bin/sh: 1: behat: not found`

Windows 10 Pro, running from powershell.

**Comment by ptmkenny** [comment]
Ok, more info.

So far, I have been able to get behat running like this:

`lando ssh appserver`

Need to add the composer vendor directory to PATH.

`vim ~/.bashrc`

Add this line:

`export PATH=$PATH:/app/vendor/bin;`

`source ~/.bashrc'

Now the `behat` command can be used from inside appserver, but `lando behat` still doesn't work.

Tests can be run using this `.behat.yml`:

```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
      # base_url: http://edosensei.lndo.site
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drush'
      drupal:
        drupal_root: '/app/web'
      drush:
        root: '/app/web'
```

But, **this results in an error when attempting to connect to localhost:**

```
    And I am logged in as a user with the "administrator" role # Drupal\DrupalExtension\Context\DrupalContext::assertAuthenticatedByRole()
      cURL error 7: Failed to connect to localhost port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (GuzzleHttp\Exception\ConnectException)
    │
    ╳  Unable to access the response before visiting a page (Behat\Mink\Exception\DriverException)
    │
```

So, there are two problems:

1) I can't run `lando behat`; I have to ssh into the app server and run `behat`.

2) The behat drush extension is trying to connect to localhost on port 80.

**Comment by ptmkenny** [comment]
Ok, so here is a solution.  On Windows, apparently you need to give behat the IP address of the host (`ipconfig /all') when running behat through docker like this:

`base_url: http://192.168.x.x:32888`

I can run the tests this way using `lando behat`.

**Comment by dustinleblanc** [comment]
That's pretty crazy! Typically when I have tried to run Behat inside a
docker container I have to give the container name as the hostname. Given
that the Lando appservers usually have Nginx and PHP inside the same
container that shouldn't even be necessary. Looks like windows showed up to
ruin the party again :(

Glad you found it!

**Comment by pirog** [comment]
@ptmkenny you might be able to get around this by hacking the windows hosts file as well. 

Also would love to see this knowledge added to some of our behat docs if you've got the time for a PR!

**Comment by ptmkenny** [comment]
@pirog I've kept notes that I will clean up and turn into documentation later.  Still trying to fix some issues; when I get it all working reliably, I'll add the doc.

**Comment by johnatasjmo** [comment]
I have on behat-pantheon.yml
```
local:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
      base_url: 'http://nginx:80'
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drupal:
        drupal_root: '/app/web'
      drush:
        root: '/app/web'
```

and run 
```
lando behat --config=/app/tests/behat-pantheon.yml --profile local
```
and works for me.
