### ISSUE TITLE
Added volumes are not readable for other services

### ISSUE THREAD

**Issue by MatthiasBrodelet** [lando/lando#3311]
I'm unable to access the files insides the added volumes from other services.
2 folders (_cfg and _cms) are being added from outside the root where the lando file exists.
When I open the proxy to the cms service I just see an empty folder while the site service is showing an error because it can't access a file in the _cms folder.

My folder structure :
```
- _cms
- project
    - public
    - .lando.yml
```

The lando file:
```
name: lapetitefourchette
recipe: lamp
config:
  webroot: .
  php: 7.3
  database: mariadb:10.1.47

proxy:
  site:
    - lpf-site.lndo.site
  cms:
    - lpf-cms.lndo.site

services:
  appserver:
    ssl: true
    overrides:
      volumes:
      - ../_cfg/:/app/_cfg
      - ../_cms/:/app/_cms
    pma:
      type: phpmyadmin
    hosts:
      - database

  site:
    type: php:7.3
    via: apache:2.4
    ssl: true
    webroot: public
    build_as_root:
      - a2enmod headers
  cms:
    type: php:7.3
    via: apache:2.4
    ssl: true
    webroot: /_cms
    build_as_root:
      - a2enmod headers
```
