### ISSUE TITLE
Proxy and appserver not starting - Certificate Issue?

### ISSUE THREAD

**Issue by markb-wa** [lando/lando#3315]
Tell us about your setup

lando v3.6.0
docker desktop 3.6.0
on macOS 12.1 (Monterey)

Tell us about your .lando.yml

```
name: auctioneer
recipe: drupal9
config:
  php: 7.4
  webroot: web
  database: mariadb:10.4
  composer_version: 2
env_file:
  - .env
proxy:
  mailhog:
    - mail.auctioneer.lndo.site
services:
  solr:
    type: solr:8.6
    portforward: 8983
    core: maincore
    config:
      dir: .lando/solr_8.x_config
  redis:
    type: redis:6.0
    portforward: true
  appserver:
    xdebug: true
    config:
      php: .lando/config/php.ini
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: serverName=auctioneer.lndo.site
        BEHAT_PARAMS: '{"extensions": {"Imbo\\BehatApiExtension": {"apiClient": {"base_uri": "https://auctioneer.lndo.site/"}}, "Drupal\\MinkExtension": {"base_url": "https://auctioneer.lndo.site/"}}}'
    build:
      - chmod 775 /app/web/sites/default
      - composer install --prefer-dist --no-progress --no-interaction --apcu-autoloader
      - composer dumpautoload -o
      - /app/vendor/bin/phpcs --config-set installed_paths /app/vendor/drupal/coder/coder_sniffer,/app/vendor/slevomat/coding-standard
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
  node:
    type: node:16
    build:
      - cd /app && npm install
    run:
      - cd /app/web/themes/custom/auctioneer && npm install
# Uncomment the lines below if you want lando to not sync those directories (https://docs.lando.dev/config/performance)
#excludes:
#  - vendor
#  - node_modules
#  - web/themes/custom/auctioneer/node_modules
#  - web/modules/contrib
#  - web/themes/contrib
#  - web/core
tooling:
  # Here are some utilities that should exist in every application
  # container
  node:
    service: node
  npm:
    service: node

  # And some utilities we installed in the `build.flavor`
  # or `dependencies` key
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: https://auctioneer.lndo.site
  composer:
    service: appserver
  redis-cli:
    service: cache
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs --standard=/app/phpcs.xml
    options:
    description: Run phpcs for given folder or file.
  phpcbf:
    service: appserver
    cmd: /app/vendor/bin/phpcbf --standard=/app/phpcs.xml
    options:
    description: Run phpcs for given folder or file.
  phpspec:
    service: appserver
    cmd: /app/vendor/bin/phpspec run
    options:
    description: Run phpspec tests for given folder or file.
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat
    options:
    description: Run behat tests for given folder or file.
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit --debug --verbose
    options:
    description: Run phpunit tests for given folder or file.
  deploy:
    service: appserver
    cmd:
      - chmod 775 /app/web/sites/default
      - composer install --prefer-dist --no-progress --no-interaction --apcu-autoloader
      - composer dumpautoload -o
      - drush -y cache-rebuild
      - drush -y updatedb
      - drush -y config-import
      - drush locale:check
      - drush locale:update
      - drush -y sql-sanitize --sanitize-email=user_%uid@example.com --sanitize-password=Custom_password@2000
      - drush uli
      - drush en maillog -y
    options:
    description: Run the deploy steps Platform.sh runs.
  git-fix:
    service: appserver
    cmd:
      - chmod 775 /app/web/sites/default
      - git checkout -- /app/web/sites/default
    options:
    description: Fixes issues where files are not reverted on git pull.
  sass-watch:
    service: node
    dir: /app/web/themes/custom/auctioneer/presentation/
    cmd: sass -w scss:css -s compressed -q
    description: Watch the theme sass files and compile on change.
  sass-compile:
    service: node
    dir: /app/web/themes/custom/auctioneer/presentation/
    cmd: sass scss:css -s compressed -q
    description: Compile theme sass files on demand.
  site-install:
    service: appserver
    cmd:
      - drush si --existing-config -y
      - drush cr
      - drush en -y sample_content maillog
    description: Install the site with some content.
```

Tell us about the error you got

After `lando start`, `lando rebuild -y`

-  Appserver URLs with the custom domain are red and do not resolve
-  Appserver not running. Starts briefly, but shuts off.

Tell us generally about your bug

I notice that the traefik proxy container, and the appserver does not remain up (exits) after starting the app, which is not normal. When I show logs for it, it seems to be failing to setup certificates.

`docker logs landoproxyhyperion5000gandalfedition_proxy_1`

```
addcert 15:24:26.INFO  ==> Cert creation kicking off....
addcert 15:24:26.INFO  ==> 
addcert 15:24:26.DEBUG ==> ==================================================
addcert 15:24:26.DEBUG ==> LANDO_CA_CERT     : /lando/certs/lndo.site.pem
addcert 15:24:26.DEBUG ==> LANDO_CA_KEY      : /lando/certs/lndo.site.key
addcert 15:24:26.DEBUG ==> CA_DIR            : /usr/share/ca-certificates
addcert 15:24:26.DEBUG ==> CA_CERT_FILENAME  : lndo.site.pem
addcert 15:24:26.DEBUG ==> CA_CERT_CONTAINER : /usr/share/ca-certificates/lndo.site.pem
addcert 15:24:26.DEBUG ==> COMMON_NAME       : 
addcert 15:24:26.DEBUG ==> LANDO_PROXY_NAMES : 
addcert 15:24:26.DEBUG ==> LANDO_EXTRA_NAMES : DNS.100 = *.lndo.site
addcert 15:24:26.DEBUG ==> ==================================================
addcert 15:24:26.INFO  ==> 
addcert 15:24:26.INFO  ==> Generating certs...
Generating RSA private key, 2048 bit long modulus (2 primes)
....................................................+++++
......................................................................................................+++++
e is 65537 (0x010001)
req: No value provided for Subject Attribute CN, skipped
Signature ok
subject=C = US, ST = California, L = San Francisco, O = Lando, OU = Bespin
Getting CA Private Key
unable to load number from /lando/certs/lndo.site.srl
139621585112392:error:06067099:digital envelope routines:EVP_PKEY_copy_parameters:different parameters:crypto/evp/p_lib.c:93:
139621585112392:error:0D066096:asn1 encoding routines:a2i_ASN1_INTEGER:short line:crypto/asn1/f_int.c:140:
run-parts: /scripts/000-add-cert: exit status 1
proxycerts 15:24:26.INFO  ==> We have proxy certs!
proxycerts 15:24:26.DEBUG ==> Removing older config
proxycerts 15:24:26.INFO  ==> Dumped config to /proxy_config/proxy.yaml
proxycerts 15:24:26.DEBUG ==> tls: certificates: - certFile: "/lando/certs/proxy._lando_.crt" keyFile: "/lando/certs/proxy._lando_.key"
addcert 15:24:26.INFO  ==> Cert creation kicking off....
addcert 15:24:26.INFO  ==> 
addcert 15:24:26.DEBUG ==> ==================================================
addcert 15:24:26.DEBUG ==> LANDO_CA_CERT     : /lando/certs/lndo.site.pem
addcert 15:24:26.DEBUG ==> LANDO_CA_KEY      : /lando/certs/lndo.site.key
addcert 15:24:26.DEBUG ==> CA_DIR            : /usr/share/ca-certificates
addcert 15:24:26.DEBUG ==> CA_CERT_FILENAME  : lndo.site.pem
addcert 15:24:26.DEBUG ==> CA_CERT_CONTAINER : /usr/share/ca-certificates/lndo.site.pem
addcert 15:24:26.DEBUG ==> COMMON_NAME       : 
addcert 15:24:26.DEBUG ==> LANDO_PROXY_NAMES : 
addcert 15:24:26.DEBUG ==> LANDO_EXTRA_NAMES : DNS.100 = *.lndo.site
addcert 15:24:26.DEBUG ==> ==================================================
addcert 15:24:26.INFO  ==> 
addcert 15:24:26.INFO  ==> Generating certs...
Generating RSA private key, 2048 bit long modulus (2 primes)
............+++++
.....................................................+++++
e is 65537 (0x010001)
req: No value provided for Subject Attribute CN, skipped
Signature ok
subject=C = US, ST = California, L = San Francisco, O = Lando, OU = Bespin
Getting CA Private Key
unable to load number from /lando/certs/lndo.site.srl
139732064791880:error:06067099:digital envelope routines:EVP_PKEY_copy_parameters:different parameters:crypto/evp/p_lib.c:93:
139732064791880:error:0D066096:asn1 encoding routines:a2i_ASN1_INTEGER:short line:crypto/asn1/f_int.c:140:
run-parts: /scripts/999-refresh-certs: exit status 1
```

Have tried multiple attempts of destroying/rebuilding the app, restarting docker, restarting my machine, reinstalling docker  and reinstalling lando, all of which had no effect.

As best as I can tell/aware nothing else has changed on my system. 

Similar/Related Issues:

- #2754 
- #2825
