### ISSUE TITLE
Can't use apt-get in build on latest php images

### ISSUE THREAD

**Issue by xtfer** [lando/lando#3330]
Attempting to use apt-get in the build_as_root step in the latest php images (and possibly others?) results in errors due to missing system dependencies.

A workaround is to add a script to your project, e.g....

```
services:
  appserver:
    build_as_root:
      - /app/scripts/build-as-root.sh
```

with the following:

```
#!/bin/sh

dpkg --configure -a
apt-get -f install -yq
apt-get autoremove -yq
apt-get autoclean -yq
apt-get update -yq
apt-get upgrade -yq
apt-get install software-properties-common -yq
apt-get install software-properties-gtk -yq
```

I found the original solution at https://askubuntu.com/questions/788762/my-system-wont-install-anything.
