### ISSUE TITLE
Error running a command as LANDO_DROP_USER

### ISSUE THREAD

**Issue by sinnbeck** [lando/lando#3331]
I am trying to run this command inside a php image
```
octane:
    type: php:8.1
    via: cli
    command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=80
    environment:
        LANDO_DROP_USER: www-data
```
But when lando tries to drop down to the www-data user, it throws the following error

>su: unrecognized option '--server=swoole'

I can only get it to work if I run it as root and manually force it to run as www-data
```
command: runuser www-data -c "/usr/local/bin/php /app/artisan octane:start --server=swoole --host=0.0.0.0 --port=80"
