### ISSUE TITLE
Restarting individual resources (with dependencies)

### ISSUE THREAD

**Issue by tpluscode** [lando/lando#3340]
I would like to propose an extension to the `lando restart` command so that it's possible to restart only a subset of services

For example, given a a config

```yaml
name: example
services:
  core:
    type: node:custom
    command: yarn start
    ssl: true
    overrides:
      image: node:14
      depends_on:
        store:
          condition: service_healthy
  store:
    type: compose
    services:
      image: a/database
    healthcheck:
        test: wget --no-verbose --tries=1 --spider http://localhost:3030 || exit 1

# more services
```

If I called `lando restart -s core`, it would restart only that one container

On the other hand, executing `lando restart -s store` would restart both the `store` and `core` because of `depends_on`. Unless this rather become an option behind some `--include-dependent` flag
