### ISSUE TITLE
Credentional cannot be overriden

### ISSUE THREAD

**Issue by Daisuke-sama** [lando/lando#3352]
https://github.com/lando/lando/issues/1383

I have same issue. 
environment variables aren't working and config replacement of lando provides same results
```
    creds:
      database: crmdb
      user: user
      password: secret
```
or
```
services:
  database:
    overrides:
       environment:
         POSTGRES_USERNAME: user
         POSTGRES_PASSWORD: secret
```

Only database name applies.
