### ISSUE TITLE
Solr config from Drupal module isn't being copied to Solr Container

### ISSUE THREAD

**Issue by drubb** [lando/lando#3358]
Using a Drupal codebase with the Search API Solr module, this was the configuration I've used for the Solr service for some time:

```
services:
  search:
      type: solr:8
      core: drupal9
      portforward: true
      config:
        dir: /app/drupal/modules/contrib/search_api_solr/jump-start/solr8/config-set
```

In the current Lando release (3.6.2), the Solr core (drupal9) will be created in /var/solr/data, but the folder is empty, no config inside.
The config source (/app/drupal/modules/contrib/search_api_solr/jump-start/solr8/config-set) exists.

What am I missing?
