### ISSUE TITLE
Additional proxy domains point to default nginx page - Mac M1

### ISSUE THREAD

**Issue by solic-manta** [lando/lando#3361]
OS: MacOS
Architecture: M1 ARM64

Lando version: 3.6.2
it didn't work on Lando 3.1.4 either

Steps to reproduce:

- add additional proxy domains to some service
- start the project and go to given domain

Lando file I used:

```
name: 'project_name'
recipe: drupal7

config:
  webroot: .
  php: '7.0'
  via: nginx
  database: mariadb:10.1
  conf:
    server:  lando_config/nginx.conf
    php:  lando_config/php.ini

services:
  node-cli:
    type: node:11
    globals:
      gulp-cli: "latest"

  database:
    type: mysql
    config:
      database: lando_config/mysql/my.cnf
    portforward: 38658

proxy:
  appserver_nginx:
    - some.lndo.site
tooling:
  npm:
    service: node-cli
  node:
    service: node-cli
  gulp:
    service: node-cli
```
Notes: same config works on ubuntu and intel-macOS so the issue isn't in custom config for nginx.
