### ISSUE TITLE
Lando could not detect an open port amongst

### ISSUE THREAD

**Issue by denics** [lando/lando#3374]
Dear all,
I was happily deploying everything with lando until one day I got this error and I have been unable to deploy anything since then:
```
ERROR ==> Lando could not detect an open port amongst: 80, 8000, 8080, 8888, 8008
```
This is my lando.yml file:
```
name: site.org
recipe: drupal9
config:
  php: '7.4'
  composer_version: 2
  via: 'apache:2.4'
  webroot: 'www'
  database: 'mariadb:10.4'
  xdebug: true
services:
  appserver:
    build_as_root:
      - ln -snf /usr/share/zoneinfo/Europe/Paris /etc/localtime
      - echo "Europe/Paris" > /etc/timezone
      - /bin/sh -c 'if [ ! -z ${HTTP_PROXY+x} ]; then echo "Acquire::http::Proxy \"${HTTP_PROXY}\";" > /etc/apt/apt.conf; fi;'
      - apt clean
      - apt update -y
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt install vim nodejs python3-pip libgeos-c1v5 -y
      - npm install -g npm
      - npm install -g gulp
      - pip install droopescan
      - pecl install uploadprogress
      - docker-php-ext-enable uploadprogress
      - /bin/sh -c 'cp /app/.lando/geos-7.4.so /usr/local/lib/php/extensions/no-debug-non-zts-20190902/geos.so'
      - docker-php-ext-enable geos
      - docker-php-ext-install sockets
    build:
      - composer install
      - /bin/sh -c "if [ ! -d /app/www/sites/default ]; then mkdir -p /app/www/sites/default; fi; cp /app/.lando/settings.local.php /app/www/sites/default/settings.php"
      - composer run-script post-install-cmd
      - npm install --prefix /app/www/themes/custom/theme
      - DISABLE_NOTIFIER=1 gulp --cwd /app/www/themes/custom/theme build
  solr:
    type: solr:8.6
    portforward: true
  redis:
    type: redis
  varnish:
    type: varnish
    backends:
      - appserver
    backend_port: 80
    ssl: false
proxy:
  appserver:
    - www.lndo.site
tooling:
  combawa:
    service: appserver
    cmd: "/app/vendor/bin/combawa.sh"
  drupal:
    service: appserver
    cmd: "/app/vendor/bin/drupal"
  drupalcs:
    service: appserver
    cmd: "/app/vendor/bin/phpcs --standard=Drupal --extensions='php,module,inc,install,test,profile,theme,css,info,txt,md'"
  drupalcsp:
    service: appserver
    cmd: "/app/vendor/bin/phpcs --standard=DrupalPractice --extensions='php,module,inc,install,test,profile,theme,css,info,txt,md'"
  drupalcbf:
   service: appserver
   cmd: "/app/vendor/bin/phpcbf --standard=Drupal --extensions='php,module,inc,install,test,profile,theme,css,info,txt,md'"
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://www.lndo.site"
  gulp:
    service: appserver
  npm:
    service: appserver
  parallel-lint:
    service: appserver
    cmd: "/app/vendor/bin/parallel-lint -j 20"
  scan:
    service: appserver
    cmd: "droopescan scan drupal -u https://www.lndo.site"
env_file:
  - .env
```

any idea?
