### ISSUE TITLE
Configure background jobs for services

### ISSUE THREAD

**Issue by drjayvee** [lando/lando#3383]
I'm trying to run [`grunt watch`](https://github.com/gruntjs/grunt-contrib-watch) in the background using

```yaml
services:
  appserver:
    type: whatever:13.37
    build:
      - npm install
    run:
      - grunt watch &
```
But that doesn't work. 😞 

Is there a way to do this? The [services docs](https://docs.lando.dev/config/services.html) don't provide examples.
