### ISSUE TITLE
lando drush uli gives url with "default" domain instead of "mysite.lndo.site"

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#339]
Bug Report
==========

**Tell us about your setup**
Windows 10 Pro, lando v3-beta-17

**Tell us about your `.lando.yml`**
```
# If you change this file, lando rebuild.

# Change php and docroot in .pantheon.yml, not here.

name: mysite
recipe: pantheon
config:
  framework: drupal8
  xdebug: true
  env: dev
  site: mysite
  id: secret
  webroot: web/

# Additional mailhog proxy settings so we get a nice URL for the mailhog ui
proxy:
  mailhog:
    - mail.mysite.lndo.site

# Mailhog things
services:

  # Spin up a mailhog container called "mailhog"
  # NOTE: "mailhog" is arbitrary, you could just as well call this "blackhole" or "weezer"
  mailhog:

    # Use the latest mailhog version
    type: mailhog

    # List of services that we want to capture mail from
    # You can run `lando info` to get a list of services that are available
    # Mailhog expects that these services will be php services
    hogfrom:
      - appserver

    # Optionally allow access to the smtp service at localhost:1026
    # You will need to make sure port 1026 is open on your machine
    #
    # You can also set `portforward: true` to have Lando dynamically assign
    # an open port. Unlike specifying an actual port setting this to true will give you
    # a different port every time you restart your app
    portforward: 1026

tooling:
  behat:
    service: appserver
  # Define `lando composer` as a command that runs `composer --ansi @` against
  # the appserver service. Note that @ will be any additional arguments you pass
  # into `lando composer`
  #
  # Example: typing `lando composer install` will run `composer --ansi install`
  # inside the container.
  composer:

    # Run the `lando composer` command against the appserver from the services
    # section above
    service: appserver

    # Give a nice description to describe what this does.
    # If ommited this will default to "Run COMMAND commands" where COMMAND is
    # composer in this case
    description: Run composer commands

    # Define a specific command to start with inside the container. If ommited
    # this will default to the name you give the service eg composer.
    #
    # This can be a string or an array. We recommend using an array if you are
    # passing in additional options that you might want to enforce.
    cmd:
      - composer
      - --ansi
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

  **lando drush uli**

**Tell us about the error you got**

http://default/user/reset/1/1505227155/Art9a6Pem9I0tLxFnNUrUe32klKvxoAOiwXbYxIYruY/login

**Tell us generally about your bug**

Instead of getting "http://mysite.lndo.site/user/reset/1/1505227155/Art9a6Pem9I0tLxFnNUrUe32klKvxoAOiwXbYxIYruY/login", I get "default" as the domain in the drush output.

**Comment by serundeputy** [comment]
Hello @ptmkenny 

If you set the `$base_url` in `settings.local.php` file then `drush uli` will give you what you want:

`settings.local.php`:
```php
// Set the base URL for the Drupal site.
$base_url = 'https://mysite.lndo.site';
```

I believe at the bottom of the Pantheon `settings.php` it is already including the `settings.local.php` file, but if it is not for your app you will have to include it.  If you don't have a `settings.local.php` you can just add one with just the above lines.  If you already have one just add those lines.

Hope that helps.

**Comment by ptmkenny** [comment]
Hi @serundeputy, thanks for this, that's helpful.

Alas, I'm using Drupal 8, which doesn't support `$base_url` ([Source](https://drupal.stackexchange.com/questions/199445/how-do-i-change-the-base-url)

**Comment by serundeputy** [comment]
@ptmkenny indeed!

This worked for me on D8:

>Instead create sites/default/drushrc.php and add
```php
<?php
$options['uri'] = "http://mysite.local";
```
>and you should be fine.

source: https://drupal.stackexchange.com/questions/197651/how-i-change-my-site-uri-in-drupal-8

**Comment by ptmkenny** [comment]
@serundeputy Perfect, thanks!  Closing this but please check my addition to the documentation.

**Comment by frederickjh** [comment]
In case someone else finds this will searching as it is high up on Google's search results, you can set the uri in a [drush site alias file][1] to avoid getting http://default at the beginning of your password reset links.

ie. **drush/sites/example.sites.yml**

```yaml
live:
   host: server.example.com
   user: user   
   ssh: '-p 22'
   root: /home/user/public_html/docroot
   uri: 'http://example.com'
test:
   host: server2.example.net
   user: user2
   ssh: '-p 22'
   root: /home/user2/public_html/docroot
   uri: 'http://test.example.net'
dev:
   host: localhost
   user: docker
   root: /var/www/docroot
   uri: 'http://example.dev.example.com'
```
Then use the Drush site alias in the command for the password reset link:

    drush @example.dev uli

The **example** after the @ symbol in the Drush site alias comes from the first part of the Drush site alias filename. The second part comes from the site entry in the file.

  [1]: https://github.com/drush-ops/drush/blob/master/examples/example.site.yml

**Comment by dwkitchen** [comment]
As my google search brought this result up first adding a link to the guide in the docs: https://docs.lando.dev/config/drupal8.html#default-url-setup

**Comment by jraviotta** [comment]
Setting `DRUSH_OPTIONS_URI` in `lando.yml` does not work for me. However setting in `sites/default/drushrc.php` [does work.](https://github.com/lando/lando/issues/339#issuecomment-329495496)

Do you see any problems with my `lando.yml`?

```
...
services:
  appserver:
    config:
      php: .vscode/php.ini
    build:
      - composer install
      - mkdir -p ~/.drush/site-aliases
      - ln -sf /app/drush/4pillars-8.aliases.drushrc.php ~/.drush/site-aliases/4pilars-8.drushrc.php
    overrides:
      environment:
        DRUSH_OPTIONS_URI: 'http://4Pillars-8.lndo.site'
...
```

**Comment by andy-lcm** [comment]
I found a solution that works for me and does not require a rebuild - in .lando.yml include:

```
tooling:
  drush:
    service: appserver
    cmd: drush -l https://sternlife.lndo.site --root=/app/web

```

**Comment by hotwebmatter** [comment]
@andy-lcm 

Your suggestion is the quickest and easiest to implement, and it seems to work out of the box without a rebuild.

However, it breaks `drush` in subtle ways.

For example:

```
$ lando drush en my_cool_module

                                                     
  Too many arguments, expected arguments "command".  
                                                     
```

What's happening here? No matter what drush command you run will be prepended by `-l https://mysite.lndo.site --root=/app/web`, but those arguments are only necessary for the `lando drush uli` and they cause Drush to become confused in some situations (and not in others, which makes debugging tricky).

Removing your tooling definition from my `.lando.yml` allowed Drush to execute commands correctly again:

```
$ lando drush en my_cool_module
 [success] Successfully enabled: my_cool_module
```

The best solution is to configure Drush aliases properly, as suggested by @frederickjh above.

If you don't have time for that, then just make a bash function like this:

```bash
function fd() {                                                                 
  if [[ $# -eq 0 ]]; then                                                       
    echo "druli"                                                
    echo "Usage: druli foo [bar baz ...]"                                          
    echo "Executes lando drush uli for project foo"                            
  fi                                                                            
  for site in "$@"; do
    lando drush -l https://${site}.lndo.site --root=/app/web uli
  done
}

I think you'll find, though, that setting up Drush aliases correctly is less work in the long run.

**Comment by uberhacker** [comment]
I recognize that @hotwebmatter dude. :)  I find the "best" but certainly not easiest way to solve this issue is as @serundeputy suggested.  However, the way I do it is in a build step that copies the config into the container in the appropriate location.  I have scripts for both Drush 8 and 9/10.
Drush 8:
```
$ cat lando/tooling/drush8-config.sh 
#!/bin/bash
LANDO_DRUSH=/app/lando/drush
LOCAL_DRUSH=$HOME/.drush
LOCAL_SITES=/app/web/sites/default
echo Add drush 8 config
if [ ! -f $LOCAL_DRUSH/drushrc.php ]; then
  cp $LANDO_DRUSH/drushrc.php $LOCAL_DRUSH/drushrc.php
fi
echo Add drush 8 aliases
if [ ! -f $LOCAL_DRUSH/myproject.aliases.drushrc.php ]; then
  cp $LANDO_DRUSH/myproject.aliases.drushrc.php \
  $LOCAL_DRUSH/myproject.aliases.drushrc.php
fi
```
Drush 9/10:
```
$ cat lando/tooling/drush9-config.sh 
#!/bin/bash
LANDO_DRUSH=/app/lando/drush
LOCAL_DRUSH=$HOME/.drush
LOCAL_SITES=/app/web/sites/default
echo Create $LOCAL_DRUSH/sites
if [ ! -d $LOCAL_DRUSH/sites ]; then
  mkdir -p $LOCAL_DRUSH/sites
fi
echo Add drush 9/10 config
if [ ! -f $LOCAL_DRUSH/drush.yml ]; then
  cp $LANDO_DRUSH/drush.yml $LOCAL_DRUSH/drush.yml
fi
echo Add drush 9/10 aliases
if [ ! -f $LOCAL_DRUSH/sites/myproject.site.yml ]; then
  cp $LANDO_DRUSH/myproject.site.yml $LOCAL_DRUSH/sites/myproject.site.yml
fi
```
In `.lando.yml`, I add the build step:
```
services:                                                                                                                                                                                     
  appserver:                                                                                                                                                                                  
    build:                                                                                                                                                                                    
      - /app/lando/tooling/drush9-config.sh
```

**Comment by andy-lcm** [comment]
> However, it breaks `drush` in subtle ways.

I must concur :) I think I've noticed that exact behaviour may depend on which drush version you're using, not sure. For sure there are better solutions, but that one solved my issue of needing to get logged in quickly to a cloned client site without making more extensive changes.

**Comment by hotwebmatter** [comment]
> I recognize that @hotwebmatter dude. :)

:dart: And I recognize that @uberhacker dude -- hi, Ed!

Snooping around the Lando issue queues, I see that you have created a newer thread for this feature request:
https://github.com/lando/lando/issues/447

And it looks like @pirog is working on it: https://github.com/lando/lando/issues/2080#issuecomment-667114326

And there's already a suggested solution in the docs:
https://docs.lando.dev/config/drupal8.html#default-url-setup
https://docs.lando.dev/config/drupal9.html#default-url-setup

So everybody is well aware of the issue, but there's no clear consensus on how to set it automatically for the majority of users.

:thinking:

**Comment by rafaelferreir4** [comment]
Hey folks! Is there any update on this?

**Comment by djvilione** [comment]
Adding the following to my .lando.yml resolved the issue for me:

`services:
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: serverName=appserver
        DRUSH_OPTIONS_URI: 'https://mysite.lndo.site/'
`

**Comment by djvilione** [comment]
Adding the following to my .lando.yml resolved the issue for me:
```
services:
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: serverName=appserver
        DRUSH_OPTIONS_URI: 'https://mysite.lndo.site/
```
