### ISSUE TITLE
the input device is not a TTY

### ISSUE THREAD

**Issue by clacdesdoigts** [lando/lando#3395]
Happens while building containers with `lando start` or `lando rebuild`, using the Wordpress recipe.
This may prevent Lando from installing tools such as WP CLI interactively

Commands are launched in WSL2 (core version : 5.10.16) on Windows 11, in a Debian 11 (bullseye) distribution.
Lando version : 3.6.5

Here is my Landofile : 
```
name: wordpress
recipe: wordpress
proxy:
  appserver:
    - wordpress.lndo.site
    - espace.wordpress.lndo.site
    - account.wordpress.lndo.site
    - ca.wordpress.lndo.site
config:
  php: "7.3"
  via: apache
  webroot: web
  database: mysql:5.7
  xdebug: true
# Services
services:
  database_admin:
    type: phpmyadmin:5.0
    hosts:
      - database
  mail:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom:
      - appserver
```

And here is the output of `lando rebuild` : 

```
user@debian:~/www/wordpress$ lando rebuild
? Are you sure you want to rebuild? Yes
Rising anew like a fire phoenix from the ashes! Rebuilding app...
Killing wordpress_database_1       ... done
Killing wordpress_database_admin_1 ... done
Killing wordpress_mail_1           ... done
Killing wordpress_appserver_1      ... done
Going to remove wordpress_database_1, wordpress_database_admin_1, wordpress_mail_1, wordpress_appserver_1
Removing wordpress_database_1       ... done
Removing wordpress_database_admin_1 ... done
Removing wordpress_mail_1           ... done
Removing wordpress_appserver_1      ... done
Pulling database       ... done
Pulling mail           ... done
Pulling appserver      ... done
Pulling database_admin ... done
mail uses an image, skipping
database uses an image, skipping
database_admin uses an image, skipping
appserver uses an image, skipping
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating wordpress_appserver_1 ... done
usermod: no changes
usermod: no changes

the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
ERROR ==> the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

Creating wordpress_mail_1           ... done
Creating wordpress_database_1       ... done
Creating wordpress_database_admin_1 ... done
Waiting until database service is ready...
Waiting until database service is ready...
Scanning to determine which services are ready... Please stand by...

  _      __              _           __
 | | /| / /__ ________  (_)__  ___ _/ /
 | |/ |/ / _ `/ __/ _ \/ / _ \/ _ `/_/
 |__/|__/\_,_/_/ /_//_/_/_//_/\_, (_)
                             /___/

Your app started up but we detected some things you may wish to investigate.
These only may be a problem.
```

Note : running `docker run -it hello-world` shows no error.
Same with `docker.exe run -it hello-world` though I have installed docker engine inside WSL and disabled interoperability so Lando should not use the Windows host's docker executable.

Trying to run `lando wp` after that returns `/bin/sh: 1: wp: not found`
My workaround has been to install WP CLI manually inside the container, but this issue might not be related to the Wordpress recipe, this is why I am posting it here.
