### ISSUE TITLE
How to run "lando composer"?

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#340]
Feature/Enhancement Request
===========================

Please explain your request and its importance in the form of a user story.

As a lando user who works on different Windows machines that don't always have composer set up, I want to be able to run composer from within the lando environment (`lando composer xyz`).

The tooling documentation (https://docs.lndo.io/config/tooling.html) suggests this for `.lando.yml` to run composer commands:

```
tooling:

  # Define `lando composer` as a command that runs `composer --ansi @` against
  # the appserver service. Note that @ will be any additional arguments you pass
  # into `lando composer`
  #
  # Example: typing `lando composer install` will run `composer --ansi install`
  # inside the container.
  composer:

    # Run the `lando composer` command against the appserver from the services
    # section above
    service: appserver

    # Give a nice description to describe what this does.
    # If ommited this will default to "Run COMMAND commands" where COMMAND is
    # composer in this case
    description: Run composer commands

    # Define a specific command to start with inside the container. If ommited
    # this will default to the name you give the service eg composer.
    #
    # This can be a string or an array. We recommend using an array if you are
    # passing in additional options that you might want to enforce.
    cmd:
      - composer
      - --ansi

```

After rebuilding with `lando rebuild` and then `lando composer`, which gives me the following error:

```
PS C:\Users\patri\d\mysite> lando composer


  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "composer" is not defined.

```

When I simply run `lando`, I see `composer` in the list of commands, so I know it was added through `.lando.yml`.

I then thought that I might need to install composer in the app, so I ran `lando ssh appserver`.  Once inside by ssh, I ran `composer`, which resolved properly, so composer is already installed.

To use `lando composer`, what do I need to do besides change `.lando.yml`?
