### ISSUE TITLE
Drupal multisite databases not being displayed in PHPMyadmin

### ISSUE THREAD

**Issue by prashantdsala** [lando/lando#3401]
Hello,

1. Created Drupal 9 multisite with 2 subsites successfully
2. Created a separate database for each site
3. Logged in to PHPMyadmin databases for 2 subsites are not displayed there. Databases are present in MariaDB.
4. However database for the main site is present as it is.

Lando version : **v3.1.4**
Here is `.lando.yml`

```
name: healsecurity_lando
recipe: drupal9
config:
  webroot: web
  php: '7.4'
  composer_version: '2.1.9'
  # via: apache:2.4
  via: nginx
  database: mariadb:10.4
  xdebug: false
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  subsite1:
    type: mariadb:10.4
    portforward: true
    creds:
      user: drupal9
      password: drupal9
      database: subsite1
  subsite2:
    type: mariadb:10.4
    portforward: true
    creds:
      user: drupal9
      password: drupal9
      database: subsite2
proxy:
  appserver_nginx:
    - main.lndo.site
    - subsite1.lndo.site
    - subsite2.lndo.site
```

Attached is the screenshot of PHPMyadmin

![localhost-49289-database-phpMyAdmin-5-0-2](https://user-images.githubusercontent.com/1982323/169795453-77d79e1b-511b-433e-9383-f5fc11f37ca1.png)

Please let me know if I am missing any configurations.

Thanks
Prashant
