### ISSUE TITLE
Custom php.ini not loading

### ISSUE THREAD

**Issue by Rufus13apostol** [lando/lando#3410]
Hi there,

Using:
lando v3.6.5
docker:  20.10.8
os: win 10

Im trying to load the custom php.ini file but no luck so far. This is my yaml:

```
name: standalone
recipe: wordpress
config:
  php: '7.4'
  via: apache:2.4
  webroot: .
  database: mariadb
  xdebug: false
  config:
    php: config/php.ini  
```

I´ve tried many variations of that code, but none works, load php.ini in phpinfo is always blank...any thoughts?
