### ISSUE TITLE
Unable to load a custom php.ini configuration with wordpress recipes

### ISSUE THREAD

**Issue by Rufus13apostol** [lando/lando#3413]
Hi all,

I´m afraid that  I cannot load a custom php.ini conf with wordpress recipe.
I want to change the upload_max_filesize. Here is the .yaml:

```
name: standalone
recipe: wordpress
config:
  php: "7.4"
  via: apache
  webroot: .
  xdebug: true
  config:
    php: config/php.ini
```
I've try to

`php: `absoluteLocationTo/php.ini``

`php: php.ini` and put the php.ini in the same folder as lando.yml

It creates a directory named "php.ini", but not the file. If I create the file, it does not load it. It does not show it on phpinfo or in the terminal, if I try to load some values there, it does not work...what Im doing wrong?

thanks in advanced
