### ISSUE TITLE
Invalid lando commands with hyphen in name do not show command list

### ISSUE THREAD

**Issue by cgmonroe** [lando/lando#3418]
**Setup**

MacOS: Catalina / 10.15.7
Lando: Version v3.6.4

.lando.yml
```
name: sandbox
recipe: drupal9
config:
  composer_version: 2-latest
  php: '7.4'
  webroot: docroot
  xdebug: true
services:
  appserver: 
    config:
      composer_version: 2-latest
    build_as_root:
      - apt-get update -y
      - apt-get install -y nano
      - apt-get install -y jq
    run_as_root:
      - "/bin/chgrp www-data /run/host-services/ssh-auth.sock && /bin/chmod g+w /run/host-services/ssh-auth.sock"
    run:
    overrides:
    # Pass SSH keys.
      volumes:
        - type: bind
          # Linux user: add 'export LANDO_SSH_AUTH_SOCK="${SSH_AUTH_SOCK}"' at the end of your ~/.bashrc:
          # Mac user: MacOS specific path is here as the variable default value, nothing to do.
          source: "${LANDO_SSH_AUTH_SOCK:-/run/host-services/ssh-auth.sock}"
          target: /run/host-services/ssh-auth.sock
      environment:
        SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
        AH_SITE_ENVIRONMENT: lando 
        AH_NON_PRODUCTION: 1
  database: 
    type: mysql:5.7
    creds:
      user: drupal
      password: drupal
  pma: 
    type: phpmyadmin
    hosts:
      - database
    overrides:
      environment:
        UPLOAD_LIMIT: 1000M
      volumes:
        - ./.php.ini:/usr/local/etc/php/conf.d/custom.ini
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
events:
  post-start:
    - appserver: test -e ~/.ssh/config || printf 'Host *\n  AddKeysToAgent yes\n' > ~/.ssh/config
tooling:
  drush:
    cmd: /app/vendor/drush/drush/drush
    env:
      XDEBUG_MODE: off
  ssh-fix:
    service: appserver
    description: Fix ssh auth sock permission for MacOS users. Lando rebuild fixes the problem as well.
    cmd: "/bin/chgrp www-data /run/host-services/ssh-auth.sock && /bin/chmod g+w /run/host-services/ssh-auth.sock"
    user: root
```

**Problem description**

Entering lando commands with hypens just returns to the prompt with no usage notification.  This can cause users to think that miss-typed commands executed when they actually did not.

Examples of this behavior

lando xxx-xxx
lando fix-ssh
lando x-yy

**Expected Behavior**

Lando should display the usage message for any invalid command.

**Odd exceptions**

lando [single-char]-[single-char]  works.
