### ISSUE TITLE
Command lando drush is executed as root, shouldn't this be www-data?

### ISSUE THREAD

**Issue by jbertoen** [lando/lando#342]
Bug Report
==========

Running drupal 8 en a drupal 7 recipe with some custom config and services.

What is your lando version and operating system?
v3.0.0-beta.17 on macOS Sierra 10.12.6

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.
```yml
name: mysite
recipe: drupal7
config:
  webroot: web
  via: nginx
  php: '7.0'
  xdebug: true
proxy:
  nginx:
    - en.mysite.lndo.site
    - nl.mysite.lndo.site
  search:
    - solr.mysite.lndo.site
  pma:
    - pma.mysite.lndo.site
  mailhog:
    - mail.mysite.lndo.site
services:
  appserver:
    build:
      - "mkdir -p ~/.drush/site-aliases"
      - "ln -s /app/drush/mysite.aliases.drushrc.php ~/.drush/site-aliases/mysite.aliases.drushrc.php"
  search:
    type: solr:5.5
    core: mysite
    portforward: true
    config:
      conf: solrconf
  pma:
    type: phpmyadmin
  cache:
    type: memcached
    mem: 128
    portforward: true
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
tooling:
  git:
    service: appserver
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

This lists @none as possible alias.
```bash
lando drush sa
```
This lists @mysite as possible alias.
```bash
lando ssh
drush sa
```
From what I researched the issue probably lies in the fact that the lando drush command is run as root, while lando ssh default goes as the www-data user. Running drush after that as a different user. Wouldn't it be better to run lando drush as www-data as well? This is probably also with drupal console as well within the drupal 8 recipe and composer within the lamp recipe.

Example of tooling without user (which defaults than to root)
***Drupal 8 Recipe***
```js
      // Set tooling
      // Add drupal to the tooling
      build.tooling.drupal = {
        service: 'appserver',
        needs: ['database'],
        description: 'Run drupal console commands',
      };
```
***Drupal 7 Recipe***
```js
    // Add drush to the tooling
    build.tooling.drush = {
      service: 'appserver',
      needs: ['database'],
      description: 'Run drush commands'
    };
```
***LAMP Recipe***
```js
    // Get our default tooling opts
    var tooling = {
      composer: {
        service: 'appserver',
        description: 'Run composer commands',
        cmd: ['composer', '--ansi']
      },
      php: {
        service: 'appserver',
        description: 'Run php commands'
      }
    };
```
These tooling setups go through this piece of code:
```js
        // Get the backup user
        var userPath = 'environment.LANDO_WEBROOT_USER';
        var user = _.get(config.app.services[config.service], userPath, 'root');
        var name = config.name;
        var eventName = name.split(' ')[0];

        // Build out our options
        var options = {
          id: [config.app.dockerName, config.service, '1'].join('_'),
          compose: config.app.compose,
          project: config.app.name,
          cmd: cmd,
          opts: {
            app: config.app,
            mode: 'attach',
            pre: ['cd', dir.join('/')].join(' '),
            user: config.user || user,
            services: [config.service]
          }
};
```
Which defaults to root if you check the 3rd line in the code snippet. 
Example of tooling in default ssh tooling task with user www-data
***SSH task***
```js
          // Build out our run
          var run = {
            id: [app.dockerName, service, '1'].join('_'),
            compose: app.compose,
            project: app.name,
            cmd: options.command || 'cd $LANDO_MOUNT && bash',
            opts: {
              app: app,
              mode: 'attach',
              user: options.user || 'www-data',
              services: [service]
            }
          };
```
Conclusion is that we probably just have to set the user parameter in the lando yml file for the tooling to make this work.

I will tag this as a bug for now, until somebody tells me it is better to run lando drush as root or it is something else that .
