### ISSUE TITLE
Add RUN commands to PHP FPM services to install memcached PECL extensions

### ISSUE THREAD

**Issue by jbertoen** [lando/lando#343]
Bug Report
==========

What is your lando version and operating system?
v3.0.0-beta.17 on macOS Sierra 10.12.6

```yml
name: mysite
recipe: drupal7
config:
  webroot: web
  via: nginx
  php: '7.0'
  xdebug: true
proxy:
  search:
    - solr.mysite.lndo.site
  pma:
    - pma.mysite.lndo.site
  mailhog:
    - mail.mysite.lndo.site
services:
  appserver:
    extras:
      - "apt-get update"
      - "apt-get install libmemcached-dev -y"
      - "pecl install memcached"
      - "docker-php-ext-enable memcached"
  search:
    type: solr:5.5
    core: mysite
    portforward: true
    config:
      conf: solrconf
  pma:
    type: phpmyadmin
  cache:
    type: memcached
    mem: 128
    portforward: true
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
tooling:
  git:
    service: appserver
```

The default extensions that are installed contain a lot (like imagick, and stuff), which is great.  The thing is that I use memcache instead of redis for caching in a lot of drupal projects. So I have enabled that service but found out the PECL extension is not installed. Which is a bit weird because we do have a service available for memcache, so I kind of expect that it should integrate quite nicely with the available php services.

My proposal is to add the following commands from my lando yml file to the php fpm docker files within the current available RUN commands.
```bash
apt-get install libmemcached-dev -y
pecl install memcached
docker-php-ext-enable memcached
```
