### ISSUE TITLE
[Q] Running Lando in Gitlab CI/CD pipeline

### ISSUE THREAD

**Issue by RobinHoutevelts** [lando/lando#3435]
Has anyone successfully used Lando in a Gitlab CI docker pipeline?

I keep getting this error:

> Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/lando-entrypoint.sh": permission denied: unknown

We have other projects running in a docker:in:docker pipeline. But this is the first time I tried to setup a project using Lando.

I'm not sure what I'm doing wrong. Can't seem to find any documentation on how to run Lando in Gitlab CI.

Here is my current config:

<details><summary><code>.lando.yml</code></summary>

```yml
name: orain
recipe: drupal9
config:
    via: nginx
    database: mariadb:10.4
    webroot: ./public
    php: '8.1'
    composer_version: '2.3.8'
    drush: false
    xdebug: true
services:
    redis:
        type: redis:5
    frontend:
        type: node:12
tooling:
    setup:
        service: appserver
        description: |
            Create a fresh instance of the application. No initial database required.
            You first have to run "lando composer install"
        cmd: ./scripts/test-setup/setup.sh
        user: www-data
    buildFrontend:
        service: frontend
        description: Build the frontend
        cmd: CI=0 make assets
        env:
            APP_ENV: local
```

</details>

<details><summary>Lando <code>my-lando-image:3.6.5</code> <code>Dockerfile</code></summary>

```dockerfile
FROM node:14-buster

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update --fix-missing \
    && apt-get install -y build-essential libssl-dev curl ca-certificates curl gnupg lsb-release \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
    && echo \
         "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
         $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
  && apt-get update -y && apt-get install -y docker-ce docker-ce-cli containerd.io \
  && usermod -a -G docker node

ARG TARGETARCH
RUN case ${TARGETARCH} in arm64) ARCH="arm64" ;; amd64) ARCH="x64" ;; esac \
    && curl -fsSL -o lando "https://github.com/lando/cli/releases/download/v3.6.5/lando-linux-${ARCH}-v3.6.5" \
    && mv lando /usr/local/bin/lando \
    && chmod +x /usr/local/bin/lando

ARG TARGETARCH
RUN case ${TARGETARCH} in arm64) ARCH="aarch64" ;; amd64) ARCH="x86_64" ;; esac \
    && curl -fsSL -o /usr/local/bin/docker-compose "https://github.com/docker/compose/releases/download/v2.9.0/docker-compose-linux-${ARCH}" \
    && chmod +x /usr/local/bin/docker-compose

USER node

RUN mkdir -p ~/.lando/cache \
    && printf "proxy: 'OFF'\nbindAddress: '0.0.0.0'\nproxyBindAddress: '0.0.0.0'" > ~/.lando/config.yml \
    && echo false > ~/.lando/cache/report_errors \
    && chmod 755 ~/.lando \
    && lando --clear

ENTRYPOINT ["/bin/bash", "-l", "-c"]
```

</details>

<details><summary>Gitlab runner <code>config.yml</code></summary>

```toml
[[runners]]
  name = "gitlab-runner"
  url = "https://git.xxxxx.xx"
  token = "xxxxxxxxxxxxxxxxxxxx"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    Type = "s3"
    Shared = true
    [runners.cache.s3]
      ServerAddress = "s3.amazonaws.com"
      AccessKey = "xxxxxxxxxxxxxxxxxxxx"
      SecretKey = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      BucketName = "xxxxxxxxxxxxxxxxxxxx-gitlab-runner-shared-cache"
      BucketLocation = "eu-central-1"
  [runners.docker]
    tls_verify = false
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    shm_size = 0
    volumes = ["/certs/client", "/cache"]
```

</details>

<details><summary>Gitlab <code>.gitlab-ci.yml</code></summary>

```yaml
loadtest:
    image: my-lando-image:3.6.5
    variables:
        DOCKER_HOST: tcp://docker:2375
        DOCKER_TLS_CERTDIR: ""
    services:
        -   name: docker:20.10.17-dind
            alias: docker
    script:
        - docker ps
        -
            |
            # Create lando environment
            export LANDO_ENGINE_CONFIG="{\"host\": \"docker\", \"port\": \"2375\"}"
        - echo "$LANDO_ENGINE_CONFIG"
        - lando start -vvv
```

</details>
