### ISSUE TITLE
Error when adding proxy domain for MinIO container

### ISSUE THREAD

**Issue by ahamilton9** [lando/lando#3438]
Possibly related but unsure: Using Laravel recipe, Compose plugin. 

I'm currently trying to configure a MinIO container (AWS S3 storage clone) using the Compose plugin. It works quite well in path-style mode where all data is accessed on a single domain, but AWS has deprecated this so I'm trying to avoid it. The alternative is "virtual server" mode which just means that the first part of the path becomes the sub-domain (i.e. http://minio:9000/bucket becomes http://bucket.minio:9000). 

When using the sub-domain style, I cannot access the MinIO container internally at any of the sub-domains. My assumption is that setting proxy configuration would help here if I define the sub-domains, but I get an error on build when I have any proxy configuration in place for the MinIO container. The error isn't particularly helpful:

```sh
> lando start
Let's get this party started! Starting app mbx...
landoproxyspacerschoiceedition_proxy_1 is up-to-date
Creating network "mbx_default" with the default driver
Creating volume "mbx_data_appserver_nginx" with default driver
Creating volume "mbx_home_appserver_nginx" with default driver
Creating volume "mbx_data_appserver" with default driver
Creating volume "mbx_home_appserver" with default driver
Creating volume "mbx_data_database" with default driver
Creating volume "mbx_home_database" with default driver
Creating volume "mbx_data_cache" with default driver
Creating volume "mbx_home_cache" with default driver
Creating volume "mbx_data_minio" with default driver
Creating volume "mbx_home_minio" with default driver
Creating mbx_minio_1 ... done
ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at Object.runBuild (/snapshot/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
From previous event:
    at /snapshot/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1847:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
Starting mbx_minio_1           ... done
Creating mbx_appserver_nginx_1 ... done
Creating mbx_appserver_1       ... done
Creating mbx_cache_1           ... done
Creating mbx_database_1        ... done
Waiting until database service is ready...
Scanning to determine which services are ready... Please stand by...
Starting mbx_minio_1 ... done
ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/plugins/lando-core/app.js
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-core/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
From previous event:
    at /snapshot/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1847:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true

  _      __              _           __
 | | /| / /__ ________  (_)__  ___ _/ /
 | |/ |/ / _ `/ __/ _ \/ / _ \/ _ `/_/ 
 |__/|__/\_,_/_/ /_//_/_/_//_/\_, (_)  
                             /___/     

Your app started up but we detected some things you may wish to investigate.
These only may be a problem.


 ■ One of your build steps failed
   This **MAY** prevent your app from working.
   Check for errors above, fix them in your Landofile, and try again by running:
   lando rebuild


 ■ The service "minio" is not running!
   This is likely a critical problem and we recommend you run the command below to investigate
   lando logs -s minio


Here are some vitals:

 NAME                  mbx                                                
 LOCATION              /home/andrew/Repos/MBx                             
 SERVICES              appserver_nginx, appserver, database, cache, minio 
 APPSERVER_NGINX URLS  https://localhost:49261                            
                       http://localhost:49263                             
                       http://mbx.lndo.site/                              
                       https://mbx.lndo.site/                             
 MINIO URLS            http://local.minio/  
```

Here is the configuration I am using. I have also tried other domains including:

- **minio.dev**, Just to test something basic, still fails
- **local.minio:9000**, 99% sure this is wrong since I want 9000:9000
- **"*.minio:9000"**, Same
- **"*.minio"**

```yaml
name: mbx
recipe: laravel
config:
  webroot: public
  php: '8.1'
  composer_version: 2
  via: nginx
  cache: redis:6
  database: postgres:13
services:
  minio:
    type: compose
    app_mount: disabled
    scanner: false
    services:
      image: 'minio/minio:latest'
      ports:
          - '9000:9000'
          - '8900:8900'
      command: minio server /data/minio --address ":9000" --console-address ":8900"
      environment:
        MINIO_ROOT_USER: 'mbx'
        MINIO_ROOT_PASSWORD: 'password'
        MINIO_DOMAIN: 'minio:9000'
    build_as_root:
      - curl https://dl.min.io/client/mc/release/linux-amd64/mc --output /usr/bin/mc
      - chmod a+x /usr/bin/mc
      - cd /data && mc mb minio/local
      - cd /data && mc mb minio/mbx-temporary
proxy:
  minio:
    - local.minio
```

Any insight would be appreciated!

**Comment by alekbless** [comment]
I'am experiencing the same stack=Error. Using laravel recipe, and Compose with a influxdb image. 

The included services like node is working, but when adding some custom with type: compose the container wont start.

```
  influxdb2:
    type: compose
    app_mount: false
    services:
      image: influxdb:2.4.0
      ports:
        - '8086:8086'
      volumes:
        # Mount for influxdb data directory and configuration
        - influxdb2:/var/lib/influxdb2
    volumes:
      influxdb2: 
```

```
Scanning to determine which services are ready... Please standby...
ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/plugins/lando-core/app.js
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-core/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
    at /snapshot/cli/lib/cli.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
```

**Comment by clementbirkle** [comment]
Hi,

Did you find a solution?

**Comment by omacha** [comment]
In case anyone is still searching, I was able to get it to work using the Bitnami image:

```yaml
name: myapp
recipe: laravel
config:
  webroot: public
  via: nginx
  php: 8.2
  database: mysql:8.0
services:
  minio:
    type: lando
    app_mount: false
    services:
      image: bitnami/minio
      command: /opt/bitnami/scripts/minio/entrypoint.sh /opt/bitnami/scripts/minio/run.sh
      environment:
        - MINIO_DEFAULT_BUCKETS=laravel #create buckets automatically
      ports:
        - 9000:9000
        - 9001:9001
      volumes:
        - minio_data:/bitnami/minio/data
    volumes: 
      minio_data:
        driver: local
    scanner:
      okCodes:
        - 200
        - 403
proxy:
  minio:
    - minio.myapp.lndo.site:9000
    - admin.minio.myapp.lndo.site:9001
```

Read up on their [documentation on Docker Hub](https://hub.docker.com/r/bitnami/minio) for more options.
