### ISSUE TITLE
Any success with setup lando with vite, default frontend framework for laravel ?

### ISSUE THREAD

**Issue by abrampl** [lando/lando#3443]
I'v tried everything, and any of this working my latest config

```yml
  node:
    type: node:16
    ssl: true
    scanner: false
    ports:
      - 3009:3009
    build:
      - npm install
    overrides:
      ports:
        - 3009 # Not sure if we need this
```

and vite.config.js

```js
server: {
		host:true,
		hmr: {
			host: 'vite.dngb.site',
			clientPort: '80',
		},
		port: 3009
	},
```

Then i run lando npm run dev, to start vite server, but without success
