### ISSUE TITLE
OpenSearch service feature request

### ISSUE THREAD

**Issue by acha5066** [lando/lando#3444]
I tried getting OpenSearch working using two compose plugins based off a sample docker-compose.yml from the official documentation [https://opensearch.org/docs/latest/opensearch/install/docker/#sample-docker-compose-file-for-development](https://opensearch.org/docs/latest/opensearch/install/docker/#sample-docker-compose-file-for-development)

``` yaml
version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.2.1
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
      - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.2.1
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards
    networks:
      - opensearch-net

volumes:
  opensearch-data1:

networks:
  opensearch-net:

```

It looks like this in lando. 

``` yaml
services:
  opensearch-node1:
    type: compose
    services:
      image: opensearchproject/opensearch:2.2.1
      command: ["./opensearch-docker-entrypoint.sh"]
      container_name: opensearch-node1
      environment:
        cluster.name: opensearch-cluster
        node.name: opensearch-node1
        bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping
        OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
        DISABLE_INSTALL_DEMO_CONFIG: "true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
        DISABLE_SECURITY_PLUGIN: "true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
        discovery.type: single-node # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
          hard: 65536
      volumes:
        - opensearch-data1:/usr/share/opensearch/data
      ports:
        - 9200:9200
        - 9600:9600 # required for Performance Analyzer
      networks:
        - opensearch-net
    volumes:
      opensearch-data1:
    networks:
      opensearch-net:
  opensearch-dashboards:
    type: compose
    services:
      image: opensearchproject/opensearch-dashboards:2.2.1
      command: [ "./opensearch-dashboards-docker-entrypoint.sh" ]
      container_name: opensearch-dashboards
      ports:
        - 5601:5601
      expose:
        - "5601"
      environment:
        OPENSEARCH_HOSTS: '["http://opensearch-node1:9200"]'
        DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true" # disables security dashboards plugin in OpenSearch Dashboards
      networks:
        - opensearch-net
``` 

Unfortunately lando seems to kill the two services immediately after starting. If I start a blank project using docker-compose and the same config from the link above it works with no issues.

Some log output from opensearch-dashboards:

```
{"type":"log","@timestamp":"2022-09-15T03:13:27Z","tags":["error","opensearch","data"],"pid":16,"message":"[ConnectionError]: getaddrinfo ENOTFOUND opensearch-node1"}
{"type":"log","@timestamp":"2022-09-15T03:13:27Z","tags":["error","savedobjects-service"],"pid":16,"message":"Unable to retrieve version information from OpenSearch nodes."}
```

It would be great to get an official OpenSearch service that we can setup as easily as the Elastic service.

**Comment by acha5066** [comment]
FYI, I was able to get a working setup using a different image from skpr. Hopefully that helps somone out: 

```yaml
services:
  opensearch:
    type: compose
    app_mount: disabled
    moreHttpPorts:
      - 9200
      - 9600
    services:
      image: skpr/opensearch:dev-v2-1.3.x
      command: "./opensearch-docker-entrypoint.sh"
      ports:
        - 9200:9200
        - 9600:9600
      environment:
        - "DISABLE_SECURITY_PLUGIN=true"
      volumes:
        - opensearch-data:/usr/share/opensearch/data
    volumes:
      opensearch-data:
  opensearch-dashboard:
    type: compose
    app_mount: disabled
    moreHttpPorts:
      - 5601
    services:
      depends_on:
        - opensearch
      image: opensearchproject/opensearch-dashboards:1.3.5
      command: "./opensearch-dashboards-docker-entrypoint.sh"
      ports:
        - 5601:5601
      environment:
        - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
        - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards

**Comment by wdrupal** [comment]
I was able to run it with the official docker compose example with next config
```
  opensearch:
    api: 3
    type: lando
    app_mount: disabled
    healthcheck: "curl -XGET localhost:9200"
    moreHttpPorts:
      - 9200
      - 9600
    services:
      image: opensearchproject/opensearch:latest
      container_name: myproject_opensearch_1
      command: './opensearch-docker-entrypoint.sh'
      environment:
        - cluster.name=opensearch-cluster # Name the cluster
        - node.name=myproject_opensearch_1 # Name the node that will run in this container
        - discovery.seed_hosts=myproject_opensearch_1 # Nodes to look for when discovering the cluster
        - cluster.initial_cluster_manager_nodes=myproject_opensearch_1 # Nodes eligibile to serve as cluster manager
        - bootstrap.memory_lock=true # Disable JVM heap memory swapping
        - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
        - "DISABLE_INSTALL_DEMO_CONFIG=true" # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
        - "DISABLE_SECURITY_PLUGIN=true" # Disables Security plugin
      ulimits:
        memlock:
          soft: -1 # Set memlock to unlimited (no soft or hard limit)
          hard: -1
        nofile:
          soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
          hard: 65536
      ports:
        - 9200:9200
        - 9600:9600
  opensearch_dasboard:
    api: 3
    type: lando
    app_mount: disabled
    moreHttpPorts:
      - 5601
    services:
      image: opensearchproject/opensearch-dashboards:latest
      command: "./opensearch-dashboards-docker-entrypoint.sh"
      ports:
        - 5601:5601
      environment:
        - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
        - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
```
