### ISSUE TITLE
Node container can't get environment variables

### ISSUE THREAD

**Issue by luispimentellopes** [lando/lando#3447]
Hi,

I'm creating a dynamic build command on the lando file, so I want to use environment variables for the folders.

```
name: test
recipe: drupal9
config:
  webroot: src/web
  php: '7.4'
services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "http://test.lndo.site"
  node:
    type: node:14
    build:
      - if [ -d $LANDO_WEBROOT/themes/custom/test/node_modules ]; then echo "Deleting node_modules folder" && rm -rf $LANDO_WEBROOT/themes/custom/test/node_modules; fi
      - echo "lando root" $LANDO_WEBROOT
      - echo "Running NPM install" && cd $LANDO_WEBROOT/themes/custom/test && npm install
      - echo "Creating NPM build" && cd $LANDO_WEBROOT/themes/custom/test && npm run gulp js && npm run gulp styles
```

This is the output of the build of node.

```
lando root
Running NPM install
/bin/sh: 1: cd: can't cd to /themes/custom/test
ERROR ==> /bin/sh: 1: cd: can't cd to /themes/custom/test 
```

It seems the node container doesn't have the environment variables set.

Thanks
