### ISSUE TITLE
Odd behavior for tooling when creating a command to run node in a service

### ISSUE THREAD

**Issue by mattsmith14** [lando/lando#3460]
**Setup**
```
name: uk-kore
proxy:
  django:
    - django.lndo.site:8000
  next:
    - nextapp.lndo.site:3000
services:
  django:
    type: python:custom
    overrides:
      image: cdk-django-deploy_local
      build:
        context: ./djangoapp
        dockerfile: ./Dockerfile
        args:
          BUILD_ENVIRONMENT: local
      user: root
      environment:
        PYTHONPATH: /app/djangoapp
        DATABASE_URL: postgres://postgres:@database.ukkore.internal:5432/django
    ssl: true
  next:
    type: node:16
    ssl: true
    overrides:
      environment:
        BACKEND_URL: https://djangoapp.lndo.site

  database:
    type: postgres:14
    portforward: true
    creds:
      user: postgres
      password: ''
      database: django

tooling:
  python:
    service: django
    cmd: python
  pip:
    service: django
    cmd: pip
  manage.py:
    service: django
    dir: /app/djangoapp
    cmd: python manage.py
  node:
    service: next
    cmd: node
    dir: /app/nextapp
  npm:
    service: next
    cmd: npm
    dir: /app/nextapp
  npx:
    service: next
    cmd: npx
    dir: /app/nextapp
  start-frontend:
    service: next
    cmd: npm run dev
    dir: /app/nextapp
  start-backend:
    service: django
    cmd: python manage.py runserver_plus 0.0.0.0:8000
    dir: /app/djangoapp
```

**Problem Description**
For the tooling entry for `node`  you receive the following error when running `lando node`:
```
/bin/sh: 1: /usr/share/lando/bin/lando: not found
```
