### ISSUE TITLE
Multiple appservers

### ISSUE THREAD

**Issue by danharper83** [lando/lando#3462]
I created a new project using `lando init` and selecting the Wordpress recipe. By default it uses NGINX and the yml file is as follows.
```
name: test-wp
recipe: wordpress
config:
  webroot: .
  via: nginx
```

When loaded these are the services
` SERVICES              appserver_nginx, appserver, database  `

It loads two appservers which makes the rest of the lando documentation difficult to use like the xdedug documentation. It always referes to appserver and it's not clear if I should be setting up xdebug on `appserver` or `appserver_nginx`.

Does this recipe need both appservers?
