### ISSUE TITLE
Lando configuration for custom service with nodejs building for gatby fails

### ISSUE THREAD

**Issue by AbhayPai** [lando/lando#3466]
Following is my configuration file for setting up gatsby project. While starting the project it gives me red color urls for proxy host. Not sure what is wrong with this setup, since development script for gatsby works just fine once it run and browser renders the url as well with the page.

Below is the screenshot while running `lando gatsby:develop` command
![Screen Shot 2022-11-03 at 1 01 23 PM](https://user-images.githubusercontent.com/14177170/199650786-285abd4c-74aa-42ae-9919-9a2f609fa440.png)

Below is the screenshot while running `lando gatsby build` command
<img width="548" alt="Screen Shot 2022-11-03 at 1 02 26 PM" src="https://user-images.githubusercontent.com/14177170/199650868-99996b3b-1c17-43bb-9434-cf619401e036.png">

![Screen Shot 2022-11-03 at 1 02 41 PM](https://user-images.githubusercontent.com/14177170/199650883-1aee9283-c080-4167-928d-21a1ba13f099.png)

```
name: gatsby-starter

config:
  webroot: public

proxy:
  custom-gatsby:
    - gatsby-starter.lndo.site

services:
  custom-gatsby:
    ssl: true
    type: node:14
    globals:
      gatsby-cli: latest
      yarn: latest

events:
  post-start:
    - custom-gatsby: "cd /app && yarn install && gatsby build"

tooling:
  yarn:
    service: custom-gatsby
  gatsby:
    service: custom-gatsby
  gatsby:develop:
    cmd: gatsby develop --host 0.0.0.0 --port 80
    service: custom-gatsby
```
