### ISSUE TITLE
Mariadb is very slow with large database compared to mysql (Drupal 8)

### ISSUE THREAD

**Issue by Asterovim** [lando/lando#3467]
- Windows 11
- Ubuntu 22.04.1 LTS (WSL)
- Lando 3.6.4
- Docker 20.10.21
- Drupal 8 (composer)

I have also try with Ubuntu 22.04 (direct install into a fresh computer) and i have the same problem.

Mariadb is very very slow with large database (more than 5gb) and my website is currently unusable.

My .lando.yml : 
```
name: mywebsitename
recipe: drupal8
excludes:
  - dump
config:
  php: "7.3"
  drush: "*"
  via: nginx
  webroot: web
  database: mariadb:10.4
  composer_version: "1.10.17"
```

If i replace mariadb by mysql : 
My .lando.yml : 
```
name: mywebsitename
recipe: drupal8
excludes:
  - dump
config:
  php: "7.3"
  drush: "*"
  via: nginx
  webroot: web
  database: mysql
  composer_version: "1.10.17"
```
i didn't have any problem with mysql and my website is very fast.

Any idea about this bug with mariadb ?
