### ISSUE TITLE
Issue connecting Lando app to Solr proxy

### ISSUE THREAD

**Issue by EthanAtDC** [lando/lando#3469]
I have been trying to connect my Lando app with Solr so that I can connect that Solr node to my Drupal 8 website.

Following this guide (https://docs.lando.dev/solr/) I've added the following lines to my ```.lando.yml``` file. This creates a healthy solr node/ proxy:
```
proxy:
  solr:
    - solr.drupal-digitalconvergence-website.lndo.site
    
services:
  myservice:
    type: solr
    portforward: 8983
    core: my-core
    config:
      dir: docroot/modules/contrib/search_api_solr/jump-start/solr7/config-set
```

The main issue I'm facing is that when creating the server on my Drupal site to connect with Solr I am continually presented with:
```
Server Connection: The Solr server could not be reached or is protected by your service provider.
```

I've followed the following documentation for the setup of said server (https://www.drupal.org/docs/8/modules/search-api-solr/search-api-solr-howtos/add-a-new-server)

Is there anything I'm missing in terms of my ```.lando.yml``` file? Or something I am over looking?
