### ISSUE TITLE
Feature Request: Apache Tika support

### ISSUE THREAD

**Issue by dnotes** [lando/lando#350]
As a lando user who works with file attachments and runs a site on Pantheon, I want the ability to debug problems with Apache Tika setup locally.

Either: 
- include Apache Tika in lando so that it is usable by default, or
- create instructions on replacing the appserver image with one that has Tika

**Comment by serundeputy** [comment]
@dnotes you should be able to add this to the `appserver` by putting this in you `.lando.yml` file:

```yml
 80 services:
 81   appserver:
 82     extras:
 83       - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -yq install libtika-java
 84       - mkdir -p /app/bin
 85       - ln -sf /usr/bin/pdftk /app/bin/libtika-java
```

I've not used Tika so i don't know how to test, but you could throw that in your `.lando.yml` and check that it installs and meets your needs.

**Comment by pirog** [comment]
nice @serundeputy, thanks for the assist here. Moving this over to the backlog because this is something we should support

**Comment by pirog** [comment]
@dnotes should have `tika` available for pantheon recipes in the next release. Until then here is some `.lando.yml` magic to get pantheon's tika running

```yaml
services:
  node:
    type: 'node:6.10'
  appserver:
    extras:
      - apt-get update -y
      - apt-get install -y openjdk-7-jre-headless
      - apt-get install -y openjdk-7-jdk
      - curl -fsSL "http://www-us.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz" | tar -xz -C /tmp
      - cd /tmp && curl -OL "http://archive.apache.org/dist/tika/apache-tika-1.1-src.zip" && unzip apache-tika-1.1-src.zip && rm apache-tika-1.1-src.zip
      - cd /tmp/apache-tika-1.1 && /tmp/apache-maven-3.5.0/bin/mvn install
      - cp -rf /tmp/apache-tika-1.1/tika-app/target/tika-app-1.1.jar /srv/bin/tika-app-1.1.jar
      - apt-get remove openjdk-7-jdk
```

you'll need to `lando rebuild` your app for this to apply.

**Comment by jimafisk** [comment]
This worked for me:
```yaml
services:
  appserver:
    extras:
      - apt update -y
      - apt install default-jre -y
      - apt install default-jdk -y
      - apt install openjdk-8-jdk -y
      - mkdir -p /app/srv/bin && cd /app/srv/bin
      - cd /app/srv/bin && curl -OL https://apache.claz.org/tika/2.0.0/tika-app-2.0.0.jar
```
