### ISSUE TITLE
Unexpected '[' in /usr/local/bin/drush/includes/startup.inc on line 63

### ISSUE THREAD

**Issue by clrockwell79** [lando/lando#3514]
I have to work with a Drupal 6 site that runs in Pantheon on PHP 5.3.  When I run `lando build` or `lando rebuild` I get the following error:

> PHP Parse error:  syntax error, unexpected '[' in phar:///usr/local/bin/drush/includes/startup.inc on line 63
> PHP Stack trace:
> PHP   1. {main}() /usr/local/bin/drush:0
> PHP   2. require() /usr/local/bin/drush:10

My config is

```
name: pkd6
recipe: pantheon
config:
  framework: drupal6
  site: redacted
  id: redacted
  xdebug: true
  config:
    php: .lando.php.ini
  drush: 5
services:
  appserver:
    type: php:5.3
    build_as_root:
      - apt-get update -y
      - apt-get install vim
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=pkd6"
```

**.lando.php.ini**
```
[PHP]
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_port=9003
xdebug.client_host=${LANDO_HOST_IP}
xdebug.log=/tmp/xdebug.log
```

Only because the error is happening within the drush folder have I tried setting `drush` to `false`, `5'`, and `6` but I keep getting the same error message after doing a `lando rebuild` each time.

I'm not sure what else to check here - any help is appreciated!
