### ISSUE TITLE
Lando app no longer rebuilds

### ISSUE THREAD

**Issue by JAyenGreen** [lando/lando#3539]
I ran into a problem today (was working yesterday) where doing a lando rebuild resulted in:
```
Creating my_appserver_1 ... done
usermod: no changes
usermod: no changes
```
and never getting further. I am running it on Mac ARM.
I found issue #3329 and created that script. No change.
I uninstalled lando and installed the latest version. No change.
I tried <ctrl>C when it gets stuck, and it continues the process and gives me 4 green URLs at the end. It also tells me that something went wrong during the build and _may_ be a problem (it is). When I tried 
`lando drush sqlc`
it crashed.

**Comment by sebastienserre** [comment]
Hello,
I've the same issue here on a WordPress recipe with lando v3.11
```
 lando rebuild --y
Rising anew like a fire phoenix from the ashes! Rebuilding app...
Killing stjean_pma_1       ... done
Killing stjean_mailhog_1   ... done
Killing stjean_redis_1     ... done
Killing stjean_database_1  ... done
Killing stjean_appserver_1 ... done
Going to remove stjean_pma_1, stjean_mailhog_1, stjean_redis_1, stjean_database_1, stjean_appserver_1
Removing stjean_pma_1       ... done
Removing stjean_mailhog_1   ... done
Removing stjean_redis_1     ... done
Removing stjean_database_1  ... done
Removing stjean_appserver_1 ... done
Pulling pma       ... done
Pulling mailhog   ... done
Pulling redis     ... done
Pulling database  ... done
Pulling appserver ... done
pma uses an image, skipping
appserver uses an image, skipping
redis uses an image, skipping
mailhog uses an image, skipping
database uses an image, skipping
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating stjean_appserver_1 ... done
usermod: no changes
usermod: no changes
```

**Comment by philltran** [comment]
I am have the same issue as well. It started with a Wordpress recipe and now cannot get any of my projects to build with proxy. Disabling proxy gets the project to build.

**Comment by AaronFeledy** [comment]
`lando rebuild -vvv` will give you verbose output and may offer some clues as to what exactly is failing.

**Comment by sebastienserre** [comment]
Hello,
Here above my landofile:
```
name: nuki
recipe: wordpress
config:
  webroot: .
  php: '8.0'
  xdebug: true
  database: mariadb
  config:
    php: ./../../php.ini
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    hogfrom:
    - appserver
tooling:
  composer:
    service: appserver
events:
  post-db-import:
    - appserver: wp search-replace "nuki-smartlock-for-wp.com" "nuki.lndo.site" --all-tables --verbose --precise
    - appserver: wp plugin update --all && wp language plugin update --all && wp theme update --all && wp language theme update --all && wp core update --force && wp language core update
```
