### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by wp-coin** [lando/lando#3547]
why am I getting this error all of a sudden?

lando.yml
```
name: metaphysicalstores
recipe: lamp
config:
  webroot: web
  php: 8.1
services:
  phpmyadmin:
    type: phpmyadmin

```

do I need to make some adjustments to ubuntu?

```
APPSERVER URLS
https://localhost:32770 [500] - REQUEST FAILED WITH STATUS CODE 500
 http://localhost:32771 [500] - REQUEST FAILED WITH STATUS CODE 500

PHPMYADMIN URLS
    ✔ http://localhost:32798 [200]

```
[v3.15.0](https://github.com/lando/lando/releases/tag/v3.15.0)
windows wsl2 ubuntu
