### ISSUE TITLE
Port mapping is not working: the port is busy but not accesible

### ISSUE THREAD

**Issue by magarzon** [lando/lando#3556]
I'm using lando in WSL2 with Windows Docker Desktop.

Last friday I updated Docker Deskop to the last version (v4.18) and the problems with the port mapping started.

I don't know if the problem is in docker, lando or both.

The problem is that the mapping doesn't seems to work correctly.

I have this configuration:

```
mongodb:
        type: compose
        portforward: 27020
        overrides:
            environment:
                MONGO_INITDB_ROOT_USERNAME: guest
                MONGO_INITDB_ROOT_PASSWORD: guest
        services:
            image: mongo:4.2.8
            restart: always
            command: docker-entrypoint.sh mongod --config /app/.lando/mongodb.conf
            ports:
                - 27020:27017
````

It seems like the port mapping is done, because I can see it in the Docker Desktop dashboard and because if I try to map any other service to that port it indicates that it's busy, but if I execute ` ss -tulpn` to see the listening ports (I'm using the Debian 11 distribution) it's not displayed in the list of listening ports, and if I try to access, even with a simple telnet command, it says connection refused.

I said at the beginning that I didn't know if the problem is in docker, lando or both, because if I execute:
`docker run -p 3366:3306 --name some-mysql14 -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql`

The mapping is done, but if I execute without the -p option, it happens the same as with lando
