### ISSUE TITLE
Document XHProf configuration.

### ISSUE THREAD

**Issue by ccharlton** [lando/lando#356]
Feature request for _XHProf_ support.

**Comment by ccjjmartin** [comment]
Looks like I was able to get this working with the Pantheon recipe (pantheon.yml `php_version: 5.6`) using these lines:
```
services:
  appserver:
    config:
      conf: config/php.ini
    extras:
      - apt-get update -y
      - apt-get install nano -y
      - pecl install xhprof-beta
      - docker-php-ext-enable xhprof-beta # This line might not be necessary but included anyway.
```
This should work without nano.

I also had to:
1) Copy the existing /usr/local/etc/php/php.ini to /app/config/php.ini
2) Edit the new php.ini to include this line: `extension=xhprof.so`
3) `lando rebuild -y`
4) `lando restart -y`

NOTE: This doesn't work unless you rebuild and then restart, not sure why.  Hope this helps someone.
