### ISSUE TITLE
Disable Scanner

### ISSUE THREAD

**Issue by spenceratwatson** [lando/lando#3566]
How do I disable the scanner with a Pantheon Wordpress setup. This is my lando setup.

```yaml
name: testname
recipe: pantheon
config:
  framework: wordpress
  site: testname
  id: ????????????????????
proxy:
  appserver_nginx:
    - testname.lndo.site
  edge_ssl:
    - testname.lndo.site
scanner: legacy
```
