### ISSUE TITLE
Make it possible to set language and locale in the recipe

### ISSUE THREAD

**Issue by yorkshire-pudding** [lando/lando#3571]
I'm working on an application that needs to use a locale other than the defaults of C and POSIX
I've attempted to add these in as build steps following instructions for ubuntu but no joy.

I've searched the docs but can't find any way to do this.

**Comment by yorkshire-pudding** [comment]
Please note that while in theory overrides should work, they are not installed and it doesn't seem possible to install them.

I tried:

```yaml
services:
  appserver:
    overrides:
      environment:
        LANG: en_GB
        LC_ALL: en_GB.utf8
```

But it can't set it as they don't exist and I haven't been able to install them and make them available to use.  My base system which is Ubuntu 20.04 on WSL2 has this locale in, but it is not made available to Lando.

**Comment by Taelkir** [comment]
Also encountering this when migrating a project from my host machine to Lando and running snapshot tests on components that have dates generated via locale in them, resulting in errors like:

```
Expected: ""<span>1 Jan 2025</span>""
Received: ""<span>Jan 1, 2025</span>""
```

**Comment by yorkshire-pudding** [comment]
@Taelkir - if it helps you (and anyone else that finds this), this is what I ended up doing:

```yaml
services:
  appserver:
    run_as_root:
      - apt-get update && apt-get install -y locales-all
```

And it worked for my use case.
