### ISSUE TITLE
Unable to import database(.sql) to alternative database within single database service

### ISSUE THREAD

**Issue by markdorison** [lando/lando#3573]
Apologies for the confusing title!

I am trying to run a multi-site on Lando using a single database service. To date, we have used [Lando's recommended approach of creating a separate database service for each of the sites](https://docs.lando.dev/drupal/drupal-multisite.html), but with 21 sites and growing, this is causing performance issues. I would like to see if running a single database _service_, with multiple databases within it would offer better performance.

[Lando's db-import documentation](https://docs.lando.dev/guides/db-import.html#examples) examples mention importing into an "auxiliary" database, but this does not seem to work. Is this supported? Could it be?

```
# Import a file into an auxiliary second database called 'db2'
# with a db called `dataz`
lando db-import dump.zip --host db2
```

**Comment by millnut** [comment]
Hi @markdorison I think the docs are wrong and the command should be;

```bash
lando db-import dump.zip --host=db2
```

**Comment by millnut** [comment]
Ah I understand so a single service with multiple databases; I don't think you can do it out of the box but may be able to achieve it with a run step?

```yaml
services:
  database:
    type: mariadb
    creds:
        user: mariadb
        password: mariadb
        database: database
    run:
      # Creates the extra databases as root since the app user does not have those privileges
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS db1; GRANT ALL PRIVILEGES ON db1.* TO 'mariadb'@'%' IDENTIFIED by 'mariadb';"
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS db2; GRANT ALL PRIVILEGES ON db2.* TO 'mariadb'@'%' IDENTIFIED by 'mariadb';"
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS db3; GRANT ALL PRIVILEGES ON db3.* TO 'mariadb'@'%' IDENTIFIED by 'mariadb';"
```
