### ISSUE TITLE
Cannot override nginx port - "port is already allocated" error

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#359]
Bug Report
==========

*This may be a [Docker bug](https://github.com/docker/compose/issues/3277#ref-issue-256793112) but I am reporting it here because it affects lando.*

Windows 10 Pro, lando 3.0-beta 17
Also happens on OS X-- in this report, I am giving details for Windows, but I can provide details on OS X as well if needed

**Problem**

When I try to override the port for nginx in `.lando.yml`, I get a `port already allocated` error when I run `lando start`.

* This issue may be a [Docker bug](https://github.com/docker/compose/issues/3277#ref-issue-256793112)-- however, the solutions suggested in the thread (restart Docker, reset Docker to factory defaults) did not work for me.  As noted in the thread, this affects Mac + Windows, and I have experienced the problem on both OSes.
* This happens regardless of which port I use (I tried "777", "1234", "7777", "8000", and others.
* These ports are NOT already allocated.  I verified this by using `netstat -an` from a Powershell run as admin and by using the [TCPView](https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview) software to check what is running on which port.  When I run `lando poweroff`, the specified port is not in use.  When I run `lando start`, the port in `.lando.yml` comes into use by the process `vpnkit.exe`, which is part of docker.
* I can override the `database` and `mailhog` ports without trouble; it's just nginx/appserver that causes this problem.

What appears to be happening is that when docker/lando tries to assign the port, it does lock the port (vpnkit.exe starts using the port) but it is unavailable to the appserver container and gives the "already allocated" error.

**Config details**

Using a Pantheon recipe, `.lando.yml`:

```
name: mysite
recipe: pantheon
config:
  framework: drupal8
  xdebug: true
  env: dev
  site: mysite
  id: 1234
  webroot: web/

# Additional mailhog proxy settings so we get a nice URL for the mailhog ui
proxy:
  mailhog:
    - mail.mysite.lndo.site

services:
  mailhog:
    # Use the latest mailhog version
    type: mailhog
    # List of services that we want to capture mail from
    # You can run `lando info` to get a list of services that are available
    # Mailhog expects that these services will be php services
    hogfrom:
      - appserver
    # Make sure port 1026 is open on your machine
    portforward: 1026
  database:
    portforward: 3306
  appserver:
    extras:
      # !! Commands run as ROOT.  Don't fuck it up.
      - "apt-get update -y"
      - "apt-get install vim -y"
      # Use custom settings.local.php; needs to be copied because we want a master under version control.
      - "cp /app/web/sites/default/lando.settings.local.php /app/web/sites/default/settings.local.php"
    overrides:
      services:
        ports: ['777:80']

tooling:
  behat:
    service: appserver
    description: Run behat tests locally.
    cmd:
      - /app/vendor/bin/behat
```

This is the error I get:

```
ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint edosensei_nginx_1 (6027be6e2ff004d2b5cdc09315ec4c113ce9b2e2557131971f607d45fd15c0d5): Bind for 0.0.0.0:777 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```
