### ISSUE TITLE
Selenium Chrome and Firefox Support for Behat

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#360]
Feature/Enhancement Request
===========================

As a lando user who tests Drupal using Behat, I want to run the tests through a real browser because I want to test the effects of CSS and Javascript.

The selenium project has a [chrome standalone image](https://hub.docker.com/r/selenium/standalone-chrome/) for docker.  There's also one for [firefox](https://hub.docker.com/r/selenium/standalone-firefox/).

I want to integrate this with Lando because [apparently you can configure it to watch the browser tests being carried out live](http://docs.docksal.io/en/latest/tools/behat/).

I'm willing to try to work on this myself.  I looked through the docs and it seems I need to write a new service using the `selenium/standalone-chrome` as the base image, is that correct?  Or is there an easier way?

**Comment by ptmkenny** [comment]
I haven't figured out how to get this working through lando itself, but here's how to do it with Docker on Windows (should work on other platforms too, but not tested).

This example uses Chrome debug.  I chose the "debug" image because it has a built-in VNC server which allows you to watch the tests live.

First, start the container in docker:

`docker run -d -p 4444:4444 -p 5900:5900 selenium/standalone-chrome-debug`

Port `4444` is for selenium server and `5900` is for VNC.  These ports need to be open, check with `netstat -ab` from cmd.exe run as Admin if you aren't sure.

Next, you need to configure the `.behat.yml` for your tests or the behat variables in `.lando.yml`.

The relevant part is this:

```
  extensions:
    Behat\MinkExtension:
      default_session: selenium2
      goutte: ~
      base_url: 'http://YOUR_MACHINE_IP:LANDO_APPSERVER_PORT_NUMBER'
      selenium2:
        wd_host: 'http://YOUR_MACHINE_IP:4444/wd/hub'

```

You will need to use the IP address of the machine on the local network.  You can get this from `ipconfig /all` run from cmd.exe as an Admin. Make sure to use the ip4 address for your local network, not for DockerNAT (the correct IP should be like 192.168...)

Also, you need to substitute the lando appserver port number, which you can get from `lando info` and then looking for the `http` port number for `appserver`.

Now you need to connect with VNC to watch the tests.  Windows doesn't have a built-in VNC viewer, so I used the open-source TightVNC.  Launch TightVNC viewer.

For the remote host, input `YOUR_MACHINE_IP:5900` and press *Connect*.  For the password, use *secret*.

Now you can run your tests with `lando behat` and watch them succeed (or *cough*, fail) before your eyes.

**Comment by shaundrong** [comment]
@ptmkenny We're working on the same problem, but like you I need to spend a bit more time reviewing the Lando plugin service code examples before diving into adding one for selenium. 
I would suggest maybe adding a few more params to the `docker run` to help setup it up in Lando's network.
- find bridge network lando added for your site: `docker network ls`
``` bash
docker run --name -h browser --network DOCKER_BRIDGE_NETWORK_NAME_FOR_LANDO_SITE --add-host=LANDO_EDGE_URL_HOSTNAME: YOUR_MACHINE_IP" -d -p 4444:4444 -p 5900:5900 selenium/standalone-chrome-debug
```
- Then you should be able to use lando urls in the behat config vs Host machine's IP
``` yml
 extensions:
    Behat\MinkExtension:
      default_session: selenium2
      goutte: ~
      base_url: 'http://LANDO_EDGE_URL_HOSTNAME:LANDO_APPSERVER_PORT_NUMBER'
      selenium2:
        browser: chrome
        wd_host: 'http://LANDO_EDGE_URL_HOSTNAME:4444/wd/hub'
```
> Note: I needed to add the `browser:chrome` setting let the mink know it was Chrome vs the default Firefox.

**Comment by aaron-capellic** [comment]
@ptmkenny @shaundrong  Did either of you get this working well? I'd love to learn more if so. Thanks.

**Comment by dustinleblanc** [comment]
Hey Folks! The way to do this right now is as follows:

```yml
name: coolProject
compose:
  - docker-compose.yml
```

And said docker-compose.yml:
```yml
version: '3'

services:
  chromedriver:
    image: robcherry/docker-chromedriver:latest
    expose:
      - "4444"
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
      CHROMEDRIVER_URL_BASE: "/wd/hub"
    security_opt:
      - seccomp:unconfined
```

Your behat config looks like:

```yml
  extensions:
    Behat\MinkExtension:
      files_path: "%paths.base%/features/fixtures/"
      base_url: https://nginx/
      browser_name: chrome
      sessions:
        default:
          goutte:
            guzzle_parameters:
              verify: false
        javascript:
          selenium2:
            wd_host: http://chromedriver:4444/wd/hub
```

I stole this from my discussion with @aaron-capellic on the topic based on the work both of us had done to support this in our apps. 

At a future date we should add Chromedriver as a service though so I'll keep this in carbonite

**Comment by sherakama** [comment]
For those using apache you can replace `nginx` with `appserver` for more parts. Example .lando.yml:

```
name: chromewithapache
recipe: drupal7
services:
  appserver:
    ssl: true
    via: apache
    overrides:
      services:
        environment:
            BEHAT_PARAMS: >-
              {
                "extensions" : {
                  "Behat\\MinkExtension" : {
                    "base_url" : "http://appserver/"
                  }
                }
              }
  database:
    type: mysql:5.7
  chromedriver:
    type: compose
    services:
      image: robcherry/docker-chromedriver:latest
      expose:
        - "4444"
      environment:
        CHROMEDRIVER_WHITELISTED_IPS: ""
        CHROMEDRIVER_URL_BASE: "/wd/hub"
      security_opt:
        - seccomp:unconfined
      command: ["/usr/local/bin/supervisord", "-c", "/etc/supervisord.conf"]
tooling:
  behat: 
    ....
```

And in your behat.yml file: 
```
default:
  extensions:
    Behat\MinkExtension:
      base_url: http://appserver/
```

**Comment by Tigatok** [comment]
Have this working locally, here is my full setup

behat.yml:
```YAML
default:
  autoload:
    - '%paths.base%/tests/features/bootstrap'
  suites:
    default:
      failure_path: '%paths.base%/tests/failures'
      paths:
        features: '%paths.base%/tests/features'
      contexts:
        - FailureContext
        - FeatureContext
        # Support BigPipe in Behat - https://github.com/jhedstrom/drupalextension/pull/325
        # Modified to not require Drupal driver.
        - BigPipeContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      # Default configuration has this commented out so it can be overidden.
      base_url: https://drupal8.lndo.site/
      browser_name: chrome
      sessions:
        default:
          goutte:
            guzzle_parameters:
              verify: false
        javascript:
          selenium2:
            wd_host: http://chromedriver:4444/wd/hub
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drush'
      drush:
        alias: '@local'
        binary: './bin/drush'
      region_map:
        # redacted
```

drush/local.site.yml
```YAML
local:
  root: /app/web
  uri: https://drupal8.lndo.site
```

.lando.yml
```YAML
name: drupal8
recipe: drupal8
services:
  appserver:
    overrides:
      services:
        environment:
          MINK_DRIVER_ARGS: '["chrome", null, "http://chromedriver:4444/wd/hub"]'
          MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", null, "http://chromedriver:4444/wd/hub"]'
          MINK_DRIVER_CLASS: 'Drupal\FunctionalJavascriptTests\DrupalSelenium2Driver'
          SIMPLETEST_DB: 'mysql://drupal8:drupal8@database/drupal8'
          SIMPLETEST_BASE_URL: 'https://drupal8.lndo.site/'
          PHP_IDE_CONFIG: "serverName=appserver"
          BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://appserver/"}, "Drupal\\DrupalExtension" : {"drush" :   {  "root":  "/app/web" }}}}'
  chromedriver:
    type: compose
    services:
      image: robcherry/docker-chromedriver:latest
      expose:
        - "4444"
      environment:
        CHROMEDRIVER_WHITELISTED_IPS: ""
        CHROMEDRIVER_URL_BASE: "/wd/hub"
      security_opt:
        - seccomp:unconfined
      command: ["/usr/local/bin/supervisord", "-c", "/etc/supervisord.conf"]
tooling:
  behat:
    service: appserver
    description: "Run behat stuff"
    cmd:
      - /app/bin/behat
  chromedriver:
    service: chromedriver
    description: "Run chromedriver commands."
config:
  via: nginx

  webroot: web

  xdebug: true

  database: mariadb:10.1
```

**Comment by brooke-heaton** [comment]
I'm a bit confused on `via: nginx`. What does this due?

**Comment by dustinleblanc** [comment]
@brooke-heaton `via: nginx` makes a PHP service boot an Nginx container for it's webserver instead of running apache

**Comment by ataylorme** [comment]
I got Behat with the [Headless Chrome Driver](https://gitlab.com/DMore/behat-chrome-extension) working inside Lando.

Rather than create a new service I just did an override on `appserver` (I'm using the Pantheon recipe) to use my [custom Dockerfile](https://github.com/ataylorme/docker-php-Advanced-WordPress-on-Pantheon/blob/headless-chrome-lando/Dockerfile). All the Dockerfile does is start with the base Lando Dockerfile (`FROM devwithlando/pantheon-appserver:7.2-fpm`) and installs Headless Chrome.

I then download and install Behat and the Headless Chrome Driver with Composer as dev dependencies.

It runs full JavaScript and is fast. I have not tried Selenium in Lando but thought I would share this as another potential solution to Behat w/ JavaScript in Lando.

You can see the repo with the entire codebase (minus the Dockerfile linked above) [here](https://github.com/ataylorme/Advanced-WordPress-on-Pantheon/tree/give-wp).

It is a WordPress project but the WordPress Behat driver could easily be swapped for Drupal.

**Comment by edurenye** [comment]
I think this would still be nice to have in as a feature in the future.

**Comment by thursdaybw** [comment]
No idea why this is closed. The op requested how to get https://hub.docker.com/r/selenium/standalone-chrome/ working.. The solutions presented use different images.

I'm trying to get that image working too. THAT image, not some other one.
I'm attempting to setup selenium/standalone-chrome-debug in lando as a compose type service.
i'm a bit stumped.
I have a working docker-compose file like so:
version: "3"
services:
  chrome:
    image: selenium/standalone-chrome-debug
    network_mode: host
    environment:
      - TZ=Australia/Darwin
    deploy:
      resources:
        reservations:
          cpus:   '150m'
          memory: '256Mi'
        limits:
          cpus:   '150m'
          memory: '256Mi'
    volumes:
      - /dev/shm:/dev/shm
And my lando like so:
name: tmp
recipe: drupal8
services:
  chrome:
    type: compose 
    services:
      image: selenium/standalone-chrome-debug
      environment:
        - TZ=Australia/Darwin
      volumes:
        - /dev/shm:/dev/shm
The docker compose works.. the lando fails on build with
Starting tmp_chrome_1 ... done
ERROR: No container found for chrome_1
error: Looks like chrome is not running! It should be so this is a problem.
warn: Try running `lando logs -s chrome` to help locate the problem!
The logs are as unhelpful as ever..
15:18
 lando logs -s chrome
Attaching to cdu_chrome_1
chrome_1     | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
chrome_1     | mkdir: cannot create directory '/etc/ssh': Permission denied
chrome_1     | Running command 
chrome_1     | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
chrome_1     | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
chrome_1     | mkdir: cannot create directory '/etc/ssh': Permission denied
chrome_1     | Running command
15:19
I'm not sure what to do next.. the chmod errors I see everytime I look at lando logs.. I don't recall looking at lando logs any time in the past 6 or so months where it wasn't full of that.
`

**Comment by thursdaybw** [comment]
Update.. made progress.

I figured out the entrypoint and so set that as the comand like so:
`  chrome:
    type: compose 
    services:
      image: selenium/standalone-chrome-debug
      environment:
       - TZ=Australia/Darwin
      volumes:
       - /dev/shm:/dev/shm
      ports:
        - '4444'  
        - '5600'
`

Now the services starts. woot. however:

I can access it from inside the container using the internal hostname
eg: (after installing telnet)
`root@92f73a728294:/app# telnet chrome.tmp.internal 4444
Trying 172.18.0.11...
Connected to chrome.tmp.internal.
Escape character is '^]'.`


However I don't know how to access this from outside the container.. specifically the 5600 port which is for the vnc protocol.

**Comment by dustinleblanc** [comment]
It was closed because it was a two-year-old issue that went stale. That said, I've made use of the Selenium standalone firefox container more than once. Here is a setup I did for a presentation at BadCamp: https://github.com/TibanaDev/tibana-drupal/blob/master/.lando.yml#L15

My setup isn't exposing any VNC debugging ports, but that might give you some help with the permissions issue. This is more of a guide / how do I do nifty things with Lando question, so the potential outcome is probably a guide for our [new Guider program](https://docs.lando.dev/contrib/guides-add.html) so if you get it going to your liking, I suggest following up with that!

**Comment by thursdaybw** [comment]
Awesome.
I had some good success moments after I posted this.
I think my previous comments code example is wrong I need to fix it up, but have a couple other dev env hurdles to fix before I update this.

Thanks for you example. I post mine here shortly.

**Comment by thursdaybw** [comment]
OK. I have it working now. Not exactly how I wanted but it works.

My lando setup sing selenium/standalong-chrome-debug (using debug because I want vnc).

```
 chrome:
    type: compose
    services:
      image: selenium/standalone-chrome-debug
      #image: selenium/standalone-firefox-debug
      environment:
        TZ: Australia/Darwin
        START_XVBF: 'false'
      volumes:
        - /dev/shm:/dev/shm
      command: /opt/bin/entry_point.sh
      ports:
        - '4444:4444'
        - '5900:5900'
```
That's the service itself.
I can access that from the host with, for example:
```
telnet tmp.lndo.site 4444
```

However form inside the container that domain isn't listening on that port.
```
telnet tmp.lndo.site 444 #inside the container gets connection refused.
telnet chrome.tmp.internal 4444 # can connect.
```

Which means I need to set that internal host name in mink config. I'd rather no do this.

I've tried configuring the proxy to resolved this so I added
```
proxy:
  chrome:
  - cdu.lndo.site:4444
```
The difference I see now is after starting lando, The chrome services URLs are printed now. But they're the same as the appserver:

```
Here are some vitals:

 NAME            tmp                                             
 LOCATION        /workspace/tmp        
 SERVICES        appserver, database, chrome 
 APPSERVER URLS  https://localhost:32985                         
                 http://localhost:32986                          
                 http://tmp.lndo.site                            
                 https://tmp.lndo.site                           
                 http://tmp.lndo.site                            
                 https://tmp.lndo.site                           
 CHROME URLS     http://tmp.lndo.site                            
                 https://tmp.lndo.site                           
                 http://tmp.lndo.site                            
                 https://tmp.lndo.site
```
And i'm still unable to connect to selenium via the external domain from inside the container, I'd prefer to be able to keep the mink configuration consistent with other projects.

I'm not sure what I need to do from here to resolve this final little issue.

I'm also using drupal test traits, so I'm going to show the settings in phpunit.xml for mink in case someone else is in the same situation of drupal test traits, mink and selenium in lando.
```
    <env name="DTT_BASE_URL" value="http://tmp.lndo.site"/>
    <!-- See \weitzman\DrupalTestTraits\WebDriverSetup -->
    <env name="DTT_MINK_DRIVER_ARGS" value='["chrome", { "chromeOptions": { "w3c": false } }, "http://chrome.tmp.internal:4444/wd/hub"]'/>
```
Note the internal domain in the mink config.

**Comment by pirog** [comment]
@dustinleblanc 👍 for this being a guide. i think this is exactly the kind of thing we want to get in there!

**Comment by dustinleblanc** [comment]
@thursdaybw using the internal host information is how I've always done it. It is more reliable than whatever proxy based domain you use. You also don't want to assign the same proxy url for the appserver to the chrome service, they should be different domains. Use something like `chrome-appname.lndo.site`. When you map a port like:
```yml
proxy:
  something.lndo.site:3000
```

You actually map port 3000 inside the container to port 80/443 on the host, so you are colliding your appserver and chrome mappings on the proxy.

**Comment by kerasai** [comment]
Not the same as the original question/issue, but I spent some time digging through the Lando and docker setup to find a way to run Behat using the [Chrome extension](https://packagist.org/packages/dmore/behat-chrome-extension), which connects directly to Chrome instead of using connecting via Selenium.

@dustinleblanc 's gist using Pantheon's build tools worked 💯 

https://gist.github.com/dustinleblanc/8d941565ed326126a5f6ccc472f14f4c

**Comment by husim0** [comment]
If you need a working example of behat+selenium+novnc check my `.lando.yml` : 

```yaml
name: xxx
recipe: lemp
config:
  webroot: web
  database: postgres:10
services:
  appserver:
    type: php:7.3
    via: nginx:1.18
    composer_version: '2.0.7'
    xdebug: true
    overrides:
      environment:
        BEHAT_PARAMS: |-
          {
            "extensions":{
              "Behat\\MinkExtension":{
                "selenium2":{
                  "browser": "chrome",
                  "wd_host": "selenium-chrome:4444/wd/hub",
                  "capabilities": {
                    "marionette": null,
                    "browserName": "chrome",
                    "browser": "chrome",
                    "chrome": {
                      "switches": [
                        "--disable-gpu",
                        "--window-size=1280,720",
                        "--no-sandbox",
                        "--disable-web-security",
                        "--disable-extensions",
                        "--start-maximized"
                      ]
                    }
                  }
                },
                "default_session":"selenium2"
              }
            }
          }
  selenium-chrome:
    type: compose
    app_mount: false
    services:
      # Chrome 74
      # Feed free to use a newer image
      image: selenium/standalone-chrome-debug:3.141.59-neon
      environment:
        TZ: Europe/Paris
        START_XVBF: 'false'
      volumes:
        - /dev/shm:/dev/shm
      command: /opt/bin/entry_point.sh
  novnc:
    type: compose
    app_mount: false
    services:
      image: bonigarcia/novnc
      command: sh /root/noVNC/utils/launch.sh --vnc selenium-chrome:5900 --listen 8888
      ports:
        - '8888:8888'
tooling:
  behat:
    service: appserver
    cmd: "/app/vendor/bin/behat --config '/app/behat.yml'
```

And then you can access to novnc at http://localhost:8888/vnc.html?password=secret&autoconnect=1&view_only=true and launch behat using `lando behat`.
