### ISSUE TITLE
Rewrite rule doesn't work when file with the same name exists

### ISSUE THREAD

**Issue by MichelJonkman** [lando/lando#3601]
I have files test1.php and test2.php.

```
RewriteEngine On
RewriteRule ^test/ test.php [L] # Doesn't work
RewriteRule ^test/1/ test.php [L] # Doesn't work

RewriteRule ^test3/ test2.php [L] # Works
RewriteRule ^test3/1/ test2.php [L] # Works
```

landofile
```
  app:
    type: php:7.4
    via: apache
    ssl: true
    sslExpose: true
    webroot: ./app/public_html
```

Note that this does work on the server I'm using Apache on
