### ISSUE TITLE
Add documentation how to use the YAML merge key (example supplied)

### ISSUE THREAD

**Issue by silverham** [lando/lando#3602]
YAML merge works in lando.yml file.
We should document this on [lando.dev](https://docs.lando.dev/).

Example of merge working in lando/yml file:

**Merged version**
```yml
name: my-drupal9-project
recipe: drupal9
x-php-version: &php-version '8.1'
x- nested-config-wrapper: &nested-config-wrapper
  config:
    php: lando-config/php.ini
config:
  php: *php-version
  << : *nested-config-wrapper
```
**Equivalent**
```yml
name: my-drupal9-project
recipe: drupal9
config:
  php: '8.1'
  config:
    php: lando-config/php.ini
```

**More information**
[Merge Key Language-Independent Type for YAML™ Version 1.1](https://yaml.org/type/merge.html)
[Lando Drupal Drupal Configuration](https://docs.lando.dev/drupal/config.html)
[Sample online YML parser - codebeautify](https://codebeautify.org/yaml-parser-online)
[Sample online YML parser - appspot](https://yaml-online-parser.appspot.com/)
