### ISSUE TITLE
Lando Fails to Start without More Info

### ISSUE THREAD

**Issue by ColeyG** [lando/lando#3613]
After starting with `lando start -y` or `lando rebuild -y`, my instance hangs and I get no response past what I've attached below

```
name: test
recipe: drupal8
config:
  webroot: ./web
  php: 8.1
services:
  database:
    type: mysql:5.7
    portforward: true
    creds:
      user: myuser
      password: mypassword
      database: mydatabase
```

```
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
ERROR ==> database reported as unhealthy. 
ERROR ==> Error: (HTTP code 404) no such container - No such container: landoproxyhyperion5000gandalfedition_proxy_1  
```

The database instance seems healthy:

2023-09-28T20:49:14.950068Z 0 [Note] /opt/bitnami/mysql/bin/mysqld: ready for connections.
