### ISSUE TITLE
Composer does not work anymore

### ISSUE THREAD

**Issue by MatthiasBrodelet** [lando/lando#3625]
I have been using Lando for years now without too much issues but now I seem to have hit a rather weird bug.
When running `lando composer install` I get the following message:
_You must set up the project dependencies using `composer install`
See https://getcomposer.org/download/ for instructions on installing Composer_

This is my lando file:
```
name: the-house-webshop
recipe: lamp
config:
    webroot: web
    php: 8.1
    database: mysql

services:
    database:
        type: mysql
    pma:
        type: phpmyadmin
        hosts:
            - database
```
            
I have uninstalled and reinstalled Lando and Docker. I also downgraded both Lando and docker but the issue persists.
I'm running on MacOS with M1 Pro.

What is the cause of this issue and how can it be fixed?

Update: It seems that `lando composer` only works when there is a composer.lock file. This seems kind of annoying because all I wanted to do was `lando composer install`
