### ISSUE TITLE
Cannot find file via tool script after latest update

### ISSUE THREAD

**Issue by sinnbeck** [lando/lando#3627]
I just updated to use the latest version of Lando. I have a script for importing a backup of my lastest database dump which no longer works.

![image](https://github.com/lando/lando/assets/13980140/db6a36af-ba19-4c1b-8b22-d63ccc192a30)

The script is just this
```bash
#!/bin/bash
DATE=`/bin/date +%Y-%m-%d`
FILENAME="intranet-"$DATE".sql.gz"

if [ "$1" != "" ]
then
    FILENAME=$1
fi

echo "Importing $FILENAME"
/helpers/sql-import.sh  $FILENAME
```
and the tooling
```yml
  import-db:
    cmd:
      - database: /app/scripts/import-db.sh
 ```
 If i ssh into the database container and run the script directly it works just fine.
