### ISSUE TITLE
Error "drupal8 is not a supported recipe type" after upgrading lando from 3.20.6 to 3.20.7

### ISSUE THREAD

**Issue by WebBeest** [lando/lando#3645]
After upgrading lando to 3.20.7 from 3.20.6 I get the following error when doing a `lando rebuild -y`

WARN ==> drupal8 is not a supported recipe type.
ERROR ==> Could not find a service builder called drupal8 in the builder registry!

The recipe is drupal8, I've also tried drupal10 (since the project has been upgraded in the meantime) but to no result.

Lando file:
```
name: myproject
recipe: drupal8
config:
  php: '8.1'
  composer_version: '2.6.5'
  via: apache
  database: mysql
  drush: ^8
  xdebug: false
  webroot: web
```
System: Ubuntu 22.04.3 LTS
Docker 24.0.7, build afdd53b
