### ISSUE TITLE
Lando `v3.21.0-alpha.10` sees the Docker version as unsupported, even though it falls in the supported range

### ISSUE THREAD

**Issue by alessandro-newzoo** [lando/lando#3657]
Hello 👋 

Lando `v3.21.0-alpha.10` complains about Docker `24.0.7-1` not being supported, even though it falls in the `>=18 <25` range:

```
  Using an unsupported version of DOCKER ENGINE
  You have version 24.0.7-1 but Lando wants something in the >=18 <25 range.
```

As far as I know, `24` is higher than `18`, and lower than `25` 😄

---
**devcontainer.json:**
```json
{
  "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
  "features": {
    "docker-in-docker": "latest",
    "lando/lando-dev-container-feature/landodevcontainer": "latest"    
  }
}
```
**.lando.yml:**
```yaml
name: newzoo
recipe: wordpress

config:
  webroot: wordpress
  via: apache:2.4
  php: "8.2"
  database: mariadb:10.4

services:
  appserver:
    ssl: false
  node:
    type: node:16
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database

events:
  pre-start:
    - node: echo -e "\e[36mRunning npm install...\e[0m"
    - node: cd wordpress/wp-content/themes/newzoo && npm i --no-progress --silent --no-fund
    - appserver: echo -e "\e[36mRunning composer install...\e[0m"
    - appserver: cd wordpress/wp-content/themes/newzoo && composer install --no-progress --no-interaction --no-dev --optimize-autoloader

tooling:
  npm: # lando npm
    service: node
  node: # lando node
    service: node
```

Thank you!
