### ISSUE TITLE
Lando v3.20.8 - ERROR ==> php version 8.1.22 is not supported

### ISSUE THREAD

**Issue by gurvindersinghusda** [lando/lando#3659]
Hi, I have Lando v3.20.8 installed in local environment. This is for a Durpal 10 project and I am trying to get PHP 8.1.22 installed.  

Here is my .lando.yml file

```
name: test
recipe: drupal9
config:
  via: apache
  webroot: web
  php: 8.1.22
  xdebug: true
  conf:
    mysql: lando/config/my.cnf
    php: lando/config/php.ini

proxy:
  drupal-solr:
    - search.test.lndo.site:8983
  pma:
    - pma.test.lndo.site
  mailhog:
    - mail.test.lndo.site

services:
  drupal-solr:
    type: solr:8.4
    portforward: true
    core: collection1
    config:
      dir: solr-conf
  pma:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    composer:
      phpunit/phpunit: 8
      behat/behat: 3.3.1
    run:
      - "ln -s /usr/local/bin/composer /usr/local/bin/composer.phar"
    run_as_root:
      - "bash /app/lando/scripts/build.sh"
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
        LANDO_HOST_IP: "host.docker.internal"
        DRUSH_OPTIONS_URI: "http://test.lndo.site"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

tooling:
  composer:
    service: appserver
    description: run composer commands
    cmd: /usr/local/bin/composer
  drush:
    service: appserver
    description: run drush commands
    cmd: /app/vendor/drush/drush/drush
  phpunit:
    service: appserver
    description: run PHPUnit- use lando phpunit
  behat:
    service: appserver
    description: run behat- use lando behat
    cmd: cd /app ; behat  # Run behat from the /app  directory
  mailhog:
    service: mailhog
```

when doing `lando rebuild`, I get the following error:- `ERROR ==> php version 8.1.22 is not supported`

If I change the file to have `php: 8.1` then it installs `PHP 8.1.18` 

For my project; however, I need to have `PHP 8.1.22` installed. Any help is appreciated.
