### ISSUE TITLE
[Help] Setting up Nextjs project

### ISSUE THREAD

**Issue by Aniket-IN** [lando/lando#3664]
Hi 👋, 

First of all, thank you so much for this Amazing tool 🙏
I'm new to Lando, was trying to setup a `Nextjs` project for development.
Couldn't find any docs/blog for configuring Nextjs with Lando. 

I did try this config:
```yml
name: next-app
services:
  node:
    type: node:18
    ssl: true
    build:
      - npm install
    command: npm run dev

proxy:
  node:
    - next-app.lndo.site:3000

tooling:
  npm:
    service: node
  npx:
    service: node
```

It does open the app on `next-app.lndo.site`, 
but when I edit some file it doesn't reflect the changes in the app. 
Hot Module Reload and manual refresh nothing works.

Only rebuilding, reflects the changes.
Not sure, what I'm missing. 😓
