### ISSUE TITLE
Lando fails to run or build

### ISSUE THREAD

**Issue by EsliManta** [lando/lando#3667]
Hello, 

I just updated lando to v3.21.0-beta.1 and now whenever I try to run my symfony + mssql project, the following error arises `ERROR ==> Could not find a service builder called symfony-mssql in the builder registry!`. This error occurs both when running `lando start` and `lando rebuild`

I have ran `lando setup` and `lando update` however they both report no additional setup is required.

Here is a `.lando.yml` file for reproducing:

```
name: symfony_mssql
recipe: symfony
config:
  php: 8.1
  via: nginx
  webroot: public
  database: mssql:2019-latest
  xdebug: 'develop,debug,profile'
```

Any help greatly appreciated :pray:
