### ISSUE TITLE
healthcheck  Access denied to database(s)

### ISSUE THREAD

**Issue by zdenekgebauer** [lando/lando#3684]
I have a .lando.yml file configured as follows:
```
name: testlando
recipe: lamp
config:
    webroot: www
    database: mariadb:10.3
proxy:
    appserver:
        - www.testlando.local
    phpmyadmin:
        - phpmyadmin.local
services:
    appserver:
        type: php:8.2
        scanner: false
    database:
        scanner: false
        creds:
            user: testlando
            password:
            database: testlando            
    phpmyadmin:
        type: phpmyadmin
        scanner: false
        hosts:
            - database
```

Command ``lando start`` writes error:
```
[+] Healthchecking 1/1
 × ERROR 1045 (28000): Access denied for user 'testlando'@'172.23.0.3' (using password: YES)
ERROR ==> ERROR 1045 (28000): Access denied for user 'testlando'@'172.23.0.3' (using password: YES)
```
However, despite the error, phpMyAdmin can access the database, and the user testlando exists.  Error  occurs even with a MySQL database.

Shouldn't the healthchecking be skipped with the option ```scanner:false```?

Tested on v3.21.0-beta.7,  Windows 10, Docker Desktop version 4.27.2
