### ISSUE TITLE
"Unsupported config option for services" after update

### ISSUE THREAD

**Issue by alex-r-redfern** [lando/lando#3707]
Lando version: v3.21.0-beta.15
Host: Ubuntu/Mint - Linux 6.5.0-27

Issue: After updating Lando core, rebuilds and destroys all fail. Manually deleting containers/images/volumes in docker does not resolve this, nor does manually removing configuration files in ~/.lando/compose. The projects all started / rebuild successfully prior to this update.

Terminal output:
```
lando destroy -yv
  lando loading app projectnamehere from config files 0=/media/alex/Data/projectnamehere/.lando.yml +411ms
  lando loading app projectnamehere from config files 0=/media/alex/Data/projectnamehere/.lando.yml +426ms
Preparing to consign projectnamehere to the dustbin of history...
  projectnamehere destroying app...  +1ms
  projectnamehere stopping app...  +103ms
ERROR: The Compose file '/home/alex/.lando/compose/projectnamehere/globals-0.yml' is invalid because:
Unsupported config option for services: 'database'
  lando ERROR Error
    at /home/alex/.lando/plugins/@lando/core/lib/shell.js:158:44
From previous event:
    at Shell.sh (/home/alex/.lando/plugins/@lando/core/lib/shell.js:150:6)
    at dc (/home/alex/.lando/plugins/@lando/core/utils/setup-engine.js:6:16)
    at compose (/home/alex/.lando/plugins/@lando/core/utils/setup-engine.js:26:35)
    at /home/alex/.lando/plugins/@lando/core/lib/router.js:132:28
    at /home/alex/.lando/plugins/@lando/core/lib/router.js:23:74
From previous event:
    at retryEach (/home/alex/.lando/plugins/@lando/core/lib/router.js:23:42)
    at exports.stop (/home/alex/.lando/plugins/@lando/core/lib/router.js:131:43)
    at run (/home/alex/.lando/plugins/@lando/core/lib/engine.js:19:59)
    at /home/alex/.lando/plugins/@lando/core/lib/router.js:31:15
From previous event:
    at exports.eventWrapper (/home/alex/.lando/plugins/@lando/core/lib/router.js:31:4)
    at Engine.engineCmd (/home/alex/.lando/plugins/@lando/core/lib/engine.js:19:104)
    at Engine.stop (/home/alex/.lando/plugins/@lando/core/lib/engine.js:489:17)
    at /home/alex/.lando/plugins/@lando/core/lib/app.js:546:29
    at process.processImmediate (node:internal/timers:476:21)
From previous event:
    at App.stop (/home/alex/.lando/plugins/@lando/core/lib/app.js:546:6)
    at /home/alex/.lando/plugins/@lando/core/lib/app.js:243:22
    at async Object.run (/home/alex/.lando/plugins/@lando/core/tasks/destroy.js:21:9)  +554ms
```

Lando file for project:
```
name: projectnamehere
excludes:
  - node_modules
  - modules/contrib
recipe: laravel
config:
  php: '8.2'
  webroot: public
  via: nginx
  xdebug: true
  config:
    php: .lando_config/php.ini
  composer_version: "2.5.5"
  build_as_root:
    - docker-php-ext-install sockets
  overrides:
    environment:
      PHP_IDE_CONFIG: "serverName=lando"
services:
  redis:
    api: 3
    type: redis:4.0.12
    persist: true
    portforward: 32840
    password: womprat-slayer
  mailhog:
    api: 3
    type: mailhog:v1.0.0
  database:
    api: 3
    type: mysql:8.0.20
    portforward: 13315
    creds:
      user: laravel
      password: laravel
      database: projectnamehere
    configs:
      - skip-name-resolve
  meilisearch:
    api: 3
    type: lando
    app_mount: false
    services:
      image: getmeili/meilisearch:v1.3
      command: tini -- /bin/sh -c /bin/meilisearch
      environment:
        - MASTER_KEY=REDACTED
      ports:
        - '7700'
    volumes:
      meilsearch:
    overrides:
      volumes:
        - meilisearch:/meili_data2
```

I'm unsure how to proceed in diagnosing this further and would hugely appreciate any further advice.

Thanks,
Alex
