### ISSUE TITLE
Installing the exif (or other php) extensions

### ISSUE THREAD

**Issue by btmash** [lando/lando#371]
I'm working on a project that requires exiftool (and the php extension). By default, neither of those is installed in the php container. I was able to figure out the docker commands to add the php extension; however, I am still not able to get it to show up in the web config.

This is my .lando.yml file:

```
name: project
recipe: pantheon
config:
  framework: drupal
  env: dev
  site: project
  id: my-project-id
services:
  appserver:
    extras:
      - "apt-get -yqq update"
      - "apt-get -yqq install exiftool"
      - "docker-php-ext-configure exif"
      - "docker-php-ext-install exif"
      - "docker-php-ext-enable exif"

```

**Comment by uberhacker** [comment]
@btmash: Does Pantheon support this extension?

**Comment by btmash** [comment]
It does, yes. The site I'm working on is hosted on pantheon.

**Comment by btmash** [comment]
As a side note, I'm currently getting around this by first creating a dockerfile with the following:

```
FROM devwithlando/pantheon-appserver:7.0-fpm

RUN apt-get -yqq update
RUN apt-get -yqq install exiftool
RUN docker-php-ext-configure exif
RUN docker-php-ext-install exif
RUN docker-php-ext-enable exif
```

I ended up publishing the image to dockerhub and can use it within my team with:
```
name: mysparkly
recipe: pantheon
config:
  framework: drupal
  env: dev
  site: mysparkly
  id: my-project-id
services:
  appserver:
    overrides:
      services:
        image: btmash/pantheon-appserver
```
