### ISSUE TITLE
Passing SSL Certs to Lando Service (Gotenberg)

### ISSUE THREAD

**Issue by faustbrian** [lando/lando#3723]
So I'm trying to run the `gotenberg/gotenberg:8` image alongside the rest of my application but I think the issue I'm encountering is caused by the certificates not being trusted by default. The following file will result in Lando starting and Gotenberg running. I've verified that by checking the logs with `lando logs -s gotenberg` for Gotenberg.

Now the issue I'm facing seems to be that as soon as those certificates are used the only status code that comes back from Gotenberg is 502. The Gotenberg logs also contain `{"level":"fatal","ts":1720177561.7641122,"logger":"api","msg":"open /certs/cert.pem: no such file or directory"}` which would indicate the certs do not exist inside the container. Based on https://docs.lando.dev/core/v3/services/lando.html#ssl my assumption was that I could reference the files in `/certs` but that doesn't seem to be the case.

What would be the recommended way to run another docker image that requires SSL certs to be passed in through CLI flags?

```yaml
name: app
recipe: laravel

proxy:
    gotenberg:
        - gotenberg.lndo.site

services:
    gotenberg:
        type: lando
        ssl: true
        portforward: true
        services:
            image: gotenberg/gotenberg:8
            ports:
                - '3000:3000'
            command:
                [
                    'gotenberg',
                    '--api-tls-cert-file',
                    '/certs/cert.pem',
                    '--api-tls-key-file',
                    '/certs/key.pem',
                ]
```

**Comment by AaronFeledy** [comment]
You can let Lando's proxy take care of SSL:

```
name: app
recipe: laravel

proxy:
  gotenberg:
    - gotenberg.app.lndo.site:3000

services:
  gotenberg:
    api: 3
    type: lando
    ssl: true
    sslExpose: false
    scanner:
      path: /health
    services:
      image: gotenberg/gotenberg:8
      ports:
        - 3000
      command: gotenberg
```
