### ISSUE TITLE
Support for Dolt as a database service

### ISSUE THREAD

**Issue by matthewbdaly** [lando/lando#3727]
Have you considered the idea of adding support for [Dolt](https://docs.dolthub.com/) as a database service? The ability to commit and roll back database state is potentially very useful in a development environment, even if you use MySQL instead in production.

The documentation for Dolt covers the [Dolt SQL Server Docker image](https://docs.dolthub.com/introduction/installation/docker#docker-image-for-dolt-sql-server), and it seems to work broadly similarly to the MySQL one. I've had a go at implementing it using services, but can't quite get it working with the following config:

```yml
name: myapp
recipe: laravel
config:
  webroot: public
  php: '8.1'
services:
  database:
    api: 3
    type: lando
    services:
      image: dolthub/dolt-sql-server:latest
      ports:
        - 3306:3306
      command: tini -- docker-entrypoint.sh
```

I think it may have been that I couldn't get the authentication set up properly, but it sounds like if this were implemented as a plugin that would make that a non-issue.

**Comment by reynoldsalec** [comment]
Does Dolt allow you to pass in defaults for authentication via env vars like MySQL/MariaDB? That would probably be the easiest thing to do.

```
name: myapp
recipe: laravel
config:
  webroot: public
  php: '8.1'
services:
  database:
    api: 3
    type: lando
    services:
      image: dolthub/dolt-sql-server:latest
      ports:
        - 3306:3306
      command: tini -- docker-entrypoint.sh
      environment:
        DOLT_USER: myuser
  ```

**Comment by matthewbdaly** [comment]
I believe it does, yes. Certainly the intent is that it's as compatible with MySQL as they can make it, so it would seem odd if it didn't support that.

**Comment by zachmu** [comment]
Hi @matthewbdaly we'd be interested in hearing what part of this process didn't work. In general a MySQL configuration for tools like this should just work with Dolt.

**Comment by matthewbdaly** [comment]
@zachmu This is the Lando config file I put together:

```yml
name: chirper
recipe: laravel
config:
  webroot: public
  php: '8.1'
services:
  database:
    api: 3
    type: lando
    services:
      image: dolthub/dolt-sql-server:latest
      ports:
        - 3306:3306
      command: tini -- docker-entrypoint.sh
      environment:
        MYSQL_DATABASE: laravel
        MYSQL_USER: laravel
        MYSQL_PASSWORD: laravel
        DOLT_DATABASE: laravel
        DOLT_USER: laravel
        DOLT_PASSWORD: laravel
tooling:
  mysql:
    service: appserver
    cmd: mysql -u root -h database
```

The application is the one built in [Laravel Bootcamp](https://bootcamp.laravel.com/), so basically a fairly standard Laravel application. I didn't know if the environment variables remained identical or not between MySQL and Lando, so I did both to cover all bases.

This does create a usable instance of Dolt, which I can connect to via the `lando mysql` command, but doesn't create the user `laravel` or the database `laravel`. It's possible to create those manually, though, so it's frustratingly close - I suspect it's probably a misconfiguration on my part.

**Comment by AaronFeledy** [comment]
If Dolt does support the MYSQL_ environment variables, you might be able to do this:
```
name: chirper
recipe: laravel
config:
  webroot: public
  php: '8.1'
services:
  database:
    overrides:
      image: dolthub/dolt-sql-server:latest
```

**Comment by matthewbdaly** [comment]
@AaronFeledy Same sort of story - the service runs, but doesn't create the user and database. I also tried it with this slight amendment to enable the `mysql` tooling :

```yml
name: chirper
recipe: laravel
config:
  webroot: public
  php: '8.1'
services:
  database:
    overrides:
      image: dolthub/dolt-sql-server:latest
      command: tini -- docker-entrypoint.sh
tooling:
  mysql:
    service: appserver
    cmd: mysql -u root -h database
```

I've also tried overriding the image and command for the MySQL service:

```yml
name: chirper
recipe: laravel
config:
  webroot: public
  php: '8.1'
services:
  database:
    type: mysql:8.0
    overrides:
      image: dolthub/dolt-sql-server:latest
      command: tini -- docker-entrypoint.sh
tooling:
  mysql:
    service: appserver
    cmd: mysql -u root -h database
```
