### ISSUE TITLE
Console command for drush throws error TypeError: arg.match is not a function

### ISSUE THREAD

**Issue by samuelmolinski** [lando/lando#373]
Bug Report
==========
using: Fedora 26 with Lando v3.0.0-beta.10

I was running the following bash command.  It seems that it doesn't like the '1' (or any other number) when added.  It vomits up errors.  The odd thing is when I ssh into the appserver and run it inside the docker, it works perfectly.  It appears to be an error in how lando relays that command to the VM.  Maybe it doesn't like numbers?

```bash
lando drush dcer node 1 --folder=modules/custom/demo_module/content
pkg/prelude/bootstrap.js:1154
      throw error;
      ^

TypeError: arg.match is not a function
    at parse (/snapshot/cli/node_modules/yargs-parser/index.js:122:13)
    at Parser (/snapshot/cli/node_modules/yargs-parser/index.js:748:16)
    at Object.<anonymous> (/snapshot/cli/lib/tasks.js:61:17)
    at Module._compile (pkg/prelude/bootstrap.js:1225:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1135:31)
```

my yml
```yml
name: emis-core
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: emis-core
  id: 0594dba1-5252-4415-bea5-0076c9370dab

services:

  appserver:
    # Optionally activate xdebug
    xdebug: true

    # Optionally customize the configuration for php and its underlying webserver
    # These paths are both relative to the app root directory
    config:
      # Use a custom nginx config file
      server: config/nginx/drupal8.conf

      # Use a custom php.ini
      conf: config/php/php.ini

    # install an extra packages
    # net-tools includes aditional utilisties such as arp, ifconfig, netstat, rarp, nameif and route
    extras:
      - "apt-get update -y"
      - "apt-get install net-tools -y"
      - "apt-get install nano -y"
      - "mkdir /var/www/tmp"
      - "chmod 777 /var/www/tmp"

    # Override the appsever to add some environment variables
    overrides:
      services:
        environment:
          XDEBUG_CONFIG: idekey=PHPSTORM
          PHP_IDE_CONFIG: serverName=appserver
```
