### ISSUE TITLE
Error: Service "edge" depends on undefined service "appserver_nginx":

### ISSUE THREAD

**Issue by ravearvind** [lando/lando#3730]
For my new setup of lando me facing issue.  
My  Environment details :
Lando version : v3.21.2 
PHP : 8.1
database:10.6

By running any lando command me getting below error.
```
**service "edge" depends on undefined service "appserver_nginx": invalid compose project
ERROR ==>** 
```

Below is the my lando.yml file 
```
recipe: pantheon
config:
  framework: drupal
  xdebug: true

events:
  post-start:
    - appserver: composer install
  post-db-import:
    - appserver: drush cr

services:
  appserver:
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_18.x | bash -
      - apt-get install -y nodejs
      - npm install -global gulp-cli
    build:
      - composer global require "pantheon-systems/terminus:^2"
      - composer global require consolidation/cgr
      - cgr mglaman/drupal-check
    overrides:
      volumes:
        - ${HOME}/.lando/composer_cache:/var/www/.composer

tooling:
  npm:
    service: appserver
    cmd: cd /app/web/themes/custom/chemidp && npm
  gulp:
    service: appserver
    cmd: cd /app/web/themes/custom/chemidp && gulp
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root
```
pantheon.yml 
```
api_version: 1
web_docroot: true
php_version: 8.1
enforce_https: full+subdomains
database:
  version: 10.6
workflows:
  deploy_product:
    after:
      -
        type: webphp
        description: 'Run composer prepare-for-pantheon'
        script: private/scripts/deploy_product/prepare-for-pantheon.php
      -
        type: webphp
        description: 'Run composer install & drupal-scaffold'
        script: private/scripts/deploy_product/composer-install.php
      -
        type: webphp
        description: Post to Slack after deploy
        script: private/scripts/slack_notification.php
      -
        type: webphp
        description: Create npm build
        script: private/scripts/npm_build.php
  sync_code:
    after:
      -
        type: webphp
        description: Clear Drupal cache after code commit
        script: private/scripts/composer_install.php
      -
        type: webphp
        description: Clear Drupal cache after code commit
        script: private/scripts/clear_cache_d8.php
```
