### ISSUE TITLE
Server is running at http://[::1]:3000

### ISSUE THREAD

**Issue by FrancoStino** [lando/lando#3736]
Hello everyone,
I have a little problem. According to the .lando.yml file that I put below, I can't hide `Server is running at http://[::1]:3000`.
The folder where it starts npm start is written in vuejs.

How can I get it to run in the background?

Everything works correctly, but I can't figure out how to do it.

P.S: I am not an expert I am trying to learn. Thanks to all 

```
---
name: ethos-local
recipe: wordpress
config:
  webroot: ethos
  php: '7.4'
  via: nginx
proxy:
  phpmyadmin:
    - phpmyadmin.ethos-local.lndo.site
  wcservice-ethos:
    - wcservice.ethos-local.lndo.site:3000
services:
  database:
    type: mariadb:10.6
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  wcservice-ethos:
    type: node:16
    ssl: true
    build:
      - cd wcservice-ethos && npm install
    run:
      - echo 'CONFIG=config.json\nPORT=3000' > /app/wcservice-ethos/.env
      - |
        echo '{"dbUri": "mysql://wordpress:wordpress@database:3306/wordpress", "tablePrefix": "wbp_", "multilingualEnabled": false, "multilingualMode": "wpml"}' > /app/wcservice-ethos/config.json
      - cd wcservice-ethos && npm start -s
  appserver:
    config:
      php: config/php.ini
```

Output:

```
lando rebuild -y
Rising anew like a fire phoenix from the ashes! Rebuilding app...
[+] Killing 5/5
 ✔ Container ethoslocal_appserver_1        Killed                                                                                                    0.4s
 ✔ Container ethoslocal_appserver_nginx_1  Killed                                                                                                    1.0s
 ✔ Container ethoslocal_phpmyadmin_1       Killed                                                                                                    0.9s
 ✔ Container ethoslocal_wcservice-ethos_1  Killed                                                                                                    0.8s
 ✔ Container ethoslocal_database_1         Killed                                                                                                    0.9s
Going to remove ethoslocal_phpmyadmin_1, ethoslocal_appserver_nginx_1, ethoslocal_wcservice-ethos_1, ethoslocal_database_1, ethoslocal_appserver_1
[+] Removing 5/0
 ✔ Container ethoslocal_phpmyadmin_1       Removed                                                                                                   0.1s
 ✔ Container ethoslocal_database_1         Removed                                                                                                   0.0s
 ✔ Container ethoslocal_appserver_nginx_1  Removed                                                                                                   0.0s
 ✔ Container ethoslocal_appserver_1        Removed                                                                                                   0.1s
 ✔ Container ethoslocal_wcservice-ethos_1  Removed                                                                                                   0.0s
[+] Pulling 4/4
 ✔ database Pulled                                                                                                                                   1.2s
 ✔ wcservice-ethos Pulled                                                                                                                            1.4s
 ✔ appserver Pulled                                                                                                                                  1.3s
 ✔ phpmyadmin Pulled                                                                                                                                 1.3s
[+] Running 1/0
 ✔ Container landoproxyhyperion5000gandalfedition_proxy_1  Running                                                                                   0.0s
[+] Running 1/1
 ✔ Container ethoslocal_wcservice-ethos_1  Started                                                                                                   0.4s
[+] Running 1/1
 ✔ Container ethoslocal_appserver_1  Started                                                                                                         0.2s
All settings correct for using Composer
Downloading...

Composer (version 2.2.22) successfully installed to: /usr/local/bin/composer
Use it: php /usr/local/bin/composer

OS:	Linux 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64
Shell:	
PHP binary:	/usr/local/bin/php
PHP version:	7.4.33
php.ini used:	
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.5.23-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
SQL modes:	
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/app
WP-CLI packages dir:	
WP-CLI cache dir:	/var/www/.wp-cli/cache
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.11.0

up to date, audited 730 packages in 1s

150 packages are looking for funding
  run `npm fund` for details

1 critical severity vulnerability

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice
npm notice New major version of npm available! 8.19.4 -> 10.8.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.3
npm notice Run npm install -g npm@10.8.3 to update!
npm notice
[+] Stopping 2/2
 ✔ Container ethoslocal_appserver_1        Stopped                                                                                                  10.2s
 ✔ Container ethoslocal_wcservice-ethos_1  Stopped                                                                                                  10.4s
[+] Running 5/5
 ✔ Container ethoslocal_wcservice-ethos_1  Started                                                                                                   0.5s
 ✔ Container ethoslocal_appserver_1        Started                                                                                                   0.4s
 ✔ Container ethoslocal_database_1         Started                                                                                                   0.5s
 ✔ Container ethoslocal_appserver_nginx_1  Started                                                                                                   1.0s
 ✔ Container ethoslocal_phpmyadmin_1       Started                                                                                                   0.6s
[+] Healthchecking 1/1
 ✔ Healthcheck ethoslocal_database_1  Passed

> wcservice@0.1.0 prestart
> npm run rebuild


> wcservice@0.1.0 rebuild
> npm run clean && npm run build


> wcservice@0.1.0 clean
> lb-clean dist *.tsbuildinfo .eslintcache


> wcservice@0.1.0 build
> lb-tsc


> wcservice@0.1.0 start
> node -r source-map-support/register .

Server is running at http://[::1]:3000```
