### ISSUE TITLE
tooling: my-command: usage: of the example, does not appear with --help

### ISSUE THREAD

**Issue by com2** [lando/lando#3738]
I thought I understood the concept but I was unable to show the _usage:_  text with _lando my-command --help_.  It would keep running the command in stead of merely showing the usage help text. My understanding is taken from the documentation of https://docs.lando.dev/core/v3/tooling.html#usage so I guess this is for version 3.x and I am presently using version v3.21.2. So I thought I must be making a mistake and simply pasted the tooling example from **Usage & Examples** to see if at least the example would work. When I then run _lando my-command --help_ I see the following: 

lando my-command --help
lando my-command

Runs my-command commands

Options:
  --channel      Sets the update channel                                                                                  [array] [choices: "edge", "none", "stable"]
  --clear        Clears the lando tasks cache                                                                                                               [boolean]
  --debug        Shows debug output                                                                                                                         [boolean]
  --help         Shows lando or delegated command help if applicable                                                                                        [boolean]
  --verbose, -v  Runs with extra verbosity                                                                                                                    [count]
  **--word, -w     Print what the word is**

So as you can see, not even the example shows the usage text. Shown in bold here, I only see the _options: word: decribe:_ text displayed. Is this an error in the Documentation or should this be filed as bug?

Apparently, unlike the example, I still make an error that causes my test command to run in stead of showing the help text:

```
tooling:
  test:
    cmd: /app/args.sh
    service: appserver
    usage: $0 test [arg1]
    examples:
      - $0 test /app
      - $0 test /app/osfw
    positionals:
      arg1:
        describe: Path to be shown
        type: string

```
/app/args.sh:
```
#!/bin/bash
echo "args (0-2): $0 $1 $2"

```
Can someone help me out?
