### ISSUE TITLE
Lando not finding cert.crt or cert.key, edge_ssl issue and wp-cli commands throw a 'OCI runtime exec failed' error

### ISSUE THREAD

**Issue by MattMakesNoise** [lando/lando#3750]
**What is your lando version and operating system?**
lando v3.2.2 on MacOS Sonoma 14.5

- Ran `lando destroy` and deleted all files
- uninstalled lando and docker 
- removed ~/.lando and ~/.docker
- reinstalled lando and docker => docker v4.34.0
- created an empty folder and ran `lando init --source pantheon`
- chose site to import but just hangs
- cloned project from pantheon into new dir
- ran `lando init --source pantheon` again and back to the same three errors

**Tell us about your .lando.yml**
I've tried numerous things with this such as adding the platform as `linux/amd64`, direct refs to the key and crt files and adding the wp command to the tooling. The lando.yml should look like this at its most basic
```
name: publishing-sites
recipe: pantheon
config:
  framework: wordpress_network
  site: publishing-sites
  id: af0ee6e0-d490-440b-9c65-603e119ef44a
proxy:
  edge:
    - network.lndo.site
    - the-ambient.lndo.site
    - getsweatgo.lndo.site
    - trustedreviews.lndo.site
    - wareable.lndo.site
services:
  database:
    portforward: 3307
```

**Tell us about the error you got**
Lines of note are...

```
Pantheon pre-run scripting
cat: /certs/cert.crt: No such file or directory
cat: /certs/cert.key: No such file or directory
ERROR ==>
```

and 

```
! edge_ssl The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s
[+] Healthchecking 1/1
 ✔ Healthcheck publishingsites_database_1  Passed

  _      __              _           __
 | | /| / /__ ________  (_)__  ___ _/ /
 | |/ |/ / _ `/ __/ _ \/ / _ \/ _ `/_/
 |__/|__/\_,_/_/ /_//_/_/_//_/\_, (_)
                             /___/

Your app is starting up but we have already detected some things you should investigate.
These may or may not prevent your app from working.

  ⚠ One of your v3 build steps failed
    This **MAY** prevent your app from working.
    Check for errors above, fix them in your Landofile, and try again by running:
    Run lando rebuild
```
    
When trying to run a basic wp-cli command such as 

`lando wp plugin list`

I get the error

`OCI runtime exec failed: exec failed: unable to start container process: exec: "wp": executable file not found in $PATH: unknown`
