### ISSUE TITLE
When .lando.yml tooling has empty keys, lando crashes

### ISSUE THREAD

**Issue by ivuorinen** [lando/lando#3759]
With tooling section of `.lando.yml` has been set like this, lando crashes:

```yaml
tooling:
  pull:
    # Disable pulling code, we have git
    # description: Pull things except code
    # options:
    #   code:
    #     default: none
  push:
    # Disable pushing database to production
    description: Pro push
    options:
      database:
        default: none

```

Notice how `pull` section is empty.

Next trying to execute lando:

```
➜ lando
/snapshot/core/node_modules/lodash/lodash.js:3585
        result[++index] = iteratee(value, key, collection);
                          ^

TypeError: Cannot read properties of null (reading 'id')
    at /snapshot/core/utils/get-tasks.js
    at /snapshot/core/node_modules/lodash/lodash.js:3585:27
    at /snapshot/core/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/snapshot/core/node_modules/lodash/lodash.js:3032:24)
    at /snapshot/core/node_modules/lodash/lodash.js:4936:18
    at baseMap (/snapshot/core/node_modules/lodash/lodash.js:3584:7)
    at Function.map (/snapshot/core/node_modules/lodash/lodash.js:9622:14)
    at interceptor (/snapshot/core/node_modules/lodash/lodash.js:17094:35)
    at Function.thru (/snapshot/core/node_modules/lodash/lodash.js:8859:14)
    at /snapshot/core/node_modules/lodash/lodash.js:4430:28

Node.js v20.18.0
```

Lando works in other folders, but crashes when in the folder with "broken" configuration.
