### ISSUE TITLE
Metrics opt-out doesn't work

### ISSUE THREAD

**Issue by todeveni** [lando/lando#3764]
Adding opt-out config to `~/.lando/config.yml` doesn't actually opt-out.

```yaml
stats:
  - report: false
    url: https://metrics.lando.dev
```

Verbose log from project start:
`my-project reporting start action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev, report=false, url=https://metrics.lando.dev +3ms`

Little Snitch firewall on macOS detects connection attempt also:
`On 22. Nov 2024, iTerm via lando tried to establish a connection to metrics.lando.dev on TCP port 443 (https). The request was denied via connection alert.`
