### ISSUE TITLE
depends_on not woring in v4 l337 service

### ISSUE THREAD

**Issue by kinglouie** [lando/lando#3768]
I tried running the custom zitadel docker image `ghcr.io/zitadel/zitadel:latest` alongside the lando `postgres` plugin.
The zitadel container should only start when the postgres server is ready, so i added the db container to the `depends_on` key with `condition: service_healthy`. On `lando start` lando errors with `container glidr_db-sso_1 has no healthcheck configured` although the postgres plugin has a healthcheck configured.

This is my complete lando.yml
```
name: sso

services:
  db-sso:
    type: postgres:16
    portforward: true

  sso:
    api: 4
    type: l337
    image: "ghcr.io/zitadel/zitadel:latest"
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    ports:
      - 80/http
    environment:
      ZITADEL_DATABASE_POSTGRES_HOST: db-sso
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: database
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD:
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_EXTERNALPORT: 80
      ZITADEL_PORT: 80
      ZITADEL_EXTERNALSECURE: false
      ZITADEL_TLS_ENABLED: false
      ZITADEL_EXTERNALDOMAIN: sso.lndo.site
    depends_on:
      db-sso:
        condition: service_healthy

proxy:
  sso:
    - hostname: sso.lndo.site
```

how can I ensure that db is ready for custom services?
