### ISSUE TITLE
Lando MySQL connection does not persist between stop/start of containers

### ISSUE THREAD

**Issue by jakoblundoe** [lando/lando#3778]
If I use Lando default config (e.g. `lando init`), ".lando.yml" looks like this:
```
name: wp-app
recipe: wordpress
config:
  webroot: .
```

Everything works on first containers running.
But after `lando stop` and `lando start`, the data from MySQL does not persist.

If I add database: mysql to the ".landa.yml":
```
name: wp-app
recipe: wordpress
config:
  webroot: .
  database: mysql
```

The data persist between container stop/start.

Am i missing something obvious or is this a bug?
