### ISSUE TITLE
Lando crashes when using Excludes in yaml

### ISSUE THREAD

**Issue by leapxdco** [lando/lando#3786]
OSX Ventura 13.5
Lando v3.24.0

When attempting to start with this config, I get `undefined is not a function`

```yml
name: site-name
recipe: pantheon
config:
  framework: wordpress
  site: site-name
  id: xxxxxxxx-xxxx-xxxx--xxxxxxxxxxxx
excludes:
  - wp-content/themes/my-theme/node_modules
```

This config works as expected

```yml
name: site-name
recipe: pantheon
config:
  framework: wordpress
  site: site-name
  id: xxxxxxxx-xxxx-xxxx--xxxxxxxxxxxx
#excludes:
#  - wp-content/themes/my-theme/node_modules
```
