### ISSUE TITLE
Cannot use mongodb.so

### ISSUE THREAD

**Issue by Sake-codex** [lando/lando#3788]
Hi ! ✋ 
### **Context:** 

I am a newbie in docker, and using your tools is really helpfull, so I switched some project on it. 
For my current client, I want to create the lando.yml file and make it working with mongoDB on a legacy version. 

I tried a lot of versions... but I didn't succeed in implement mongodb in this version. 
I have a old dockerfile that I didn't make... but for futur purpose i need lando to work. 

### **ISSUE**

```bash
NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'mongodb.so' 
(tried: /usr/local/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so (/usr/local/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so: cannot open shared object file: 
No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so.so 
(/usr/local/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so.so: cannot open shared object file: No s
```

### **Recipe** 

```yml
name: projet-api
recipe: symfony
config:
  php: '7.4'
  via: nginx
  webroot: public
  platform: linux/arm64/v8
  database: mongo
  xdebug: false
services:
  appserver:
    config:
      php: ./lando_php.ini
    run_as_root:
      - apt-get update
      - docker-php-ext-install pcntl
      - pecl channel-update pecl.php.net
      - pecl install mongodb-1.9.0
      - docker-php-ext-enable mongodb
  database:
    type: mongo:4.2
    platform: linux/arm64/v8
    creds:
      user: xxx
      password: xxx
      database: xxx
  mongo-express:
    type: compose
    services:
      image: mongo-express
      restart: always
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: xxx
        ME_CONFIG_MONGODB_ADMINPASSWORD: xxx
        ME_CONFIG_MONGODB_SERVER: xxx
```

### **Composer**

```json
{
    "type": "project",
    "license": "proprietary",
    "name": "xxxxx",
    "description": "xxxxx",
    "require": {
        "php": ">=7.2.5",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "alexpechkarev/geometry-library": "^1.0",
        "api-platform/core": "^2.5",
        "aws/aws-sdk-php": "^3.199",
        "composer/package-versions-deprecated": "^1.11",
        "doctrine/annotations": "^1.10",
        "doctrine/doctrine-bundle": "^2.0",
        "doctrine/doctrine-migrations-bundle": "^3.0",
        "doctrine/mongodb-odm-bundle": "^4.3",
        "gesdinet/jwt-refresh-token-bundle": "^1.1.1",
        "guzzlehttp/guzzle": "^7.2.0",
        "jmikola/geojson": "^1.1",
        "league/csv": "^9.8",
        "league/geotools": "^0.8.2",
        "lexik/jwt-authentication-bundle": "^2.6",
        "mikehaertl/phpwkhtmltopdf": "^2.5",
        "nelmio/cors-bundle": "^2.0",
        "phpdocumentor/reflection-docblock": "^5.2",
        "phpmd/phpmd": "^2.9",
        "saikiran/geohash": "^1.0",
        "sensio/framework-extra-bundle": "^5.5",
        "stof/doctrine-extensions-bundle": "^1.4",
        "symfony/asset": "5.4.*",
        "symfony/console": "5.4.*",
        "symfony/dotenv": "5.4.*",
        "symfony/expression-language": "5.4.*",
        "symfony/flex": "^1.3.1",
        "symfony/framework-bundle": "5.4.*",
        "symfony/intl": "5.4.*",
        "symfony/messenger": "5.4.*",
        "symfony/property-access": "5.4.*",
        "symfony/property-info": "5.4.*",
        "symfony/security-bundle": "5.4.*",
        "symfony/serializer": "5.4.*",
        "symfony/twig-bundle": "5.4.*",
        "symfony/validator": "5.4.*",
        "symfony/yaml": "5.4.*",
        "twig/twig": "^3.0",
        "vich/uploader-bundle": "^1.15"
    },
    "require-dev": {
        "doctrine/doctrine-fixtures-bundle": "^3.0",
        "friendsofphp/php-cs-fixer": "^2.13",
        "jangregor/phpstan-prophecy": "^0.8.0",
        "phpstan/phpstan-doctrine": "^0.12.13",
        "phpstan/phpstan-strict-rules": "^0.12.2",
        "phpstan/phpstan-symfony": "^0.12.6",
        "symfony/debug-bundle": "5.4.*",
        "symfony/maker-bundle": "^1.14",
        "symfony/monolog-bundle": "^3.0",
        "symfony/phpunit-bridge": "^7.0",
        "symfony/stopwatch": "5.4.*",
        "symfony/var-dumper": "5.4.*",
        "symfony/web-profiler-bundle": "5.4.*"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true,
        "allow-plugins": {
            "composer/package-versions-deprecated": true,
            "symfony/flex": true,
            "php-http/discovery": true
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        },
        "files": [
            "src/Doctrine/Annotations/CachedReader.php"
        ]
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "5.4.*"
        }
    }
}
```

Hoping you have some tips or enlightenment for me; thanks !
