### ISSUE TITLE
Custom URL for my Lando Site (Wordpress/Drupal)

### ISSUE THREAD

**Issue by sharif-elshobkshy** [lando/lando#3790]
Hi,

Apologies if this has been addressed already.

I use Lando to build my local Wordpress/Drupal development environments.

I'm trying to create a URL other than https://mysite.lndo.site for my Site.
Specifically, I need it to be mysite.local

I followed some steps on the internet

```
name: mysite
recipe: pantheon
config:
  framework: wordpress
  site: mysite
proxy:
  appserver:
    - mysite.local
```

Then update my local /etc/hosts

`127.0.0.1 mysite.local`

After running "lando rebuild -y" I get:

```
 URLS                                                                                     
  ✔ APPSERVER NGINX URLS
    ✔ https://localhost:32937 [302]
    ✔ http://localhost:32936 [302]
  ⚠ APPSERVER URLS
    ✖ http://mysite.local:8000/ [502] REQUEST FAILED WITH STATUS CODE 502
  ✔ EDGE SSL URLS
    ✔ https://localhost:32939 [302]
  ✔ EDGE URLS
    ✔ http://localhost:32938 [302]
    ✔ http://mysite.lndo.site:8000/ [302]
    ✔ https://mysite.lndo.site/ [302]
```
I tried changing the port, but that didn't make a difference
```
proxy:
  appserver:
    - mysite.local:8081
```

What am I missing?

Thanks in advance.

**Comment by AaronFeledy** [comment]
For the pantheon recipe serves pages from the `edge` service, so this should probably work:
```yaml
proxy:
  edge:
    - mysite.local
```
