### ISSUE TITLE
How to use host ssh keys inside container?

### ISSUE THREAD

**Issue by kinglouie** [lando/lando#3792]
I have a wordpress application that I want to deploy using deployer. For deployer to be able to connect to the production server I need my host machines ssh keys to be available inside a php docker container.

I tried to use [docker secrets](https://docs.docker.com/engine/swarm/secrets/) to mount my `.ssh/id_rsa` into my container. 

Unfortunately this does not work with lando:
```
services:
  example:
    api: 4
    type: l337
    image: custom-image
    secrets:
      - user_ssh_key
secrets:
  user_ssh_key:
    file: ~/.ssh/id_rsa
```

It throws the following error on `lando start`:
> service "example" refers to undefined secret user_ssh_key

Is there any way to fix this or another easy way to use the hosts ssh key inside a container?
