### ISSUE TITLE
Issue with PHP 8.3 development tools and Postgres plugin in Lando container

### ISSUE THREAD

**Issue by web-assistant** [lando/lando#3795]
**Title:**
Issue with PHP 8.3 development tools and Postgres plugin in Lando container

**Description:**
I am facing an issue while working with Lando and the Postgres service in my setup. I am unable to install the php8.3-dev package inside the Lando container, and I am also seeking clarification on whether the Postgres plugin is included with Lando or if it needs to be manually configured.

**Steps to Reproduce:**
Set up a Lando environment with a postgres service in the lando.yml.

Try to install the php8.3-dev package inside the container.

The following error appears:

> E: Unable to locate package php8.3-dev
> E: Couldn't find any package by glob 'php8.3-dev'
> E: Couldn't find any package by regex 'php8.3-dev'

The Postgres service seems to be running, but I am unsure whether it was automatically included with Lando or if manual setup is required.

**Expected Behavior:**
The php8.3-dev package should be installable without errors.

The Postgres service should be ready to use without additional configuration, if it's bundled with Lando by default.

**Actual Behavior:**
The php8.3-dev package cannot be found and installed.

Uncertainty about whether Postgres is automatically included with Lando or requires manual installation.

Environment:
Lando version: v3.24.3

OS: Windows 10

PHP version: PHP 8.3

Postgres version: 13.0

Additional Information:
I’ve tried running sudo apt update and other troubleshooting steps, but the issue persists.

The Postgres container seems to start, but I am unsure whether it was configured correctly.

**Comment by web-assistant** [comment]
I should add, I'm adding the below to my lando file:

>   postgres:
>   type: postgres:13
>   portforward: 5432

**Comment by AaronFeledy** [comment]
Where and how are you trying to install this?

**Comment by web-assistant** [comment]
@AaronFeledy 

The install is for the postgres service and installs when doing `lando rebuild`

I guess when I say 'Lando container', I mean the Lando instance that runs when you spin it up

I think the maybe the issue is I'm using PHP 8.3 and it's fairly new for postgres, though I have installed it on my production server, installed via EasyApache for PHP 8.3

```
name: mysite
recipe: drupal11
config:
  php: '8.3'
  composer_version: "2.6.5"
  via: apache
  webroot: web
  database: mariadb
  drush: ^12
  xdebug: false
  config:
    php: .lando/.lando.php.ini
    database: .lando/.lando.mysql.cnf

proxy:
  appserver:
    - mysite.lndo.site
    - www.mysite.lndo.site
  mailhog:
    - mail.mysite.lndo.site
  pma:
    - pma.mysite.lndo.site

services:
  database:
    creds:
      database: database
      user: user
      password: password
  postgres:
    type: postgres:13
    portforward: 5432
  appserver:
    type: php:8.3
    scanner: false
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
        XDEBUG_SESSION_START: lando
        PHP_MEMORY_LIMIT: 1024M
        PHP_OPCACHE_MEMORY_CONSUMPTION: 256
        PHP_OPCACHE_MAX_ACCELERATED_FILES: 10000
        PHP_OPCACHE_VALIDATE_TIMESTAMPS: "0"
        PHP_OPCACHE_REVALIDATE_FREQ: "60"
        XDEBUG_MODE: develop,debug
        XDEBUG_MAX_NESTING_LEVEL: 512
        PHP_SENDMAIL_PATH: '/usr/sbin/sendmail -S mailhog:1025'
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
    scanner: false
    ssl: true
  pma:
    type: phpmyadmin
    hosts:
      - database
    scanner: false
    ssl: true

tooling:
  xon:
    service: appserver
    description: Enable xdebug for Apache.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && docker-php-ext-enable xdebug && /etc/init.d/apache2 reload && echo "Xdebug enabled"
    user: root
  xoff:
    service: appserver
    description: Disable xdebug for Apache.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload && echo "Xdebug disabled"
    user: root

excludes:
  - .idea
  - .git
```
