### ISSUE TITLE
ECONNRESET upon custom Keycloack image service

### ISSUE THREAD

**Issue by leocas14** [lando/lando#3798]
Hello everyone!

I'm having a hard time implementing a [Keycloack image](https://quay.io/repository/keycloak/keycloak) service and I'm not quite sure what is going wrong as I'm able to compose and expose the service on 8080 port (Keycloack default) but the service can't be reached via browser.

This is my .lando.yml:

`name: test
recipe: drupal11
config:
  webroot: ./web
services:
  appserver:
    type: php:8.3
    xdebug: true
    config:
      php: .lando/config/php.ini
  mailhog:
    type: mailhog
  keycloack:
    api: 3
    type: lando
    services:
      image: quay.io/keycloak/keycloak:24.0.2
      command: start-dev
      user: root
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - "8080:8080"
    moreHttpPorts:
      - 8080`

I tried tweaking proxy as well as port configuration but nothing seems to work, I would really appreciate if you can point me to the right direction.

**Comment by AaronFeledy** [comment]
I was able to get a keycloak service running like this:
```yaml
name: test-keycloak
services:
  keycloak:
    api: 3
    type: lando
    meUser: keycloak
    services:
      image: quay.io/keycloak/keycloak:24.0.2
      command: /opt/keycloak/bin/kc.sh start-dev
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - "8080"

proxy:
  keycloak:
    - keycloak.lndo.site:8080
```
