### ISSUE TITLE
Inject a "last loaded" php.ini file instead of replacing the default one.

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#410]
I'm trying to modify the appserver's php.ini to troubleshoot xdebug.

In my `.lando.yml`, I tried this:

```
  appserver:
    environment:
      XDEBUG_CONFIG: remote_host=192.168.0.177
    extras:
      # Enable Remote xdebug
      - "echo 'xdebug.idekey = PHPSTORM' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      # - "echo 'xdebug.remote_autostart = 1' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "echo 'xdebug.remote_connect_back = 1' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "echo 'xdebug.remote_host = 192.168.0.177' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "echo 'xdebug.remote_log = /app/lando/logs/xdebug.log' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "echo 'xdebug.idekey = PHPSTORM' >> /usr/local/etc/php/php.ini"
      # - "echo 'xdebug.remote_autostart = 1' >> /usr/local/etc/php/php.ini"
      - "echo 'xdebug.remote_connect_back = 1' >> /usr/local/etc/php/php.ini"
      - "echo 'xdebug.remote_host = 192.168.0.177' >> /usr/local/etc/php/php.ini"
      - "echo 'xdebug.remote_log = /app/lando/logs/xdebug.log' >> /usr/local/etc/php/php.ini"
```

**Note**: After adding these commands, I ran `lando rebuild`, but `phpinfo()` showed no changes to appserver.  After running `lando poweroff` and then `lando start`, I saw the changes in `phpinfo()`.  So, it seems that in this case, `lando rebuild` is not enough; it has to be `lando rebuild -y; lando poweroff; lando start`.

This allows me to change the values of everything except `xdebug.remote_host`, which has a master value of `192.168.0.177` (what I set, and what I want) but a local value of `10.0.75.1`.  I assume this is set by lando or docker somewhere, but I have no idea where to look to override it.
