### ISSUE TITLE
proxy weirdness

### ISSUE THREAD

**Issue by markisatacomputer** [lando/lando#415]
v3.0.0-beta.20 on macos sierra 10.12.4 

I've been running a Drupal 7 site imported from Pantheon and I've altered .lando.yml file as detailed [here](https://docs.devwithlando.io/config/proxy.html) in order to add a new route.  Previously there was no proxy entry.  Here's the entire .lando.yml with proxy:

```
name: exploratorium
recipe: pantheon
config:
  framework: drupal
  env: dev
  site: exploratorium
  id: 8866abfe-692d-4e99-bc86-0c1f69625809
proxy:
  web:
    - exploratorium.lndo.site
    - local.exploratorium.edu
```

When running `lando rebuild -y -vvvv`, here's the error I get:

```
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
error: Duplicate URL detected: {"http://exploratorium.lndo.site":2,"https://exploratorium.lndo.site":2,"http://local.exploratorium.edu":1,"https://local.exploratorium.edu":1}
ERROR: The Compose file '/Users/mnicola/.lando/tmp/exploratorium/exploratorium-proxy-3.yml' is invalid because:
services.appserver.extra_hosts contains non unique items, please remove duplicates from ['exploratorium.lndo.site:10.120.76.241', 'exploratorium.lndo.site:10.120.76.241', 'local.exploratorium.edu:10.120.76.241']
services.cache.extra_hosts contains non unique items, please remove duplicates from ['exploratorium.lndo.site:10.120.76.241', 'exploratorium.lndo.site:10.120.76.241', 'local.exploratorium.edu:10.120.76.241']
services.database.extra_hosts contains non unique items, please remove duplicates from ['exploratorium.lndo.site:10.120.76.241', 'exploratorium.lndo.site:10.120.76.241', 'local.exploratorium.edu:10.120.76.241']
services.edge.extra_hosts contains non unique items, please remove duplicates from ['exploratorium.lndo.site:10.120.76.241', 'exploratorium.lndo.site:10.120.76.241', 'local.exploratorium.edu:10.120.76.241']
services.edge_ssl.extra_hosts contains non unique items, please remove duplicates from ['exploratorium.lndo.site:10.120.76.241', 'exploratorium.lndo.site:10.120.76.241', 'local.exploratorium.edu:10.120.76.241']
services.index.extra_hosts contains non unique items, please remove duplicates from ['exploratorium.lndo.site:10.120.76.241', 'exploratorium.lndo.site:10.120.76.241', 'local.exploratorium.edu:10.120.76.241']
services.nginx.extra_hosts contains non unique items, please remove duplicates from ['exploratorium.lndo.site:10.120.76.241', 'exploratorium.lndo.site:10.120.76.241', 'local.exploratorium.edu:10.120.76.241']
```

I've also attempted the same with a .lando.yml without the default proxy name as that seems to be causing the problem.  It looks like so:

```
name: exploratorium
recipe: pantheon
config:
  framework: drupal
  env: dev
  site: exploratorium
  id: 8866abfe-692d-4e99-bc86-0c1f69625809
proxy:
  web:
    - local.exploratorium.edu
```

That doesn't work.  When I run `lando rebuild -y -vvvv` see a different error:

```
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
ERROR: The Compose file is invalid because:
Service web has neither an image nor a build context specified. At least one must be provided.
```

Any advice on how to proceed?  Thanks!

**Comment by pirog** [comment]
@markisatacomputer i think there are two major issues here, the good news is these errors are actually expected based on the lando file that you have

1. `exploratorium.lndo.site` is already going to be set up by the `pantheon` recipe so you don't need to add this... so also makes sense you'd get an error about it being a duplicate

2. There is no service called `web` so your second error also makes sense. You might want to run `lando info` on your app to see what services are available. Not exactly sure your use case but i'm guessing you'll want to use the `edge` service for `pantheon` recipes

**Comment by markisatacomputer** [comment]
Thanks @pirog!  Updated .lando.yml and sailing is smooth

```
name: exploratorium
recipe: pantheon
config:
  framework: drupal
  env: dev
  site: exploratorium
  id: 8866abfe-692d-4e99-bc86-0c1f69625809
proxy:
  edge:
    - local.exploratorium.edu
```
