### ISSUE TITLE
Secure HTTPS URL redirects to HTTP when trailing slash is missing

### ISSUE THREAD

**Issue by wturnerharris** [lando/lando#423]
Bug Report
==========

**System Setup**
What is your lando version and operating system?
v3.0.0-beta.17 on Mac OS X: 10.12.6

*Lando Config*

```yml
name: barrel-base-theme
recipe: pantheon
config:
  framework: wordpress
  env: dev
  site: barrel-base-theme
  id: 55e6ab01-ecf0-4b68-ad70-7238f9af2320
```

**Tell us about the command you were running**
1. Run `lando start` on any lando project running WordPress
2. Visit the secure HTTPS URL provided after starting lando.
3. Go to /wp-admin on the same URL
4. Get redirected to HTTP

In some cases, if a random port was chosen for HTTP, assuming something like apache or node is already occupying that port, then the site reflects a 500 error because instead of redirecting to HTTP's mapped port, it redirects to the HTTP URL without the port.

I've found that adding a trailing slash to the request fixes this issue, but in some cases this is unavoidable such as submitting a form with gravity forms, or logging in.
