### ISSUE TITLE
Bug Report - lando composer require drupal/<anything> dies after a long attempt to update dependencies

### ISSUE THREAD

**Issue by nimzie** [lando/lando#424]
I've got lando running on my mac. Sites are running fine. Lando seems to be starting / rebuilding just fine.
When I attempt to add a Drupal module using
lando composer drupal/pathauto (for example) the process just goes away. Here is my output:

> $lando composer require drupal/pathauto -v
Using version ^1.0 for drupal/pathauto
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Killed

It doesn't return Killed for up to 10 mins some times.

The weird thing is regular composer works to do this. It's not super fast but it is working and returning a warning:

> Warning: Ambiguous class resolution, "Drupal\Component\Utility\Random" was found in both "$baseDir . '/web/core/lib/Drupal/Component/Utility/Random.php" and "/Users/adamshore/wwwroot/clchfx/vendor/drupal/drupal-driver/src/Drupal/Component/Utility/Random.php", the first will be used.

I feel like this has nothing to do with the lando issue though. lando is not returning any errors. I've tried on multiple D8 sites - all built with Pantheon's D8 Drops upstream if this helps.

MacOS High Sierra - lando v3.0.0-beta.21

.lando.yml 
```name: clchfx
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: clchfx
  id: f9f7f1a5-fe62-4325-879f-7bb49de24d56
```

.pantheon.yml
```
api_version: 1
web_docroot: true
php_version: 7.0
workflows:
  deploy_product:
    after:
      -
        type: webphp
        description: 'Run composer prepare-for-pantheon'
        script: private/scripts/deploy_product/prepare-for-pantheon.php
      -
        type: webphp
        description: 'Run composer install & drupal-scaffold'
        script: private/scripts/deploy_product/composer-install.php
  sync_code:
    after:
      - type: webphp
        description: Push changes back to GitHub if needed
        script: private/scripts/quicksilver/quicksilver-pushback/push-back-to-github.php
```
It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

Running the command with --verbose gives me no more information than already posted.

`lando composer require drupal/pathauto --verbose`
