### ISSUE TITLE
Drupal multisite tutorial

### ISSUE THREAD

**Issue by pirog** [lando/lando#433]

**Comment by ccjjmartin** [comment]
For my site (running domain access - not exactly multisite but is multidomain) I had to:

1) Add this to .lando.yml
```
proxy:
  edge:
    - domain1.lndo.site
    - domain2.lndo.site
```
2) Login using the nginx localhost domain and/or update allowed domains manually from my previously exported feature.
3) Edit my $cookie_domain in settings.php to remove any references to port numbers (with the port in the cookie domain I was getting access denied when using `drush uli` locally)

Hope that helps someone.

**Comment by pirog** [comment]
nice @ccjjmartin! thanks for this.

I think the 1. in your list here is going to be the crux of the tutorial but 2/3 are awesome points that i'll definitely add.

**Comment by GaxZE** [comment]
I've managed to get a Drupal 8 site using https://www.drupal.org/project/domain via the proxy setting. Only additional requirement was to create a domain alias within the CMS.

**Comment by brookeheaton** [comment]
Can anyone share any guidance in the comments here about how to get a Drupal 8 multisite running on lando?

**Comment by brooke-heaton** [comment]
I have a d8 lando multisite up and running. For reference, check out this incredibly helpful repo by @nalipaz

https://github.com/nalipaz/lando-acquia-multisite-recipe

In short, the .lando.yml will need proxies for each multisite in the appserver array, the settings.local should include the out of the box configuration for the database plus the host defined in the proxy:appserver array, and finally you need drush aliases pointing to your local (at the least) assuming you want to use drush. If you use drupal console, you'll need to specify your uri (e.g. `drupal --uri=http://site1.lndo.site cr` all)

.lando.yml - note you MUST have additional services for subsites - not necessarily for the 'default' site if that is one of the multisites. The service name becomes the 'host' for each setting.php .    
```
proxy:
  appserver:
    - site1.lndo.site
    - site2.lndo.s
services:
  site1:
    type: mysql:5.7
    portforward: 33068
    config:
      confd: lando/mysql/conf.d
  site2:
    type: mysql:5.7
    portforward: 33069
    config:
      confd: .lando/mysql/conf.d
```

docroot/sites/site1/settings/local.settings.php - note that the only thing we need to add to the deafult lando sql configuration is the host 
```
/**
 * Database configuration.
 */
$databases['default'] = array (
  'default' => array (
    'driver' => 'mysql',
    'database' => 'database',
    'username' => 'mysql',
    'password' => 'password',
    'prefix' => '',
    'port' => 3306,
  )
);
// The only thing to add from the out-of-the-box Lando db is the special host for each subsite
$databases['default']['default']['host'] = 'site1';
```

docroot/sites/sites1/settings.php - special conditions specific to acquia here - you may have something similar for your host. the $_Server['PWD']=DRUPAL_ROOT; is necessary if you use drush9 on Acquia
```
if (!key_exists('AH_SITE_ENVIRONMENT', $_ENV)) {
  $environment_settings = __DIR__  . '/settings/local.settings.php';
  if (file_exists($environment_settings)) {
    include $environment_settings;
  }
}
// Temporary fix because drush9 blocks superglobals
$_SERVER['PWD']=DRUPAL_ROOT;

if (file_exists('/var/www/site-php')) {
  require('/var/www/site-php/naswa/naswa-settings.inc');
}
```

Finally you'll need some subsite aliases so that drush can find your site

drush/sites/site-aliases/naswa.site.yml

```
local:
  uri: 'https://site1.lndo.site'
  paths:
  - files: /Users/brookeheaton/Sites/site1/docroot'
  - drush-script: 'drush8'
dev:
  host: 'site1dev.ssh.prod.acquia-sites.com'
  user: 'site1.dev'
  root: '/var/www/html/site1.dev/docroot'
  uri: 'site1dev.prod.acquia-sites.com'
  ac-site: 'site1'
  ac-env: 'dev'
  ac-realm: 'prod'
  paths:
    drush-script: 'drush8'
test:
  root: '/var/www/html/site1.test/docroot'
  ac-site: 'site1'
  ac-env: 'test'
  ac-realm: 'prod'
  uri: 'site1stg.prod.acquia-sites.com'
  host: 'site1stg.ssh.prod.acquia-sites.com'
  user: 'site1.test'
  paths:
    drush-script: 'drush8'
prod:
  root: '/var/www/html/site1.prod/docroot'
  ac-site: 'site1'
  ac-env: 'prod'
  ac-realm: 'prod'
  uri: 'site1.prod.acquia-sites.com'
  host: 'site1.ssh.prod.acquia-sites.com'
  user: 'site1.prod'
  paths:
    drush-script: 'drush8'
```

**Comment by nalipaz** [comment]
@brooke-heaton nice work on documenting what you did. Good catch on the superglobals issue. Also interesting solution for the drush aliases at the end there. If you read the README.md in my repo you will understand the approach I use for drush aliases of the upstream servers. My approach is more to just add aliases on each of the Acquia servers and then copy those aliases to my lando as well. I find that having those sorts of aliases on the Acquia servers eases management when I am on one of those servers.

**Comment by brooke-heaton** [comment]
@nalipaz Yes, teh supserglobals bug had Acquia support stumped for days. I finally found a mention of this on the [Acquia BLT repo](https://github.com/acquia/blt/issues/2527). hm, good point on the aliases. In my case, I found that the aliases worked for drush 8 but not drush 9. I'm using drush 9 locally and have it defined in my composer.json however I have not added drush9 aliases to the Acquia Cloud as it seems unadvisable. I also don't seem to have aliases for the multisites on the cloud. I may be doing something wrong, but I understand that we have to define our own multisite aliases. I may be confused.

**Comment by nalipaz** [comment]
I certainly don't think you are doing anything wrong. You are right that Acquia documentation advises against adding your own aliases. However their documentation likely advises against multisites and lots of stuff doesn't work correctly with multisites. That said I opted to add my own to ease my life. I used the main aliases they provide as the parent of my aliases so that it minimizes what I have to declare. As seen here: https://github.com/nalipaz/lando-acquia-multisite-recipe/blob/master/acquia-servers/home/appname/.drush/site-aliases/appname.aliases.drushrc.php

**Comment by brooke-heaton** [comment]
Ah, I see what you do there. I may adopt that practice. I guess that also gets around the need to define them in drush/sites ?

**Comment by nalipaz** [comment]
Sorry I don't quite understand your question. You are defining them in drush by adding to the site-aliases.

**Comment by brooke-heaton** [comment]
@nalipaz Yea, totally bad phrasing on my part - in other words you don't need to define each site in a yml, you can dynamically build the aliases in the `drushrc.php`. What stumped me was that drush 9 uses a yaml definition for each alias, but maybe it's not required? I see you build a function in php to do the same. That works with drush 9?

**Comment by nalipaz** [comment]
ah, I understand the question now.

my Acquia server:
```
$ drush --version
 Drush Version   :  8.1.15
```
my lando installation:
```
$ lando drush --version
 Drush Version   :  8.1.15
```
Guess I wouldn't know the answer to your question, sorry.

**Comment by brooke-heaton** [comment]
Yea, drush 9 introduces various dragons.

**Comment by pirog** [comment]
@nalipaz @brooke-heaton this is great and super helpful. Either of you have any energy to try and write up a lando tutorial for our docs?

**Comment by brooke-heaton** [comment]
@pirog I think @nalipaz is the real pioneer and expert here and I've honestly just cribbed his approach, but I do owe the Lando community so I'm happy to do whatever I can. I'm happy to lend a hand however I can.

**Comment by markdorison** [comment]
Is it possible to configure a multisite to use a single database container with multiple databases within it? In `lando db-import --help` I see a way to specify a `--host` value but I do not see any way to tell lando to import the database to anywhere but the default database.

**Comment by brooke-heaton** [comment]
@markdorison you can use one container, but you need a separate service for the other database. I do this for migrations - the extra mysql service being used for a legacy database - for which you can specify a host. For instance in my `.lando.yml` I have this:

```
services:
  migrate_source:
    type: 'mysql:5.7'
    portforward: 33069
    config:
      confd: .lando/mysql/conf.d
```

So that allows me to run this: `lando db-import dump.zip --host migrate_source`

And that ill import the database to that service.

On the Drupal side, I have this second database defined in my `settings.local.php` thus:

```
$databases['migrate']['default'] = [
  'database' => 'database',
  'username' => 'mysql',
  'password' => 'mysql',
  'host' => 'migrate_source',
  'port' => '3306',
  'driver' => 'mysql',
  'prefix' => '',
  'collation' => 'utf8mb4_general_ci',
];
```
