### ISSUE TITLE
Create a custom service for selenium

### ISSUE THREAD

**Issue by miiimooo** [lando/lando#442]
Feature/Enhancement Request
===========================

**As a lando user who works with Drupal sites that do automatic behat testing I want to be able to use selenium**

I have experimented with something like this to run selenium with some nice features (vnc, screenshots, video recording) but I don't think it's the right way to do it.

```yml
  selenium:
    type: apache:custom
    overrides:
      services:
        environment:
          TZ: "US/Pacific"
        image: elgalu/selenium:latest
        privileged: true
        ports:
          - 4444:24444
          - 5900:25900
        volumes:
          - /dev/shm:/dev/shm
```

I can run the container manually like this:

```
docker run -d --name=grid -p 4444:24444 -p 5900:25900 -e TZ="US/Pacific" -v /dev/shm:/dev/shm --privileged elgalu/selenium
```
