### ISSUE TITLE
Can we replace the nginx startup command?

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#443]
This command is executed on the NGINX service: 

`/bin/sh -c envsubst '$LANDO_WEBROOT' </etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'`

I want to replace it with: 

`/bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'`

I'm using the following in my .lando.yml.

```
services:
  appserver:
    type: php:7.0

    # Served by the latest nginx
    via: nginx
```

I thought maybe the override key would be the place for this to live, or "command" but the nginx service fails to launch because the config contains variables of mine that were not replced.

**Comment by pirog** [comment]
@tylerssn you can definitely replace the `nginx` start up command using `overrides`

```yaml
services:
  appserver:
    type: php:7.0
    via: nginx
    overrides:
      services:
        command: my custom nginx command
```

That said, our default nginx file assumes that $LANDO_WEBROOT is going to be replaced so im guessing you'll probably want your own nginx file as well

```yaml
services:
  appserver:
    type: php:7.0
    via: nginx
    config:
      server: config/mycustomnginx.conf
    overrides:
      services:
        command: my custom nginx command
```

Where `config/mycustomnginx.conf` is relative to your app root
