### ISSUE TITLE
Lando build fails with pip install

### ISSUE THREAD

**Issue by cancerballs** [lando/lando#444]
Bug Report
==========

I'm running OS X **10.12.6** and lando version **v3.0.0-beta.21**

**`.lando.yml`**

```yml
# Python app
name: test

# Give me http://python.lndo.site and https://python.lndo.site
proxy:
  appserver:
    - python.lndo.site:5000

# Spin up services to run a basic python server
services:

  # Create a python instance
  appserver:

    # Python version 3.6
    type: python:3.6

    # Optionally create certs in /certs that can be used by your application
    # to listen over https. Creates the following certs your app can use
    #
    #   - /certs/cert.key
    #   - /certs/cert.crt
    #   - /certs/cert.pem
    #
    # ssl: true

    # Optionally specify a command/script to run when you start your python service up.
    #
    # If you are using python as a server you are going to want to define this.
    # This can be either a string or array.
    #
    # If you are just spinning up a python container for usage as a cli tool
    # you can leave this blank and the container will boot up and stay on
    #
    # You will likely want to run needed build steps eg `lando pip install`
    # first so needed dependencies are installed before your server starts up.
    #
    # command: python /app/server.py
    command: python -m flask run

    # Install some extra server packages
    extras:
     - "apt-get update -y"
     - "apt-get install python-pip python-dev build-essential"
    overrides:
      services:
        ports: ['5000:5000']

    # Print a message just to demonstrate this
    build:
      - cd $LANDO_MOUNT && echo 'Holla!'
      - cd $LANDO_MOUNT && pip install flask

# Add some nice command routing
tooling:

  # Any python service with a defined command (aka not running in cli only mode)
  # Will also spin up a python cli container called `SERVICENAME_cli` (appserver_cli)
  # in this example.
  #
  # This will allow you to run things like `lando pip install` without needing
  # to `lando start` first. This is particularly needed for python based projects
  # since you almost always need to run `pip install` before you can boot up your
  # app successfully.
  pip:
    service: appserver_cli
  python:
    service: appserver_cli
  easy_install:
    service: appserver_cli
  pyvenv:
    service: appserver_cli

  # This will only be available if you run `lando pip install livereload` first
  livereload:
    service: appserver_cli

```

Running `lando rebuild` returns an error.

```bash
➜  lando-test lando rebuild
? Are you sure you want to rebuild? Yes
Stopping test_appserver_cli_1 ... done
Removing test_appserver_cli_1 ... done
Removing test_appserver_1     ... done
Pulling appserver (python:3.6-jessie)...
Pulling appserver_cli (python:3.6-jessie)...
appserver uses an image, skipping
appserver_cli uses an image, skipping
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating test_appserver_1 ...
Creating test_appserver_cli_1 ...
Creating test_appserver_cli_1
Creating test_appserver_1 ... done
error:  message=, code=137
```

`--verbose` does not give any more information.

To replicate this bug copy the .land.yml file and run rebuild.

I've followed the steps in the documentation. This bug prevents me from using lando.

**Comment by iler** [comment]
Any idea on this? This is currently preventing us to use Lando which we would really much want to

**Comment by pirog** [comment]
@iler @cancerballs going to be investigating this later. As you may have inferred already Lando is (currently) mostly used for php development so our support and stability for other frameworks is lagging behind. 

Tickets like this definitely help us set priorities and focus on the other frameworks/languages so thanks for surfacing this.

**Comment by pirog** [comment]
This should be improved in teh next release 

for an example that uses a livereload server, flask and a `requirements.txt`  see 
https://github.com/lando/lando/tree/master/examples/flask and remember to `lando pip install -r requirements.txt` before `lando start`

**Comment by silverham** [comment]
Since this is the only result on google search with "error code 137" and lando, I thought I would add what solved it for me.

I was converting a custom docker compose yml with an image to using a lando file, with the [lando service](https://docs.lando.dev/core/v3/lando-service.html).
I didn't understand the [instructions](https://docs.lando.dev/core/v3/lando-service.html#setting-the-command) and so I had only the `[entrypoint]` in the lando `command` property, but instead it should of been of `[entrypoint] + [command]` in the `command` property (if you keep the original `[entrypoint]` then, you lose the lando secret sauce, so you must manually specifiy it, so lando adds its own with yours when it starts the containers). 

To give example.
I was using image: https://hub.docker.com/layers/govcms/govcms/10.x-latest/images/sha256-62ef083979b5ea55a33c8313eff8bdcb27e373b4f02d1fa515cb2a231e0e81a8?context=explore

Which had in the dockerfile:
```lang-sh
ENTRYPOINT ["/sbin/tini" "--" "/lagoon/entrypoints.sh"]
CMD ["/bin/docker-sleep"]
```

So then my lando file should of been:
```yml
services:
  myservicename:
    api: 3
    type: lando
    services:
      [...]
      # Set Dockerfile entrypoint & CMD together so lando uses it secret sauce.
      command: /sbin/tini -- /lagoon/entrypoints.sh /bin/docker-sleep
```
