### ISSUE TITLE
Location logs in container

### ISSUE THREAD

**Issue by MikeWong1991** [lando/lando#460]
I was reading the docs concerning logs and was wondering where the  logs are stored within the container? 

I checked /var/log but could not see where the logs were located that I can see though a lando logs -s command.  

**Tell us about your setup**

What is your lando version and operating system?

*Example: v3.0.0-alpha1 on macosx sierra

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

```yml
name: example
recipe: drupal8
proxy:
  nginx:
    - example.dev
  mailhog:
    - mailhog.example.dev
  solr:
    - solr.example.dev:8983
config:
  webroot: web
  via: nginx
  xdebug: true
  conf:
    php: php.ini
services:
  appserver:
    extras:
      - "apt-get update -y"
      # To run this from drupal use "/usr/bin/xvfb-run /usr/bin/wkhtmltopdf" as a command because else it won't work on
      # some linux OS versions.
      - "apt-get install wkhtmltopdf -y"
      - "apt-get install xvfb -y"
      - "ln -sf /app/phpmemcachedadmin /app/web/phpmemcachedadmin"
      - "ln -sf /app/adminer.php /app/web/adminer.php"
      - "ln -sf /app/simplesamlphp/log /app/web/vendor/simplesamlphp/simplesamlphp/"
      - "ln -sf /app/simplesamlphp/metadata /app/web/vendor/simplesamlphp/simplesamlphp/"
      - "ln -sf /app/simplesamlphp/config /app/web/vendor/simplesamlphp/simplesamlphp/"
      - "touch /var/log/php-scripts.log"
  solr:
    type: solr:5.5
    portforward: true
    core: project
    config:
      conf: solrconf
  memcache:
    type: memcached:1.5
    mem: 128
    portforward: true
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true

# Add in some custom event scripting. All command line tooling defined have a post event automatically defined.
# For instance the above phantomsjs and phpunit tooling will have a post-phantomjs and post-phpunit event which can be
# used.
# https://docs.devwithlando.io/config/events.html
events:

```

** php.ini file **
```php

;;;;;;;;;;;;;;;
; PHP Globals ;
;;;;;;;;;;;;;;;

short_open_tag = Off
output_buffering = 4096
allow_call_time_pass_reference = Off
variables_order = "GPCS"
request_order = "GP"
register_long_arrays = Off
register_argc_argv = Off
magic_quotes_gpc = Off
enable_dl = Off
allow_url_fopen = On
realpath_cache_size = "800K"
realpath_cache_ttl = "86400"
disable_functions =
;include_path = ".:/usr/share/pear:/usr/share/php"

[Date]
date.timezone = "UTC"

;;;;;;;;;;;;;;;;;;;;;;
;; PACKAGE SETTINGS ;;
;;;;;;;;;;;;;;;;;;;;;;

; Xdebug
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
xdebug.profiler_enable_trigger = on
xdebug.remote_enable = on
xdebug.remote_host = ${LANDO_HOST_IP}

; Globals
expose_php = on
max_execution_time = 300
max_input_time = 900
max_input_vars = 10000
memory_limit = 1024M
upload_max_filesize = 100M
post_max_size = 100M
error_reporting = E_ALL & ~E_DEPRECATED
ignore_repeated_errors = on
html_errors = off
display_errors = on
log_errors = on
error_log = /var/log/php-scripts.log



```
