### ISSUE TITLE
Tooling documentation - indentation issue

### ISSUE THREAD

**Issue by mourogers** [lando/lando#489]
There's an indentation issue in docs/tutorials/frontend.md under 'Adding Grunt/Gulp/Etc.':

```
services:
  node:
    type: node:6.10
    build:
      - "cd $LANDO_MOUNT && npm install"
      - "cd $LANDO_MOUNT && gulp"
globals:
  gulp-cli: "latest"
```

'globals' should be under 'node', I think:

```
services:
  node:
    type: node:6.10
    build:
      - "cd $LANDO_MOUNT && npm install"
      - "cd $LANDO_MOUNT && gulp"
    globals:
      gulp-cli: "latest"
```
