### ISSUE TITLE
Expounding upon supporting versions in mariaDB  doc

### ISSUE THREAD

**Issue by lyleRpalagar** [lando/lando#500]
**Tell us about your setup**
OS = macOS Sierra Version 10.12.6 , Lando version =  lando-v3.0.0-beta.24.dmg

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

*Example:*

```yml
name: dotcom
recipe: drupal7
services:
  appserver:
    build:
      - "curl -sS https://platform.sh/cli/installer | php"
    config:
      conf: php.ini
  database:
    portforward: 8993
  cache:
    type: redis
    persist: true
    portforward: 6379
tooling:
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd:
      - /var/www/.platformsh/bin/platform
    options:
      passthrough: true
  redis-cli:
    service: cache
config:
  via: nginx
  webroot: _www
  database: mariadb:10.1
```
**Tell us about the command you were running**
```bash
lando rebuild -y 
# checked to see if everything was running
# open up new terminal 
docker ps -a 
# notice that i had mariadb:10.1 not running
8366fc3e671a        mariadb:10.1               "/lando-entrypoint..."   2 minutes ago       Exited (1) 2 minutes ago                                                                          dotcom_database_1
docker rm 8366fc3e671a
# did another lando  rebuild -y
# same issue, so i checked logs
lando logs 
```

**Tell us about the error you got**

```bash
database_1   | 2017-11-15 16:01:10 140537640757184 [Note] InnoDB: Using SSE crc32 instructions
database_1   | 2017-11-15 16:01:10 140537640757184 [Note] InnoDB: Initializing buffer pool, size = 384.0M
database_1   | 2017-11-15 16:01:10 140537640757184 [Note] InnoDB: Completed initialization of buffer pool
database_1   | 2017-11-15 16:01:10 140537640757184 [Note] InnoDB: Highest supported file format is Barracuda.
database_1   | InnoDB: No valid checkpoint found.
database_1   | InnoDB: A downgrade from MariaDB 10.2.2 or later is not supported.
database_1   | InnoDB: If this error appears when you are creating an InnoDB database,
database_1   | InnoDB: the problem may be that during an earlier attempt you managed
database_1   | InnoDB: to create the InnoDB data files, but log file creation failed.
database_1   | InnoDB: If that is the case, please refer to
database_1   | InnoDB: http://dev.mysql.com/doc/refman/5.6/en/error-creating-innodb.html
database_1   | 2017-11-15 16:01:10 140537640757184 [ERROR] Plugin 'InnoDB' init function returned error.
database_1   | 2017-11-15 16:01:10 140537640757184 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
database_1   | 2017-11-15 16:01:10 140537640757184 [Note] Plugin 'FEEDBACK' is disabled.
database_1   | 2017-11-15 16:01:10 140537640757184 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
database_1   | 2017-11-15 16:01:10 140537640757184 [ERROR] Unknown/unsupported storage engine: innodb
database_1   | 2017-11-15 16:01:10 140537640757184 [ERROR] Aborting
database_1   | 
```

**Tell us generally about your bug**

Whenever I tried to run `lando mysql` i would get  this error 
```bash
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
```
which told me that my database service isnt starting

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
In slack Pirog explained that it was because i was jumping versions from high -> low which could cause this problem and that i would need to run a `lando destroy`  and then `lando rebuild` to resolve the situation. 

Feature/Enhancement Request
===========================

Please explain your request and its importance in the form of a user story.

As a lando user who works with Drupal sites, I want more elaboration on the documentation for mariadb explaining that even though Lando supports older versions if you edit your lando.yml file from a higher version to a lower version there could be issues with your build 
Please provide some detail on how lando can help solve this problem
