### ISSUE TITLE
SSL proxy headers seem broken in WordPress

### ISSUE THREAD

**Issue by nullvariable** [lando/lando#503]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?

v3.0.0-beta.22  Win10 Pro

**Tell us about your `.lando.yml`**

```yml
name: <client>
recipe: wordpress
config:
  webroot: .
  xdebug: true

proxy:
  pma:
    - pma.<client>.lndo.site

services:
  cli:
    type: node:6
  pma:
    type: phpmyadmin
    hosts:
      - database

tooling:
  npm:
    service: cli
  node:
    service: cli
```

**Tell us about the command you were running**

```bash
lando init --recipe=wordpress
lando start
# Edited my lando.yml as above
lando rebuild -y
lando ssh
wp core download
wp create config --dbname=$DB_NAME --dbhost=$DB_HOST --dbuser=$DB_USER --dbpass=$DB_PASSWORD
exit
lando db-import <db>
lando wp search-replace <original> https://wordpress.lndo.site
```

**Tell us about the error you got**

Redirect loop

**Tell us generally about your bug**

Copied a WP site locally that had force ssl enabled for admin pages. You can replicate this like

```bash
lando wp option update siteurl 'https://wordpress.lndo.site'
```
and then attempt to access the site at https://wordpress.lndo.site

**Tell us more**

The relevant code in WordPress core is: `wp-includes/default-constants.php:287` which forces connections to https if https is found in the `siteurl` option. WordPress uses the `is_ssl` function to determine if a request is secure (`wp-includes/load.php:967`). This function relies on the `$_SERVER['HTTPS']` variable being set to `on`. Inspecting this variable in the site shows that because there's a proxy involved in the request, apache doesn't see the request as being secure.

Does this bug prevent you from using lando?
no, I've temporarily overridden the `$_SERVER['HTTPS']` variable in the wp-config. Another option would be to search-replace urls from https to http.

I believe that just passing the right headers from the proxy should resolve this issue.
