### ISSUE TITLE
Feature Request: Add Blackfire as a component of Lando 

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#511]
Since Blackfire does not add any overhead when not in use, it would be nice to have a parameter in our Lando config that toggled Blackfire. Something like: `blackfire: true`

Currently I am installing the Blackfire PHP extensions by extending the devwithlando/php image with:

    services:
      appserver:
        type: php:7.0
        overrides:
          services:
            image: my/lando-blackfire-php:7.0
        extras:
          ##########
          # Blackfire setup
          - "bash $LANDO_MOUNT/dev/lando/deploy/blackfire/init.sh"

The file located at `$LANDO_MOUNT/dev/lando/deploy/blackfire/init.sh` contains:

    # Configure Repo
    wget -O - https://packagecloud.io/gpg.key | apt-key add -
    echo "deb http://packages.blackfire.io/debian any main" | tee /etc/apt/sources.list.d/blackfire.list
    apt-get update
    
    # Install agent
    echo "Installing blackfire agent"
    apt-get -yqq install blackfire-agent
    echo -e "yes\n$BLACKFIRE_SERVER_ID\n$BLACKFIRE_SERVER_TOKEN" | blackfire-agent --register
    /etc/init.d/blackfire-agent restart
    
    # Install the Cli Tool
    echo -e "$BLACKFIRE_CLIENT_ID\n$BLACKFIRE_CLIENT_TOKEN" | blackfire config

I have a `.env` file that contains the `BLACKFIRE_*` variables referenced in the bash script above.

**Comment by jbertoen** [comment]
Love to pick this up @serundeputy, if you are not already working on it.

**Comment by jbertoen** [comment]
Some documentation from blackfire for reference: https://blackfire.io/docs/integrations/docker

**Comment by dmsmidt** [comment]
Working on this!

**Comment by jbertoen** [comment]
Hurry up or I'll take over @dmsmidt  😆 🤣

**Comment by serundeputy** [comment]
@jbertoen @dmsmidt here is what I had going; https://github.com/serundeputy/lando/tree/511-blackfire if it helps

**Comment by dmsmidt** [comment]
@serundeputy thanks, used some of your work.
I've got the integration working in https://github.com/dmsmidt/lando/tree/511-blackfire-support.

Still some things I want to work out. Like not using the entry-point script.. and maybe adding a blackfire agent cli tool `lando blackfire <url>`

**Comment by dmsmidt** [comment]
With this setup `lando ssh blackfire` doesn't work since the www-data user and bash are not present. Do we really need this?

**Comment by serundeputy** [comment]
> and maybe adding a blackfire agent cli tool lando blackfire <url>

yes; we want to have this for sure!

**Comment by tylerssn** [comment]
Great work, all. Thanks for donating your *extremely* valuable time to this amazing tool.

**Comment by RistoNiinemets** [comment]
What's the status on this? That would be really neat. I could help testing it, somehow.

**Comment by dustinleblanc** [comment]
@RistoNiinemets thanks to @mmenavas this is virtually at the finish line, however, we've put merging in new feautres essentially on a deep freeze while we sprint like hell on tests.

**Comment by Auspicus** [comment]
@dustinleblanc Now that test coverage has been taken care of in the latest release is this one back in the line of sight for you guys?

**Comment by serundeputy** [comment]
One idea that has been bounced around is to make this a `lando/contrib` plugin.  Then if we see a lot of usage on the plugin (or any plugin) that data can drive decisions for `lando/lando` ... so if someone has bandwidth on turning this PR into a plugin that could be the next step to continue momentum for blackfire + lando.

https://docs.devwithlando.io/dev/plugins.html

**Comment by tylerssn** [comment]
I am happy to work on converting this to a plugin once a decision is made on [this plugin PR](https://github.com/lando/lando/pull/1169).

**Comment by tylerssn** [comment]
I Started diving into this (https://github.com/lando/lando/commit/f20536712f9cb129492b7c032dfb1bc21a3ea957) a bit. It still requires that you manually install the PHP extension.

In testing, I had to do the following so that I could profile the example Blackfire environment.

```yaml
tooling:
  "blackfire:add-php-cli":
    service: appserver
    uses: blackfire
    user: root
    cmd:
      - version=$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;"); curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$version;
      - mkdir -p /tmp/blackfire
      - tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp/blackfire
      - mv /tmp/blackfire/blackfire-*.so $(php -r "echo ini_get('extension_dir');")/blackfire.so;
      - printf "extension=blackfire.so\nblackfire.agent_socket=tcp://blackfire:8707\n" > $PHP_INI_DIR/conf.d/blackfire.ini;
      - rm -rf /tmp/blackfire /tmp/blackfire-probe.tar.gz;
      - echo "\n\n\n ===> Execute 'lando restart' to apply the changes \n\n"
```
