### ISSUE TITLE
Read timeout when restarting lando

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#515]
**What is your lando version and operating system?** v3.0.0-beta.21 on MacBook Pro High Sierra (10.13.1)

**.lando.yml**

```yml
name: magento
proxy:
  nginx:
    - ${LANDO_HOST}
  solr:
    - solr.lndo.site:8983
services:
  appserver:
    type: php:7.0
    via: nginx
    ssl: true
    webroot: web
    xdebug: false
    config:
      server: dev/lando/config/nginx/default.conf
      conf: dev/lando/config/php/php.ini
    composer:
      overtrue/phplint: '*'
    build:
      - "cd $LANDO_MOUNT && composer install || true"
      - "curl -s -O https://files.magerun.net/n98-magerun.phar && chmod +x ./n98-magerun.phar && mv ./n98-magerun.phar /usr/local/bin/magerun"
      - "curl -s -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp"
      - "bash $LANDO_MOUNT/dev/lando/deploy/init.sh"
    extras:
      - "apt-get -yqq update"
  magento-db:
    type: mysql:5.6
    portforward: true
    creds:
      user: ${LANDO_MAGENTO_DB_USER}
      password: ${LANDO_MAGENTO_DB_PASS}
      database: ${LANDO_MAGENTO_DB_NAME}
  wordpress-db:
    type: mysql:5.6
    portforward: true
    creds:
      user: ${LANDO_WORDPRESS_DB_USER}
      password: ${LANDO_WORDPRESS_DB_PASS}
      database: ${LANDO_WORDPRESS_DB_NAME}
  redis-cache:
    type: redis
    portforward: true
  redis-session:
    type: redis
    portforward: true
  solr:
    type: solr:3.6
    portforward: true
    config:
      conf: lib/Apache/Solr/conf
tooling:
  phplint:
    service: appserver
  magerun:
    service: appserver
    user: www-data
    cmd: magerun
  exec:
    service: appserver
    description: Execute commands within the appserver
    user: www-data
    cmd: ""
  composer:
    service: appserver
    description: Run composer commands
    cmd:
      - composer
      - --ansi
  php:
    service: appserver
  mysql:
    user: root
    service: database
    description: Drop into a MySQL shell
  'app:init':
    service: appserver
    needs:
      - wordpress-db
      - magento-db
    description: Get current platformy branch db dump and import into local DB
    cmd:
      - ./dev/lando/deploy/init.sh
  'db-import ':
    service: appserver
    needs:
      - wordpress-db
      - magento-db
    description: Import into database
    cmd: /helpers/mysql-import.sh
    options:
      host:
        description: The database host
        alias:
          - h
      user:
        description: The database user
        default: root
        alias:
          - u
      database:
        description: The database name
        alias:
          - d
      password:
        description: The database password
        alias:
          - p
      port:
        description: The database port
        default: 3306
        alias:
          - P
```

**Recreate the problem**
I when executing `lando restart`, `lando rebuild` (after a stop), or `lando start` (after a stop) I get the following error:

```text
ERROR: for magento_appserver_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for magento_magento-db_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for magento_wordpress-db_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

...

ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```
The only way to resolve this is by rebooting my host machine.
