### ISSUE TITLE
Decrease amount of unnecessary volume mapping in some services

### ISSUE THREAD

**Issue by jbertoen** [lando/lando#518]
Feature/Enhancement Request
===========================
Currently all services get the same volume mappings:
```
services:
  some_service:
    volumes:
      - '$LANDO_ENGINE_SCRIPTS_DIR/lando-entrypoint.sh:/lando-entrypoint.sh'
      - '$LANDO_APP_ROOT_BIND:/app:delegated'
      - '$LANDO_ENGINE_HOME:/user:delegated'
      - '$LANDO_ENGINE_SCRIPTS_DIR/user-perms.sh:/user-perms.sh'
      - >-
        /Users/jeffreybertoen/.lando/services/config/scripts/load-keys.sh:/scripts/load-keys.sh
      - >-
        /Users/jeffreybertoen/.lando/services/config/helpers/mysql-import.sh:/helpers/mysql-import.sh
      - >-
        /Users/jeffreybertoen/.lando/services/config/helpers/mysql-export.sh:/helpers/mysql-export.sh

```
For stuff like mysl, solr, mailhog and such, it could be much cleaner. The app, user, and probably the scripts do not have to be mapped as volumes. It will cause a lot of unnecessary syncing of files when developing on services that have no use with these volumes.
I get that for like nginx, php, these are necessary.

Therefor you would expect that the following would "override" this setup:
```
services:
  some_service:
    overrides:
       services:
         volumes:
           - '$LANDO_ENGINE_SCRIPTS_DIR/lando-entrypoint.sh:/lando-entrypoint.sh'
```

But instead it "adds" these mapping to the list of mappings. Shouldn't we correct this to make it really an override that replaces settings instead of adding them.

If we want to have some sort of merging of docker-compose settings we can already use:
```
compose:
  - compose.yml
```
The biggest gain would be file syncing performance that would improve because we can lower the amount of files begint synced to multiple containers.

**Comment by pirog** [comment]
@jbertoen i definitely understand the thinking behind both proposals here but i dont think these are things we can easily change given they are pretty low level assumptions and changing them would require a lot of work to both the documentation and a slew of impacted code with likely a whole bunch of regressions we'd only discover after the fact.

If there were significant gains we could see from such a change i'd be all for considering it but based on how i understand how docker mounting works i dont think this is very different than what we currently do. eg there is not a huge difference between mounting your user folder into one container vs 5 containers.

Im going to close this for now. That said, If you feel like i am totally wrong on the performance implications here (which i totally could be) and want to provide some sort of *replicable* benchmark then feel free to reopen this and heckle me with an appropriate "i told you so".

**Comment by jbertoen** [comment]
@pirog I will benchmark this, I know the guys at amazee.io work with the docker guys and have build a benchmarking tool.
It is a recommendation from them to "exclude" ad many files as possible from the syncing as that is the source of the biggest performance issues. For instance, letting the "vendor" folder exist in a top level volume and not mapping it to OSX for syncing increases my build time exponentially. Even more when doing a composer install after doing 
`composer global require hirak/prestissimo`
If yo feel like benchmarking this just for fun, you could experience the difference when doing the follwoing:

Use the drupal 8 recipe and add the following to your .lando:
```
appserver
  overrides:
     services:
       volumes:
         - /app/vendor/
         -/app/core
```
Try a composer install and/or create project process for drupal with this. You probably experience the difference.

Btw, this: `composer global require hirak/prestissimo` will download all vendor libraries in parallel and that add them directly from cache. Something I picked up form here:
http://jackmcdade.com/blog/tired-of-waiting
Also NPM performance improvements are gained by not doing `npm install -g MODULE@VERSION ` but doing "yarn global add MODULE@VERSION"

**Comment by jbertoen** [comment]
@pirog ,
Could you reopen it and assign it to me? So I will give you the desired benchmarks and maybe even the fix. At least I will produce a set of workarounds so that people can improve docker performance issues when running a lot of containers and doing a lot of file changes.

**Comment by pirog** [comment]
@jbertoen definitely agreed its best to limit the files, im on board with that. that said, a large part of that is on the user. the two things that i think are worth mentioning are

1. i dont think there is a big difference between mounting the same directory in one container vs multiple containers because its still the same underlying mount point at the end of the day. so *i dont think* removing "unneeded" mounts from one container that are mounted in another container is going to give significant gains.
2. from a usability standpoint i don't think we want to enforce or restrict how the user has to set up their project. i realize that having `vendor` or `node_modules` shared into the container does slow things down a bit but it doesnt seem to be a deal breaker, docker is making improvement there and we've done that sort of thing in the best and people generally didnt like it.

**Comment by pirog** [comment]
@jbertoen but yah if you have energy around doing benchmarks, go for it!

**Comment by jbertoen** [comment]
**Composer install without ignore**

```yml
name: projectname
recipe: drupal8
proxy:
  nginx:
    - projectname.localhost
  mailhog:
    - mailhog.projectname.localhost
  solr:
    - solr.projectname.localhost:8983
  docs:
    - docs.projectname.localhost
  node:
    - node.projectname.localhost:3000
config:
  webroot: web
  via: nginx
services:
  solr:
    type: solr:6.4
    portforward: true
    core: project
    config:
      conf: solrconf
  redis:
    type: redis:4.0
    portforward: true
    type: mailhog
    hogfrom:
      - appserver
    portforward: true

  docs:
    # Use nginx version 1.12
    type: nginx:1.12

    # Optionally specify a webroot if your index.html is in a subdirectory
    webroot: documentation
  node:
    type: node:8.4

# Add some nice command routing
tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  gulp:
    service: node

# A list of docker compose files to load relative to my app root directory
compose:
 - compose.yml

```

1
2017-11-20T08:20:59.490Z
2017-11-20T08:27:46.876Z
2
2017-11-20T08:42:50.698Z
2017-11-20T08:48:39.883Z
3
2017-11-20T08:59:33.237Z
2017-11-20T09:05:39.954Z

_About 6 minutes for composer install_

**Composer install only on appserver defined volumes without sync to OSX**

``` yml
name: projectname
recipe: drupal8
proxy:
  nginx:
    - projectname.localhost
  mailhog:
    - mailhog.projectname.localhost
  solr:
    - solr.projectname.localhost:8983
  docs:
    - docs.projectname.localhost
  node:
    - node.projectname.localhost:3000
config:
  webroot: web
  via: nginx
services:
  appserver:
    overrides:
       services:
         volumes:
           - /app/vendor/
           - d8_core:/app/web/core/
           - d8_libraries:/app/web/libraries/
           - d8_modules_contrib:/app/web/modules/contrib
           - d8_modules_synetic:/app/web/modules/synetic
           - d8_profiles:/app/web/profiles
           - d8_themes_contrib:/app/web/themes/contrib
           - public_files:/app/web/sites/default/files/
           - public_files:/app/files/public
           - private_files:/app/files/private
  solr:
    type: solr:6.4
    portforward: true
    core: project
    config:
      conf: solrconf
    overrides:
       services:
         volumes:
           - /app/vendor/
           - /app/web/core/
           - /app/web/libraries/
           - /app/web/modules/contrib
           - /app/web/modules/synetic
           - /app/web/profiles
           - /app/web/themes/contrib
           - /app/web/sites/default/files/
           - /app/files/public
           - /app/files/private
  redis:
    type: redis:4.0
    portforward: true
    overrides:
       services:
         volumes:
           - /app/vendor/
           - /app/web/core/
           - /app/web/libraries/
           - /app/web/modules/contrib
           - /app/web/modules/synetic
           - /app/web/profiles
           - /app/web/themes/contrib
           - /app/web/sites/default/files/
           - /app/files/public
           - /app/files/private
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
    overrides:
       services:
         volumes:
           - /app/vendor/
           - /app/web/core/
           - /app/web/libraries/
           - /app/web/modules/contrib
           - /app/web/modules/synetic
           - /app/web/profiles
           - /app/web/themes/contrib
           - /app/web/sites/default/files/
           - /app/files/public
           - /app/files/private

  docs:
    # Use nginx version 1.12
    type: nginx:1.12
    overrides:
       services:
         volumes:
           - /app/vendor/
           - /app/web/core/
           - /app/web/libraries/
           - /app/web/modules/contrib
           - /app/web/modules/synetic
           - /app/web/profiles
           - /app/web/themes/contrib
           - /app/web/sites/default/files/
           - /app/files/public
           - /app/files/private

    # Optionally specify a webroot if your index.html is in a subdirectory
    webroot: documentation
  node:
    type: node:8.4
    overrides:
       services:
         volumes:
           - /app/vendor/
           - /app/web/core/
           - /app/web/libraries/
           - /app/web/modules/contrib
           - /app/web/modules/synetic
           - /app/web/profiles
           - /app/web/themes/contrib
           - /app/web/sites/default/files/
           - /app/files/public
           - /app/files/private

# Add some nice command routing
tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  gulp:
    service: node

# A list of docker compose files to load relative to my app root directory
compose:
 - compose.yml

```

1
2017-11-20T07:29:43.650Z
2017-11-20T07:32:46.603Z
2
2017-11-20T07:38:00.073Z
2017-11-20T07:41:05.910Z
3
2017-11-20T07:57:27.057Z
2017-11-20T08:00:38.058Z

_About 3 minutes for composer install_

**Composer install with ignores on solo, reds, mailhog, nginx,nodejs to prevent file syncing of composer vendor, drupal core, contrib modules, profiles and themes.**

``` yml
name: projectname
recipe: drupal8
proxy:
  nginx:
    - projectname.localhost
  mailhog:
    - mailhog.projectname.localhost
  solr:
    - solr.projectname.localhost:8983
  docs:
    - docs.projectname.localhost
  node:
    - node.projectname.localhost:3000
config:
  webroot: web
  via: nginx
services:
  solr:
    type: solr:6.4
    portforward: true
    core: project
    config:
      conf: solrconf
  redis:
    type: redis:4.0
    portforward: true
    type: mailhog
    hogfrom:
      - appserver
    portforward: true

  docs:
    # Use nginx version 1.12
    type: nginx:1.12

    # Optionally specify a webroot if your index.html is in a subdirectory
    webroot: documentation
  node:
    type: node:8.4

# Add some nice command routing
tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  gulp:
    service: node

# A list of docker compose files to load relative to my app root directory
compose:
 - compose.yml
```


1
2017-11-20T10:18:41.842Z
2017-11-20T10:23:31.624Z
2
2017-11-20T10:36:14.496Z
2017-11-20T10:41:45.375Z
3
2017-11-20T10:44:33.665Z
2017-11-20T10:49:38.226Z

_About 5 minutes for composer install_

To be able to use shared volumes in lando I had to include my own compose.yml to create some extra volumes.

``` yml
volumes:
  d8_core: {}
  d8_modules_contrib: {}
  d8_modules_synetic: {}
  d8_profiles: {}
  d8_libraries: {}
  d8_themes_contrib: {}
  public_files: {}
  private_files: {}

```
