### ISSUE TITLE
nginx with deep project root does not work

### ISSUE THREAD

**Issue by yobottehg** [lando/lando#521]
Please complete the following steps.

Bug Report
==========

**Tell us about your setup**

3.0.0-Beta25 on Mac 10.13.1

**Tell us about your `.lando.yml`**

```yml
name: decoupled
proxy:
  php:
    - cms.decoupled.lndo.site
  mariadb:
    - db.decoupled.lndo.site
  nodejs:
    - www.decoupled.lndo.site
  mailhog:
    - mail.decoupled.lndo.site
services:
  php:
    type: php:7.1
    via: nginx
    ssl: true
    webroot: backend/web
    xdebug: true
  mariadb:
    type: mariadb:10.3
    portforward: 3308
    creds:
      user: drupal
      password: drupal
      database: drupal
  redis:
    type: redis:3.2
  mailhog:
    type: mailhog
    hogfrom:
      - php
  nodejs:
    type: node:8
    ssl: true
    command: "cd frontend && npm start"
tooling:
  composer:
    service: php
    cmd:
      - "composer"
      - "--ansi"
  drush:
    service: php
    cmd:
      - "cd backend/web"
      - "../bin/drush"
    needs:
      - mariadb
  npm:
    service: nodejs
  node:
    service: nodejs
```

**Tell us about the command you were running**

Accessing the backend url after running `lando start` returns bad gateway. Using apache works.

**Comment by yobottehg** [comment]
I thought i fixed the problem but it still occurs.
Updated the Summary with a more recent version of the .lando.yml

**Comment by yobottehg** [comment]
If i switch `via: nginx` to `via: apache` everything works as expected.

**Comment by pirog** [comment]
@yobottehg im *guessing* your issue might be something else considering this "deep" example works https://github.com/lando/lando/tree/master/examples/deepweb

**Comment by yobottehg** [comment]
Thanks for the example and the investigation.
I found the problem and perhaps its of interest for someone.

If you provide proxy for the php container by yourself it does work with apache because for apache the php with bundled apache is used. For nginx the php-fpm image is used.

So the proxy generates urls for the php-fpm image and not for nginx.

So instead of
```yml
proxy:
  php:
    - cms.decoupled.lndo.site
```

you have to use:
```yml
proxy:
  nginx:
    - cms.decoupled.lndo.site
```

And everything works.

**Comment by Jokerwin** [comment]
In my case I have two services with `php 7.3` via `nginx` and I wanted access both through the proxy:
`.lando.yml`
```
proxy:
  api:
    - api.lndo.site
  qe_nginx:
    - qe.lndo.site
  core_nginx:
    - core.lndo.site
services:
  console:
    type: node
    run:
      - cd /app/core/src && npm install
      - cd /app/core/src && npm rebuild node-sass
      - cd /app/core/src && npm run dev
  core:
    type: php:7.3
    via: nginx
    webroot: core/src/public
    xdebug: true
    run:
      - cd /app/core/src && cp .env.local .env
      - cd /app/core/src && composer install
      - cd /app/core/src && php artisan migrate
  qe:
    type: php:7.3
    via: nginx
    webroot: query-executor/src/public
    xdebug: true
    run:
      - cd /app/query-executor/src && cp .env.local .env
      - cd /app/query-executor/src && composer install
  api:
    type: nginx
```
