### ISSUE TITLE
Mariadb:10.0 container image not starting up

### ISSUE THREAD

**Issue by hanoii** [lando/lando#525]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?

 v3.0.0-beta.25 OSX high sierra - Git cloned, up to date for today.

**Tell us about your `.lando.yml`**

```yml
name: sime
recipe: drupal8

# The following additional build step will install the Platform CLI
# in the application container.
services:
  appserver:
    build:
      - "curl -sS https://platform.sh/cli/installer | php"

# The following entry creates a `lando platform` command that will run
# any Platform CLI command from inside the container if desired.
tooling:
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd:
      - /var/www/.platformsh/bin/platform
    options:
      passthrough: true


config:
  # Lando defaults to Apache. Switch to nginx to match Platform.sh.
  via: nginx

  # Set the webroot to match your .platform.app.yaml.
  webroot: web

  # Lando defaults to the latest MySQL release, but Platform.sh uses MariaDB.
  # Specify the version to match what's in services.yaml.
  database: mariadb:10.0
```

**Tell us about the command you were running**

Mariadb docker container won't start, see `lando logs -s database`

```bash
database_1   | Making sure correct user exists...
database_1   | 33
database_1   | Scanning /user/.ssh for keys...
database_1   | Scanning /user/.lando/keys for keys...
database_1   | Checking whether /user/.ssh/config is a private key...
database_1   | Checking whether /user/.ssh/id_rsa is a private key...
database_1   | Checking whether /user/.ssh/id_rsa_4096 is a private key...
database_1   | Checking whether /user/.ssh/id_dsa is a private key...
database_1   | Ensuring permissions for /user/.ssh/id_rsa...
database_1   | Ensuring permissions for /user/.ssh/id_rsa_4096...
database_1   | Ensuring permissions for /user/.ssh/id_dsa...
database_1   | Using the following keys: /user/.ssh/id_rsa /user/.ssh/id_rsa_4096 /user/.ssh/id_dsa
database_1   | Running command docker-entrypoint.sh mysqld
database_1   | 171120 22:11:36 [Note] mysqld (mysqld 10.0.33-MariaDB-1~jessie) starting as process 72 ...
database_1   | 171120 22:11:36 [Note] InnoDB: Using mutexes to ref count buffer pool pages
database_1   | 171120 22:11:36 [Note] InnoDB: The InnoDB memory heap is disabled
database_1   | 171120 22:11:36 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
database_1   | 171120 22:11:36 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
database_1   | 171120 22:11:36 [Note] InnoDB: Compressed tables use zlib 1.2.8
database_1   | 171120 22:11:36 [Note] InnoDB: Using Linux native AIO
database_1   | 171120 22:11:36 [Note] InnoDB: Using CPU crc32 instructions
database_1   | 171120 22:11:36 [Note] InnoDB: Initializing buffer pool, size = 384.0M
database_1   | 171120 22:11:36 [Note] InnoDB: Completed initialization of buffer pool
database_1   | 171120 22:11:36 [Note] InnoDB: Highest supported file format is Barracuda.
database_1   | InnoDB: No valid checkpoint found.
database_1   | InnoDB: A downgrade from MariaDB 10.2.2 or later is not supported.
database_1   | InnoDB: If this error appears when you are creating an InnoDB database,
database_1   | InnoDB: the problem may be that during an earlier attempt you managed
database_1   | InnoDB: to create the InnoDB data files, but log file creation failed.
database_1   | InnoDB: If that is the case, please refer to
database_1   | InnoDB: http://dev.mysql.com/doc/refman/5.6/en/error-creating-innodb.html
database_1   | 171120 22:11:36 [ERROR] Plugin 'InnoDB' init function returned error.
database_1   | 171120 22:11:36 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
database_1   | 171120 22:11:36 [Note] Plugin 'FEEDBACK' is disabled.
database_1   | 171120 22:11:36 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
database_1   | 171120 22:11:36 [ERROR] Unknown/unsupported storage engine: innodb
database_1   | 171120 22:11:36 [ERROR] Aborting
database_1   |
database_1   | 171120 22:11:36 [Note] mysqld: Shutdown complete
database_1   |
```

**Tell us generally about your bug**

I am trying lando for a platform.sh project. It's using mariadb:10.0 so I wanted to use the same version.
