### ISSUE TITLE
How to use a site-local drush?

### ISSUE THREAD

**Issue by hanoii** [lando/lando#526]
Feature/Enhancement Request
===========================

Explain/allow for site-local drush, 

On your docs, you mention:

```php
  # Optionally specify the version of global drush on your site
  #
  # If omitted this will install the latest stable version
  #
  # You should also highly consider a site-local install of drush.
```

I guess that for having a site-local drush, you would have to install the tooling yourself.

Would a simple override of the tooling work? Do you think we should be also installing the shim?

Is this outside of lando or something that could be include on the recipe?

**Comment by pirog** [comment]
yup, this is up to the user to do. that said and AFAIK site local drush is not a requirement at this point but is highly recommended. there is various pre-existing documentation on how to do this. this one from greg anderson is pretty good.
https://pantheon.io/blog/avoiding-dependency-hell-site-local-drush

**Comment by hanoii** [comment]
@pirog The question on how to avoid the default drush tooling is still valid.

If I am using the drupal8 recipe and I want to try avoid installing drush and use the binary that comes from composer. How can I void changing the drush tooling config, or even maybe disable altogether.

Adding 
```yaml
# The following entry creates a `lando platform` command that will run
# any Platform CLI command from inside the container if desired.
tooling:
  drush: false
```

or the like didn't work.
