### ISSUE TITLE
Does the "config:" parameter for a recipe accept all of the same values as a service?

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#530]
I'm setting up a Lando config using a Laravel recipe. Until now I have used custom recipes to set up my dev environments.

Normally, I'd have something like:

```
services:
  appserver:
    ssl: true
    xdebug: true
    php: '7.1'
    ...
```

I see that, for the Laravel recipe, many of the service parameters are the same for the `conf:` parameter. Is that because the recipe was designed to accept some of these params or can I treat the `conf:` param the same as I would the `appserver` param?
