### ISSUE TITLE
how to use a custom php.ini with the Pantheon recipe

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#544]
Windows 10 Pro
lando beta 29

I tried to set up a custom php.ini for xdebug [as described in the documentation ](https://docs.devwithlando.io/services/php.html) but the file isn't being picked up.

relevant part of .lando.yml
```
name: MYSITE
recipe: pantheon
config:
  framework: drupal8
  # xdebug: true
  webroot: web/

services:
  appserver:
    # xdebug config
    php: lando/php.ini
    build:
      # Add terminus plugins.
      - mkdir -p ~/.terminus/plugins
      - composer create-project -d ~/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:~1
      - composer create-project --no-dev -d ~/.terminus/plugins pantheon-systems/terminus-drupal-console-plugin:~1
```

The `php.ini` at `lando/php.ini` is the dev `php.ini` that comes with the Windows version of PHP 7.1, to which I added:

```
xdebug.remote_enable=1
; xdebug.remote_port=9000
; Normally you need to use a specific HTTP GET/POST variable to start remote debugging (see Remote Debugging). When this setting is set to 1, Xdebug will always attempt to start a remote debugging session and try to connect to a client, even if the GET/POST/COOKIE variable was not present.
xdebug.remote_autostart=1
xdebug.remote_host=192.168.0.177
; https://docs.devwithlando.io/services/php.html
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
xdebug.idekey = PHPSTORM
```

However, this file isn't being picked up, because when I access a `phpinfo()` file from a browser, xdebug.remote_host is set to `localhost` and the `xdebug.idekey` is not set.

**Comment by amklose** [comment]
I would also like to know this. I have a pantheon wordpress site. To the root (next to the .lando.yml file), I've aded a php.ini file with some xdebug settings. My .lando.yml file looks like the following:

`name: [site name]
recipe: pantheon
config:
  framework: wordpress
  site: [site name]
  id: [site id]
  conf: php.ini`

After running `lando restart`, I check with phpinfo() and the php.ini file isn't being used. I've also tried with the effective structure `config.conf.php: php.ini` and got the same results.

**Comment by jhume** [comment]
Subscribed, really need to get XDebug setup within Lando on a pantheon site.

**Comment by labboy0276** [comment]
@jhume xdebug is already setup in a pantheon recipe.  Per the docs: https://docs.devwithlando.io/recipes/pantheon.html

All you need to do is add a xdebug: true in your .lando.yml and do a lando restart

**Comment by serundeputy** [comment]
You should be able to turn on xdebug as @labboy0276 pointed out above (https://github.com/lando/lando/issues/544#issuecomment-353598202).

If you want to or need to load a custom `*.ini` you can per https://docs.devwithlando.io/tutorials/setup-additional-services.html#overriding-recipe-services

here is an example that I've confirmed working:

`.lando.yml`

```yml
  1 name: 544-custom-ini
  2 recipe: pantheon
  3 config:
  4   framework: drupal8
  5   site: 544-custom-ini
  6   id: bdd07eb8-c917-43f0-9f56-c4b26b080c8e
  7
  8 services:
  9   appserver:
 10     config:
 11       conf: config/xdebug.ini
```

* The `ini` file must exist in your app repo, in this case I have it in `config/xdebug.ini`

* Then `lando restart` and the app will pick up the specified config file.

@ptmkenny @jhume try updating your `.lando.yml` files accordingly.
I'm going to close this issue as it works as expected.

**Comment by mckinzie25** [comment]
If you are trying to use a custom php.ini file with Lando, this is the syntax that worked for me:

```
config:
  webroot: docroot
  php: '7.1'
  database: 'mysql:5.6'
  conf:
    php: php.ini
```

Then just run lando rebuild, and that should do it.

**Comment by kirantejp** [comment]
> If you are trying to use a custom php.ini file with Lando, this is the syntax that worked for me:
> 
> ```
> config:
>   webroot: docroot
>   php: '7.1'
>   database: 'mysql:5.6'
>   conf:
>     php: php.ini
> ```
> 
> Then just run lando rebuild, and that should do it.

Where should we write this? Also, is this the same case with mysql also?
In .lando.yml or pantheon.yml (recipe)

**Comment by mckinzie25** [comment]
Not sure about adding a mysql.conf file.  This is what my full .lando.yml file looks like:

```
name: xxxxx
recipe: drupal8
config:
  webroot: docroot
  php: '7.1'
  database: 'mysql:5.6'
  conf:
    php: php.ini
    
services:
  appserver:
    build:
      - if [ ! -L /usr/local/bin/blt ]; then ln -s /app/vendor/bin/blt /usr/local/bin/blt; fi;
    extras:
      - if ! command -v node > /dev/null; then curl -sL https://deb.nodesource.com/setup_8.x | bash && apt-get install -y nodejs; fi;
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

tooling:
  node:
    service: appserver
  npm:
    service: appserver
  blt:
    service: appserver
    cmd: /usr/local/bin/blt

proxy:
  mailhog:
    - mailhog.lndo.site
```

**Comment by vasikgreif** [comment]
I'm also trying to load the custom .ini file, for some reason it's not loaded. My config is a simple one:

```
name: masl
recipe: wordpress
config:
  php: 7.2
  via: nginx
  database: mariadb
  conf:
    php: php.ini
  webroot: web
  xdebug: true
```

Anything wrong with my config file?

**Comment by uberhacker** [comment]
@vasikgreif: It's easy to miss but you need to change `conf` to `config`.  See https://docs.devwithlando.io/tutorials/php.html#configuration.

**Comment by vasikgreif** [comment]
@uberhacker Thanks, it looked to me the config is correct as per the discussion above. Can you please give me an exact example of my config with the custom php.ini? I don't seem to get it right..

**Comment by uberhacker** [comment]
@vasikgreif:  This is an old thread and the newer versions of Lando use `config` instead of `conf`.  What is your version?  You might be able to get away with removing the entire `conf:` section including the `php: php.ini` line.  I recently used a Drupal 7 recipe and the custom php.ini from webroot was automagically picked up and overrode the master config.

**Comment by labboy0276** [comment]
Just providing an example on this older thread as it is one of the first ones to come up in search:

```
name: landobot-drupal9
recipe: pantheon
config:
  framework: drupal8
  site: landobot-drupal9
  id: #####
  xdebug: true

services:
  appserver:
    config:
      php: ./php.ini
```

This is how you add a custom php.ini to a pantheon recipe.
