### ISSUE TITLE
Does it support multi-project?

### ISSUE THREAD

**Issue by hanoii** [lando/lando#549]
I am not sure this will work or didn't find a specific reference on the docs, but say that you have an angular frontend and a drupal backend. Would that means to completely different .lando.yml files or can this be configured on a single file?

Thanks!

**Comment by ccharlton** [comment]
Are you asking about multiple projects (Lando "Apps"), or Drupal's multi-site feature?

**Comment by hanoii** [comment]
Multiple lando apps

**Comment by jbertoen** [comment]
Depends on how you set it up I guess. You could add more services. 
But the easiest way might be to setup 2 projects. Each having their own .lando.yml. 
This would allow you to create multiple angular/react frontend apps that communicate with drupal in the future.
But you could also add a node and an extra nginx service to a drupal recipe. And that would also be accessible within a single yml file.
```
name: PROJECT_NAME
recipe: drupal8
proxy:
  node:
    - node.PROJECT_NAME.localhost:3000
  angular:
    - angular.PROJECT_NAME.localhost
services:
  node:
    type: node:8.4
  angular:
    type: nginx:1.12
```
