### ISSUE TITLE
Solr core not automatically created

### ISSUE THREAD

**Issue by hanoii** [lando/lando#551]
I wanted to have, for now, just a solr service on a drupal project, not going full lando yet.

I have the following .yml file:

```yml
name: moog-drupal

proxy:
  # Lets get a nice lndo url for the solr web interface
  solrsearch2:
    - moog-solr.lndo.site:8983

# Spin up services to run a basic LAMP stack
services:
  solrsearch2:
    type: solr:6.6
    portforward: true
    core: drupal
    config:
      conf: .platform/solr-conf
```

For some reason the core is not created or found automatically.

Solr is there without core. I can see the configs on /opt/solr/server/solr/mycores/drupal, but the core is not there.

When I went to try to add the core manually, providing mycores/drupal as the instanceDir, it complained that it didn't have access to /opt/solr/server/solr/mycores/drupal/core.properties.

I ssh to the service and saw that /opt/solr/server/solr/mycores/drupal was owned by root:root. I then chowned it to solr:solr and added the core and that worked, but this surely have been automatically.

Using lando master.

**Comment by heshanlk** [comment]
I have the same issue, the Solr core would not create automatically.

**Comment by heshanlk** [comment]
After couple of different config attempts following configs appeared to be working fine for me for search api solr with Solr 5.5

```
  solr:
    type: solr:5.5
    portforward: true
    config:
      conf: docroot/modules/contrib/search_api_solr/solr-conf/5.x
```
