### ISSUE TITLE
WordPress Recipe + Node Service = Errors Galore

### ISSUE THREAD

**Issue by labboy0276** [lando/lando#554]
Bug Report
==========

**Tell us about your setup**

beta-29 + Ubuntu 16.04

**Tell us about your `.lando.yml`**

_Version that works:_

```yml
name: yourmom
recipe: wordpress
config:
  webroot: web
  xdebug: true
```
_Version that breaks lando_

```yml
name: yourmom
recipe: wordpress
config:
  webroot: web
  xdebug: true
services:
  appserver:
    type: node:8
tooling:
  npm:
    service: appserver
  node:
    service: appserver
```

**Tell us about the command you were running**

lando rebuild

**This is the failed output**

```bash
john@tandem:~/lando/yourmom$ lando rebuild
? Are you sure you want to rebuild? Yes
Stopping yourmom_database_1 ... done
Stopping yourmom_appserver_1 ... done
Removing yourmom_database_1 ... done
Removing yourmom_appserver_1 ... done
Pulling appserver (node:8)...
Pulling database (mysql:latest)...
appserver uses an image, skipping
database uses an image, skipping
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating yourmom_appserver_1 ... 
Creating yourmom_database_1 ... 
Creating yourmom_database_1
Creating yourmom_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4306k  100 4306k    0     0  10.4M      0 --:--:-- --:--:-- --:--:-- 10.4M
/bin/sh: 1: php: not found
error:  message=  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4306k  100 4306k    0     0  10.4M      0 --:--:-- --:--:-- --:--:-- 10.4M
/bin/sh: 1: php: not found
, code=127
```

**Tell us about the error you got**

See above

```bash
/bin/sh: 1: php: not found
```

**Tell us generally about your bug**

@pirog witnessed this bug with me, he is in the know.

Does this bug prevent you from using lando?

Kinda but not totally
