### ISSUE TITLE
Lando v3.0.0-beta.29 not working on certain cases on Ubuntu 17.10

### ISSUE THREAD

**Issue by cjgratacos** [lando/lando#557]
Lando not working for the config pasted bellow. it triggers an error. had to revert back to previous version.

Bug Report
==========

**Tell us about your setup**

*lando: v3.0.0-beta.29*
*OS: Ubuntu 17.10*
*Node: 8.7.0*

**Tell us about your `.lando.yml`**
```yml
name: d6
recipe: drupal6
config:
  php: '5.5'
  via: apache
  webroot: site
  drush: 6
  database: mysql:5.5
  xdebug: true
```
