### ISSUE TITLE
Failed to import into PhpMyAdmin from a large script file: 504 gateway time-out nginx

### ISSUE THREAD

**Issue by joel7** [lando/lando#567]
Buenas noches, deseo importar una base de datos en **phpmyadmin** desde un archivo script grande, y da error:
(Good evening, I want to import a database in **phpmyadmin** from a large script file, and it gives error:)
# 504 gateway time-out nginx

Estoy usando (I am using) **lando-v3.0.0-beta.29.exe** in Windows 10 Professional
¿Cómo hacer para que **php.ini** o **config.user.inc.php** funcione en **phpmyadmin**?
(How to make **php.ini** or **config.user.inc.php** work in **phpmyadmin**?)

**My .lando.yml:**
```
name: cole
recipe: drupal8
proxy:
  appserver:
    - drupal8421.dev
services:
  appserver:
    config:
      conf: php.ini
  pma:
    type: phpmyadmin
    hosts:
      - database
    config: config.user.inc.php
  node:
    type: node:6.10
  cache:
    type: redis
    persist: true
tooling:
  redis-cli:
    service: cache
  node:
    service: node
  npm:
    service: node
config:
  php: '7.1'
  database: mysql
  via: apache
  webroot: .
  drush: stable
  drupal: true
  xdebug: true
```

**My php.ini**
```
max_execution_time = 36000
max_input_time = 3600
max_input_vars = 10000
memory_limit = 1024M
upload_max_filesize = 1024M
post_max_size = 1024M
```

**My config.user.inc.php**
`$cfg['ExecTimeLimit'] =36000;`
