### ISSUE TITLE
Add wkhtmltopdf to the install of tooling on the PHP images.

### ISSUE THREAD

**Issue by jbertoen** [lando/lando#572]
Feature Request
===============

We often use WKHTMLTOPDF to generate our pdf files. Like imagemagick this works pretty good. Only the installation takes a lot of time because we have to do the following on every rebuild:
```
services:
  appserver:
    extras:
      - "apt-get update -y"
      - "apt-get install wkhtmltopdf -y"
      - "apt-get install xvfb -y"
```
The current docker file for php already implement similar logic for imagemagick and others. So why not add this as well.

**Comment by pirog** [comment]
closing this with rationale in #573 
@jbertoen def feel free to open up a doc pr!

**Comment by tanc** [comment]
I realise this is old but here is my successful install of `wkhtmltopdf` using the `drupal9` recipe with PHP 8.0:

```
services:
  appserver:
    build_as_root:
      - "[ -f /usr/bin/wkhtmltopdf ] || ( apt-get update -y && apt-get install zlib1g fontconfig libxrender1 libfreetype6 libxext6 libx11-6 -y)"
      - "[ -f /usr/bin/wkhtmltopdf ] || ( wget -nc https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_amd64.deb -P /tmp )"
      - "[ -e /usr/bin/wkhtmltopdf ] || ( dpkg -i /tmp/wkhtmltox_0.12.6-1.buster_amd64.deb )"
      - "[ -f /usr/bin/wkhtmltopdf ] || ( ln -s /usr/local/bin/wkhtmltopdf /usr/bin/wkhtmltopdf )"
```

**Comment by cbiggins** [comment]
@tanc this worked perfectly. Thanks.

**Comment by yuseferi** [comment]
Nice!

**Comment by melvix** [comment]
The solution posted by @tanc worked well for me until this week when I updated lando and changed my lando recipe to drupal10. The installation of wkhtmltox would fail because of a requirement of `libssl1.1`, which is apparently no longer supported.

Here is my workaround:

```
services:
  appserver:
    build_as_root:
      - "[ -f /usr/bin/wkhtmltopdf ] || ( wget -nc http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.1_1.1.1w-0+deb11u2_amd64.deb -P /tmp )"
      - "[ -f /usr/bin/wkhtmltopdf ] || ( dpkg -i /tmp/libssl1.1_1.1.1w-0+deb11u2_amd64.deb )"
      - "[ -f /usr/bin/wkhtmltopdf ] || ( apt-get update -y && apt-get install libjpeg62-turbo-dev xfonts-75dpi xfonts-base -y )"
      - "[ -f /usr/bin/wkhtmltopdf ] || ( wget -nc https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.bullseye_amd64.deb -P /tmp )"
      - "[ -e /usr/bin/wkhtmltopdf ] || ( dpkg -i /tmp/wkhtmltox_0.12.6.1-2.bullseye_amd64.deb )"
      - "[ -f /usr/bin/wkhtmltopdf ] || ( ln -s /usr/local/bin/wkhtmltopdf /usr/bin/wkhtmltopdf )"

```

I suppose this also suggests that an alternative to wkhtmltox should be used.
