### ISSUE TITLE
Setting up CircleCI for testing Lando app: docker-ce requirement?

### ISSUE THREAD

**Issue by davisshaver** [lando/lando#575]
Bug Report
==========

**Tell us about your setup**
Most everything working great with Lando!

Setting up CircleCI, here's the `circle.yml` I've got currently ([based on Lando docs](https://docs.devwithlando.io/tutorials/lando-and-ci.html)):

```
machine:
  php:
    version: 7.1.9
  services:
    - docker
dependencies:
  pre:
    - sudo apt-get -y update
    - sudo apt-get -y install cgroup-bin curl
    - curl -fsSL -o /tmp/lando-latest.deb http://installer.kalabox.io/lando-latest-dev.deb
    - sudo dpkg -i /tmp/lando-latest.deb
    - lando version
  override:
    - echo "This section is intentionally skipped."
test:
  override:
    - echo "Ignore CircleCI default test"
    - lando start -- -v
    - lando test -- -v
```

However the `sudo dpkg -i /tmp/lando-latest.deb` fails due to Docker CE missing.

<img width="608" alt="screen shot 2017-12-09 at 3 11 09 pm" src="https://user-images.githubusercontent.com/1636964/33799122-35dd9e94-dcf3-11e7-98fb-7f80778e1bd2.png">

Any pointers would be helpful. I can add to docs for CircleCI so we have more than travis documented.
