### ISSUE TITLE
Lando version beta.29 and above does not find drush when running lando drush status

### ISSUE THREAD

**Issue by dandinu** [lando/lando#580]
Hi,

There is a problem with the latest versions of Lando (beta.29 through beta.31). When I run `lando drush status` I get:
```
The Drush launcher could not find a local Drush in your Drupal site.
Please add Drush with Composer to your project.
Run 'cd "/app" && composer require drush/drush'
```
![image](https://user-images.githubusercontent.com/939182/33894569-fadffb04-df66-11e7-9fcb-a833340b61fa.png)

The issue does not replicate on beta.28. It works without any issues there and I have no idea why.

Steps to replicate:

1. Run `lando start`
2. Run `lando drush status`
3. Get error

This is what `lando rebuild` says:
![image](https://user-images.githubusercontent.com/939182/33894793-8668bb7a-df67-11e7-8958-ffa728195ded.png)
I can clearly see `drush launcher` installing.

This is what the `.lando.yml` file looks like:
```
# Name the application the same as in your .platform.app.yaml.
name: app
# Use the recipe appropriate for your application.
recipe: drupal8

# The following additional build step will install the Platform CLI
# in the application container.
services:
  appserver:
    build:
      - "curl -sS https://platform.sh/cli/installer | php"

# The following entry creates a `lando platform` command that will run
# any Platform CLI command from inside the container if desired. 
tooling:
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd:
      - /var/www/.platformsh/bin/platform
    options:
      passthrough: true
  sync:
    description: Execute script to sync files to the local machine.
    service: appserver
    cmd: /app/scripts/lando-scripts/sync.sh

config:
  # Lando defaults to Apache. Switch to nginx to match Platform.sh.
  via: nginx

  # Set the webroot to match your .platform.app.yaml.
  webroot: web

  # Lando defaults to the latest MySQL release, but Platform.sh uses MariaDB.
  # Specify the version to match what's in services.yaml.
  database: mariadb:10.1
```

Do you have any ideas?

**Comment by aisforaaron** [comment]
To solve this manually until Lando works try these steps.

1. From your project root (where .lando.yml file is located) run
  $ lando ssh
1. You should now be in the "app" dir, run
  $ composer require drush/drush
1. Logout of ssh session
  $ exit
1. Try drush
  $ lando drush status

**Comment by dandinu** [comment]
Thanks @aisforaaron ,

I am now able to solve this issue through a `lando rebuild`. It appears to be working after a couple of rebuilds. Seems random at this point, but I will try to debug a bit more.

**Comment by honzapara** [comment]
This is not working for me. Once I run `composer require drush/drush` then it ends up with an error: 

```
[RuntimeException]
/vendor does not exist and could not be created.
```

**Comment by dandinu** [comment]
hi @honzapara,

As an alternative try adding `drush` globally by putting this in you `.lando.yml`:
```
config:
  drush: global:8.1.15
```

**Comment by honzapara** [comment]
This helped! Thanks a lot @dandinu.

**Comment by dandinu** [comment]
@jasonbell the Drupal 8 recipe is specifically configured to not install drush. This is not the case for the Drupal 7 recipe, since that installs drush globally by default. I believe the logic behind it is that in D8 you would install it yourself using composer.

**Comment by jasonbell** [comment]
@dandinu Ok, thanks. That seems to make sense, however the documentation isn’t very clear on that inferred logic. The [Tooling section of docs](https://docs.devwithlando.io/tutorials/pantheon.html#tooling) about Pantheon seems to indicate that these tools are installed by default, “ Each Lando Pantheon recipe will also ship with the Pantheon toolchain”. Maybe this is an issue of documentation?

**Comment by spencerbrooks** [comment]
Running `composer require drush/drush` and committing the vendor changes causes issues on Pantheon sites because it installs Drush 9 by default, which is [not supported on Pantheon](https://pantheon.io/docs/drush-versions/). Pantheon runs on Drush 8 by default, but if your repository contains a copy of Drush in the `/vendor` directory, it redispatches Pantheon's Drush to use that version. In my case, this broke Drush on all our Pantheon environments, including the launch check/status report.

The global approach to using Drush outlined by @dandinu is the cleanest way I've found to handle this without interfering with Drush on Pantheon. Another alternative is to commit Drush 8 to your repo, but in my opinion it's preferable to let Pantheon use whatever version of Drush they want instead of locking them to whatever's committed to your repository.

**Comment by pirog** [comment]
@spencerbrooks (and others), after talking to @dustinleblanc *i think* we are going to change lando's default behavior for Drupal 8 Pantheon sites to just globally installing Drush 8.

**Comment by pirog** [comment]
@nerdstein can you provide more detail here? i'm not exactly sure what you are trying to say. 

AFAIK you don't have to run `lando drush` exclusively from the docroot directory. That said you DO need to run it within the context of some Lando app since drush is provided and configured on an app-to-app basis.

Re: drush not working, i think the bigger concern here is just keeping lando up to date with the myriad of ways one can install drush, how the recommended installation can be different depending on things like Pantheon, and how all of this is still very much fluid right now. We try to set a good sane default and then provide a good deal of configurability that the user can do on their end if that default doesnt match what you need.

**Comment by dandinu** [comment]
@nerdstein I had the same issue. The way I solved it was by setting the root of the `drush` command to point to the folder I want (in my case `/app/web`). Add this into your `.lando.yml`:

```
tooling:
  drush:
    service: appserver
    cmd:
      - "drush"
      - "--root=/app/web"
```
