### ISSUE TITLE
mysql slow start ... quite confussing

### ISSUE THREAD

**Issue by anibalsanchez** [lando/lando#583]
Bug Report
==========

- Ubuntu 17.10
- lando-v3.0.0-beta.31.deb

```yml
##
# Based on LAMP stack example - https://docs.devwithlando.io/services/php.html
##
name: lampboilerplate

proxy:
  appserver:
    - lampboilerplate.lndo.site

services:
  appserver:
    type: php:7.1
    via: apache
    ssl: false
    webroot: www
    config:
      conf: config/php/php.ini
    xdebug: true

  database:
    type: mysql
    portforward: 3308
    creds:
      user: lampboilerplatedb
      password: lampboilerplatedb
      database: lampboilerplatedb

  pma:
    type: phpmyadmin

tooling:
  composer:
    service: appserver
    description: Run composer commands
    cmd:
      - composer
      - --ansi
  php:
    service: appserver

  mysql:
    user: root
    service: database
    description: Drop into a MySQL shell
```
**Commands**

```bash
lando destroy
lando start
lando mysql
lando mysql
lando mysql
lando mysql
```

**Tell us generally about your bug**

After several hours of testing, I've finally found the issue. To be brief, mysql starts and initializes slower than the rest of the services. Additionally, there is no indication that the service is not fully available.

Could better documentation have prevented this issue? if so what should we change?

Yes, for sure. There should be some warning that the services are not ready yet. Now, after executing "lando start"... I'm manually checking with "lando mysql" and visiting phpmyadmin to confirm when the services are fully available.

This is the error that you get while mysql is still being initialized:

```bash
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```
So, the solution should be to show "BOOMSHAKALAKA!!!" only when mysql is completely initialized.
