### ISSUE TITLE
[nodejs] CLI container doesn't respect service overrides

### ISSUE THREAD

**Issue by vincenzo** [lando/lando#586]
# Bug Report

- **Lando**: `v3.0.0-beta.31`
- **OS**: macOS High Sierra 10.13.1 (`Darwin iDumbo 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64`)

My `.lando.yml`:

```yml
name: panda

proxy:
  panda:
    - panda.lndo.site

services:
  panda:
    type: node
    build:
      - "cd /app/ && npm install"
    command: cd /app/ && npm run dev
    overrides:
      services:
        image: node:8.9.3
        environment:
          PORT: 80
          
tooling:
  npm:
    service: panda_cli
```

When provisioning this, you get: 

```
Pulling panda_cli (node:latest)...
Pulling panda (node:8.9.3)...
```

The expected behaviour would be to have both on node:8.9.3. I have double checked that they are actually different by ssh-ing into the individual containers. 

Also, please note that, [according to the docs](https://docs.devwithlando.io/config/advanced.html), the following section: 

```yml
services:
  panda:
    type: node
```

should actually be

```yml
services:
  panda:
    type: node:custom
```

but when specifying `:custom` I get the following error (repeatedly, I guess at each 'pull' attempt): 

```
ERROR: manifest for node:custom not found
```

This bug doesn't strictly prevent me from using Lando, but it is an impediment as it doesn't allow me to have the same `nodejs` version on Lando as the one I currently have on Platform.sh, where I deploy the apps for production.
