### ISSUE TITLE
Extra Config File Not Loaded On Rebuild

### ISSUE THREAD

**Issue by alexfinnarn** [lando/lando#589]
Bug Report
==========

**Tell us about your setup**

OS: Mac OS 10.13.2
Lando: v3.0.0-beta.31

**Tell us about your `.lando.yml`**

```yml
name: express
recipe: drupal7
config:
  webroot: web
  xdebug: true
  php: "7.1"
  conf:
    php: config/php/zzzzzz-express-custom.ini
services:
  appserver:
    overrides:
      services:
        environment:
          BEHAT_PARAMS: '{"extensions":{"Drupal\\DrupalExtension":{"drupal":{"drupal_root":"/app/web/express"}},"Behat\\MinkExtension":{"base_url":"http://express.lndo.site:8000/express","files_path":"/app/web/express/profiles/express/tests/behat/assets/"}}}'
          DSLM_BASE: '/app/code/dslm_base'
          PACKAGES_BASE: '/app/code/packages_base'
tooling:
  create-site:
    service: appserver
    cmd:
      - "./scripts/create-site.sh"
  add-tools:
    service: appserver
    cmd:
      - "./scripts/add-tools.sh"
```
**PHP ini file**

Located at: /app/config/php/zzzzzz-express-custom.ini

```ini
[PHP]

;;;;;;;;;;;;;;;
; PHP Globals ;
;;;;;;;;;;;;;;;

short_open_tag = Off
output_buffering = 4096
allow_call_time_pass_reference = Off
variables_order = "GPCS"
request_order = "GP"
register_long_arrays = Off
register_argc_argv = Off
magic_quotes_gpc = Off
enable_dl = Off
allow_url_fopen = On
realpath_cache_size = "800K"
realpath_cache_ttl = "86400"
;include_path = ".:/usr/share/pear:/usr/share/php"

[Date]
date.timezone = "America/Denver"

;;;;;;;;;;;;;;;;;;;;;;
;; PACKAGE SETTINGS ;;
;;;;;;;;;;;;;;;;;;;;;;

; Xdebug
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
xdebug.remote_enable = 1

;;;;;;;;;;;;;;;;;;;;;;;
;; PANTHEON SETTINGS ;;
;;;;;;;;;;;;;;;;;;;;;;;

; Globals
expose_php = on
max_execution_time = 90
max_input_time = 900
max_input_vars = 10000
memory_limit = 512M
upload_max_filesize = 256M
post_max_size = 256M
error_reporting = E_ALL & ~E_DEPRECATED
ignore_repeated_errors = on
html_errors = on
display_errors = on
display_startup_errors = on
log_errors = on

; Using this to insert essential Pantheon functionality.
;auto_prepend_file = prepend.php

[Opcache]

opcache.revalidate_freq=0
opcache.validate_timestamps=0
opcache.max_accelerated_files=20000
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.fast_shutdown=1
```

**Tell us generally about your bug**

I tried to add a php.ini file like in https://github.com/lando/lando/blob/master/examples/drupal7/.lando.yml but it didn't seem to load.

```bash
lando rebuild
# Look at PHP ini settings which I did via "admin/reports/status/php" in a Drupal site.
# See that your ini settings aren't loaded.
```

**Tell us more**

For a work around. I just copied in my settings after the custom Lando ini file. 

```yaml
  appserver:
    extras:
      - cp /app/config/php/zzzzzz-express-custom.ini /usr/local/etc/php/conf.d
```

**Comment by ccharlton** [comment]
Ditto.

**Comment by pirog** [comment]
@alexfinnarn im confused. is the name of your custom php file `config/php/zzzzzz-express-custom.ini` or `config/php/php.ini`?

**Comment by alexfinnarn** [comment]
@pirog I changed the name of that file while debugging once I saw that that ini files were parsed alphabetically. I have updated my original posting to show they are supposed to be the same config file.

**Comment by pirog** [comment]
@alexfinnarn awesome thanks, that eliminates a potentially obvious reason at least

**Comment by alexfinnarn** [comment]
So...

```yaml
name: express
recipe: drupal7
config:
  webroot: web
  php: "7.1"
  conf:
    php: config/php/zzzzzz-express-custom.ini
```

works and...

```yaml
name: express
recipe: drupal7
config:
  webroot: web
  php: "7.1"
  conf:
    php: config/php/express-custom.ini
```

doesn't. I think the `ini` file is parsed but doesn't appear anywhere for the user to see that like on "admin/reports/status/php" for a Drupal 7 site. If I manually add the file by copying over as an extra step after build, I can see that it is loaded last and then move that step over to the `conf` config key.

I'm not sure if you just want to make a doc change or fix it to load the user's file last, but since I see the Lando `php.ini` file is prefixed with "zzzz" maybe it is easier to tell people to add some zzzz's for now.
