### ISSUE TITLE
Adding second database container in a recipe doesn't respect `creds` key.

### ISSUE THREAD

**Issue by serundeputy** [lando/lando#593]
Using the `backdrop` recipe with two mariadb databases I can not specify the `creds` for the second database.

```yml
name: civi
recipe: backdrop
config:
  webroot: web
  php: '7.0'

services:
  appserver:
    build:
      - "curl -sS https://platform.sh/cli/installer | php"
  database:
    type: mariadb
    portforward: 6618
  cividatabase:
    type: mariadb
    portforward: 6619
    creds:
      user: geoff
      password: candlabra
      database: cividatabase
```

The username is always `root` and blank `password` regardless of putting a `creds` key in your `.lando.yml` file

So you can still use the database you just have to know that the creds are `root` with an empty password.

I'm using the `backdrop` recipe here, but I suspect it is with any recipe and possibly `custom` as well (needs to be checked / tested).

**Comment by serundeputy** [comment]
I tested this morning on a d8 recipe:

```yml
name: 593-d-8
recipe: drupal8
config:
  webroot: .

services:
  database:
    creds:
      user: geoff
      password: elaphone
      database: geoffalot
  mybase:
    type: mysql
    portforward: true
    creds:
      user: px
      password: px
      database: memow
```

The `creds` key is respected for the primary `database` container and I can login with the creds provided by `lando info`.

```json
{
  "appserver": {
    "type": "php",
    "version": "7.1",
    "via": "apache",
    "webroot": ".",
    "config": {
      "conf": "/Users/geoff/.lando/services/config/drupal8/php.ini"
    },
    "urls": [
      "https://localhost:32860",
      "http://localhost:32861",
      "http://593-d-8.lndo.site",
      "https://593-d-8.lndo.site"
    ]
  },
  "database": {
    "type": "mysql",
    "version": "latest",
    "creds": {
      "user": "geoff",
      "password": "elaphone",
      "database": "geoffalot"
    },
    "internal_connection": {
      "host": "database",
      "port": 3306
    },
    "external_connection": {
      "host": "localhost",
      "port": "32858"
    },
    "config": {
      "confd": "/Users/geoff/.lando/services/config/drupal8/mysql"
    }
  },
  "mybase": {
    "type": "mysql",
    "version": "latest",
    "creds": {
      "user": "px",
      "password": "px",
      "database": "memow"
    },
    "internal_connection": {
      "host": "mybase",
      "port": 3306
    },
    "external_connection": {
      "host": "localhost",
      "port": "32859"
    }
  }
}
```

The second database container does not respect the `creds` key and regardless of the info from `lando info` you have to login with:
  * user: `root`
  * password: `ø` {empty password}

**Comment by serundeputy** [comment]
In a `custom` `.lando.yml` file the `creds` key was respected by both the primary `database` service and a secondary `dbtwo` service.

```yml
name: bee
recipe: custom
config:
  webroot: .

services:
  database:
    type: postgres
    portforward: true
    creds:
      user: geoff
      password: eons
  dbtwo:
    type: mariadb
    portforward: true
    creds:
      user: em
      password: em
      database: em
```

`lando info`

```json
{
  "database": {
    "type": "postgres",
    "version": "latest",
    "creds": {
      "user": "geoff",
      "password": "eons",
      "database": "database"
    },
    "internal_connection": {
      "host": "database",
      "port": 5432
    },
    "external_connection": {
      "host": "localhost",
      "port": "32865"
    }
  },
  "dbtwo": {
    "type": "mariadb",
    "version": "latest",
    "creds": {
      "user": "em",
      "password": "em",
      "database": "em"
    },
    "internal_connection": {
      "host": "dbtwo",
      "port": 3306
    },
    "external_connection": {
      "host": "localhost",
      "port": "32864"
    }
  }
}
```

So I'm guessing something in the inheritance chain for recipes that `backdrop` and `drupal` are inheriting from is clobbering the parsing of `creds` ... I'll check  `lamp` and `lemp` recipes.
