### ISSUE TITLE
Rebuild single service runs all build steps for the appserver

### ISSUE THREAD

**Issue by dmsmidt** [lando/lando#596]
Bug Report
==========

* Lando v3.0.0-beta.31 - Docker for Mac 17.12.0-ce-rc3-mac43 (21270) - macOS High Sierra*

When rebuilding a single service all build steps of the appserver are executed. This makes rebuilding a single service slow and sometimes problematic.

```yml
name: projectx

# https://docs.devwithlando.io/recipes/drupal7.html
recipe: drupal7

# These are the url's to use for your project. The key, such as nginx, solr, etc,
# are the services that are defined below.
# https://docs.devwithlando.io/config/proxy.html
proxy:
  solr:
    - solr.projectx.localhost:8983

# Add some default configuration for the recipe here. Which will be passed to all the services within the recipe.
# https://docs.devwithlando.io/recipes/drupal7.html
config:
  webroot: web

  # Choose whether to use apache or nginx.
  via: nginx

  php: '7.1'

  # Add custom php.ini for development configuration.
  conf:
    php: config/develop/php/php.ini

services:
  appserver:
    overrides:
       services:
         volumes:
           - /app/documentation/
              - public_files:/app/web/sites/default/files
           - private_files:/app/files/private
    build:
      - "mkdir -p ~/.drush/alias"
      - "ln -sf /app/drush/alias/projectx.aliases.drushrc.php ~/.drush/alias/projectx.aliases.drushrc.php"
      - "drush dl registry_rebuild-7.x drush_language-7.x"

  # https://docs.devwithlando.io/services/solr.html
  solr:
    type: solr:5.5
    portforward: true
    core: projectx
    config:
      conf: config/shared/solr

compose:
 - compose.yml

```

Example rebuild single service command:

```bash
lando rebuild -s solr
```
Example build output:

```
Pulling solr (solr:5.5)...
solr uses an image, skipping
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating volume "projectx_data_solr" with default driver
Creating projectx_solr_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599    0   599    0     0   1154      0 --:--:-- --:--:-- --:--:--  1156
100 5912k  100 5912k    0     0  1737k      0  0:00:03  0:00:03 --:--:-- 2675k
 PHP configuration      :                                                
 PHP OS                 :  Linux                                         
 Drush script           :  /tmp/drush.phar                               
 Drush version          :  8.1.15                                        
 Drush temp directory   :  /tmp                                          
 Drush configuration    :                                                

Install location /var/www/.drush/registry_rebuild already exists. Do you want to overwrite it? (y/n): n
Skip installation of registry_rebuild to /var/www/.drush/registry_rebuild.                                                                                                                                                                           [warning]
Install location /var/www/.drush/drush_language already exists. Do you want to overwrite it? (y/n): n
Skip installation of drush_language to /var/www/.drush/drush_language.                                                                                                                                                                               [warning]
```

As you can see Drush is installed every time (Drupal recipe) and my custom build steps are called.
