### ISSUE TITLE
Determine best practice for sharing `~/.ssh/known_hosts` with Lando

### ISSUE THREAD

**Issue by davisshaver** [lando/lando#601]
CircleCI can [inject SSH keys for Github](https://circleci.com/docs/2.0/configuration-reference/#add_ssh_keys). The key is placed into `known_hosts`, which gets excluded during the SSH key sync process: https://github.com/lando/lando/blob/48ed38df2f1868bbace676944da078565d63d1d8/plugins/lando-services/scripts/load-keys.sh#L25

Is this safe to copy into the Lando environment by default? Is there any additional risk that gets introduced by including this file?

As a workaround, a modification to `lando.yml` allows us to use docker volumes feature to pass the file:

```
services:
  appserver:
    overrides:
      services:
        volumes:
          - ~/.ssh/known_hosts:/etc/ssh/known_hosts
```
