### ISSUE TITLE
lando drush command requires --root option 

### ISSUE THREAD

**Issue by snize** [lando/lando#603]
Bug Report
==========

**Tell us about your setup**

3.0.0-beta.31 on macOS 10.12.6

**Tell us about your `.lando.yml`**

```yml
name: myproj
recipe: pantheon
config:
  framework: drupal8
  site: myproj
  id: XXXXXXXXX
```

```yml
api_version: 1
web_docroot: true
php_version: 7.0
workflows:
  deploy_product:
    after:
      -
        type: webphp
        description: 'Run composer prepare-for-pantheon'
        script: private/scripts/deploy_product/prepare-for-pantheon.php
      -
        type: webphp
        description: 'Run composer install & drupal-scaffold'
        script: private/scripts/deploy_product/composer-install.php
  sync_code:
    after:
      - type: webphp
        description: Push changes back to GitHub if needed
        script: private/scripts/quicksilver/quicksilver-pushback/push-back-to-github.php
```

**Tell us about the command you were running**

with `lando drush status`

```bash
$ lando drush status
 PHP executable         :  /usr/local/bin/php
 PHP configuration      :
 PHP OS                 :  Linux
 Drush script           :  /app/vendor/drush/drush/drush.php
 Drush version          :  8.1.15
 Drush temp directory   :  /tmp
 Drush configuration    :
 Drush alias files      :
```

```bash
$ lando drush status --root=/app/web
 Drupal version                  :  8.4.3
 Site URI                        :  http://myproj.lndo.site
 Database driver                 :  mysql
 Database hostname               :  database
 Database port                   :  3306
 Database username               :  pantheon
 Database name                   :  pantheon
 Database                        :  Connected
 Drupal bootstrap                :  Successful
 Drupal user                     :
 Default theme                   :  bartik
 Administration theme            :  seven
 PHP executable                  :  /usr/local/bin/php
 PHP configuration               :
 PHP OS                          :  Linux
 Drush script                    :  /app/vendor/drush/drush/drush.php
 Drush version                   :  8.1.15
 Drush temp directory            :  /tmp
 Drush configuration             :  /app/web/sites/default/drushrc.php
 Drush alias files               :
 Install profile                 :  standard
 Drupal root                     :  /app/web
 Drupal Settings File            :  sites/default/settings.php
 Site path                       :  sites/default
 File directory path             :  sites/default/files
 Private file directory path     :  sites/default/files/private
 Temporary file directory path   :  /var/www/tmp
 Sync config path                :  /app/config
```

With `lando drush uli`

```bash
lando drush uli
We could not find an applicable site for that command.
```

```bash
$ lando drush uli --root=/app/web
http://myproj.lndo.site/user/reset/1/1514424716/r_bgNRfzY_JIEeQW0aHc5juRWwD_o2-XAbcyq3T3IXw/login
```

**Tell us generally about your bug**

I confirmed that `drush` is running in `$LANDO_MOUNT`. It should be run in  `$LANDO_WEBROOT`.

`lando drush uli -- -vvvv`

```bash
verbose: Exec cd "$LANDO_MOUNT"&&drush uli on myproj_appserver_1 in mode attach
debug: With opts {"AttachStdin":true,"AttachStdout":true,"AttachStderr":true,"Cmd":["/bin/sh","-c","cd \"$LANDO_MOUNT\"&&drush uli"],"Env":[],"DetachKeys":"ctrl-p,ctrl-q","Tty":true,"User":"www-data"} {"hijack":false,"stdin":true,"Detach":false,"Tty":true}
We could not find an applicable site for that command.                                                                                                                                                                                               [error]
```
