### ISSUE TITLE
Can't start or stop, not even the `lando` command works

### ISSUE THREAD

**Issue by maaxxicarvalho** [lando/lando#608]
Bug Report
==========

## Environment

*Macos version:* 10.13.2
*Docker version:* 17.12.0-ce-rc4-mac44 (21438) - edge channel
*Lando Version:* v3.0.0-beta.31

## `.lando.yml`:*

```yml
name: magento

proxy:
  nginx:
    - local.magento.com

services:
  appserver:
    type: php:7.0
    via: nginx
    ssl: true
    webroot: .
    xdebug: true
    build:
      - "curl -s -O https://files.magerun.net/n98-magerun.phar && chmod +x ./n98-magerun.phar && mv ./n98-magerun.phar /usr/local/bin/magerun"

  database:
    type: mysql:5.7
    portforward: 3306
    creds:
      user: lamp
      password: lamp
      database: lamp

tooling:
  magerun:
    service: appserver
    user: www-data
    cmd: magerun

  composer:
    service: appserver
    description: Run composer commands
    cmd:
      - composer
      - --ansi

  php:
      service: appserver

  mysql:
    user: root
    service: database
    description: Drop into a MySQL shell
```

## Commands that caused the bug:

```bash
lando
```

## Error message:

```bash
warn:  {"message":"API rate limit exceeded for 213.94.140.222. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
    (No stack trace)
From previous event:
    at Object.__dirname.setupRoutes.Object.keys.forEach.self.(anonymous function).(anonymous function) [as getReleases] (/snapshot/cli/node_modules/github/lib/index.js:275:40)
    at /snapshot/cli/lib/update.js:0:0
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/cli/lib/update.js:0:0)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/events.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/bootstrap.js:0:0
    at bitmask (/snapshot/cli/node_modules/lodash/lodash.js:10067:25)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3
error:  TypeError: Cannot read property 'version' of undefined
    at /snapshot/cli/lib/update.js:0:0
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/cli/lib/update.js:0:0)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/events.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/bootstrap.js:0:0
    at bitmask (/snapshot/cli/node_modules/lodash/lodash.js:10067:25)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3
```
