### ISSUE TITLE
chown: invalid user: 'solr:solr' after upgrade to beta32

### ISSUE THREAD

**Issue by spuky** [lando/lando#611]
Bug Report
==========

OSX High Siera v3.0.0-beta.32

```yml
name: xxx
recipe: pantheon
config:
  framework: drupal
  env: dev
  site: dkluge
  id: xxxxxx
```

lando start or lando rebuild

command ends with:

 [notice] Logging in via machine token.
chown: invalid user: 'solr:solr'
error:  message=chown: invalid user: 'solr:solr'

Pantheon site D7 already on my machine after update to Beta 32 i can't start the machine..

Does this bug prevent you from using lando?

Downgraded to beta 31 and am able to work...
