### ISSUE TITLE
lando start error with Windows 7 to 'UpperCase' of null

### ISSUE THREAD

**Issue by benedikt-d** [lando/lando#633]
Bug Report
==========

**Tell us about your setup**

*v3.0.0-beta.35 on Windows 7 Professional with Docker Quick Start Terminal*

**My `.lando.yml`**

```yml
name: voa
recipe: drupal8
services:
  appserver:
    build:
      - 'curl -sS https://platform.sh/cli/installer | php'
      - "mkdir -p ~/.drush/site-aliases"
      - "ln -sf /app/drush/voa.aliases.drushrc.php ~/.drush/site-aliases/voa.drushrc.php"
tooling:
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd:
      - /var/www/.platformsh/bin/platform
    options:
      passthrough: true
config:
  via: nginx
  webroot: web
  database: 'mariadb:10.2'
```

**Tell us about the command you were running**

```bash
lando start
```

**Tell us about the error you got**

```bash
user@Blau MINGW64 /c/Websites/site (test)
$ lando start -vvv
error:  TypeError: Cannot read property 'toUpperCase' of null
    at Object.exports.isInstalled (C:\snapshot\cli\lib\daemon.js:0:0)
    at verifyDaemonInstalled (C:\snapshot\cli\lib\engine.js:0:0)
    at verifyDaemonIsReady (C:\snapshot\cli\lib\engine.js:0:0)
    at Object.exports.list (C:\snapshot\cli\lib\engine.js:0:0)
From previous event:
    at Object.exports.cleanup (C:\snapshot\cli\lib\app.js:0:0)
    at C:\snapshot\cli\lib\app.js:0:0
From previous event:
    at Object.exports.start (C:\snapshot\cli\lib\app.js:0:0)
    at C:\snapshot\cli\plugins\lando-core\lib\tasks\start.js:0:0
From previous event:
    at Object.run (C:\snapshot\cli\plugins\lando-core\lib\tasks\start.js:0:0)
From previous event:
    at C:\snapshot\cli\lib\tasks.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.exports.parseToYargs.command.handler (C:\snapshot\cli\lib\tasks.js
:0:0)
    at Object.module.exports.self.runCommand (C:\snapshot\cli\node_modules\yargs
\lib\command.js:170:22)
    at parseArgs (C:\snapshot\cli\node_modules\yargs\yargs.js:920:28)
    at Object.get [as argv] (C:\snapshot\cli\node_modules\yargs\yargs.js:860:16)

    at C:\snapshot\cli\lib\cli.js:0:0
From previous event:
    at Object.exports.init (C:\snapshot\cli\lib\cli.js:0:0)
    at C:\snapshot\cli\bin\lando.js:0:0
From previous event:
    at Object.<anonymous> (C:\snapshot\cli\bin\lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3
```

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Not Sure

Does this bug prevent you from using lando?

Yes
