### ISSUE TITLE
The post-db-import event does not fire after `lando pull` using the Pantheon recipe

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#636]
```bash
$ lando pull
? Pull code from? dev
? Pull DB from? dev
? Pull files from? none
Verifying that you are logged in and authenticated by getting info about horizonmediacom...
 --------------- ------------------------------------------------------------------------------------- 
  ID              e98f7fae-82e9-4859-957d-309108a7d869                                                 
  Name            horizonmediacom                                                                      
  Label           horizonmedia.com                                                                     
  Created         2017-03-26 17:21:10                                                                  
  Framework       drupal8                                                                              
  Organization                                                                                         
  Service Level   free                                                                                 
  Max Multidevs   10                                                                                   
  Upstream        8a129104-9d37-4082-aaf8-e6f31154644e: git://github.com/pantheon-systems/drops-8.git  
  PHP Version     5.5                                                                                  
  Holder Type     user                                                                                 
  Holder ID       989907d6-de30-4bf2-b81e-af07126f8505                                                 
  Owner           989907d6-de30-4bf2-b81e-af07126f8505                                                 
  Is Frozen?      false                                                                                
 --------------- ------------------------------------------------------------------------------------- 
Logged in as ed.reel@drupalconnect.com
Detected that horizonmediacom is a drupal8 site
Checking for /user/.lando/keys/pantheon.lando.id_rsa
Pulling code...
M	composer.json
M	composer.lock
M	sites/default/settings.php
M	vendor/composer/ClassLoader.php
M	vendor/composer/LICENSE
M	vendor/composer/autoload_files.php
M	vendor/composer/autoload_psr4.php
M	vendor/composer/autoload_static.php
M	vendor/composer/installed.json
Already on 'master'
Your branch is up-to-date with 'origin/master'.
From ssh://codeserver.dev.e98f7fae-82e9-4859-957d-309108a7d869.drush.in:2222/~/repository
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Downloading drush aliases...
 [notice] Aliases file written to ~/.drush/pantheon.aliases.drushrc.php.
@pantheon.horizonmediacom.dev
Clearing remote cache to shrink db size
Cache rebuild complete.                                                     [ok]
 [notice] OK >> dev-horizonmediacom.pantheonsite.io responded
Pulling database...
8.87MiB 0:00:12 [ 743KiB/s] [       <=>                                        ]

Pull complete!
```
If I perform a `lando db-import`, it works as expected:
```bash
$ lando db-import horizonmediacom.dev-201801101332.sql 
Preparing to import /app/horizonmediacom.dev-201801101332.sql into pantheon on database:3306 as pantheon...
Importing /app/horizonmediacom.dev-201801101332.sql...
8.96MiB 0:00:06 [1.33MiB/s] [================================>] 100%            

Import complete!
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Drupal\Core\Composer\Composer::preAutoloadDump
> Drupal\Core\Composer\Composer::ensureHtaccess
Removing packages services cache file:
/app/vendor/drupal/console/extend.console.uninstall.services.yml
Creating packages services cache file: 
/app/vendor/drupal/console/extend.console.uninstall.services.yml
Class DrupalProject\composer\ScriptHandler is not autoloadable, can not call post-install-cmd script
> find . -mindepth 2 -type d -name .git | xargs rm -rf
There are no changes to import.                                                                                                                                                                                                                      [ok]
There are no changes to import.                                                                                                                                                                                                                      [ok]
There are no changes to import.                                                                                                                                                                                                                      [ok]
No database updates required                                                                                                                                                                                                                         [success]
The following extensions will be enabled: config_inspector, devel, kint, stage_file_proxy
Do you really want to continue? (y/n): y
config_inspector was enabled successfully.                                                                                                                                                                                                           [ok]
config_inspector defines the following permissions: inspect configuration
devel was enabled successfully.                                                                                                                                                                                                                      [ok]
devel defines the following permissions: access devel information, execute php code, switch users
kint was enabled successfully.                                                                                                                                                                                                                       [ok]
kint defines the following permissions: access kint
stage_file_proxy was enabled successfully.                                                                                                                                                                                                           [ok]
stage_file_proxy defines the following permissions: administer stage_file_proxy settings
Do you want to update origin key in stage_file_proxy.settings config? (y/n): y
Do you want to update hotlink key in stage_file_proxy.settings config? (y/n): y
Cache rebuild complete.                                                                                                                                                                                                                              [ok]
```
```bash
$ lando version
v3.0.0-beta.35
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya
```
```yaml
name: horizonmediacom
recipe: pantheon
config:
  framework: drupal8
  site: horizonmediacom
  id: e98f7fae-82e9-4859-957d-309108a7d869
  webroot: .

# add development environment settings
# See: https://www.drupal.org/node/2598914
parameters:
  twig.config:
    debug: true
    auto_reload: true
    cache: false

# add in some custom event scripting
events:
  post-db-import:
    appserver: |
      cd /app
      # make sure all composer components are installed
      composer install
      # import the config
      drush cim -y && drush cim -y && drush cim -y
      # execute pending database updates
      drush updb -y
      # enable stage_file_proxy and configure settings
      drush en config_inspector devel kint stage_file_proxy -y
      drush cset stage_file_proxy.settings origin http://dev-horizonmediacom.pantheonsite.io/ -y
      drush cset stage_file_proxy.settings hotlink true -y
      # clear caches just for good measure
      drush cr
```
