### ISSUE TITLE
"curl not found" error w/ WordPress recipe

### ISSUE THREAD

**Issue by davisshaver** [lando/lando#642]
Trying to start a barebones `.lando.yml`..

```
name: wordpress
recipe: wordpress
config:
  php: 'hhvm'
  webroot: web
  database: mariadb
  xdebug: true
```

Ending up with a `curl not found` error.

```
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating network "wordpress_default" with the default driver
Creating volume "wordpress_appserver" with default driver
Creating volume "wordpress_data" with default driver
Creating wordpress_appserver_1 ... done
Creating wordpress_database_1  ...
Creating wordpress_database_1  ... done
Creating wordpress_nginx_1     ... done
/bin/sh: 1: curl: not found
error:  message=/bin/sh: 1: curl: not found
, code=127
```
