### ISSUE TITLE
Platform CLI is throwing "operation not permitted" error on lando start/rebuild

### ISSUE THREAD

**Issue by dandinu** [lando/lando#646]
Hi,

I'm using *lando-v3.0.0-beta.36* on Windows 10 Professional, configured with Platform CLI. I am getting this error when doing a `lando start` or `lando rebuild`:
```
Platform.sh CLI installer

Environment check
  [*] The PHP version is supported: 7.1.13.
  [*] The "json" PHP extension is installed.
  [*] The "phar" PHP extension is installed.
  [*] Git is installed.
  [*] The "openssl" PHP extension is installed.
  [*] The "curl" PHP extension is installed.
  [*] The "ctype" PHP extension is installed.
  [*] The "mbstring" and/or "iconv" PHP extensions are installed.
  [*] The "allow_url_fopen" setting is on.
  [*] The "apc.enable_cli" setting is off.

Download
  Finding the latest version...
  Downloading version 3.26.1...
  Checking file integrity...
  Checking that the file is a valid Phar (PHP Archive)...

Install
  Making the Phar executable...
  Moving the Phar to your home directory...
  Successfully moved the Phar to: /var/www/.platformsh/bin/platform

  Running self:install command...
  To set up the CLI, add the following lines to your shell configuration file:

    # Platform.sh CLI configuration
    export PATH='/var/www/.platformsh/bin':"$PATH"
    . '/var/www/.platformsh/shell-config.rc'
error:  Error
    at ChildProcess.<anonymous> (C:\snapshot\cli\lib\shell.js:0:0)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
From previous event:
    at spawn (C:\snapshot\cli\lib\shell.js:0:0)
    at Object.exports.sh (C:\snapshot\cli\lib\shell.js:0:0)
    at shCompose (C:\snapshot\cli\lib\compose.js:0:0)
    at Object.exports.run (C:\snapshot\cli\lib\compose.js:0:0)
    at C:\snapshot\cli\lib\docker.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.exports.run (C:\snapshot\cli\lib\docker.js:0:0)
    at C:\snapshot\cli\lib\engine.js:0:0
    at runCallback (timers.js:800:20)
From previous event:
    at Object.exports.run (C:\snapshot\cli\lib\engine.js:0:0)
    at AsyncEvents.<anonymous> (C:\snapshot\cli\plugins\lando-services\lib\config.js:0:0)
    at AsyncEvents.handle (C:\snapshot\cli\lib\events.js:0:0)
    at C:\snapshot\cli\lib\events.js:0:0
From previous event:
    at AsyncEvents.emit (C:\snapshot\cli\lib\events.js:0:0)
    at C:\snapshot\cli\lib\app.js:0:0
    at runCallback (timers.js:800:20)
From previous event:
    at Object.exports.start (C:\snapshot\cli\lib\app.js:0:0)
    at C:\snapshot\cli\plugins\lando-core\lib\tasks\start.js:0:0
From previous event:
    at Object.run (C:\snapshot\cli\plugins\lando-core\lib\tasks\start.js:0:0)
From previous event:
    at C:\snapshot\cli\lib\tasks.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.exports.parseToYargs.command.handler (C:\snapshot\cli\lib\tasks.js:0:0)
    at Object.module.exports.self.runCommand (C:\snapshot\cli\node_modules\yargs\lib\command.js:170:22)
    at parseArgs (C:\snapshot\cli\node_modules\yargs\yargs.js:920:28)
    at Object.get [as argv] (C:\snapshot\cli\node_modules\yargs\yargs.js:860:16)
    at C:\snapshot\cli\lib\cli.js:0:0
From previous event:
    at Object.exports.init (C:\snapshot\cli\lib\cli.js:0:0)
    at C:\snapshot\cli\bin\lando.js:0:0
From previous event:
    at Object.<anonymous> (C:\snapshot\cli\bin\lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3
```

I have also tried running a `lando ssh` and manually installing the Platform CLI, using the command `curl -sS https://platform.sh/cli/installer | php`, and I get some more insights on what the issue really is. Here is the error:
```
lando ssh
www-data@f4c1f91d272b:/app$ curl -sS https://platform.sh/cli/installer | php
Platform.sh CLI installer

Environment check
  [*] The PHP version is supported: 7.1.13.
  [*] The "json" PHP extension is installed.
  [*] The "phar" PHP extension is installed.
  [*] Git is installed.
  [*] The "openssl" PHP extension is installed.
  [*] The "curl" PHP extension is installed.
  [*] The "ctype" PHP extension is installed.
  [*] The "mbstring" and/or "iconv" PHP extensions are installed.
  [*] The "allow_url_fopen" setting is on.
  [*] The "apc.enable_cli" setting is off.

Download
  Finding the latest version...
  Downloading version 3.26.1...
  Checking file integrity...
  Checking that the file is a valid Phar (PHP Archive)...

Install
  Making the Phar executable...
  Moving the Phar to your home directory...

Error (2): rename(/app/platform.phar,/var/www/.platformsh/bin/platform): Operation not permitted
```
Apparently, the file move is no longer permitted. This used to work in **beta.32** and below. Has anything changed since then?

Here is my `.lando.yml` file:
```
# Name the application the same as in your .platform.app.yaml.
name: ixia-comm
# Use the recipe appropriate for your application.
recipe: drupal8

# The following additional build step will install the Platform CLI
# in the application container.
services:
  appserver:
    build:
      - "curl -sS https://platform.sh/cli/installer | php"

# The following entry creates a `lando platform` command that will run
# any Platform CLI command from inside the container if desired. 
tooling:
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd:
      - /var/www/.platformsh/bin/platform
    options:
      passthrough: true
  sync:
    description: Execute script to sync files to the local machine.
    service: appserver
    cmd: /app/scripts/lando-scripts/sync.sh

config:
  # Lando defaults to Apache. Switch to nginx to match Platform.sh.
  via: nginx

  # Set the webroot to match your .platform.app.yaml.
  webroot: web

  # Lando defaults to the latest MySQL release, but Platform.sh uses MariaDB.
  # Specify the version to match what's in services.yaml.
  database: mariadb:10.1
```

Does anyone have any ideas?

**Comment by serundeputy** [comment]
Thanks @dandinu ; @mattpaz and I reported and verified the same issue in #650 but this one was first! I've closed #650 and we can work to solve here.

@dandinu worth noting that even though the error looks `bad` the cli still works so you can still run your `platform` commands once the app is started.  We still need to fix it though.

-----
Thanks for reporting @mattpaz 

I can confirm this error is thrown when starting an app.  I tried on `v3.0.0-beta.36` and downgrading to `v3.0.0-beta.35` but the error happens on both versions.

I dug into the [platfrom-cli](https://github.com/platformsh/platform-cli) a bit and found that 20 days ago the installer was refactored to detect if `bash` or `zsh` are available before loading in certain files: https://github.com/platformsh/platformsh-cli/commit/a6a348bbacfc69afeb3679ee8d51d6600a592ce3#diff-e96945190ee925e175b0ef90403d40aaR5

In `lando` depending on `sh` or `/bin/bash` `$HOME` is returning different values so that may have something to do with this, but I've not been able to figure out how to definitively check this hypothesis.

**Comment by dandinu** [comment]
I am using both `CMD` and `bash` (on Windows 10, both) and it is replicating.

**Comment by serundeputy** [comment]
> In lando depending on sh or /bin/bash $HOME is returning different values

to be clear this is the shell script inside the lando appserver container being executed as `sh` or `bash` not the host OS shell.

**Comment by dandinu** [comment]
I believe that was my error. I was erroneously mentioning the host OS shell. However, my shell script in the lando appserver is `bash` so I can confirm it is also replicating with `bash` as the shell inside the docker container.

**Comment by labboy0276** [comment]
This was failing me also in travis builz, so i changed the platform cli build to this in my lando.yml:

```yml
services:
  appserver:
    build:
      - "mkdir /var/www/.platformsh && mkdir /var/www/.platformsh/bin"
      - "curl -fsSL -o /var/www/.platformsh/bin/platform https://github.com/platformsh/platformsh-cli/releases/download/v3.26.0/platform.phar"
      - "chmod ug+x /var/www/.platformsh/bin/platform"
```

**Comment by mattpaz** [comment]
Confirmed that the technique from @labboy0276 seemed to help with the issue we were experiencing too.  Thanks!

**Comment by drewf7** [comment]
Chiming in with the same error (line for line identical) from a different use case.

I work on a team at the University of Arizona, and we use Lando for local testing of our custom Drupal distribution.

Our lando.yml file is as follows:
```
name: ua-quickstart
recipe: drupal7
config:
  webroot: uaqsbuildroot
services:
  appserver:
    # Runs drush make within the lando docker container, thereby bypassing the file system issues encountered on windows
    build:
      - "cd $LANDO_MOUNT && drush make build-ua_quickstart.make.yml $LANDO_WEBROOT"
      # This command installs drupal with the ua_quickstart install profile.
      - "drush si ua_quickstart --root=$LANDO_WEBROOT --account-mail=noreply@email.arizona.edu --account-name=uaqs_admin --account-pass=[redacted] --db-url=mysqli://drupal7:drupal7@database:3306/drupal7 --site-name='UA Quickstart' ua_quickstart_install_options_form.uaqs_verbosity=1 -y --verbose"
      # Fix filesystem permissions and ownerships.
      - "find $LANDO_WEBROOT/sites/default/files ! -name '\\.*' -exec chgrp $LANDO_WEBROOT_GROUP {} \\;"
      - "find $LANDO_WEBROOT/sites/default/files -type d -exec chmod 2775 {} \\;"
      - "find $LANDO_WEBROOT/sites/default/files ! -name '\\.*' -a -type f -exec chmod 664 {} \\;"
```
I haven't yet determined which command is causing the error to appear (although I will be doing further testing). Similar to @mattpaz experience though, everything does seem to work fine if I again run `lando start`. 

I have tested this with identical results on two computers, both running Windows 10 Enterprise. One with Lando v3.0.0-beta.35 and one with Lando v3.0.0-beta.36.

Let me know if there is anymore information I can provide to help.

**Comment by devkodama** [comment]
I had the same error on lando start and was able to resolve it with labboy0276's solution by changing my .lando.yml from:

```
services:
  appserver:
    build:
      - "curl -sS https://platform.sh/cli/installer | php"
      - "cd $LANDO_MOUNT && composer install"

```

to:

```
services:
  appserver:
    build:
      - "curl -fsSL -o /var/www/.platformsh/bin/platform https://github.com/platformsh/platformsh-cli/releases/download/v3.26.0/platform.phar"
      - "chmod ug+x /var/www/.platformsh/bin/platform"
      - "cd $LANDO_MOUNT && composer install"

```

I had to delete labboy0276's mkdir commands because they threw errors because the directories already existed.

Don't really understand why this works but thank you for the solution.
