### ISSUE TITLE
Lando dies with container not running error

### ISSUE THREAD

**Issue by aaron-capellic** [lando/lando#648]
Bug Report
==========

After the update to beta 36, Lando dies with "container not running error".

lando-v3.0.0-beta.36
ubuntu 16.04

```yml
name: site
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: uca
  id: 3913120e-xxxxx-xx-xx-b2c8a
  web: web
  xdebug: false
events:
  post-db-import:
    - appserver: cd $LANDO_MOUNT && composer install
services:
  appserver:
    extras:
      - "apt-get update"
      - "apt-get install -y apt-utils"
      - "curl -sL https://deb.nodesource.com/setup_6.x | bash"
      - "apt-get install -y nodejs"
      - "npm install --global gulp-cli"
    build:
      - "cd $LANDO_MOUNT && cd web/themes/custom/site2017/patternlab && composer install"
      - "cd $LANDO_MOUNT && cd web/themes/custom/site2017 && npm install"
      - "cd $LANDO_MOUNT && cd web/themes/custom/site2017 && gulp build"
      - "cd $LANDO_MOUNT && cd web/themes/custom/site2017 && gulp translate"
    overrides:
      services:
        environment:
          BEHAT_PARAMS: >-
            {"extensions" : {"Behat\\MinkExtension" : {"base_url" :
            "http://nginx/"}, "Drupal\\DrupalExtension" : {"drush" :   {
            "root":  "/app/web" }}}}
          CI_ENV: ci-${CIRCLE_BUILD_NUM}
          PANTHEON_SITE: ${TERMINUS_SITE}
          CIRCLE_BRANCH: ${CIRCLE_BRANCH}
          CIRCLE_USERNAME: ${CIRCLE_USERNAME}
          GIT_EMAIL: ${GIT_EMAIL}
tooling:
  phplint:
    service: appserver
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat
```

```
lando rebuild

error:  Error: (HTTP code 409) unexpected - Container 305d172d57093f1f53d3db250086ccb5961b4ac25ed750d36197583c5226a41c is not running 
    at /snapshot/cli/node_modules/docker-modem/lib/modem.js:254:17
    at getCause (/snapshot/cli/node_modules/docker-modem/lib/modem.js:284:7)
    at Modem.buildPayload (/snapshot/cli/node_modules/docker-modem/lib/modem.js:253:5)
    at IncomingMessage.<anonymous> (/snapshot/cli/node_modules/docker-modem/lib/modem.js:229:14)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
From previous event:
    at /snapshot/cli/lib/container.js:0:0
From previous event:
    at Object.exports.run (/snapshot/cli/lib/container.js:0:0)
    at /snapshot/cli/lib/docker.js:0:0
    at /snapshot/cli/node_modules/dockerode/lib/exec.js:130:7
    at Modem.buildPayload (/snapshot/cli/node_modules/docker-modem/lib/modem.js:270:7)
    at IncomingMessage.<anonymous> (/snapshot/cli/node_modules/docker-modem/lib/modem.js:229:14)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
From previous event:
    at Object.exports.run (/snapshot/cli/lib/docker.js:0:0)
    at /snapshot/cli/lib/engine.js:0:0
    at runCallback (timers.js:800:20)
From previous event:
    at Object.exports.run (/snapshot/cli/lib/engine.js:0:0)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-services/lib/config.js:0:0)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/events.js:0:0
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js:0:0)
From previous event:
    at Object.exports.start (/snapshot/cli/lib/app.js:0:0)
    at /snapshot/cli/lib/app.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.exports.rebuild (/snapshot/cli/lib/app.js:0:0)
    at /snapshot/cli/plugins/lando-core/lib/tasks/rebuild.js:0:0
From previous event:
    at Object.run (/snapshot/cli/plugins/lando-core/lib/tasks/rebuild.js:0:0)
From previous event:
    at /snapshot/cli/lib/tasks.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.exports.parseToYargs.command.handler (/snapshot/cli/lib/tasks.js:0:0)
    at Object.module.exports.self.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:170:22)
    at parseArgs (/snapshot/cli/node_modules/yargs/yargs.js:920:28)
    at Object.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:860:16)
    at /snapshot/cli/lib/cli.js:0:0
From previous event:
    at Object.exports.init (/snapshot/cli/lib/cli.js:0:0)
    at /snapshot/cli/bin/lando.js:0:0
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3

```

```
docker ps
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS                          PORTS                                                                 NAMES
c0980600887a        devwithlando/pantheon-appserver:7.0-fpm   "/lando-entrypoint.s…"   3 minutes ago       Up 3 minutes                    9000/tcp                                                              uca_appserver_1
7607300d8026        devwithlando/pantheon-index:3.6           "/lando-entrypoint.s…"   3 minutes ago       Up 3 minutes                    0.0.0.0:32829->449/tcp                                                uca_index_1
7262ce0dff8e        redis:2.8                                 "/lando-entrypoint.s…"   3 minutes ago       Up 3 minutes                    0.0.0.0:32828->6379/tcp                                               uca_cache_1
35c333eb2d82        mariadb:10.0                              "/lando-entrypoint.s…"   3 minutes ago       Up 3 minutes                    0.0.0.0:32827->3306/tcp                                               uca_database_1
335b6e660755        de9f6e044a46                              "/bin/bash"              5 weeks ago         Restarting (0) 27 seconds ago                                                                         unruffled_hamilton
4ca36c38b3dd        traefik:1.3-alpine                        "/lando-entrypoint.s…"   6 weeks ago         Up 4 hours                      0.0.0.0:443->443/tcp, 0.0.0.0:8000->80/tcp, 0.0.0.0:58086->8080/tcp   landoproxyhyperion5000gandalfedition_proxy_1

```
```
 lando restart -vvv
WARNING: The TERMINUS_SITE variable is not set. Defaulting to a blank string.
WARNING: The CIRCLE_BUILD_NUM variable is not set. Defaulting to a blank string.
WARNING: The CIRCLE_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The GIT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The CIRCLE_BRANCH variable is not set. Defaulting to a blank string.
Stopping uca_appserver_1 ... done
Stopping uca_index_1 ... done
Stopping uca_cache_1 ... done
Stopping uca_database_1 ... done
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
WARNING: The TERMINUS_SITE variable is not set. Defaulting to a blank string.
WARNING: The CIRCLE_BUILD_NUM variable is not set. Defaulting to a blank string.
WARNING: The CIRCLE_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The GIT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The CIRCLE_BRANCH variable is not set. Defaulting to a blank string.
Starting uca_database_1 ... 
Starting uca_index_1 ... 
Starting uca_database_1
Starting uca_cache_1 ... 
Starting uca_index_1
Starting uca_index_1 ... done
Starting uca_appserver_1 ... 
Starting uca_appserver_1 ... done
Starting uca_nginx_1 ... 
Starting uca_nginx_1 ... done
Starting uca_edge_1 ... 
Starting uca_edge_1 ... done
Starting uca_edge_ssl_1 ... 
Starting uca_edge_ssl_1 ... done

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME       uca                                                      
 LOCATION   /var/www/capellic/uca2                                   
 SERVICES   appserver, nginx, database, cache, edge_ssl, edge, index 
                                                                     
 EDGE URLS  http://localhost:32845                                   
            http://uca.lndo.site:8000                                
            https://uca.lndo.site                                    
```

```
lando behat --config=/app/tests/behat-pantheon.yml
Feature: Create Author
  In order to add blog authors to the site
  As an editor
  I need to be able to create Author nodes

  @api
  Scenario: Check author form fields                                  # features/author.feature:7
    Given I am logged in as a user with the "administrator" role      # Drupal\DrupalExtension\Context\DrupalContext::assertAuthenticatedByRole()
      cURL error 6: Could not resolve host: nginx (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (GuzzleHttp\Exception\ConnectException)
```
