### ISSUE TITLE
Lando info and start showing wrong info, docs update too

### ISSUE THREAD

**Issue by ccjjmartin** [lando/lando#658]
Bug Report
==========

**Tell us about your setup**

v3.0.0-beta.35 on OSX El Capitan

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

*Example:*

NOTE: You may need to change the webroot for testing.
```yml
name: drupal
recipe: drupal7
config:
  php: '5.6'
  via: apache
  webroot: build
  database: mariadb:10.1
  xdebug: true
proxy:
  mailhog:
    - mail.drupal.lndo.site
  edge:
    - local.drupal.com
  index:
    - admin.solr.lndo.site:8983
services:
  cache:
    type: memcached:1.4
    mem: 128
    portforward: 11222
  index:
    type: solr:4.10
    portforward: 9999
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  edge:
    type: varnish:4.1
    backends:
      - appserver
    ssl: true
tooling:
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat --profile=drupal --config=/app/behat.yml
  varnishadm:
    service: edge
    user: root
  varnishstat:
    service: edge
    user: root
  varnishlog:
    service: edge
    user: root
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

*Example:*

```bash
lando start
lando info
```

**Tell us about the error you got**

Not really an error just wrong information.  The core is actually named `collection1`.  I am also getting URLs in red after lando start because it is testing on port `8000` even though it is configured for 9999.  I was following the docs here so maybe a docs update is needed for part of this.

```bash
  "index": {
    "type": "solr",
    "version": "4.10",
    "internal_connection": {
      "core": "index1",
      "host": "index",
      "port": 8983
    },
    "external_connection": {
      "core": "index1",
      "host": "localhost",
      "port": "9999"
    },
    "urls": [
      "http://admin.solr.lndo.site:8000",
      "https://admin.solr.lndo.site"
    ]
  },
```

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
Yes, the line below on this page (https://docs.devwithlando.io/services/solr.html) might not be working properly:

```
  # Lets get a nice lndo url for the solr web interface
  index:
    - admin.solr.lndo.site:8983
```

Does this bug prevent you from using lando?
No
