### ISSUE TITLE
Access denied for additional DB services (mysql, all?) causing db-import to fail.

### ISSUE THREAD

**Issue by Kolin** [lando/lando#671]
Bug Report
==========

**Tell us about your setup**

v3.0.0-beta.35 on Windows 10 Professional

**Tell us about your `.lando.yml`**

```yml
name: llaia-website
recipe: drupal8
config:
  webroot: ./web

services:
  oldmembersdb:
      type: mysql
      creds:
        user: oldmembersdb
        password: oldmembersdb
        database: oldmembersdb
```

**lando info output:**

```yml
{                                                                                              
  "appserver": {                                                                               
    "type": "php",                                                                             
    "version": "7.1",                                                                          
    "via": "apache",                                                                           
    "webroot": "./web",                                                                        
    "config": {                                                                                
      "conf": "C:\\Users\\Kolin\\.lando\\services\\config\\drupal8\\php.ini"                   
    },                                                                                         
    "urls": [                                                                                  
      "https://localhost:32800",                                                               
      "http://localhost:32802",                                                                
      "http://llaia-website.lndo.site",                                                        
      "https://llaia-website.lndo.site"                                                        
    ]                                                                                          
  },                                                                                           
  "database": {                                                                                
    "type": "mysql",                                                                           
    "version": "latest",                                                                       
    "creds": {                                                                                 
      "user": "drupal8",                                                                       
      "password": "drupal8",                                                                   
      "database": "drupal8"                                                                    
    },                                                                                         
    "internal_connection": {                                                                   
      "host": "database",                                                                      
      "port": 3306                                                                             
    },                                                                                         
    "external_connection": {                                                                   
      "host": "localhost",                                                                     
      "port": "32801"                                                                          
    },                                                                                         
    "config": {                                                                                
      "confd": "C:\\Users\\Kolin\\.lando\\services\\config\\drupal8\\mysql"                    
    }                                                                                          
  },                                                                                           
  "oldmembersdb": {                                                                            
    "type": "mysql",                                                                           
    "version": "latest",                                                                       
    "creds": {                                                                                 
      "user": "oldmembersdb",                                                                  
      "password": "oldmembersdb",                                                              
      "database": "oldmembersdb"                                                               
    },                                                                                         
    "internal_connection": {                                                                   
      "host": "oldmembersdb",                                                                  
      "port": 3306                                                                             
    },                                                                                         
    "external_connection": {                                                                   
      "host": "localhost",                                                                     
      "port": "not forwarded"                                                                  
    }                                                                                          
  }                                                                                            
}                                                                                              
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

```bash
lando db-import lochlom1_llaia.sql.gz --host oldmembersdb --database oldmembersdb --user oldmembersdb --password oldmembersdb
```

**Tell us about the error you got**

```Preparing to import /app/lochlom1_llaia.sql.gz into oldmembersdb on oldmembersdb:3306 as oldmembersdb...
ERROR 1045 (28000): Access denied for user 'oldmembersdb'@'172.19.0.3' (using password: YES)
Destroying all current tables in oldmembersdb...
NOTE: See the --no-wipe flag to avoid this step!
Importing /app/lochlom1_llaia.sql.gz...
ERROR 1045 (28000): Access denied for user 'oldmembersdb'@'172.19.0.3' (using password: YES)
  64KiB 0:00:00 [ 6.4MiB/s] [============>                                                                          ] 16%
```

**Comment by Kolin** [comment]
@dustinleblanc no that fails as well.

```
www-data@8c1284e23ca4:/app$ mysql -uoldmembers -poldmembers
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'oldmembers'@'localhost' (using password: YES)
```

I also tried with the `oldmembersdb` as the username and password I assume `oldmembers` was a typo.

```
www-data@8c1284e23ca4:/app$ mysql -uoldmembersdb -poldmembersdb
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'oldmembersdb'@'localhost' (using password: YES)
```

**Comment by dustinleblanc** [comment]
@Kolin good catch on my typos 😄 

Yeah, I'd say that this indicates the service config isn't working right. I'd recommend a rebuild if you haven't yet.

**Comment by Kolin** [comment]
After running `lando rebuild` 
I still get an access denied message:

```
lando db-import lochlom1_llaia.sql.gz --host oldmembersdb --database oldmembersdb --user 

oldmembersdb --password oldmembersdb
Preparing to import /app/lochlom1_llaia.sql.gz into oldmembersdb on oldmembersdb:3306 as oldmembersdb...
ERROR 1045 (28000): Access denied for user 'oldmembersdb'@'172.19.0.4' (using password: YES)
Destroying all current tables in oldmembersdb...
NOTE: See the --no-wipe flag to avoid this step!
Importing /app/lochlom1_llaia.sql.gz...
ERROR 1045 (28000): Access denied for user 'oldmembersdb'@'172.19.0.4' (using password: YES)
  64KiB 0:00:00 [9.49MiB/s] [====>                             ] 16%```

**Comment by uberhacker** [comment]
@Kolin: Have you tried?
```
lando mysql --host oldmembersdb --database oldmembersdb --user oldmembersdb --password oldmembersdb < lochlom1_llaia.sql.gz
```

**Comment by labboy0276** [comment]
@pirog and @serundeputy were made aware of this issue this AM.  I tried everything above and then some.  The work around for importing a 2nd DB into your 2nd DB service is:

lando ssh DBNAME -u root
use MYDB
source dump.sql.gz

**Comment by Kolin** [comment]
Thanks @labboy0276 

In the end I used this workaround 
```
gunzip lochlom1_llaia.sql.gz
lando ssh oldmembersdb -u root
mysql
use oldmembersdb
source lochlom1_llaia.sql
```

**Comment by pstevemichel** [comment]
Thanks for this; @laddyboy0276's approach worked for me.

**Comment by parijke** [comment]
I used the drupal8 recipe. It didn't work with the credentials shown in lando list. But it did when I used:

database: drupal8
user: root
password; <blank>
hostname: database

so something is going wrong in setting the db credentials

**Comment by serundeputy** [comment]
The problem here is when trying to import into a second db service you must specify the database name, that is documented here: https://docs.devwithlando.io/tutorials/db-import.html

So in @labboy0276 's case the command:

```bash
lando db-import -u drupal7db -p drupal7db -d drupal7db DBDUMP.sql.gz -h d7db
```

will get it done. I've confirmed this to be working. closing ticket.

**Comment by tonystar** [comment]
+1 @parijke. Doesn't work with drupal8:drupal8, but works with root:<empty>. Spent a day for this...(

**Comment by denics** [comment]
The issue is still there, I am trying lando with civicrm. This is my lando.yml (part of)

```yaml
recipe: drupal7
config:
  php: '5.6'
  via: 'apache:2.4'
  webroot: 'web'
  database: 'mariadb:10.1'
  drush: ^8
  xdebug: true
services:
  appserver:
  node:
    type: node:10
  civicrm:
    type: mariadb:10.1
```
This is the relevant ``lando info``:

```json
[
  {
    service: 'appserver',
    urls: [
      'https://localhost:33118',
      'http://localhost:33119',
      'http://unesco.lndo.site',
      'https://unesco.lndo.site',
      'http://*.unesco.lndo.site',
      'https://*.unesco.lndo.site'
    ],
    type: 'php',
    via: 'apache:2.4',
    webroot: 'web',
    version: '5.6',
    meUser: 'www-data',
    hostnames: [
      'appserver.civicrm.internal'
    ]
  },
  {
    service: 'database',
    urls: [],
    type: 'mariadb',
    internal_connection: {
      host: 'database',
      port: '3306'
    },
    external_connection: {
      host: 'localhost',
      port: '33120'
    },
    creds: {
      database: 'drupal7',
      password: 'drupal7',
      user: 'drupal7'
    },
    config: {
      database: '/home/.../.lando/config/drupal7/mysql.cnf'
    },
    version: '10.1',
    meUser: 'www-data',
    hostnames: [
      'database.civicrm.internal'
    ]
  },
  {
    service: 'node',
    urls: [],
    type: 'node',
    config: {},
    version: '10',
    meUser: 'node',
    hostnames: [
      'node.civicrm.internal'
    ]
  },
  {
    service: 'civicrm',
    urls: [],
    type: 'mariadb',
    internal_connection: {
      host: 'civicrm',
      port: '3306'
    },
    external_connection: {
      host: 'localhost',
      port: 'not forwarded'
    },
    creds: {
      database: 'database',
      password: 'mariadb',
      user: 'mariadb'
    },
    config: {},
    version: '10.1',
    meUser: 'www-data',
    hostnames: [
      'civicrm.civicrm.internal'
    ]
  }
]
```
If I ssh into my civicrm service:
```bash
lando ssh -s civicrm

www-data@0fd6ac81f148:/app$ mysql -u mariadb -pmariadb civicrm
ERROR 1044 (42000): Access denied for user 'mariadb'@'%' to database 'civicrm'

www-data@0fd6ac81f148:/app$ mysql -u mariadb -pmariadb        
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 33157
Server version: 10.1.41-MariaDB Source distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
```

so it seems that the user "mariadb" has access to the DB server, but not to the database???
