### ISSUE TITLE
Starting Local Filepath

### ISSUE THREAD

**Issue by brianO3world** [lando/lando#679]
Good Evening,

Not sure if I'm posting this in the right place, but I wasn't sure if I was just missing something or if this wasn't doable.

I'm hosting a site on Github Pages but I'm not using a custom domain, so my example project URL is:

http://company.github.io/project-name/

This is my Lando setup... I'm using the LAMP Recipe as a starting point. When I setup my project, the generated local URL is: https://project-name.lndo.site

This causes an issue with my navigation between local and Github Pages. Is it possible to make it so my local environment is configured to run from: https://project-name.lndo.site/project-name

Bug Report
==========

My setup:
*v3.0.0-beta.35 on Mac OS High Sierra 10.13.2*

My current YML file:
```yml
name: project-name
recipe: lamp
config:
  webroot: .
```

==========

Any help is much appreciated.

Thanks,
Brian

**Comment by dustinleblanc** [comment]
@brianO3world this would be done in the apache configuration.

**Comment by brianO3world** [comment]
@dustinleblanc Thanks for the followup. I've been tinkering with this today and I must not understand where that would be done. I was testing adding a new `webroot` like here:

https://docs.devwithlando.io/services/apache.html

That doesn't seem to be working. Here's my updated YML file:

```
name: vtx-style-guide
recipe: lamp

# Build me an apache worthy of the internet
services:

  # You can name this key anything you want.
  html:

    # Optionally specify a webroot if it is a subdirectory of the appRoot
    webroot: test/vtx-style-guide
```

Thoughts?
