### ISSUE TITLE
Packages installed with apt-get aren't retained after restarting

### ISSUE THREAD

**Issue by JeremyDunn** [lando/lando#683]
Bug Report
==========

**Tell us about your setup**

v3.0.0-beta.35 on MacOS HIgh Sierra (10.13.3)

**Tell us about your `.lando.yml`**

```yml
name: cms
recipe: laravel
config:
  php: '7.0'
  via: nginx
  webroot: public
  database: mysql:5.6
  cache: redis:3.2
  xdebug: true
services:
  appserver:
    build:
      - echo '* * * * * /usr/local/bin/php /app/artisan schedule:run >> /dev/null 2>&1' | crontab -
      - cd $LANDO_MOUNT && composer install
    extras:
      - apt-get update -y
      - apt-get install sudo nano vim unrtf cron supervisor -y
```

**Description of issue**

When lando is running after destroying or rebuild, the apt packages are installed properly.  I can ssh into the `appserver` container and run the commands.  Then, if I restart lando and ssh into the `appserver` container again, they are no longer installed.

I've noticed that running `docker ps` right after rebuilding shows a new container id, but when I just restart lando I see a different container id for the appserver (devwithlando/php:7.0-fpm).

**Steps to reproduce**
(assuming lando hasn't been build yet or has been destroyed)

```bash
lando start
lando ssh
```

At this point, the apt packages are installed.

```bash
docker ps
```
Remember the container id for the 'appserver'.

```bash
lando restart
docker ps
```
Now the container id for the 'appserver' is different.

```bash
lando ssh
```
And the packages are no longer installed. 
At this point, if you restart lando the container id doesn't change anymore.

Any suggestions?
