### ISSUE TITLE
[BUG] chown solr:solr fails on Solr 3:6 service with custom data directory.

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#692]
When using `solr:3.6` type (referenced in [plugins/lando-services/services/solr/solr.js:53](https://github.com/lando/lando/blob/98291d7483766c5d301281c9ac2b81da594e8704/plugins/lando-services/services/solr/solr.js#L53) with a custom directory setting, the Solr service fails at [plugins/lando-services/services/solr/solr.js:119](https://github.com/lando/lando/blob/98291d7483766c5d301281c9ac2b81da594e8704/plugins/lando-services/services/solr/solr.js#L119) with a `user does not exist` error.

My Lando Config:

```YML
  solr:
    type: solr:3.6
    portforward: true
    config:
      conf: custom/lib/Apache/Solr/conf
```

Based on the owner of `/opt/solr/example/solr/conf` within the Solr service it looks like the owner should be www-data.

**Comment by tylerssn** [comment]
Temporary workaround:

```YML
  solr:
    type: solr:3.6
    portforward: true
    overrides:
      services:
        build: ${PWD}/dev/lando/services/solr
    extras:
      - 'chown -R www-data:www-data  /opt/solr/example/solr/conf'
```
