### ISSUE TITLE
Files not pulled from Pantheon "live" site

### ISSUE THREAD

**Issue by johnnypea** [lando/lando#693]
Bug Report
==========

**Tell us about your setup**

v3.0.0-beta.35 on macOS High Sierra v10.13.3 

**Tell us about your `.lando.yml`**

```yml
name: example
recipe: pantheon
config:
  framework: WordPress
  site: example
  id: 111111-2222-33333-4444-555555
```

**Tell us about the command you were running**

```bash
lando pull
```

```bash
? Pull code from? dev
? Pull DB from? live
? Pull files from? live
```

**Tell us about the error you got**

It got stuck at "Pulling files..." when pulling from Pantheon "live" environment. It works with "dev" environment though. It pulled database from "live" with no problems.
