### ISSUE TITLE
NGINX Error: Upstream sent too big header while reading response header from upstream

### ISSUE THREAD

**Issue by labboy0276** [lando/lando#704]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

beta-35 & Ubuntu 16.04

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

```yml
name: rmc
recipe: drupal8
config:
  via: nginx
  webroot: web
  database: mariadb:10.1
  php: '7.1'

services:
  appserver:
    build:
      - "mkdir -p /var/www/.platformsh && mkdir -p /var/www/.platformsh/bin"
      - "curl -fsSL -o /var/www/.platformsh/bin/platform https://github.com/platformsh/platformsh-cli/releases/download/v3.26.0/platform.phar"
      - "chmod ug+x /var/www/.platformsh/bin/platform"
      - "cd $LANDO_MOUNT && composer install"
      - "/app/vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer"
    overrides:
      services:
        environment:
          BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://nginx/"}, "Drupal\\DrupalExtension" : {"drush" :   {  "root":  "/app/web" }}}}'
  d7db:
    type: mariadb
    creds:
      user: drupal7db
      password: drupal7db
      database: drupal7db

tooling:
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd:
      - /var/www/.platformsh/bin/platform
    options:
      passthrough: true
  phplint:
    service: appserver
    cmd:
      - /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd:
      - /app/vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd:
      - /app/vendor/bin/phpunit
  behat:
    service: appserver
    cmd:
      - /app/vendor/bin/behat
  git:
   service: appserver

```

**Tell us about the command you were running**

Not a command, but an error in the browser.  

**Tell us about the error you got**

Rerun the command that produced your error in `verbose` mode. Paste in the error and the ~100 lines that proceeded it.

502 in the browser, the nginx log says this:

```bash
nginx_1      | 2018/02/14 19:36:19 [error] 373#373: *95 upstream sent too big header while reading response header from upstream, client: 172.30.0.2, server: appserver, request: "GET /node/add/grant_object HTTP/1.1", upstream: "fastcgi://192.168.160.4:9000", host: "rmc.lndo.site", referrer: "http://rmc.lndo.site/node/add"
nginx_1      | 172.30.0.2 - - [14/Feb/2018:19:36:19 +0000] "GET /node/add/grant_object HTTP/1.1" 502 575 "http://rmc.lndo.site/node/add" "Mozilla/5.0 (X11; Linux x86_64)
```

**Tell us generally about your bug**

When I visit a node add / edit screen on a Drupal 8 site that has > 25 fields on the node type, it throws a 502.  If I change the number of fields to 25 or less, it works ok.

People on the interwebz suggest adding these vars to nginx.conf:

```bash
fastcgi_buffers 16 16k; 
fastcgi_buffer_size 32k;
```

**Tell us more**

If I switch to apache, those pages work just fine.
