### ISSUE TITLE
Drupal 7 with Postgres Drush cannot clear cache or bootstrap

### ISSUE THREAD

**Issue by barnettrob** [lando/lando#717]
Bug Report
==========

**Tell us about your setup**

Lando version: v3.0.0-beta.35
OS: OS X Sierra 10.12.6

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.
```name: d-7-postgres
recipe: drupal7
config:
  webroot: .
  php: 5.6
  drush: global:8.1.15
  database: postgres
  xdebug: true
```

**Tell us about the error you got**

Running `lando drush cc all` gives response:
```
No Drupal site found, only 'drush' cache was cleared. 
```

I added a drush alias called `@d7gres` and the output of `lando drush @d7gres status` is
```Drupal version         :  7.56                                                                         
 Site URI               :  https://d-7-postgres.lndo.site                                               
 Database driver        :  pgsql                                                                        
 Database hostname      :  database                                                                     
 Database port          :  5432                                                                         
 Database username      :  drupal7                                                                      
 Database name          :  drupal7                                                                      
 PHP configuration      :                                                                               
 PHP OS                 :  Linux                                                                        
 Drush script           :  /usr/local/bin/drush                                                         
 Drush version          :  8.1.15                                                                       
 Drush temp directory   :  /tmp                                                                         
 Drush configuration    :                                                                               
 Drush alias files      :  /app//drush/d7gres.aliases.drushrc.php /app/drush/d7gres.aliases.drushrc.php 
 Drupal root            :  /app                                                                         
 Drupal Settings File   :  sites/default/settings.php                                                   
 Site path              :  sites/default 
```

I notice that it's missing
` Drupal bootstrap                :  Successful`

I ran `lando drush @d7gres sql-cli` which returns:
```
sh: 1: psql: not found
SQL client error occurred.  
```

Running `lando drush @d7gres cc all -vvv` returns:
```
Executing: PGPASSFILE=/tmp/drush_GUpLCy psql -q --dbname=drupal7 --host=database --port=5432 --username=drupal7  --no-align --field-separator="	" --pset tuples_only=on --file /tmp/drush_dipbyw
No Drupal site found, only 'drush' cache was cleared.   
```  

If there is any more relevant information that I can provide, please let me know.

Does this bug prevent you from using lando?
Yes, because having drush commands is very important

**Comment by serundeputy** [comment]
@barnettrob thanks for reporting.

I can verify the bug. 

.lando.yml

```yaml
name: pgd7
recipe: drupal7 
config:
  webroot: .
  php: 5.6
  drush: global:8.1.15
  database: postgres
  xdebug: true
```

* `lando start`
* install drupal
* `lando cc all --debug`

```bash
Executing: PGPASSFILE=/tmp/drush_VFyBTU psql -q --dbname=drupal7 --host=database --port=5432 --username=drupal7  --no-align --field-separator="	" --pset tuples_only=on --file /tmp/drush_Teng72
  sh: 1: psql: not found
```

Looks like the `postgresql-client` is not on the `appserver`.

I added the `postgresql-client` to the `appserver` in a build step:

```yaml
name: pgd7
recipe: drupal7 
config:
  webroot: .
  php: 5.6
  drush: global:8.1.15
  database: postgres
  xdebug: true

services:
  appserver:
    extras:
      - apt-get update
      - apt-get install postgresql-client
    build:
      - touch ~/.pgpass
      - echo  database:5432:drupal7:drupal7:drupal7 > ~/.pgpass
      - chmod 600 ~/.pgpass
```

@barnettrob that should get you going for now.

@pirog can/should we consider adding the `psql` client to the `appserver` either conditionally or universally?
