### ISSUE TITLE
Containers are not persistent

### ISSUE THREAD

**Issue by ccjjmartin** [lando/lando#718]
Bug Report
==========

**Tell us about your setup**

Mac High Sierra
Lando Beta35
Docker for Mac (49 and 53 - switched from stable to edge to see if this fixed it)

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

*Example:*

```yml
name: abc
recipe: drupal7
config:
  php: '5.6'
  via: apache
  webroot: build
  database: mariadb:10.1
  xdebug: true
proxy:
  mailhog:
    - mail.abc.lndo.site
  edge:
    - local.abc.com
  index:
    - admin.solr.lndo.site:8983
services:
  cache:
    type: memcached:1.4
    mem: 128
    portforward: 11222
  index:
    type: solr:4.10
    portforward: 9999
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  edge:
    type: varnish:4.1
    backends:
      - appserver
    ssl: true
tooling:
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat --profile=abc --config=/app/behat.yml
  varnishadm:
    service: edge
    user: root
  varnishstat:
    service: edge
    user: root
  varnishlog:
    service: edge
    user: root
  drush:
    service: appserver
    cmd:
      - "drush"
      - "--root=/app/build"
```

**Tell us about the command you were running**

This site has been working fine for the last 3-4 weeks and today both my laptop and my co-workers computer are now not starting.

*Example:*

```bash
`lando start`
`lando db-import`
```

**Tell us about the error you got**

```
$ lando db-import reference/abc.sql.gz
Recreating abc_database_1 ...
Recreating abc_appserver_1 ... done
Preparing to import /app/reference/abc.sql.gz into drupal7 on database:3306 as drupal7...
ERROR 2005 (HY000): Unknown MySQL server host 'database' (0)
Destroying all current tables in drupal7...
NOTE: See the --no-wipe flag to avoid this step!
Gunzipped file detected!
Importing /app/reference/abc.sql.gz...
ERROR 2005 (HY000): Unknown MySQL server host 'database' (0)
  96KiB 0:00:00 [1.76MiB/s] [>                                 ]  0%

Import failed.
```

**Tell us generally about your bug**

When I check to see if the database container is running the container isn't there.  It seems that the containers are disappearing after they are spun up (when this was no previously the case).

Before the database container was giving me errors the edge server appeared to be coming and going so I am wondering if this is an upstream docker for mac issue (would be willing to accept any advice on how to approach such an issue).

**Tell us more**
Does this bug prevent you from using lando?
Yes, my local development environment is broken.
