### ISSUE TITLE
Networking how to configure

### ISSUE THREAD

**Issue by houssem-bensalem** [lando/lando#726]
Bug Report
==========

**Tell us about your setup**

v3.0.0-beta.35, MacOS High sierra 10.13.3

**Tell us about your `.lando.yml`**
2 apps, custom Recipe

App A : With 2 services apache / PHP 7.1 and Mysql.
App B : With 1 service apache / PHP 5.6

I start App A first then APP B, what i need is to access the Database from the App A. This is a very specific case because both applications use the same Database .. so i can't create a database service in the second application.

My question is how to get The hostnames information like the documentation : https://docs.devwithlando.io/config/networking.html

Thank you for your help.

**Comment by dustinleblanc** [comment]
Hi @houssem-bensalem! We spoke in slack earlier today about this issue. Beta 35 doesn't have it available yet, you can play with building Lando from source if you'd like to try it. Going to close this for now. Thanks!

**Comment by vincenzo** [comment]
We've dealt with this on the Slack channel. Networking stuff is not yet available on `beta.35`. It was included as part of `beta.36`, a release that was pulled soon after its publishing. 

A way to achieve similar results is to you use [docker links](https://docs.docker.com/compose/networking/#links), as long as all your services are part of the same Lando app (same `.lando.yml` file). 

A sample config for this: 

```yaml
name: zoo

proxy:
  panda:
    - panda.lndo.site
  puma:
    - puma.lndo.site
  rhino:
    - rhino.lndo.site
    - '*.rhino.lndo.site'

services:
  db:
    type: mongo:3.0
    portforward: 27017
    config: .lando.mongo.yml
    
  panda:
    type: node:8.9
    build:
      - "cd /app/panda && npm install"
    command: cd /app/panda && npm run dev
    overrides:
      services:
        environment:
          PORT: 80
  
  puma:
    type: node:8.9
    build:
      - "cd /app/puma && npm install"
    command: cd /app/puma && npm run dev
    overrides:
      services:
        environment:
          PORT: 80
        links:
          - "panda:panda.lndo.site"

  rhino:
    type: node:8.9
    build:
      - "cd /app/rhino && npm install"
    command: cd /app/rhino && npm run dev
    overrides:
      services:
        environment:
          PORT: 80
        links:
          - "panda:panda.lndo.site"
```
