### ISSUE TITLE
WordPress recipe and Varnish

### ISSUE THREAD

**Issue by Rahe** [lando/lando#739]
Hello,

I'm trying to use Lando in this configuration
- WordPress
- Varnish
- Redis
- Apache

But this isn't working, when getting to the https version I have the "404 document not found".
I have tried to change the apache port to 8080 but this seems to not have any effet.
Do I have a schema like this ?
NGINX(443) > Varnish (80) > Apache (8080) 

Here my yml file
```yml
name: myapp
recipe: wordpress
config:
  webroot: .
  database: mariadb
  php: '7.1'
proxy:
  appserver:
  http-cache:
    - port: 80/tcp
  http-cache_ssl:
    - port: 443/tcp
      default: true
      secure: true
services:
  # Redis Cache
  object-cache:
    type: redis:4.0
    portforward: 6380
    persist: true
  # Varnish Cache
  http-cache:
    type: varnish
    # based on the appserver, given by the WordPress recipe
    backends: appserver
    vcl: conf/varnish/wordpress.vcl
    ssl: true
tooling:
  # Drop the user into a redis shell
  redis-cli:
    service: object-cache
  varnishadm:
    service: http-cache
    user: root
  varnishstat:
    service: http-cache
    user: root
  varnishlog:
    service: http-cache
    user: root
events:
  # Runs composer install and a custom php script after your app starts
  post-start:
    - appserver: cd $LANDO_MOUNT && composer install --prefer-dist
```

This seem to work effortlessly if i configure on NGINX only.

I'm on last release of Lando and MACOS Sierra.

Thank you

**Comment by pirog** [comment]
@Rahe thanks for providing the yaml file here. i can definitely give this a try sometime and see if i can reproduce. 

in the meantime id recommend just using nginx since that seems to work better for you

**Comment by dustinleblanc** [comment]
Even easier, just use the Pantheon recipe which has Varnish/Nginx/Php-fpm dialed like a boss 💯 

I may be a little biased...

**Comment by Rahe** [comment]
Hello,

Thank you for looking at it @pirog , I'm unfortunately not able to use something else than Apache.

**Comment by pirog** [comment]
@Rahe i think the big issue here is using the legacy proxy format instead of the new one

```yml
name: issue739
recipe: wordpress
config:
  webroot: .
  database: mariadb
  php: '7.1'
proxy:
  appserver:
  httpcache:
    - issue739.lndo.site
services:
  # Redis Cache
  objectcache:
    type: redis:4.0
    portforward: 6380
    persist: true
  # Varnish Cache
  httpcache:
    type: varnish
    # based on the appserver, given by the WordPress recipe
    backends: appserver
    # vcl: conf/varnish/wordpress.vcl
    # ssl: true
tooling:
  # Drop the user into a redis shell
  redis-cli:
    service: objectcache
  varnishadm:
    service: httpcache
    user: root
  varnishstat:
    service: httpcache
    user: root
  varnishlog:
    service: httpcache
    user: root
# events:
  # Runs composer install and a custom php script after your app starts
  # post-start:
    # - appserver: cd $LANDO_MOUNT && composer install --prefer-dist
```

Using the master version of lando this boots up as expected
