### ISSUE TITLE
How to properly override Lando's base php 7.1 image using .lando.yml

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#740]
I am hoping to "cache" some of my build steps in a docker image that extends the base Lando PHP 7.1 image. In the past, I have implemented this in Lando by manually building the Dockerfile image and then adding `image: image:tag` to the service override. However, I'd rather point to a Dockerfile  and have Lando perform the build for me.

I've tried each of the YML configurations below but the `appserver` and `nginx` containers fail to launch. No errors are thrown during the build.

**What is your lando version and operating system?** *MacOS*

```yml
#.lando.yml
# --attempt 1
...
services:
  appserver:
    type: php:7.1
    overrides:
      services:
        build: ${PWD}/dev/lando/dockerfiles/appserver
        image: php:7.1
...
```

```yml
#.lando.yml
# --attempt 2
...
services:
  appserver:
    type: php:7.1
    overrides:
      services:
        build: ${PWD}/dev/lando/dockerfiles/appserver 
...
```
```yml
#.lando.yml
# --attempt 3
...
services:
  appserver:
    type: php:7.1
    overrides:
      services:
        build:
          context: ${PWD}/dev/lando/dockerfiles/appserver
...
```

```dockerfile
# dev/lando/dockerfiles/appserver/Dockerfile
FROM devwithlando/php:7.1-fpm

RUN apt-get -yqq update

##########
# PHP-INTL - OroCommerce Dependencies
# Lando ships with INTL but we need a more recent version
RUN apt-get -yqq install zlib1g-dev libicu-dev g++

RUN curl -sS -o /tmp/icu.tar.gz -L http://download.icu-project.org/files/icu4c/57.1/icu4c-57_1-src.tgz \
    && tar -zxf /tmp/icu.tar.gz -C /tmp \
    && cd /tmp/icu/source \
    && ./configure --prefix=/usr/local \
    && make \
    && make install

RUN docker-php-ext-configure intl --with-icu-dir=/usr/local
RUN docker-php-ext-install intl

##########
# PHP-TIDY - OroCommerce Dependencies
RUN apt-get -yqq install libtidy-dev
RUN docker-php-ext-install tidy
RUN docker-php-ext-enable tidy
```

**Comment by pirog** [comment]
@tylerssn oh interesting. i haven't tried to do this, i dont think our yaml file knows what to do with things like `${PWD}` at least on the host side. This var is going to get resolved INSIDE the container by docker compose so it might not be what you want. 

Have you tried just hardcoding the path since you should be able to do that since its inside the container?

`build: /app/dev/lando/dockerfiles/appserver`

**Comment by tylerssn** [comment]
@pirog, actually, I am using `${PWD}` because relative paths and `${LANDO_MOUNT}` throw errors reporting that the build path does not exist. `${PWD}` does not

**Comment by tylerssn** [comment]
@pirog, @jmdrawneek & @dustinleblanc - the log did not return anything helpful and I did not dig into the Lando codebase to see what might be causing this but it looks like you guys have made impressive progress on this. 

This will go a long way in reducing launch time on `lando restarts` and `lando rebuilds` that have a number of build steps that really only need to run once. Thanks a ton!

**Comment by dustinleblanc** [comment]
I worked on this a bit tonight, it looks like the issue here is that the build context for Docker is within `~/.lando/compose/appname`. This means the path to the Dockerfile is invalid. I can get this to work by passing the absolute path to the Dockerfile on my machine (since this path is a host path).

@pirog I believe that we could make this a supported feature (to provide your own images to build) only if we give a specific path in one's app so that we can shuttle the file off to be built in the proper context.

**Comment by pirog** [comment]
@dustinleblanc let's def talk this in the office hours. I think there are a couple considerations here:

1. The new "passthru" service (which is more or less a "docker compose" service) which might fit the bill here, or also need to be similarly fixed #933 
2. Specifying a "patch" version of something #890 which is a similar override to this

I think we want to:

1. Get the "custom docker file" thing to work eg this issue and possibly also #933 
2. Provide a more robust tutorial around "overriding", or extending the fairly light docs here https://docs.devwithlando.io/config/advanced.html or both

**Comment by pirog** [comment]
@tylerssn following up on @dustinleblanc's work here and some discovery i am doing: i think we want this to "just work". This can definitely be a powerful tool for people who want to extend our php containers with extra php extensions, or extend the official containers we use elsewhere without the mess and rebuilding chaos of our build steps.

**Comment by pirog** [comment]
ok @tylerssn  @dustinleblanc this should be fixed and ive documented it (which links to a working example) over here
https://docs.devwithlando.io/services/php.html#using-a-dockerfile

**Comment by tylerssn** [comment]
Thanks for all the time and effort on this. Love the tool and your teams' responsive nature.

**Comment by pirog** [comment]
@tylerssn thanks for pointing it out! i think this is going to open up a new world of lando customization possibilities.

**Comment by tylerssn** [comment]
@pirog - I totally agree. I was preparing plugins that would provide recipes for frameworks like Magento 2, Symfony and OroCommerce. This will completely change my approach to that.

Also, just to sing a little more praise, I saw that in the documentation it is suggested to run with a `php:custom` image. I applied this to a Laravel recipe setup that we have and it worked like a charm and drastically cut down on restart times.

```yaml
recipe: laravel
config:
  php: '7.1'
  via: nginx
services:
  appserver:
    overrides:
      services:
        # This should relative to your app root
        build: ./.lando/extras/appserver

        # Optionally specify a name and tag for the built image so you can
        # user it elsewhere later
        #
        # NOTE: Docker may throw a warning like:
        #   WARNING: Image for service appserver was built because it did not already exist.
        # This is safe to ignore
        image: monin/api-php:7.1-fpm
```

Alright, I'll let this thread die.
