### ISSUE TITLE
Extremely slow pantheon lando push database

### ISSUE THREAD

**Issue by serhatozkara** [lando/lando#741]
I'm using lando for a while and I am extremely happy with it. But I have a problem with pushing DB to pantheon. While codebase and files are speedy enough DB push takes 10 minutes minimum on a 120MB uncompressed db dump.

Bug Report
==========

*lando v3.0.0-beta.35 on macOS 13.3.3*

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

*Example:*
lando.yml
```
name: roomify
recipe: pantheon
config:
  framework: drupal
  site: roomify-sandbox
  id:
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

```
lando push
```
