### ISSUE TITLE
Developing without an internet connection

### ISSUE THREAD

**Issue by Krilo89** [lando/lando#746]
Bug Report
==========

**Tell us about your setup**

*lando v3.0.0-beta.35 / docker Version 18.02.0-ce-mac53 (22617) on macOS High Sierra 10.13.3*

**Tell us about your `.lando.yml`**
```yml
name: website

# https://docs.devwithlando.io/recipes/drupal8.html
recipe: drupal8

# https://docs.devwithlando.io/config/proxy.html
proxy:
  mailhog:
    - mailhog.website.localhost
  node:
    - node.website.localhost:3000

# https://docs.devwithlando.io/recipes/drupal8.html
config:
  webroot: web

  # Choose whether to use apache or nginx.
  via: nginx

  # If set to true this will force an autostart of xdebug on every request.
  xdebug: false

  # Set specific Drush
  drush: path:/app/vendor/bin/drush
  # Add custom php.ini for development configuration.
  conf:
    php: config/develop/php/php.ini

# We can add additional services here or even override some configuration.
services:
  # By default the recipe's such as drupal8 will already configure and start an appserver.
  appserver:
    overrides:
       services:
         volumes:
           - public_files:/app/web/sites/default/files
           - public_files:/app/files/public
           - private_files:/app/files/private
    # Let's make sure we can use drush aliases from our development environment by making sure on every build that the alias is symlinked to the drush directory in the user folder.
    build:
      - "mkdir -p ~/.drush/alias"
      - "ln -sf /app/drush/alias/aliases.drushrc.php ~/.drush/alias/aliases.drushrc.php"
      - "ln -sf /app/vendor/bin/drush /usr/local/bin/drush"

  # Remove this if your project does not need a REDIS container to implement cachhing for instance.
  # https://docs.devwithlando.io/services/redis.html
  redis:
    type: redis:4.0
    portforward: true

  # This container will catch all mails that your application will try to send. And show them in a slick interface.
  # https://docs.devwithlando.io/services/mailhog.html
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true

  # To allow (frontend) developers to use cool tools based on node, yarn and gulp, we add this container. This could be
  # used to generate css from scss or integrate with browsersync to reload your browser pages when changes are detected.
  # https://docs.devwithlando.io/services/node.html
  node:
    type: node:8.9
    build:
      - "yarn global add gulp-cli@latest yo@latest"

# This will add some tools from the containers to the command line of your OS.
# https://docs.devwithlando.io/config/tooling.html
tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  gulp:
    service: node
  drush:
    cmd:
      - "drush"
      - "--root=/app/web"

events:
  # Run some commands after `lando db-import`. We want the configuration and caches to be up to date.
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cr -y && drush cim -y

  # Make sure composer is up to date with the latest required packages.
  post-start:
    # This will improve composer install speed, from 4 min to 30 seconds at least with a full composer install
    # on a drupal project.
    - appserver: composer global require hirak/prestissimo
    - appserver: cd $LANDO_MOUNT && composer install
# A list of docker compose files to load relative to my app root directory. This follows the docker-compose v3 format,
# and will be merged with the generated docker-compose file from the .lando.yml configuration.
compose:
 - compose.yml
```

```php
[PHP]

;;;;;;;;;;;;;;;
; PHP Globals ;
;;;;;;;;;;;;;;;

short_open_tag = Off
output_buffering = 4096
allow_call_time_pass_reference = Off
variables_order = "GPCS"
request_order = "GP"
register_long_arrays = Off
register_argc_argv = Off
magic_quotes_gpc = Off
enable_dl = Off
allow_url_fopen = On
realpath_cache_size = "800K"
realpath_cache_ttl = "86400"
disable_functions =
;include_path = ".:/usr/share/pear:/usr/share/php"

[Date]
date.timezone = "UTC"

;;;;;;;;;;;;;;;;;;;;;;
;; PACKAGE SETTINGS ;;
;;;;;;;;;;;;;;;;;;;;;;

; Xdebug
; https://xdebug.org/docs/all_settings
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
xdebug.profiler_enable = 0
xdebug.profiler_enable_trigger = 1
xdebug.remote_enable = 1
xdebug.remote_connect_back = 0
xdebug.idekey = PHPSTORM
; This is a loopback address which needs to be active on your host.
xdebug.remote_host = 10.254.254.254
xdebug.remote_autostart = 0
xdebug.remote_cookie_expire_time = -9999

; Globals
expose_php = on
max_execution_time = 300
max_input_time = 900
max_input_vars = 10000
memory_limit = 1024M
upload_max_filesize = 100M
post_max_size = 100M
error_reporting = E_ALL & ~E_DEPRECATED
ignore_repeated_errors = on
html_errors = off
display_errors = on
log_errors = on
error_log = "/app/log/php.log"
```

**Tell us about the command you were running**
Every command beginning with `lando` will fail.

**Tell us about the error you got**
```
warn:  getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at module.exports.__dirname.sendError (/snapshot/cli/node_modules/github/lib/index.js:854:19)
    at /snapshot/cli/node_modules/github/lib/index.js:865:29
    at callCallback (/snapshot/cli/node_modules/github/lib/index.js:728:17)
    at ClientRequest.<anonymous> (/snapshot/cli/node_modules/github/lib/index.js:807:17)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
From previous event:
    at Object.__dirname.setupRoutes.Object.keys.forEach.self.(anonymous function).(anonymous function) [as getReleases] (/snapshot/cli/node_modules/github/lib/index.js:275:40)
    at /snapshot/cli/lib/update.js:0:0
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/cli/lib/update.js:0:0)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/events.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/bootstrap.js:0:0
    at bitmask (/snapshot/cli/node_modules/lodash/lodash.js:10067:25)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3
error:  TypeError: Cannot read property 'version' of undefined
    at /snapshot/cli/lib/update.js:0:0
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/cli/lib/update.js:0:0)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/events.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/bootstrap.js:0:0
    at bitmask (/snapshot/cli/node_modules/lodash/lodash.js:10067:25)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3
```

**Tell us generally about your bug**
When you don't have an Internet Connection, lando will fail your commands. I think it's because Lando wants to check if there are any updates available, but that's not possible without an Internet Connection.

*Example:*

```bash
1. Simply disable your Internet Connection
2. Run `lando` or `lando start`
3. You will get a warn for `getaddrinfo`
4. You will get an error for `TypeError: Cannot read property 'version' of undefined`
```

**Tell us more**
This bug prevents people to Develop locally without an Internet Connection. For example inside a Plain or outside your Country on a vacation.

**Comment by Krilo89** [comment]
Found out that inside the config.yml file there's configuration to send stats about lando: https://github.com/lando/lando/blob/898863360f61d728326d0c80a095944336f20468/config.yml
```yml
stats:
  - report: true
    url: https://metrics.devwithlando.io
```

Solution will be to set report to false. But the question is, how? Can we do this inside the lando.yml file or with env vars?
