### ISSUE TITLE
script example should use the same name for the script

### ISSUE THREAD

**Issue by quietone1** [lando/lando#748]
The documentation for scripts uses different names for the example script. The example begins with a script,  'my-script..sh' but then the excerpt from a .lando.yml uses run-scripts.sh.

> An executable (eg chmod +x) bash script located in scripts/my-script.sh in your app root directory.

```
services:
  appserver:
    scripts:
      - scripts/run-this.sh
```
While either can be changed to make them both the same, for reasons unknown, I prefer my-script.sh. Therefor I suggest changing the line   `- scripts/run-this.sh `to  `- scripts/my-script.sh`
