### ISSUE TITLE
Allow referencing existing tools from tooling and events

### ISSUE THREAD

**Issue by rbayliss** [lando/lando#751]
**Before you submit an issue make sure you have [downloaded](https://github.com/lando/lando/releases) the latest version of Lando and checked to see if the latest version resolves your issue!**

Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.
3.  Fill out either the `BUG REPORT` or `FEATURE REQUEST` below.

Feature Request
===============

Hi there!  As someone who is configuring Lando files, I dislike repeating myself, and wish that I could reference `tooling` that's already define in other tools and event steps.  Eg: I have a `phpunit` tool defined, and I have a `test` event as described in [the docs](https://docs.devwithlando.io/tutorials/setup-additional-tooling.html#multi-service-tooling-with-events).  Currently this looks like this:
```
tooling:
  behat:
    service: appserver
    cmd: cd $LANDO_MOUNT && vendor/bin/behat
  phpunit:
    service: appserver
    cmd: cd $LANDO_MOUNT && vendor/bin/phpunit
  test:
    service: node
    description: "Run all testing steps"
    cmd: true

events:
  post-test:
    - appserver: cd $LANDO_MOUNT && vendor/bin/behat
    - appserver: cd $LANDO_MOUNT && vendor/bin/phpunit
```
I wish it could look more like:
```
tooling:
  phpunit:
    service: appserver
    cmd: cd $LANDO_MOUNT && vendor/bin/phpunit
  behat:
    service: appserver
    cmd: cd $LANDO_MOUNT && vendor/bin/behat
  test:
    service: node
    description: "Run all testing steps"
    cmd: true

events:
  post-test:
    - lando: behat
    - lando: phpunit
```

It would also be super if I could define a tool that references an existing tool.  Eg:
```
tooling:
  gulp:
    service: node
    cmd: node_modules/.bin/gulp
  assets:
    service: lando
    cmd: gulp build
```
I'm imagining that `service: lando` would just route the command back to lando to resolve rather than looking to a container for it, but I'm not tied to that implementation at all.

**Comment by dustinleblanc** [comment]
This is something you can do in composer, yarn/npm, etc, I definitely think the idea of composing commands this way is pretty legit. @rbayliss the way I do this in PHP apps is by wrapping the stuff in Robo: https://github.com/dustinleblanc/cornell_camp_sprint/blob/master/.lando.yml

I can see how doing it at the Lando level would be cool though. I'd actually look to do this via the `@toolingcommand` type of syntax in the way you can do in Composer.

**Comment by hailwood** [comment]
I'm also super keen on this,
I have some events which are simply echo's with an event hook being 3-4 lines of additional commands,

I like the concept of creating one command to trigger a few of them i.e. `lando everything` but unfortunately at the moment I need to copy/paste the 3-4 lines from each of those events into my new everything tool.

As a side note, When questioning whether is was possible on slack I also came up with the exact syntax used here of prefixing the command with `lando: some-command` so it seems fairly logical, although we may also want to investigate adding a `host: ` prefix to run arbitrary commands on the host itself rather than automatically through lando which should run from the directory of the .lando.yml

**Comment by sebinievas** [comment]
Likewise on board with this!

**Comment by RichardDavies** [comment]
The OP also asked about adding the ability to define a tooling command that references another existing tooling command. It looks like @pirog 	suggested that this was possible with something like

```
tooling:
  gulp:
    service: node
    cmd:  gulp
  assets:
    service: lando
    cmd: gulp build
```

However, when I try something similar, I get this error `ERROR: No such service: lando`. Am I missing something or was the implication that this should work a mistake?
