### ISSUE TITLE
Q or FR: Is there any way to merge other yml file into .lando.yml?

### ISSUE THREAD

**Issue by fchris82** [lando/lando#759]
As lando users who work with different environments, we would like to use a little bit different configs but same base.

For example
----------------

In the project's git repository there are two config files:
- `.lando.yml` (project base)
- `.lando.local.yml.dist` (custom user options example file)

```yml
# .lando.yml
name: hte

recipe: lemp

config:
    webroot: web

services:
    database:
        portforward: false

imports:
    - { resource_if_exists: .lando.local.yml }
```

```yml
# .lando.local.yml.dist

# If you want to use fix port in this project, you can set it here
#services:
#   database:
#        portforward: 3360
```

The developers can make a `.lando.local.yml` file (or maybe it's a must) in which it can use its own custom settings in this project. This file is outside the git repository (the `.gitignore` contains this name) The Lando should use deep merge. For example: https://symfony.com/doc/current/service_container/import.html .

---

... or the only one solution is the full own `.lando.yml` in the `.gitignore` with a `.lando.yml.dist` base? It will be good also, but in this case it will be better when the `lando init` command can check the `.lando.yml.dist`'s existing and if it exists, then the Lando just make a copy from this - or ask the developer: `We are detecting a '.lando.yml.dist' file. Do you want to use this or proceed to build your own one with wizard? [Y/n]`
