### ISSUE TITLE
The xdebug config option doesn't work "right"

### ISSUE THREAD

**Issue by fchris82** [lando/lando#760]
We have a complex project which can became very slow when the xdebug is loaded. Currently the developers can switch ON or OFF the `xdebug` in the `docer-compose.yml`:

```yml
# docker-compose.yml
services:
    # [...]
    app:
        # [...]
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
            XDEBUG_ENABLED: 0
```

And we have an `entrypoint.sh` file with this part:

```sh
        if [[ $XDEBUG_ENABLED != 1 ]]; then
            # Disable xdebug
            XDEBUG_INI_BASE=`php --ini | grep -oh ".*xdebug.ini"`
            XDEBUG_INI=$([ -h ${XDEBUG_INI_BASE} ] && readlink ${XDEBUG_INI_BASE} || echo ${XDEBUG_INI_BASE})
            # We add a ';' comment sign to "xdebug.so" --> the xdebug won't load
            sed -i "s/\([^;]*zend_extension=.*xdebug.so\)/;\\1/" $XDEBUG_INI
        else
            # Set remote IP
            HOST_IP=`/sbin/ip route|awk '/default/ { print $3 }'`
            # We have xdebug.ini.dist files for xdebug's config, which won't load when we don't want to use xdebug
            for file in $(egrep -lir --include=xdebug.ini.dist "remote" /usr/local/etc/php); do
                cp $file $(dirname $file)/xdebug.ini
                sed -i "s/\(xdebug.remote_host *= *\).*/\\1${HOST_IP}/" $(dirname $file)/xdebug.ini
            done
        fi
```
As I can see in the `plugins/lando-services/services/php/php.js` file, now if the config `xdebug` value is `false`, the program doesn't set the remote parameters:

```js
    // Add in our xdebug config
    if (config.xdebug) {

      // Conf
      var xconfig = [
        'remote_enable=true',
        'remote_host=' + lando.config.env.LANDO_ENGINE_REMOTE_IP
      ];

      // Add the conf
      php.environment.XDEBUG_CONFIG = xconfig.join(' ');

    }
```

But it won't have an effect on the performance, and I can't switch *off* the xdebug, when I don't want to use it; and switch *on*, when I want it. In this form it is not very helpful. I think an `else` is required to really switch off xdebug.

**Comment by pirog** [comment]
@fchris82 yup, i think i agree with this. we should completely disable/enable the extension vs disabling/enabling the remote settings

**Comment by ataylorme** [comment]
I am trying to run Behat inside of Lando and keep getting this:

```
Background:                                # features/admin-login.feature:6
    Given I am logged in as an administrator # PaulGibbs\WordpressBehatExtension\Context\UserContext::iAmLoggedInAsRole()
      Fatal error: Maximum function nesting level of '256' reached, aborting! (Behat\Testwork\Call\Exception\FatalThrowableError)
```


I’ve only seen `Maximum function nesting level` style errors before when xdebug is on. I do not have `xdebug` defined in my `.lando.yml` and have also tried to explicitly set it to `false` but it seems xdebug is still running.

Tried a restart, rebuild and even deleted my local Docker image to force container images to re-download but no luck.

**Comment by ataylorme** [comment]
It turned out to be the [lh-hsts plugin](https://wordpress.org/plugins/lh-hsts/). I am running Behat tests with a wp-cli driver and the plugin sends the site into a redirect loop as the wp-cli driver tries to authenticate with WordPress.

**Comment by unknownterritory** [comment]
I've found a workaround to completely disable xdebug and ensure it doesn't get loaded:
```
lando ssh appserver --user=root
php --ini
apt-get update && apt-get install nano
nano /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
# comment out the only extension in that file
# exit and save
# logout from your ssh connection into appserver
lando restart
```
An easier way to accomplish this is using a build step in your lando recipe:
```
  appserver:
    type: php:7.1
    config:
      conf: config/php/php.ini
    # xdebug: true
    install_dependencies_as_root:
      - "mkdir /usr/local/etc/php/conf.d/disabled_extensions && mv -vf /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/disabled_extensions/docker-php-ext-xdebug.ini"
```
To apply the changes, you need to run `lando rebuild`.
When you need xdebug again, you invert the `mv` instruction and un-comment the xdebug setting:
```
  appserver:
    type: php:7.1
    config:
      conf: config/php/php.ini
    xdebug: true
    install_dependencies_as_root:
      - "mv -vf /usr/local/etc/php/conf.d/disabled_extensions/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini "
```
To avoid rebuilding your app, I guess you can also log into appserver as root `lando ssh appserver --user=root` and run... 
```
mkdir /usr/local/etc/php/conf.d/disabled_extensions && mv -vf /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/disabled_extensions/docker-php-ext-xdebug.ini
```
... and the run `lando restart`.

The gains in performance, so far, seem really worth it. I hope this may help.
