### ISSUE TITLE
Drupal multisite database import

### ISSUE THREAD

**Issue by diacu** [lando/lando#790]
Feature Request
===============

Using Lando with Drupal in multisite mode is not an easy to configure task. It would be helpful if there could be a way to configure multiple databases (either with same user or each with it's user)

Right now, you have to manually create database using `lando mysql`, set the correct permissions for mysql user and then import database.

**Comment by pirog** [comment]
@diacu you would want to add additional db services to your `.lando.yml` file to get these extra databases.  Something like

```yml
name: mysql
recipe: drupalWHATEVER
services:
  database2:
    type: mysql
    creds:
      user: db2
      password: db2
      database: db2
  database3:
    type: mysql
    creds:
      user: db3
      password: db3
      database: db3
...
```

**Comment by pirog** [comment]
Because doing the above is more or less the same end result of the feature request im closing this.

**Comment by diacu** [comment]
But each database service is a docker container, right? If so, is quite resource consuming to have one full mysql instance for each database.

**Comment by pirog** [comment]
@diacu its not particularly resource intensive unless you have lots and lots of database containers (eg hundreds). if you want to add more databases to a single container i'd recommend scripting that out in a lando event or build step.

**Comment by Mar2zz** [comment]
# DATABASE
```
  database:
    run_as_root:
      # Create extra databases.
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS db; GRANT ALL PRIVILEGES ON db.* TO 'drupal8'@'%' IDENTIFIED by 'drupal8';"
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS cb; GRANT ALL PRIVILEGES ON cb.* TO 'drupal8'@'%' IDENTIFIED by 'drupal8';"
```

**Comment by StanBarrows** [comment]
Hey @Mar2zz , 

I've tried your solution but this is somehow not working. Any idea?

```
name: www-application
recipe: laravel
config:
  php: 7.4
  via: nginx
  webroot: public
  xdebug: false

services:
  appserver:
    build_as_root:
      - apt update -y && apt install nano
      - apt update -y && apt install sudo nano

  myservice:
    build_as_root:

  database:
    type: mysql:8.0
    run_as_root:
      # Create extra databases.
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS testing; GRANT ALL PRIVILEGES ON testing.* TO 'laravel'@'%' IDENTIFIED by 'laravel';"
    portforward: 33060

```

TablePlus still shows one Database

![image](https://user-images.githubusercontent.com/10268813/99059111-65540e00-259e-11eb-9f97-39bf96619048.png)
