### ISSUE TITLE
How to setup multiple datases in one mysql service

### ISSUE THREAD

**Issue by andreasbergqvist** [lando/lando#792]
I have a Drupal site with multiple databases that I would like to migrate to use lando as a development environment.

I can only, in the configs, see:
creds:
      user: drupal7
      password: drupal7
      database: drupal7

What if I would like to have more databases then the drupal7 one?

I tried just to import a database (named new-database-name) with drush but if fails with:
Access denied for user 'drupal7'@'%' to database 'new-database-name'.

Is it possible to add multiple databases (with same user/password) by just editing the config?

**Comment by elin-y** [comment]
@pirog I really need to create a second database on the same service, since on the project there are some queries with `JOIN` clauses between two databases

**Comment by pirog** [comment]
We plan to support this at some point but in the meantime you can use a
build step to spin up a separate DB within the same service

**Comment by elin-y** [comment]
Thank you for the quick response. I'll try your suggestion creating a db in a build step.

**Comment by miloskroulik** [comment]
@elin-y You can create a second DB in the same database service manually:

```
  database:
    type: mysql
    run_as_root:
      # Create extra databases.
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS dbname; GRANT ALL PRIVILEGES ON dbname.* TO 'drupal8'@'%' IDENTIFIED by 'drupal8';"
```
But don't expect lando mysql import/export commands to be working for this extra database.
