### ISSUE TITLE
Drush 

### ISSUE THREAD

**Issue by RoloDMonkey** [lando/lando#793]
I am running the latest version.

I have reviewed the issue queue, and I have not found a solution to my problem.

Bug Report
==========

**Tell us about your setup**

v3.0.0-beta.35 on Mac OS High Sierra

**Tell us about your `.lando.yml`**

```yml
name: hias
recipe: pantheon
config:
  framework: drupal
  site: [client name]
  id: [id]
```

**Tell us about the error you got**

Rerun the command that produced your error in `verbose` mode. Paste in the error and the ~100 lines that proceeded it.

```bash
lando drush -vvvv
/bin/sh: 1: drush: not found
```

**Tell us generally about your bug**

This morning, my lando.yml file included a service for a second DB server.  I realized that wasn't necessary and removed those lines.  When I did a `lando rebuild`, two things happened:

- I noticed that the DB service wasn't removed
- I started getting the Drush error

I have tried `lando destroy` several times.  Is that supposed to remove the app from `lando list`? Because, it didn't.

I have managed to re-initialize the site with a Pantheon recipe.  Another strange thing that happened was that I had to re-authorize the app with my Pantheon machine token.  I haven't had to do that before.

Does this bug prevent you from using lando?

Yes, I cannot do `drush uli` to get into my local Drupal site.

**Comment by pirog** [comment]
@RoloDMonkey paste in the relevant parts of your `pantheon.yml` file so we know what version of php and drush you are trying to use

**Comment by RoloDMonkey** [comment]
I don't have a `pantheon.yml` file.  Do you mean `pantheon.upstream.yml`?

```yml
# IMPORTANT NOTE:
# Do not edit this file unless you are doing so in your custom upstream repository.
# Override the defaults specified here in a site-specific `pantheon.yml` file.
# For more information see: https://pantheon.io/docs/pantheon-upstream-yml
api_version: 1
php_version: 5.6
```
