### ISSUE TITLE
Getting PatternLab based Drupal themes to work with lando

### ISSUE THREAD

**Issue by brooke-heaton** [lando/lando#799]
**Setup**
Using Lando v3.0.0-beta.35 on macOS High Sierra 10.13.3
Drupal 8.5 
[Bootstrap child theme](https://www.drupal.org/project/bootstrap) using [PatternLab](patternlab.io) and Drupal [component libraries module](https://www.drupal.org/project/components)

**.lando.yml**
```
name: naswa
recipe: drupal8
config:
  webroot: docroot
  php: 7.1
  database: mysql:5.7
  conf:
    php: lando/php/php.ini
proxy:
  appserver:
    - naswa.lndo.site
    - naswa_main.lndo.site
tooling:
  blt:
    service: appserver
    cmd: /usr/bin/blt
  'sql-sync-all <environment>':
    service: appserver
    description: Synchronize SQL on all sites, from a specific environment (prod, test, dev, proto)
    cmd: /app/lando/tooling/sql-sync-all.sh
services:
  naswa_main:
    type: mysql:5.7
    portforward: true
    config:
      confd: lando/mysql/conf.d
  integrity:
    type: mysql:5.7
    portforward: true
    config:
      confd: lando/mysql/conf.d
  appserver:
    scripts:
      - scripts/add-blt.sh
```
 **Issue**
I was able to resolve the issue - ultimately the issue was more to do with how the Component Libraries module was mapping my templates -the templates in my theme are no longer necessary and the templates in PatternLab should be used. There may be more issues related to PatternLab - specifically gulp watch issues. I'll leave this ticket open for now.
