### ISSUE TITLE
Extension not loaded

### ISSUE THREAD

**Issue by gaedelprete** [lando/lando#806]
Bug Report
==========

I have the following `.lando.yml`

```yml
name: myapp
recipe: lamp
proxy:
  appserver:
    - dev.myapp.com
config:
    php: '5.6'
    webroot: public
    xdebug: true
services:
  appserver:
    run:
      - "cd $LANDO_MOUNT && composer install"
    run_as_root:
      - docker-php-ext-install pcntl
      - pecl channel-update pecl.php.net
      - pecl install mongo mongodb
      - docker-php-ext-enable mongo mongodb
```
After build if i look from browser my index.php (with `phpinfo()`) i can't see the installed extension.

After a ``lando restart`` extension are correctly loaded.
