### ISSUE TITLE
Elasticsearch requires increasing mmap counts

### ISSUE THREAD

**Issue by tormi** [lando/lando#817]
As per @serundeputy's request on Slack:

[elasticsearch](https://github.com/lando/lando/blob/master/docs/services/elasticsearch.md) recipe requires `vm.max_map_count` > current default (65530) to run properly. 

Steps to reproduce on Ubuntu 16.04.4 LTS and Lando v3.0.0-beta.37-10-g8f12:

```
lando start
...
warn: Service search is unhealthy
warn: Run "lando logs -s search"

lando logs -s search
Attaching to elasticsearch_search_1
search_1         | Running command /start
search_1         | 
search_1         | ERROR: As of 5.0.0 Elasticsearch requires increasing mmap counts.
search_1         | Refer to https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
search_1         | 

```
See https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html of how to increase the limit of `vm.max_map_count`.

**Comment by dustinleblanc** [comment]
Actually kind of surprised the docker images don't already do this, their docs seem to kind of indicate meh, its done.

**Comment by dustinleblanc** [comment]
That said, we should define a `/etc/sysctl.conf` that sets this and do it only on linux hosts as a fix?

**Comment by tormi** [comment]
Some inspiration: https://github.com/appcelerator/amp/commit/6fa7b8dba690387c38adadfc164efe9502a23050

**Comment by serundeputy** [comment]
@tormi can I see a paste of your `.lando.yml` file?

I used the ES example from `lando/examples/elasticsearch` with this `.lando.yml` file:

```yml
# elasticsearch example
name: elasticsearch

#
# You need to run `lando npm install` before you run `lando start` for this
# example to work
#

# Give me http://elasticsearch.lndo.site
proxy:
  appserver:
    - elasticsearch.lndo.site

# Spin up a basic nodes server with elasticsearch backend
services:

  # Spin up a memcache container called "search"
  # NOTE: "search" is arbitrary, you could just as well call this "theboss" or "eljefe"
  search:

    # Use version 5.4 of elasticsearch
    type: elasticsearch:5.4

    # Optionally allow access to the cache at localhost:9999
    # You will need to make sure port 9999 is open on your machine
    #
    # You can also set `portforward: true` to have Lando dynamically assign
    # a port. Unlike specifying an actual port setting this to true will give you
    # a different port every time you restart your app
    portforward: 9999

    # Optionally load in a custom config file. This is relative to the app root.
    #
    # config: customElasticsearch.yml

    # There are various envvars you can specify to further customize how
    # elasticsearch works.
    #
    # See: https://hub.docker.com/r/itzg/elasticsearch/
    #
    # overrides:
      # services:
        # environment:
          # ES_JAVA_OPTS: -Xms16g -Xmx16g
          # PLUGINS: elasticsearch/marvel/latest

  # Spin up services to run a basic node server
  appserver:
    type: node:6.10
    command: npm start

# Add some nice command routing
tooling:
  yarn:
    service: appserver_cli
  npm:
    service: appserver_cli
  node:
    service: appserver_cli
```

and then checking the value of `vm.max_map_count`:

```bash
geoff@yep es exit code: [0] $ lando.dev ssh search -u root -c 'sysctl vm.max_map_count'
vm.max_map_count = 262144
```

Are you using a different version of elasticsearch?
