### ISSUE TITLE
Node.js: complete the build step before "starting" the container

### ISSUE THREAD

**Issue by vincenzo** [lando/lando#822]
Hi @pirog @dustinleblanc 

Sorry, do not have the time right now to write this properly, and I am not sure this is a bug or a feature request. But if you remember all the trouble I talked about yesterday on Slack, it's because of something I was supposed to know already, but that I still feel it should not be the way it is.

Essentially, I have

```yaml
name: zoo

proxy:
  panda:
    - panda.lndo.site

services:
  panda:
    type: node:8.9
    build:
      - "cd /app/panda && npm install"
    command: "cd /app/panda && npm run dev"
    overrides:
      services:
          PORT: 80
```

If there is no `node_modules` locally to the app and one runs `lando start` without runninng `lando npm install` (or even just `npm install` from your host machine) first, the container will fail to boot. I understand from this that the `build` step is not a blocking step which must finish before anything else (even the `command`) happens. 

That is why in your docs you instruct to have `npm` tooling associated with the helper container `_cli` and run `lando npm install` before running `lando start`. 

There are two reasons why I am here again saying that I'd rather have the `build` step complete before actually booting up: 

1. That's the intuitive way I expect it to work. 
2. For reasons I won't explain here, I need the tooling to run against the main container, and not the `_cli`

From past discussions, I kind of understand the reasons why it is as it is a the moment. My idea is this: regardless of what the tooling is tied to, when one runs `lando start` on a `node` container that has a `build` step you could execute that build step on the associated `_cli` container, complete that, and then execute the actually `lando start` process. All hidden away from the user that runs `lando start`. In fact, if this worked, the `_cli` container will never be required except from when `start` (or `restart`) is invoked, thus you could even shut down the `_cli` container once the main one is up and running.

Thoughts?
