### ISSUE TITLE
Add pre and post lando build scripts to run on the host machine

### ISSUE THREAD

**Issue by nathandentzau** [lando/lando#847]
Feature Request
===============

The ability to define in `.lando.yml` scripts to be triggered before and after lando has built a project's containers to be run on the host machine. [A similar feature exists with DrupalVM][] that allows for scripts to be triggered outside of Vagrant at the beginning and end of Ansible provisioning.

**Example:**
A user creates a new project using lando or clones an existing project using lando. They start lando and these scripts will be triggered. Also when rebuilding a lando project these scripts would run as well. There is a `scripts` directive in the root of the `.lando.yml` file that defines a list of scripts to run:

```yaml
name: my-site

recipe: drupal8

config:
  webroot: web
  php: '7.2'

# Scripts to be run on the host machine before and after lando builds.
scripts:
  pre: 
    - ./scripts/create-files-directory.sh
  post: 
    - ./scripts/generate-settings-local.sh
```

In my case, I'd like like to generate the project's `settings.local.php` with the same Ansible task we use to deploy to our production site and lower environments. We currently use DrupalVM and use that same task to generate a settings.local.php file for our local environments.

I'm new to Lando, so if there's a _better_ way to handle something like this, I'm all ears. Thank you for your time in advanced. 😃 

[A similar feature exists with DrupalVM]: http://docs.drupalvm.com/en/latest/extending/scripts/
