### ISSUE TITLE
Getting two lando environments to 'talk' to each other

### ISSUE THREAD

**Issue by Kwapi** [lando/lando#857]
**Tell us about your setup**

Lando - v3.0.0-beta.35
macOS El Capitan (0.11.6 )

I'm trying to get send a POST request between two lando containers but I can't get it to work. If I'm correct I need to add the container info to the internal hosts file. I found the `extra_hosts` option in the [docker docs](https://docs.docker.com/compose/compose-file/#extra_hosts) but it seems that I need to get docker IPs. Running `docker ps --all | grep lando` gives me IPs that look like this: `0.0.0.0:32770`. I tried adding them to my `.lando.yml` like this:

```
config:
  webroot: .
  xdebug: true
  php: '7.0'

services:
 appserver:
   overrides:
     services:
       extra_hosts:
         - "http://eportfolio.test: 0.0.0.0:32770"
```

but I'm getting this error:
```
ERROR: for appserver  Cannot create container for service appserver: invalid IP address in add-host: "//eportfolio.test: 0.0.0.0:32770"
```

Has anyone else encountered that?
