### ISSUE TITLE
Drush Debugging

### ISSUE THREAD

**Issue by jleaders** [lando/lando#874]
Documentation Request
===============

Kind sir, might I gently request a tutorial for xdebug for CLI php commands? As a lando user who works with Drupal sites that have custom drush CLI PHP commands, I'd like a tutorial on how to put breakpoints in them, via XDebug.

Please write documentation on debugging drush CLI commands to [The Drupal Docs]( https://docs.devwithlando.io/tutorials/drupal8.html). I use PHPStorm but any IDE should work once configured.

**Comment by richardbporter** [comment]
This would be nice. I haven't had any luck.

**Comment by dustinleblanc** [comment]
Is there an existing example of documentation on doing this _without_ Lando? I am close to saying this is out of scope unless there is a Lando specific need here.

**Comment by richardbporter** [comment]
Yea, I agree with that. There are quite a few examples out there, for example: https://confluence.jetbrains.com/display/PhpStorm/Debugging+PHP+CLI+scripts+with+PhpStorm. It also depends on your IDE/editor.

**Comment by Etroid** [comment]
I was able to get this to work with Lando + PHPstorm adding the following override to my appserver:
```
appserver:
    # Enable Xdebug.
    xdebug: true
    overrides:
      services:
        environment:
          # Support Drush with XDEBUG
          PHP_IDE_CONFIG: "serverName=appserver"
```

**Comment by zuernBernhard** [comment]
Here we have a Drupal 8 Project where the Drupal-8 installation lives in /web (installed with drupal-composer-template). We also had to do the following steps:

add a .env-File to the Project-Root (above /web) with the following content:

`DRUSH_ALLOW_XDEBUG=1
PHP_IDE_CONFIG="serverName=foobar.lndo.site"` 

(replace foobar according to your project needs)

In the phpStorm project preferences -> language & frameworks -> PHP : We added ~/.lando/services/config/drupal8 to the include path

Then we have a runtime configuration on phpStorm for foobar.lando.site where the path mapping for /app/web had to be removed and we added a mapping from /app on the server to our project root-filedirectory.

We also added a pathmapping from /srv/includes on the server to ~/.lando/services/config/drupal8

Now we can debug Browser-Requests to the Drupal8-Instance AND drush commands in phpstorm.

btw I use drush launcher on my local system (mac os)

**Comment by zuernBernhard** [comment]
If this also works for you it perhaps makes sense to add it to the docs with extra screenshots and so on

**Comment by zuernBernhard** [comment]
drush is installed in the project via composer thats why `vendor/bin/drush` is used instead of `/usr/local/bin/drush`.

To fix this for debugging drush commands add the following "tooling" in .lando.yml:

```
tooling:
    drush:
        service: appserver
        cmd:
        - "/app/vendor/bin/drush"
```

**Comment by q0rban** [comment]
This is what worked for me:

```
config:
  ...
  drush: path:/app/vendor/bin/drush
services:
  appserver:
    xdebug: true
    overrides:
      services:
        environment:
          # Support debugging Drush with XDEBUG. Use lando drush to debug.
          PHP_IDE_CONFIG: "serverName=appserver"
```

Then turning on "Listen for PHP Debug Connections" in PHPStorm and calling `lando drush my-command` would start debugging in PHPStorm.

**Comment by ElijahLynn** [comment]
Thanks @q0rban and @Etroid. I also had to go to Settings > Languages & Frameworks > PHP > Servers and change the server name to "appserver", otherwise it would semi-break, but tell me it couldn't find the server "appserver" and that it didn't have an entry point.

**Comment by ralkeon** [comment]
> This is what worked for me:
> 
> ```
> config:
>   ...
>   drush: path:/app/vendor/bin/drush
> services:
>   appserver:
>     xdebug: true
>     overrides:
>       services:
>         environment:
>           # Support debugging Drush with XDEBUG. Use lando drush to debug.
>           PHP_IDE_CONFIG: "serverName=appserver"
> ```
> Then turning on "Listen for PHP Debug Connections" in PHPStorm and calling `lando drush my-command` would start debugging in PHPStorm.



> Thanks @q0rban and @Etroid. I also had to go to Settings > Languages & Frameworks > PHP > Servers and change the server name to "appserver", otherwise it would semi-break, but tell me it couldn't find the server "appserver" and that it didn't have an entry point.

Those two are the way for me, thanks guys!!! :tada: :tada: :tada:

**Comment by ElijahLynn** [comment]
Nice @ralkeon, also worth noting is that you can do it the other way and take the server name that is autogenerated in PHPStorm and use that as the `PHP_IDE_CONFIG` value.

**Comment by q0rban** [comment]
> @pirog closed this 8 hours ago

Could you give a quick update on why this is now closed? I assume this is closed because the documentation for this is now present somewhere on https://docs.devwithlando.io, but I couldn't find it, and being that this issue is still the number one search result for `lando xdebug drush` on Google, it would be helpful to document in here where the canonical location of the documentation lives now. Thanks, Mike!

**Comment by ElijahLynn** [comment]
Also, if you want phpunit tests working with `lando phpunit...` then make sure to path map 'tests' to /app/tests.

**Comment by Etroid** [comment]
Since `v3.0.0-rc` the syntax is as follows:

```
services:
  appserver:
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
```
