### ISSUE TITLE
WP CLI - DB export and alias

### ISSUE THREAD

**Issue by Rahe** [lando/lando#877]
Hello everyone,

here is my issue.

Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? 
Last version of Lando from releases.
MacOS Sierra

**Tell us about your `.lando.yml`**
```yml
name: project
recipe: wordpress
config:
  webroot: .
  database: mariadb
  php: '7.1'
  xdebug: true
proxy:
  appserver:
  httpcache:
    - project.localhost
services:
  # Redis Cache
  object-cache:
    type: redis:4.0
    portforward: 6380
    persist: true
  #Varnish
  httpcache:
    type: varnish
    # based on the appserver, given by the WordPress recipe
    backends: appserver
    #vcl: conf/varnish/wordpress.vcl
    ssl: true
tooling:
  # Drop the user into a redis shell
  redis-cli:
    service: object-cache
  varnishadm:
    service: httpcache
    user: root
  varnishstat:
    service: httpcache
    user: root
  varnishlog:
    service: httpcache
    user: root
  get-dev:
    service: appserver
    cmd: "wp @dev db export - > sql-dump-dev.sql"
    description: "Import the development environment Database"
events:
  # Runs composer install and a custom php script after your app starts
  post-start:
    - appserver: cd $LANDO_MOUNT && composer install --prefer-dist
  post-db-import:
    - appserver: cd $LANDO_MOUNT && wp search-replace distant.fr project.localhost --precise -all-tables && wp cache flush
  post-get-dev:
    - appserver: cd $LANDO_MOUNT && db-import sql-dump-dev.sql
```

**Tell us about the command you were running**
```bash
lando get-dev
```

**Tell us about the error you got**
 ```bash
Error: Too many positional arguments: > sql-dump-dev.sql
```

Or 
```bash
Error: '@dev' is not a registered wp command. See 'wp help' for available commands.
```

Like the wp-cli.yml isn't loaded

**Tell us generally about your bug**

I Tried to run the command lando get-dev for getting the distant databse on local and import it with lando db-import.

If I launch the command directly from bash on my computer, local wp-cli : 
```bash
wp @dev db export - > sql-dump-dev.sql
```

But if I launch
```bash
lando wp cli info
OS:	Linux 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64
Shell:	
PHP binary:	/usr/local/bin/php
PHP version:	7.1.15
php.ini used:	
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/app
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	/app/wp-cli.yml
WP-CLI version:	1.5.0
```
The wp-cli.yml seems to be loaded.

So do I miss something for the tooling part ?
Aliases seems to be handled by the Pantheon recipe and Drush.

Is it due to the https://github.com/lando/lando/blob/master/plugins/lando-recipes/recipes/wordpress/wordpress.js#L65 --allow-root already added at the end of the command ?

If I remove the `-` part then the exported stream is shown but impossible , doing
```bash
lando get-dev > file.sql
```
Is working but this is not my goal here ^^
