### ISSUE TITLE
Top level domain .local should not  be used (on macOS)

### ISSUE THREAD

**Issue by osopolar** [lando/lando#880]
## Bug Report

I want to be able to work offline and run lando with the proxyDomain `local`, although I followed the [instructions for *developing offline*](https://docs.devwithlando.io/tutorials/offline-dev.html) I can't get it work.

* lando version: v3.0.0-beta.39 (installed via homebrew)
* macOS: 10.12.6
* `.lando.yml`:
```yml
name: myapp
recipe: drupal7
config:
  php: '5.6'
  via: apache
  webroot: .
  drush: global:^8.1
  database: mysql:5.6
  xdebug: true
proxy:
  mailhog:
    - mail.myapp.local
  solr:
    - solr.myapp.local:8983
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: 1026
  solr:
    type: solr:7.1
    portforward: 9999
    core: freedom
    config:
      conf: sites/all/etc/solr-conf/7.x
```

* I followed the [mac specific instructions for *developing offline*](https://docs.devwithlando.io/tutorials/offline-dev.html), but changed localhost to local, see below:

> ### Mac Specific Instructions
> 1. Ensure you've installed [Homebrew](https://brew.sh/). **✓**
> 2. Install DNSMasq: `brew install dnsmasq` **✓**
> 3. Follow the instructions in the output of `brew info dnsmasq` **✓**
> 4. Add the following line to your `/usr/local/etc/dnsmasq.conf` file: **✓**
> ```
> address=/local/127.0.0.1
> ```
> Sub in your favorite TLD for 'localhost' here if you want to use something more flashy.
> 5. Restart DNSMasq: `brew services restart dnsmasq` **✓**
> 6. For OS X to resolve requests from *.localhost to localhost we need to add a resolver: **✓**
> ```
> sudo mkdir -p /etc/resolver
> sudo nano /etc/resolver/local
> ```
> 7. Add the following line to the local file resolver in /etc/resolver/.
> ```
> nameserver 127.0.0.1
> ```
>   * I was not sure of the file needs to be named `local` or `localhost`, I created both with same content **✓**
> 8. Reboot OS X to enable the new resolver. **✓**
> 9. Flush your DNS, just to be sure that your browsers use the new dns **✓**
> directives.
> ```
> sudo dscacheutil -flushcache
> sudo killall -HUP mDNSResponder
> ```
> 10. Open your `~/.lando/config.yml` file and add the following line: **✓**
> ```yaml
> proxyDomain: local
> ```
> Again, allow your creativity to flourish and use whatever TLD makes you smile.
> 11. Power Lando down with `lando poweroff` **✓**
> 12. Start up your favorite Lando app to test it out with `lando start` from within your app's root directory. **✓**

```
lando start
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... done
Starting myapp_appserver_1 ... done
Starting myapp_mailhog_1   ... done
Starting myapp_solr_1      ... done
Starting myapp_database_1  ... done
Waiting until database service is ready...
Waiting until appserver service is ready...
Waiting until solr service is ready...
Waiting until mailhog service is ready...
Changed current directory to /var/www/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME            myapp
 LOCATION        /Users/Dev/Projects/myapp.de/myapp.de
 SERVICES        appserver, database, mailhog, solr
 APPSERVER URLS  https://localhost:32791      [green]
                 http://localhost:32792       [green]
                 http://myapp.local           [red]
                 https://myapp.local          [red]
 MAILHOG URLS    http://localhost:32787       [green]
                 http://mail.myapp.local      [red]
                 https://mail.myapp.local     [red]
 SOLR URLS       http://solr.myapp.local      [red]
                 https://solr.myapp.local     [red]
```

* It was working before with lndo.stie proxy, but I changed to local but now the .local sites aren't available. What did I miss?
