### ISSUE TITLE
Unable to start more than one app with beta.40

### ISSUE THREAD

**Issue by vincenzo** [lando/lando#881]
# Bug Report

## Set-up
Lando: `v3.0.0-beta.40`
Docker: `18.03.0-ce-mac60 (23751)`
OS: Mac OS High Sierra (with latest updates on)

## Issue

Beta 40 introduces an issue whereby it is impossible to `lando start` more than one Lando App at once; the moment one `lando start` the second one, all the containers related to the first app already running are shut down before the containers of the second app are fired up. 

I even tried to `lando start` them one right after the other (i.e. without waiting for the first one to be up and running). What happened was that the second one took over, killed the containers of the first one (which never started properly), then launched ok. 

When running a second `lando start` whilst there's an Lando app already started (or starting), one can definitely tell Lando is busy doing something else before actually starting the second app; and that something else is shutting down the containers of the other app (I wonder whether it's just shutting down all containers he finds? -- I haven't tried this scenario, since I only run Docker containers via Lando). You do not see that "pause" in a second `lando start` with `beta.39`.

I've tried this multiple times: 

- without destroying the apps
- destroying the apps first
- factory-resetting Docker
- etc. 

Always the same result. 

The only thing I have not tried was to nuke the `~/.lando` dir. I can do that, too, if you think it could be a valuable test. 

## Two of my apps

First one:

```yml
name: panda

proxy:
  panda:
    - panda.lndo.site

services:
  db:
    type: mongo:3.0
    portforward: 27017

  panda:
    type: node:8.9
    command: yarn --cwd=/app/ run dev
    overrides:
      services:
        environment:
          PORT: 80

tooling:
  yarn:
    service: panda_cli
    cmd: yarn --cwd=/app/
    description: Run yarn commands inside Panda
  mongo:
    service: db
    description: Launch mongo shell for Panda
  mongoimport:
    service: db
    description: Launch mongoimport tool for Panda
  mongoexport:
    service: db
    description: Launch mongoexport tool for Panda
```

Second one: 

```yml
name: rhino

proxy:
  rhino:
    - rhino.lndo.site:4000
    - '*.rhino.lndo.site:4000'

services:
  # Rhino Admin UI
  rhino:
    type: node:8.9
    command: runuser www-data -c 'yarn --cwd=/app run dev'
    overrides:
      services:
        environment:
          PORT: 4000

tooling:
  yarn:
    service: rhino_cli
    cmd: yarn --cwd=/app/
    description: Run yarn commands inside Rhino
  reload:
    service: rhino
    cmd: /app/node_modules/pm2/bin/pm2 restart all
  status:
    service: rhino
    cmd: /app/node_modules/pm2/bin/pm2 show yarn
```

## Does this bug prevent you from using lando?

Yes.
