### ISSUE TITLE
Overriding the image used for Python fails expecting www-data user

### ISSUE THREAD

**Issue by aleksijohansson** [lando/lando#883]
Overriding the image used for Python with an Alpine based image doesn't work because Lando expects `www-data` user. This forces the usage of the default Python image which is based on Debian Jessie and is huge compared to the Alpine based one:

```bash
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
python              3.6-jessie          336d482502ab        9 days ago          692MB
python              3.6-alpine3.7       4b00a94b6f26        6 weeks ago         83.4MB
```

Operating system: v3.0.0-beta.39 on macOS High Sierra 10.13.4.
Also tested on: v3.0.0-beta.39 on Windows 10 Version 1709

`.lando.yml`:

```yml
name: python
services:
  appserver:
    type: python:3.6
    overrides:
      services:
        image: python:3.6-alpine3.7
tooling:
  python:
    service: appserver
```

Commands:

```bash
lando start
lando python
```

Error:

```
unable to find user www-data: no matching entries in passwd file
```
