### ISSUE TITLE
Why is "php_value xdebug.remote_autostart 1" set in services/config/php/httpd-ssl.conf?

### ISSUE THREAD

**Issue by osopolar** [lando/lando#886]
* lando version: v3.0.0-beta.39 (installed via homebrew)
* macOS: 10.12.6
* `.lando.yml`:
```yml
name: myapp
recipe: drupal7
config:
  php: '5.6'
  via: apache
  webroot: .
  drush: global:^8.1
  database: mysql:5.6
  xdebug: false
  conf:
    php: sites/all/etc/lando/dev.php.ini
proxy:
  mailhog:
    - mail.myapp.local
  solr:
    - solr.myapp.local:8983
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: 1026
  solr:
    type: solr:7.1
    portforward: 9999
    core: freedom
    config:
      conf: sites/all/etc/solr-conf/7.x
```
My xdeug settings in sites/all/etc/lando/dev.php.ini look like:

```
;...
; Xdebug
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
xdebug.remote_autostart = 0
xdebug.profiler_enable_trigger = 0
xdebug.remote_enable = 1
xdebug.remote_host = ${LANDO_HOST_IP}
```

I want to disable xdebug.remote_autostart, but it didn't work. I found that in [services/config/php/httpd-ssl.conf](https://github.com/lando/lando/blob/898863360f61d728326d0c80a095944336f20468/plugins/lando-services/services/php/httpd-ssl.conf) xdebug.remote_autostart was set to 1. Is that necessary as it could be easily set by php.ini? That way I guess also the setting "xdebug: false" in .lando.yml will be bypassed, won't it?

**Comment by osopolar** [comment]
Adding a custom httpd-ssl.conf (copy of the original [httpd-ssl.conf](https://github.com/lando/lando/blob/898863360f61d728326d0c80a095944336f20468/plugins/lando-services/services/php/httpd-ssl.conf) but without `php_value xdebug.remote_autostart 1`) to .lando.yml (see below) solves the issue. But maybe it isn't necessary in first place.

```yml
config:
  conf:
    server: sites/all/etc/lando/dev.httpd-ssl.conf
```
