### ISSUE TITLE
Lando Start Doesn't Work Anymore

### ISSUE THREAD

**Issue by digisavvy** [lando/lando#893]
Bug Report
==========

I'm running Mac OSx, High Sierra, 10.13.14.
Lando v. 3.0.0 beta 40

**`.lando.yml` config**

```
name: nfac
recipe: pantheon
config:
  framework: wordpress
  site: nfac
  id: 553d5fc8-ea12-4dd0-8554-4eb95439f06c
```
**Tell us about the command you were running**
I started up a new site using `lando init pantheon`. I chose my pantheon site and the commands seemed to work okay. 

I then ran `lando start` and received the following error
```
error: (HTTP code 500) server error - container bfb54dc29d1f59df4981041aaf95725dc9328f619dbe167657fd51ede1f8a311 is not connected to the network lando_bridge_network 
```
If I try to visit the site I see this ([screenshot](https://digisavvycdn.s3.amazonaws.com/nfac.site_2018-04-11_16-42-09.png))

**Tell us more**
I was having problems with the site before upgrading to beta 40, but the beta gave me the above error, which I wasn't getting previously.  

It seems like this is happening to all sites now, not just new sites.
