### ISSUE TITLE
Name cannot use dashes

### ISSUE THREAD

**Issue by jarvisjohnson** [lando/lando#896]
Bug Report
==========

Version: v3.0.0-beta.40
OS: OSX 10.13.3
Node: v9.11.1

`.lando.yml`:
```yml
name: in-the-mesh
recipe: pantheon
config:
  framework: wordpress
  env: dev
  site: in-the-mesh
  id: 123456789
```

`lando rebuild` strips the dashes out of the name:

```
Your app has started up correctly.
Here are some vitals:

 NAME           inthemesh
 LOCATION       /Users/blah/sites/in-the-mesh
 SERVICES       appserver, nginx, database, cache, edge_ssl, edge, index
 NGINX URLS     https://localhost:32807
                http://localhost:32808
 EDGE URLS      http://localhost:32809
                http://inthemesh.lndo.site
                https://inthemesh.lndo.site
 EDGE_SSL URLS  https://localhost:32810
```
