### ISSUE TITLE
Question: is it possible to create NFS volumes with lando?

### ISSUE THREAD

**Issue by mmenozzi** [lando/lando#901]
Hi guys,
I would like to create NFS volumes like explained here: https://medium.com/@sean.handley/how-to-set-up-docker-for-mac-with-native-nfs-145151458adc

Is it possible with lando? I cannot find in the docs how to specify advanced volumes configuration with the `.lando.yml`.

**Comment by mmenozzi** [comment]
I think I found a solution for this. My `.lando.yml` looks like this:

```yml
name: myapp
recipe: lamp
config:
  webroot: .

services:
  appserver:
    overrides:
      services:
        volumes:
          - "nfsmount:/app"

compose:
  - compose.yml
```

And my `compose.yml` looks like:

```yml
version: '3'
volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${LANDO_APP_ROOT_BIND}"
```

It seems to work.
Do you see any issue with such configuration?

Thank you for your feedback!

**Comment by dustinleblanc** [comment]
@mmenavas I'd only say that you are in ymmv territory, as you're overriding our standard volume mounts (which are going to be using the defaults for the platform in question), other than that, no specific issues.

I'd be interested in how your performance goes vs the standard volumes though! I am going to close this as you seem to have found a path, but do share your results if it turns out to be a boon for performance!

**Comment by mmenozzi** [comment]
Thank you for your feedback. With this configuration I have faster response time of my application but I didn’t run any benchmark of disk I/O performance. Do you have any suggestions on what tool to use to perform such benchmark?

**Comment by dustinleblanc** [comment]
Hey @mmenavas even just `time curl -I http://mysite.lndo.site` with both methods is probably useful. Same thing when running composer commands, drush commands, etc

**Comment by chill-genomeweb** [comment]
@mmenozzi , yes, this helps a lot. Definitely want to try out this NFS approach soon.
Thank you for doing this!

**Comment by mmenozzi** [comment]
You're welcome @chill-genomeweb.
Note also that the approach described above doesn't work anymore with version `beta.46` because of this commit https://github.com/lando/lando/commit/b2373cfe24112077e825b44ed83713d2128d9309.

As a workaround you can use the following volumes definition for your service:

```yaml
services:
  appserver:
    overrides:
      services:
        volumes:
          - "${LANDO_VOLUME}:/app"
```

But you have to export the `LANDO_VOLUME` env variable to the value `nfsmount` before launching the `lando start` command.

**Comment by dustinleblanc** [comment]
Yeah, NFS seems to be like, 3x faster, if it were a easy to implement reliably solution, maybe we'd want to look more at that

**Comment by tylerssn** [comment]
> But you have to export the `LANDO_VOLUME` env variable to the value nfsmount before launching the lando start command.

@mmenozzi - if I understand you correctly, you are stating that the setup should be:

```yaml
# compose.yml
version: '3'
    my_nfs_mount_name:
        ...
```

```
# .env
LANDO_VOLUME=my_nfs_mount_name
```

```yaml
# .lando.yml
compose:
  # Make nfsmount available
  - ./.lando/services/compose.yml

...

services:
  appserver:
    overrides:
      services:
        volumes:
          # Improve Mac OSX Volume Performance
          - ${LANDO_MOUNT}:/app
```

I have tried your setup (admittedly, without the .env and instead hardcoding the nsfmount name in .lando.yml) but when I inspect the container I see the the host path is `/user/me/project-path/my_nfs_mount_name` rather than using the created volume and assigning the path to `/user/me/project-path`

**Comment by tylerssn** [comment]
@mmenozzi - how are automating the mapping of your user & group IDs from the host to the container in any way?

**Comment by mmenozzi** [comment]
@tylerssn I don't. But I can confirm that the application running inside the container is able to write on the filesystem and a file written by the host is readable from the application as well. I think this is possible due to the `-mapall` option of the `/etc/exports` configuration.

**Comment by tylerssn** [comment]
I can write to files, however, my session save handler checks the Lando user (www-data) ID and compares it with the file owner ID which matches my host user ID. This results in a warning.

Though this is docker/nfs related, it is not Lando related so I will stop congesting this thread.

Thanks for the feedback @mmenozzi !

**Comment by mmenozzi** [comment]
@tylerssn you're welcome.
Note that I defined an additional "normal" volume where my application saves sessions (`var/session`). Like the following:

```yaml
services:
  appserver:
    overrides:
      services:
        volumes:
          - "${LANDO_VOLUME}:/app"
          - "/app/var/session"
```

**Comment by pirog** [comment]
@dustinleblanc if its so much faster maybe Docker for Mac will just ditch `osxfs` and use it. I wonder if that is being discussed at all?

**Comment by dustinleblanc** [comment]
I haven't spied on their conversations enough to know, I have to imagine that such a huge amount of their user base are osx users that this has to be important. The performance hit my MBP takes over my linux tower is 100% completely insane. I never really noticed it until I started using Lando to run big gnarly real projects with, now its like, unbearably slow some days, and I even bought the quadcore 15" mbp to get some extra processing power!

After we hit 3.0 stable, I hope to god I can find some magic to make this better

**Comment by mikenolimits** [comment]
I tried the above on a laravel app, and get the following error:
for sc_appserver_1  Cannot start service appserver: error while mounting volume '/var/lib/docker/volumes/sc_nfsmount/_data': error while mounting volume with options: type='nfs' device=':/Users/michael/Documents/Programming/PhpstormProjects/Lando/sc' o='addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3': permission denied

My lando.yml looks like so 
```
name: sc
recipe: laravel
config:
  webroot: ./public/.
  database: mysql:5.7
  php: '7.2'
  via: nginx
  xdebug: true
services:
  cache:
    type: redis
    persist: true
  appserver:
    overrides:
      services:
        volumes:
          - "${LANDO_VOLUME}:/app"
compose:
  - compose.yml
```

**Comment by tylerssn** [comment]
@mikenolimits - I don't have a solution for you, but just throwing out a warning. I had to abandon this method because, though I got it to work on MacOS, it caused our Linux-using Lando hosts to fail to launch. For the sake of the greater good, if you're using Lando to ensure all devs across all OS' have a simple DevOps workflow, my suggestion is to bounce to Linux or suffer through the MacOS slow-downs.

**Comment by mmenozzi** [comment]
Hi @tylerssn , we managed this by having under version control 2 different `compose.yml` files, one for MacOS and another for Linux:

`compose.yml.macos`:
```yaml
version: '3'
volumes:
  app:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3,fsc,actimeo=2,tcp
      device: ":${LANDO_APP_ROOT_BIND}"
```

`compose.yml.linux`:
```yaml
version: '3'
volumes:
  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${LANDO_APP_ROOT_BIND}"
```

Those files are under version control and the `compose.yml` used by Lando is ignored from version control. So all the developer needs to do is to clone the project's repository and the copy the right compose file in `compose.yml` (`cp compose.yml.linux compose.yml` for Linux and `cp compose.yml.macos compose.yml` for MacOS).

@mikenolimits I never had a "permission denied" error. Could you please share your `compose.yml` file? Did you followed the setup part described [here](https://medium.com/@sean.handley/how-to-set-up-docker-for-mac-with-native-nfs-145151458adc) (especially the `setup_native_nfs_docker_osx.sh ` script)?

**Comment by mikenolimits** [comment]
Thanks -- that seemed to resolve the permission error, but now I get a different error:

ERROR: Named volume "nfsmount:/app:rw" is used in service "appserver" but no declaration was found in the volumes section. 

The version control approach seems pretty solid if this can get working.

**Comment by mmenozzi** [comment]
@mikenolimits I have this error only when I do a `lando poweroff` and I'm not in the directory where the `.lando.yml` file is.
Anyway you didn't share your `compose.yml`...

**Comment by mikenolimits** [comment]
Sorry -- 

It looks like this:
```version: '3'
volumes:
  app:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3,fsc,actimeo=2,tcp
      device: ":${LANDO_APP_ROOT_BIND}" ```

**Comment by osopolar** [comment]
Is the performance improvement using nfs still valid compared to "raw" formatted disk (docker version &ge; 18.06.0-ce-mac70) on macOS &ge; 10.13.4 with APFS enabled?

**Comment by dustinleblanc** [comment]
Probably, raw mode only helps some

**Comment by mmenozzi** [comment]
@osopolar I don't know... I would like to try but I don't know what this "raw" formatted disk is. Do you have a link or anything that explain what it is and it can be used?

@dustinleblanc What do you mean with "raw mode only helps some"?

**Comment by osopolar** [comment]
You may check [Section "Step two: Disk.raw" of the Article "How to get a better disk performance in Docker for Mac"](https://medium.com/@TomKeur/how-get-better-disk-performance-in-docker-for-mac-2ba1244b5b70#4c34) or just try to google for more information.

**Comment by dustinleblanc** [comment]
Its a different disk image format that improves docker filesystem performance, but its by no means a panacea

**Comment by mmenozzi** [comment]
@dustinleblanc why not?
@osopolar thank you

**Comment by brooke-heaton** [comment]
@mmenozzi Could you clarify this one detail of your setup?

```
But you have to export the LANDO_VOLUME env variable to the value nfsmount before launching the lando start command.
```

**Comment by brooke-heaton** [comment]
@mmenozzi are you still using this setup? I noticed that there's now an 'EDIT' on that blog post that reads:

> EDIT: D4M has some filesystem tuning options which achieve a great performance boost. The default option is consistent but if you change it to cached then you shouldn’t need NFS at all for speedup. Thanks Vanya Yani for sharing this info in the comments 🙌

So, does that essentially mean that NFS really isn't worth it for Docker For Mac?

**Comment by mmenozzi** [comment]
@brooke-heaton I don't use this setup anymore. TBH I don't use lando or docker for development on Mac anymore. Too much complexity.

Anyway from what I remember the "cached" filesystem is used by default by lando and switching to NFS gives you the improvement stated here: https://github.com/lando/lando/issues/901#issuecomment-392866288

So I think that it's still worth to have an NFS.

**Comment by hussainweb** [comment]
Just a quick post here for me to document my findings. I have been able to mount the files using NFS but it is not very stable. Once I load a moderately heavy page, the database container crashes. I am not sure if that is a Docker issue itself or something to do with NFS. I do have to restart my Docker daemon once this happens, so I am thinking it is something closer to Docker. I even tried overriding the mount for all my services but that didn't help.

Anyway, I'll keep testing this but I wanted to share one thing that has changed since the original post and the comment in https://github.com/lando/lando/issues/901#issuecomment-395879581. The new override block should be this:

```
services:
  appserver:
    overrides:
      volumes:
        - "${LANDO_VOLUME}:/app"
```

**Comment by pirog** [comment]
@hussainweb awesome! thanks for the trial run. Sad the results were less than stellar but i cant say they are unsurprising. :(

**Comment by jbertoen** [comment]
We run nfs currently on osx with docker, and now issues with it. About database issues though... We do not have a persistent volume to the osx host for that. Just like your composer vendor or node modules directory, it creates pressure on your volume syncing issues. 

We did also test performance, and a site install was sometimes 2 minutes faster on NFS than osxfs. Drush cr also much much faster. I recommend everyone to use nfs as long as docker has issues with them. But just for your custom code. Not for stuff like database data, solr, or whatever.

**Comment by gnuget** [comment]
Recently I moved from DDEV to Lando, and at [DDEV using the NFS integration is supported](https://ddev.readthedocs.io/en/stable/users/performance/#using-nfs-to-mount-the-project-into-the-web-container) so I think it should be possible to use NFS in Lando as well.

This is what it worked for me:

I executed the `setup_native_nfs_docker_osx.sh` script suggested at [this link](https://sean-handley.medium.com/how-to-set-up-docker-for-mac-with-native-nfs-145151458adc), I just replaced `/Users`  to `/System/Volumes/Data/Users` given that this is the new location since I think Catalina.

Then in my `.lando.yml` file I put this at the end of the file:

```
compose:
  - compose.yml

services:
  appserver:
    overrides:
      volumes:
        - "./${LANDO_VOLUME}:/app"
```

And I created the `compose.yml` file with the following content:
```
version: '3'
volumes:
  app:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3,fsc,actimeo=2,tcp
      #device: ":${LANDO_APP_ROOT_BIND}"
      device: ":/Users/myuser/Projects/my-project"
```

The `$LANDO_APP_ROOT_BIND`  returns empty when I tried initially so for my tests I put the full path.

The change in the performance is very promissing:

**Without NFS:**
```
www-data@7a826415c00c:/app$ time drush cr
 [success] Cache rebuild complete.

real	0m19.092s
user	0m4.428s
sys	0m1.301s
www-data@7a826415c00c:/app$ time drush cr
 [success] Cache rebuild complete.

real	0m19.869s
user	0m4.403s
sys	0m1.253s
www-data@7a826415c00c:/app$ time drush cr
 [success] Cache rebuild complete.

real	0m17.494s
user	0m4.551s
sys	0m1.276s
www-data@7a826415c00c:/app$ time drush cr
 [success] Cache rebuild complete.

real	0m18.960s
user	0m4.940s
sys	0m1.556s
www-data@7a826415c00c:/app$ time drush cr
 [success] Cache rebuild complete.

real	0m22.768s
user	0m4.849s
sys	0m1.570s
```

**With NFS**
```
www-data@7a826415c00c:/app$ time drush cr
 [success] Cache rebuild complete.

real	0m10.793s
user	0m3.308s
sys	0m0.985s
www-data@7a826415c00c:/app$ time drush cr
 [success] Cache rebuild complete.

real	0m9.919s
user	0m2.940s
sys	0m0.939s
www-data@7a826415c00c:/app$ time drush cr
 [success] Cache rebuild complete.

real	0m10.060s
user	0m3.027s
sys	0m0.921s
```
I will use it in the following days/weeks to see how stable it is and I will report it. 

David.
