### ISSUE TITLE
Lando Start fails: unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by bsnodgrass** [lando/lando#905]
pre-release v3.0.0-beta.40 
Running Docker Version 18.03.0-ce-mac60 (23751)
Mac OS 10.13.4 (17E199)

Bug Report
==========

**Tell us about your `.lando.yml`**

```yml
name: flexaco
recipe: pantheon
config:
  framework: drupal8
  site: flexaco
  id: 7e7d0925-239c-4554-8ed9-c19b67145210
```
It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

```yml
---
api_version: 1

# PHP Version: 
# https://pantheon.io/docs/pantheon-yml#php-version
# Set site's PHP version to 7.0
php_version: 7.0

# Drush Version
# https://pantheon.io/docs/pantheon-yml/#drush-version
drush_version: 8

# Protected Web Paths
# https://pantheon.io/docs/pantheon-yml#protected-web-paths
protected_web_paths:
  - /CHANGELOG.txt
  - /README.txt

# Quicksilver Platform Integration Hooks
# https://pantheon.io/docs/pantheon-yml#quicksilver
workflows:
  # deploy:
  #   after:
  #     - type: webphp
  #       description: Import configuration from .yml files
  #       script: private/scripts/drush_config_import/drush_config_import.php
  clone_database:
    after:
      - type: webphp
        description: Enable development modules on dev
        script: private/scripts/enable_dev_modules/enable_dev_modules.php
```
**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

```bash
$ lando start
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Pulling proxy (traefik:1.5.4-alpine)...
ERROR: Get https://registry-1.docker.io/v2/library/traefik/manifests/1.5.4-alpine: unauthorized: incorrect username or password
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Pulling proxy (traefik:1.5.4-alpine)...
ERROR: Get https://registry-1.docker.io/v2/library/traefik/manifests/1.5.4-alpine: unauthorized: incorrect username or password
^C

```

Using the command in `verbose` mode. yielded no further info.

**Tell us more**

I get the same results with any of my apps that were running before and I only see the latest 3 of 17 when I do lando list. This app example was not reported in lando list.

*Example:*

```bash
$ lando info
{
  "appserver": {
    "type": "php",
    "version": "7.0",
    "hostnames": [
      "appserver",
      "appserver.flexaco.internal"
    ],
    "via": "nginx:1.8",
    "webroot": ".",
    "config": {
      "server": "/Users/bobsnodgrass/.lando/services/config/pantheon/drupal8.conf",
      "conf": "/Users/bobsnodgrass/.lando/services/config/pantheon/php.ini"
    },
    "urls": []
  },
  "nginx": {
    "type": "nginx",
    "version": "latest",
    "hostnames": [
      "nginx",
      "nginx.flexaco.internal"
    ],
    "webroot": ".",
    "config": {
      "server": "/Users/bobsnodgrass/.lando/services/config/pantheon/drupal8.conf",
      "conf": "/Users/bobsnodgrass/.lando/services/config/pantheon/php.ini"
    },
    "urls": []
  },
  "database": {
    "type": "mariadb",
    "version": "10.0",
    "hostnames": [
      "database",
      "database.flexaco.internal"
    ],
    "creds": {
      "user": "pantheon",
      "password": "pantheon",
      "database": "pantheon"
    },
    "internal_connection": {
      "host": "database",
      "port": 3306
    },
    "external_connection": {
      "host": "localhost",
      "port": true
    },
    "config": {
      "confd": "/Users/bobsnodgrass/.lando/services/config/pantheon/mysql"
    },
    "urls": []
  },
  "cache": {
    "type": "redis",
    "version": "2.8",
    "hostnames": [
      "cache",
      "cache.flexaco.internal"
    ],
    "internal_connection": {
      "host": "cache",
      "port": 6379
    },
    "external_connection": {
      "host": "localhost",
      "port": true
    },
    "urls": []
  },
  "edge": {
    "type": "varnish",
    "version": "4.1",
    "hostnames": [
      "edge",
      "edge.flexaco.internal"
    ],
    "vcl": "/Users/bobsnodgrass/.lando/services/config/pantheon/pantheon.vcl",
    "backends": [
      "nginx"
    ],
    "urls": []
  },
  "index": {
    "type": "solr",
    "version": "custom",
    "hostnames": [
      "index",
      "index.flexaco.internal"
    ],
    "internal_connection": {
      "core": "index1",
      "host": "index",
      "port": 449
    },
    "external_connection": {
      "core": "index1",
      "host": "localhost",
      "port": "not forwarded"
    },
    "urls": []
  },
  "edge_ssl": {
    "urls": [],
    "hostnames": [
      "edge_ssl.flexaco.internal"
    ]
  }
}
```

Does this bug prevent you from using lando?

Yes
