### ISSUE TITLE
Change in PMA version causes access denied

### ISSUE THREAD

**Issue by ronaldmulero** [lando/lando#906]
Bug Report
==========

lando v3.0.0-beta.39 on OSX 10.13.4

As of the morning of April 18, 2018, the following "latest" phpmyadmin setting fails : 
```yml
...
  pma:
    type: phpmyadmin
...
```
Steps to reproduce:
```
1. lando rebuild -y
2. Navigate to phpmyadmin in web browser
3. Access denied: Cannot connect: invalid settings.
```
A temporary solution is to use phpmyadmin version 4.6 instead, like so:
```yml
...
  pma:
    type: phpmyadmin:4.6
...
```
```
1. lando rebuild -y
2. Navigate to phpmyadmin in web browser
3. Works.
```
Maybe it's a bug in latest phpmyadmin:
https://microbadger.com/images/phpmyadmin/phpmyadmin

Could better documentation have prevented this issue? if so what should we change?
No

Does this bug prevent you from using lando?
No
