### ISSUE TITLE
"Waiting until database service is ready..." warn: Service database is unhealthy warn: Run "lando logs -s database"

### ISSUE THREAD

**Issue by MatthieuScarset** [lando/lando#909]
**Before you submit an issue make sure you have [downloaded](https://github.com/lando/lando/releases) the latest version of Lando and checked to see if the latest version resolves your issue!**

Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.
3.  Fill out either the `BUG REPORT` or `FEATURE REQUEST` below.

Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

*Example: v3.0.0-alpha1 on Windows 10 Professional*

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

*Example:*

```yml
name: lamp2
recipe: lamp
config:
  php: '5.6'
  webroot: www
  database: mysql
  xdebug: true
  conf:
    server: config/lamp.conf
    database: config/mysql
    php: config/php.ini
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

*Example:*

```bash
lando init mysite --recipe lamp --webroot web
lando start
# Edited my lando.yml as above
lando rebuild -y
```

**Tell us about the error you got**

Rerun the command that produced your error in `verbose` mode. Paste in the error and the ~100 lines that proceeded it.

*Example:*

```bash
lando CMDTHATFAILED -- -vvvv
```

**Tell us generally about your bug**

*Example: I tried to create a pantheon site but got a `LowerCase` not defined exception*

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

*Example:*

```bash
1. Started up GUI
2. Clicked on my Pantheon account in the sidebar
3. Selected a site and an environment
4. Kept the default create options and pressed submit
```

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Does this bug prevent you from using lando?

Feature Request
===============

Please explain your request and its importance in the form of a user story.

*Example: As a lando user who works with Drupal sites that have large databases, I want the option to exclude unnecessary database tables from being pulled when I update my site because I want faster "site pull" actions.*

Please provide some detail on how lando can help solve this problem

*Example: Place an option on the "site pull" screen to exclude cache tables.*

**Comment by vinmassaro** [comment]
I'm seeing the exact same issue on Lando v3.0.0-beta39 and v3.0.0-beta40 on MacOS 10.13.2 since yesterday as well.

**Comment by wluisi** [comment]
Having the same issue running Mac OS 10.12.6, Docker 18.03.0-ce-mac60, and Lando v3.0.0-beta39

My .lando.yml is pretty generic, using the drupal8 recipe. Was able to fix for now by adding “database: mariadb:10.1” and running lando rebuild. I tried “database: mysql:5.7” but that didn’t fix the issue.

**Comment by vinmassaro** [comment]
Thanks, asserting `database: mariadb:10.1` is working for me now. I did have to run `lando poweroff` to kill everything first before starting lando would get this to work.

**Comment by MatthieuScarset** [comment]
I've tried to fixed this with `database: mariadb: 10.1` but still no luck for me :(

Here's my updated Lando file:
```
name: test
recipe: drupal8
config:
  webroot: docroot
services:
  database:
    type: mariadb:10.1  
  node:
    type: node:6.10
    build:
      - echo "Installation completed!"
tooling:
  npm:
    service: node      
events:
  post-start:
    - echo "Nothing here..."
```

Lando says it started correctly but actually, the app can't talk to the MySQL container:
```
The website encountered an unexpected error. Please try again later.
PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known in Drupal\Component\DependencyInjection\PhpArrayContainer->createService() (line 79 of /app/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php).
```

**Comment by MatthieuScarset** [comment]
What's wrong with the `drupal8` recipe :| :| ??

**Comment by MatthieuScarset** [comment]
I've tried to specify `mysql 5.7` as suggested in this other Bug report #908 
But still no luck...

**Comment by labboy0276** [comment]
@MatthieuScarset You yaml is wrong, it should be:

```yaml
name: test
recipe: drupal8
config:
  webroot: docroot
  database: mariadb:10.1
services:
  node:
    type: node:6.10
    build:
      - echo "Installation completed!"
tooling:
  npm:
    service: node      
events:
  post-start:
    - echo "Nothing here..."
```

**Comment by MatthieuScarset** [comment]
Thanks for your answer @labboy0276 
Unfortunately, still no luck:
```
Pulling appserver (devwithlando/php:7.1-apache)...
Pulling database (mariadb:10.1)...
Pulling node (node:6.10)...
appserver uses an image, skipping
database uses an image, skipping
node uses an image, skipping
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating test_node_1      ... done
Creating test_appserver_1 ... done
Creating test_database_1  ... done
Waiting until database service is ready...
Waiting until appserver service is ready...
Waiting until node service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Nothing here...
```

Then still the same error with `php_network_getaddresses` obviously, as the database container doesnt' work.

**Comment by labboy0276** [comment]
@MatthieuScarset did you do a ```lando rebuild``` ?

**Comment by labboy0276** [comment]
Also, if a rebuild doesn't work, then you need to destroy and recreate the app as per the docs when switching DBs

**Comment by MatthieuScarset** [comment]
Yep, sure thing. I've destroyed and rebuild my Lando app several times. 
I've tried to use `mariadb:10.1` or `mysql:5.7` but still no luck.

**Comment by MatthieuScarset** [comment]
Thanks @dustinleblanc

**Comment by saurabh-vijayvargiya** [comment]
I am getting the same error even after the 
```
database:
    type: mysql:5.7
```
The above code worked for the site with php 5.6 but its not working with php 7.0

**Comment by ronaldmulero** [comment]
Specifying both php version and mysql version fixed it for me too:
```
config:
  webroot: docroot
  php: '7.1'
  database: mysql:5.7
```
