### ISSUE TITLE
Named volume is used in service "proxy" but no declaration was found in the volumes section

### ISSUE THREAD

**Issue by legovaer** [lando/lando#927]
# Bug Report

## Setup
Lando: `v3.0.0-beta.42`
Docker: `Docker version 18.03.1-ce, build 9ee9f40`
OS: `Mac OS High Sierra (with latest updates on)`

*.lando.yml:*

```yml
# Name the application the same as in your .platform.app.yaml.
name: mtdd18
# Use the recipe appropriate for your application.
recipe: drupal8

# The following additional build step will install the Platform CLI
# in the application container.
services:
  appserver:
    build:
      - "curl -sS https://platform.sh/cli/installer | php"

# The following entry creates a `lando platform` command that will run
# any Platform CLI command from inside the container if desired.
tooling:
  cim:
    service: appserver
    description: Import the configuration from the codebase
    cmd:
      - /app/scripts/lando/cim.sh
  cex:
    service: appserver
    description: Export the configuration from the codebase
    cmd:
      - /app/scripts/lando/cex.sh
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd:
      - /var/www/.platformsh/bin/platform
    options:
      passthrough: true
  sync-db:
    service: appserver
    description: Get the database from a Platform.sh environment
    cmd:
      - /app/scripts/lando/swap-db.sh
    options:
      env:
        passthrough: true
        alias:
          - e
        describe: The environment you want to copy the database from.
        interactive:
          type: input
          message: Which environment would you like to copy?
          default: master
          wieght: 600

config:
  # Lando defaults to Apache. Switch to nginx to match Platform.sh.
  via: nginx

  # Set the webroot to match your .platform.app.yaml.
  webroot: web

  # Lando defaults to the latest MySQL release, but Platform.sh uses MariaDB.
  # Specify the version to match what's in services.yaml.
  database: mariadb:10.1
```
## Issue

After updating to the latest version of Lando, now I get an error when executing `lando start`:

`error: Error: Named volume "$LANDO_ENGINE_CONF:/lando:rw" is used in service "proxy" but no declaration was found in the volumes section.` 

Edit1: I went back to version `v3.0.0-beta.40` and now it's working again.
