### ISSUE TITLE
SSL EDGE URL does not work

### ISSUE THREAD

**Issue by drfuzetto** [lando/lando#928]
I want to be able to access site using https but I am getting connection refused.

`lando version
v3.0.0-beta.42`

```
docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true`
```

**Before you submit an issue make sure you have [downloaded](https://github.com/lando/lando/releases) the latest version of Lando and checked to see if the latest version resolves your issue!**

Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already. - DONE
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate. - Could not find anything similar
3.  Fill out either the `BUG REPORT` or `FEATURE REQUEST` below. - DONE

Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**
`lando version
v3.0.0-beta.42`

`macOS High Sierra
Version 10.13.4`

**Tell us about your `.lando.yml`**

```yml
name: markel
recipe: pantheon
config:
  framework: drupal
  site: markel-prod
  id: << hidden >>
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

`pantheon.yml`
```yml
api_version: 1
php_version: 7.0
drush_version: 8

protected_web_paths:
  - /CHANGELOG.txt
  - /COPYRIGHT.txt
  - /INSTALL.mysql.txt
  - /INSTALL.pgsql.txt
  - /INSTALL.sqlite.txt
  - /INSTALL.txt
  - /LICENSE.txt
  - /MAINTAINERS.txt
  - /README.txt
  - /UPGRADE.txt
  - /web.config```
```

**Tell us about the command you were running**

```bash
lando start markel
```

**Tell us about the error you got**

https://markel.lndo.site does not work.

This site can’t be reached
markel.lndo.site refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

Does this bug prevent you from using lando? yes
