### ISSUE TITLE
Passthrough service type

### ISSUE THREAD

**Issue by neclimdul** [lando/lando#933]
It woudl be useful to be able to run arbitrary containers as a service in Lando. For example something not already defined(swagger-ui, some new hotness, etc) or something very specific to an environment contained in a container.

From slack, something like
```
name: myapp
services:
  customservice:
    type: passthrough
	overrides:
	  services:
	     image: image
		 ports:
		   - "8080:80"
```
