### ISSUE TITLE
Feature Request: Support proxy support for directories

### ISSUE THREAD

**Issue by neclimdul** [lando/lando#937]
In a complex environment is possible that some directories are served by a separate system and development might be pretty tightly connected.

An example might be:
```
/ # main site. cms?
/api # some lightweight api platform maybe for headless components.
/docs # swagger or maybe static files.
```

It is documented and quite easy to solve this with subdomains but and this may be a documentation issue but I wasn't able to figure out how to shoehorn it into the HostRegexp traffic syntax.

**Comment by jbertoen** [comment]
This might help:
https://github.com/lando/lando/issues/1024

Another addition would be an easy way to add additional vhosts for nginx and apache. But for nodejs you could use the exposure of multiple ports with this PR.
The online thing you need to add is a set of hosts for a service:
```
proxy:
  node:
    - host.lndo.site // port 80
    - host.lndo.site:3000. // port 3000
services:
  node:
    overrides:
      services:
        node:
          ports:
            - 80
            - 3000
          expose:
            - 80
            - 3000
```
