### ISSUE TITLE
Lando needs hash salt to avoid unexpected error on `lando start` with lando versions 42 and 43

### ISSUE THREAD

**Issue by andreathegiant** [lando/lando#945]
I was able to find a fix for this, but it required creating my own `settings.local.php`. Just detailing out because this didn't come up in previous versions for me. (39 was the one I started with, where I didn't have this error.)

1.  Install lando.
2. Go to URL `lando` start produces, in this case:
``` NAME           decouplingpoc
 LOCATION       /Users/andrea/decoupling-poc
 SERVICES       appserver, nginx, database, cache, edge_ssl, edge, index
 NGINX URLS     https://localhost:32772
                http://localhost:32773
 EDGE URLS      http://localhost:32774
                http://decouplingpoc.lndo.site
                https://decouplingpoc.lndo.site
 EDGE_SSL URLS  https://localhost:32775
```

3. Browser displays error: "This website encountered an unexpected error. Please try again later."

Bug Report
==========
## System Information
* Mac OSX High Sierra 10.13.4.
* Lando version lando-v3.0.0-beta.43.dmg and lando-v3.0.0-beta.42.dmg
* Drupal core 8.5.3
* Pantheon sandbox.

## .lando.yml
```
name: decoupling-poc
recipe: pantheon
config:
  webroot: web
  php: '7.2'
  framework: drupal8
  site: decoupling-poc
  id: d9faf0e6-f3db-445c-bd34-20f1d7ebcb01
    Optionally activate xdebug
    If you are having trouble getting xdebug to work please see:
    https://docs.devwithlando.io/services/php.html#using-xdebug
    xdebug: true

services:
  appserver:
    xdebug: true
    config:
      conf: config/xdebug.ini
    run_as_root:
       - apt-get update
       - apt-get install iputils-ping nmap vim -y
```
## pantheon.yml
```api_version: 1
web_docroot: true
php_version: 7.2
workflows:
  deploy_product:
    after:
      -
        type: webphp
        description: 'Run composer prepare-for-pantheon'
        script: private/scripts/deploy_product/prepare-for-pantheon.php
      -
        type: webphp
        description: 'Run composer install & drupal-scaffold'
        script: private/scripts/deploy_product/composer-install.php
  sync_code:
    after:
      - type: webphp
        description: Push changes back to GitHub if needed
        script: private/scripts/quicksilver/quicksilver-pushback/push-back-to-github.php
```

## Tell us about the command you were running

`lando drush uli`

## Tell us about the error you got

```$ lando drush uli
RuntimeException: Missing $settings['hash_salt'] in settings.php. in /app/web/core/lib/Drupal/Core/Site/Settings.php:146                                                                                                                             [error]
Stack trace:
#0 /app/web/core/lib/Drupal/Core/PhpStorage/PhpStorageFactory.php(43): Drupal\Core\Site\Settings::getHashSalt()
#1 /app/web/core/includes/utility.inc(33): Drupal\Core\PhpStorage\PhpStorageFactory::get('twig')
#2 /app/vendor/drush/drush/commands/core/cache.drush.inc(302): drupal_rebuild(Object(Composer\Autoload\ClassLoader), Object(Symfony\Component\HttpFoundation\Request))
#3 /app/vendor/drush/drush/includes/command.inc(422): drush_cache_rebuild()
#4 /app/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#5 /app/vendor/drush/drush/includes/command.inc(199): drush_command()
#6 /app/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#7 /app/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 /app/vendor/drush/drush/drush.php(12): drush_main()
#9 {main}
```

## Tell us generally about your bug
I noticed this after updating versions, starting Tuesday to 42. Before Tuesday, I was on version 39.

I was able to resolve this by creating a `settings.local.php` file in /web/sites/default/ that reads:
```
<?php

$settings['hash_salt'] = 'c0e81794384491161f1777c232bc6bd9ec38f616560b120fda8e90f383853542';
```

Once this file is in place the app loads, but without it lando doesn't work on install. You might want to resolve this so it's usable from the get-go.

I'm also not a developer, but a site builder, so let me know if I'm misunderstanding who is responsible for a setting like this. Thanks!
