### ISSUE TITLE
Shared database volume

### ISSUE THREAD

**Issue by anthropos9** [lando/lando#950]
I'm not sure if this is a bug report or a feature request or possibly both. I'm trying to have the MySQL files save in a local volume on my machine so that I can backup and save databases. I can do this with docker-compose by setting up a volumes key in the config like this:
```
volumes:
        - ./database:/var/lib/mysql
```

I've tried using the overrides setting in my .lando.yml file (below) for the database, but it doesn't seem to be working. The system starts up fine, but the database volume isn't being shared with the local directory the way it does with docker-compose.  I.e....
```
lando-dbtest2 sdean$ ls lando_config/mysql/
lando-dbtest2 sdean$ lando ssh mcdbtest2 database
www-data@fb0db2b0bab1:/app$ ls /var/lib/mysql
auto.cnf  database  ib_logfile0  ib_logfile1  ibdata1  mysql  performance_schema
```
Not sure if it's something I didn't do right or if it's a limitation of the system, but I'd like to be able to have this work. Thanks.

#### Version
v3.0.0-beta.44 on Mac 10.11.6

#### .lando.yml
```
name: mc-db-test-2
proxy:
  nginx:
    - mc.lndo.site

services:
  appserver:
    type: php:7.0
    via: nginx
    ssl: true
    webroot: html
    xdebug: false
    config:
      server: lando_config/nginx/server.conf
      conf: lando_config/php/php.ini

  database:
    type: mysql:5.6
    portforward: 3334
    overrides:
      services:
        volumes:
          - ./lando_config/mysql:/var/lib/mysql

  cache:
    type: redis:4.0
    portforward: 6382
    persist: true

tooling:
  phplint:
    service: appserver
  composer:
    service: appserver
    description: Run composer commands
    cmd:
      - composer
      - --ansi
  php:
    service: appserver
  mysql:
    user: root
    service: database
    description: Drop into a MySQL shell
```

**Comment by pirog** [comment]
@anthropos9 my guess here is that `./database` is relative to where the docker-compose files live (which on lando is not your app root, its in `~/.lando/compose` so you might want to check in there. 

We recently had a similar issue for users specifying custom Dockerfiles over at #740 so maybe we need to extend this logic so lando is smart enough to detect relative paths and translate them into absolute paths prefixed with the app root. 

What i would do is:

1. See if your database backup ended up somewhere relative to `~/.lando/compose`
2. See if an absolute path works as expected

**Comment by pirog** [comment]
@anthropos9 awesome! now that we can verify that is what is happening we can expand our logic on handling relative path overrides for all the things ;)

**Comment by anthropos9** [comment]
@pirog knowing that allowed me to have it do what I would like:
```
database:
    type: mysql:5.7
    portforward: 3334
    overrides:
      services:
        volumes:
          - $LANDO_APP_ROOT/lando_config/mysql:/var/lib/mysql
```
