### ISSUE TITLE
Tooling commands can't pipe output

### ISSUE THREAD

**Issue by neclimdul** [lando/lando#951]
Bug Report
==========
A closely related problem to #703, because of how tooling commands are run it breaks piping. 
overly simple example:

```yaml
name: landobrokenpipe
recipe: custom
config:
  webroot: .
services:
  test:
    type: node:8
tooling:
  compile:
    service: test
    cmd: cat file1.txt > file2.txt

```

Expected:
```
$ lando compile
```
file2.txt is now a copy of file1.txt

Actual:
```
$ lando compile
cat: >: No such file or directory
cat: file2.txt: No such file or directory
```
File2 doesn't exist.
