### ISSUE TITLE
lando rebuild -s stops all containers and only restarts specified container

### ISSUE THREAD

**Issue by nterbogt** [lando/lando#952]
**Tell us about your setup**

I'm running lando 3.0.0-beta44 with the pantheon recipe on OS X 10.13.4, Docker 18.03.1-ce-mac65 (24312).

**Tell us about your `.lando.yml`**

```yml
name: my-site
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: my-site
  id: my-site
  xdebug: true
services:
  pma:
    type: phpmyadmin
    version: latest
  node:
    type: node:8.4
    globals:
      gulp-cli: "1.4.0"
    build:
      - cd $LANDO_MOUNT && npm install
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
```

**Tell us about the command you were running**

`lando rebuild -s node`

**Tell us generally about your bug**

When I run this command... it shuts down all containers for the site and when they come back up it only restarts node. When I used to run this command in beta39, it would only stop, rebuild and start the service requested.

```
Your app has started up correctly.
Here are some vitals:

 NAME       mysite                                                          
 LOCATION   /Users/nathan/Projects/my-site                           
 SERVICES   appserver, nginx, database, cache, edge_ssl, edge, index, pma, node 
 EDGE URLS  http://mysite.lndo.site                                         
            https://mysite.lndo.site  
```
