### ISSUE TITLE
drush fails not a directory error

### ISSUE THREAD

**Issue by barnettrob** [lando/lando#957]
Bug Report
--------------------------------

Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.
3.  Fill out either the `BUG REPORT` or `FEATURE REQUEST` below.

Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.0.0-beta.44 on OS X High Sierra 

**Tell us about your `.lando.yml`**

```yml
name: edb-d7
recipe: drupal7
config:
  webroot: docroot
  php: 5.6
  drush: global:8.1.15
  database: postgres
services:
  cache:
    type: memcached:1.4
  appserver:
    xdebug: true
    extras:
      - apt-get update
      - apt-get install postgresql-client
    build:
      - touch ~/.pgpass
      - echo  database:5432:drupal7:drupal7:drupal7 > ~/.pgpass
      - chmod 600 ~/.pgpass
      - "mkdir -p ~/.drush/site-aliases"
      - "ln -sf /app/drush/edb.aliases.drushrc.php ~/.drush/site-aliases/edb.drushrc.php"
```

**Tell us about the command you were running**

```
lando drush updb
```
or a custom drush script with drush_backend_batch_process();

**Tell us about the error you got**

```
env: /usr/local/bin/drush/drush: Not a directory
The command could not be executed successfully (returned: env: /usr/local/bin/drush/drush: Not a directory                                                                                                                                           [error]
, code: 126)
Finished.
```

**Tell us generally about your bug**

Many drush commands work fine like drush cc all, drush st, drush dl, drush en, drush dis.
Even my custom drush script runs fine except when I include a call to drush_backend_batch_process()

I have tried to run the problematic drush commands after I ssh into the service (lando ssh) but I get the same error.
