### ISSUE TITLE
Enable apache modules (eg. mod_headers)

### ISSUE THREAD

**Issue by SimonIMG** [lando/lando#976]
Bug Report
==========

**Tell us generally about your bug**
How do I enable apache modules? I've been right through the [apache page](https://docs.devwithlando.io/services/apache.html) and other _Additional Config_ pages but I want to enable `mod_headers` but can't find how to do this (or I'm clearly missing something).

I have entries in my .htaccess file that require the `mod_headers` apache module.

**Tell us about your setup**
3.0.0-beta.45 on Mac OSX Sierra 10.12.6 (ie. _not_ High Sierra)

**Tell us about your `.lando.yml`**
```yml
name: my-wordpress-site
recipe: wordpress
config:
  php: '7.1'
  webroot: .
services:
  database:
    type: mariadb
```

**Tell us about the command you were running**
```bash
lando start
```

**Tell us about the error you got**
```bash
Error 500 - Internal Server Error
```

**Tell us more**
Can we add an example of enabling apache modules in the docs?

**Does this bug prevent you from using lando?**
No. I was able to wrap my .htaccess commands in <IfModule> statements.
```apache
<FilesMatch ".(flv|gif|jpg|jpeg|png|ico|swf)$">
    <IfModule mod_headers.c>
        Header set Cache-Control "max-age=2592000"
    </IfModule>
</FilesMatch>
```
Without those <IfModule> wrappers, I get the 500 error.

**Comment by SimonIMG** [comment]
Thanks for your reply. So I'm updating my .lando.yml with something like the following?

```bash
name: my-wordpress-site
recipe: wordpress
config:
  php: '7.1'
  webroot: .
services:
  database:
    type: mariadb
  appserver:
    run_as_root:
      - "httpd -M |grep header"
```

I'll give it a go and report back.

**Comment by SimonIMG** [comment]
OK, got this working!

```bash
name: my-wordpress-site
recipe: wordpress
config:
  php: '7.1'
  webroot: .
services:
  database:
    type: mariadb
  appserver:
    run_as_root: 'a2enmod headers'
```
I updated the bottom of my .lando.yml - I needed to run the Debian command, rather than the Mac OSX command.

Tested this out on two different Lando instances with different mod_header commands in the .htaccess file and both running fine.

To double check, I added `Header always set X-Content-Type-Options "nosniff"` to my .htaccess file, saved and reloaded the page with Google Dev Tools open on the _Network_ tab. Clicking the _my-wordpress-site.lndo.site_ file in the list, I could see, under the Response Headers on the right-hand side, `x-content-type-options: nosniff`.

Commenting it out and reloading the page, the `x-content-type-options: nosniff` was no longer there.

Thanks for your help @dustinleblanc.

**Comment by dustinleblanc** [comment]
Sweet! Glad that worked 👍

**Comment by SimonIMG** [comment]
Just following up on this with some new findings. I applied this .yml config to a new project and after `lando start` I was prompted to restart apache in the lando app.

I simply followed up with `lando service apache2 restart`. Happy days, everything is working.

So I started trying to update my .lando.yml file with a command that would restart apache for me.

Not much luck so far.

I tried...

```bash
name: img-travel
recipe: wordpress
config:
  php: '7.1'
  webroot: .
services:
  database:
    type: mariadb
  appserver:
    run_as_root:
      - 'a2enmod headers'
      - 'service apache2 restart'
```

After `lando start`, it would say...

```Enabling module headers.
To activate the new configuration, you need to run:
  service apache2 restart
[....] Restarting web server: apache2error: Looks like one of your build steps failed...
```
Also tried the Debian specific command `- 'systemctl restart apache2.service'`

Also tried adding it as an event after `lando start`

```bash
events:
  post-start:
    - appserver: 'service apache2 restart'
```

Still no joy.

Ideally, I'd like the `a2enmod headers` to run only when the lando instance is running for the first time, so it wouldn't give me `Module headers already enabled` each time I run `lando start`.

Does this mean adding it to the `config:` block instead of the `services:` block?

Or should I be doing something globally with lando? It's pretty much every project I need mod_headers so I can configure XSS rules and stuff. A little surprised it's not already on by default in lando (or is that a little naïve).

**Comment by dustinleblanc** [comment]
@SimonIMG part of the problem here is probably that the container can't restart the service that defines the container's run command. That means that apache can't be stopped and restarted because it is the service that keeps the container alive. You may want to actually override and extend our dockerfile to make your changes as I believe you could handle this all in the dockerfile. You can do this with

```yml
services:
  appserver:
    build: ./relative/path/to/dir/container/dockerfile
```
and then in that dockerfile:
```Dockerfile
FROM devwithlando/php:someversionwithapache

RUN a2enmod head
```

Or some such thing like that. I am spitting this out from top of mind, so expect to have to tweak 😉 

Give the above a try

**Comment by ivrh** [comment]
The recommendation by @SimonIMG did not work.

Ended up building my own image based on devwithlando/php with mod_headers added:

```yaml
services:
  appserver:
    overrides:
      services:
        image: ivrh/devwithlando-php
```

**Comment by SimonIMG** [comment]
What didn't work? What was the error? And what's your whole `.lando.yml` file look like before you tried your own image?

I spoke to someone a little later on that used a different command to reload apache (rather than restart). This is what my `.lando.yml` file looks like nowadays...

 ```
name: myproject
recipe: wordpress
config:
  php: '7.1'
  webroot: .
services:
  database:
    type: mariadb
  appserver:
    run_as_root:
      - "a2enmod headers"
      - "service apache2 reload"
```

Maybe try that out? Keen to hear what doesn't work.

**Comment by elliottpost** [comment]
I also needed the Header mod for my app. Here's the approach I took to make it work.  Putting the apache commands in `run_as_root` would cause errors during the start up process and I'd end up with bad gateway error messages as a result when trying to access my app from my browser. I believe it is caused from the lando config not supplying the needed credentials at that moment of restart, but I'm new to lando so I'm not 100% certain. That said, it occurs to me that we didn't need to run `a2enmod headers` _every_ server restart, just once at build, so I moved this section into the `install_dependencies_as_root` section and it worked. Sample below:

```yaml
services:
  appserver:
    composer:
      phpunit/phpunit: '*'

    install_dependencies_as_root:
      - apt-get update -y
      - apt-get install build-essential chrpath libssl-dev libxft-dev libfreetype6-dev libfreetype6 libfontconfig1-dev libfontconfig1 -y
      - apt-get install -my wget gnupg # install node, npm,  and dependencies
      - curl -sL https://deb.nodesource.com/setup_9.x | bash -
      - apt-get install nodejs npm -y
      - a2enmod headers
      - service apache2 restart
    config:
      conf: ./lando-config/php.ini
```

It does generate some warnings about invalid configs at server reboot, but it _did_ solve the issue. It looks like these errors are related to the ones I experienced earlier about `LANDO_XXX` not being available during apache restart, but doing them at install instead of reboot did not prevent the server from running correctly:

```bash
Starting phub_appserver_1 ... done
Enabling module headers.
To activate the new configuration, you need to run:
  service apache2 restart
Killing phub_appserver_1 ... done
Starting phub_appserver_1 ... done
[....] Restarting Apache httpd web server: apache2[Sun Nov 25 18:52:29.535351 2018] [core:warn] [pid 110] AH00111: Config variable ${LANDO_WEBROOT} is not defined
[Sun Nov 25 18:52:29.535471 2018] [core:warn] [pid 110] AH00111: Config variable ${BACKDROP_SETTINGS} is not defined
[Sun Nov 25 18:52:29.535936 2018] [core:warn] [pid 110] AH00111: Config variable ${LANDO_WEBROOT} is not defined
[Sun Nov 25 18:52:29.536663 2018] [core:warn] [pid 110] AH00111: Config variable ${BACKDROP_SETTINGS} is not defined
AH00112: Warning: DocumentRoot [/etc/apache2/${LANDO_WEBROOT}] does not exist
AH00112: Warning: DocumentRoot [/etc/apache2/${LANDO_WEBROOT}] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.3. Set the 'ServerName' directive globally to suppress this message
[Sun Nov 25 18:52:29.571779 2018] [core:warn] [pid 110] AH00111: Config variable ${LANDO_WEBROOT} is not defined
[Sun Nov 25 18:52:29.571856 2018] [core:warn] [pid 110] AH00111: Config variable ${BACKDROP_SETTINGS} is not defined
[Sun Nov 25 18:52:29.572012 2018] [core:warn] [pid 110] AH00111: Config variable ${LANDO_WEBROOT} is not defined
[Sun Nov 25 18:52:29.572645 2018] [core:warn] [pid 110] AH00111: Config variable ${BACKDROP_SETTINGS} is not defined
. ok
Killing phub_appserver_1 ... done
```

CC: @ivrh @SimonIMG

**Comment by michael-wojcik** [comment]
Confirming that adding the following to my `.lando.yml` fixed things for me:
```
appserver:
  install_dependencies_as_root:
    - a2enmod headers
```
Thanks, @elliottpost!!

**Comment by hkirsman** [comment]
Came across this post and wanted to give updated command that worked for me. install_dependencies_as_root isn't correct with the latest Lando https://docs.devwithlando.io/guides/updating-to-rc2.html. Also reload is needed after enabling new mod:

    services:
      appserver:
        build_as_root:
          - a2enmod headers
          - service apache2 reload

**Comment by elliottpost** [comment]
Thanks @hkirsman for the `build_as_root` command -- that's helpful! It's probably not necessary to include the `service apache2 reload` though since the server will automatically reload it after building/starting.

**Comment by josvanderzalm** [comment]
Just did a test, `service apache2 reload` is indeed not necessary .

**Comment by seanr** [comment]
I unfortunately keep hitting this from time to time. We need a permanent workable solution. :/

**Comment by temporarychaos** [comment]
I can confirm that this works (and seems like a permanent workable solution):

```
services:
  appserver:
    build_as_root:
      - a2enmod headers
```
