### ISSUE TITLE
lando drupal site:mode dev is failing

### ISSUE THREAD

**Issue by parijke** [lando/lando#977]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.0.0-beta.45 on Ubuntu Linux 17.10

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.
```
name: drupal-with-twig
recipe: drupal8
config:
  webroot: web
  drush: composer
  xdebug: true
```
**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

lando drupal site:mode dev

**Tell us about the error you got**

[ERROR] Error copying file: /app/web/sites/default/services.yml   

I think it has something to do with the /app/ in the path? This is added by lando I think
