### ISSUE TITLE
Ability to set "pull" command default flags

### ISSUE THREAD

**Issue by amaisano** [lando/lando#982]
Feature Request
===============

Ability to set more sane default flags for the Pantheon `pull` command.

After following the tutorial [here](https://docs.devwithlando.io/config/tooling.html) on overriding the tooling commands in my `.lando.yml` file, I was unable to set the flags I wanted on the `pull` command - they didn't "take."

My attempt (`.lando.yml` file):

```
name: mysite
recipe: pantheon
config:
  framework: drupal8
  site: mysite
  id: <redacted>
tooling:
  pull:
    cmd:
      - "--code=none --rsync"
```

**Comment by pirog** [comment]
@amaisano this should already be possible. i think the issue here is your syntax is wrong. `pull` is a special tooling command that delegates to a script so overriding it is a little more complex. The below configuration seems to work for me on the latest lando

```yaml
  pull:
    options:
      code:
        interactive:
          default: none
      rsync:
        default: true
```

also FWIW the current default we have is what pantheon recommends.
