### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by bianqui149** [lando/lando#992]
I am getting this error "Error establishing a database connection", when I tried to run a wordpress app
This is my lando.yml:
```yml
name: my-lando-app
recipe: wordpress
proxy:
  pma:
    - pma.wordpress.lndo.site
config:
  webroot: .
  via: nginx
  php: '7.0'
  xdebug: true
services:
  pma:
    type: phpmyadmin
    hosts: database
database:
  type: mysql

  portforward: true

  creds:
    user: wordpress
    password: wordpress
    database: wordpress
```

PD: sorry for english.
