### ISSUE TITLE
Priority (weight?) on proxy urls

### ISSUE THREAD

**Issue by MikeWong1991** [lando/lando#997]
In the following set-up with nginx wildcards I experienced a naming collision 

```
proxy:
  nginx:
    - site.localhost
    - '*site.localhost'
  mailhog:
    - mailhog.site.localhost
  solr:
    - solr.site.localhost
  docs:
    - docs.site.localhost
```

It would be nice if we can prioritise the proxy urls by weight for example.
